\. ./FIBI-COI-5.5.2/FC-1274/Procedures/COI_COPY_GLOBAL_ENTITY.sql
\. ./FIBI-COI-5.5.2/FC-1274/Procedures/COI_INT_GET_ENTITY_DETAILS.sql
\. ./FIBI-COI-5.5.2/FC-1274/Procedures/COI_INT_GET_ORGANIZATION_DETAILS.sql
\. ./FIBI-COI-5.5.2/FC-1274/Procedures/COI_INT_GET_SPONSOR_DETAILS.sql
\. ./FIBI-COI-5.5.2/FC-1274/Procedures/GET_ENTITY_TAB_STATUS.sql
\. ./FIBI-COI-5.5.2/FC-1274/Procedures/VALIDATE_ENTITY_MANDATORY_FIELDS.sql
