DELIMITER //
CREATE FUNCTION FN_QRY_REVEWR_DAS_OVRVEW_TRAVEL(
    AV_PERSON_ID VARCHAR(40),
    JSON_INPUT JSON
)
RETURNS TEXT
DETERMINISTIC
BEGIN

DECLARE AV_FETCH_TYPE           VARCHAR(200);
DECLARE JOIN_CONDITION          LONGTEXT;
DECLARE LS_DYN_CTE_SQL          LONGTEXT;
DECLARE LS_DYN_SQL              LONGTEXT;
DECLARE TAB_QUERY               LONGTEXT;
DECLARE LS_FILTER_CONDITION     LONGTEXT;
DECLARE SELECTED_FIELD_LIST     LONGTEXT;
DECLARE LS_GROUP_CONDITION      LONGTEXT;
DECLARE AV_IS_COUNT             BOOLEAN DEFAULT FALSE;
DECLARE AV_LIMIT                INT DEFAULT 10;
DECLARE AV_PAGED                INT DEFAULT 0;
DECLARE AV_UNLIMITED            BOOLEAN DEFAULT FALSE;
DECLARE LS_OFFSET               INT DEFAULT 0;
DECLARE LS_OFFSET_CONDITION     LONGTEXT DEFAULT '';
DECLARE AV_SORT_TYPE            LONGTEXT DEFAULT '';

SET JOIN_CONDITION          = '';
SET LS_DYN_CTE_SQL          = '';
SET LS_DYN_SQL              = '';
SET TAB_QUERY               = '';
SET LS_FILTER_CONDITION     = '';
SET SELECTED_FIELD_LIST     = '';
SET LS_GROUP_CONDITION      = '';

-- Declare all expected JSON fields
SET AV_FETCH_TYPE       = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.FETCH_TYPE'));
SET AV_IS_COUNT         = (JSON_EXTRACT(JSON_INPUT, '$.IS_COUNT') = TRUE);
SET AV_LIMIT            = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT,'$.LIMIT'));
SET AV_PAGED            = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT,'$.PAGED'));
SET AV_UNLIMITED        = (JSON_EXTRACT(JSON_INPUT, '$.IS_UNLIMITED') = TRUE);
SET AV_SORT_TYPE        = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT,'$.SORT_TYPE'));

    SET LS_DYN_CTE_SQL = CONCAT('WITH ACCESS_TMP AS (
        SELECT UNIT_NUMBER
        FROM PERSON_ROLES T1
        INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
        INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
        WHERE T1.DESCEND_FLAG = ''N''
          AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
          AND T3.RIGHT_NAME IN (''MANAGE_TRAVEL_DISCLOSURE'', ''VIEW_TRAVEL_DISCLOSURE'')

        UNION

        SELECT T1.UNIT_NUMBER
        FROM PERSON_ROLES T1
        INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID
        WHERE T2.MODULE_CODE = 24 AND T1.PERSON_ID = ''', AV_PERSON_ID, '''

        UNION

        SELECT CHILD_UNIT_NUMBER
        FROM UNIT_WITH_CHILDREN
        WHERE UNIT_NUMBER IN (
            SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''Y''
              AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
              AND T3.RIGHT_NAME IN (''MANAGE_TRAVEL_DISCLOSURE'', ''VIEW_TRAVEL_DISCLOSURE'')
        )
    )');

    SET LS_FILTER_CONDITION = CONCAT(
        LS_FILTER_CONDITION,
        ' (T1.HOME_UNIT IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
           OR EXISTS (
                SELECT 1
                FROM PERSON_AFFILIATED_UNITS PAU
                WHERE PAU.PERSON_ID = T1.PERSON_ID
                  AND PAU.AFFILIATION_TYPE_CODE = ''1''
                  AND PAU.IS_ACTIVE = ''Y''
                  AND PAU.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS_TMP)
            )
            OR T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID, '''
        ) ', FN_QRY_RVW_DAS_OVRVW_TRAVEL_FIL_COND(AV_PERSON_ID, JSON_INPUT)
    );

    IF AV_FETCH_TYPE = 'HEADER' THEN
        SET SELECTED_FIELD_LIST = CONCAT(
            ' COUNT(DISTINCT CASE WHEN T1.REVIEW_STATUS_CODE IN (2,3) THEN T1.TRAVEL_DISCLOSURE_ID END) AS REVIEW_PENDING_COUNT,
             COUNT(DISTINCT CASE WHEN T1.REVIEW_STATUS_CODE IN (7) THEN T1.TRAVEL_DISCLOSURE_ID END) AS APPROVED_COUNT '
        );
        SET AV_SORT_TYPE = '';
        SET LS_OFFSET_CONDITION = '';
        SET JOIN_CONDITION = '';
    ELSE
        IF AV_IS_COUNT THEN
            SET SELECTED_FIELD_LIST = ' COUNT(DISTINCT T1.TRAVEL_DISCLOSURE_ID) AS TOTAL_COUNT ';
            SET AV_SORT_TYPE = '';
            SET LS_OFFSET_CONDITION = '';
        ELSE
             SET SELECTED_FIELD_LIST = CONCAT(' T1.TRAVEL_DISCLOSURE_ID,
                    T5.UNIT_NUMBER AS UNIT,
                    T5.UNIT_NAME,
                    T5.DISPLAY_NAME,
                    T4.REVIEW_STATUS_CODE,
                    T4.DESCRIPTION AS REVIEW_STATUS,
                    T9.RELATIONSHIP_TYPES AS TRAVELER_TYPE_DESCRIPTION,
                    T2.PRIMARY_NAME AS TRAVEL_ENTITY_NAME,
                    T1.ENTITY_ID,
                    T3.FULL_NAME AS TRAVELLER_NAME,
                    T45.VALUE AS TRAVEL_AMOUNT,
                    T1.EXPIRATION_DATE,
                    T41.VALUE AS PURPOSE_OF_THE_TRIP,
                    T43.VALUE AS TRIP_TITLE,
                    T1.UPDATE_TIMESTAMP,
                    T1.VERSION_STATUS,
                    T1.CREATE_TIMESTAMP,
                    T10.DOCUMENT_STATUS_CODE,
                    T10.DESCRIPTION AS DISPOSITION_STATUS,
                    CASE
                        WHEN TIMESTAMPDIFF(DAY, T1.CREATE_TIMESTAMP, T1.CERTIFIED_AT) > 30 THEN true
                            ELSE false
                    END AS IS_LATE_SUBMISSION,
                    CASE
                        WHEN T1.HOME_UNIT IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) THEN ''HOME_UNIT''
                        WHEN EXISTS (
                            SELECT 1 FROM PERSON_AFFILIATED_UNITS PAU
                            WHERE PAU.PERSON_ID = T1.PERSON_ID
                              AND PAU.AFFILIATION_TYPE_CODE = ''1''
                              AND PAU.IS_ACTIVE = ''Y''
                              AND PAU.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS_TMP)
                        ) THEN ''AFFILIATED_UNIT''
                    END AS UNIT_ACCESS_TYPE,
                    T1.CERTIFIED_AT,
                    T1.ADMIN_PERSON_ID,
                    T1.ADMIN_GROUP_ID,
                    T1.PERSON_ID,
                    T1.TRAVEL_NUMBER,
                    T46.DESCRIPTION AS FUNDING_TYPE,
                    T47.FULL_NAME AS UPDATE_USER_FULL_NAME,
                    T49.MIN_START_DATE AS TRAVEL_START_DATE,
                    T49.MAX_END_DATE AS TRAVEL_END_DATE,
                    T50.TRAVEL_DESTINATIONS,
                    T51.FULL_NAME AS ADMIN_PERSON_NAME,
                    T52.ADMIN_GROUP_NAME,
                    T48.COUNTRY_CODES,
                    T21.DISCLOSURE_TYPES AS ENG_RELATIONSHIPS,
                    FN_DISCLOSURE_TOTAL_COMMENT_COUNT(T1.TRAVEL_DISCLOSURE_ID, ''', AV_PERSON_ID, ''', 24) AS DISCLOSURE_COMMENT_COUNT,'
                    ,FN_QRY_REVWR_DASH_CMN_SELECT_FIELDS('T1.PERSON_ID', 24)
             );
             IF AV_UNLIMITED IS NULL OR  AV_UNLIMITED != TRUE THEN
                 SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
                 SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
             ELSE
                 SET LS_OFFSET_CONDITION = '';
             END IF;

             IF AV_SORT_TYPE IS NOT NULL OR AV_SORT_TYPE <> '' THEN
                 SET AV_SORT_TYPE = CONCAT(' ORDER BY ', AV_SORT_TYPE);
             ELSE
                 SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
             END IF;
        END IF;

        SET LS_GROUP_CONDITION = '';

        SET JOIN_CONDITION = CONCAT('
                LEFT JOIN ENTITY T2 ON T2.ENTITY_ID=T1.ENTITY_ID
                LEFT JOIN COI_TRAVEL_REVIEW_STATUS T4 ON T4.REVIEW_STATUS_CODE=T1.REVIEW_STATUS_CODE
                 LEFT JOIN UNIT T5 ON T5.UNIT_NUMBER = T1.HOME_UNIT
                LEFT JOIN(SELECT T21.TRAVEL_DISCLOSURE_ID, GROUP_CONCAT(DISTINCT T25.DESCRIPTION ORDER BY T25.VALID_PERS_ENTITY_REL_TYP_CODE ASC) AS RELATIONSHIP_TYPES FROM COI_TRAVEL_DISCLOSURE T21
                    LEFT JOIN COI_TRAVEL_DISCLOSURE_TRAVELER T27 ON T27.TRAVEL_DISCLOSURE_ID = T21.TRAVEL_DISCLOSURE_ID
                    LEFT JOIN VALID_PERSON_ENTITY_REL_TYPE T25 ON T25.VALID_PERS_ENTITY_REL_TYP_CODE = T27.VALID_PERS_ENTITY_REL_TYP_CODE
                    GROUP BY T21.TRAVEL_DISCLOSURE_ID)T9 ON T9.TRAVEL_DISCLOSURE_ID = T1.TRAVEL_DISCLOSURE_ID
                LEFT JOIN COI_TRAVEL_DOCUMENT_STATUS_TYPE T10 ON T10.DOCUMENT_STATUS_CODE = T1.DOCUMENT_STATUS_CODE
                LEFT JOIN FB_COMP_CUSTOM_ELEMENT T40 ON T40.CUSTOM_ELEMENT_NAME = "Purpose"
                LEFT JOIN FB_COMP_CUSTOM_ELEMENT_ANSWER T41 ON T41.CUSTOM_DATA_ELEMENTS_ID = T40.CUSTOM_DATA_ELEMENTS_ID AND T41.MODULE_ITEM_CODE = 24 AND T41.MODULE_ITEM_KEY = T1.TRAVEL_DISCLOSURE_ID
                LEFT JOIN FB_COMP_CUSTOM_ELEMENT T42 ON T42.CUSTOM_ELEMENT_NAME = "Trip Title"
                LEFT JOIN FB_COMP_CUSTOM_ELEMENT_ANSWER T43 ON T43.CUSTOM_DATA_ELEMENTS_ID = T42.CUSTOM_DATA_ELEMENTS_ID AND T43.MODULE_ITEM_CODE = 24 AND T43.MODULE_ITEM_KEY = T1.TRAVEL_DISCLOSURE_ID
                LEFT JOIN FB_COMP_CUSTOM_ELEMENT T44 ON T44.CUSTOM_ELEMENT_NAME = "Reimbursed Cost"
                LEFT JOIN FB_COMP_CUSTOM_ELEMENT_ANSWER T45 ON T45.CUSTOM_DATA_ELEMENTS_ID = T44.CUSTOM_DATA_ELEMENTS_ID AND T45.MODULE_ITEM_CODE = 24 AND T45.MODULE_ITEM_KEY = T1.TRAVEL_DISCLOSURE_ID
                LEFT JOIN COI_TRAVEL_FUNDING_TYPE T46 ON T46.FUNDING_TYPE_CODE = T1.FUNDING_TYPE_CODE
                LEFT JOIN (SELECT TRAVEL_DISCLOSURE_ID, GROUP_CONCAT(DISTINCT COUNTRY_CODE ORDER BY COUNTRY_CODE SEPARATOR '','') AS COUNTRY_CODES FROM COI_TRAVEL_DESTINATIONS GROUP BY TRAVEL_DISCLOSURE_ID) T48 ON T48.TRAVEL_DISCLOSURE_ID = T1.TRAVEL_DISCLOSURE_ID
                LEFT JOIN (SELECT TD.TRAVEL_DISCLOSURE_ID, GROUP_CONCAT(C.COUNTRY_NAME SEPARATOR ''||'') AS TRAVEL_DESTINATIONS FROM COI_TRAVEL_DESTINATIONS TD LEFT JOIN COUNTRY C ON C.COUNTRY_CODE = TD.COUNTRY_CODE GROUP BY TD.TRAVEL_DISCLOSURE_ID) T50 ON T50.TRAVEL_DISCLOSURE_ID = T1.TRAVEL_DISCLOSURE_ID
                LEFT JOIN (SELECT TRAVEL_DISCLOSURE_ID, MIN(STAY_START_DATE) AS MIN_START_DATE, MAX(STAY_END_DATE) AS MAX_END_DATE FROM COI_TRAVEL_DESTINATIONS GROUP BY TRAVEL_DISCLOSURE_ID) T49 ON T49.TRAVEL_DISCLOSURE_ID = T1.TRAVEL_DISCLOSURE_ID
                LEFT JOIN PERSON T51 ON T51.PERSON_ID = T1.ADMIN_PERSON_ID
                LEFT JOIN ADMIN_GROUP T52 ON T52.ADMIN_GROUP_ID = T1.ADMIN_GROUP_ID
                LEFT JOIN PERSON T3 ON T3.PERSON_ID=T1.PERSON_ID
                LEFT JOIN PERSON T47 ON T47.PERSON_ID=T1.UPDATED_BY
                LEFT JOIN (
                    SELECT T1.TRAVEL_DISCLOSURE_ID,
                    CONCAT(''['',
                        GROUP_CONCAT(
                            DISTINCT JSON_OBJECT(
                                ''DISCLOSURE_TYPE_CODE'', T3.DISCLOSURE_TYPE_CODE,
                                ''DESCRIPTION'', T3.DESCRIPTION
                            )
                        ),
                    '']'') AS DISCLOSURE_TYPES
                    FROM COI_TRAVEL_DISCLOSURE T1
                    LEFT JOIN PER_ENT_DISCL_TYPE_SELECTION T2 ON T2.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
                    LEFT JOIN COI_DISCLOSURE_TYPE T3 ON T3.DISCLOSURE_TYPE_CODE = T2.DISCLOSURE_TYPE_CODE
                    WHERE T1.VERSION_STATUS = ''ACTIVE''
                    GROUP BY T1.TRAVEL_DISCLOSURE_ID
                ) T21 ON T21.TRAVEL_DISCLOSURE_ID = T1.TRAVEL_DISCLOSURE_ID
        ');
    END IF;

    SET LS_DYN_SQL = CONCAT(LS_DYN_CTE_SQL, ' SELECT * FROM (SELECT ', SELECTED_FIELD_LIST, '
        FROM COI_TRAVEL_DISCLOSURE T1 ', JOIN_CONDITION, ' WHERE ', LS_FILTER_CONDITION, LS_GROUP_CONDITION, LS_OFFSET_CONDITION, ') T ', AV_SORT_TYPE);

    RETURN LS_DYN_SQL;
END
//
