Analyze table REMINDER_NOTIFICATION;
SET @sql1 := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'REMINDER_NOTIFICATION' AND COLUMN_NAME = 'JOB_GROUP') = 0,

    'ALTER TABLE REMINDER_NOTIFICATION ADD COLUMN JOB_GROUP VARCHAR(15);',

    'DO 1'
);

PREPARE stmt FROM @sql1;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET SQL_SAFE_UPDATES = 0;
update reminder_notification set JOB_GROUP = 'coi';
SET SQL_SAFE_UPDATES = 1;
