ALTER TABLE `COI_TRAVEL_FUNDING_AGENCY_TYPE`
CHANGE COLUMN `FUNDING_AGENCY_CODE` `FUNDING_AGENCY_CODE` VARCHAR(6) NOT NULL ;

UPDATE LOOKUP_WINDOW SET DATA_TYPE_CODE = '8' WHERE LOOKUP_WINDOW_NAME = 'Travel Funding Agency';

