DELIMITER //
CREATE PROCEDURE `FCOI_DISCLOSRE_RENEWAL_REMINDER`(AV_DAYS INT)
BEGIN
	SELECT DISTINCT t1.DISCLOSURE_ID AS MODULE_ITEM_KEY, 0 AS SUB_MODULE_ITEM_KEY, 8 AS MODULE_CODE, 0 AS SUB_MODULE_CODE
	FROM COI_DISCLOSURE t1
	INNER JOIN COI_DISCL_PROJECTS t4 ON t4.DISCLOSURE_ID = t1.DISCLOSURE_ID
	INNER JOIN (
		SELECT MODULE_ITEM_KEY, KEY_PERSON_ID, MODULE_CODE
		FROM (
			SELECT PROJECT_NUMBER AS MODULE_ITEM_KEY, KEY_PERSON_ID, STATUS, 1 AS MODULE_CODE
				FROM COI_INT_STAGE_AWARD_PERSON
				WHERE DISCLOSURE_REQUIRED_FLAG IS NOT NULL AND DISCLOSURE_REQUIRED_FLAG <> 'NOT_REQUIRED'
			UNION ALL
			SELECT PROPOSAL_NUMBER AS MODULE_ITEM_KEY, KEY_PERSON_ID, STATUS, 3 AS MODULE_CODE
				FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
				WHERE DISCLOSURE_REQUIRED_FLAG IS NOT NULL AND DISCLOSURE_REQUIRED_FLAG <> 'NOT_REQUIRED'
		) s
		WHERE s.STATUS = 'A'
		GROUP BY MODULE_ITEM_KEY, KEY_PERSON_ID
	) t5 ON t5.MODULE_CODE = t4.MODULE_CODE AND t5.MODULE_ITEM_KEY = t4.MODULE_ITEM_KEY AND t5.KEY_PERSON_ID = t1.PERSON_ID
	WHERE t1.FCOI_TYPE_CODE != 2
	AND t1.VERSION_STATUS = 'ACTIVE'
	AND DATE(EXPIRATION_DATE) = DATE(DATE_ADD(utc_timestamp(),INTERVAL AV_DAYS DAY))
	AND (
		NOT EXISTS (
			SELECT 1
			FROM COI_DISCL_PROJECTS CD
			JOIN COI_DISCLOSURE T2 ON CD.DISCLOSURE_ID = T2.DISCLOSURE_ID AND T2.PERSON_ID = t1.PERSON_ID
			WHERE CD.MODULE_ITEM_KEY = t4.MODULE_ITEM_KEY
		)
		OR EXISTS (
			SELECT 1
			FROM COI_DISCL_PROJECTS CD
			JOIN COI_DISCLOSURE T2 ON CD.DISCLOSURE_ID = T2.DISCLOSURE_ID AND T2.PERSON_ID = t1.PERSON_ID
			WHERE CD.MODULE_ITEM_KEY = t4.MODULE_ITEM_KEY AND T2.REVIEW_STATUS_CODE IN (1, 9, 10)
		)
	)
	AND t1.DISCLOSURE_ID = (
        SELECT MAX(DISCLOSURE_ID)
            FROM COI_DISCLOSURE CD
            WHERE CD.DISCLOSURE_NUMBER = t1.DISCLOSURE_NUMBER
            AND CD.REVIEW_STATUS_CODE NOT IN (1, 5, 6)
    );
END
//
