INSERT INTO rights (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A)
 , 'MANAGE_TRAINING_ACTIONS', 'To view and manage actions column in Person training', 'quickstart', now(), '1');
