-- DROP PROCEDURE IF EXISTS CALL_REST_API;
-- DROP PROCEDURE IF EXISTS FIBI_COI_GET_DEV_PROP_DTLS;
-- DROP PROCEDURE IF EXISTS FIBI_COI_GET_DEV_PROP_NUM;

-- DROP PROCEDURE IF EXISTS FIBI_COI_GET_DEV_PROP_PER_DTLS;
-- DROP PROCEDURE IF EXISTS FIBI_COI_GET_DEV_PROP_QNR_DTLS;


