-- Drop the table if it already exists (optional, for setup purposes)
DROP TABLE INTEGRATION_EXCEPTION_LOG;
DROP SEQUENCE INTEGRATION_EXCEPTION_LOG_SEQ;

CREATE SEQUENCE INTEGRATION_EXCEPTION_LOG_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Create the table with the IDENTITY column
CREATE TABLE INTEGRATION_EXCEPTION_LOG (
    ID NUMBER PRIMARY KEY,
    EXCEPTION_TYPE VARCHAR2(255),
    EXCEPTION_MESSAGE CLOB,
    STACK_TRACE CLOB,
    URL VARCHAR2(255),
    REQUEST_OBJ CLOB,
    CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
