
UPDATE dyn_section_config SET DESCRIPTION = 'Entity Overview' WHERE (SECTION_CODE = 'GE2601');

INSERT INTO `DISCLOSURE_ACTION_TYPE` (`ACTION_TYPE_CODE`, `MESSAGE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES ('31', 'Disclosure Synced', 'Disclosure Synced', now(), 'quickstart');

INSERT INTO notification_type(NOTIFICATION_TYPE_ID,MODULE_CODE,SUB_MODULE_CODE,DESCRIPTION,SUBJECT,MESSAGE,PROMPT_USER,IS_ACTIVE,CREATE_USER,CREATE_TIMESTAMP,UPDATE_USER,UPDATE_TIMESTAMP) VALUES(8014,8,0,"Notify Incomplete Disclosure","Action required: Disclosure Submission Request","<p>Dear {COI_DISCL_PROJECT#REPORTER_NAME},</p> <p>We kindly request you to complete and submit your disclosure for the following:</p> <p><strong>Project:</strong> {COI_DISCL_PROJECT#PROJECT_ID} - {COI_DISCL_PROJECT#PROJECT_TITLE}</p> <p><strong>Disclosure Status:</strong> {COI_DISCL_PROJECT#DISCLOSURE_STATUS}</p> <p><br /><span >Please login to COI and access your disclosure at {APPLICATION_URL} to complete and submit your disclosure.</span></p> <p>&nbsp;</p>","Y","Y","quickstart",now(),"ADMIN",now());

INSERT INTO module_action_type(MODULE_ACTION_TYPE_ID,ACTION_TYPE,MODULE_CODE,SUB_MODULE_CODE,IS_ACTIVE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES(23,"PROJECT_NOTIFY",8,0,"Y","Notify Incomplete ProjectDisclosure",now(),"ADMIN");
INSERT INTO notify_action_type_map(NOTIFICATION_TYPE_ID,MODULE_ACTION_TYPE_ID,UPDATE_TIMESTAMP, UPDATE_USER)VALUES(8014,23,now(), "quickstart");


INSERT INTO mq_router_action_configuration(ACTION_TYPE,IS_ACTIVE,MODULE_CODE,QUEUE_NAME,SUB_MODULE_CODE,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES("PROJECT_NOTIFY","Y",8,"Q_NOTIFICATION",0,now(),"quickstart");

INSERT INTO notify_placeholder_header(NOTIFY_PLACEHOLDER_HEADER_ID,MODULE_CODE,SUB_MODULE_CODE,QUERY_TYPE,ELEMENT_TYPE,IS_ACTIVE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,UNIQUE_DISPLAY_NAME)
VALUES(4,8,0,"S","S","Y","Project placeholder",NOW(),"will Smith","COI_DISCL_PROJECT");

INSERT INTO notify_placeholder_columns(NOTIFY_PLACEHOLDER_HEADER_ID,QUERY_COLUMN_NAME,LABEL_NAME,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES(4,"PROJECT_ID","PROJECT_ID",now(),"Will Smith");
INSERT INTO notify_placeholder_columns(NOTIFY_PLACEHOLDER_HEADER_ID,QUERY_COLUMN_NAME,LABEL_NAME,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES(4,"PROJECT_TITLE","PROJECT_TITLE",now(),"Will Smith");
INSERT INTO notify_placeholder_columns(NOTIFY_PLACEHOLDER_HEADER_ID,QUERY_COLUMN_NAME,LABEL_NAME,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES(4,"DISCLOSURE_STATUS","DISCLOSURE_STATUS",now(),"Will Smith");
INSERT INTO notify_placeholder_columns(NOTIFY_PLACEHOLDER_HEADER_ID,QUERY_COLUMN_NAME,LABEL_NAME,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES(4,"REPORTER_NAME","REPORTER_NAME",now(),"Will Smith");


ALTER TABLE entity 
CHANGE COLUMN START_DATE START_DATE VARCHAR(10) NULL DEFAULT NULL ,
CHANGE COLUMN INCORPORATION_DATE INCORPORATION_DATE VARCHAR(10) NULL DEFAULT NULL ;


ALTER TABLE entity_telephone 
MODIFY COLUMN TELEPHONE_NUMBER BIGINT;

ALTER TABLE industry_category_code CHANGE COLUMN INDUSTRY_CATEGORY_ID INDUSTRY_CATEGORY_ID INT NOT NULL AUTO_INCREMENT ;

DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1643');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1583');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1584');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1622');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1603');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1604');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1605');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1625');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1626');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1612');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1628');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1629');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1613');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1614');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1615');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1630');
DELETE FROM dyn_element_config WHERE (ELEMENT_ID = '1631');

