DELIMITER //
CREATE PROCEDURE `GET_OPA_DISCL_PERSON_ENTITY_REL`(IN AV_DISCLOSURE_ID INT, IN AV_PERSON_ID VARCHAR(40))
BEGIN
DECLARE LS_PERSON_ID VARCHAR(40);

    SELECT PERSON_ID INTO LS_PERSON_ID
    FROM OPA_DISCLOSURE
    WHERE OPA_DISCLOSURE_ID = AV_DISCLOSURE_ID;

    WITH PERSON_ENTITIES AS (
    SELECT 
      PERSON_ENTITY_ID, 
      PERSON_ENTITY_NUMBER,
      PERSON_ID, 
      ENTITY_ID, 
      INVOLVEMENT_START_DATE, 
      INVOLVEMENT_END_DATE, 
      ENTITY_NAME, 
      IS_COMPENSATED, 
      RELATIONSHIPS, 
      INVOLVEMENT_OF_STUDENTS, 
      INVOLVEMENT_OF_STAFF, 
      USE_OF_MIT_RESOURCES, 
      SABBATICAL_TYPE, 
      OPA_PERSON_ENTITY_REL_ID
    FROM 
      OPA_DISCL_PERSON_ENTITY_REL
    WHERE 
      DISCLOSURE_ID = AV_DISCLOSURE_ID
      AND PERSON_ID = LS_PERSON_ID
  ),
  PERSON_ENTITY_DELETE_ELIGIBILITY AS (
    SELECT 
      T1.PERSON_ENTITY_ID,
      CASE 
          WHEN T5.PERSON_ENTITY_ID IS NOT NULL 
               OR T1.VERSION_NUMBER > 1 
          THEN FALSE 
          ELSE TRUE 
      END AS CAN_DELETE
    FROM PERSON_ENTITY T1
    LEFT JOIN (
        SELECT T1.PERSON_ENTITY_ID 
        FROM PERSON_ENTITY T1
        INNER JOIN COI_DISCL_PROJECT_ENTITY_REL T2 ON T2.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
        UNION
        SELECT T1.PERSON_ENTITY_ID 
        FROM PERSON_ENTITY T1
        INNER JOIN COI_DISCL_PERSON_ENTITY_REL T2 ON T2.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
        UNION
        SELECT T1.PERSON_ENTITY_ID 
        FROM PERSON_ENTITY T1
        INNER JOIN OPA_DISCL_PERSON_ENTITY T2 ON T2.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
        UNION
        SELECT T1.PERSON_ENTITY_ID 
        FROM PERSON_ENTITY T1
        INNER JOIN CONSULTING_DISCLOSURE T2 ON T2.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
        UNION
        SELECT T1.PERSON_ENTITY_ID 
        FROM PERSON_ENTITY T1
        INNER JOIN COI_TRAVEL_DISCLOSURE T2 ON T2.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
    ) T5 ON T5.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
    INNER JOIN ENTITY T2 ON T2.ENTITY_NUMBER = T1.ENTITY_NUMBER AND T2.VERSION_STATUS = 'ACTIVE'
    WHERE 
      T1.PERSON_ID = AV_PERSON_ID 
      AND T1.VERSION_STATUS != 'ARCHIVE'
  )
  SELECT 
    A.PERSON_ENTITY_ID, 
    A.PERSON_ENTITY_NUMBER,
    A.PERSON_ID, 
    A.ENTITY_ID, 
    A.INVOLVEMENT_START_DATE, 
    A.INVOLVEMENT_END_DATE, 
    A.ENTITY_NAME, 
    A.IS_COMPENSATED, 
    A.RELATIONSHIPS, 
    A.INVOLVEMENT_OF_STUDENTS, 
    A.INVOLVEMENT_OF_STAFF, 
    A.USE_OF_MIT_RESOURCES, 
    A.SABBATICAL_TYPE, 
    A.OPA_PERSON_ENTITY_REL_ID,
    IFNULL(B.CAN_DELETE, FALSE) AS CAN_DELETE,
    PE.VERSION_STATUS,
    PE.IS_FORM_COMPLETED,
    E.IS_FOREIGN
  FROM PERSON_ENTITIES A
  LEFT JOIN PERSON_ENTITY_DELETE_ELIGIBILITY B ON A.PERSON_ENTITY_ID = B.PERSON_ENTITY_ID
LEFT JOIN PERSON_ENTITY PE ON A.PERSON_ENTITY_ID = PE.PERSON_ENTITY_ID
LEFT JOIN ENTITY E ON A.ENTITY_ID = E.ENTITY_ID;
END
//
