DELIMITER //
CREATE PROCEDURE `SYNC_OPA_DISCL_PERSON_ENTITY_REL`(IN AV_DISCLOSURE_ID INT, IN AV_PERSON_ID VARCHAR(40))
BEGIN
   DECLARE LI_REVIEW_STATUS_CODE INT;

    SELECT REVIEW_STATUS_CODE 
    INTO LI_REVIEW_STATUS_CODE
    FROM OPA_DISCLOSURE
    WHERE OPA_DISCLOSURE_ID = AV_DISCLOSURE_ID;

    IF LI_REVIEW_STATUS_CODE IN (1, 5, 6) THEN

        INSERT INTO OPA_DISCL_PERSON_ENTITY_REL (
            DISCLOSURE_ID,
            PERSON_ENTITY_ID,
            PERSON_ENTITY_NUMBER,
            PERSON_ID,
            ENTITY_ID,
            INVOLVEMENT_START_DATE,
            INVOLVEMENT_END_DATE,
            ENTITY_NAME,
            IS_COMPENSATED,
            RELATIONSHIPS,
            INVOLVEMENT_OF_STUDENTS,
            INVOLVEMENT_OF_STAFF,
            USE_OF_MIT_RESOURCES,
            UPDATE_USER,
            UPDATE_TIMESTAMP
        )
        SELECT 
            AV_DISCLOSURE_ID, 
            T.PERSON_ENTITY_ID,
            T.PERSON_ENTITY_NUMBER,
            T.PERSON_ID,
            T.ENTITY_ID,
            T.INVOLVEMENT_START_DATE,
            T.INVOLVEMENT_END_DATE,
            T.ENTITY_NAME,
            T.IS_COMPENSATED,
            T.RELATIONSHIPS,
            T.INVOLVEMENT_OF_STUDENTS,
            T.INVOLVEMENT_OF_STAFF,
            T.USE_OF_MIT_RESOURCES,
            T.USER_NAME,
            NOW()
        FROM (
            WITH ACTIVE_ENTITIES AS (
                SELECT ENTITY_NUMBER, PRIMARY_NAME
                FROM ENTITY
                WHERE VERSION_STATUS = 'ACTIVE'
            ),
            PERSON_ENTITIES AS (
                SELECT 
                    T1.PERSON_ENTITY_ID,
                    T1.PERSON_ENTITY_NUMBER,
                    T1.PERSON_ID,
                    T1.ENTITY_ID,
                    T1.INVOLVEMENT_START_DATE,
                    T1.INVOLVEMENT_END_DATE,
                    T2.PRIMARY_NAME AS ENTITY_NAME,
                    T1.IS_COMPENSATED,
                    GROUP_CONCAT(DISTINCT T4.DESCRIPTION ORDER BY T4.DESCRIPTION SEPARATOR ', ') AS RELATIONSHIPS
                FROM PERSON_ENTITY T1
                INNER JOIN ACTIVE_ENTITIES T2 ON T2.ENTITY_NUMBER = T1.ENTITY_NUMBER
                LEFT JOIN PER_ENT_DISCL_TYPE_SELECTION T3 ON T3.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
                LEFT JOIN COI_DISCLOSURE_TYPE T4 ON T4.DISCLOSURE_TYPE_CODE = T3.DISCLOSURE_TYPE_CODE
                WHERE T1.VERSION_STATUS NOT IN ('ARCHIVE', 'CANCELLED')
                  AND T1.PERSON_ID = AV_PERSON_ID
                GROUP BY 
                    T1.PERSON_ENTITY_NUMBER
                HAVING T1.PERSON_ENTITY_ID = (
                    SELECT MAX(T2.PERSON_ENTITY_ID)
                    FROM PERSON_ENTITY T2
                    WHERE T2.PERSON_ENTITY_NUMBER = T1.PERSON_ENTITY_NUMBER
                      AND T2.PERSON_ID = T1.PERSON_ID
                )
                ORDER BY T1.UPDATE_TIMESTAMP DESC
            ),
            PERSON_ENTITY_QN_ANSWERS AS (
                SELECT 
                    E.PERSON_ENTITY_ID,
                    MAX(CASE WHEN E.QUESTION = 'INVOLVEMENT OF STUDENTS' THEN E.ANSWER END) AS INVOLVEMENT_OF_STUDENTS,
                    MAX(CASE WHEN E.QUESTION = 'INVOLVEMENT OF STAFF OR SUBORDINATES' THEN E.ANSWER END) AS INVOLVEMENT_OF_STAFF,
                    MAX(CASE WHEN E.QUESTION = 'USE OF MIT RESOURCES INCLUDING ANY FEE FOR SERVICE FACILITIES (NANO, KOCH IMAGING, ETC.)' THEN E.ANSWER END) AS USE_OF_MIT_RESOURCES
                FROM (
                    SELECT 
                        T2.MODULE_ITEM_KEY AS PERSON_ENTITY_ID,
                        T1.ANSWER,
                        T4.QUESTION,
                        ROW_NUMBER() OVER (PARTITION BY T2.MODULE_ITEM_KEY, T4.QUESTION ORDER BY T1.UPDATE_TIMESTAMP DESC) AS RN
                    FROM FB_QUEST_ANSWER T1
                    INNER JOIN FB_QUEST_ANSWER_HEADER T2 
                        ON T1.QUESTIONNAIRE_ANS_HEADER_ID = T2.QUESTIONNAIRE_ANS_HEADER_ID
                    INNER JOIN QUEST_QUESTION T4 
                        ON T1.QUESTION_ID = T4.QUESTION_ID
                    WHERE T2.MODULE_ITEM_CODE = 8
                      AND T2.MODULE_SUB_ITEM_CODE = 801
                      AND T2.MODULE_ITEM_KEY IN (SELECT PERSON_ENTITY_ID FROM PERSON_ENTITIES)
                      AND T2.MODULE_SUB_ITEM_KEY = 3122
                      AND T4.QUESTIONNAIRE_ID = 1157
                      AND T4.QUESTION IN (
                          'INVOLVEMENT OF STUDENTS', 
                          'INVOLVEMENT OF STAFF OR SUBORDINATES', 
                          'USE OF MIT RESOURCES INCLUDING ANY FEE FOR SERVICE FACILITIES (NANO, KOCH IMAGING, ETC.)'
                      )
                ) E
                WHERE E.RN = 1
                GROUP BY E.PERSON_ENTITY_ID
            )
            SELECT 
                PE.PERSON_ENTITY_ID,
                PE.PERSON_ENTITY_NUMBER,
                PE.PERSON_ID,
                PE.ENTITY_ID,
                PE.INVOLVEMENT_START_DATE,
                PE.INVOLVEMENT_END_DATE,
                PE.ENTITY_NAME,
                PE.IS_COMPENSATED,
                PE.RELATIONSHIPS,
                EA.INVOLVEMENT_OF_STUDENTS,
                EA.INVOLVEMENT_OF_STAFF,
                EA.USE_OF_MIT_RESOURCES,
                P.USER_NAME
            FROM PERSON_ENTITIES PE
            LEFT JOIN PERSON_ENTITY_QN_ANSWERS EA ON PE.PERSON_ENTITY_ID = EA.PERSON_ENTITY_ID
            LEFT JOIN PERSON P ON PE.PERSON_ID = P.PERSON_ID
            ORDER BY PE.PERSON_ENTITY_ID
        ) T
        ON DUPLICATE KEY UPDATE 
            PERSON_ENTITY_ID = VALUES(PERSON_ENTITY_ID),
            PERSON_ENTITY_NUMBER = VALUES(PERSON_ENTITY_NUMBER),
            ENTITY_ID = VALUES(ENTITY_ID),
            INVOLVEMENT_START_DATE = VALUES(INVOLVEMENT_START_DATE),
            INVOLVEMENT_END_DATE = VALUES(INVOLVEMENT_END_DATE),
            ENTITY_NAME = VALUES(ENTITY_NAME),
            IS_COMPENSATED = VALUES(IS_COMPENSATED),
            RELATIONSHIPS = VALUES(RELATIONSHIPS),
            INVOLVEMENT_OF_STUDENTS = VALUES(INVOLVEMENT_OF_STUDENTS),
            INVOLVEMENT_OF_STAFF = VALUES(INVOLVEMENT_OF_STAFF),
            USE_OF_MIT_RESOURCES = VALUES(USE_OF_MIT_RESOURCES),
            UPDATE_USER = VALUES(UPDATE_USER),
            UPDATE_TIMESTAMP = NOW();

    END IF;
END
//
