DROP PROCEDURE IF EXISTS COI_EVALUATE_VALIDATION_MESSAGE;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_FUNCTION;

DROP FUNCTION IF EXISTS FN_CHK_ACTV_SFI_NOT_SYNC;
DROP FUNCTION IF EXISTS FN_CHK_ENGAGEMENT_IS_MOD;
DROP FUNCTION IF EXISTS FN_CHK_ENTY_IS_MODIFIED;
DROP FUNCTION IF EXISTS FN_CHK_INACTV_ENTITY;
DROP FUNCTION IF EXISTS FN_CHK_INCMPLTE_ENAGMNT;
DROP FUNCTION IF EXISTS FN_CHK_PERSON_HAS_ENGEMNT;
DROP FUNCTION IF EXISTS FN_CHK_SFI_IS_DEFIND;
