CREATE TABLE IF NOT EXISTS AFFILIATION_TYPE (
  AFFILIATION_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(500) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(40) DEFAULT NULL,
  PRIMARY KEY (AFFILIATION_TYPE_CODE)
);

SELECT CHARACTER_SET_NAME, COLLATION_NAME
INTO @person_charset, @person_collation
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'person'
  AND COLUMN_NAME = 'PERSON_ID';

SELECT CHARACTER_SET_NAME, COLLATION_NAME
INTO @unit_charset, @unit_collation
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'unit'
  AND COLUMN_NAME = 'UNIT_NUMBER';

SELECT CHARACTER_SET_NAME, COLLATION_NAME
INTO @affil_charset, @affil_collation
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'affiliation_type'
  AND COLUMN_NAME = 'AFFILIATION_TYPE_CODE';

SET @create_table_sql = CONCAT('
CREATE TABLE IF NOT EXISTS person_affiliated_units (
  PERSON_AFFILIATED_UNIT_ID INT NOT NULL AUTO_INCREMENT,
  PERSON_ID VARCHAR(40) CHARACTER SET ', @person_charset, ' COLLATE ', @person_collation, ' NOT NULL,
  UNIT_NUMBER VARCHAR(50) CHARACTER SET ', @unit_charset, ' COLLATE ', @unit_collation, ' NOT NULL,
  AFFILIATION_TYPE_CODE VARCHAR(3) CHARACTER SET ', @affil_charset, ' COLLATE ', @affil_collation, ' NOT NULL,
  AFFILIATION_START_DATE DATE DEFAULT NULL,
  AFFILIATION_END_DATE DATE DEFAULT NULL,
  DESCRIPTION varchar(500) DEFAULT NULL,
  IS_ACTIVE VARCHAR(1) DEFAULT NULL,
  UPDATED_BY VARCHAR(40) DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  PRIMARY KEY (PERSON_AFFILIATED_UNIT_ID),
  KEY PERSON_AFFILIATED_UNITS_IDX1 (PERSON_ID),
  KEY PERSON_AFFILIATED_UNITS_IDX2 (UNIT_NUMBER),
  CONSTRAINT PERSON_AFFILIATED_UNITS_FK1 FOREIGN KEY (PERSON_ID) REFERENCES person(PERSON_ID),
  CONSTRAINT PERSON_AFFILIATED_UNITS_FK2 FOREIGN KEY (UNIT_NUMBER) REFERENCES unit(UNIT_NUMBER),
  CONSTRAINT PERSON_AFFILIATED_UNITS_FK3 FOREIGN KEY (AFFILIATION_TYPE_CODE) REFERENCES affiliation_type(AFFILIATION_TYPE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
');

PREPARE stmt FROM @create_table_sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
