INSERT INTO AFFILIATION_TYPE
(AFFILIATION_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
SELECT '1', 'Departmental Affiliation', 'Y', UTC_TIMESTAMP(), 'admin'
WHERE NOT EXISTS (
    SELECT 1
    FROM AFFILIATION_TYPE
    WHERE AFFILIATION_TYPE_CODE = '1'
);

INSERT INTO RIGHTS
(RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
SELECT COALESCE(MAX(RIGHT_ID), 0) + 1, 
       'MAINTAIN_DISCLOSURES_FROM_AFFILIATED_UNITS', 
       'To maintain disclosures from affiliated units', 
       'admin', UTC_TIMESTAMP(), '1'
FROM RIGHTS
WHERE NOT EXISTS (
    SELECT 1
    FROM RIGHTS
    WHERE RIGHT_NAME = 'MAINTAIN_DISCLOSURES_FROM_AFFILIATED_UNITS'
);

INSERT INTO RIGHTS
(RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
SELECT COALESCE(MAX(RIGHT_ID), 0) + 1, 
       'MAINTAIN_AFFILIATED_UNITS', 
       'To maintain affiliated units of a person', 
       'admin', UTC_TIMESTAMP(), '1'
FROM RIGHTS
WHERE NOT EXISTS (
    SELECT 1
    FROM RIGHTS
    WHERE RIGHT_NAME = 'MAINTAIN_AFFILIATED_UNITS'
);
