INSERT INTO RIGHTS(RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
VALUES((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A),'VIEW_DISCLOSURE_NOTES', 'To view disclosure notes', 'quickstart', now(),1);

INSERT INTO RIGHTS(RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
VALUES((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A),'MANAGE_DISCLOSURE_NOTES', 'To manage disclosure notes', 'quickstart', now(),1);