
SET SQL_SAFE_UPDATES=0;
UPDATE `COI_INT_STAGE_DEV_PROPOSAL_PERSON` SET `ATTRIBUTE_1_LABEL` = 'NON_EMPLOYEE_FLAG', ATTRIBUTE_1_VALUE = 'N' WHERE ATTRIBUTE_1_LABEL IS NULL AND ATTRIBUTE_1_VALUE IS NULL ;
UPDATE `COI_INT_STAGE_PROPOSAL_PERSON` SET `ATTRIBUTE_1_LABEL` = 'NON_EMPLOYEE_FLAG', ATTRIBUTE_1_VALUE = 'N' WHERE ATTRIBUTE_1_LABEL IS NULL AND ATTRIBUTE_1_VALUE IS NULL ;
UPDATE `COI_INT_STAGE_AWARD_PERSON` SET `ATTRIBUTE_1_LABEL` = 'NON_EMPLOYEE_FLAG', ATTRIBUTE_1_VALUE = 'N' WHERE ATTRIBUTE_1_LABEL IS NULL AND ATTRIBUTE_1_VALUE IS NULL ;
SET SQL_SAFE_UPDATES=1;
-- fibi related scripts
ALTER TABLE ROLODEX ADD COLUMN COUNTRY_OF_CITIZENSHIP VARCHAR(30) AFTER COUNTRY_CODE;
ALTER TABLE ROLODEX ADD INDEX ROLODEX_COUNTRY_FK1_idx (COUNTRY_OF_CITIZENSHIP ASC) VISIBLE;
ALTER TABLE ROLODEX ADD CONSTRAINT ROLODEX_COUNTRY_FK1 FOREIGN KEY (COUNTRY_OF_CITIZENSHIP) REFERENCES country (COUNTRY_CODE);
ALTER TABLE ROLODEX RENAME COLUMN ACTV_IND TO IS_ACTIVE;
ALTER TABLE `sponsor` ADD COLUMN `ROR_ID` VARCHAR(50) DEFAULT NULL;
