DROP PROCEDURE IF EXISTS INSERT_WORKFLOW_ALTER_APPROVER;
DROP PROCEDURE IF EXISTS GET_OPA_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_OPA_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_APPROVERS_FOR_ROLE_TYPE;
DROP FUNCTION IF EXISTS FN_WORKFLOW_APPROVE;
