DROP PROCEDURE IF EXISTS COI_COPY_GLOBAL_ENTITY;
DROP PROCEDURE IF EXISTS DUNS_REFRESH_ENTITY_HEADER;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_COUNT;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_DATA;
DROP PROCEDURE IF EXISTS VALIDATE_ENTITY_MANDATORY_FIELDS;
