INSERT INTO `ENTITY_STATUS_TYPE` (`ENTITY_STATUS_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('4', 'Modification in Progress-DUNS Refresh', 'Y', now(), 'quickstart');

INSERT INTO `parameter` (`PARAMETER_NAME`, `VALUE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) 
VALUES ('ENTITY_MONITORING_CONFIRMATION_REQUIRED', 'Y', 'If the value is Y all entity version created as part of duns monitoring should be confirmed manually', now(), 'quickstart');
INSERT INTO `parameter` (`PARAMETER_NAME`, `VALUE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) 
VALUES ('ENABLE_ENTITY_MONITORING', 'Y', 'If the value is Y while entity verifying will subscribe for duns monitoring', now(), 'quickstart');

INSERT INTO entity_duns_refresh_status_type
(REFRESH_STATUS_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('1', 'Pending', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_status_type
(REFRESH_STATUS_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('2', 'Completed', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_status_type
(REFRESH_STATUS_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('3', 'Error', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_status_type
(REFRESH_STATUS_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('4', 'No Change Detected', 'Y', now(), 'quickstart');

INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('1', 'Update', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('2', 'Deleted', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('3', 'Enter', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('4', 'Exit', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('5', 'Reviewed', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('6', 'Seed', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('7', 'Transfer', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('8', 'Undelete', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('9', 'Under review', 'Y', now(), 'quickstart');
INSERT INTO entity_duns_refresh_type
(REFRESH_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
VALUES('10', 'Unidentified', 'Y', now(), 'quickstart');

INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.PRIMARY_NAME', 'Entity Name', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.DUNS_NUMBER', 'DUNS Number', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.UEI_NUMBER', 'UEI Number', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.CAGE_NUMBER', 'Cage Number', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.BUSINESS_TYPE_CODE', 'Entity Business Type', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.ENTITY_OWNERSHIP_TYPE_CODE', 'Ownership Type', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.CURRENCY_CODE', 'Currency', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.INCORPORATION_DATE', 'Incorporation Date', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.FEDERAL_EMPLOYER_ID', 'Federal Employer ID', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.START_DATE', 'Start Date', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.CERTIFIED_EMAIL', 'Email Address', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.PRIMARY_ADDRESS_LINE_1', 'Primary Address Line 1', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.PRIMARY_ADDRESS_LINE_2', 'Primary Address Line 2', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.CITY', 'City', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.STATE', 'State', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.POST_CODE', 'Zip', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.COUNTRY_CODE', 'Country', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.NUMBER_OF_EMPLOYEES', 'Number of Employees', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.PHONE_NUMBER', 'Phone', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.SHORT_NAME', 'Entity Short Name', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.WEBSITE_ADDRESS', 'Website', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.FOREIGN_NAME', 'Foreign Name', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.ACTIVITY_TEXT', 'Activity Text', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY.FOREIGN_NAME', 'Foreign Name', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY_INDUSTRY_CLASSIFICATION.INDUSTRY_CATEGORY_ID', 'Foreign Name', 'Y', now(), 'quickstart');
INSERT INTO `ENTITY_DUNS_REFRESH_FIELD_CONFIG` (`FIELD_NAME`, `DESCRIPTION`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATED_BY`)
VALUES ('ENTITY_INDUSTRY_CLASSIFICATION.INDUSTRY_CATEGORY_ID', 'Foreign Name', 'Y', now(), 'quickstart');
