CREATE TABLE ENTITY_DUNS_REFRESH_FIELD_CONFIG (REFRESH_FIELD_CONFIG_ID INT NOT NULL AUTO_INCREMENT, FIELD_NAME VARCHAR(70) NULL, DESCRIPTION VARCHAR(200) NULL, IS_MANDATORY VARCHAR(1) NULL DEFAULT 'Y', UPDATE_TIMESTAMP DATETIME NULL, UPDATED_BY VARCHAR(40) NULL, PRIMARY KEY (REFRESH_FIELD_CONFIG_ID));

CREATE TABLE ENTITY_DUNS_REFRESH_STATUS_TYPE ( REFRESH_STATUS_TYPE_CODE VARCHAR(3) NOT NULL, DESCRIPTION VARCHAR(200) NULL, IS_ACTIVE VARCHAR(1) NULL, UPDATE_TIMESTAMP DATETIME NULL, UPDATED_BY VARCHAR(40) NULL, PRIMARY KEY (REFRESH_STATUS_TYPE_CODE));

CREATE TABLE ENTITY_DUNS_REFRESH_TYPE ( REFRESH_TYPE_CODE VARCHAR(3) NOT NULL, DESCRIPTION VARCHAR(200) NULL, IS_ACTIVE VARCHAR(1) NULL, UPDATE_TIMESTAMP DATETIME NULL, UPDATED_BY VARCHAR(40) NULL, PRIMARY KEY (REFRESH_TYPE_CODE));

CREATE TABLE ENTITY_DUNS_REFRESH_DETAILS ( ENT_DUNS_REF_DETAIL_ID INT NOT NULL AUTO_INCREMENT, ENTITY_ID INT NULL, ENTITY_NUMBER INT NULL, DUNS_NUMBER VARCHAR(20) NULL, REFRESH_STATUS_TYPE_CODE VARCHAR(3) NULL, MONITORING_SEED_DATA JSON NULL, REFRESH_TYPE_CODE VARCHAR(3),MONITORING_SEED_FILE_NAME VARCHAR(150) NULL, ERROR_MESSAGE TEXT NULL, CREATE_TIMESTAMP DATETIME NULL, UPDATE_TIMESTAMP DATETIME NULL, CREATED_BY VARCHAR(40) NULL, UPDATED_BY VARCHAR(40) NULL, PRIMARY KEY (ENT_DUNS_REF_DETAIL_ID), INDEX REFRESH_STATUS_TYPE_CODE_IDX_1 (ENTITY_ID ASC) VISIBLE, INDEX REFRESH_STATUS_TYPE_CODE_IDX_2 (REFRESH_STATUS_TYPE_CODE ASC) VISIBLE, INDEX REFRESH_STATUS_TYPE_CODE_IDX_3 (REFRESH_TYPE_CODE ASC) VISIBLE, CONSTRAINT ENTITY_DUNS_REFRESH_DETAILS_FK_1 FOREIGN KEY (ENTITY_ID) REFERENCES entity (ENTITY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT ENTITY_DUNS_REFRESH_DETAILS_FK_2 FOREIGN KEY (REFRESH_STATUS_TYPE_CODE) REFERENCES ENTITY_DUNS_REFRESH_STATUS_TYPE (REFRESH_STATUS_TYPE_CODE) ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT ENTITY_DUNS_REFRESH_DETAILS_FK_3 FOREIGN KEY (REFRESH_TYPE_CODE) REFERENCES ENTITY_DUNS_REFRESH_TYPE (REFRESH_TYPE_CODE) ON DELETE NO ACTION ON UPDATE NO ACTION);

ALTER TABLE ENTITY ADD COLUMN IS_DUNS_MONITORING_ENABLE VARCHAR(1) NULL DEFAULT 'N';

update ENTITY_ADDRESS_TYPE set IS_ACTIVE = 'N' where ADDRESS_TYPE_CODE in (3,4);
