\. ./FIBI-COI-5.8.4/FC-1693/Procedures/GET_APPROVERS_FOR_ROLE_TYPE.sql
\. ./FIBI-COI-5.8.4/FC-1693/Procedures/GET_COI_DECLARATION_DETAIL_INTEG.sql
\. ./FIBI-COI-5.8.4/FC-1693/Procedures/GET_DECLARATION_DASHBOARD_DYNAMIC_DATA.sql
\. ./FIBI-COI-5.8.4/FC-1693/Procedures/GET_DECLARATION_DETAILS.sql
\. ./FIBI-COI-5.8.4/FC-1693/Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
