INSERT IGNORE INTO `NOTIFICATION_TYPE` (`NOTIFICATION_TYPE_ID`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`SUBJECT`,`MESSAGE`,`PROMPT_USER`,`IS_ACTIVE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`IS_SYSTEM_SPECIFIC`,`SHOW_TEMPLATE_IN_MODULE`,`SENT_TO_INITIATOR`) VALUES (8086,23,0,'OPA Disclosure Review Location Assign without Reviewer.','Action required: OPA disclosure Submitted by {OPA_DETAILS#REPORTER_NAME} waiting for review at {OPA_DISCL_REVIEW#REVIEW_LOCATION}.','<p><span style=\"color:hsl(0,0%,0%);\">Hello Reviewer,</span></p><p><span style=\"color:hsl(0,0%,0%);\">On {OPA_DISCL_REVIEW#REVIEW_ASSIGNED_DATE}, COI Administrator {OPA_OTHER#ADMINISTRATOR_NAME} assigned you to review the OPA Disclosure submitted on </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">{OPA_DETAILS#CERTIFICATION_DATE}</span><span style=\"color:hsl(0,0%,0%);\"> by {OPA_DETAILS#REPORTER_NAME}.</span></p><p><strong>Department</strong>: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p><strong>Disclosure Status</strong>: {OPA_DETAILS#DISPOSITION_STATUS}</p><p><strong>Review Location</strong>: {OPA_DISCL_REVIEW#REVIEW_LOCATION}</p><p><strong>Review Status</strong>: {OPA_DISCL_REVIEW#REVIEWER_REVIEW_STATUS}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>','N','Y','admin',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'N',NULL,'N');

INSERT INTO `NOTIFICATION_RECIPIENT` 
(`NOTIFICATION_TYPE_ID`, `ROLE_TYPE_CODE`, `CREATE_TIMESTAMP`, `RECIPIENT_TYPE`, `RECIPIENT_NAME`)
SELECT * FROM (
    SELECT 8086, 67, UTC_TIMESTAMP(), 'TO', 'OPA Primary Administrator'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM `NOTIFICATION_RECIPIENT` 
    WHERE `NOTIFICATION_TYPE_ID` = 8086
      AND `ROLE_TYPE_CODE` = 67
      AND `RECIPIENT_TYPE` = 'TO'
      AND `RECIPIENT_NAME` = 'OPA Primary Administrator'
);

INSERT INTO `NOTIFICATION_RECIPIENT` 
(`NOTIFICATION_TYPE_ID`, `ROLE_TYPE_CODE`, `CREATE_TIMESTAMP`, `RECIPIENT_TYPE`, `RECIPIENT_NAME`)
SELECT * FROM (
    SELECT 8086, 66, UTC_TIMESTAMP(), 'CC', 'OPA Administrators'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM `NOTIFICATION_RECIPIENT` 
    WHERE `NOTIFICATION_TYPE_ID` = 8086
      AND `ROLE_TYPE_CODE` = 66
      AND `RECIPIENT_TYPE` = 'CC'
      AND `RECIPIENT_NAME` = 'OPA Administrators'
);

INSERT IGNORE INTO `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`,`ACTION_TYPE`,`MODULE_CODE`,`SUB_MODULE_CODE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (85,'OPA_LOC_ASSIGNED_NO_REVIEWER',23,0,'Y','OPA Review Location added without reviewer',UTC_TIMESTAMP(),'admin');

INSERT INTO `NOTIFY_ACTION_TYPE_MAP` 
(`NOTIFICATION_TYPE_ID`, `MODULE_ACTION_TYPE_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
SELECT * FROM (
    SELECT 8086, 85, UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM `NOTIFY_ACTION_TYPE_MAP` 
    WHERE `NOTIFICATION_TYPE_ID` = 8086
      AND `MODULE_ACTION_TYPE_ID` = 85
);

INSERT INTO `MQ_ROUTER_ACTION_CONFIGURATION` 
(`ACTION_TYPE`, `IS_ACTIVE`, `MODULE_CODE`, `QUEUE_NAME`, `SUB_MODULE_CODE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
SELECT * FROM (
    SELECT 'OPA_LOC_ASSIGNED_NO_REVIEWER', 'Y', 23, 'Q_NOTIFICATION', 0, UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM `MQ_ROUTER_ACTION_CONFIGURATION` 
    WHERE `ACTION_TYPE` = 'OPA_LOC_ASSIGNED_NO_REVIEWER'
      AND `MODULE_CODE` = 23
      AND `SUB_MODULE_CODE` = 0
);

INSERT IGNORE INTO `NOTIFY_PLACEHOLDER_HEADER` (`NOTIFY_PLACEHOLDER_HEADER_ID`,`MODULE_CODE`,`SUB_MODULE_CODE`,`QUERY_DEFINITION`,`QUERY_TYPE`,`ELEMENT_NAME`,`ELEMENT_TYPE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`UNIQUE_DISPLAY_NAME`) VALUES (23,23,0,'GET_OPA_DISCL_REVIEW_DETAILS','P',NULL,'P','Y','OPA Disclosure review details only',UTC_TIMESTAMP(),'admin','OPA_DISCL_REVIEW');

INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` 
(`NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
SELECT * FROM (
    SELECT 23, 'REVIEW_LOCATION', 'Review Location', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM `NOTIFY_PLACEHOLDER_COLUMNS` 
    WHERE `NOTIFY_PLACEHOLDER_HEADER_ID` = 23
      AND `QUERY_COLUMN_NAME` = 'REVIEW_LOCATION'
      AND `LABEL_NAME` = 'Review Location'
);

INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` 
(`NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
SELECT * FROM (
    SELECT 23, 'REVIEWER_REVIEW_STATUS', 'Reviewer Review Status', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM `NOTIFY_PLACEHOLDER_COLUMNS` 
    WHERE `NOTIFY_PLACEHOLDER_HEADER_ID` = 23
      AND `QUERY_COLUMN_NAME` = 'REVIEWER_REVIEW_STATUS'
      AND `LABEL_NAME` = 'Reviewer Review Status'
);

INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` 
(`NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
SELECT * FROM (
    SELECT 23, 'REVIEWER_NAME', 'Reviewer Name', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM `NOTIFY_PLACEHOLDER_COLUMNS` 
    WHERE `NOTIFY_PLACEHOLDER_HEADER_ID` = 23
      AND `QUERY_COLUMN_NAME` = 'REVIEWER_NAME'
      AND `LABEL_NAME` = 'Reviewer Name'
);

INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` 
(`NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
SELECT * FROM (
    SELECT 23, 'REVIEW_ASSIGNED_DATE', 'Review Assigned Date', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM `NOTIFY_PLACEHOLDER_COLUMNS` 
    WHERE `NOTIFY_PLACEHOLDER_HEADER_ID` = 23
      AND `QUERY_COLUMN_NAME` = 'REVIEW_ASSIGNED_DATE'
      AND `LABEL_NAME` = 'Review Assigned Date'
);

DELETE FROM NOTIFY_PLACEHOLDER_COLUMNS WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 20 AND QUERY_COLUMN_NAME IN ('REVIEWER_NAME','REVIEW_LOCATION','REVIEWER_REVIEW_STATUS');

UPDATE `NOTIFICATION_TYPE` SET `SUBJECT` = 'Action required: OPA disclosure Submitted by {OPA_DETAILS#REPORTER_NAME} waiting for review at {OPA_DISCL_REVIEW#REVIEW_LOCATION} with {OPA_DISCL_REVIEW#REVIEWER_REVIEW_STATUS} status.', `MESSAGE` = '<p>Hello,</p><p>OPA Administrator {OPA_OTHER#ADMINISTRATOR_NAME} assigned you to review the OPA submitted on {OPA_DETAILS#CERTIFICATION_DATE} by {OPA_DETAILS#REPORTER_NAME}.</p><p>Department: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p>Disclosure Status: {OPA_DETAILS#DISPOSITION_STATUS}</p><p>Review Location: {OPA_DISCL_REVIEW#REVIEW_LOCATION}</p><p>Review Status: {OPA_DISCL_REVIEW#REVIEWER_REVIEW_STATUS}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8075');
