INSERT IGNORE INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (1380,'Entity DST Administrator','Entity DST Administrator','1','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin');

INSERT IGNORE INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES (2602,'Entity DST Administrators',UTC_TIMESTAMP(),'admin','Y');
