\. ./FIBI-COI-5.7/FC-1396/Procedures/GET_PERSON_ENTITIES.sql
\. ./FIBI-COI-5.7/FC-1396/Procedures/GET_COI_PERSON_ENTITY_DETAILS.sql
\. ./FIBI-COI-5.7/FC-1396/Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./FIBI-COI-5.7/FC-1396/Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./FIBI-COI-5.7/FC-1396/Procedures/COI_VALIDATE_DISCLOSURE_CONFLICTS.sql
\. ./FIBI-COI-5.7/FC-1396/Procedures/COI_SYNC_FCOI_DISCLOSURE.sql
\. ./FIBI-COI-5.7/FC-1396/Procedures/COI_EVALUATE_VALIDATION_MESSAGE.sql
\. ./FIBI-COI-5.7/FC-1396/Procedures/COI_DISCL_PERSON_ENTITY_INSERTION.sql
