INSERT INTO COI_DISCL_PERSON_ENTITY_REL (
    PERSON_ENTITY_ID,
    PERSON_ENTITY_NUMBER,
    PREVIOUS_PERSON_ENTITY_ID,
    ENTITY_ID,
    UPDATED_BY,
    UPDATE_TIMESTAMP,
    DISCLOSURE_ID
)
SELECT 
    rel.PERSON_ENTITY_ID,
    rel.PERSON_ENTITY_NUMBER,
    rel.PREVIOUS_PERSON_ENTITY_ID,
    rel.ENTITY_ID,
    rel.UPDATED_BY,
    rel.UPDATE_TIMESTAMP,
    proj.DISCLOSURE_ID
FROM COI_DISCL_PROJECT_ENTITY_REL rel
JOIN COI_DISCL_PROJECTS proj
    ON rel.COI_DISCL_PROJECTS_ID = proj.COI_DISCL_PROJECTS_ID;
	
SET SQL_SAFE_UPDATES = 0;
	DELETE FROM COI_DISCL_PERSON_ENTITY_REL
WHERE COI_DISCL_PERSON_ENTITY_REL_ID IN (
    SELECT COI_DISCL_PERSON_ENTITY_REL_ID
    FROM (
        SELECT 
            COI_DISCL_PERSON_ENTITY_REL_ID,
            ROW_NUMBER() OVER (
                PARTITION BY DISCLOSURE_ID, ENTITY_ID, PREVIOUS_PERSON_ENTITY_ID, PERSON_ENTITY_NUMBER, PERSON_ENTITY_ID
                ORDER BY COI_DISCL_PERSON_ENTITY_REL_ID
            ) AS rn
        FROM COI_DISCL_PERSON_ENTITY_REL
    ) temp
    WHERE temp.rn > 1
);
SET SQL_SAFE_UPDATES = 1;
