CREATE TABLE IF NOT EXISTS `CMP_TASK_TYPE` (
  `TASK_TYPE_CODE` VARCHAR(3) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NOT NULL,
  `SORT_ORDER` INT DEFAULT NULL,
  `UPDATE_TIMESTAMP` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(60) NOT NULL,
  `IS_ACTIVE` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`TASK_TYPE_CODE`)
);


CREATE TABLE IF NOT EXISTS `CMP_TASK_STATUS` (
  `TASK_STATUS_CODE` VARCHAR(3) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NOT NULL,
  `UPDATE_TIMESTAMP` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(60) NOT NULL,
  `IS_ACTIVE` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`TASK_STATUS_CODE`)
);


CREATE TABLE IF NOT EXISTS `CMP_TASK` (
  `TASK_ID` INT NOT NULL AUTO_INCREMENT,
  `TASK_TYPE_CODE` VARCHAR(3) NOT NULL,
  `TASK_STATUS_CODE` VARCHAR(3) NOT NULL,
  `ASSIGNEE_PERSON_ID` VARCHAR(40) DEFAULT NULL,
  `CREATE_TIMESTAMP` DATETIME DEFAULT NULL,
  `CREATED_BY` VARCHAR(60) NOT NULL,
  `UPDATE_TIMESTAMP` DATETIME DEFAULT NULL,
  `COMPLETION_TIMESTAMP` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(60) NOT NULL,
  `DESCRIPTION` VARCHAR(2000) DEFAULT NULL,
  `DUE_DATE` DATETIME DEFAULT NULL,
  `CMP_ID` INT NOT NULL,
  `ASSIGNED_ON` DATETIME DEFAULT NULL,
  PRIMARY KEY (`TASK_ID`),
  KEY `CMP_TASK_FK1` (`TASK_TYPE_CODE`),
  KEY `CMP_TASK_FK2` (`TASK_STATUS_CODE`),
  KEY `CMP_TASK_FK3` (`CMP_ID`),
  CONSTRAINT `CMP_TASK_FK1` FOREIGN KEY (`TASK_TYPE_CODE`) REFERENCES `CMP_TASK_TYPE` (`TASK_TYPE_CODE`),
  CONSTRAINT `CMP_TASK_FK2` FOREIGN KEY (`TASK_STATUS_CODE`) REFERENCES `CMP_TASK_STATUS` (`TASK_STATUS_CODE`),
  CONSTRAINT `CMP_TASK_FK3` FOREIGN KEY (`CMP_ID`) REFERENCES `COI_MANAGEMENT_PLAN` (`CMP_ID`)
);


CREATE TABLE IF NOT EXISTS `CMP_TASK_ATTACHMENT` (
  `ATTACHMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `TASK_ID` INT DEFAULT NULL,
  `FILE_NAME` VARCHAR(500) DEFAULT NULL,
  `CONTENT_TYPE` VARCHAR(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(60) DEFAULT NULL,
  `FILE_DATA_ID` VARCHAR(100) DEFAULT NULL,
  `VERSION_NUMBER` INT DEFAULT NULL,
  `DESCRIPTION` VARCHAR(1000) DEFAULT NULL,
  `DOCUMENT_ID` INT DEFAULT NULL,
  `CREATED_BY` VARCHAR(60) DEFAULT NULL,
  `CREATE_TIMESTAMP` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ATTACHMENT_ID`),
  KEY `CMP_TASK_ATTACHMENT_FK1` (`TASK_ID`),
  CONSTRAINT `CMP_TASK_ATTACHMENT_FK1` FOREIGN KEY (`TASK_ID`) REFERENCES `CMP_TASK` (`TASK_ID`)
);


CREATE TABLE IF NOT EXISTS `CMP_TASK_QUESTIONS` (
  `CMP_TASK_QUESTION_ID` INT NOT NULL AUTO_INCREMENT,
  `TASK_ID` INT NOT NULL,
  `QUESTION` TEXT NOT NULL,
  `DESCRIPTION` TINYTEXT NULL,
  `CREATED_BY` VARCHAR(40) NULL,
  `CREATE_TIMESTAMP` DATETIME NULL,
  `UPDATE_TIMESTAMP` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`CMP_TASK_QUESTION_ID`),
   CONSTRAINT `CMP_TASK_QUESTIONS_FK1`
    FOREIGN KEY (`TASK_ID`)
    REFERENCES`CMP_TASK` (`TASK_ID`));


CREATE TABLE IF NOT EXISTS `CMP_TASK_QUESTION_ANS` (
  `TASK_QUESTION_ANS_ID` INT NOT NULL AUTO_INCREMENT,
  `CMP_TASK_QUESTION_ID` INT NULL,
  `ANSWER` TEXT NOT NULL,
  `ANSWERED_BY` VARCHAR(40) NULL,
  `ANSWERED_TIMESTAMP` DATETIME NULL,
  `UPDATED_BY` VARCHAR(40) NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  PRIMARY KEY (`TASK_QUESTION_ANS_ID`),
  CONSTRAINT `CMP_TASK_QUESTION_ANS_FK1`
    FOREIGN KEY (`CMP_TASK_QUESTION_ID`)
    REFERENCES`CMP_TASK_QUESTIONS` (`CMP_TASK_QUESTION_ID`));


CREATE TABLE IF NOT EXISTS `CMP_TASK_COMMENTS` (
  `CMP_TASK_COMMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `PARENT_COMMENT_ID` INT DEFAULT NULL,
  `TASK_ID` INT DEFAULT NULL,
  `COMMENTS` VARCHAR(255) DEFAULT NULL,
  `IS_PRIVATE` VARCHAR(1) DEFAULT NULL,
  `IS_RESOLVED` VARCHAR(1) DEFAULT NULL,
  `RESOLVED_BY` VARCHAR(40) DEFAULT NULL,
  `RESOLVED_TIMESTAMP` VARCHAR(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` DATETIME(6) DEFAULT NULL,
  `UPDATED_BY` VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (`CMP_TASK_COMMENT_ID`),
  KEY `TASK_COMMENTS_FK1` (`TASK_ID`),
  CONSTRAINT `CMP_TASK_COMMENTS_FK1` FOREIGN KEY (`TASK_ID`) REFERENCES `CMP_TASK` (`TASK_ID`)
);


CREATE TABLE IF NOT EXISTS `CMP_TASK_WATCHER` (
  `CMP_TASK_WATCHER_ID` INT NOT NULL AUTO_INCREMENT,
  `WATCHER_PERSON_ID` VARCHAR(40) DEFAULT NULL,
  `TASK_ID` INT NOT NULL,
  `UPDATE_TIMESTAMP` DATETIME(6) DEFAULT NULL,
  `UPDATED_BY` VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (`CMP_TASK_WATCHER_ID`),
  KEY `CMP_TASK_WATCHER_FK1` (`TASK_ID`),
  CONSTRAINT `CMP_TASK_WATCHER_FK1` FOREIGN KEY (`TASK_ID`) REFERENCES `CMP_TASK` (`TASK_ID`)
);

INSERT IGNORE INTO `CMP_TASK_STATUS` (`TASK_STATUS_CODE`, `DESCRIPTION`, `UPDATED_BY`, `IS_ACTIVE`) VALUES ('1', 'Assigned', 'admin', 'Y');
INSERT IGNORE INTO `CMP_TASK_STATUS` (`TASK_STATUS_CODE`, `DESCRIPTION`, `UPDATED_BY`, `IS_ACTIVE`) VALUES ('2', 'In Progress', 'admin', 'Y');
INSERT IGNORE INTO `CMP_TASK_STATUS` (`TASK_STATUS_CODE`, `DESCRIPTION`, `UPDATED_BY`, `IS_ACTIVE`) VALUES ('3', 'On Hold', 'admin', 'Y');
INSERT IGNORE INTO `CMP_TASK_STATUS` (`TASK_STATUS_CODE`, `DESCRIPTION`, `UPDATED_BY`, `IS_ACTIVE`) VALUES ('4', 'Completed', 'admin', 'Y');

INSERT IGNORE INTO `CMP_TASK_TYPE` (`TASK_TYPE_CODE`, `DESCRIPTION`, `SORT_ORDER`, `UPDATED_BY`, `IS_ACTIVE`) VALUES ('1', 'CMP Revision', '1', 'admin', 'Y');
INSERT IGNORE INTO letter_template_type (LETTER_TEMPLATE_TYPE_CODE,FILE_NAME,CONTENT_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,MODULE_CODE,SUB_MODULE_CODE,PRINT_FILE_TYPE,IS_ACTIVE) VALUES
	 ('8020','CMP.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',utc_timestamp(),'admin',28,1,'docx','Y');

