CREATE TABLE FIBI_COI_ENTITY_STATUS (
    STATUS_CODE INT PRIMARY KEY,
    DESCRIPTION VARCHAR(200),
    UPDATE_TIMESTAMP DATETIME,
    UPDATE_USER VARCHAR(60)
);

CREATE TABLE FIBI_COI_ENTITY_TYPE (
    ENTITY_TYPE_CODE INT PRIMARY KEY,
    DESCRIPTION VARCHAR(2000),
    UPDATE_TIMESTAMP DATETIME,
    UPDATE_USER VARCHAR(60)
);

CREATE TABLE FIBI_COI_ENG_REVIEW_STATUS (
    ENG_REVIEW_STATUS_CODE INT PRIMARY KEY,
    DESCRIPTION VARCHAR(30),
    UPDATE_TIMESTAMP DATETIME,
    UPDATE_USER VARCHAR(60)
);

CREATE TABLE LEGACY_COI_ENT_MAT_MAPPING (
    MATRIX_MAPPING_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MATRIX_QUESTION_ID INT,
    MATRIX_NAME VARCHAR(30),
	DATA_GROUP_ID INT,
    UPDATE_TIMESTAMP DATETIME,
    UPDATE_USER VARCHAR(60),
    CONSTRAINT LEGACY_COI_ENT_MAT_MAPPRING_FK1 FOREIGN KEY (MATRIX_QUESTION_ID) REFERENCES PER_ENT_MATRIX_QUESTION(MATRIX_QUESTION_ID)
);

CREATE TABLE LEGACY_COI_ENGAGEMENTS (
    ENGAGEMENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PERSON_ID VARCHAR(9),
    ENTITY_NUMBER VARCHAR(10),
    SEQUENCE_NUMBER INT,
    STATUS_CODE INT,
    ENTITY_NAME VARCHAR(60),
    ENTITY_TYPE_CODE INT,
    ENTITY_OWNERSHIP_TYPE CHAR(1),
    RELATIONSHIP_DESCRIPTION VARCHAR(4000),
	STUDENT_INVOLVEMENT VARCHAR(4000),
	STAFF_INVOLVEMENT VARCHAR(4000),
    INST_RESOURCE_INVOLVEMENT VARCHAR(4000),
    IS_TRAVEL CHAR(1),
    HAS_TRAVEL_ENTRY CHAR(1),
    IS_FOUNDER CHAR(1),
    MIGRATION_STATUS INT,
    FIBI_COI_ENGAGEMENT_ID INT,
    FIBI_COI_ENTITY_ID INT,
    UPDATE_USER VARCHAR(60),
    UPDATE_TIMESTAMP DATETIME,
    CONSTRAINT LEGACY_COI_ENGAGEMENTS_FK1 FOREIGN KEY (STATUS_CODE) REFERENCES FIBI_COI_ENTITY_STATUS(STATUS_CODE),
    CONSTRAINT LEGACY_COI_ENGAGEMENTS_FK2 FOREIGN KEY (ENTITY_TYPE_CODE) REFERENCES FIBI_COI_ENTITY_TYPE(ENTITY_TYPE_CODE),
    CONSTRAINT LEGACY_COI_ENGAGEMENTS_FK3 FOREIGN KEY (MIGRATION_STATUS) REFERENCES FIBI_COI_ENG_REVIEW_STATUS(ENG_REVIEW_STATUS_CODE)
);

CREATE TABLE LEGACY_COI_ENTITY_MATRIX (
    ENTITY_MATRIX_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ENGAGEMENT_ID INT,
    ENTITY_NUMBER VARCHAR(10),
    MATRIX_NAME VARCHAR(30),
    MATRIX_VALUE VARCHAR(2000),
    RELATIONSHIP_TYPE_CODE VARCHAR(3) NOT NULL,
    UPDATE_TIMESTAMP DATETIME,
    UPDATE_USER VARCHAR(60),
    CONSTRAINT LEGACY_COI_ENTITY_MATRIX_FK1 FOREIGN KEY (ENGAGEMENT_ID) REFERENCES LEGACY_COI_ENGAGEMENTS(ENGAGEMENT_ID),
    CONSTRAINT LEGACY_COI_ENTITY_MATRIX_FK2 FOREIGN KEY (RELATIONSHIP_TYPE_CODE) REFERENCES PERSON_ENTITY_REL_TYPE(RELATIONSHIP_TYPE_CODE)
);
