DROP PROCEDURE IF EXISTS FCOI_DIS_RNWL_RMNDR_MNTLY_SMRY;
DROP PROCEDURE IF EXISTS FCOI_DISCL_RENWAL_REMNDR_SUMRY;
DROP PROCEDURE IF EXISTS FCOI_DISCLOSRE_RENEWAL_REMINDER;
DROP FUNCTION IF EXISTS FN_FCOI_DISCLOSURE_REQUIRED;
DROP PROCEDURE IF EXISTS GET_EXPIRING_FCOI_AND_OPA_DISCLOSURES;
DROP PROCEDURE IF EXISTS MARK_DISCLOSURES_AS_EXPIRED;
