DROP PROCEDURE IF EXISTS GET_ENTITY_MANDATORY_FIELDS;
DROP PROCEDURE IF EXISTS GET_ENTITY_TAB_STATUS;
DROP PROCEDURE IF EXISTS VALIDATE_ENTITY_MANDATORY_FIELDS;
DROP PROCEDURE IF EXISTS GET_COI_PROJECTS;
DROP PROCEDURE IF EXISTS COI_SYNC_FCOI_DISCLOSURE;
DROP PROCEDURE IF EXISTS COI_SYNC_INSERT_DISCL_PROJECTS;
DROP PROCEDURE IF EXISTS VALIDATE_PROJECT_DISCLOSURE;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;