UPDATE INDUSTRY_CATEGORY_CODE SET INDUSTRY_CATEGORY_CODE = 'S001' WHERE (INDUSTRY_CATEGORY_TYPE_CODE = 'S001' AND DESCRIPTION = 'Fossil Fuel');
UPDATE INDUSTRY_CATEGORY_CODE SET INDUSTRY_CATEGORY_CODE = 'S002' WHERE (INDUSTRY_CATEGORY_TYPE_CODE = 'S001' AND DESCRIPTION = 'Climate');
UPDATE INDUSTRY_CATEGORY_CODE SET INDUSTRY_CATEGORY_CODE = 'S003' WHERE (INDUSTRY_CATEGORY_TYPE_CODE = 'S001' AND DESCRIPTION = 'AI');
UPDATE INDUSTRY_CATEGORY_CODE SET INDUSTRY_CATEGORY_CODE = 'S004' WHERE (INDUSTRY_CATEGORY_TYPE_CODE = 'S001' AND DESCRIPTION = 'Foreign Aid');
