\. ./FIBI-COI-5.1.1/FC-10/Procedures/FCOI_DISCLOSRE_RENEWAL_REMINDER.sql
\. ./FIBI-COI-5.1.1/FC-10/Procedures/GET_APPROVERS_FOR_ROLE_TYPE.sql
\. ./FIBI-COI-5.1.1/FC-10/Procedures/GET_COI_DISCL_GENERAL_DETAILS.sql
\. ./FIBI-COI-5.1.1/FC-10/Procedures/GET_COI_DISCL_REVIEW_DETAILS.sql
\. ./FIBI-COI-5.1.1/FC-10/Procedures/PROJECT_DISCLOSURE_RENEWAL_REMINDER.sql
\. ./FIBI-COI-5.1.1/FC-10/Procedures/GET_COI_DISCL_PROJECT_DETAILS.sql
\. ./FIBI-COI-5.1.1/FC-10/Procedures/GET_GLOBAL_ENTITY_DETAILS.sql

