DROP PROCEDURE IF EXISTS COI_INT_GET_ORGANIZATION_DETAILS;
DROP PROCEDURE IF EXISTS COI_INT_GET_SPONSOR_DETAILS;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_COUNT;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_DATA;
