\. ./FIBI-COI-5.6.P2/FC-975/Procedures/COI_INT_GET_ORGANIZATION_DETAILS.sql
\. ./FIBI-COI-5.6.P2/FC-975/Procedures/COI_INT_GET_SPONSOR_DETAILS.sql
\. ./FIBI-COI-5.6.P2/FC-975/Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_COUNT.sql
\. ./FIBI-COI-5.6.P2/FC-975/Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_DATA.sql
