CREATE TRIGGER PERSON_POST_INS AFTER INSERT ON PERSON FOR EACH ROW BEGIN
    DECLARE LI_SORT_ORDER INT;
    
        SELECT IFNULL(MAX(SORT_ORDER), 0) + 1 INTO LI_SORT_ORDER
        FROM USER_SELECTED_WIDGET
        WHERE PERSON_ID = NEW.PERSON_ID;

        INSERT INTO `USER_SELECTED_WIDGET` (`WIDGET_ID`, `SORT_ORDER`, `PERSON_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
        VALUES 
            (2, LI_SORT_ORDER, NEW.PERSON_ID, UTC_TIMESTAMP(), 'POLUS_ADMIN'),
            (9, LI_SORT_ORDER + 1, NEW.PERSON_ID, UTC_TIMESTAMP(), 'POLUS_ADMIN'),
            (13, LI_SORT_ORDER + 2, NEW.PERSON_ID, UTC_TIMESTAMP(), 'POLUS_ADMIN'),
            (31, LI_SORT_ORDER + 3, NEW.PERSON_ID, UTC_TIMESTAMP(), 'POLUS_ADMIN'),
            (32, LI_SORT_ORDER + 4, NEW.PERSON_ID, UTC_TIMESTAMP(), 'POLUS_ADMIN');
END