DROP PROCEDURE IF EXISTS GET_PERSON_ENTITIES;
DROP PROCEDURE IF EXISTS COI_EVALUATE_VALIDATION_MESSAGE;
DROP PROCEDURE IF EXISTS COI_SYNC_FCOI_DISCLOSURE;
DROP PROCEDURE IF EXISTS COI_EVALUATE_SFI;
DROP PROCEDURE IF EXISTS TRAVEL_VALIDATE_REIMBURSEMENT_COST;
