Analyze table PERSON_ENTITY;

SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PERSON_ENTITY' AND COLUMN_NAME = 'COMPENSATION_AMOUNT') = 0,
    'ALTER TABLE PERSON_ENTITY ADD COLUMN COMPENSATION_AMOUNT DECIMAL(12,2) NULL DEFAULT NULL AFTER IS_COMPENSATED;',
    'DO 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PERSON_ENTITY' AND COLUMN_NAME = 'TRAVEL_REIMBURSEMENT_AMOUNT') = 0,
    'ALTER TABLE PERSON_ENTITY ADD COLUMN TRAVEL_REIMBURSEMENT_AMOUNT DECIMAL(12,2) NULL AFTER COMPENSATION_AMOUNT;',
    'DO 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PERSON_ENTITY' AND COLUMN_NAME = 'IS_SIGNIFICANT_FIN_INTEREST') = 0,
    'ALTER TABLE PERSON_ENTITY ADD COLUMN IS_SIGNIFICANT_FIN_INTEREST VARCHAR(1) NULL AFTER TRAVEL_REIMBURSEMENT_AMOUNT;',
    'DO 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PERSON_ENTITY' AND COLUMN_NAME = 'SFI_REASON') = 0,
    'ALTER TABLE PERSON_ENTITY ADD COLUMN SFI_REASON VARCHAR(500) NULL AFTER IS_SIGNIFICANT_FIN_INTEREST;',
    'DO 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

UPDATE parameter 
SET VALUE = '4999' 
WHERE PARAMETER_NAME = 'TRAVEL_REIMBURSED_COST_THRESHOLD';

UPDATE parameter 
SET PARAMETER_NAME = 'ENGAGEMENT_TYPE_FOR_COI_DISCLOSURE', 
    VALUE = 'ALL_FIN', 
    DESCRIPTION = 'To determine the type of engagement to be included in FCOI disclosure. Possible values are: ALL_ENG, ALL_FIN, ALL_SFI', 
    UPDATE_TIMESTAMP = UTC_TIMESTAMP(), 
    UPDATE_USER = 'admin' 
WHERE PARAMETER_NAME = 'IS_FINANCIAL_ENGAGEMENT_ONLY_FOR_DISCLOSURE';

INSERT IGNORE INTO parameter (
    PARAMETER_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER
) VALUES (
    'ENABLE_SIGNIFICANT_FIN_INTEREST_EVALUATION',
    'Y',
    'Determines whether the system should evaluate and flag engagements as Significant Financial Interest',
    UTC_TIMESTAMP(),
    'admin'
);

INSERT IGNORE INTO parameter (
    PARAMETER_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER
) VALUES (
    'SIGNIFICANT_FIN_INTEREST_THRESHOLD',
    '4999',
    'Engagements with compensation greater than the threshold is SFI',
    UTC_TIMESTAMP(),
    'admin'
);
