import { CLASS_BLUE_BADGE, CLASS_GREEN_BADGE, CLASS_GREY_BADGE, CLASS_RED_BADGE, CLASS_YELLOW_BADGE } from "../app-constants";

export const VIEW_MFTRP_DECLARATION_RIGHTS = ['VIEW_MFTRP_DECLARATION'];
export const MANAGE_MFTRP_DECLARATION_RIGHTS = ['MANAGE_MFTRP_DECLARATION'];
export const MFTRP_DECLARATION_RIGHTS = [...MANAGE_MFTRP_DECLARATION_RIGHTS, ...VIEW_MFTRP_DECLARATION_RIGHTS];
export const DECLARATION_RIGHTS = [...MFTRP_DECLARATION_RIGHTS];

export const COI_DECLARATION_MODULE_CODE = 28;
export const DECLARATION_MODULE_CONFIGURATION_CODE  = 'CC28';
export const DECLARATION_INITIAL_VERSION_NUMBER = 1;

export const DECLARATION_STATUS = {
    PENDING: '1',
    APPROVED: '2',
    REJECTED: '3',
    VOID: '4'
} as const;

export const DECLARATION_REVIEW_STATUS = {
    PENDING: '1',
    REVIEW_REQUIRED: '2',
    REVIEW_IN_PROGRESS: '3',
    WITHDRAWN: '4',
    RETURNED: '5',
    REVIEW_COMPLETED: '6',
    EXPIRED: '7',
    REVIEW_NOT_REQUIRED: '8',
} as const;


export const DECLARATION_VERSION_TYPE = {
    ACTIVE: 'ACTIVE',
    PENDING: 'PENDING',
    ARCHIVE: 'ARCHIVE'
} as const;

export const DECLARATION_STATUS_BADGE: Record<typeof DECLARATION_STATUS[keyof typeof DECLARATION_STATUS], string> = {
    [DECLARATION_STATUS.PENDING]: CLASS_YELLOW_BADGE,
    [DECLARATION_STATUS.APPROVED]: CLASS_GREEN_BADGE,
    [DECLARATION_STATUS.REJECTED]: CLASS_RED_BADGE,
    [DECLARATION_STATUS.VOID]: CLASS_GREY_BADGE,
} as const;

export const DECLARATION_REVIEW_STATUS_BADGE: Record<typeof DECLARATION_REVIEW_STATUS[keyof typeof DECLARATION_REVIEW_STATUS], string> = {
    [DECLARATION_REVIEW_STATUS.PENDING]: CLASS_YELLOW_BADGE,
    [DECLARATION_REVIEW_STATUS.REVIEW_REQUIRED]: CLASS_BLUE_BADGE,
    [DECLARATION_REVIEW_STATUS.REVIEW_IN_PROGRESS]: CLASS_YELLOW_BADGE,
    [DECLARATION_REVIEW_STATUS.WITHDRAWN]: CLASS_RED_BADGE,
    [DECLARATION_REVIEW_STATUS.RETURNED]: CLASS_RED_BADGE,
    [DECLARATION_REVIEW_STATUS.REVIEW_COMPLETED]: CLASS_GREEN_BADGE,
    [DECLARATION_REVIEW_STATUS.EXPIRED]: CLASS_RED_BADGE,
    [DECLARATION_REVIEW_STATUS.REVIEW_NOT_REQUIRED]: CLASS_GREY_BADGE,
} as const;

export const DECLARATION_VERSION_STATUS_BADGE = {
    [DECLARATION_VERSION_TYPE.ACTIVE]: CLASS_GREEN_BADGE,
    [DECLARATION_VERSION_TYPE.PENDING]: CLASS_YELLOW_BADGE,
    [DECLARATION_VERSION_TYPE.ARCHIVE]: CLASS_GREY_BADGE,
} as const;

export const DECLARATION_ADMIN_DASHBOARD_URL = '/coi/declaration-dashboard';
export const DECLARATION_BASE_URL = '/coi/declaration';
export const DECLARATION_ROUTE_URLS = {
    FORM: `${DECLARATION_BASE_URL}/form`,
    HISTORY: `${DECLARATION_BASE_URL}/history`,
};

export const ADVANCE_SEARCH_CRITERIA_IN_DECLARATION_ADMIN_DASHBOARD = [
    'PERSON', 'DEPARTMENT', 'DECLARATION_STATUS', 'REVIEW_STATUS_CODE', 'SUBMISSION_DATE', 'EXPIRATION_DATE', 'DECLARATION_TYPE', 'ADMINISTRATOR'
];

export const DASHBOARD_DECLARATION_CARD_FIELD_ORDER = [
    'DEPARTMENT',
    'CERTIFICATION_DATE',
    'EXPIRATION_DATE',
    'ADMINISTRATOR',
    'ADMIN_GROUP'
];
