DROP FUNCTION IF EXISTS FN_CAN_NOTIFY_FOR_CREATE_AWD_DISCL;
DROP PROCEDURE IF EXISTS GET_COI_AWARD_PROJECT_OVERVIEW;
DROP PROCEDURE IF EXISTS GET_HEIR_PROJECT_DETAIL;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP VIEW IF EXISTS coi_project_award_v;
DROP VIEW IF EXISTS coi_project_institute_proposal_v;
DROP VIEW IF EXISTS coi_project_proposal_v;
