INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) 
VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MAINTAIN_COI_RESOLVE_COMMENTS', 'Maintains and resolves comments related to COI disclosures.', 'quickstart', now(), '1');

INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) 
VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_ENTITY_OVERVIEW_RESOLVE_COMMENTS', 'Handles resolving comments in the Manage Entity Overview module.', 'quickstart', now(), '1');

INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) 
VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_ENTITY_CORPORATE_FAMILY_RESOLVE_COMMENTS', 'Handles resolving comments in the Manage Entity Corporate Family section.', 'quickstart', now(), '1');

INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) 
VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_ENTITY_COMPLIANCE_RESOLVE_COMMENTS', 'Handles resolving comments in the Manage Entity Compliance section.', 'quickstart', now(), '1');

INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) 
VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_ENTITY_ORGANIZATION_RESOLVE_COMMENTS', 'Handles resolving comments in the Manage Entity Organization section.', 'quickstart', now(), '1');

INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) 
VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_ENTITY_SPONSOR_RESOLVE_COMMENTS', 'Handles resolving comments in the Manage Entity Sponsor section.', 'quickstart', now(), '1');

INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) 
VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_OPA_RESOLVE_COMMENTS', 'Handles resolving comments in the Manage OPA section.', 'quickstart', now(), '1');

INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) 
VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_TRAVEL_RESOLVE_COMMENTS', 'Handles resolving comments in the Manage Travel section.', 'quickstart', now(), '1');

ALTER TABLE DISCL_COMMENT 
ADD COLUMN IS_RESOLVED VARCHAR(1) NULL DEFAULT NULL AFTER FORM_BUILDER_COMPONENT_ID,
ADD COLUMN RESOLVED_BY VARCHAR(60) NULL DEFAULT NULL AFTER IS_RESOLVED,
ADD COLUMN RESOLVED_TIMESTAMP DATETIME NULL DEFAULT NULL AFTER RESOLVED_BY;

ALTER TABLE COI_PROJECT_COMMENT 
ADD COLUMN IS_RESOLVED VARCHAR(1) NULL DEFAULT NULL AFTER MODULE_ITEM_KEY,
ADD COLUMN RESOLVED_BY VARCHAR(60) NULL DEFAULT NULL AFTER IS_RESOLVED,
ADD COLUMN RESOLVED_TIMESTAMP DATETIME NULL DEFAULT NULL AFTER RESOLVED_BY;

ALTER TABLE ENTITY_COMMENT 
ADD COLUMN IS_RESOLVED VARCHAR(1) NULL DEFAULT NULL AFTER PARENT_COMMENT_ID,
ADD COLUMN RESOLVED_BY VARCHAR(60) NULL DEFAULT NULL AFTER IS_RESOLVED,
ADD COLUMN RESOLVED_TIMESTAMP DATETIME NULL DEFAULT NULL AFTER RESOLVED_BY;
