DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS COI_DISCL_AFFILIATED_UNITS_INSERTION;
DROP PROCEDURE IF EXISTS EVALUATE_OPA_QUESTIONNAIRE;
DROP PROCEDURE IF EXISTS EVALUATE_FORM_RESPONSE;
DROP PROCEDURE IF EXISTS GET_AWARD_DASHBOARD_OVERVIEW;
DROP PROCEDURE IF EXISTS SYNC_OPA_DISCL_PERSON_ENTITY_REL;
DROP FUNCTION IF EXISTS FN_CHK_IS_HOME_UNIT_SUBMISSION;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
