DELIMITER //
create or replace PROCEDURE FIBI_COI_SYNC_PERSON_DETAILS (
    AV_PERSON_ID IN FIBI_COI_PERSON.PERSON_ID%TYPE,
	AV_DATE IN WHOSP_PERSON_HISTORY.UPDATE_TIMESTAMP%TYPE,
   cur_generic       OUT SYS_REFCURSOR)
  
   IS
  
    LI_COUNT NUMBER := 0;
    LS_ERROR_FLAG VARCHAR2(20) DEFAULT 'TRUE';
    LI_BEFORE_DATA_COUNT NUMBER := 0;
    LI_AFTER_DATA_COUNT NUMBER := 0;
    LI_TOTAL_COUNT NUMBER := 0;
    LS_PERSON_IDS CLOB := '';
	LI_AFFECTED_ROWS NUMBER := 0;
    LI_DATA_COUNT NUMBER := 0;

BEGIN
BEGIN
SELECT COUNT(1) INTO LI_DATA_COUNT FROM FIBI_COI_PERSON WHERE ROWNUM<= 2;

IF LI_DATA_COUNT = 0 THEN
	INSERT INTO FIBI_COI_PERSON (
	PERSON_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, PRIOR_NAME,
	USER_NAME, EMAIL_ADDRESS, DATE_OF_BIRTH, AGE, AGE_BY_FISCAL_YEAR,
	GENDER, EDUCATION_LEVEL, OFFICE_LOCATION, OFFICE_PHONE,
	SECONDRY_OFFICE_LOCATION, SECONDRY_OFFICE_PHONE, SCHOOL,
	DIRECTORY_DEPARTMENT, SALUTATION, COUNTRY_OF_CITIZENSHIP,
	PRIMARY_TITLE, DIRECTORY_TITLE, HOME_UNIT, IS_FACULTY,
	IS_GRADUATE_STUDENT_STAFF, IS_RESEARCH_STAFF, IS_SERVICE_STAFF,
	IS_SUPPORT_STAFF, IS_OTHER_ACCADEMIC_GROUP, IS_MEDICAL_STAFF,
	ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, CITY, COUNTY, STATE,
	POSTAL_CODE, COUNTRY_CODE, FAX_NUMBER, PAGER_NUMBER,
	MOBILE_PHONE_NUMBER, VISA_CODE, VISA_TYPE, VISA_RENEWAL_DATE,
	STATUS, SALARY_ANNIVERSARY_DATE, UPDATE_TIMESTAMP, UPDATE_USER
		)
	SELECT 
	PERSON_ID, SUBSTR(LAST_NAME, 1, 30), SUBSTR(FIRST_NAME, 1, 30), 
	SUBSTR(MIDDLE_NAME, 1, 30), SUBSTR(FULL_NAME, 1, 901), PRIOR_NAME,
	USER_NAME, EMAIL_ADDRESS, 
	TO_DATE(DATE_OF_BIRTH, 'DD-MM-YY'), AGE, AGE_BY_FISCAL_YEAR,
	GENDER, EDUCATION_LEVEL, OFFICE_LOCATION, OFFICE_PHONE,
	SECONDRY_OFFICE_LOCATION, SECONDRY_OFFICE_PHONE, SUBSTR(SCHOOL,1,50),
	DIRECTORY_DEPARTMENT, SALUTATION, COUNTRY_OF_CITIZENSHIP,
	PRIMARY_TITLE, DIRECTORY_TITLE, HOME_UNIT, IS_FACULTY,
	IS_GRADUATE_STUDENT_STAFF, IS_RESEARCH_STAFF, IS_SERVICE_STAFF,
	IS_SUPPORT_STAFF, IS_OTHER_ACCADEMIC_GROUP, IS_MEDICAL_STAFF,
	ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, CITY, COUNTY, STATE,
	POSTAL_CODE, COUNTRY_CODE, FAX_NUMBER, PAGER_NUMBER,
	MOBILE_PHONE_NUMBER, VISA_CODE, VISA_TYPE, 
	TO_DATE(VISA_RENEWAL_DATE, 'DD-MM-YY'), NVL(STATUS,'N'),
	TO_DATE(SALARY_ANNIVERSARY_DATE, 'DD-MM-YY'), SYSDATE, UPDATE_USER
	FROM WHOSP_PERSON_HISTORY;

    COMMIT;
END IF;  

SELECT COUNT(1) INTO LI_BEFORE_DATA_COUNT FROM FIBI_COI_PERSON;

IF AV_PERSON_ID IS NOT NULL THEN 

	MERGE INTO FIBI_COI_PERSON target
		USING (
			SELECT * 
			FROM WHOSP_PERSON_HISTORY WHERE PERSON_ID = AV_PERSON_ID
		) source
		ON (target.PERSON_ID = source.PERSON_ID)
		WHEN MATCHED THEN
			UPDATE
			SET LAST_NAME = SUBSTR(source.LAST_NAME,1,30),
				FIRST_NAME = SUBSTR(source.FIRST_NAME,1,30),
				MIDDLE_NAME = SUBSTR(source.MIDDLE_NAME,1,30),
				FULL_NAME = SUBSTR(source.FULL_NAME,1,90),
				PRIOR_NAME = source.PRIOR_NAME,
				USER_NAME = source.USER_NAME,
				EMAIL_ADDRESS = source.EMAIL_ADDRESS,
				DATE_OF_BIRTH = TO_DATE(source.DATE_OF_BIRTH, 'DD-MM-YY'),
				AGE = source.AGE,
				EDUCATION_LEVEL = source.EDUCATION_LEVEL,
				AGE_BY_FISCAL_YEAR = source.AGE_BY_FISCAL_YEAR,
				GENDER = source.GENDER,
				OFFICE_LOCATION = source.OFFICE_LOCATION,
				OFFICE_PHONE = source.OFFICE_PHONE,
				SECONDRY_OFFICE_LOCATION = source.SECONDRY_OFFICE_LOCATION,
				SECONDRY_OFFICE_PHONE = source.SECONDRY_OFFICE_PHONE,
				SCHOOL = SUBSTR(source.SCHOOL,1,50),
				DIRECTORY_DEPARTMENT = source.DIRECTORY_DEPARTMENT,
				SALUTATION = source.SALUTATION,
				COUNTRY_OF_CITIZENSHIP = source.COUNTRY_OF_CITIZENSHIP,
				PRIMARY_TITLE = source.PRIMARY_TITLE,
				DIRECTORY_TITLE = source.DIRECTORY_TITLE,
				HOME_UNIT = source.HOME_UNIT,
				IS_FACULTY = source.IS_FACULTY,
				IS_GRADUATE_STUDENT_STAFF = source.IS_GRADUATE_STUDENT_STAFF,
				IS_RESEARCH_STAFF = source.IS_RESEARCH_STAFF,
				IS_SERVICE_STAFF = source.IS_SERVICE_STAFF,
				IS_SUPPORT_STAFF = source.IS_SUPPORT_STAFF,
				IS_OTHER_ACCADEMIC_GROUP = source.IS_OTHER_ACCADEMIC_GROUP,
				IS_MEDICAL_STAFF = source.IS_MEDICAL_STAFF,
				UPDATE_USER = source.UPDATE_USER,
				VISA_CODE = source.VISA_CODE,
				VISA_TYPE = source.VISA_TYPE,
				VISA_RENEWAL_DATE = TO_DATE(source.VISA_RENEWAL_DATE, 'DD-MM-YY'),
				
				ADDRESS_LINE_1 = source.ADDRESS_LINE_1,
				ADDRESS_LINE_2 = source.ADDRESS_LINE_2,
				ADDRESS_LINE_3 = source.ADDRESS_LINE_3,
				CITY = source.CITY,
				COUNTY = source.COUNTY,
				STATE = source.STATE,
				POSTAL_CODE = source.POSTAL_CODE,
				COUNTRY_CODE = source.COUNTRY_CODE,
				FAX_NUMBER = source.FAX_NUMBER,
				PAGER_NUMBER = source.PAGER_NUMBER,
				MOBILE_PHONE_NUMBER = source.MOBILE_PHONE_NUMBER,
				STATUS = NVL(source.STATUS,'N'),
				SALARY_ANNIVERSARY_DATE = TO_DATE(source.SALARY_ANNIVERSARY_DATE, 'DD-MM-YY'),
				
				
				UPDATE_TIMESTAMP = CASE 
									WHEN ( NVL(target.LAST_NAME,' ') != NVL(SUBSTR(source.LAST_NAME,1,30),' ') OR
											NVL(target.FIRST_NAME,' ') != NVL(SUBSTR(source.FIRST_NAME,1,30),' ') OR
											NVL(target.MIDDLE_NAME,' ') != NVL(SUBSTR(source.MIDDLE_NAME,1,30),' ') OR
											NVL(target.FULL_NAME,' ') != NVL(SUBSTR(source.FULL_NAME,1,90),' ') OR
											NVL(target.PRIOR_NAME,' ') != NVL(source.PRIOR_NAME,' ') OR
											NVL(target.USER_NAME,' ') != NVL(source.USER_NAME,' ') OR
											NVL(target.EMAIL_ADDRESS,' ') != NVL(source.EMAIL_ADDRESS,' ') OR
											TO_DATE(NVL(target.DATE_OF_BIRTH,'01-JAN-01'), 'DD-MM-YY') != TO_DATE(NVL(source.DATE_OF_BIRTH,'01-JAN-01'), 'DD-MM-YY') OR
											NVL(TO_NUMBER(target.AGE),0) != NVL(TO_NUMBER(source.AGE),0) OR
											NVL(target.EDUCATION_LEVEL,' ') != NVL(source.EDUCATION_LEVEL,' ') OR
											NVL(TO_NUMBER(target.AGE_BY_FISCAL_YEAR),0) != NVL(TO_NUMBER(source.AGE_BY_FISCAL_YEAR),0) OR
											NVL(target.GENDER,' ') != NVL(source.GENDER,' ') OR
											NVL(target.OFFICE_LOCATION,' ') != NVL(source.OFFICE_LOCATION,' ') OR
											NVL(target.OFFICE_PHONE,' ') != NVL(source.OFFICE_PHONE,' ') OR
											NVL(target.SECONDRY_OFFICE_LOCATION,' ') != NVL(source.SECONDRY_OFFICE_LOCATION,' ') OR
											NVL(target.SECONDRY_OFFICE_PHONE,' ') != NVL(source.SECONDRY_OFFICE_PHONE,' ') OR
											NVL(target.SCHOOL,' ') != NVL(SUBSTR(source.SCHOOL,1,50),' ') OR
											NVL(target.DIRECTORY_DEPARTMENT,' ') != NVL(source.DIRECTORY_DEPARTMENT,' ') OR
											NVL(target.SALUTATION,' ') != NVL(source.SALUTATION,' ') OR
											NVL(target.COUNTRY_OF_CITIZENSHIP,' ') != NVL(source.COUNTRY_OF_CITIZENSHIP,' ') OR
											NVL(target.PRIMARY_TITLE,' ') != NVL(source.PRIMARY_TITLE,' ') OR
											NVL(target.DIRECTORY_TITLE,' ') != NVL(source.DIRECTORY_TITLE,' ') OR
											NVL(target.HOME_UNIT,' ') != NVL(source.HOME_UNIT,' ') OR
											NVL(target.IS_FACULTY,' ') != NVL(source.IS_FACULTY,' ') OR
											NVL(target.IS_GRADUATE_STUDENT_STAFF,' ') != NVL(source.IS_GRADUATE_STUDENT_STAFF,' ') OR
											NVL(target.IS_RESEARCH_STAFF,' ') != NVL(source.IS_RESEARCH_STAFF,' ') OR
											NVL(target.IS_SERVICE_STAFF,' ') != NVL(source.IS_SERVICE_STAFF,' ') OR
											NVL(target.IS_SUPPORT_STAFF,' ') != NVL(source.IS_SUPPORT_STAFF,' ') OR
											NVL(target.IS_OTHER_ACCADEMIC_GROUP,' ') != NVL(source.IS_OTHER_ACCADEMIC_GROUP,' ') OR
											NVL(target.IS_MEDICAL_STAFF,' ') != NVL(source.IS_MEDICAL_STAFF,' ') OR
											NVL(target.VISA_CODE,' ') != NVL(source.VISA_CODE,' ') OR
											NVL(target.VISA_TYPE,' ') != NVL(source.VISA_TYPE,' ') OR
											
											NVL(target.ADDRESS_LINE_1,' ') != NVL(source.ADDRESS_LINE_1,' ') OR
											NVL(target.ADDRESS_LINE_2,' ') != NVL(source.ADDRESS_LINE_2,' ') OR
											NVL(target.ADDRESS_LINE_3,' ') != NVL(source.ADDRESS_LINE_3,' ') OR
											NVL(target.CITY,' ') != NVL(source.CITY,' ') OR
											NVL(target.COUNTY,' ') != NVL(source.COUNTY,' ') OR
											NVL(target.STATE,' ') != NVL(source.STATE,' ') OR
											NVL(target.POSTAL_CODE,' ') != NVL(source.POSTAL_CODE,' ') OR
											NVL(target.COUNTRY_CODE,' ') != NVL(source.COUNTRY_CODE,' ') OR
											NVL(target.FAX_NUMBER,' ') != NVL(source.FAX_NUMBER,' ') OR
											NVL(target.PAGER_NUMBER,' ') != NVL(source.PAGER_NUMBER,' ') OR
											NVL(target.MOBILE_PHONE_NUMBER,' ') != NVL(source.MOBILE_PHONE_NUMBER,' ') OR
											NVL(target.STATUS,' ') != NVL(source.STATUS,' ') OR
											TO_DATE(NVL(target.SALARY_ANNIVERSARY_DATE,'01-JAN-01'), 'DD-MM-YY') != TO_DATE(NVL(source.SALARY_ANNIVERSARY_DATE,'01-JAN-01'), 'DD-MM-YY') OR
											
											TO_DATE(NVL(target.VISA_RENEWAL_DATE,'01-JAN-01'), 'DD-MM-YY') != TO_DATE(NVL(source.VISA_RENEWAL_DATE,'01-JAN-01'), 'DD-MM-YY'))
									THEN TO_DATE(SYSDATE, 'DD-MM-YY')
									ELSE TO_DATE(target.UPDATE_TIMESTAMP, 'DD-MM-YY')
								END
		WHEN NOT MATCHED THEN
			INSERT (
				PERSON_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME,FULL_NAME, PRIOR_NAME, USER_NAME, EMAIL_ADDRESS, 
				DATE_OF_BIRTH, AGE, EDUCATION_LEVEL, AGE_BY_FISCAL_YEAR, GENDER, OFFICE_LOCATION, OFFICE_PHONE, 
				SECONDRY_OFFICE_LOCATION, SECONDRY_OFFICE_PHONE, SCHOOL, DIRECTORY_DEPARTMENT, SALUTATION, 
				COUNTRY_OF_CITIZENSHIP, PRIMARY_TITLE, DIRECTORY_TITLE, HOME_UNIT, IS_FACULTY, IS_GRADUATE_STUDENT_STAFF, 
				IS_RESEARCH_STAFF, IS_SERVICE_STAFF, IS_SUPPORT_STAFF, IS_OTHER_ACCADEMIC_GROUP, IS_MEDICAL_STAFF, 
				UPDATE_TIMESTAMP, UPDATE_USER, VISA_CODE, VISA_TYPE, VISA_RENEWAL_DATE,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,
				CITY,COUNTY,STATE,POSTAL_CODE,COUNTRY_CODE,FAX_NUMBER,PAGER_NUMBER,MOBILE_PHONE_NUMBER,STATUS,SALARY_ANNIVERSARY_DATE
			)
			VALUES (
				source.PERSON_ID, SUBSTR(source.LAST_NAME,1,30), SUBSTR(source.FIRST_NAME,1,30), SUBSTR(source.MIDDLE_NAME,1,30), SUBSTR(source.FULL_NAME,1,90), source.PRIOR_NAME, 
				source.USER_NAME, source.EMAIL_ADDRESS, TO_DATE(source.DATE_OF_BIRTH, 'DD-MM-YY'), source.AGE, source.EDUCATION_LEVEL, source.AGE_BY_FISCAL_YEAR, 
				source.GENDER, source.OFFICE_LOCATION, source.OFFICE_PHONE, source.SECONDRY_OFFICE_LOCATION, source.SECONDRY_OFFICE_PHONE, 
				SUBSTR(source.SCHOOL,1,50), source.DIRECTORY_DEPARTMENT, source.SALUTATION, source.COUNTRY_OF_CITIZENSHIP, source.PRIMARY_TITLE, 
				source.DIRECTORY_TITLE, source.HOME_UNIT, source.IS_FACULTY, source.IS_GRADUATE_STUDENT_STAFF, source.IS_RESEARCH_STAFF, 
				source.IS_SERVICE_STAFF, source.IS_SUPPORT_STAFF, source.IS_OTHER_ACCADEMIC_GROUP, source.IS_MEDICAL_STAFF, 
				TO_DATE(SYSDATE, 'DD-MM-YY'), source.UPDATE_USER, source.VISA_CODE, source.VISA_TYPE, TO_DATE(source.VISA_RENEWAL_DATE, 'DD-MM-YY'),
				source.ADDRESS_LINE_1,source.ADDRESS_LINE_2,source.ADDRESS_LINE_3,source.CITY,
				source.COUNTY,source.STATE,source.POSTAL_CODE,source.COUNTRY_CODE,source.FAX_NUMBER,
				source.PAGER_NUMBER,source.MOBILE_PHONE_NUMBER,
				NVL(source.STATUS,'N'),TO_DATE(source.SALARY_ANNIVERSARY_DATE, 'DD-MM-YY')				
			);

LI_AFFECTED_ROWS := SQL%ROWCOUNT;
COMMIT;
END IF;

IF AV_DATE IS NOT NULL THEN

	MERGE INTO FIBI_COI_PERSON target
		USING (
			SELECT * 
			FROM WHOSP_PERSON_HISTORY WHERE TO_DATE(UPDATE_TIMESTAMP, 'DD-MM-YY') = TO_DATE(AV_DATE, 'DD-MM-YY')
		) source
		ON (target.PERSON_ID = source.PERSON_ID)
		WHEN MATCHED THEN
			UPDATE
			SET LAST_NAME = SUBSTR(source.LAST_NAME,1,30),
				FIRST_NAME = SUBSTR(source.FIRST_NAME,1,30),
				MIDDLE_NAME = SUBSTR(source.MIDDLE_NAME,1,30),
				FULL_NAME = SUBSTR(source.FULL_NAME,1,90),
				PRIOR_NAME = source.PRIOR_NAME,
				USER_NAME = source.USER_NAME,
				EMAIL_ADDRESS = source.EMAIL_ADDRESS,
				DATE_OF_BIRTH = TO_DATE(source.DATE_OF_BIRTH, 'DD-MM-YY'),
				AGE = source.AGE,
				EDUCATION_LEVEL = source.EDUCATION_LEVEL,
				AGE_BY_FISCAL_YEAR = source.AGE_BY_FISCAL_YEAR,
				GENDER = source.GENDER,
				OFFICE_LOCATION = source.OFFICE_LOCATION,
				OFFICE_PHONE = source.OFFICE_PHONE,
				SECONDRY_OFFICE_LOCATION = source.SECONDRY_OFFICE_LOCATION,
				SECONDRY_OFFICE_PHONE = source.SECONDRY_OFFICE_PHONE,
				SCHOOL = SUBSTR(source.SCHOOL,1,50),
				DIRECTORY_DEPARTMENT = source.DIRECTORY_DEPARTMENT,
				SALUTATION = source.SALUTATION,
				COUNTRY_OF_CITIZENSHIP = source.COUNTRY_OF_CITIZENSHIP,
				PRIMARY_TITLE = source.PRIMARY_TITLE,
				DIRECTORY_TITLE = source.DIRECTORY_TITLE,
				HOME_UNIT = source.HOME_UNIT,
				IS_FACULTY = source.IS_FACULTY,
				IS_GRADUATE_STUDENT_STAFF = source.IS_GRADUATE_STUDENT_STAFF,
				IS_RESEARCH_STAFF = source.IS_RESEARCH_STAFF,
				IS_SERVICE_STAFF = source.IS_SERVICE_STAFF,
				IS_SUPPORT_STAFF = source.IS_SUPPORT_STAFF,
				IS_OTHER_ACCADEMIC_GROUP = source.IS_OTHER_ACCADEMIC_GROUP,
				IS_MEDICAL_STAFF = source.IS_MEDICAL_STAFF,
				UPDATE_USER = source.UPDATE_USER,
				VISA_CODE = source.VISA_CODE,
				VISA_TYPE = source.VISA_TYPE,
				VISA_RENEWAL_DATE = TO_DATE(source.VISA_RENEWAL_DATE, 'DD-MM-YY'),
				
				ADDRESS_LINE_1 = source.ADDRESS_LINE_1,
				ADDRESS_LINE_2 = source.ADDRESS_LINE_2,
				ADDRESS_LINE_3 = source.ADDRESS_LINE_3,
				CITY = source.CITY,
				COUNTY = source.COUNTY,
				STATE = source.STATE,
				POSTAL_CODE = source.POSTAL_CODE,
				COUNTRY_CODE = source.COUNTRY_CODE,
				FAX_NUMBER = source.FAX_NUMBER,
				PAGER_NUMBER = source.PAGER_NUMBER,
				MOBILE_PHONE_NUMBER = source.MOBILE_PHONE_NUMBER,
				STATUS = NVL(source.STATUS,'N'),
				SALARY_ANNIVERSARY_DATE = TO_DATE(source.SALARY_ANNIVERSARY_DATE, 'DD-MM-YY'),
				
				
				UPDATE_TIMESTAMP = CASE 
									WHEN ( NVL(target.LAST_NAME,' ') != NVL(SUBSTR(source.LAST_NAME,1,30),' ') OR
											NVL(target.FIRST_NAME,' ') != NVL(SUBSTR(source.FIRST_NAME,1,30),' ') OR
											NVL(target.MIDDLE_NAME,' ') != NVL(SUBSTR(source.MIDDLE_NAME,1,30),' ') OR
											NVL(target.FULL_NAME,' ') != NVL(SUBSTR(source.FULL_NAME,1,90),' ') OR
											NVL(target.PRIOR_NAME,' ') != NVL(source.PRIOR_NAME,' ') OR
											NVL(target.USER_NAME,' ') != NVL(source.USER_NAME,' ') OR
											NVL(target.EMAIL_ADDRESS,' ') != NVL(source.EMAIL_ADDRESS,' ') OR
											TO_DATE(NVL(target.DATE_OF_BIRTH,'01-JAN-01'), 'DD-MM-YY') != TO_DATE(NVL(source.DATE_OF_BIRTH,'01-JAN-01'), 'DD-MM-YY') OR
											NVL(TO_NUMBER(target.AGE),0) != NVL(TO_NUMBER(source.AGE),0) OR
											NVL(target.EDUCATION_LEVEL,' ') != NVL(source.EDUCATION_LEVEL,' ') OR
											NVL(TO_NUMBER(target.AGE_BY_FISCAL_YEAR),0) != NVL(TO_NUMBER(source.AGE_BY_FISCAL_YEAR),0) OR
											NVL(target.GENDER,' ') != NVL(source.GENDER,' ') OR
											NVL(target.OFFICE_LOCATION,' ') != NVL(source.OFFICE_LOCATION,' ') OR
											NVL(target.OFFICE_PHONE,' ') != NVL(source.OFFICE_PHONE,' ') OR
											NVL(target.SECONDRY_OFFICE_LOCATION,' ') != NVL(source.SECONDRY_OFFICE_LOCATION,' ') OR
											NVL(target.SECONDRY_OFFICE_PHONE,' ') != NVL(source.SECONDRY_OFFICE_PHONE,' ') OR
											NVL(target.SCHOOL,' ') != NVL(SUBSTR(source.SCHOOL,1,50),' ') OR
											NVL(target.DIRECTORY_DEPARTMENT,' ') != NVL(source.DIRECTORY_DEPARTMENT,' ') OR
											NVL(target.SALUTATION,' ') != NVL(source.SALUTATION,' ') OR
											NVL(target.COUNTRY_OF_CITIZENSHIP,' ') != NVL(source.COUNTRY_OF_CITIZENSHIP,' ') OR
											NVL(target.PRIMARY_TITLE,' ') != NVL(source.PRIMARY_TITLE,' ') OR
											NVL(target.DIRECTORY_TITLE,' ') != NVL(source.DIRECTORY_TITLE,' ') OR
											NVL(target.HOME_UNIT,' ') != NVL(source.HOME_UNIT,' ') OR
											NVL(target.IS_FACULTY,' ') != NVL(source.IS_FACULTY,' ') OR
											NVL(target.IS_GRADUATE_STUDENT_STAFF,' ') != NVL(source.IS_GRADUATE_STUDENT_STAFF,' ') OR
											NVL(target.IS_RESEARCH_STAFF,' ') != NVL(source.IS_RESEARCH_STAFF,' ') OR
											NVL(target.IS_SERVICE_STAFF,' ') != NVL(source.IS_SERVICE_STAFF,' ') OR
											NVL(target.IS_SUPPORT_STAFF,' ') != NVL(source.IS_SUPPORT_STAFF,' ') OR
											NVL(target.IS_OTHER_ACCADEMIC_GROUP,' ') != NVL(source.IS_OTHER_ACCADEMIC_GROUP,' ') OR
											NVL(target.IS_MEDICAL_STAFF,' ') != NVL(source.IS_MEDICAL_STAFF,' ') OR
											NVL(target.VISA_CODE,' ') != NVL(source.VISA_CODE,' ') OR
											NVL(target.VISA_TYPE,' ') != NVL(source.VISA_TYPE,' ') OR
											
											NVL(target.ADDRESS_LINE_1,' ') != NVL(source.ADDRESS_LINE_1,' ') OR
											NVL(target.ADDRESS_LINE_2,' ') != NVL(source.ADDRESS_LINE_2,' ') OR
											NVL(target.ADDRESS_LINE_3,' ') != NVL(source.ADDRESS_LINE_3,' ') OR
											NVL(target.CITY,' ') != NVL(source.CITY,' ') OR
											NVL(target.COUNTY,' ') != NVL(source.COUNTY,' ') OR
											NVL(target.STATE,' ') != NVL(source.STATE,' ') OR
											NVL(target.POSTAL_CODE,' ') != NVL(source.POSTAL_CODE,' ') OR
											NVL(target.COUNTRY_CODE,' ') != NVL(source.COUNTRY_CODE,' ') OR
											NVL(target.FAX_NUMBER,' ') != NVL(source.FAX_NUMBER,' ') OR
											NVL(target.PAGER_NUMBER,' ') != NVL(source.PAGER_NUMBER,' ') OR
											NVL(target.MOBILE_PHONE_NUMBER,' ') != NVL(source.MOBILE_PHONE_NUMBER,' ') OR
											NVL(target.STATUS,' ') != NVL(source.STATUS,' ') OR
											TO_DATE(NVL(target.SALARY_ANNIVERSARY_DATE,'01-JAN-01'), 'DD-MM-YY') != TO_DATE(NVL(source.SALARY_ANNIVERSARY_DATE,'01-JAN-01'), 'DD-MM-YY') OR
											
											TO_DATE(NVL(target.VISA_RENEWAL_DATE,'01-JAN-01'), 'DD-MM-YY') != TO_DATE(NVL(source.VISA_RENEWAL_DATE,'01-JAN-01'), 'DD-MM-YY'))
									THEN TO_DATE(SYSDATE, 'DD-MM-YY')
									ELSE TO_DATE(target.UPDATE_TIMESTAMP, 'DD-MM-YY')
								END
		WHEN NOT MATCHED THEN
			INSERT (
				PERSON_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME,FULL_NAME, PRIOR_NAME, USER_NAME, EMAIL_ADDRESS, 
				DATE_OF_BIRTH, AGE, EDUCATION_LEVEL, AGE_BY_FISCAL_YEAR, GENDER, OFFICE_LOCATION, OFFICE_PHONE, 
				SECONDRY_OFFICE_LOCATION, SECONDRY_OFFICE_PHONE, SCHOOL, DIRECTORY_DEPARTMENT, SALUTATION, 
				COUNTRY_OF_CITIZENSHIP, PRIMARY_TITLE, DIRECTORY_TITLE, HOME_UNIT, IS_FACULTY, IS_GRADUATE_STUDENT_STAFF, 
				IS_RESEARCH_STAFF, IS_SERVICE_STAFF, IS_SUPPORT_STAFF, IS_OTHER_ACCADEMIC_GROUP, IS_MEDICAL_STAFF, 
				UPDATE_TIMESTAMP, UPDATE_USER, VISA_CODE, VISA_TYPE, VISA_RENEWAL_DATE,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,
				CITY,COUNTY,STATE,POSTAL_CODE,COUNTRY_CODE,FAX_NUMBER,PAGER_NUMBER,MOBILE_PHONE_NUMBER,STATUS,SALARY_ANNIVERSARY_DATE
			)
			VALUES (
				source.PERSON_ID, SUBSTR(source.LAST_NAME,1,30), SUBSTR(source.FIRST_NAME,1,30), SUBSTR(source.MIDDLE_NAME,1,30), SUBSTR(source.FULL_NAME,1,90), source.PRIOR_NAME, 
				source.USER_NAME, source.EMAIL_ADDRESS, TO_DATE(source.DATE_OF_BIRTH, 'DD-MM-YY'), source.AGE, source.EDUCATION_LEVEL, source.AGE_BY_FISCAL_YEAR, 
				source.GENDER, source.OFFICE_LOCATION, source.OFFICE_PHONE, source.SECONDRY_OFFICE_LOCATION, source.SECONDRY_OFFICE_PHONE, 
				SUBSTR(source.SCHOOL,1,50), source.DIRECTORY_DEPARTMENT, source.SALUTATION, source.COUNTRY_OF_CITIZENSHIP, source.PRIMARY_TITLE, 
				source.DIRECTORY_TITLE, source.HOME_UNIT, source.IS_FACULTY, source.IS_GRADUATE_STUDENT_STAFF, source.IS_RESEARCH_STAFF, 
				source.IS_SERVICE_STAFF, source.IS_SUPPORT_STAFF, source.IS_OTHER_ACCADEMIC_GROUP, source.IS_MEDICAL_STAFF, 
				TO_DATE(SYSDATE, 'DD-MM-YY'), source.UPDATE_USER, source.VISA_CODE, source.VISA_TYPE, TO_DATE(source.VISA_RENEWAL_DATE, 'DD-MM-YY'),
				source.ADDRESS_LINE_1,source.ADDRESS_LINE_2,source.ADDRESS_LINE_3,source.CITY,
				source.COUNTY,source.STATE,source.POSTAL_CODE,source.COUNTRY_CODE,source.FAX_NUMBER,
				source.PAGER_NUMBER,source.MOBILE_PHONE_NUMBER,
				NVL(source.STATUS,'N'),TO_DATE(source.SALARY_ANNIVERSARY_DATE, 'DD-MM-YY')				
			);

LI_AFFECTED_ROWS := SQL%ROWCOUNT;
COMMIT;

END IF;

IF AV_PERSON_ID IS NULL AND AV_DATE IS NULL AND LI_DATA_COUNT > 0 THEN
	MERGE INTO FIBI_COI_PERSON target
		USING (
			SELECT * 
			FROM WHOSP_PERSON_HISTORY 
		) source
		ON (target.PERSON_ID = source.PERSON_ID)
		WHEN MATCHED THEN
			UPDATE
			SET LAST_NAME = SUBSTR(source.LAST_NAME,1,30),
				FIRST_NAME = SUBSTR(source.FIRST_NAME,1,30),
				MIDDLE_NAME = SUBSTR(source.MIDDLE_NAME,1,30),
				FULL_NAME = SUBSTR(source.FULL_NAME,1,90),
				PRIOR_NAME = source.PRIOR_NAME,
				USER_NAME = source.USER_NAME,
				EMAIL_ADDRESS = source.EMAIL_ADDRESS,
				DATE_OF_BIRTH = TO_DATE(source.DATE_OF_BIRTH, 'DD-MM-YY'),
				AGE = source.AGE,
				EDUCATION_LEVEL = source.EDUCATION_LEVEL,
				AGE_BY_FISCAL_YEAR = source.AGE_BY_FISCAL_YEAR,
				GENDER = source.GENDER,
				OFFICE_LOCATION = source.OFFICE_LOCATION,
				OFFICE_PHONE = source.OFFICE_PHONE,
				SECONDRY_OFFICE_LOCATION = source.SECONDRY_OFFICE_LOCATION,
				SECONDRY_OFFICE_PHONE = source.SECONDRY_OFFICE_PHONE,
				SCHOOL = SUBSTR(source.SCHOOL,1,50),
				DIRECTORY_DEPARTMENT = source.DIRECTORY_DEPARTMENT,
				SALUTATION = source.SALUTATION,
				COUNTRY_OF_CITIZENSHIP = source.COUNTRY_OF_CITIZENSHIP,
				PRIMARY_TITLE = source.PRIMARY_TITLE,
				DIRECTORY_TITLE = source.DIRECTORY_TITLE,
				HOME_UNIT = source.HOME_UNIT,
				IS_FACULTY = source.IS_FACULTY,
				IS_GRADUATE_STUDENT_STAFF = source.IS_GRADUATE_STUDENT_STAFF,
				IS_RESEARCH_STAFF = source.IS_RESEARCH_STAFF,
				IS_SERVICE_STAFF = source.IS_SERVICE_STAFF,
				IS_SUPPORT_STAFF = source.IS_SUPPORT_STAFF,
				IS_OTHER_ACCADEMIC_GROUP = source.IS_OTHER_ACCADEMIC_GROUP,
				IS_MEDICAL_STAFF = source.IS_MEDICAL_STAFF,
				UPDATE_USER = source.UPDATE_USER,
				VISA_CODE = source.VISA_CODE,
				VISA_TYPE = source.VISA_TYPE,
				VISA_RENEWAL_DATE = TO_DATE(source.VISA_RENEWAL_DATE, 'DD-MM-YY'),
				
				ADDRESS_LINE_1 = source.ADDRESS_LINE_1,
				ADDRESS_LINE_2 = source.ADDRESS_LINE_2,
				ADDRESS_LINE_3 = source.ADDRESS_LINE_3,
				CITY = source.CITY,
				COUNTY = source.COUNTY,
				STATE = source.STATE,
				POSTAL_CODE = source.POSTAL_CODE,
				COUNTRY_CODE = source.COUNTRY_CODE,
				FAX_NUMBER = source.FAX_NUMBER,
				PAGER_NUMBER = source.PAGER_NUMBER,
				MOBILE_PHONE_NUMBER = source.MOBILE_PHONE_NUMBER,
				STATUS = NVL(source.STATUS,'N'),
				SALARY_ANNIVERSARY_DATE = TO_DATE(source.SALARY_ANNIVERSARY_DATE, 'DD-MM-YY'),
				
				
				UPDATE_TIMESTAMP = CASE 
									WHEN ( NVL(target.LAST_NAME,' ') != NVL(SUBSTR(source.LAST_NAME,1,30),' ') OR
											NVL(target.FIRST_NAME,' ') != NVL(SUBSTR(source.FIRST_NAME,1,30),' ') OR
											NVL(target.MIDDLE_NAME,' ') != NVL(SUBSTR(source.MIDDLE_NAME,1,30),' ') OR
											NVL(target.FULL_NAME,' ') != NVL(SUBSTR(source.FULL_NAME,1,90),' ') OR
											NVL(target.PRIOR_NAME,' ') != NVL(source.PRIOR_NAME,' ') OR
											NVL(target.USER_NAME,' ') != NVL(source.USER_NAME,' ') OR
											NVL(target.EMAIL_ADDRESS,' ') != NVL(source.EMAIL_ADDRESS,' ') OR
											TO_DATE(NVL(target.DATE_OF_BIRTH,'01-JAN-01'), 'DD-MM-YY') != TO_DATE(NVL(source.DATE_OF_BIRTH,'01-JAN-01'), 'DD-MM-YY') OR
											NVL(TO_NUMBER(target.AGE),0) != NVL(TO_NUMBER(source.AGE),0) OR
											NVL(target.EDUCATION_LEVEL,' ') != NVL(source.EDUCATION_LEVEL,' ') OR
											NVL(TO_NUMBER(target.AGE_BY_FISCAL_YEAR),0) != NVL(TO_NUMBER(source.AGE_BY_FISCAL_YEAR),0) OR
											NVL(target.GENDER,' ') != NVL(source.GENDER,' ') OR
											NVL(target.OFFICE_LOCATION,' ') != NVL(source.OFFICE_LOCATION,' ') OR
											NVL(target.OFFICE_PHONE,' ') != NVL(source.OFFICE_PHONE,' ') OR
											NVL(target.SECONDRY_OFFICE_LOCATION,' ') != NVL(source.SECONDRY_OFFICE_LOCATION,' ') OR
											NVL(target.SECONDRY_OFFICE_PHONE,' ') != NVL(source.SECONDRY_OFFICE_PHONE,' ') OR
											NVL(target.SCHOOL,' ') != NVL(SUBSTR(source.SCHOOL,1,50),' ') OR
											NVL(target.DIRECTORY_DEPARTMENT,' ') != NVL(source.DIRECTORY_DEPARTMENT,' ') OR
											NVL(target.SALUTATION,' ') != NVL(source.SALUTATION,' ') OR
											NVL(target.COUNTRY_OF_CITIZENSHIP,' ') != NVL(source.COUNTRY_OF_CITIZENSHIP,' ') OR
											NVL(target.PRIMARY_TITLE,' ') != NVL(source.PRIMARY_TITLE,' ') OR
											NVL(target.DIRECTORY_TITLE,' ') != NVL(source.DIRECTORY_TITLE,' ') OR
											NVL(target.HOME_UNIT,' ') != NVL(source.HOME_UNIT,' ') OR
											NVL(target.IS_FACULTY,' ') != NVL(source.IS_FACULTY,' ') OR
											NVL(target.IS_GRADUATE_STUDENT_STAFF,' ') != NVL(source.IS_GRADUATE_STUDENT_STAFF,' ') OR
											NVL(target.IS_RESEARCH_STAFF,' ') != NVL(source.IS_RESEARCH_STAFF,' ') OR
											NVL(target.IS_SERVICE_STAFF,' ') != NVL(source.IS_SERVICE_STAFF,' ') OR
											NVL(target.IS_SUPPORT_STAFF,' ') != NVL(source.IS_SUPPORT_STAFF,' ') OR
											NVL(target.IS_OTHER_ACCADEMIC_GROUP,' ') != NVL(source.IS_OTHER_ACCADEMIC_GROUP,' ') OR
											NVL(target.IS_MEDICAL_STAFF,' ') != NVL(source.IS_MEDICAL_STAFF,' ') OR
											NVL(target.VISA_CODE,' ') != NVL(source.VISA_CODE,' ') OR
											NVL(target.VISA_TYPE,' ') != NVL(source.VISA_TYPE,' ') OR
											
											NVL(target.ADDRESS_LINE_1,' ') != NVL(source.ADDRESS_LINE_1,' ') OR
											NVL(target.ADDRESS_LINE_2,' ') != NVL(source.ADDRESS_LINE_2,' ') OR
											NVL(target.ADDRESS_LINE_3,' ') != NVL(source.ADDRESS_LINE_3,' ') OR
											NVL(target.CITY,' ') != NVL(source.CITY,' ') OR
											NVL(target.COUNTY,' ') != NVL(source.COUNTY,' ') OR
											NVL(target.STATE,' ') != NVL(source.STATE,' ') OR
											NVL(target.POSTAL_CODE,' ') != NVL(source.POSTAL_CODE,' ') OR
											NVL(target.COUNTRY_CODE,' ') != NVL(source.COUNTRY_CODE,' ') OR
											NVL(target.FAX_NUMBER,' ') != NVL(source.FAX_NUMBER,' ') OR
											NVL(target.PAGER_NUMBER,' ') != NVL(source.PAGER_NUMBER,' ') OR
											NVL(target.MOBILE_PHONE_NUMBER,' ') != NVL(source.MOBILE_PHONE_NUMBER,' ') OR
											NVL(target.STATUS,' ') != NVL(source.STATUS,' ') OR
											TO_DATE(NVL(target.SALARY_ANNIVERSARY_DATE,'01-JAN-01'), 'DD-MM-YY') != TO_DATE(NVL(source.SALARY_ANNIVERSARY_DATE,'01-JAN-01'), 'DD-MM-YY') OR
											
											TO_DATE(NVL(target.VISA_RENEWAL_DATE,'01-JAN-01'), 'DD-MM-YY') != TO_DATE(NVL(source.VISA_RENEWAL_DATE,'01-JAN-01'), 'DD-MM-YY'))
									THEN TO_DATE(SYSDATE, 'DD-MM-YY')
									ELSE TO_DATE(target.UPDATE_TIMESTAMP, 'DD-MM-YY')
								END
		WHEN NOT MATCHED THEN
			INSERT (
				PERSON_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME,FULL_NAME, PRIOR_NAME, USER_NAME, EMAIL_ADDRESS, 
				DATE_OF_BIRTH, AGE, EDUCATION_LEVEL, AGE_BY_FISCAL_YEAR, GENDER, OFFICE_LOCATION, OFFICE_PHONE, 
				SECONDRY_OFFICE_LOCATION, SECONDRY_OFFICE_PHONE, SCHOOL, DIRECTORY_DEPARTMENT, SALUTATION, 
				COUNTRY_OF_CITIZENSHIP, PRIMARY_TITLE, DIRECTORY_TITLE, HOME_UNIT, IS_FACULTY, IS_GRADUATE_STUDENT_STAFF, 
				IS_RESEARCH_STAFF, IS_SERVICE_STAFF, IS_SUPPORT_STAFF, IS_OTHER_ACCADEMIC_GROUP, IS_MEDICAL_STAFF, 
				UPDATE_TIMESTAMP, UPDATE_USER, VISA_CODE, VISA_TYPE, VISA_RENEWAL_DATE,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,
				CITY,COUNTY,STATE,POSTAL_CODE,COUNTRY_CODE,FAX_NUMBER,PAGER_NUMBER,MOBILE_PHONE_NUMBER,STATUS,SALARY_ANNIVERSARY_DATE
			)
			VALUES (
				source.PERSON_ID, SUBSTR(source.LAST_NAME,1,30), SUBSTR(source.FIRST_NAME,1,30), SUBSTR(source.MIDDLE_NAME,1,30), SUBSTR(source.FULL_NAME,1,90), source.PRIOR_NAME, 
				source.USER_NAME, source.EMAIL_ADDRESS, TO_DATE(source.DATE_OF_BIRTH, 'DD-MM-YY'), source.AGE, source.EDUCATION_LEVEL, source.AGE_BY_FISCAL_YEAR, 
				source.GENDER, source.OFFICE_LOCATION, source.OFFICE_PHONE, source.SECONDRY_OFFICE_LOCATION, source.SECONDRY_OFFICE_PHONE, 
				SUBSTR(source.SCHOOL,1,50), source.DIRECTORY_DEPARTMENT, source.SALUTATION, source.COUNTRY_OF_CITIZENSHIP, source.PRIMARY_TITLE, 
				source.DIRECTORY_TITLE, source.HOME_UNIT, source.IS_FACULTY, source.IS_GRADUATE_STUDENT_STAFF, source.IS_RESEARCH_STAFF, 
				source.IS_SERVICE_STAFF, source.IS_SUPPORT_STAFF, source.IS_OTHER_ACCADEMIC_GROUP, source.IS_MEDICAL_STAFF, 
				TO_DATE(SYSDATE, 'DD-MM-YY'), source.UPDATE_USER, source.VISA_CODE, source.VISA_TYPE, TO_DATE(source.VISA_RENEWAL_DATE, 'DD-MM-YY'),
				source.ADDRESS_LINE_1,source.ADDRESS_LINE_2,source.ADDRESS_LINE_3,source.CITY,
				source.COUNTY,source.STATE,source.POSTAL_CODE,source.COUNTRY_CODE,source.FAX_NUMBER,
				source.PAGER_NUMBER,source.MOBILE_PHONE_NUMBER,
				NVL(source.STATUS,'N'),TO_DATE(source.SALARY_ANNIVERSARY_DATE, 'DD-MM-YY')				
			);
LI_AFFECTED_ROWS := SQL%ROWCOUNT;
 
COMMIT;
END IF;
EXCEPTION WHEN OTHERS THEN
LS_ERROR_FLAG :='FALSE';
END;

IF LI_AFFECTED_ROWS > 0 THEN

 SELECT COUNT(1) INTO LI_AFTER_DATA_COUNT FROM FIBI_COI_PERSON; 
 
 LI_TOTAL_COUNT := LI_AFTER_DATA_COUNT - LI_BEFORE_DATA_COUNT;
 
 
SELECT COUNT(1) INTO LI_COUNT
FROM FIBI_COI_PERSON
WHERE TRUNC(UPDATE_TIMESTAMP) = TRUNC(SYSDATE); 
 
SELECT RTRIM(XMLAGG(XMLELEMENT(e, person_id, ', ').EXTRACT('//text()') ORDER BY person_id).GetClobVal(), ', ')  INTO LS_PERSON_IDS
FROM FIBI_COI_PERSON
WHERE (TRUNC(UPDATE_TIMESTAMP) = TRUNC(SYSDATE) OR SYNC_STATUS = 'ERROR');

END IF;

UPDATE FIBI_COI_PERSON SET SYNC_STATUS = NULL;
   
   OPEN cur_generic FOR
SELECT LS_PERSON_IDS AS SYNCED_PERSON_IDS,LS_ERROR_FLAG as PERSON_SYNC_RESULT, ROUND(LI_COUNT-LI_TOTAL_COUNT) AS NUM_OF_SYNCED_UPDATED,LI_TOTAL_COUNT AS NUM_OF_RECORDS_INSERTED FROM DUAL;
END;
//