INSERT IGNORE INTO FORM_SECTION_COMPONENT_TYPE (COMPONENT_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER, SORT_ORDER) VALUES ('AT', 'Attachment', 'Y', UTC_TIMESTAMP(), 'admin', '18');
INSERT IGNORE INTO FORM_SECTION_COMPONENT_TYPE (COMPONENT_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER, SORT_ORDER) VALUES ('PT', 'Paragraph - Text Editor', 'Y', UTC_TIMESTAMP(), 'admin', '17');

ANALYZE TABLE FB_COMP_CUSTOM_ELEMENT_OPTIONS;
SET @SQL := IF(
    (
        SELECT COUNT(*) 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'FB_COMP_CUSTOM_ELEMENT_OPTIONS'
          AND COLUMN_NAME = 'OPTION_NAME'
          AND DATA_TYPE = 'LONGTEXT'
    ) = 0,
    'ALTER TABLE FB_COMP_CUSTOM_ELEMENT_OPTIONS MODIFY COLUMN OPTION_NAME LONGTEXT;', 
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

ANALYZE TABLE FB_COMP_CUSTOM_ELEMENT_ANSWER;
SET @SQL := IF(
    (
        SELECT COUNT(*) 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'FB_COMP_CUSTOM_ELEMENT_ANSWER'
          AND COLUMN_NAME = 'DESCRIPTION'
          AND DATA_TYPE = 'LONGTEXT'
    ) = 0,   
    'ALTER TABLE FB_COMP_CUSTOM_ELEMENT_ANSWER MODIFY COLUMN DESCRIPTION LONGTEXT;',  
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

ANALYZE TABLE FB_COMP_CUSTOM_ELEMENT_ANSWER;
SET @SQL := IF(
    (
        SELECT COUNT(*) 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'FB_COMP_CUSTOM_ELEMENT_ANSWER'
          AND COLUMN_NAME = 'VALUE'
          AND DATA_TYPE = 'LONGTEXT'
    ) = 0,   
    'ALTER TABLE FB_COMP_CUSTOM_ELEMENT_ANSWER MODIFY COLUMN VALUE LONGTEXT;',  
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

-- Attachment Related Scripts
CREATE TABLE IF NOT EXISTS FB_FILE_DATA (
        FB_FILE_DATA_ID VARCHAR(36),
        DATA LONGBLOB,
        FILE_PATH VARCHAR(500),
        ORIGINAL_FILE_NAME VARCHAR(255),
        FILE_NAME VARCHAR(255),
        IS_ARCHIVED BOOLEAN DEFAULT FALSE,
        CREATE_TIMESTAMP DATETIME NOT NULL,
        CREATE_USER VARCHAR(60) NOT NULL,
        UPDATE_TIMESTAMP DATETIME NOT NULL,
        UPDATE_USER VARCHAR(60) NOT NULL,
        CONSTRAINT FB_FILE_DATA_PK PRIMARY KEY (FB_FILE_DATA_ID)
    );

CREATE TABLE IF NOT EXISTS FB_ATTACHMENTS (
        FB_ATT_ID INT AUTO_INCREMENT,
        MODULE_ITEM_CODE INT NOT NULL,
        MODULE_ITEM_KEY VARCHAR(20) NOT NULL,
        MODULE_SUB_ITEM_CODE INT NOT NULL,
        MODULE_SUB_ITEM_KEY VARCHAR(20) NOT NULL,
        FILE_ID VARCHAR(36) NOT NULL,
        FILE_NAME VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(2000) NULL,
        CREATE_TIMESTAMP DATETIME NOT NULL,
        CREATE_USER VARCHAR(60) NOT NULL,
        UPDATE_TIMESTAMP DATETIME NOT NULL,
        UPDATE_USER VARCHAR(60) NOT NULL,
        CONSTRAINT FB_ATTACHMENTS_PK PRIMARY KEY (FB_ATT_ID),
        CONSTRAINT FB_ATTACHMENTS_FILE_DATA_FK1 FOREIGN KEY (FILE_ID) REFERENCES FB_FILE_DATA (FB_FILE_DATA_ID)
    );

ANALYZE TABLE FORM_BUILDER_SECTION_COMPONENT;
SET @SQL := IF(
    (
        SELECT COUNT(*) 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'FORM_BUILDER_SECTION_COMPONENT'
          AND COLUMN_NAME = 'IS_CAPTURE_DESCRIPTION'
    ) = 0,
    'ALTER TABLE FORM_BUILDER_SECTION_COMPONENT ADD COLUMN IS_CAPTURE_DESCRIPTION VARCHAR(1);', 
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;
