Analyze table LEGACY_COI_DISCLOSURE;
SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LEGACY_COI_DISCLOSURE' AND COLUMN_NAME = 'SRC_CREATE_TIMESTAMP') = 0
    AND
    (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LEGACY_COI_DISCLOSURE' AND COLUMN_NAME = 'CREATE_TIMESTAMP') = 1,
    'ALTER TABLE LEGACY_COI_DISCLOSURE RENAME COLUMN CREATE_TIMESTAMP TO SRC_CREATE_TIMESTAMP;',
    'DO 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

Analyze table LEGACY_COI_DISCLOSURE;
SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LEGACY_COI_DISCLOSURE' AND COLUMN_NAME = 'SRC_CREATE_USER') = 0
    AND
    (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LEGACY_COI_DISCLOSURE' AND COLUMN_NAME = 'CREATE_USER') = 1,
    'ALTER TABLE LEGACY_COI_DISCLOSURE RENAME COLUMN CREATE_USER TO SRC_CREATE_USER;',
    'DO 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
