DROP PROCEDURE IF EXISTS COI_INT_PROP_PERSON_DISCL_STATUS;
DROP PROCEDURE IF EXISTS COI_INT_PROJECT_PRSN_DISCL_STATUS;
DROP PROCEDURE IF EXISTS GET_EXPIRING_FCOI_AND_OPA_DISCLOSURES;
DROP PROCEDURE IF EXISTS MARK_DISCLOSURES_AS_EXPIRED;

DROP FUNCTION IF EXISTS COI_INT_PROJECT_DISCL_STATUS;
DROP FUNCTION IF EXISTS COI_INT_PROP_DISCL_STATUS;
