ALTER TABLE `entity`
CHANGE COLUMN `INCORPORATED_IN` `INCORPORATED_IN` VARCHAR(50) NULL DEFAULT NULL ,
CHANGE COLUMN `CONGRESSIONAL_DISTRICT` `CONGRESSIONAL_DISTRICT` VARCHAR(50) NULL DEFAULT NULL ,
CHANGE COLUMN `PHONE_NUMBER` `PHONE_NUMBER` VARCHAR(20) NULL DEFAULT NULL;

ALTER TABLE `entity_sponsor_info`
CHANGE COLUMN `SPONSOR_CODE` `SPONSOR_CODE` VARCHAR(20) NULL DEFAULT NULL ,
CHANGE COLUMN `PHONE_NUMBER` `PHONE_NUMBER` VARCHAR(20) NULL DEFAULT NULL;

ALTER TABLE `entity_sub_org_info`
CHANGE COLUMN `PHONE_NUMBER` `PHONE_NUMBER` VARCHAR(20) NULL DEFAULT NULL ,
CHANGE COLUMN `CONGRESSIONAL_DISTRICT` `CONGRESSIONAL_DISTRICT` VARCHAR(50) NULL DEFAULT NULL ,
CHANGE COLUMN `INCORPORATED_IN` `INCORPORATED_IN` VARCHAR(50) NULL DEFAULT NULL;
