DROP PROCEDURE IF EXISTS GET_APPROVERS_FOR_ROLE_TYPE;
DROP PROCEDURE IF EXISTS GET_COI_DECLARATION_DETAIL_INTEG;
DROP PROCEDURE IF EXISTS GET_DECLARATION_DASHBOARD_DYNAMIC_DATA;
DROP PROCEDURE IF EXISTS GET_DECLARATION_DETAILS;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
