DROP FUNCTION IF EXISTS FN_QRY_OPA_DISCLOSURE_HOME_UNIT;
DROP FUNCTION IF EXISTS FN_QRY_REVEWR_DAS_OVRVEW_FCOI;
DROP FUNCTION IF EXISTS FN_QRY_REVEWR_DAS_OVRVEW_OPA;
DROP FUNCTION IF EXISTS FN_QRY_REVEWR_DAS_OVRVEW_TRAVEL;
DROP FUNCTION IF EXISTS FN_QRY_REVWR_DASH_CMN_SELECT_FIELDS;
DROP FUNCTION IF EXISTS FN_QRY_RVW_DAS_OVRVW_FCOI_FIL_COND;
DROP FUNCTION IF EXISTS FN_QRY_RVW_DAS_OVRVW_OPA_FIL_COND;
DROP FUNCTION IF EXISTS FN_QRY_RVW_DAS_OVRVW_TRAVEL_FIL_COND;
DROP FUNCTION IF EXISTS FN_OPA_DISCLOSURE_REQUIRED;
DROP PROCEDURE IF EXISTS GET_PERS_DISCL_REQUIREMENT_DASH_DATA;
DROP PROCEDURE IF EXISTS GET_REVIEWER_UNIT_HIERARCHY;
DROP PROCEDURE IF EXISTS REVIEWER_DASHBOARD_OVERVIEW;
DROP PROCEDURE IF EXISTS REVIEWER_DEPARTMENT_DASH_OVERVIEW;
DROP PROCEDURE IF EXISTS UPDT_OPA_ELIGIBILITY_FROM_FEED;

