DELIMITER //
CREATE PROCEDURE `OPA_DETERMINE_SEBBATIC_VALUE`(
    IN AV_OPA_DISCLOSURE_ID INT,
    IN AV_PERSON_ID VARCHAR(40)
)
BEGIN
DECLARE LS_IS_FALL_SABATICAL VARCHAR(1) DEFAULT 'N';
    DECLARE LS_IS_SPRING_SABATICAL VARCHAR(1) DEFAULT 'N';
    DECLARE LS_SABBATICAL_BEGIN_DATE DATE;
    DECLARE LS_SABBATICAL_END_DATE DATE;

    -- Fetch sabbatical dates
    SELECT SABBATICAL_BEGIN_DATE, SABBATICAL_END_DATE
    INTO LS_SABBATICAL_BEGIN_DATE, LS_SABBATICAL_END_DATE
    FROM OPA_PERSON
    WHERE PERSON_ID = AV_PERSON_ID;

    -- Determine Fall Sabbatical
    IF (LS_SABBATICAL_BEGIN_DATE IS NOT NULL AND LS_SABBATICAL_BEGIN_DATE BETWEEN DATE_SUB(CURDATE(), INTERVAL 12 MONTH) AND CURDATE()) THEN
        IF MONTH(LS_SABBATICAL_BEGIN_DATE) BETWEEN 9 AND 12 AND MONTH(CURDATE()) < 9 THEN
            SET LS_IS_FALL_SABATICAL = 'Y';
            SET LS_IS_SPRING_SABATICAL = 'Y';
        ELSEIF MONTH(LS_SABBATICAL_BEGIN_DATE) BETWEEN 9 AND 12 THEN
            SET LS_IS_FALL_SABATICAL = 'Y';
        ELSEIF (LS_SABBATICAL_END_DATE IS NOT NULL AND LS_SABBATICAL_END_DATE BETWEEN DATE_SUB(CURDATE(), INTERVAL 12 MONTH) AND CURDATE() AND
                MONTH(LS_SABBATICAL_END_DATE) BETWEEN 9 AND 12) THEN
            SET LS_IS_FALL_SABATICAL = 'Y';
        ELSEIF (LS_SABBATICAL_END_DATE IS NULL AND (MONTH(LS_SABBATICAL_BEGIN_DATE) BETWEEN 1 AND 5) AND MONTH(CURDATE()) BETWEEN 9 AND 12)  THEN
            SET LS_IS_SPRING_SABATICAL = 'Y';
            SET LS_IS_FALL_SABATICAL = 'Y';
        ELSEIF (LS_SABBATICAL_END_DATE IS NULL AND (MONTH(LS_SABBATICAL_BEGIN_DATE) NOT BETWEEN 1 AND 5) AND MONTH(CURDATE()) BETWEEN 9 AND 12)  THEN
            SET LS_IS_FALL_SABATICAL = 'Y';
        ELSEIF (LS_SABBATICAL_END_DATE IS NULL AND (MONTH(LS_SABBATICAL_BEGIN_DATE) BETWEEN 1 AND 5) AND MONTH(CURDATE()) NOT BETWEEN 9 AND 12)  THEN
            SET LS_IS_SPRING_SABATICAL = 'Y';
        END IF;
    ELSEIF (LS_SABBATICAL_BEGIN_DATE IS NOT NULL AND LS_SABBATICAL_BEGIN_DATE NOT BETWEEN DATE_SUB(CURDATE(), INTERVAL 12 MONTH) AND CURDATE() AND
            LS_SABBATICAL_END_DATE IS NULL) THEN
        SET LS_IS_FALL_SABATICAL = 'Y';
        SET LS_IS_SPRING_SABATICAL = 'Y';
    ELSEIF (LS_SABBATICAL_BEGIN_DATE IS NOT NULL AND LS_SABBATICAL_BEGIN_DATE NOT BETWEEN DATE_SUB(CURDATE(), INTERVAL 12 MONTH) AND CURDATE() AND
                LS_SABBATICAL_END_DATE IS NOT NULL AND LS_SABBATICAL_END_DATE BETWEEN DATE_SUB(CURDATE(), INTERVAL 12 MONTH) AND CURDATE()) THEN
        SET LS_IS_FALL_SABATICAL = 'Y';
        SET LS_IS_SPRING_SABATICAL = 'Y';
    ELSEIF (LS_SABBATICAL_END_DATE IS NOT NULL AND LS_SABBATICAL_END_DATE BETWEEN DATE_SUB(CURDATE(), INTERVAL 12 MONTH) AND CURDATE() AND
            MONTH(LS_SABBATICAL_END_DATE) BETWEEN 9 AND 12) THEN
        SET LS_IS_FALL_SABATICAL = 'Y';
    END IF;

    -- Determine Spring Sabbatical
    IF (LS_SABBATICAL_END_DATE IS NOT NULL AND LS_SABBATICAL_END_DATE BETWEEN DATE_SUB(CURDATE(), INTERVAL 12 MONTH) AND CURDATE()) THEN
        IF (MONTH(LS_SABBATICAL_END_DATE) < 9 AND
            LS_SABBATICAL_BEGIN_DATE BETWEEN DATE_SUB(CURDATE(), INTERVAL 12 MONTH) AND CURDATE() AND
            MONTH(LS_SABBATICAL_BEGIN_DATE) NOT BETWEEN 6 AND 8) THEN
            SET LS_IS_SPRING_SABATICAL = 'Y';
        ELSEIF MONTH(LS_SABBATICAL_END_DATE) BETWEEN 1 AND 5 THEN
            SET LS_IS_SPRING_SABATICAL = 'Y';
        END IF;
    END IF;

    -- Update disclosure
    UPDATE OPA_DISCLOSURE
    SET IS_FALL_SABATICAL = LS_IS_FALL_SABATICAL,
        IS_SPRING_SABATICAL = LS_IS_SPRING_SABATICAL
    WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;

END
//
