CREATE TABLE IF NOT EXISTS COI_DECLARATION_STATUS (
    DECLARATION_STATUS_CODE VARCHAR(3) PRIMARY KEY,
    DESCRIPTION VARCHAR(200),
    IS_ACTIVE VARCHAR(1),
    CREATED_BY VARCHAR(40),
    CREATE_TIMESTAMP DATETIME,
    UPDATED_BY VARCHAR(40),
    UPDATE_TIMESTAMP DATETIME
);

CREATE TABLE IF NOT EXISTS COI_DECLARATION_TYPE (
    DECLARATION_TYPE_CODE VARCHAR(3) PRIMARY KEY,
    DESCRIPTION VARCHAR(500),
	BADGE_COLOR VARCHAR(100),
	PROJECT_ICON VARCHAR(45),
    IS_ACTIVE VARCHAR(1),
    CREATED_BY VARCHAR(40),
    CREATE_TIMESTAMP DATETIME,
    UPDATED_BY VARCHAR(40),
    UPDATE_TIMESTAMP DATETIME
);

CREATE TABLE IF NOT EXISTS COI_DECLARATION (
    DECLARATION_ID INT AUTO_INCREMENT PRIMARY KEY,
	DECLARATION_NUMBER VARCHAR(20),
    PERSON_ID VARCHAR(40),
    DECLARATION_TYPE_CODE VARCHAR(3),
    DECLARATION_STATUS_CODE VARCHAR(3),
    SUBMISSION_DATE DATE,
    EXPIRATION_DATE DATE,
    VERSION_NUMBER INT,
    VERSION_STATUS VARCHAR(45),
    CREATED_BY VARCHAR(40),
    CREATE_TIMESTAMP DATETIME,
    UPDATED_BY VARCHAR(40),
    UPDATE_TIMESTAMP DATETIME,
    CONSTRAINT COI_DECLARATION_FK1 FOREIGN KEY (DECLARATION_TYPE_CODE) REFERENCES COI_DECLARATION_TYPE(DECLARATION_TYPE_CODE),
    CONSTRAINT COI_DECLARATION_FK2 FOREIGN KEY (DECLARATION_STATUS_CODE) REFERENCES COI_DECLARATION_STATUS(DECLARATION_STATUS_CODE)
);

CREATE TABLE IF NOT EXISTS COI_DECL_ACTION_LOG_TYPE (
  ACTION_TYPE_CODE VARCHAR(3) PRIMARY KEY,
  ACTION_MESSAGE VARCHAR(200),
  DESCRIPTION VARCHAR(200),
  CREATED_BY VARCHAR(40),
  CREATE_TIMESTAMP DATETIME,
  UPDATE_TIMESTAMP DATETIME,
  UPDATED_BY VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS COI_DECL_ACTION_LOG (
  ACTION_LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
  DECLARATION_ID INT,
  ACTION_TYPE_CODE VARCHAR(3),
  ACTION_MESSAGE VARCHAR(200),
  CREATE_TIMESTAMP DATETIME,
  CREATED_BY VARCHAR(40),
  CONSTRAINT COI_DECL_ACTION_LOG_FK1 FOREIGN KEY (DECLARATION_ID) REFERENCES COI_DECLARATION (DECLARATION_ID),
  CONSTRAINT COI_DECL_ACTION_LOG_FK2 FOREIGN KEY (ACTION_TYPE_CODE) REFERENCES COI_DECL_ACTION_LOG_TYPE (ACTION_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS COI_DECLARATION_NUMBER_COUNTER (
    COUNTER_NAME VARCHAR(255) PRIMARY KEY,
    COUNTER_VALUE INT
);
