DROP PROCEDURE IF EXISTS GET_DECLARATION_DASHBOARD_DYNAMIC_DATA;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
DROP PROCEDURE IF EXISTS GET_APPROVERS_FOR_ROLE_TYPE;

DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
