INSERT IGNORE INTO COI_DECLARATION_STATUS (DECLARATION_STATUS_CODE, DESCRIPTION, IS_ACTIVE, CREATED_BY, CREATE_TIMESTAMP, UPDATED_BY, UPDATE_TIMESTAMP) VALUES
('1', 'Pending', 'Y', 'admin', UTC_TIMESTAMP(), 'admin', UTC_TIMESTAMP()),
('2', 'Submitted', 'Y', 'admin', UTC_TIMESTAMP(), 'admin', UTC_TIMESTAMP()),
('3', 'Expired', 'Y', 'admin', UTC_TIMESTAMP(), 'admin', UTC_TIMESTAMP());

INSERT IGNORE INTO COI_DECLARATION_TYPE (DECLARATION_TYPE_CODE, DESCRIPTION, BADGE_COLOR, PROJECT_ICON, IS_ACTIVE, CREATED_BY, CREATE_TIMESTAMP, UPDATED_BY, UPDATE_TIMESTAMP) VALUES
('1', 'MFTRP', '#006642', NULL, 'Y', 'admin', UTC_TIMESTAMP(), 'admin', UTC_TIMESTAMP());

INSERT IGNORE INTO COI_DECL_ACTION_LOG_TYPE (ACTION_TYPE_CODE, ACTION_MESSAGE, DESCRIPTION, CREATED_BY, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('1', 'Declaration <b>created</b> by <b>{REPORTER}</b>', 'Created', 'admin', UTC_TIMESTAMP(), UTC_TIMESTAMP(), 'admin');
INSERT IGNORE INTO COI_DECL_ACTION_LOG_TYPE (ACTION_TYPE_CODE, ACTION_MESSAGE, DESCRIPTION, CREATED_BY, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('2', 'Declaration <b>submitted</b> by <b>{REPORTER}</b>', 'Submitted', 'admin', UTC_TIMESTAMP(), UTC_TIMESTAMP(), 'admin');
INSERT IGNORE INTO COI_DECL_ACTION_LOG_TYPE (ACTION_TYPE_CODE, ACTION_MESSAGE, DESCRIPTION, CREATED_BY, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('3', 'Declaration has been <b>revised</b> by <b>{REPORTER}</b>', 'Revised', 'admin', UTC_TIMESTAMP(), UTC_TIMESTAMP(), 'admin');
INSERT IGNORE INTO COI_DECL_ACTION_LOG_TYPE (ACTION_TYPE_CODE, ACTION_MESSAGE, DESCRIPTION, CREATED_BY, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('4', 'Declaration <b>expired</b>', 'Expired', 'admin', UTC_TIMESTAMP(), UTC_TIMESTAMP(), 'admin');

INSERT IGNORE INTO COI_DECLARATION_NUMBER_COUNTER (COUNTER_NAME, COUNTER_VALUE) VALUES
('COI_DECLARATION_NUMBER_COUNTER', 1);

INSERT IGNORE INTO COEUS_MODULE (MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE, DYN_MODULE_CODE) VALUES 
('28', 'Declaration', UTC_TIMESTAMP(), 'admin', 'Y', 'CC28');

INSERT IGNORE INTO NOTIFICATION_TYPE (NOTIFICATION_TYPE_ID, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, SUBJECT, MESSAGE, PROMPT_USER, IS_ACTIVE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, IS_SYSTEM_SPECIFIC)
VALUES (8088, '28', '0', 'Notifications related to upcoming declaration expirations.', '{DECLARATION_DETAILS#DECLARATION_TYPE} Declaration for {DECLARATION_DETAILS#REPORTER_NAME} Expired on {DECLARATION_DETAILS#EXPIRATION_DATE}', '<p style="margin-left:0px;"><strong>Dear </strong>{DECLARATION_DETAILS#REPORTER_NAME},</p><p style="margin-left:0px;"><span style="background-color:rgb(255,255,255);color:rgb(64,64,64);">This is a reminder that your {DECLARATION_DETAILS#DECLARATION_TYPE} Declaration expired on {DECLARATION_DETAILS#EXPIRATION_DATE}. Please find the details below:</span></p><p style="margin-left:0px;"><strong>Department: </strong>{DECLARATION_DETAILS#DEPARTMENT_NUMBER} - {DECLARATION_DETAILS#DEPARTMENT_NAME}</p><p style="margin-left:0px;"><strong>Status</strong>: {DECLARATION_DETAILS#DECLARATION_STATUS}</p><p style="margin-left:0px;"><span style="background-color:rgb(255,255,255);color:rgb(64,64,64);">Please update your {DECLARATION_DETAILS#DECLARATION_TYPE} Declaration at the earliest to remain compliant.</span></p><p style="margin-left:0px;"><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{DECLARATION_URL#DECLARATION_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>', 'N', 'Y', 'admin', UTC_TIMESTAMP(), 'admin', UTC_TIMESTAMP(), 'N');

INSERT IGNORE INTO NOTIFICATION_RECIPIENT (NOTIFICATION_TYPE_ID, RECIPIENT_PERSON_ID, ROLE_TYPE_CODE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, RECIPIENT_TYPE, RECIPIENT_NAME) VALUES (8088, NULL, 72, 'admin', UTC_TIMESTAMP(), 'admin', UTC_TIMESTAMP(), 'TO', 'Declaration Reporter');

INSERT IGNORE INTO NOTIFICATION_TYPE (NOTIFICATION_TYPE_ID, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, SUBJECT, MESSAGE, PROMPT_USER, IS_ACTIVE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, IS_SYSTEM_SPECIFIC)
VALUES (8089, '28', '0', 'Notifications related to expired declaration.', 'Your {DECLARATION_DETAILS#DECLARATION_TYPE} Declaration Has Expired', '<p style="margin-left:0px;"><strong>Dear </strong>{DECLARATION_DETAILS#REPORTER_NAME},</p><p style="margin-left:0px;"><span style="background-color:rgb(255,255,255);color:rgb(64,64,64);">Your {DECLARATION_DETAILS#DECLARATION_TYPE} has expired as it has reached its expiration date. Please find the details below:</span></p><p style="margin-left:0px;"><strong>Department: </strong>{DECLARATION_DETAILS#DEPARTMENT_NUMBER} - {DECLARATION_DETAILS#DEPARTMENT_NAME}</p><p style="margin-left:0px;"><strong>Submission Date:</strong> <span style="background-color:rgb(255,255,255);color:rgb(0,0,0);">{DECLARATION_DETAILS#SUBMISSION_DATE}</span></p><p style="margin-left:0px;"><strong>Expiration Date:</strong> <span style="background-color:rgb(255,255,255);color:rgb(0,0,0);">{DECLARATION_DETAILS#EXPIRATION_DATE}</span></p><p style="margin-left:0px;"><strong>Status</strong>: {DECLARATION_DETAILS#DECLARATION_STATUS}</p><p style="margin-left:0px;"><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{DECLARATION_URL#DECLARATION_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>', 'N', 'Y', 'admin', UTC_TIMESTAMP(), 'admin', UTC_TIMESTAMP(), 'N');

INSERT IGNORE INTO NOTIFICATION_RECIPIENT (NOTIFICATION_TYPE_ID, RECIPIENT_PERSON_ID, ROLE_TYPE_CODE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, RECIPIENT_TYPE, RECIPIENT_NAME) VALUES (8089, NULL, 72, 'admin', UTC_TIMESTAMP(), 'admin', UTC_TIMESTAMP(), 'TO', 'Declaration Reporter');

INSERT IGNORE INTO MQ_ROUTER_TRIGGER_CONFIGURATION (TRIGGER_TYPE,IS_ACTIVE,QUEUE_NAME,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('NOTIFY_DECLARATION_EXPIRED',' Y', 'Q_NOTIFICATION', 'Declaration Expired', UTC_TIMESTAMP(), 'admin');

INSERT IGNORE INTO REMINDER_NOTIFICATION
(REMINDER_NOTIFICATION_ID, REMINDER_NAME, NOTIFICATION_TYPE_ID, DAYS_TO_DUE_DATE, PROCEDURE_NAME, IS_ACTVE, UPDATE_USER, UPDATE_TIMESTAMP, PLACEHOLDER_VALUES)
VALUES((SELECT T.ID FROM (SELECT MAX(REMINDER_NOTIFICATION_ID) + 1 AS ID FROM REMINDER_NOTIFICATION) AS T), 'Declaration Expiration Alert', 8088, 0, '', 'Y', 'admin', UTC_TIMESTAMP(), NULL),

((SELECT T.ID FROM (SELECT MAX(REMINDER_NOTIFICATION_ID) + 1 AS ID FROM REMINDER_NOTIFICATION) AS T), 'Declaration Expiration Alert', 8088, 7, '', 'Y', 'admin', UTC_TIMESTAMP(), NULL),

((SELECT T.ID FROM (SELECT MAX(REMINDER_NOTIFICATION_ID) + 1 AS ID FROM REMINDER_NOTIFICATION) AS T), 'Declaration Expiration Alert', 8088, 30, '', 'Y', 'admin', UTC_TIMESTAMP(), NULL);

INSERT IGNORE INTO MESSAGE (MESSAGE_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('8033', 'Declaration Renewal Required', UTC_TIMESTAMP(), 'admin');

INSERT IGNORE INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'VIEW_MFTRP_DECLARATION', 'To control view access for MFTRP Declarations.', 'admin', UTC_TIMESTAMP(), '1');

INSERT IGNORE INTO SCHEDULER_JOB_INFO (JOB_ID, CRON_EXPRESSION, IS_CRON_JOB, JOB_CLASS, JOB_GROUP, JOB_NAME, DESCRIPTION, CRON_STATUS, UPDATE_USER, UPDATE_TIMESTAMP, IS_ACTIVE) 
VALUES ((SELECT A.ID FROM (SELECT MAX(JOB_ID) + 1 AS ID FROM SCHEDULER_JOB_INFO ) AS A), '0 */10 * * * ?', 'Y', 'com.polus.fibicomp.quartzscheduler.CoiDeclarationScheduler', 'coi', 'Declaration expiration action list', 'This job is to update the action list of reporters with their expired Declarations.', 'SCHEDULED', 'admin', UTC_TIMESTAMP(), 'Y');

INSERT IGNORE INTO PERSON_ROLE_TYPE (ROLE_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE) VALUES (72, 'Declaration Reporter', UTC_TIMESTAMP(), 'admin', 'Y');

INSERT IGNORE INTO COEUS_SUB_MODULE(COEUS_SUB_MODULE_ID, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, REQUIRE_UNIQUE_QUESTIONNAIRE, IS_ACTIVE)
VALUES(2605,28,1,'MFTRP',UTC_TIMESTAMP(),'admin', 'N', 'Y');

INSERT IGNORE INTO NOTIFY_PLACEHOLDER_HEADER (NOTIFY_PLACEHOLDER_HEADER_ID, MODULE_CODE, SUB_MODULE_CODE, QUERY_DEFINITION, QUERY_TYPE, ELEMENT_NAME, ELEMENT_TYPE, IS_ACTIVE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, UNIQUE_DISPLAY_NAME) VALUES (24, 28, 0, NULL, 'S', NULL, 'S', 'Y', 'Declaration Details', UTC_TIMESTAMP(), 'admin', 'DECLARATION_DETAILS');

INSERT IGNORE INTO NOTIFY_PLACEHOLDER_HEADER (NOTIFY_PLACEHOLDER_HEADER_ID, MODULE_CODE, SUB_MODULE_CODE, QUERY_DEFINITION, QUERY_TYPE, ELEMENT_NAME, ELEMENT_TYPE, IS_ACTIVE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, UNIQUE_DISPLAY_NAME) VALUES (25, 28, 0, NULL, 'U', NULL, 'U', 'Y', 'Declaration URL', UTC_TIMESTAMP(), 'admin', 'DECLARATION_URL');

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS 
(NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT * FROM (
    SELECT 24, 'DECLARATION_ID', 'Declaration ID', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM NOTIFY_PLACEHOLDER_COLUMNS 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 24
      AND QUERY_COLUMN_NAME = 'DECLARATION_ID'
      AND LABEL_NAME = 'Declaration ID'
);

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS 
(NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT * FROM (
    SELECT 24, 'DECLARATION_TYPE', 'Declaration Type', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM NOTIFY_PLACEHOLDER_COLUMNS 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 24
      AND QUERY_COLUMN_NAME = 'DECLARATION_TYPE'
      AND LABEL_NAME = 'Declaration Type'
);

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS 
(NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT * FROM (
    SELECT 24, 'REVIEWER_NAME', 'Reviewer Name', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM NOTIFY_PLACEHOLDER_COLUMNS 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 24
      AND QUERY_COLUMN_NAME = 'REVIEWER_NAME'
      AND LABEL_NAME = 'Reviewer Name'
);

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS 
(NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT * FROM (
    SELECT 24, 'DEPARTMENT_NUMBER', 'Department Number', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM NOTIFY_PLACEHOLDER_COLUMNS 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 24
      AND QUERY_COLUMN_NAME = 'DEPARTMENT_NUMBER'
      AND LABEL_NAME = 'Department Number'
);

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS 
(NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT * FROM (
    SELECT 24, 'DEPARTMENT_NAME', 'Department Name', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM NOTIFY_PLACEHOLDER_COLUMNS 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 24
      AND QUERY_COLUMN_NAME = 'DEPARTMENT_NAME'
      AND LABEL_NAME = 'Department Name'
);

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS 
(NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT * FROM (
    SELECT 24, 'SUBMISSION_DATE', 'Submission Date', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM NOTIFY_PLACEHOLDER_COLUMNS 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 24
      AND QUERY_COLUMN_NAME = 'SUBMISSION_DATE'
      AND LABEL_NAME = 'Submission Date'
);

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS 
(NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT * FROM (
    SELECT 24, 'EXPIRATION_DATE', 'Expiration Date', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM NOTIFY_PLACEHOLDER_COLUMNS 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 24
      AND QUERY_COLUMN_NAME = 'EXPIRATION_DATE'
      AND LABEL_NAME = 'Expiration Date'
);

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS 
(NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT * FROM (
    SELECT 24, 'DECLARATION_STATUS', 'Declaration Status', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM NOTIFY_PLACEHOLDER_COLUMNS 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 24
      AND QUERY_COLUMN_NAME = 'DECLARATION_STATUS'
      AND LABEL_NAME = 'Declaration Status'
);

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS 
(NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, BASE_URL_ID, URL_PATH, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT * FROM (
    SELECT 25, 'DECLARATION_URL', 'Declaration URL', 1, '/declaration/form?declarationId={DECLARATION_DETAILS#DECLARATION_ID}', UTC_TIMESTAMP(), 'admin'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM NOTIFY_PLACEHOLDER_COLUMNS 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 25
      AND QUERY_COLUMN_NAME = 'DECLARATION_URL'
      AND LABEL_NAME = 'Declaration URL'
	  AND BASE_URL_ID = 1
	  AND URL_PATH = '/declaration/form?declarationId={DECLARATION_DETAILS#DECLARATION_ID}'
);
