ALTER TABLE SPONSOR  
ADD ENTITY_ID NUMBER(6);
/
ALTER TABLE ORGANIZATION  
ADD ENTITY_ID NUMBER(6);
/
CREATE TABLE "KCSO"."INTEGRATION_EXCEPTION_LOG" 
   ("ID" NUMBER, 
	"EXCEPTION_TYPE" VARCHAR2(255 BYTE), 
	"EXCEPTION_MESSAGE" CLOB, 
	"STACK_TRACE" CLOB, 
	"URL" VARCHAR2(255 BYTE), 
	"REQUEST_OBJ" CLOB, 
	"CREATE_TIMESTAMP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
   );
/
CREATE SEQUENCE  INTEGRATION_EXCEPTION_LOG_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
/
CREATE TABLE "KCSO"."USER_TOKENS" 
   (	"ID" NUMBER(19,0), 
	"USER_NAME" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"ACCESS_TOKEN" CLOB, 
	"SALT" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"PERSON_ID" VARCHAR2(50 CHAR), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
   );
CREATE SEQUENCE  "KCSO"."USER_TOKENS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE TABLE "KCSO"."FIBI_COI_PERSON" 
   (	"PERSON_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(30 BYTE), 
	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"MIDDLE_NAME" VARCHAR2(30 BYTE), 
	"FULL_NAME" VARCHAR2(90 BYTE), 
	"PRIOR_NAME" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(60 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(60 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"AGE" NUMBER, 
	"AGE_BY_FISCAL_YEAR" NUMBER, 
	"GENDER" VARCHAR2(30 BYTE), 
	"EDUCATION_LEVEL" VARCHAR2(30 BYTE), 
	"OFFICE_LOCATION" VARCHAR2(30 BYTE), 
	"OFFICE_PHONE" VARCHAR2(20 BYTE), 
	"SECONDRY_OFFICE_LOCATION" VARCHAR2(30 BYTE), 
	"SECONDRY_OFFICE_PHONE" VARCHAR2(20 BYTE), 
	"SCHOOL" VARCHAR2(50 BYTE), 
	"DIRECTORY_DEPARTMENT" VARCHAR2(30 BYTE), 
	"SALUTATION" VARCHAR2(30 BYTE), 
	"COUNTRY_OF_CITIZENSHIP" VARCHAR2(30 BYTE), 
	"PRIMARY_TITLE" VARCHAR2(51 BYTE), 
	"DIRECTORY_TITLE" VARCHAR2(50 BYTE), 
	"HOME_UNIT" VARCHAR2(8 BYTE), 
	"IS_FACULTY" CHAR(1 BYTE), 
	"IS_GRADUATE_STUDENT_STAFF" CHAR(1 BYTE), 
	"IS_RESEARCH_STAFF" CHAR(1 BYTE), 
	"IS_SERVICE_STAFF" CHAR(1 BYTE), 
	"IS_SUPPORT_STAFF" CHAR(1 BYTE), 
	"IS_OTHER_ACCADEMIC_GROUP" CHAR(1 BYTE), 
	"IS_MEDICAL_STAFF" CHAR(1 BYTE), 
	"ADDRESS_LINE_1" VARCHAR2(80 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(80 BYTE), 
	"ADDRESS_LINE_3" VARCHAR2(80 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"COUNTY" VARCHAR2(30 BYTE), 
	"STATE" VARCHAR2(30 BYTE), 
	"POSTAL_CODE" VARCHAR2(15 BYTE), 
	"COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"FAX_NUMBER" VARCHAR2(20 BYTE), 
	"PAGER_NUMBER" VARCHAR2(20 BYTE), 
	"MOBILE_PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"VISA_CODE" VARCHAR2(20 BYTE), 
	"VISA_TYPE" VARCHAR2(30 BYTE), 
	"VISA_RENEWAL_DATE" DATE, 
	"STATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
	"SALARY_ANNIVERSARY_DATE" DATE, 
	"UPDATE_TIMESTAMP" DATE, 
	"UPDATE_USER" VARCHAR2(60 BYTE), 
	"SYNC_STATUS" VARCHAR2(500 BYTE), 
	 CONSTRAINT "PK_FIBI_COI_PERSON" PRIMARY KEY ("PERSON_ID")
    );

  CREATE TABLE FIBI_COI_ROLODEX 
   (	
    "ROLODEX_ID" NUMBER, 
	"LAST_NAME" VARCHAR2(50 CHAR), 
	"FIRST_NAME" VARCHAR2(50 CHAR), 
	"MIDDLE_NAME" VARCHAR2(50 CHAR), 
	"FULL_NAME" VARCHAR2(250 CHAR), 
	"PREFIX" VARCHAR2(10 CHAR), 
	"SUFFIX" VARCHAR2(10 CHAR), 
	"TITLE" VARCHAR2(35 CHAR), 
	"ORGANIZATION" VARCHAR2(200 CHAR), 
	"ORGANIZATION_NAME" VARCHAR2(200 CHAR), 
	"ADDRESS_LINE_1" VARCHAR2(80 CHAR), 
	"ADDRESS_LINE_2" VARCHAR2(80 CHAR), 
	"ADDRESS_LINE_3" VARCHAR2(80 CHAR), 
	"FAX_NUMBER" VARCHAR2(20 CHAR), 
	"EMAIL_ADDRESS" VARCHAR2(60 CHAR), 
	"CITY" VARCHAR2(30 CHAR), 
	"COUNTY" VARCHAR2(30 CHAR), 
	"STATE" VARCHAR2(30 CHAR), 
	"POSTAL_CODE" VARCHAR2(15 CHAR), 
	"COMMENTS" VARCHAR2(4000 CHAR), 
	"PHONE_NUMBER" VARCHAR2(20 CHAR), 
	"COUNTRY_CODE" VARCHAR2(3 CHAR), 
	"SPONSOR_CODE" VARCHAR2(6 CHAR), 
	"OWNED_BY_UNIT" VARCHAR2(8 CHAR), 
	"SPONSOR_ADDRESS_FLAG" CHAR(1 BYTE) DEFAULT 'N', 
	"DELETE_FLAG" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATE_USER" VARCHAR2(60 CHAR), 
	"UPDATE_TIMESTAMP" DATE, 
	"UPDATE_USER" VARCHAR2(60 CHAR), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"DESIGNATION" VARCHAR2(255 CHAR), 
	"SYNC_STATUS" VARCHAR2(10 CHAR), 
	"FEED_STATUS" VARCHAR2(10 CHAR), 
	 PRIMARY KEY ("ROLODEX_ID")
   ) ;
