DELIMITER //
CREATE PROCEDURE GET_COI_AWARD_PROJECT_OVERVIEW(
AV_AWARD_TITLE		  VARCHAR(1000),
AV_AWARD_NUMBER		  VARCHAR(20),
AV_UNIT_NUMBER            VARCHAR(8),
AV_PERSON_ID    		  VARCHAR(40),
AV_AWARD_STATUS        VARCHAR(200),
AV_REVIEW_STATUS 		  VARCHAR(200),
AV_SPONSOR 					VARCHAR(6),
AV_PRIME_SPONSOR 			VARCHAR(6),
AV_AWARD_START_DATE 		VARCHAR(20),
AV_AWARD_END_DATE 		VARCHAR(20),
AV_PAGED                        INT(10),
AV_LIMIT                        INT(10),
AV_UNLIMITED                    BOOLEAN,
AV_TYPE						 VARCHAR(1),
AV_SORT_TYPE 				VARCHAR(2000)
)
BEGIN

DECLARE LS_FILTER_CONDITION 		LONGTEXT;
DECLARE LS_JOIN_CONDITION			LONGTEXT;
DECLARE LS_PAGINATION_CONDITION 	VARCHAR(60);
DECLARE LS_DYN_SQL					LONGTEXT;

DECLARE LS_OFFSET 					INT(11);
DECLARE LS_ORDER_BY 				LONGTEXT;
DECLARE LS_OFFSET_CONDITION			LONGTEXT;

SET LS_DYN_SQL ='';
SET LS_FILTER_CONDITION = '';
SET LS_PAGINATION_CONDITION = '';
SET LS_JOIN_CONDITION = '';
SET LS_OFFSET = (AV_LIMIT * AV_PAGED);

DROP  TABLE if exists DisclosureAwardProjects;
CREATE  TABLE DisclosureAwardProjects AS SELECT DISTINCT T1.EXTERNAL_SYSTEM_REF_ID AS PROJECT_ID
		,T1.AWARD_NUMBER AS PROJECT_NUMBER
		,T1.KEY_PERSON_ID
        ,T1.DISCLOSURE_REQUIRED_FLAG
        ,T55.DISCLOSURE_ID 
		,CASE 
    WHEN T1.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED' COLLATE utf8mb4_0900_ai_ci
	THEN CASE 
        WHEN T1.DISCLOSURE_VALIDATION_FLAG <> 'SELF' COLLATE utf8mb4_0900_ai_ci
        THEN 
            CASE 
                WHEN FN_CHK_HIERARCHY_HAS_DISCL(T1.AWARD_NUMBER, T1.KEY_PERSON_ID) = 'NO DATA' COLLATE utf8mb4_0900_ai_ci
                THEN 
                    CASE 
                        WHEN T55.REVIEW_STATUS_CODE IN (
                                2
                                ,3
                                ,4
                                ,7
                                ,8
                                )
                        THEN 'DISCLOSURE_COMPLETED' COLLATE utf8mb4_0900_ai_ci
                        ELSE 'DISCLOSURE_PENDING' COLLATE utf8mb4_0900_ai_ci
                    END
                ELSE FN_CHK_HIERARCHY_HAS_DISCL(T1.AWARD_NUMBER, T1.KEY_PERSON_ID)
            END
        WHEN T55.REVIEW_STATUS_CODE IN (
                2
                ,3
                ,4
                ,7
                ,8
                )
        THEN 'DISCLOSURE_COMPLETED' COLLATE utf8mb4_0900_ai_ci
        ELSE 'DISCLOSURE_PENDING' COLLATE utf8mb4_0900_ai_ci
                END
    WHEN T1.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED' COLLATE utf8mb4_0900_ai_ci
        THEN CASE 
                WHEN T1.DISCLOSURE_VALIDATION_FLAG = 'SELF' COLLATE utf8mb4_0900_ai_ci
                    THEN CASE 
                    WHEN T55.REVIEW_STATUS_CODE IS NULL 
                    THEN 'DISCLOSURE_NOT_REQUIRED' COLLATE utf8mb4_0900_ai_ci
                            WHEN T55.REVIEW_STATUS_CODE IN (
                                    2
                                    ,3
                                    ,4
                                    ,7
                                    ,8
                                    )
                                THEN 'DISCLOSURE_COMPLETED' COLLATE utf8mb4_0900_ai_ci
                            ELSE 'DISCLOSURE_PENDING' COLLATE utf8mb4_0900_ai_ci
                            END                 
                END
    ELSE 'DISCLOSURE_TO_BE_DETERMINED' COLLATE utf8mb4_0900_ai_ci
	END AS DISCLOSURE_STATUS,
CASE
    WHEN T1.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED' COLLATE utf8mb4_0900_ai_ci
        THEN T9.DESCRIPTION
    WHEN T1.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED' 
        THEN 
        CASE 
            WHEN T1.DISCLOSURE_VALIDATION_FLAG = 'SELF' 
                THEN 
                CASE 
                    WHEN T55.DISCLOSURE_ID  IS NULL  
                        THEN 'DISCLOSURE_REVIEW_NA' COLLATE utf8mb4_0900_ai_ci
                    ELSE T9.DESCRIPTION
                END
            WHEN T1.DISCLOSURE_VALIDATION_FLAG = 'SELF' 
                THEN T9.DESCRIPTION 
            ELSE 'DISCLOSURE_REVIEW_NA' 
        END
       
END AS PROJECT_DISCLOSURE_REVIEW_STATUS
	FROM COI_PROJECT_AWARD_V T1
		LEFT JOIN (
		SELECT T13.EXTERNAL_SYSTEM_REF_ID
			,T13.AWARD_NUMBER
			,T22.DISCLOSURE_ID
			,T6.FCOI_TYPE_CODE
			,T6.REVIEW_STATUS_CODE
			,T6.DISPOSITION_STATUS_CODE
			,T6.PERSON_ID
		FROM COI_PROJECT_AWARD_V T13
		INNER JOIN COI_DISCL_PROJECTS T22 ON T22.MODULE_ITEM_KEY = T13.AWARD_NUMBER
			AND T22.MODULE_CODE = T13.COI_PROJECT_TYPE_CODE
		INNER JOIN COI_DISCLOSURE T6 ON T22.DISCLOSURE_ID = T6.DISCLOSURE_ID
		WHERE T6.DISPOSITION_STATUS_CODE != 2
         AND T6.DISCLOSURE_ID = (SELECT MAX(DISCLOSURE_ID) FROM COI_DISCL_PROJECTS WHERE DISCLOSURE_NUMBER = T6.DISCLOSURE_NUMBER AND MODULE_CODE = T13.COI_PROJECT_TYPE_CODE )    
        
		) AS T55 ON T55.EXTERNAL_SYSTEM_REF_ID = T1.EXTERNAL_SYSTEM_REF_ID
		AND T55.PERSON_ID = T1.KEY_PERSON_ID AND T55.DISCLOSURE_ID = (SELECT MAX(T22.DISCLOSURE_ID)
		FROM COI_DISCL_PROJECTS T22			
		INNER JOIN COI_DISCLOSURE T6 ON T22.DISCLOSURE_ID = T6.DISCLOSURE_ID
        WHERE T22.MODULE_ITEM_KEY = T1.AWARD_NUMBER AND T22.MODULE_CODE = '1'
        AND T6.PERSON_ID = T1.KEY_PERSON_ID)
	LEFT JOIN coi_review_status_type T9 ON T9.REVIEW_STATUS_CODE = T55.REVIEW_STATUS_CODE
    INNER  JOIN coi_int_stage_award_person CISA ON CISA.PROJECT_NUMBER = T1.AWARD_NUMBER AND CISA.NEW_DISCLOSURE_REQUIRED <> 'Y';
    

    SET LS_JOIN_CONDITION = CONCAT(LS_JOIN_CONDITION, ' LEFT JOIN PERSON T2 ON T1.KEY_PERSON_ID = T2.PERSON_ID
														LEFT JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T1.SPONSOR_CODE
														LEFT JOIN SPONSOR T4 ON T4.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE
														LEFT JOIN (
                                                        SELECT T13.EXTERNAL_SYSTEM_REF_ID, T22.DISCLOSURE_ID, T6.FCOI_TYPE_CODE, T6.REVIEW_STATUS_CODE,
															T6.DISPOSITION_STATUS_CODE, T6.PERSON_ID
															from coi_project_award_v T13
                                                            INNER JOIN COI_DISCL_PROJECTS T22
																ON T22.MODULE_ITEM_KEY = T13.AWARD_NUMBER
																AND T22.MODULE_CODE = T13.COI_PROJECT_TYPE_CODE
                                                            inner join
															COI_DISCLOSURE T6
                                                            on T22.DISCLOSURE_ID = T6.DISCLOSURE_ID
                                                            where T6.DISPOSITION_STATUS_CODE != 2
                                                            and T6.DISCLOSURE_ID = (select max(DISCLOSURE_ID) from COI_DISCLOSURE where DISCLOSURE_NUMBER = t6.DISCLOSURE_NUMBER )
														) AS T55 ON (T55.EXTERNAL_SYSTEM_REF_ID = T1.EXTERNAL_SYSTEM_REF_ID AND T55.PERSON_ID = T1.KEY_PERSON_ID)
														INNER JOIN eps_prop_person_role T7 ON T7.PROP_PERSON_ROLE_ID = T1.KEY_PERSON_ROLE_CODE
														LEFT JOIN UNIT T8 ON T8.UNIT_NUMBER = T2.HOME_UNIT
														LEFT JOIN coi_review_status_type T9 ON T9.REVIEW_STATUS_CODE = T55.REVIEW_STATUS_CODE
														INNER JOIN coi_project_type T10 ON T10.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
                                                        INNER JOIN coi_project_award_status_v T11 ON T11.STATUS_CODE = T1.AWARD_STATUS_CODE
                                                         ');

IF AV_TYPE ='A' THEN

    IF AV_AWARD_TITLE IS NOT NULL AND AV_AWARD_TITLE <> '' THEN
		 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T1.TITLE LIKE ''%', AV_AWARD_TITLE, '%'' ');
	END IF;

    IF AV_AWARD_NUMBER IS NOT NULL  AND AV_AWARD_NUMBER <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.AWARD_NUMBER LIKE ''%',AV_AWARD_NUMBER, '%'' ');
	END IF;
    
    IF AV_UNIT_NUMBER IS NOT NULL AND AV_UNIT_NUMBER <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.LEAD_UNIT_NUMBER = ''',AV_UNIT_NUMBER,''' ');
    END IF;

    IF AV_PERSON_ID IS NOT NULL AND AV_PERSON_ID <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.AWARD_NUMBER IN(SELECT AWARD_NUMBER FROM coi_project_award_v WHERE KEY_PERSON_ID = ''',AV_PERSON_ID,''') ');
    END IF;

    IF AV_AWARD_STATUS IS NOT NULL AND AV_AWARD_STATUS <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T11.STATUS_CODE IN (', AV_AWARD_STATUS, ') ');
    END IF;

    IF AV_REVIEW_STATUS IS NOT NULL AND AV_REVIEW_STATUS <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T55.REVIEW_STATUS_CODE IN (', AV_REVIEW_STATUS, ') ');
    END IF;

    IF AV_SPONSOR IS NOT NULL AND AV_SPONSOR <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T3.SPONSOR_CODE = ''',AV_SPONSOR,''' ');
    END IF;
    
    IF AV_PRIME_SPONSOR IS NOT NULL AND AV_PRIME_SPONSOR <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T4.SPONSOR_CODE = ''',AV_PRIME_SPONSOR,''' ');
    END IF;

    IF AV_AWARD_START_DATE IS NOT NULL AND AV_AWARD_START_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND DATE(T1.AWARD_START_DATE) >= DATE_FORMAT(''',AV_AWARD_START_DATE,''',''%Y-%m-%d'') ');
    END IF;

    IF AV_AWARD_END_DATE IS NOT NULL AND AV_AWARD_END_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND DATE(T1.AWARD_END_DATE) <= DATE_FORMAT(''',AV_AWARD_END_DATE,''',''%Y-%m-%d'') ');
    END IF;
END IF;

IF AV_TYPE <> 'A' THEN
	SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND  (T1.DISCLOSURE_VALIDATION_FLAG = ''SELF'' OR (T1.AWARD_STATUS_CODE = 6))');
END IF;



IF AV_SORT_TYPE IS NOT NULL OR AV_SORT_TYPE <> '' THEN 

SET LS_ORDER_BY = CONCAT(' ORDER BY T1.PROJECT_SUBMISSION_STATUS IS NULL, T1.PROJECT_REVIEW_STATUS IS NULL,
 ',AV_SORT_TYPE,', T1.UPDATE_TIMESTAMP DESC,T1.SORT_ID ASC');
ELSE 

SET LS_ORDER_BY = ' ORDER BY T1.UPDATE_TIMESTAMP DESC,T1.SORT_ID ASC ';

END IF;

IF AV_UNLIMITED <> TRUE  THEN


IF AV_LIMIT IS NOT NULL AND LS_OFFSET IS NOT NULL THEN
SET LS_OFFSET_CONDITION =CONCAT(' WHERE T.ROWNUMBER BETWEEN ', (SELECT CASE WHEN LS_OFFSET = 0 THEN LS_OFFSET ELSE LS_OFFSET+1 END), ' AND ', ( LS_OFFSET + AV_LIMIT));
END IF;

ELSE 
SET LS_OFFSET_CONDITION = '';
END IF;


SET LS_DYN_SQL = CONCAT(
    LS_DYN_SQL,
    'WITH	CommentsCount AS (
        SELECT MODULE_ITEM_KEY, MODULE_CODE, COUNT(*) AS COMMENT_COUNT
        FROM coi_project_comment
        where MODULE_CODE = 1
        GROUP BY MODULE_ITEM_KEY
    )'
);

SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '
SELECT * FROM (SELECT 
	T1.PROJECT_ID,
    T1.PROJECT_NUMBER,
    T1.TITLE,
    T1.PI_NAME,
    T1.KEY_PERSON_ID,
    T1.KEY_PERSON_NAME,
    T1.KEY_PERSON_ROLE_CODE,
    T1.KEY_PERSON_ROLE,
    T1.SPONSOR_NAME,
    T1.SPONSOR_CODE,
    T1.PRIME_SPONSOR_NAME,
    T1.PRIME_SPONSOR_CODE,
    T1.LEAD_UNIT_NUMBER,
    T1.LEAD_UNIT_NAME,
    T1.HOME_UNIT,
    T1.HOME_UNIT_NAME,
    T1.AWARD_START_DATE,
    T1.AWARD_END_DATE,
    T1.PROJECT_STATUS,
    T1.DISCLOSURE_ID,
    T1.DISCLOSURE_REVIEW_STATUS,
    T1.FCOI_TYPE_CODE,
    T1.PROJECT_TYPE_CODE,
    T1.PROJECT_TYPE,
    T1.BADGE_COLOR,
    T1.UPDATE_TIMESTAMP,
    null as CERTIFICATION_FLAG,
    T1.DISCLOSURE_REQUIRED_FLAG,
    T1.COMMENT_COUNT ,
    T1.DISCLOSURE_COMPLETION_STATUS,
    T1.PROJECT_ICON,
    T1.DOCUMENT_NUMBER,
    T1.ACCOUNT_NUMBER,
    CASE WHEN T1.DISCLOSURE_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
    WHEN T1.DISCLOSURE_STATUS =''DISCLOSURE_NOT_REQUIRED''  THEN ''Not Required''
    WHEN T1.DISCLOSURE_STATUS =''DISCLOSURE_TO_BE_DETERMINED'' THEN ''TO_BE_DETERMINED''
    WHEN T1.DISCLOSURE_STATUS is null AND T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED'' AND T1.RESUBMISSION_FLAG = ''N'' THEN ''Not Required''
    WHEN T1.DISCLOSURE_STATUS is null AND T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED'' AND T1.RESUBMISSION_FLAG = ''Y'' THEN ''Yet to disclose''
    WHEN T1.DISCLOSURE_STATUS is null and T1.DISCLOSURE_REQUIRED_FLAG <> ''REQUIRED'' THEN ''N/A''
    WHEN T1.DISCLOSURE_STATUS = ''DISCLOSURE_PENDING'' and T1.DISCLOSURE_ID is not null THEN ''Pending''
	WHEN T1.DISCLOSURE_STATUS = ''DISCLOSURE_PENDING'' and T1.DISCLOSURE_ID is null THEN ''Yet to disclose''
    WHEN T1.DISCLOSURE_STATUS is null AND T1.DISCLOSURE_REQUIRED_FLAG = ''REQUIRED'' AND T1.RESUBMISSION_FLAG = ''Y'' THEN ''Yet to disclose''
    ELSE T1.DISCLOSURE_STATUS
    END AS PERSON_SUBMISSION_STATUS ,
 	CASE WHEN T1.REVIEW_STATUS = ''COMPLETED'' THEN ''Completed''
    WHEN T1.DISCLOSURE_STATUS is null AND T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED'' AND T1.RESUBMISSION_FLAG = ''N'' THEN ''Not Required''
    WHEN T1.DISCLOSURE_STATUS is null AND T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED'' AND T1.RESUBMISSION_FLAG = ''Y'' THEN  NULL
    WHEN T1.REVIEW_STATUS =''DISCLOSURE_REVIEW_NA'' THEN ''N/A''
    WHEN T1.REVIEW_STATUS =''DISCLOSURE_TO_BE_DETERMINED'' THEN ''TO_BE_DETERMINED''
	WHEN T1.REVIEW_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''
    WHEN T1.DISCLOSURE_STATUS is null then null
    ELSE T1.REVIEW_STATUS
    END AS PERSON_REVIEW_STATUS ,
    CASE WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
    WHEN T1.PROJECT_SUBMISSION_STATUS =''DISCLOSURE_REQUIRED_NOT'' AND T1.RESUBMISSION_FLAG = ''N'' THEN ''Not Required''
    WHEN T1.PROJECT_SUBMISSION_STATUS =''DISCLOSURE_REQUIRED_NOT'' AND T1.RESUBMISSION_FLAG = ''Y'' THEN ''Yet to disclose''
    WHEN T1.PROJECT_SUBMISSION_STATUS =''DISCLOSURE_TO_BE_DETERMINED'' THEN NULL
    WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''
    WHEN T1.PROJECT_SUBMISSION_STATUS = ''NOT_YET_DISCLOSED'' AND T1.RESUBMISSION_FLAG = ''Y'' THEN ''Yet to disclose''
    ELSE T1.PROJECT_SUBMISSION_STATUS
    END AS PROJECT_SUBMISSION_STATUS ,
    CASE  WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_PENDING'' 
     AND T1.PROJECT_REVIEW_STATUS =''DISCLOSURE_REVIEW_NA''  THEN NULL
    WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_PENDING'' 
     AND T1.PROJECT_REVIEW_STATUS IS NOT NULL  THEN ''Pending''
	WHEN T1.PROJECT_SUBMISSION_STATUS = ''NOT_YET_DISCLOSED''  THEN NULL
    WHEN T1.PROJECT_SUBMISSION_STATUS IS NULL THEN NULL
    WHEN T1.PROJECT_REVIEW_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
    WHEN T1.PROJECT_REVIEW_STATUS =''DISCLOSURE_REVIEW_NA'' AND T1.RESUBMISSION_FLAG = ''N'' THEN ''N/A''
    WHEN T1.PROJECT_REVIEW_STATUS =''DISCLOSURE_REVIEW_NA'' AND T1.RESUBMISSION_FLAG = ''Y'' THEN NULL
    WHEN T1.PROJECT_REVIEW_STATUS =''DISCLOSURE_TO_BE_DETERMINED'' THEN NULL
    WHEN T1.PROJECT_REVIEW_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''    
    ELSE T1.PROJECT_REVIEW_STATUS
    END AS PROJECT_REVIEW_STATUS,
    T1.Complete_count,
     T1.PCK,
     T1.DISCLOSURE_VALIDATION_FLAG,
    T1.SPONSOR_HIERARCY,
    T1.Incomplete_count,
    T1.RESUBMISSION_FLAG,
           (CASE 
        WHEN T1.SPONSOR_HIERARCY = ''YES'' THEN CONCAT(
            "This award is on hold due to ",
            "the sponsor\'s requirement for a disclosure",
            CASE 
                WHEN T1.DISCLOSURE_VALIDATION_FLAG = ''SELF'' THEN ", Disclosure request from the COI administration"
                ELSE \'\'
            END,
            CASE 
                WHEN T1.PCK != ''N/A'' THEN ", and the need for the PI/COI/keyperson to complete their disclosures"
                ELSE \'\'
            END
        )
        WHEN T1.DISCLOSURE_VALIDATION_FLAG = ''SELF'' THEN CONCAT(
            "This award is on hold due to ",
            "Disclosure request from the COI administration",
            CASE 
                WHEN T1.PCK != ''N/A'' THEN ", and the need for the PI/COI/keyperson to complete their disclosures"
                ELSE \'\'
            END
        )
        WHEN T1.PCK != ''N/A'' THEN CONCAT(
            "This award is on hold due to ",
            "the need for the PI/COI/keyperson to complete their disclosures"
        )
        ELSE NULL
    END )as INFO,
    @row_number := IF(@prev_value = T1.PROJECT_ID, @row_number, @row_number + 1) AS rownumber,
	@prev_value := T1.PROJECT_ID AS PROJECT_IDS,
    T1.NON_EMPLOYEE_FLAG 
    FROM
(SELECT DISTINCT 
    T1.EXTERNAL_SYSTEM_REF_ID AS PROJECT_ID,
    T1.AWARD_NUMBER AS PROJECT_NUMBER,
    T1.TITLE,
    T1.PI_NAME,
    T1.KEY_PERSON_ID,
    T1.KEY_PERSON_NAME,
    T1.KEY_PERSON_ROLE_CODE,
    T7.DESCRIPTION AS KEY_PERSON_ROLE,
    T1.SPONSOR_NAME,
    T3.SPONSOR_CODE,
    T1.PRIME_SPONSOR_NAME,
    T4.SPONSOR_CODE AS PRIME_SPONSOR_CODE,
    T1.LEAD_UNIT_NUMBER,
    T1.LEAD_UNIT_NAME,
    T2.HOME_UNIT,
    T8.UNIT_NAME AS HOME_UNIT_NAME,
    T1.AWARD_START_DATE,
    T1.AWARD_END_DATE,
    T1.AWARD_STATUS AS PROJECT_STATUS,
    T55.DISCLOSURE_ID,
    T9.DESCRIPTION AS DISCLOSURE_REVIEW_STATUS,
    T55.FCOI_TYPE_CODE,
    T1.COI_PROJECT_TYPE_CODE AS PROJECT_TYPE_CODE,
    T10.DESCRIPTION AS PROJECT_TYPE,
    T7.SORT_ID ,
    T10.BADGE_COLOR,
    T1.UPDATE_TIMESTAMP,
    null as CERTIFICATION_FLAG,
    T1.DISCLOSURE_REQUIRED_FLAG,
    COALESCE(CC.COMMENT_COUNT, 0) AS COMMENT_COUNT,
    CASE 
        WHEN T55.REVIEW_STATUS_CODE IN (2, 3, 4, 7, 8)
        THEN "Yes"
        ELSE "No"
    END AS DISCLOSURE_COMPLETION_STATUS,
    T10.PROJECT_ICON,
    T1.DOCUMENT_NUMBER,
    T1.ACCOUNT_NUMBER,
    T1.PCK,
    T1.DISCLOSURE_VALIDATION_FLAG,
    (case when (T1.SPONSOR_CODE IN (SELECT T21.SPONSOR_CODE FROM SPONSOR_DISCLOSURE_REQUIREMENTS T21)
      OR T1.PRIME_SPONSOR_CODE IN (SELECT T21.SPONSOR_CODE FROM SPONSOR_DISCLOSURE_REQUIREMENTS T21) )
      THEN ''YES'' ELSE ''NO'' END) AS SPONSOR_HIERARCY,

(SELECT FN_GET_OVRAL_AWD_PRJT_DISCL_RVW_STATUS(T1.EXTERNAL_SYSTEM_REF_ID)) AS PROJECT_REVIEW_STATUS,
(SELECT FN_GET_OVAL_AWD_PRJT_DISCL_STATUS(T1.EXTERNAL_SYSTEM_REF_ID)) AS PROJECT_SUBMISSION_STATUS,

        (SELECT COUNT(1)
                FROM DisclosureAwardProjects
                WHERE PROJECT_ID = T1.EXTERNAL_SYSTEM_REF_ID
                    AND DISCLOSURE_STATUS = ''DISCLOSURE_COMPLETED'') AS complete_count,
	(SELECT COUNT(1)
                FROM DisclosureAwardProjects
                WHERE PROJECT_ID = T1.EXTERNAL_SYSTEM_REF_ID
                    AND DISCLOSURE_STATUS != ''DISCLOSURE_COMPLETED'') AS Incomplete_count,

    (SELECT DISCLOSURE_STATUS FROM DisclosureAwardProjects WHERE PROJECT_ID = T1.EXTERNAL_SYSTEM_REF_ID AND  KEY_PERSON_ID = T1.KEY_PERSON_ID LIMIT 1) AS DISCLOSURE_STATUS,
	(SELECT PROJECT_DISCLOSURE_REVIEW_STATUS FROM DisclosureAwardProjects WHERE PROJECT_ID = T1.EXTERNAL_SYSTEM_REF_ID AND  KEY_PERSON_ID = T1.KEY_PERSON_ID LIMIT 1 ) AS REVIEW_STATUS,
     (CASE
    WHEN EXISTS (SELECT 1 FROM coi_int_stage_award_person WHERE PROJECT_NUMBER = T1.AWARD_NUMBER AND NEW_DISCLOSURE_REQUIRED = ''Y'' AND STATUS != ''I''
    AND ATTRIBUTE_1_VALUE = ''N'') THEN ''Y''
    ELSE ''N''
  END) AS RESUBMISSION_FLAG,
  T1.NON_EMPLOYEE_FLAG
	FROM coi_project_award_v T1
	LEFT JOIN CommentsCount CC ON CC.MODULE_ITEM_KEY = T1.AWARD_NUMBER
		AND CC.MODULE_CODE = T1.COI_PROJECT_TYPE_CODE',IFNULL(LS_JOIN_CONDITION,''), '
	WHERE PERSON_STATUS != ''I'' ',IFNULL(LS_FILTER_CONDITION,''), ' GROUP BY T1.EXTERNAL_SYSTEM_REF_ID , T1.KEY_PERSON_ID,T1.KEY_PERSON_ROLE_CODE )T1',ifnull(LS_ORDER_BY,''),' )T ',IFNULL(LS_OFFSET_CONDITION,''),' ');
 
 
 IF AV_UNLIMITED = TRUE THEN
        SET LS_DYN_SQL = CONCAT('SELECT count(distinct PROJECT_ID) AS AWARD_COUNT FROM ( ',LS_DYN_SQL,' ) T');

 END IF;

SET @row_number = 0;
SET @prev_value = NULL;
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;

END
//
