\. ./FIBI-COI-5.5/FC-1283/Procedures/BULK_UPDATE_GLOBAL_ENTITY_FOREIGN_FLAG.sql
\. ./FIBI-COI-5.5/FC-1283/Procedures/GET_COI_PERSON_ENTITY_DETAILS.sql
\. ./FIBI-COI-5.5/FC-1283/Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_COUNT.sql
\. ./FIBI-COI-5.5/FC-1283/Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_DATA.sql
\. ./FIBI-COI-5.5/FC-1283/Procedures/GET_ENTITY_HIERARCHY.sql
\. ./FIBI-COI-5.5/FC-1283/Procedures/UPDATE_GLOBAL_ENTITY_FOREIGN_FLAG.sql
\. ./FIBI-COI-5.5/FC-1283/Procedures/GET_PERSON_ENTITIES.sql
