SET SQL_SAFE_UPDATES = 0;
UPDATE MESSAGE SET DESCRIPTION = 'Disclosure recall requested' WHERE (MESSAGE_TYPE_CODE = '159');
UPDATE MESSAGE SET DESCRIPTION = 'Recall Request Denied' WHERE (MESSAGE_TYPE_CODE = '160');
UPDATE MESSAGE SET DESCRIPTION = 'Disclosure revision/Recall required' WHERE (MESSAGE_TYPE_CODE = '161');
UPDATE MESSAGE SET DESCRIPTION = 'COI Annual disclosure Recall Required' WHERE (MESSAGE_TYPE_CODE = '165');

UPDATE COI_REVIEW_STATUS_TYPE SET DESCRIPTION = 'Recalled' WHERE (REVIEW_STATUS_CODE = '6');
UPDATE OPA_REVIEW_STATUS_TYPE SET DESCRIPTION = 'Recalled' WHERE (REVIEW_STATUS_CODE = '6');
UPDATE COI_TRAVEL_REVIEW_STATUS SET DESCRIPTION = 'Recalled' WHERE (REVIEW_STATUS_CODE = '5');
UPDATE CONSULTING_DISCL_REVIEW_STATUS_TYPE SET DESCRIPTION = 'Recalled' WHERE (REVIEW_STATUS_CODE = '7');

UPDATE NOTIFICATION_TYPE SET DESCRIPTION = 'FCOI Disclosure Recalled', SUBJECT = 'Recall of COI Annual Disclosure Submitted by {COI_DISCLOSURE#REPORTER_NAME}', MESSAGE = '<p><span style=\"color:hsl(0, 0%, 0%);\">A COI Annual Disclosure was submitted by {COI_DISCLOSURE#REPORTER_NAME} on {COI_DISCLOSURE#CERTIFICATION_DATE} is Recalled for the following reason “{COI_DISCL_OTHER#WITHDRAWAL_REASON}”</span></p><p><span style=\"color:hsl(0, 0%, 0%);\">Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style=\"color:hsl(0, 0%, 0%);\">Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</span></p><p><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p><span style=\"color:hsl(0, 0%, 0%);\">Note: This is a system generated email. Please do not reply to this email.</span></p>' WHERE (NOTIFICATION_TYPE_ID = '8001');
UPDATE NOTIFICATION_TYPE SET DESCRIPTION = 'Project Disclosure Recalled', SUBJECT = 'Recall of Project Disclosure Submitted by {COI_DISCLOSURE#REPORTER_NAME}', MESSAGE = '<p>A Project Disclosure was submitted by {COI_DISCLOSURE#REPORTER_NAME} on {COI_DISCLOSURE#CERTIFICATION_DATE} is Recalled for the following reason “{COI_DISCL_OTHER#WITHDRAWAL_REASON}”</p><p>Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p>Project: {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} {COI_DISCLOSURE#PROJECT_TITLE}</p><p>Disclosure Status:{COI_DISCLOSURE#DISCLOSURE_STATUS}</p><p><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (NOTIFICATION_TYPE_ID = '8008');
UPDATE NOTIFICATION_TYPE SET DESCRIPTION = 'Disclosure Request Recall', SUBJECT = 'Action Required: Recall request has been submitted  {COI_DISCLOSURE#REPORTER_NAME} ', MESSAGE = '<p>Disclosure was submitted by {COI_DISCLOSURE#REPORTER_NAME} on {COI_DISCLOSURE#CERTIFICATION_DATE} is Recalled for the following reason: {COI_DISCL_OTHER#WITHDRAWAL_REASON}</p><p>Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p>Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</p><p><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p><span style=\"color:hsl(0,0%,0%);\">Note: This is a system-generated email. Please do not reply to this email.</span></p>' WHERE (NOTIFICATION_TYPE_ID = '8039');
UPDATE NOTIFICATION_TYPE SET DESCRIPTION = 'Disclosure Request Recall Deny', SUBJECT = ' Disclosure Recall Request Submitted by {COI_DISCLOSURE#REPORTER_NAME} Declined by {COI_DISCLOSURE#ADMINISTRATOR_NAME}', MESSAGE = '<p>Dear {COI_DISCLOSURE#REPORTER_NAME},</p><p>Your request to Recall the disclosure has been declined for the following </p><p>Reason<strong>:</strong> {COI_DISCL_OTHER#DECLINE_REASON}</p><p>Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p><span style=\"color:hsl(0,0%,0%);\">Note: This is a system-generated email. Please do not reply to this email.</span></p>' WHERE (NOTIFICATION_TYPE_ID = '8040');
UPDATE NOTIFICATION_TYPE SET DESCRIPTION = 'Revise or Recall Disclosure to Reflect New Engagement', SUBJECT = 'Action Required: Revise or Recall Your Disclosure to Reflect New Engagement', MESSAGE = '<p>Dear {COI_DISCLOSURE#REPORTER_NAME},</p><p>A new engagement :<strong> {COI_DISCL_OTHER#ENGAGEMENT_NAME} </strong> has been created in the system, and a financial relationship has been marked. Please either revise or Recall your initial disclosure to reflect this change.</p><p><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_HOME_PAGE_URL#HOME_PAGE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p><span style=\"color:hsl(0,0%,0%);\">Note: This is a system-generated email. Please do not reply to this email.</span></p>' WHERE (NOTIFICATION_TYPE_ID = '8041');
UPDATE NOTIFICATION_TYPE SET DESCRIPTION = 'Travel Disclosure Recall', SUBJECT = 'Recall of Travel Disclosure Submitted by {TRAVEL_DETAILS#REPORTER_NAME}', MESSAGE = '<p>A Travel Disclosure was submitted by {TRAVEL_DETAILS#REPORTER_NAME} on {TRAVEL_DETAILS#CERTIFICATION_DATE} is Recalled for the following reason “{TRAVEL_OTHER#WITHDRAWAL_REASON}”</p><p>Department : {TRAVEL_DETAILS#DEPARTMENT_NUMBER} - {TRAVEL_DETAILS#DEPARTMENT_NAME}</p><p>Entity Name: {TRAVEL_DETAILS#ENTITY_NAME}</p><p>Travel Start date: {TRAVEL_DETAILS#TRAVEL_START_DATE}</p><p>Travel End Date: {TRAVEL_DETAILS#TRAVEL_END_DATE}</p><p>Please follow <a href=\"{TRAVEL_URL#TRAVEL_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (NOTIFICATION_TYPE_ID = '8047');
UPDATE NOTIFICATION_TYPE SET DESCRIPTION = 'Resubmission of Travel Disclosure After Recalled' WHERE (NOTIFICATION_TYPE_ID = '8057');
UPDATE NOTIFICATION_TYPE SET DESCRIPTION = 'OPA Disclosure Recall.', SUBJECT = 'Recall of OPA Disclosure Submitted by {OPA_DETAILS#REPORTER_NAME}.', MESSAGE = '<p>A OPA Disclosure was submitted by {OPA_DETAILS#REPORTER_NAME} on {OPA_DETAILS#CERTIFICATION_DATE} is Recalled for the following reason: <strong>“{OPA_OTHER#WITHDRAWAL_REASON}”</strong></p><p><strong>Department</strong>: {OPA_DETAILS#HR_ORG_UNIT_NUMBER} - {OPA_DETAILS#HR_ORG_UNIT_NAME}</p><p>Please go to<strong> </strong><a href=\"{OPA_URL#OPA_URL}\"><strong>this link</strong></a> to view the details.</p><p>Thank you.</p><p> </p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (NOTIFICATION_TYPE_ID = '8064');
UPDATE NOTIFICATION_TYPE SET DESCRIPTION = 'Resubmission of OPA Disclosure After Recalled', SUBJECT = 'Action Required - Resubmitted OPA Disclosure (Previously Recalled)', MESSAGE = '<p>Hello Admins,</p><p style=\"margin-left:0px;\"><span style=\"background-color:rgb(255,255,255);color:rgb(64,64,64);\">An OPA Disclosure that was previously Recalled has been resubmitted for your review:</span></p><p style=\"margin-left:0px;\"><strong>Submitted By:</strong> {OPA_DETAILS#REPORTER_NAME}</p><p style=\"margin-left:0px;\"><strong>Submission Date:</strong> {OPA_DETAILS#CERTIFICATION_DATE}</p><p style=\"margin-left:0px;\"><strong>Department:</strong> {OPA_DETAILS#HR_ORG_UNIT_NUMBER} - {OPA_DETAILS#HR_ORG_UNIT_NAME}</p><p>Please go to <a href=\"{OPA_URL#OPA_URL}\"><strong>this link</strong></a> to view the details.</p><p>Thank you.</p><p> </p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (NOTIFICATION_TYPE_ID = '8065');

UPDATE MODULE_ACTION_TYPE SET DESCRIPTION = 'FCOI Disclosure Recall' WHERE (MODULE_ACTION_TYPE_ID = '7');
UPDATE MODULE_ACTION_TYPE SET DESCRIPTION = 'Project Disclosure Recall' WHERE (MODULE_ACTION_TYPE_ID = '8');
UPDATE MODULE_ACTION_TYPE SET DESCRIPTION = 'Disclosure Request Recall' WHERE (MODULE_ACTION_TYPE_ID = '38');
UPDATE MODULE_ACTION_TYPE SET DESCRIPTION = 'Disclosure Request Recall Deny' WHERE (MODULE_ACTION_TYPE_ID = '39');
UPDATE MODULE_ACTION_TYPE SET DESCRIPTION = 'Travel Recall' WHERE (MODULE_ACTION_TYPE_ID = '49');
UPDATE MODULE_ACTION_TYPE SET DESCRIPTION = 'Resubmission of Travel Disclosure After Recalled' WHERE (MODULE_ACTION_TYPE_ID = '56');
UPDATE MODULE_ACTION_TYPE SET DESCRIPTION = 'OPA Recall' WHERE (MODULE_ACTION_TYPE_ID = '61');
UPDATE MODULE_ACTION_TYPE SET DESCRIPTION = 'OPA Recalled Resubmission' WHERE (MODULE_ACTION_TYPE_ID = '64');

UPDATE `OPA_Action_Log_Type` SET `MESSAGE` = 'OPA disclosure <b>recalled</b> by <b>{REPORTER}</b>' WHERE (`ACTION_TYPE_CODE` = '3');

SET SQL_SAFE_UPDATES = 1;
