UPDATE `business_rule_function_arg` SET `ARGUMENT_NAME` = 'AV_DISCLOSURE_ID' WHERE (`FUNCTION_NAME` = 'For All OPAs') and (`ARGUMENT_SEQUENCE_NUMBER` = '1');

/*
ALTER TABLE WORKFLOW_MAP_DETAIL ADD COLUMN ADMIN_GROUP_ID INT DEFAULT NULL,
ADD CONSTRAINT WORKFLOW_MAP_DETAIL_FK4 FOREIGN KEY (ADMIN_GROUP_ID) REFERENCES ADMIN_GROUP (ADMIN_GROUP_ID);

ALTER TABLE WORKFLOW_DETAIL ADD COLUMN ADMIN_GROUP_ID INT DEFAULT NULL,
 ADD CONSTRAINT WORKFLOW_DETAIL_FK6 FOREIGN KEY (ADMIN_GROUP_ID) REFERENCES ADMIN_GROUP (ADMIN_GROUP_ID);
*/
