DELIMITER //
CREATE PROCEDURE `COI_DISCL_ENT_PROJ_DETAILS`(
	AV_DISCLOSURE_ID          INT,
	AV_PERSON_ENTITY_ID       INT,
    AV_MODULE_CODE            INT(3),
    AV_MODULE_ITEM_KEY        VARCHAR(100)
)
BEGIN

DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LS_QRY_CONDITIONS LONGTEXT;

SET LS_DYN_SQL ='';
SET LS_QRY_CONDITIONS ='';

    IF AV_PERSON_ENTITY_ID IS NOT NULL THEN
        SET LS_QRY_CONDITIONS = CONCAT(' AND T1.PERSON_ENTITY_ID = ', AV_PERSON_ENTITY_ID, ' ' );

    ELSEIF AV_MODULE_CODE IS NOT NULL AND AV_MODULE_ITEM_KEY IS NOT NULL THEN
            SET LS_QRY_CONDITIONS = CONCAT(' AND T1.MODULE_CODE = ', AV_MODULE_CODE, ' AND T1.MODULE_ITEM_KEY = ''',AV_MODULE_ITEM_KEY,'''' );

    END IF;

    SET LS_DYN_SQL = CONCAT('SELECT DISTINCT T1.DISCLOSURE_DETAILS_ID,T1.DISCLOSURE_ID, T1.DISCLOSURE_NUMBER, T1.PERSON_ENTITY_ID,
        T1.PERSON_ENTITY_NUMBER, T1.PREVIOUS_PERSON_ENTITY_ID, T1.ENTITY_ID, T1.ENTITY_NUMBER, T1.MODULE_CODE, T1.MODULE_ITEM_KEY,
        T1.PROJECT_CONFLICT_STATUS_CODE, T1.UPDATE_USER, T1.UPDATE_TIMESTAMP, T8.ENTITY_NAME, T8.VERSION_NUMBER, T8.VERSION_STATUS,
        T8.ENTITY_STATUS_CODE, T8.CREATE_USER AS ENTITY_CREATE_USER, T8.CREATE_TIMESTAMP AS ENTITY_CREATE_TIMESTAMP,
        T8.UPDATE_USER AS ENTITY_UPDATE_USER, T8.UPDATE_TIMESTAMP AS ENTITY_UPDATE_TIMESTAMP, T8.RISK_CATEGORY_CODE,
        COALESCE(T2.EXTERNAL_SYSTEM_REF_ID, T3.EXTERNAL_SYSTEM_REF_ID, T4.EXTERNAL_SYSTEM_REF_ID) AS PROJECT_ID,
        COALESCE(T2.AWARD_NUMBER, T3.PROPOSAL_NUMBER, T4.PROPOSAL_NUMBER) AS PROJECT_NUMBER,
        COALESCE(T2.TITLE, T3.TITLE, T4.TITLE) AS PROJECT_TITLE,
        COALESCE(T5.COI_PROJECT_TYPE_CODE, T6.COI_PROJECT_TYPE_CODE, T7.COI_PROJECT_TYPE_CODE) AS COI_PROJECT_TYPE_CODE,
        COALESCE(T5.DESCRIPTION, T6.DESCRIPTION, T7.DESCRIPTION) AS COI_PROJECT_TYPE,
        COALESCE(T5.BADGE_COLOR, T6.BADGE_COLOR, T7.BADGE_COLOR) AS BADGE_COLOR, T9.DESCRIPTION AS PROJECT_CONFLICT_STATUS
        FROM COI_DISCL_ENT_PROJ_DETAILS T1
        LEFT JOIN COI_PROJECT_AWARD_V T2 ON T2.EXTERNAL_SYSTEM_REF_ID = T1.MODULE_ITEM_KEY AND T1.MODULE_CODE = 1
        LEFT JOIN COI_PROJECT_PROPOSAL_V T3 ON T3.EXTERNAL_SYSTEM_REF_ID = T1.MODULE_ITEM_KEY AND T1.MODULE_CODE = 3
        LEFT JOIN coi_project_institute_proposal_v T4 ON T4.EXTERNAL_SYSTEM_REF_ID = T1.MODULE_ITEM_KEY AND T1.MODULE_CODE = 2
        LEFT JOIN COI_PROJECT_TYPE T5 ON T5.COI_PROJECT_TYPE_CODE = T2.COI_PROJECT_TYPE_CODE
        LEFT JOIN COI_PROJECT_TYPE T6 ON T6.COI_PROJECT_TYPE_CODE = T3.COI_PROJECT_TYPE_CODE
        LEFT JOIN COI_PROJECT_TYPE T7 ON T7.COI_PROJECT_TYPE_CODE = T4.COI_PROJECT_TYPE_CODE
        LEFT JOIN ENTITY T8 ON T8.ENTITY_ID = T1.ENTITY_ID
        LEFT JOIN COI_PROJ_CONFLICT_STATUS_TYPE T9 ON T9.PROJECT_CONFLICT_STATUS_CODE = T1.PROJECT_CONFLICT_STATUS_CODE
        WHERE T1.DISCLOSURE_ID = ', AV_DISCLOSURE_ID, LS_QRY_CONDITIONS,
        ' ORDER BY T1.UPDATE_TIMESTAMP DESC');


SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;

END
//