CREATE TABLE per_ent_data_capturing_type (
  DATA_CAPTURING_TYPE_CODE int NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(500) DEFAULT NULL,
  IS_ACTIVE char(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (DATA_CAPTURING_TYPE_CODE)
);

CREATE TABLE per_ent_discl_type_selection (
  ID int NOT NULL AUTO_INCREMENT,
  PERSON_ENTITY_ID int DEFAULT NULL,
  DISCLOSURE_TYPE_CODE varchar(3) DEFAULT NULL,
  DATA_CAPTURING_TYPE_CODE int DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY PER_ENT_DISCL_TYPE_SELECTION_FK1_idx (PERSON_ENTITY_ID),
  KEY PER_ENT_DISCL_TYPE_SELECTION_FK2_idx (DISCLOSURE_TYPE_CODE),
  KEY PER_ENT_DISCL_TYPE_SELECTION_FK3_idx (DATA_CAPTURING_TYPE_CODE),
  CONSTRAINT PER_ENT_DISCL_TYPE_SELECTION_FK1 FOREIGN KEY (PERSON_ENTITY_ID) REFERENCES person_entity (PERSON_ENTITY_ID),
  CONSTRAINT PER_ENT_DISCL_TYPE_SELECTION_FK2 FOREIGN KEY (DISCLOSURE_TYPE_CODE) REFERENCES coi_disclosure_type (DISCLOSURE_TYPE_CODE),
  CONSTRAINT PER_ENT_DISCL_TYPE_SELECTION_FK3 FOREIGN KEY (DATA_CAPTURING_TYPE_CODE) REFERENCES per_ent_data_capturing_type (DATA_CAPTURING_TYPE_CODE)
);

CREATE TABLE per_ent_matrix_answer_type (
  ANSWER_TYPE_CODE int NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(20) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (ANSWER_TYPE_CODE)
);

CREATE TABLE per_ent_matrix_group (
  GROUP_ID int NOT NULL AUTO_INCREMENT,
  GROUP_NAME varchar(500) NOT NULL,
  SORT_ID int DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) NOT NULL,
  PRIMARY KEY (GROUP_ID)
);

CREATE TABLE per_ent_matrix_question (
  MATRIX_QUESTION_ID int NOT NULL AUTO_INCREMENT,
  COLUMN_LABEL varchar(500) NOT NULL,
  ANSWER_TYPE_CODE int NOT NULL,
  LOOKUP_TYPE varchar(50) DEFAULT NULL,
  LOOKUP_VALUE varchar(50) DEFAULT NULL,
  GROUP_ID int DEFAULT NULL,
  SORT_ID int DEFAULT NULL,
  IS_ACTIVE char(1) NOT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) NOT NULL,
  PRIMARY KEY (MATRIX_QUESTION_ID),
  KEY COI_MATRIX_QUESTION_FK1 (GROUP_ID),
  KEY COI_MATRIX_QUESTION_FK2_idx (ANSWER_TYPE_CODE),
  CONSTRAINT COI_MATRIX_QUESTION_FK1 FOREIGN KEY (GROUP_ID) REFERENCES per_ent_matrix_group (GROUP_ID),
  CONSTRAINT COI_MATRIX_QUESTION_FK2 FOREIGN KEY (ANSWER_TYPE_CODE) REFERENCES per_ent_matrix_answer_type (ANSWER_TYPE_CODE)
);

CREATE TABLE per_ent_matrix_answer (
  MATRIX_ANSWER_ID int NOT NULL AUTO_INCREMENT,
  PERSON_ENTITY_ID int DEFAULT NULL,
  PERSON_ENTITY_NUMBER int DEFAULT NULL,
  MATRIX_QUESTION_ID int DEFAULT NULL,
  COLUMN_VALUE varchar(500) DEFAULT NULL,
  RELATIONSHIP_TYPE_CODE varchar(3) DEFAULT NULL,
  COMMENTS varchar(500) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (MATRIX_ANSWER_ID),
  KEY COI_MATRIX_ANSWER_FK2 (MATRIX_QUESTION_ID),
  KEY COI_MATRIX_ANSWER_FK1 (RELATIONSHIP_TYPE_CODE),
  CONSTRAINT COI_MATRIX_ANSWER_FK1 FOREIGN KEY (RELATIONSHIP_TYPE_CODE) REFERENCES person_entity_rel_type (RELATIONSHIP_TYPE_CODE),
  CONSTRAINT COI_MATRIX_ANSWER_FK2 FOREIGN KEY (MATRIX_QUESTION_ID) REFERENCES per_ent_matrix_question (MATRIX_QUESTION_ID)
);

CREATE TABLE per_ent_matrix_rel_mapping (
  MAPPING_CODE varchar(3) NOT NULL,
  RELATIONSHIP_TYPE_CODE varchar(3) NOT NULL,
  MATRIX_QUESTION_ID int NOT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (MAPPING_CODE),
  KEY RELATIONSHIP_TYPE_CODE (RELATIONSHIP_TYPE_CODE),
  KEY MATRIX_QUESTION_ID (MATRIX_QUESTION_ID),
  CONSTRAINT MATRIX_PERSON_REL_MAPPING_FK1 FOREIGN KEY (RELATIONSHIP_TYPE_CODE) REFERENCES person_entity_rel_type (RELATIONSHIP_TYPE_CODE),
  CONSTRAINT MATRIX_PERSON_REL_MAPPING_FK2 FOREIGN KEY (MATRIX_QUESTION_ID) REFERENCES per_ent_matrix_question (MATRIX_QUESTION_ID)
);

