\. ./FIBI-COI-5.8.6/FC-1721/Functions/FN_CHK_CAN_CREATE_DECLARATION.sql
\. ./FIBI-COI-5.8.6/FC-1721/Procedures/COI_DECLARATION_EXPIRY_REMINDER.sql
\. ./FIBI-COI-5.8.6/FC-1721/Procedures/UPDT_PERSON_DECLRATION_ELGBLTY.sql
