ALTER TABLE INDUSTRY_CATEGORY_TYPE ADD COLUMN `SOURCE` VARCHAR(1) NULL DEFAULT NULL;

SET SQL_SAFE_UPDATES = 0;

UPDATE INDUSTRY_CATEGORY_TYPE SET SOURCE = 'D' WHERE SOURCE IS NULL;

SET SQL_SAFE_UPDATES = 1;

INSERT INTO INDUSTRY_CATEGORY_TYPE (INDUSTRY_CATEGORY_TYPE_CODE, IS_PRIMARY, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY, SOURCE) VALUES ('S001', 'N', 'MIT Reporting', 'Y', now(), '10000000001', 'S');

INSERT INTO INDUSTRY_CATEGORY_CODE (INDUSTRY_CATEGORY_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('S001', 'Fossil Fuel', 'Y', now(), '10000000001');
INSERT INTO INDUSTRY_CATEGORY_CODE (INDUSTRY_CATEGORY_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('S001', 'Climate', 'Y', now(), '10000000001');
INSERT INTO INDUSTRY_CATEGORY_CODE (INDUSTRY_CATEGORY_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('S001', 'AI', 'Y', now(), '10000000001');
INSERT INTO INDUSTRY_CATEGORY_CODE (INDUSTRY_CATEGORY_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('S001', 'Foreign Aid', 'Y', now(), '10000000001');
