DROP PROCEDURE IF EXISTS GET_COI_ENTITY_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_OPA_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITIES;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITY_INFO;