UPDATE `NOTIFICATION_TYPE` SET `MESSAGE` = '<p>A OPA Disclosure was submitted by {OPA_DETAILS#REPORTER_NAME} on {OPA_DETAILS#CERTIFICATION_DATE}.</p><p>Department: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8063');

UPDATE `NOTIFICATION_TYPE` SET `MESSAGE` = '<p>Dear {OPA_DETAILS#REPORTER_NAME},</p><p>Your OPA disclosure submitted on {OPA_DETAILS#CERTIFICATION_DATE} was returned for the following reason “{OPA_OTHER#RETURN_REASON}”.</p><p>Department: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8067');

UPDATE `NOTIFICATION_TYPE` SET `DESCRIPTION` = 'OPA Disclosure Notify Reassigned Administrator', `MESSAGE` = '<p>Hello {OPA_OTHER#ADMIN_ASSIGNED_TO},</p><p>OPA Administrator {OPA_OTHER#ADMIN_ASSIGNED_BY} assigned you as the Administrator of the OPA Disclosure submitted on {OPA_DETAILS#CERTIFICATION_DATE} by {OPA_DETAILS#REPORTER_NAME}.</p><p>Department: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8071');

UPDATE `NOTIFICATION_TYPE` SET `MESSAGE` = '<p>Dear Reviewer,</p><p>The following OPA Disclosure is rejected. Details are given below:</p><p>Submitted by: {OPA_DETAILS#REPORTER_NAME}</p><p>Lead Unit: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p>Comments: {OPA_OTHER#WORKFLOW_COMMENT}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Thank you.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8072');

UPDATE `NOTIFICATION_TYPE` SET `MESSAGE` = '<p>Dear {OPA_DETAILS#REPORTER_NAME},</p><p>Your OPA disclosure submitted on {OPA_DETAILS#CERTIFICATION_DATE} has been approved by {OPA_OTHER#ADMINISTRATOR_NAME}.</p><p>Department: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}<br>Disclosure Status: {OPA_DETAILS#DISPOSITION_STATUS}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8074');

UPDATE `NOTIFICATION_TYPE` SET `MESSAGE` = '<p>Hello,</p><p>OPA Administrator {OPA_OTHER#ADMINISTRATOR_NAME} assigned you to review the OPA submitted on {OPA_DETAILS#CERTIFICATION_DATE} by {OPA_DETAILS#REPORTER_NAME}.</p><p>Department: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p>Disclosure Status: {OPA_DETAILS#DISPOSITION_STATUS}</p><p>Review Location: {OPA_OTHER#REVIEW_LOCATION}</p><p>Review Status: {OPA_OTHER#REVIEWER_REVIEW_STATUS}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8075');

UPDATE `NOTIFICATION_TYPE` SET `MESSAGE` = '<p>Hello OPA Admin,</p><p>OPA Reviewer {OPA_OTHER#REVIEWER_NAME} has completed the review of the OPA Disclosure submitted on {OPA_DETAILS#CERTIFICATION_DATE} by {OPA_DETAILS#REPORTER_NAME}.</p><p>Department: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p>Disclosure Status: {OPA_DETAILS#DISPOSITION_STATUS}</p><p>Review Location: {OPA_OTHER#REVIEW_LOCATION}</p><p>Review Status: {OPA_OTHER#REVIEWER_REVIEW_STATUS}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8076');

UPDATE `NOTIFICATION_TYPE` SET `MESSAGE` = '<p>Hello {OPA_OTHER#ADMIN_ASSIGNED_TO},</p><p>OPA Administrator {OPA_OTHER#ADMIN_ASSIGNED_BY} assigned you as the Administrator of the OPA Disclosure submitted on {OPA_DETAILS#CERTIFICATION_DATE} by {OPA_DETAILS#REPORTER_NAME}.</p><p>Department: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p>Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8069');

UPDATE `NOTIFICATION_TYPE` SET `DESCRIPTION` = 'OPA Disclosure Administrator Reassigned', `MESSAGE` = '<p>Hello {OPA_OTHER#ADMINISTRATOR_NAME},</p><p>The OPA Administrator {OPA_OTHER#ADMIN_ASSIGNED_BY} removed you as a Administrator for the OPA Disclosure submitted on {OPA_DETAILS#CERTIFICATION_DATE} by {OPA_DETAILS#REPORTER_NAME}.</p><p>Department: {OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p>You are no longer responsible for reviewing this disclosure.</p><p>You can access the OPA Dashboard at <a href=\"{OPA_URL#OPA_URL}\">link</a>.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8070');

INSERT INTO `NOTIFICATION_TYPE` (`NOTIFICATION_TYPE_ID`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`SUBJECT`,`MESSAGE`,`PROMPT_USER`,`IS_ACTIVE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`IS_SYSTEM_SPECIFIC`,`SHOW_TEMPLATE_IN_MODULE`,`SENT_TO_INITIATOR`) VALUES (8077,23,0,'OPA Disclosure Reviewer Remove','Your access to the OPA Disclosure of {OPA_DETAILS#REPORTER_NAME} submitted on {OPA_DETAILS#CERTIFICATION_DATE} has been removed.','<p>Hi,</p><p>Your access to the OPA Disclosure of {OPA_DETAILS#REPORTER_NAME} submitted on {OPA_DETAILS#CERTIFICATION_DATE} has been removed.</p><p><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p><span style=\"color:hsl(0,0%,0%);\">Note: This is a system-generated email. Please do not reply to this email.</span></p>','N','Y','admin',now(),'',NULL,'N',NULL,NULL);

INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8077,NULL,69,NULL,now(),NULL,NULL,'CC','OPA Admin Group');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8077,NULL,66,NULL,now(),NULL,NULL,'CC','OPA Administrators');

DELETE FROM NOTIFICATION_RECIPIENT WHERE NOTIFICATION_TYPE_ID = 8069;
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8069,NULL,67,NULL,now(),NULL,NULL,'TO','OPA Primary Administrator');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8069,NULL,66,NULL,now(),NULL,NULL,'CC','OPA Administrators');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8069,NULL,69,NULL,now(),NULL,NULL,'CC','OPA Admin Group');

DELETE FROM NOTIFICATION_RECIPIENT WHERE NOTIFICATION_TYPE_ID = 8071;
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8071,NULL,69,NULL,now(),NULL,NULL,'CC','OPA Admin Group');

DELETE FROM NOTIFICATION_RECIPIENT WHERE NOTIFICATION_TYPE_ID = 8070;
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8070,NULL,69,NULL,now(),NULL,NULL,'CC','OPA Admin Group');

DELETE FROM NOTIFICATION_RECIPIENT WHERE NOTIFICATION_TYPE_ID = 8075;
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8075,NULL,69,NULL,now(),NULL,NULL,'CC','OPA Admin Group');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8075,NULL,66,NULL,now(),NULL,NULL,'CC','OPA Administrators');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8075,NULL,70,NULL,now(),NULL,NULL,'TO','OPA Reviewer');

DELETE FROM NOTIFICATION_RECIPIENT WHERE NOTIFICATION_TYPE_ID = 8076;
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8076,NULL,67,NULL,now(),NULL,NULL,'TO','OPA Primary Administrator');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8076,NULL,69,NULL,now(),NULL,NULL,'CC','OPA Admin Group');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8076,NULL,66,NULL,now(),NULL,NULL,'CC','OPA Administrators');

UPDATE NOTIFY_PLACEHOLDER_COLUMNS 
SET URL_PATH = '/opa/form?disclosureId={OPA_DETAILS#OPA_DISCLOSURE_ID}' 
WHERE NOTIFY_PLACEHOLDER_HEADER_ID = 21 
AND QUERY_COLUMN_NAME = 'OPA_URL';

INSERT INTO `MESSAGE` (`MESSAGE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('8031','OPA disclosure waiting for review',now(),'admin');

UPDATE NOTIFICATION_RECIPIENT 
SET RECIPIENT_NAME = 'OPA Administrators' 
WHERE NOTIFICATION_TYPE_ID IN ('8063', '8064', '8065');

INSERT INTO `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`,`ACTION_TYPE`,`MODULE_CODE`,`SUB_MODULE_CODE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (75,'OPA_ADMIN_REMOVE',23,0,'y','OPA Admin Removal',now(),'admin');
INSERT INTO `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`,`ACTION_TYPE`,`MODULE_CODE`,`SUB_MODULE_CODE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (76,'OPA_REVIEWER_REMOVE',23,0,'Y','OPA Reviewer Removal',now(),'admin');

INSERT INTO `NOTIFY_ACTION_TYPE_MAP` (`NOTIFICATION_TYPE_ID`,`MODULE_ACTION_TYPE_ID`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (8070,75,now(),'admin');
INSERT INTO `NOTIFY_ACTION_TYPE_MAP` (`NOTIFICATION_TYPE_ID`,`MODULE_ACTION_TYPE_ID`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (8077,76,now(),'admin');

INSERT INTO `MQ_ROUTER_ACTION_CONFIGURATION` (`ACTION_TYPE`,`IS_ACTIVE`,`MODULE_CODE`,`QUEUE_NAME`,`SUB_MODULE_CODE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('OPA_ADMIN_REMOVE','Y',23,'Q_NOTIFICATION',0,now(),'admin');
INSERT INTO `MQ_ROUTER_ACTION_CONFIGURATION` (`ACTION_TYPE`,`IS_ACTIVE`,`MODULE_CODE`,`QUEUE_NAME`,`SUB_MODULE_CODE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('OPA_REVIEWER_REMOVE','Y',23,'Q_NOTIFICATION',0,now(),'admin');
