INSERT INTO FIBI_COI_ENG_REVIEW_STATUS (ENG_REVIEW_STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) 
VALUES 
(1, 'COMPLETED', UTC_TIMESTAMP(), 'admin'),
(2, 'EXCLUDED', UTC_TIMESTAMP(), 'admin'),
(3, 'TO REVIEW', UTC_TIMESTAMP(), 'admin');

INSERT INTO FIBI_COI_ENTITY_STATUS (STATUS_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) 
VALUES 
(1, 'Active', UTC_TIMESTAMP(), 'admin'),
(2, 'Inactive', UTC_TIMESTAMP(), 'admin');

INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'INCOME_ROYALTY', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'INCOME_BOARD_MEMBER', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'INCOME_CONSULTING', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('4', 'INCOME_EMPLOYEE', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('5', 'INCOME_SPEAKING', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('6', 'STOCK_ANY_EQUITY', '2', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('7', 'STOCK_COMMON', '2', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('8', 'STOCK_OPTIONS', '2', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('9', 'STOCK_OTHER', '2', UTC_TIMESTAMP(), 'admin');

INSERT INTO `PARAMETER` (`PARAMETER_NAME`, `VALUE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('ENABLE_LEGACY_ENG_MIG', 'Y', 'This is set to Y to enable migration of legacy engagements.', UTC_TIMESTAMP(), 'admin');

INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'City or Township Government', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'State Government', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'Federal Government', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('4', 'Nonprofit with 501C3 IRS status (other than Institution of Higher Education)', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('5', 'Nonprofit without 501C3 IRS status (other than Institution of Higher Education)', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('6', 'For-profit Organization (other than small business)', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('7', 'Other', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('8', 'Native American Tribal Government (Federally Recognized)', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('9', 'Individual', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('10', 'Private Institution of Higher Education', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('11', 'Small Business', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('14', 'Other - Socially and economically disadvantaged', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('15', 'Other - Women owned', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('21', 'State-Controlled Institution of Higher Education', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('22', 'County Government', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('23', 'Special District Governments', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('24', 'Independent School District', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('25', 'Public/Indian Housing Authority', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('26', 'Native American Tribal Organization (other than Federally recognized)', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('27', 'Frequently used in IRB', UTC_TIMESTAMP(), 'admin');
INSERT INTO `FIBI_COI_ENTITY_TYPE` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('28', 'Foreign University/governmental organization', UTC_TIMESTAMP(), 'admin');
