ALTER TABLE discl_attachment CHANGE COLUMN update_user UPDATED_BY VARCHAR(40) NULL DEFAULT NULL;
ALTER TABLE discl_attachment CHANGE COLUMN create_user CREATED_BY VARCHAR(40) NULL DEFAULT NULL;
ALTER TABLE attachments CHANGE COLUMN UPDATE_USER UPDATED_BY VARCHAR(40) NULL DEFAULT NULL;
ALTER TABLE attachments CHANGE COLUMN CREATE_USER CREATED_BY VARCHAR(40) NULL DEFAULT NULL;

set sql_safe_updates = 0;
UPDATE discl_attachment DA
JOIN PERSON p ON DA.UPDATED_BY = p.USER_NAME
SET DA.UPDATED_BY = p.PERSON_ID
WHERE DA.UPDATED_BY REGEXP '^[A-Za-z]'
AND p.USER_NAME IS NOT NULL;

UPDATE discl_attachment DA
JOIN PERSON p ON DA.CREATED_BY = p.USER_NAME
SET DA.CREATED_BY = p.PERSON_ID
WHERE DA.CREATED_BY REGEXP '^[A-Za-z]'
AND p.USER_NAME IS NOT NULL;

UPDATE attachments A
JOIN PERSON p ON A.UPDATED_BY = p.USER_NAME
SET A.UPDATED_BY = p.PERSON_ID
WHERE A.UPDATED_BY REGEXP '^[A-Za-z]'
AND p.USER_NAME IS NOT NULL;

UPDATE attachments A
JOIN PERSON p ON A.CREATED_BY = p.USER_NAME
SET A.CREATED_BY = p.PERSON_ID
WHERE A.CREATED_BY REGEXP '^[A-Za-z]'
AND p.USER_NAME IS NOT NULL;
set sql_safe_updates = 1;
