DROP FUNCTION IF EXISTS FN_FOR_ALL_COI_DISCL;
DROP FUNCTION IF EXISTS FN_WORKFLOW_APPROVE;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS INSERT_WORKFLOW_ALTER_APPROVER;
DROP PROCEDURE IF EXISTS INSERT_WORKFLOW_FOR_ROLE_TYPE;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_FUNCTION;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_WORKFLOW;
