INSERT INTO `message` (`MESSAGE_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES ('8036', 'Annual Disclosure Waiting for approval', now(), 'quickstart');

INSERT INTO `message` (`MESSAGE_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES ('8037', 'Project Disclosure Waiting for approval', now(), 'quickstart');

INSERT INTO `BUSINESS_RULE_FUNCTION` (`FUNCTION_NAME`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`DB_FUNCTION_NAME`,`UPDATE_TIMESTAMP`,`UPDATE_USER`)
VALUES ('For all financial disclosures',8,0,'For all financial disclosures','FN_FOR_ALL_COI_DISCL',now(),'quickstart');

INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`,`ARGUMENT_SEQUENCE_NUMBER`,`ARGUMENT_NAME`,`DESCRIPTION`,`DATA_TYPE`,`DEFAULT_VALUE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`LOOKUP_WINDOW_NAME`,`LOOKUP_TYPE`,`ARGUMENT_TYPE`,`ARGUMENT_LABEL`)
VALUES ('For all financial disclosures',1,'AV_DISCLOSURE_ID','For all financial disclosures',NULL,NULL,now(),'quickstart',NULL,NULL,NULL,NULL);

INSERT INTO `disclosure_action_type` (`ACTION_TYPE_CODE`, `MESSAGE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES ('35', 'Route Log review <b>completed</b>', 'Route Log review completed', now(), 'quickstart');

INSERT IGNORE INTO PARAMETER (PARAMETER_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES ('FCOI_APPROVAL_FLOW_TYPE', 'ADMIN_REVIEW',  'This is used to define the FCOI Approval flow type the system follows. Can have values ROUTING_AND_ADMIN_REVIEW, ROUTING_REVIEW, ADMIN_REVIEW, and NO_REVIEW.',  UTC_TIMESTAMP(), 'quickstart');

INSERT IGNORE INTO COI_REVIEW_STATUS_TYPE (REVIEW_STATUS_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER, SORT_ORDER)
VALUES ('9', 'Routing in progress', 'Y', UTC_TIMESTAMP(), 'quickstart', '9');
