DELIMITER //
CREATE FUNCTION FN_QRY_RVW_DAS_OVRVW_TRAVEL_FIL_COND(
    AV_PERSON_ID VARCHAR(40),
    JSON_INPUT JSON
)
RETURNS TEXT
DETERMINISTIC
BEGIN

    DECLARE LS_FILTER_CONDITION             LONGTEXT    DEFAULT '';
    DECLARE AV_FREE_TEXT_SEARCH_FIELDS      VARCHAR(500);
    DECLARE AV_TAB_TYPE                     VARCHAR(200);
    DECLARE AV_HOME_UNIT                    VARCHAR(500);
    DECLARE AV_FETCH_TYPE                   VARCHAR(50);
    DECLARE AV_DISCLOSURE_PERSON            VARCHAR(200);
    DECLARE AV_END_DATE                     VARCHAR(20);
    DECLARE AV_CERTIFICATION_DATE           VARCHAR(20);
    DECLARE AV_ENTITY                       VARCHAR(200);
    DECLARE AV_DOCUMENT_STATUS_CODE         VARCHAR(50);
    DECLARE AV_REVIEW_STATUS_CODE           VARCHAR(50);
    DECLARE AV_ADMINISTRATOR                VARCHAR(200);
    DECLARE AV_COUNTRY                      VARCHAR(100);
    DECLARE AV_TRIP_TITLE                   VARCHAR(500);
    DECLARE AV_TRAVEL_START_DATE            VARCHAR(20);
    DECLARE AV_TRAVEL_END_DATE              VARCHAR(20);
    DECLARE AV_INCLUDE_CHILD_UNITS          BOOLEAN;
    DECLARE AV_TRAVEL_PERSON_ID             VARCHAR(40);

    SET AV_FREE_TEXT_SEARCH_FIELDS  = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.SEARCH_KEYWORD'));
    SET AV_TAB_TYPE                 = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.TAB_TYPE'));
    SET AV_HOME_UNIT                = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.HOME_UNIT'));
    SET AV_FETCH_TYPE               = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.FETCH_TYPE'));
    SET AV_DISCLOSURE_PERSON        = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.DISCLOSURE_PERSON'));
    SET AV_END_DATE                 = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.END_DATE'));
    SET AV_CERTIFICATION_DATE       = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.CERTIFIED_AT'));
    SET AV_ENTITY                   = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.ENTITY'));
    SET AV_DOCUMENT_STATUS_CODE     = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.DOCUMENT_STATUS_CODE'));
    SET AV_REVIEW_STATUS_CODE       = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.REVIEW_STATUS_CODE'));
    SET AV_ADMINISTRATOR            = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.ADMIN_PERSON_ID'));
    SET AV_COUNTRY                  = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.COUNTRY'));
    SET AV_TRIP_TITLE               = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.TRIP_TITLE'));
    SET AV_TRAVEL_START_DATE        = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.TRAVEL_START_DATE'));
    SET AV_TRAVEL_END_DATE          = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.TRAVEL_END_DATE'));
    SET AV_INCLUDE_CHILD_UNITS      = JSON_EXTRACT(JSON_INPUT, '$.INCLUDE_CHILD_UNITS');
    SET AV_TRAVEL_PERSON_ID       = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.PERSON'));

    IF AV_FETCH_TYPE = 'HEADER' OR AV_TAB_TYPE = 'ALL' THEN
        SET AV_TAB_TYPE = null;
    END IF;

    SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND ');

    IF AV_TAB_TYPE IS NOT NULL AND AV_TAB_TYPE <> '' AND AV_TAB_TYPE <> 'ALL_DISCLOSURES' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' (');
        -- REVIEW_PENDING
        IF FIND_IN_SET('REVIEW_PENDING', AV_TAB_TYPE) > 0 THEN
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.REVIEW_STATUS_CODE IN (3,2) ');
        END IF;
        IF FIND_IN_SET('APPROVED', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.DOCUMENT_STATUS_CODE = 2 ');
        END IF;

        IF FIND_IN_SET('MY_REVIEWS_PENDING', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID, ''' AND T1.REVIEW_STATUS_CODE = 3 ');
        END IF;

        IF FIND_IN_SET('WITHOUT_ENGAGEMENTS', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.PERSON_ENTITY_ID IS NULL ');
        END IF;

        IF FIND_IN_SET('HAS_ENGAGEMENTS', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.PERSON_ENTITY_ID IS NOT NULL ');
        END IF;

        IF FIND_IN_SET('FOREIGN_ENGAGEMENTS', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T3.IS_FOREIGN = ''Y'' ');
        END IF;

        IF FIND_IN_SET('FACULTY', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T7.IS_FACULTY = ''Y'' ');
        END IF;

        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ') AND ');
    END IF;
    
    IF AV_DISCLOSURE_PERSON IS NOT NULL AND AV_DISCLOSURE_PERSON <> '' THEN
            IF FIND_IN_SET('PERSON', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
                IF INSTR(AV_DISCLOSURE_PERSON, '*') > 0 THEN
                    SET AV_DISCLOSURE_PERSON = REPLACE(AV_DISCLOSURE_PERSON, '*', '%');
                ELSE
                    SET AV_DISCLOSURE_PERSON = CONCAT('%', AV_DISCLOSURE_PERSON, '%');
                END IF;
                SET LS_FILTER_CONDITION = CONCAT(
                    LS_FILTER_CONDITION,
                    ' (T3.FULL_NAME LIKE ''', AV_DISCLOSURE_PERSON,
                    ''' OR T1.PERSON_ID LIKE ''', AV_DISCLOSURE_PERSON, ''') AND '
                );
            ELSE
                SET LS_FILTER_CONDITION = CONCAT(
                    LS_FILTER_CONDITION,
                    ' T1.PERSON_ID = ''', AV_DISCLOSURE_PERSON, ''' AND '
                );
            END IF;
    END IF;
        
    IF AV_END_DATE IS NOT NULL AND AV_END_DATE <> '' THEN
    
         SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' DATE(T1.EXPIRATION_DATE) = ''', STR_TO_DATE(AV_END_DATE,'%Y-%m-%d'),''' AND ');
      
     END IF;
    
    IF AV_CERTIFICATION_DATE IS NOT NULL AND AV_CERTIFICATION_DATE <> '' THEN
    
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' DATE(T1.CERTIFIED_AT) = ''', STR_TO_DATE(AV_CERTIFICATION_DATE,'%Y-%m-%d'),''' AND ');
      
    END IF;
     
    IF AV_ENTITY IS NOT NULL AND AV_ENTITY <> '' THEN
        IF FIND_IN_SET('ENTITY', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
        IF INSTR(AV_ENTITY, '*') > 0 THEN
            SET AV_ENTITY = REPLACE(AV_ENTITY, '*', '%');
        ELSE
            SET AV_ENTITY = CONCAT('%', AV_ENTITY, '%');
        END IF;
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' (T2.PRIMARY_NAME LIKE ''', AV_ENTITY, 
                ''' OR T1.ENTITY_ID LIKE ''', AV_ENTITY, ''') AND '
            );
        ELSE
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' T1.ENTITY_ID = ''', AV_ENTITY, ''' AND '
            );
        END IF;
    END IF;

    IF AV_HOME_UNIT IS NOT NULL AND AV_HOME_UNIT <> '' AND AV_HOME_UNIT <> 'ALL' AND (AV_INCLUDE_CHILD_UNITS IS NULL OR AV_INCLUDE_CHILD_UNITS = FALSE)THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.HOME_UNIT = ''',AV_HOME_UNIT,''' AND ');
    ELSEIF AV_INCLUDE_CHILD_UNITS = TRUE THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.HOME_UNIT IN (SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN WHERE UNIT_NUMBER =''',AV_HOME_UNIT,''') AND ');
    END IF;
   
    
    IF AV_DOCUMENT_STATUS_CODE IS NOT NULL  AND AV_DOCUMENT_STATUS_CODE <> '' THEN
    
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T10.DOCUMENT_STATUS_CODE IN (',AV_DOCUMENT_STATUS_CODE,') AND ');
    
    END IF;
    
    IF AV_REVIEW_STATUS_CODE IS NOT NULL  AND AV_REVIEW_STATUS_CODE <> '' THEN
    
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.REVIEW_STATUS_CODE IN (',AV_REVIEW_STATUS_CODE,') AND ');
    
    END IF;
    
    IF AV_ADMINISTRATOR IS NOT NULL AND AV_ADMINISTRATOR <> '' THEN
    
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.ADMIN_PERSON_ID IN (''', REPLACE(AV_ADMINISTRATOR, ',', ''','''),''') AND ');
    
    END IF;
    
    IF AV_COUNTRY IS NOT NULL AND AV_COUNTRY <> '' THEN
        IF FIND_IN_SET('COUNTRY', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
            IF INSTR(AV_COUNTRY, '*') > 0 THEN
                SET AV_COUNTRY = REPLACE(AV_COUNTRY, '*', '%');
            ELSE
                SET AV_COUNTRY = CONCAT('%', AV_COUNTRY, '%');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' (T50.TRAVEL_DESTINATIONS LIKE ''', AV_COUNTRY,
                ''' OR T48.COUNTRY_CODES LIKE ''', AV_COUNTRY, ''') AND '
            );
        ELSE
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' FIND_IN_SET(''', AV_COUNTRY, ''', REPLACE(T48.COUNTRY_CODES, '' '', '''')) AND '
            );
        END IF;
    END IF;
    
    IF AV_TRIP_TITLE IS NOT NULL AND AV_TRIP_TITLE <> '' THEN
        IF INSTR(AV_TRIP_TITLE, '*') > 0 THEN
            SET AV_TRIP_TITLE = REPLACE(AV_TRIP_TITLE, '*', '%');
        ELSE
            SET AV_TRIP_TITLE = CONCAT('%', AV_TRIP_TITLE, '%');
        END IF;
    
        SET LS_FILTER_CONDITION = CONCAT(
            LS_FILTER_CONDITION,
            ' T43.VALUE LIKE ''', AV_TRIP_TITLE, ''' AND '
        );
    END IF;
    
    IF AV_TRAVEL_START_DATE IS NOT NULL AND AV_TRAVEL_END_DATE IS NOT NULL THEN
    IF AV_TRAVEL_START_DATE <= AV_TRAVEL_END_DATE THEN
        SET LS_FILTER_CONDITION = CONCAT(
            LS_FILTER_CONDITION,
            ' (T49.MIN_START_DATE <= ''', AV_TRAVEL_END_DATE, ''' AND T49.MAX_END_DATE >= ''', AV_TRAVEL_START_DATE, ''') AND '
        );
    ELSE
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' 1=0 AND ');
    END IF;
    ELSEIF AV_TRAVEL_START_DATE IS NOT NULL THEN
        SET LS_FILTER_CONDITION = CONCAT(
            LS_FILTER_CONDITION,
            ' T49.MAX_END_DATE >= ''', AV_TRAVEL_START_DATE, ''' AND '
            );
    ELSEIF AV_TRAVEL_END_DATE IS NOT NULL THEN
        SET LS_FILTER_CONDITION = CONCAT(
            LS_FILTER_CONDITION,
            ' T49.MIN_START_DATE <= ''', AV_TRAVEL_END_DATE, ''' AND '
            );
    END IF;

    IF AV_TRAVEL_PERSON_ID IS NOT NULL AND AV_TRAVEL_PERSON_ID <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(
            LS_FILTER_CONDITION,
            ' T1.PERSON_ID = ''', AV_TRAVEL_PERSON_ID, ''' AND '
        );
    END IF;
    
    
    IF RIGHT(LS_FILTER_CONDITION, 5) = ' AND ' THEN
        SET LS_FILTER_CONDITION = LEFT(LS_FILTER_CONDITION, LENGTH(LS_FILTER_CONDITION) - 5);
    END IF;

    RETURN LS_FILTER_CONDITION;
END
//
