DELIMITER //
CREATE PROCEDURE `GET_OPA_DETAILS`(
IN AV_COLUMN_NAMES VARCHAR(4000),
    IN AV_MODULE_ITEM_KEY INT,
    IN AV_SUB_MODULE_ITEM_KEY  INT
)
BEGIN
    DECLARE LS_DYN_SQL LONGTEXT;

    SET LS_DYN_SQL = CONCAT(
        'SELECT ', AV_COLUMN_NAMES, ' FROM(
        SELECT
        T1.OPA_DISCLOSURE_ID AS OPA_DISCLOSURE_ID,
        T1.OPA_DISCLOSURE_NUMBER AS OPA_DISCLOSURE_NUMBER,
        T2.FULL_NAME AS REPORTER_NAME,
        DATE(T1.SUBMISSION_TIMESTAMP) AS CERTIFICATION_DATE,
        DATE(T1.EXPIRATION_DATE) AS EXPIRATION_DATE,
        T3.HR_ORG_UNIT_ID AS HR_ORG_UNIT_NUMBER,
        T4.HR_ORG_UNIT_TITLE AS HR_ORG_UNIT_NAME,
        T2.HOME_UNIT AS PERSON_UNIT_NUMBER,
        T5.UNIT_NAME AS PERSON_UNIT_NAME,
        T6.DESCRIPTION AS DISPOSITION_STATUS,
        T7.FULL_NAME AS PRIMARY_ADMINISTRATOR_NAME
        FROM OPA_DISCLOSURE T1
        LEFT JOIN OPA_PERSON T3 ON T3.PERSON_ID = T1.PERSON_ID
        LEFT JOIN OPA_HR_ORG_UNIT_MAPPING T4 ON T4.HR_ORG_UNIT_ID = T3.HR_ORG_UNIT_ID
        LEFT JOIN PERSON T2 ON T2.PERSON_ID = T1.PERSON_ID
        LEFT JOIN UNIT T5 ON T5.UNIT_NUMBER = T2.HOME_UNIT
        LEFT JOIN OPA_DISPOSITION_STATUS_TYPE T6 ON T6.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE
		LEFT JOIN PERSON T7 ON T7.PERSON_ID = T1.ADMIN_PERSON_ID
        WHERE T1.OPA_DISCLOSURE_ID = ', AV_MODULE_ITEM_KEY, ') T');

    SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STATEMENT;
    DEALLOCATE PREPARE EXECUTABLE_STATEMENT;

END
//
