INSERT INTO  ACCOUNT_TYPE (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Regulars',NOW(),'fibi_admin','Y');
INSERT INTO  ACCOUNT_TYPE (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Draper Fellowship',NOW(),'fibi_admin','Y');
INSERT INTO  ACCOUNT_TYPE (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Core Grant Administration',NOW(),'fibi_admin','Y');
INSERT INTO  ACCOUNT_TYPE (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Gift',NOW(),'fibi_admin','Y');
INSERT INTO  ACCOUNT_TYPE (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Conversion Account',NOW(),'fibi_admin','Y');
INSERT INTO  ACCOUNT_TYPE (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','Off-campus account',NOW(),'fibi_admin','Y');
