INSERT INTO ADERP_PROJECT_STATUS_MAPPING  (MAPPING_ID,API_PROJECT_STATUS_CODE,API_PROJECT_STATUS,STATUS_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'APPROVED','APPROVED','1',NOW(),'fibi_admin');
INSERT INTO ADERP_PROJECT_STATUS_MAPPING  (MAPPING_ID,API_PROJECT_STATUS_CODE,API_PROJECT_STATUS,STATUS_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'CLOSED','CLOSED','5',NOW(),'fibi_admin');
