INSERT INTO AGREEMENT_LINK_MODULE  (MODULE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER,SORT_ORDER) VALUES ('1','Award','Y',NOW(),'fibi_admin',NULL);
INSERT INTO AGREEMENT_LINK_MODULE  (MODULE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER,SORT_ORDER) VALUES ('13','Agreement','Y',NOW(),'fibi_admin',NULL);
INSERT INTO AGREEMENT_LINK_MODULE  (MODULE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER,SORT_ORDER) VALUES ('2','Institutional Proposal','Y',NOW(),'fibi_admin',NULL);
INSERT INTO AGREEMENT_LINK_MODULE  (MODULE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER,SORT_ORDER) VALUES ('3','Development Proposal','Y',NOW(),'fibi_admin',NULL);
