INSERT INTO  AGREEMENT_SPONSOR_CONTCT_TYPE  (SPONSOR_CONTCT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Primary',NOW(),'fibi_admin','Y');
INSERT INTO  AGREEMENT_SPONSOR_CONTCT_TYPE  (SPONSOR_CONTCT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Technical',NOW(),'fibi_admin','Y');
INSERT INTO  AGREEMENT_SPONSOR_CONTCT_TYPE  (SPONSOR_CONTCT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Legal',NOW(),'fibi_admin','Y');
INSERT INTO  AGREEMENT_SPONSOR_CONTCT_TYPE  (SPONSOR_CONTCT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Other',NOW(),'fibi_admin','Y');
