INSERT INTO  AGREEMENT_ATTACHMENT_STATUS (AGRMNT_ATTACH_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('C','Complete',NOW(),'fibi_admin','Y');
INSERT INTO  AGREEMENT_ATTACHMENT_STATUS (AGRMNT_ATTACH_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('I','Draft',NOW(),'fibi_admin','Y');
