INSERT INTO  AGREEMENT_SECTION_TYPE  (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('100','OVERVIEW',NOW(),'fibi_admin');
INSERT INTO  AGREEMENT_SECTION_TYPE  (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('101','PEOPLE',NOW(),'fibi_admin');
INSERT INTO  AGREEMENT_SECTION_TYPE  (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('102','THIRD_PARTY',NOW(),'fibi_admin');
INSERT INTO  AGREEMENT_SECTION_TYPE  (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('103','QUESTIONNAIRE',NOW(),'fibi_admin');
INSERT INTO  AGREEMENT_SECTION_TYPE  (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('104','CLAUSES',NOW(),'fibi_admin');
