INSERT INTO AGREEMENT_SPONSOR_TYPE (AGREEMENT_SPONSOR_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Primary','Y',NOW(),'fibi_admin');
INSERT INTO AGREEMENT_SPONSOR_TYPE (AGREEMENT_SPONSOR_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Other','Y',NOW(),'fibi_admin');
