INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','TEMPORARY EMPLOYEE','1.00',NOW(),'fibi_admin','Y');
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','SUMMER EMPLOYEE','3.00',NOW(),'fibi_admin','Y');
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','9M DURATION','9.00',NOW(),'fibi_admin','Y');
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','10M DURATION','10.00',NOW(),'fibi_admin','Y');
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','11M DURATION','11.00',NOW(),'fibi_admin','Y');
INSERT INTO APPOINTMENT_TYPE (APPOINTMENT_TYPE_CODE,DESCRIPTION,DURATION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','12M DURATION','12.00',NOW(),'fibi_admin','Y');
