INSERT INTO audit_log_config VALUES ('BIRT_REPORT','Y','Birt Report')
,('BUSINESS_RULE','Y','Business Rules')
,('CODE_TABLE','Y','Code Table')
,('CUSTOM_ELEMENT','Y','Custom Element')
,('MAP_MAINTENANCE','Y','Map Maintenance')
,('NOTIFICATION','Y','Notification')
,('PERSON','Y','Person')
,('QUESTIONNAIRE','Y','Questionnaire')
,('ROLE_MAINTENANCE','Y','Role Maintenance')
,('ROLODEX','Y','Rolodex')
,('SPONSOR','Y','Sponsor')
,('UNIT_HIERARCHY','Y','Unit Hierarchy');