INSERT INTO AWARD_DOCUMENT_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','ACTIVE',NOW(),'fibi_admin');
INSERT INTO AWARD_DOCUMENT_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','ARCHIVE',NOW(),'fibi_admin');
INSERT INTO AWARD_DOCUMENT_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','CANCELLED',NOW(),'fibi_admin');
INSERT INTO AWARD_DOCUMENT_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','PENDING',NOW(),'fibi_admin');
