INSERT INTO AWARD_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('1','Active',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('11','Withdrawn',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('12','Inactive',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('13','Terminated',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('14','Expired',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('3','Pending',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('5','Closed',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('6','Hold',NOW(),'fibi_admin','Y');
