INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Grant',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_TYPE (AWARD_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Contract',NOW(),'fibi_admin','Y');
