INSERT INTO AWARD_BASIS_OF_PAYMENT  (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Firm fixed price',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_BASIS_OF_PAYMENT  (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Cost reimbursement',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_BASIS_OF_PAYMENT  (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Fixed price level of effort',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_BASIS_OF_PAYMENT  (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Other',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_BASIS_OF_PAYMENT  (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Gift',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_BASIS_OF_PAYMENT  (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','No Payment',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_BASIS_OF_PAYMENT  (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('7','Advance',NOW(),'fibi_admin','Y');


