INSERT INTO AWARD_RESEARCH_TYPE (RESRCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Area of Research',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_RESEARCH_TYPE (RESRCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Societal Challenge Area',NOW(),'fibi_admin','Y');
