INSERT INTO AWARD_CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Unit Contact',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Sponsor Contact',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_CONTACT_TYPE (CONTACT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Person Contact',NOW(),'fibi_admin','Y');
