INSERT INTO AWARD_TRANSACTION_STATUS (TRANSACTION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('A','ACTIVE','Y',NOW(),'fibi_admin');
INSERT INTO AWARD_TRANSACTION_STATUS (TRANSACTION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('P','PENDING','Y',NOW(),'fibi_admin');
INSERT INTO AWARD_TRANSACTION_STATUS (TRANSACTION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('V','VOID','Y',NOW(),'fibi_admin');
