INSERT INTO AWARD_BUDGET_STATUS (AWARD_BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','In Progress',NOW(),'fibi_admin');
INSERT INTO AWARD_BUDGET_STATUS (AWARD_BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('10','Active',NOW(),'fibi_admin');
INSERT INTO AWARD_BUDGET_STATUS (AWARD_BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('11','Error in Posting',NOW(),'fibi_admin');
INSERT INTO AWARD_BUDGET_STATUS (AWARD_BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('12','To be Posted',NOW(),'fibi_admin');
INSERT INTO AWARD_BUDGET_STATUS (AWARD_BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Submitted',NOW(),'fibi_admin');
INSERT INTO AWARD_BUDGET_STATUS (AWARD_BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('8','Rejected',NOW(),'fibi_admin');
INSERT INTO AWARD_BUDGET_STATUS (AWARD_BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('9','Posted',NOW(),'fibi_admin');
