INSERT INTO AWARD_ASSOCIATION_TYPE (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Award',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_ASSOCIATION_TYPE (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Proposal',NOW(),'fibi_admin','Y');
INSERT INTO AWARD_ASSOCIATION_TYPE (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','External',NOW(),'fibi_admin','Y');
