INSERT INTO AWARD_DOCUMENT_TYPE (AWARD_DOCUMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('0','MASTER_AWARD',NOW(),'fibi_admin');
INSERT INTO AWARD_DOCUMENT_TYPE (AWARD_DOCUMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','AWARD_SETUP',NOW(),'fibi_admin');
INSERT INTO AWARD_DOCUMENT_TYPE (AWARD_DOCUMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','AWARD_MODIFICATION',NOW(),'fibi_admin');
INSERT INTO AWARD_DOCUMENT_TYPE (AWARD_DOCUMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','AWARD_VARIATION',NOW(),'fibi_admin');
