INSERT INTO AWARD_WORKFLOW_STATUS (WORKFLOW_AWARD_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Draft',NOW(),'fibi_admin');
INSERT INTO AWARD_WORKFLOW_STATUS (WORKFLOW_AWARD_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Approval In Progress',NOW(),'fibi_admin');
INSERT INTO AWARD_WORKFLOW_STATUS (WORKFLOW_AWARD_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Active',NOW(),'fibi_admin');
INSERT INTO AWARD_WORKFLOW_STATUS (WORKFLOW_AWARD_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Revision Requested',NOW(),'fibi_admin');
INSERT INTO AWARD_WORKFLOW_STATUS (WORKFLOW_AWARD_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Hold For Funding Agency Review',NOW(),'fibi_admin');
INSERT INTO AWARD_WORKFLOW_STATUS (WORKFLOW_AWARD_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('6','Hold For SAP Response',NOW(),'fibi_admin');
INSERT INTO AWARD_WORKFLOW_STATUS (WORKFLOW_AWARD_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('7','Withdrawn',NOW(),'fibi_admin');
