INSERT INTO BIRT_DOWNLOAD_OPTION  (ID,TYPE_CODE,DOWNLOAD_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'101','E',NOW(),'fibi_admin');
INSERT INTO BIRT_DOWNLOAD_OPTION  (ID,TYPE_CODE,DOWNLOAD_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'102','P',NOW(),'fibi_admin');
INSERT INTO BIRT_DOWNLOAD_OPTION  (ID,TYPE_CODE,DOWNLOAD_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'96','P',NOW(),'fibi_admin');
