INSERT INTO BUDGET_TYPE  (BUDGET_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','New',NOW(),'fibi_admin');
INSERT INTO BUDGET_TYPE  (BUDGET_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Rebudget',NOW(),'fibi_admin');
