INSERT INTO BUDGET_STATUS  (BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','In Progress',NOW(),'fibi_admin','Y');
INSERT INTO BUDGET_STATUS  (BUDGET_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Complete',NOW(),'fibi_admin','Y');
