INSERT INTO CLAIM_ATTACHMENT_TYPE (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES ('1','Budget Template',NOW(),'fibi_admin','Y','N');
INSERT INTO CLAIM_ATTACHMENT_TYPE (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES ('2','Other document',NOW(),'fibi_admin','Y','N');
INSERT INTO CLAIM_ATTACHMENT_TYPE (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES ('3','Signed Document',NOW(),'fibi_admin','Y','N');
