INSERT INTO COI_DISPOSITION_STATUS_TYPE  (DISPOSITION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Pending','Y',NOW(),'fibi_admin');
INSERT INTO COI_DISPOSITION_STATUS_TYPE  (DISPOSITION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Void','Y',NOW(),'fibi_admin');
INSERT INTO COI_DISPOSITION_STATUS_TYPE  (DISPOSITION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Approved','Y',NOW(),'fibi_admin');
