INSERT INTO COI_DISCLOSURE_FCOI_TYPE  (FCOI_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','FCOI','Y',NOW(),'fibi_admin');
INSERT INTO COI_DISCLOSURE_FCOI_TYPE  (FCOI_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Proposal','Y',NOW(),'fibi_admin');
INSERT INTO COI_DISCLOSURE_FCOI_TYPE  (FCOI_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Award','Y',NOW(),'fibi_admin');
INSERT INTO COI_DISCLOSURE_FCOI_TYPE  (FCOI_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Revision','Y',NOW(),'fibi_admin');
