INSERT INTO COI_TRAVELER_TYPE  (TRAVELER_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Self','Y',NOW(),'fibi_admin');
INSERT INTO COI_TRAVELER_TYPE  (TRAVELER_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Spouse/Domestic Partner','Y',NOW(),'fibi_admin');
INSERT INTO COI_TRAVELER_TYPE  (TRAVELER_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Dependent Children','Y',NOW(),'fibi_admin');
