INSERT INTO COI_DISCLOSURE_TYPE  (DISCLOSURE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Financial Conflict of Interest','Y',NOW(),'fibi_admin');
INSERT INTO COI_DISCLOSURE_TYPE  (DISCLOSURE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Other Professional Activities','N',NOW(),'fibi_admin');
INSERT INTO COI_DISCLOSURE_TYPE  (DISCLOSURE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Project Disclosures','Y',NOW(),'fibi_admin');
INSERT INTO COI_DISCLOSURE_TYPE  (DISCLOSURE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Travel Disclosures','N',NOW(),'fibi_admin');
