INSERT INTO COI_REVIEW_ACTIVITY  (COI_REVIEW_ACTIVITY_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Comment',NOW(),'fibi_admin','Y');
INSERT INTO COI_REVIEW_ACTIVITY  (COI_REVIEW_ACTIVITY_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Create',NOW(),'fibi_admin','Y');
INSERT INTO COI_REVIEW_ACTIVITY  (COI_REVIEW_ACTIVITY_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Start',NOW(),'fibi_admin','Y');
INSERT INTO COI_REVIEW_ACTIVITY  (COI_REVIEW_ACTIVITY_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Complete',NOW(),'fibi_admin','Y');
