INSERT INTO COI_PROJECT_TYPE  (COI_PROJECT_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Award','Y',NOW(),'fibi_admin');
INSERT INTO COI_PROJECT_TYPE  (COI_PROJECT_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Development Proposal','Y',NOW(),'fibi_admin');
