INSERT INTO COI_PROJ_CONFLICT_STATUS_TYPE  (PROJECT_CONFLICT_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','No Conflict','Y',NOW(),'fibi_admin');
INSERT INTO COI_PROJ_CONFLICT_STATUS_TYPE  (PROJECT_CONFLICT_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Potential Conflict','Y',NOW(),'fibi_admin');
INSERT INTO COI_PROJ_CONFLICT_STATUS_TYPE  (PROJECT_CONFLICT_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Conflict Identified','Y',NOW(),'fibi_admin');
