INSERT INTO COI_SECTIONS_TYPE  (COI_SECTIONS_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Questionnaire',NOW(),'fibi_admin','Y');
INSERT INTO COI_SECTIONS_TYPE  (COI_SECTIONS_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','SFIs',NOW(),'fibi_admin','Y');
INSERT INTO COI_SECTIONS_TYPE  (COI_SECTIONS_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Project relationships',NOW(),'fibi_admin','Y');
INSERT INTO COI_SECTIONS_TYPE  (COI_SECTIONS_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Certification',NOW(),'fibi_admin','Y');
