INSERT INTO COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,MODULE_CODE) VALUES ('1','General',NOW(),'fibi_admin','N',3);
INSERT INTO COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,MODULE_CODE) VALUES ('2','Application Comments',NOW(),'fibi_admin','N',3);
INSERT INTO COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,MODULE_CODE) VALUES ('3','Main Panel Reviewer Comment',NOW(),'fibi_admin','Y',3);
INSERT INTO COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,MODULE_CODE) VALUES ('4','Withdraw Variation Comment',NOW(),'fibi_admin','Y',1);
INSERT INTO COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,MODULE_CODE) VALUES ('5','General',NOW(),'fibi_admin','Y',2);
INSERT INTO COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,MODULE_CODE) VALUES ('6','Application Comments',NOW(),'fibi_admin','Y',2);
INSERT INTO COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,MODULE_CODE) VALUES ('7','Action Comment',NOW(),'fibi_admin','N',3);
