INSERT INTO DISTRIBUTION  (OSP_DISTRIBUTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('1','Report',NOW(),'fibi_admin','Y');
INSERT INTO DISTRIBUTION  (OSP_DISTRIBUTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('2','Report + Letter',NOW(),'fibi_admin','Y');
INSERT INTO DISTRIBUTION  (OSP_DISTRIBUTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('3','Letter Only',NOW(),'fibi_admin','Y');
INSERT INTO DISTRIBUTION  (OSP_DISTRIBUTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('4','Sponsor Form',NOW(),'fibi_admin','Y');
