INSERT INTO DOCUMENT_STATUS  (DOCUMENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'DRAFT',NOW(),'fibi_admin');
INSERT INTO DOCUMENT_STATUS  (DOCUMENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'ARCHIVED',NOW(),'fibi_admin');
INSERT INTO DOCUMENT_STATUS  (DOCUMENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'DELETED',NOW(),'fibi_admin');
