INSERT INTO ENTITY_RISK_CATEGORY  (RISK_CATEGORY_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','High','Y',NOW(),'fibi_admin');
INSERT INTO ENTITY_RISK_CATEGORY  (RISK_CATEGORY_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Medium','Y',NOW(),'fibi_admin');
INSERT INTO ENTITY_RISK_CATEGORY  (RISK_CATEGORY_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Low','Y',NOW(),'fibi_admin');
