INSERT INTO ENTITY_TYPE  (ENTITY_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Publicly Owned','Y',NOW(),'fibi_admin');
INSERT INTO ENTITY_TYPE  (ENTITY_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Private','Y',NOW(),'fibi_admin');
INSERT INTO ENTITY_TYPE  (ENTITY_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Non-Profit','Y',NOW(),'fibi_admin');
INSERT INTO ENTITY_TYPE  (ENTITY_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','For-Profit','Y',NOW(),'fibi_admin');
