INSERT INTO EPS_PROPOSAL_KEY_PERSONNEL_ATTACH_TYPE  (ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES (1,'CV',NOW(),'fibi_admin','Y','N');
INSERT INTO EPS_PROPOSAL_KEY_PERSONNEL_ATTACH_TYPE  (ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES (2,'Biosketch',NOW(),'fibi_admin','Y','N');
INSERT INTO EPS_PROPOSAL_KEY_PERSONNEL_ATTACH_TYPE  (ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES (3,'Current and Pending',NOW(),'fibi_admin','Y','N');
INSERT INTO EPS_PROPOSAL_KEY_PERSONNEL_ATTACH_TYPE  (ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES (4,'Other',NOW(),'fibi_admin','Y','N');
INSERT INTO EPS_PROPOSAL_KEY_PERSONNEL_ATTACH_TYPE  (ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES (5,'Collaborators and Other Affiliations',NOW(),'fibi_admin','Y','N');
