INSERT INTO EPS_PROPOSAL_RESRCH_TYPE  (RESRCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (1,'Research Area',NOW(),'fibi_admin','Y');
INSERT INTO EPS_PROPOSAL_RESRCH_TYPE  (RESRCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (2,'Societal Challenge Areas',NOW(),'fibi_admin','Y');
