INSERT INTO EPS_PROPOSAL_DOCUMENT_STATUS  (DOCUMENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Active',NOW(),'fibi_admin');
INSERT INTO EPS_PROPOSAL_DOCUMENT_STATUS  (DOCUMENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Admin Correction',NOW(),'fibi_admin');
INSERT INTO EPS_PROPOSAL_DOCUMENT_STATUS  (DOCUMENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Archive',NOW(),'fibi_admin');
