INSERT INTO EXCELLENCE_AREA  (EXCELLENCE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Analytics for Business, Consumer and Social Insights',NOW(),'fibi_admin');
INSERT INTO EXCELLENCE_AREA  (EXCELLENCE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Finance & Financial Markets',NOW(),'fibi_admin');
INSERT INTO EXCELLENCE_AREA  (EXCELLENCE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'Innovation and Entrepreneurship',NOW(),'fibi_admin');
INSERT INTO EXCELLENCE_AREA  (EXCELLENCE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (4,'Urban Management & Sustainability',NOW(),'fibi_admin');
INSERT INTO EXCELLENCE_AREA  (EXCELLENCE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (5,'Ageing & Healthcare Management',NOW(),'fibi_admin');
