INSERT INTO EXT_REVIEWER_CIRA  (CIRA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Higher',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_CIRA  (CIRA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Lower',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_CIRA  (CIRA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Even',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_CIRA  (CIRA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Varied',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_CIRA  (CIRA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','N/A',NOW(),'fibi_admin');
