INSERT INTO EXT_REVIEWER_ORIGINALITY  (ORGINALITY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Exceptional',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_ORIGINALITY  (ORGINALITY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Good',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_ORIGINALITY  (ORGINALITY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Average',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_ORIGINALITY  (ORGINALITY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Poor',NOW(),'fibi_admin');
