INSERT INTO EXT_REVIEW_REVIEWERS_STATUS  (EXT_REVIEW_REVIEWERS_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Awaiting Response','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEW_REVIEWERS_STATUS  (EXT_REVIEW_REVIEWERS_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Still In Progress','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEW_REVIEWERS_STATUS  (EXT_REVIEW_REVIEWERS_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'Finalized','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEW_REVIEWERS_STATUS  (EXT_REVIEW_REVIEWERS_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (4,'Rejected','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEW_REVIEWERS_STATUS  (EXT_REVIEW_REVIEWERS_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (5,'Reserved','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEW_REVIEWERS_STATUS  (EXT_REVIEW_REVIEWERS_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (6,'Unassigned','Y',NOW(),'fibi_admin');
