INSERT INTO EXT_REVIEWER_ATTACHMENT_TYPE  (ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Biography',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_ATTACHMENT_TYPE  (ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Agreement',NOW(),'fibi_admin');
