INSERT INTO EXT_REVIEW_COMMENT_TYPE  (EXT_REVIEW_COMMENT_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Requester comment','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEW_COMMENT_TYPE  (EXT_REVIEW_COMMENT_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Reviewer comment','Y',NOW(),'fibi_admin');
