INSERT INTO EXT_REV_REVIEWER_FLOW_STATUS  (EXT_REV_REVIEWER_FLOW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Pending','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REV_REVIEWER_FLOW_STATUS  (EXT_REV_REVIEWER_FLOW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','In Progress','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REV_REVIEWER_FLOW_STATUS  (EXT_REV_REVIEWER_FLOW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Returned','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REV_REVIEWER_FLOW_STATUS  (EXT_REV_REVIEWER_FLOW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Responded','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REV_REVIEWER_FLOW_STATUS  (EXT_REV_REVIEWER_FLOW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Completed','Y',NOW(),'fibi_admin');
