INSERT INTO EXT_REVIEWERS_STATUS  (EXT_REVIEWERS_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Active','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWERS_STATUS  (EXT_REVIEWERS_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'InActive','Y',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWERS_STATUS  (EXT_REVIEWERS_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'OnHold','Y',NOW(),'fibi_admin');
