INSERT INTO EXT_REVIEW_SERVICE_TYPE  (EXT_REVIEW_SERVICE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_SCORING_NEEDED) VALUES (1,'Main-Proposal',NOW(),'fibi_admin','Y','Y');
INSERT INTO EXT_REVIEW_SERVICE_TYPE  (EXT_REVIEW_SERVICE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_SCORING_NEEDED) VALUES (2,'Pre-Proposal',NOW(),'fibi_admin','Y','N');
