INSERT INTO EXT_REVIEWER_ACADEMIC_RANK  (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Full Prof.',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_ACADEMIC_RANK  (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Assoc. Prof.',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_ACADEMIC_RANK  (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Asst. Prof.',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_ACADEMIC_RANK  (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Postdoc',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_ACADEMIC_RANK  (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Res. Sci.',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEWER_ACADEMIC_RANK  (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('6','Cent/Inst Dir.',NOW(),'fibi_admin');
