INSERT INTO EXT_REVIEW_ATTACHMENT_TYPE  (ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Review Document',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEW_ATTACHMENT_TYPE  (ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Supporting Documents',NOW(),'fibi_admin');
INSERT INTO EXT_REVIEW_ATTACHMENT_TYPE  (ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'Other Documents',NOW(),'fibi_admin');
