INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Mathematics',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('10','Mechanical engineering',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('11','Chemical engineering',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('12','Materials engineering',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('13','Medical engineering',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('14','Environmental engineering',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('15','Environmental biotechnology',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('16','Industrial Biotechnology',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('17','Nano-technology',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('18','Other engineering and technologies',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('19','Basic medicine',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Computer and information sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('20','Clinical medicine',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('21','Health sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('22','Health biotechnology',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('23','Other medical sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('24','Agriculture, forestry, and fisheries',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('25','Animal and dairy science',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('26','Veterinary science',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('27','Agricultural biotechnology',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('28','Other agricultural sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('29','Psychology',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Physical sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('30','Economics and business',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('31','Educational sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('32','Sociology',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('33','Law',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('34','Political Science',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('35','Social and economic geography',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('36','Media and communications',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('37','Other social sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('38','History and archaeology',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('39','Languages and literature',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Chemical sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('40','Philosophy, ethics and religion',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('41','Art (arts, history of arts, performing arts,music)',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('42','Other humanities',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Earth and related environmental sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('6','Biological sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('7','Other natural sciences',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('8','Civil engineering',NOW(),'fibi_admin');
INSERT INTO ext_reviewer_academic_area  (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('9','Electrical engineering, electronic \n\nengineering, information engineering',NOW(),'fibi_admin');
