INSERT INTO FAQ_SUB_CATEGORY  (SUB_CATEGORY_CODE,CATEGORY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,11,'Map',NOW(),'fibi_admin');
INSERT INTO FAQ_SUB_CATEGORY  (SUB_CATEGORY_CODE,CATEGORY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,11,'Unit',NOW(),'fibi_admin');
INSERT INTO FAQ_SUB_CATEGORY  (SUB_CATEGORY_CODE,CATEGORY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,11,'Business rule etc',NOW(),'fibi_admin');
INSERT INTO FAQ_SUB_CATEGORY  (SUB_CATEGORY_CODE,CATEGORY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (4,10,'Ontime',NOW(),'fibi_admin');
