INSERT INTO FIBI_WORKFLOW_ROLE_TYPE  (ROLE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Grant Manager',NOW(),'fibi_admin');
INSERT INTO FIBI_WORKFLOW_ROLE_TYPE  (ROLE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Grant Administarator',NOW(),'fibi_admin');
INSERT INTO FIBI_WORKFLOW_ROLE_TYPE  (ROLE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'Grant Reviewer',NOW(),'fibi_admin');
INSERT INTO FIBI_WORKFLOW_ROLE_TYPE  (ROLE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (4,'Grant Investigator',NOW(),'fibi_admin');
