INSERT INTO FILE_TYPE  (FILE_TYPE_CODE,EXTENSION,FILE_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','pdf, doc, docx, csv, xml, ppt, pptx, txt, xls, xlsx, zip, json, xlsm, msg','General',NOW(),'fibi_admin');
INSERT INTO FILE_TYPE  (FILE_TYPE_CODE,EXTENSION,FILE_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','pdf, doc, docx,xlsx,zip','CV',NOW(),'fibi_admin');
INSERT INTO FILE_TYPE  (FILE_TYPE_CODE,EXTENSION,FILE_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','xls,xlsx','Excel',NOW(),'fibi_admin');
INSERT INTO FILE_TYPE  (FILE_TYPE_CODE,EXTENSION,FILE_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','doc,docx','Word',NOW(),'fibi_admin');
INSERT INTO FILE_TYPE  (FILE_TYPE_CODE,EXTENSION,FILE_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','pdf, doc, docx,xls,xlsx,csv','Correspondence Template',NOW(),'fibi_admin');
