INSERT INTO FUNDING_SOURCE_TYPE  (FUNDING_SOURCE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,FUNDING_SOURCE_TYPE_FLAG,SPONSOR_CODE) VALUES ('1','Sponsor',NOW(),'fibi_admin','Y',NULL);
INSERT INTO FUNDING_SOURCE_TYPE  (FUNDING_SOURCE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,FUNDING_SOURCE_TYPE_FLAG,SPONSOR_CODE) VALUES ('2','Unit',NOW(),'fibi_admin','Y',NULL);
INSERT INTO FUNDING_SOURCE_TYPE  (FUNDING_SOURCE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,FUNDING_SOURCE_TYPE_FLAG,SPONSOR_CODE) VALUES ('3','Other',NOW(),'fibi_admin','Y',NULL);
INSERT INTO FUNDING_SOURCE_TYPE  (FUNDING_SOURCE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,FUNDING_SOURCE_TYPE_FLAG,SPONSOR_CODE) VALUES ('4','Development Proposal',NOW(),'fibi_admin','Y',NULL);
INSERT INTO FUNDING_SOURCE_TYPE  (FUNDING_SOURCE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,FUNDING_SOURCE_TYPE_FLAG,SPONSOR_CODE) VALUES ('5','Institutional Proposal',NOW(),'fibi_admin','Y',NULL);
INSERT INTO FUNDING_SOURCE_TYPE  (FUNDING_SOURCE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,FUNDING_SOURCE_TYPE_FLAG,SPONSOR_CODE) VALUES ('6','Award',NOW(),'fibi_admin','Y',NULL);
