INSERT INTO GRANT_CALL_ATTACH_TYPE  (GRANT_ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (1,'Funding Agency Guidelines',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_ATTACH_TYPE  (GRANT_ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (2,'Administrative Guidelines',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_ATTACH_TYPE  (GRANT_ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (3,'Application Form For External Grants',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_ATTACH_TYPE  (GRANT_ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (4,'Application Form For Internal Grants',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_ATTACH_TYPE  (GRANT_ATTACHMNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (5,'Application Form For Others Grants',NOW(),'fibi_admin','Y');
