INSERT INTO GRANT_CALL_CATEGORY  (GRANT_CALL_CATEGORY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Internal',NOW(),'fibi_admin');
INSERT INTO GRANT_CALL_CATEGORY  (GRANT_CALL_CATEGORY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'External',NOW(),'fibi_admin');
INSERT INTO GRANT_CALL_CATEGORY  (GRANT_CALL_CATEGORY_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'Others',NOW(),'fibi_admin');
