INSERT INTO GRANT_CALL_RESEARCH_TYPE  (RESEARCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (1,'Research Area',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_RESEARCH_TYPE  (RESEARCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (2,'Societal Challenge Area',NOW(),'fibi_admin','Y');
