INSERT INTO GRANT_CALL_STATUS  (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (1,'Draft',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_STATUS  (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (2,'Open',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_STATUS  (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (3,'Closed',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_STATUS  (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (4,'Tentative',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_STATUS  (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (5,'Archived',NOW(),'fibi_admin','Y');
INSERT INTO GRANT_CALL_STATUS  (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (6,'Not to Publish',NOW(),'fibi_admin','Y');
