INSERT INTO GRANTCALL_ACTION_TYPE  (ACTION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Created',NOW(),'fibi_admin');
INSERT INTO GRANTCALL_ACTION_TYPE  (ACTION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Published',NOW(),'fibi_admin');
INSERT INTO GRANTCALL_ACTION_TYPE  (ACTION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Updated',NOW(),'fibi_admin');
INSERT INTO GRANTCALL_ACTION_TYPE  (ACTION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Modified',NOW(),'fibi_admin');
