INSERT INTO GRANT_CALL_CRITERIA  (GRANT_CRITERIA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Faculty Category',NOW(),'fibi_admin');
INSERT INTO GRANT_CALL_CRITERIA  (GRANT_CRITERIA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Faculty Track',NOW(),'fibi_admin');
INSERT INTO GRANT_CALL_CRITERIA  (GRANT_CRITERIA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'Rank of Faculty',NOW(),'fibi_admin');
INSERT INTO GRANT_CALL_CRITERIA  (GRANT_CRITERIA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (4,'School',NOW(),'fibi_admin');
