INSERT INTO KPI_TECHNOLOGY_DISCLOSURE_STATUS (TECHNOLOGY_DISCLOSURE_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Filed',NOW(),'fibi_admin','Y');
INSERT INTO KPI_TECHNOLOGY_DISCLOSURE_STATUS (TECHNOLOGY_DISCLOSURE_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Awarded',NOW(),'fibi_admin','Y');
