INSERT INTO KPI_PUBLICATION_STATUS (PUBLICATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Published',NOW(),'fibi_admin','Y');
INSERT INTO KPI_PUBLICATION_STATUS (PUBLICATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','In Press',NOW(),'fibi_admin','Y');
INSERT INTO KPI_PUBLICATION_STATUS (PUBLICATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Accepted or Submitted',NOW(),'fibi_admin','Y');
