INSERT INTO MANPOWER_INTERFACE_STATUS  (INTERFACE_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('1','Success','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_INTERFACE_STATUS  (INTERFACE_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('2','Error','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_INTERFACE_STATUS  (INTERFACE_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('3','Pending','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_INTERFACE_STATUS  (INTERFACE_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('4','Feed not needed','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_INTERFACE_STATUS  (INTERFACE_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('5','Retriggered','Y','fibi_admin',NOW());
