INSERT INTO MANPOWER_RESOURCE_TYPE  (RESOURCE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('1','Student','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_RESOURCE_TYPE  (RESOURCE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('2','New Employee','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_RESOURCE_TYPE  (RESOURCE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('3','Current Employee','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_RESOURCE_TYPE  (RESOURCE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('4','Visiting Professor','Y','fibi_admin',NOW());
