INSERT INTO MANPOWER_TYPE  (MANPOWER_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('1','Staff','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_TYPE  (MANPOWER_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('2','Student','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_TYPE  (MANPOWER_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('3','Others','Y','fibi_admin',NOW());
