INSERT INTO MANPOWER_COMPENSATION_TYPE  (COMPENSATION_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('1','M1','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_COMPENSATION_TYPE  (COMPENSATION_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('2','M2','Y','fibi_admin',NOW());
INSERT INTO MANPOWER_COMPENSATION_TYPE  (COMPENSATION_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('3','M3','Y','fibi_admin',NOW());
