INSERT INTO NARRATIVE_STATUS  (NARRATIVE_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('C','Final',NOW(),'fibi_admin','Y');
INSERT INTO NARRATIVE_STATUS  (NARRATIVE_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('I','Draft',NOW(),'fibi_admin','Y');
