INSERT INTO NEGOTIATION_AGREEMENT_TYPE  (AGREEMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Research Agreement',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_AGREEMENT_TYPE  (AGREEMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Research Agreement Amendment',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_AGREEMENT_TYPE  (AGREEMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','No-Cost Extension',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_AGREEMENT_TYPE  (AGREEMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Non-Disclosure Agreement',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_AGREEMENT_TYPE  (AGREEMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Material Transfer Agreement',NOW(),'fibi_admin','Y');
