INSERT INTO NEGOTIATION_ASSOCIATION_TYPE  (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Award',NOW(),'fibi_admin');
INSERT INTO NEGOTIATION_ASSOCIATION_TYPE  (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Institute Proposal',NOW(),'fibi_admin');
INSERT INTO NEGOTIATION_ASSOCIATION_TYPE  (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','None',NOW(),'fibi_admin');
INSERT INTO NEGOTIATION_ASSOCIATION_TYPE  (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Agreement',NOW(),'fibi_admin');
