INSERT INTO NEGOTIATION_ACTIVITY_TYPE  (ACTIVITY_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Email',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_ACTIVITY_TYPE  (ACTIVITY_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('10','Comment',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_ACTIVITY_TYPE  (ACTIVITY_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Meeting',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_ACTIVITY_TYPE  (ACTIVITY_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Telephone Call',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_ACTIVITY_TYPE  (ACTIVITY_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Executable Document Sent',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_ACTIVITY_TYPE  (ACTIVITY_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Executable Document Received',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_ACTIVITY_TYPE  (ACTIVITY_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','Filed - Returned to CA',NOW(),'fibi_admin','Y');
