INSERT INTO NEGOTIATION_STATUS  (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','In Progress',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_STATUS  (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Waiting for response',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_STATUS  (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Suspended',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_STATUS  (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Complete',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_STATUS  (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Approval in Progress',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_STATUS  (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','Approved',NOW(),'fibi_admin','Y');
