INSERT INTO NEGOTIATION_LOCATION_TYPE  (LOCATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','ORS',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_LOCATION_TYPE  (LOCATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Legal',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_LOCATION_TYPE  (LOCATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','TMI',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_LOCATION_TYPE  (LOCATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','3rd Party',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_LOCATION_TYPE  (LOCATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Other',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_LOCATION_TYPE  (LOCATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','HOD',NOW(),'fibi_admin','Y');
