INSERT INTO ORCID_WORK_CATEGORY  (ORCID_WORK_CATEGORY_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Publications','Y',NOW(),'fibi_admin');
INSERT INTO ORCID_WORK_CATEGORY  (ORCID_WORK_CATEGORY_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Conference','Y',NOW(),'fibi_admin');
INSERT INTO ORCID_WORK_CATEGORY  (ORCID_WORK_CATEGORY_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Intellectual Property','Y',NOW(),'fibi_admin');
INSERT INTO ORCID_WORK_CATEGORY  (ORCID_WORK_CATEGORY_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Others','Y',NOW(),'fibi_admin');
