INSERT INTO ORCID_WORK_STATUS  (ORCID_WORK_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('A','Active','Y',NOW(),'fibi_admin');
INSERT INTO ORCID_WORK_STATUS  (ORCID_WORK_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('V','Void (ORCID Update)','Y',NOW(),'fibi_admin');
