INSERT INTO ORCID_WEBHOOK_ACTION_TYPES  (WEBHOOK_ACTION_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('C','Connect','fibi_admin',NOW());
INSERT INTO ORCID_WEBHOOK_ACTION_TYPES  (WEBHOOK_ACTION_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('D','Disconnect','fibi_admin',NOW());
INSERT INTO ORCID_WEBHOOK_ACTION_TYPES  (WEBHOOK_ACTION_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('S','Sync','fibi_admin',NOW());
