INSERT INTO ORGANIZATION_TYPE  (ORGANIZATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_DEFAULT_ENTRY_REQUIRED) VALUES ('1','Proposal Organization',NOW(),'fibi_admin','Y','N');
INSERT INTO ORGANIZATION_TYPE  (ORGANIZATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_DEFAULT_ENTRY_REQUIRED) VALUES ('2','Performing Organization',NOW(),'fibi_admin','Y','N');
INSERT INTO ORGANIZATION_TYPE  (ORGANIZATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_DEFAULT_ENTRY_REQUIRED) VALUES ('3','Performance Site',NOW(),'fibi_admin','Y','N');
INSERT INTO ORGANIZATION_TYPE  (ORGANIZATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_DEFAULT_ENTRY_REQUIRED) VALUES ('4','Other Organization',NOW(),'fibi_admin','Y','N');
