INSERT INTO PRE_REVIEW_TYPE  (PRE_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Pre Routing Review',NOW(),'fibi_admin','Y');
INSERT INTO PRE_REVIEW_TYPE  (PRE_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Clarification',NOW(),'fibi_admin','Y');
INSERT INTO PRE_REVIEW_TYPE  (PRE_REVIEW_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Award',NOW(),'fibi_admin','Y');
