INSERT INTO PROGRESS_REPORT_STATUS  (PROGRESS_REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','In Progress',NOW(),'fibi_admin','Y');
INSERT INTO PROGRESS_REPORT_STATUS  (PROGRESS_REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Revision Requested',NOW(),'fibi_admin','Y');
INSERT INTO PROGRESS_REPORT_STATUS  (PROGRESS_REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Approval in Progress',NOW(),'fibi_admin','Y');
INSERT INTO PROGRESS_REPORT_STATUS  (PROGRESS_REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Approved',NOW(),'fibi_admin','Y');
INSERT INTO PROGRESS_REPORT_STATUS  (PROGRESS_REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Hold for Funding Agency Review',NOW(),'fibi_admin','Y');
INSERT INTO PROGRESS_REPORT_STATUS  (PROGRESS_REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('7','Cancelled',NOW(),'fibi_admin','Y');
