INSERT INTO PROPOSAL_FUNDING_STATUS  (FUNDING_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Funded',NOW(),'fibi_admin');
INSERT INTO PROPOSAL_FUNDING_STATUS  (FUNDING_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Pending',NOW(),'fibi_admin');
