INSERT INTO PROPOSAL_ACTION_ITEM  (ACTION_ITEM_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Status Changed to',NOW(),'fibi_admin');
INSERT INTO PROPOSAL_ACTION_ITEM  (ACTION_ITEM_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Modified Institute Proposal',NOW(),'fibi_admin');
INSERT INTO PROPOSAL_ACTION_ITEM  (ACTION_ITEM_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Submitted Institute Proposal',NOW(),'fibi_admin');
INSERT INTO PROPOSAL_ACTION_ITEM  (ACTION_ITEM_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Dev Proposal Merged to Institute Proposal',NOW(),'fibi_admin');
