INSERT INTO QUEST_GROUP_TYPE  (QUEST_GROUP_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('G1','Group 1',NOW(),'fibi_admin');
INSERT INTO QUEST_GROUP_TYPE  (QUEST_GROUP_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('G2','Group 2',NOW(),'fibi_admin');
INSERT INTO QUEST_GROUP_TYPE  (QUEST_GROUP_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('G3','Group 3',NOW(),'fibi_admin');
