INSERT INTO RELEVANT_FIELD  (RELEVANT_FIELD_CODE,DESCRIPTION,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Management',NULL,NOW(),'fibi_admin','Y');
INSERT INTO RELEVANT_FIELD  (RELEVANT_FIELD_CODE,DESCRIPTION,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Social Sciences','000001',NOW(),'fibi_admin','N');
INSERT INTO RELEVANT_FIELD  (RELEVANT_FIELD_CODE,DESCRIPTION,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Economics',NULL,NOW(),'fibi_admin','Y');
INSERT INTO RELEVANT_FIELD  (RELEVANT_FIELD_CODE,DESCRIPTION,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Information Systems',NULL,NOW(),'fibi_admin','Y');
INSERT INTO RELEVANT_FIELD  (RELEVANT_FIELD_CODE,DESCRIPTION,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Accountancy',NULL,NOW(),'fibi_admin','Y');
INSERT INTO RELEVANT_FIELD  (RELEVANT_FIELD_CODE,DESCRIPTION,UNIT_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','Law','000001',NOW(),'fibi_admin','N');
