INSERT INTO REPORT_STATUS  (REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Pending',NOW(),'fibi_admin');
INSERT INTO REPORT_STATUS  (REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Received',NOW(),'fibi_admin');
INSERT INTO REPORT_STATUS  (REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Not Required',NOW(),'fibi_admin');
INSERT INTO REPORT_STATUS  (REPORT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Due',NOW(),'fibi_admin');
