INSERT INTO research_type  (RESRCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('1','Area of Research',NOW(),'fibi_admin','Y');
INSERT INTO research_type  (RESRCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,ACTIVE_FLAG) VALUES ('2','Societal Challenge Area',NOW(),'fibi_admin','Y');
