INSERT INTO rights_type  (RIGHTS_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','System',NOW(),'fibi_admin');
INSERT INTO rights_type  (RIGHTS_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Department',NOW(),'fibi_admin');
