INSERT INTO ROLE_TYPE  (ROLE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','System',NOW(),'fibi_admin','Y');
INSERT INTO ROLE_TYPE  (ROLE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Unit',NOW(),'fibi_admin','Y');
