INSERT INTO SAP_FEED_TYPE  (FEED_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('C','Change','Y','fibi_admin',NOW());
INSERT INTO SAP_FEED_TYPE  (FEED_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('N','New','Y','fibi_admin',NOW());
