INSERT INTO SAP_FEED_STATUS  (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('CH','Hold',NOW(),'fibi_admin','Y');
INSERT INTO SAP_FEED_STATUS  (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('CX','Cancelled',NOW(),'fibi_admin','Y');
INSERT INTO SAP_FEED_STATUS  (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('E','Error',NOW(),'fibi_admin','Y');
INSERT INTO SAP_FEED_STATUS  (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('F','Feed',NOW(),'fibi_admin','Y');
INSERT INTO SAP_FEED_STATUS  (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('H','Hold',NOW(),'fibi_admin','Y');
INSERT INTO SAP_FEED_STATUS  (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('N','Not To Feed',NOW(),'fibi_admin','Y');
INSERT INTO SAP_FEED_STATUS  (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('P','Pending',NOW(),'fibi_admin','Y');
INSERT INTO SAP_FEED_STATUS  (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('R','Success',NOW(),'fibi_admin','Y');
INSERT INTO SAP_FEED_STATUS  (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('X','Cancelled',NOW(),'fibi_admin','Y');
