INSERT INTO SP_REV_APPROVAL_TYPE  (APPROVAL_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Pending',NOW(),'fibi_admin','Y');
INSERT INTO SP_REV_APPROVAL_TYPE  (APPROVAL_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Approved',NOW(),'fibi_admin','Y');
INSERT INTO SP_REV_APPROVAL_TYPE  (APPROVAL_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Not yet applied',NOW(),'fibi_admin','Y');
INSERT INTO SP_REV_APPROVAL_TYPE  (APPROVAL_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Exempt',NOW(),'fibi_admin','Y');
INSERT INTO SP_REV_APPROVAL_TYPE  (APPROVAL_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Link to IRB',NOW(),'fibi_admin','Y');
INSERT INTO SP_REV_APPROVAL_TYPE  (APPROVAL_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','Link to IACUC',NOW(),'fibi_admin','Y');
INSERT INTO SP_REV_APPROVAL_TYPE  (APPROVAL_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('7','Not Applicable',NOW(),'fibi_admin','Y');
