INSERT INTO SPECIAL_REVIEW  (SPECIAL_REVIEW_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,SORT_ID,IS_ACTIVE,IS_INTEGRATED) VALUES ('1','Human Subjects',NOW(),'fibi_admin',4,'Y',NULL);
INSERT INTO SPECIAL_REVIEW  (SPECIAL_REVIEW_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,SORT_ID,IS_ACTIVE,IS_INTEGRATED) VALUES ('2','Animal Usage',NOW(),'fibi_admin',1,'Y',NULL);
INSERT INTO SPECIAL_REVIEW  (SPECIAL_REVIEW_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,SORT_ID,IS_ACTIVE,IS_INTEGRATED) VALUES ('5','Biohazard Materials',NOW(),'fibi_admin',2,'Y',NULL);
