INSERT INTO SPONSOR_TERM_TYPE  (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Equipment Approval Terms',NOW(),'fibi_admin','Y');
INSERT INTO SPONSOR_TERM_TYPE  (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Invention Terms',NOW(),'fibi_admin','Y');
INSERT INTO SPONSOR_TERM_TYPE  (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Prior Approval Terms',NOW(),'fibi_admin','Y');
INSERT INTO SPONSOR_TERM_TYPE  (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Property Terms',NOW(),'fibi_admin','Y');
INSERT INTO SPONSOR_TERM_TYPE  (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Publication',NOW(),'fibi_admin','Y');
INSERT INTO SPONSOR_TERM_TYPE  (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','Referenced Document Terms',NOW(),'fibi_admin','Y');
INSERT INTO SPONSOR_TERM_TYPE  (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('7','Rights In Data Terms',NOW(),'fibi_admin','Y');
INSERT INTO SPONSOR_TERM_TYPE  (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('8','Subaward Approval Terms',NOW(),'fibi_admin','Y');
INSERT INTO SPONSOR_TERM_TYPE  (SPONSOR_TERM_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('9','Travel Restrictions Terms',NOW(),'fibi_admin','Y');
