INSERT INTO SPONSOR_ROLE  (SPONSOR_ROLE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Sponsor','Y',NOW(),'fibi_admin');
INSERT INTO SPONSOR_ROLE  (SPONSOR_ROLE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Academic Collabrator','Y',NOW(),'fibi_admin');
INSERT INTO SPONSOR_ROLE  (SPONSOR_ROLE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Data Provider','Y',NOW(),'fibi_admin');
INSERT INTO SPONSOR_ROLE  (SPONSOR_ROLE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Material Provider','Y',NOW(),'fibi_admin');
INSERT INTO SPONSOR_ROLE  (SPONSOR_ROLE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Prime Sponsor','Y',NOW(),'fibi_admin');
INSERT INTO SPONSOR_ROLE  (SPONSOR_ROLE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('6','Subcontractor','Y',NOW(),'fibi_admin');
