INSERT INTO SR_STATUS  (STATUS_CODE,DESCRIPTION,ACTION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Draft',NULL,NOW(),'fibi_admin');
INSERT INTO SR_STATUS  (STATUS_CODE,DESCRIPTION,ACTION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Approval In Progress',NULL,NOW(),'fibi_admin');
INSERT INTO SR_STATUS  (STATUS_CODE,DESCRIPTION,ACTION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'Returned',NULL,NOW(),'fibi_admin');
INSERT INTO SR_STATUS  (STATUS_CODE,DESCRIPTION,ACTION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (4,'Submitted',NULL,NOW(),'fibi_admin');
INSERT INTO SR_STATUS  (STATUS_CODE,DESCRIPTION,ACTION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (5,'Resolved',NULL,NOW(),'fibi_admin');
INSERT INTO SR_STATUS  (STATUS_CODE,DESCRIPTION,ACTION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (6,'Reopen',NULL,NOW(),'fibi_admin');
INSERT INTO SR_STATUS  (STATUS_CODE,DESCRIPTION,ACTION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (7,'Reject',NULL,NOW(),'fibi_admin');
INSERT INTO SR_STATUS  (STATUS_CODE,DESCRIPTION,ACTION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (10,'Withdrawn',NULL,NOW(),'fibi_admin');
INSERT INTO SR_STATUS  (STATUS_CODE,DESCRIPTION,ACTION_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (11,'Cancelled',NULL,NOW(),'fibi_admin');
