INSERT INTO SR_TYPE  (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,INSTRUCTION,SUBJECT,ACTIVE_FLAG,sort_order,module_code,ADMIN_GROUP_ID,HELP_TEXT,STATUS_CODE) VALUES ('1','Project Duration - Extend/Reduce',NOW(),'fibi_admin','Project Duration - Extend/Reduce','Project Duration - Extend/Reduce','Y',1,1,NULL,NULL,NULL);
INSERT INTO SR_TYPE  (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,INSTRUCTION,SUBJECT,ACTIVE_FLAG,sort_order,module_code,ADMIN_GROUP_ID,HELP_TEXT,STATUS_CODE) VALUES ('19','Virement of funds',NOW(),'fibi_admin','Please provide sufficient details required for the requests. Sequence = Reduce then increase.  Initial base salary should be the highest amount that can be paid for incoming for the position.','Virement of Funds','Y',18,1,NULL,NULL,NULL);
INSERT INTO SR_TYPE  (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,INSTRUCTION,SUBJECT,ACTIVE_FLAG,sort_order,module_code,ADMIN_GROUP_ID,HELP_TEXT,STATUS_CODE) VALUES ('21','Submit Closure request',NOW(),'fibi_admin','Submit Closure request','Submit Closure request','Y',21,1,NULL,NULL,NULL);
INSERT INTO SR_TYPE  (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,INSTRUCTION,SUBJECT,ACTIVE_FLAG,sort_order,module_code,ADMIN_GROUP_ID,HELP_TEXT,STATUS_CODE) VALUES ('24','Manpower Admin Correction',NOW(),'fibi_admin','Manpower Admin Correction','Manpower Admin Correction','Y',24,1,NULL,NULL,NULL);
INSERT INTO SR_TYPE  (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,INSTRUCTION,SUBJECT,ACTIVE_FLAG,sort_order,module_code,ADMIN_GROUP_ID,HELP_TEXT,STATUS_CODE) VALUES ('25','Administrative Correction',NOW(),'fibi_admin','Administrative Correction','Administrative Correction','Y',22,1,NULL,NULL,NULL);
INSERT INTO SR_TYPE  (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,INSTRUCTION,SUBJECT,ACTIVE_FLAG,sort_order,module_code,ADMIN_GROUP_ID,HELP_TEXT,STATUS_CODE) VALUES ('3','Change of Research Team',NOW(),'fibi_admin',NULL,NULL,'Y',NULL,1,NULL,NULL,NULL);
INSERT INTO SR_TYPE  (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,INSTRUCTION,SUBJECT,ACTIVE_FLAG,sort_order,module_code,ADMIN_GROUP_ID,HELP_TEXT,STATUS_CODE) VALUES ('4','Change in Total Budgets(Reduce/increase)',NOW(),'fibi_admin','Change in Total Budgets(Reduce/increase)','Change in Total Budgets(Reduce/increase)','Y',5,1,NULL,NULL,NULL);
INSERT INTO SR_TYPE  (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,INSTRUCTION,SUBJECT,ACTIVE_FLAG,sort_order,module_code,ADMIN_GROUP_ID,HELP_TEXT,STATUS_CODE) VALUES ('6','Admin Correction',NOW(),'fibi_admin',NULL,NULL,'Y',NULL,1,NULL,NULL,NULL);
INSERT INTO SR_TYPE  (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,INSTRUCTION,SUBJECT,ACTIVE_FLAG,sort_order,module_code,ADMIN_GROUP_ID,HELP_TEXT,STATUS_CODE) VALUES ('7','Project Closure',NOW(),'fibi_admin',NULL,NULL,'Y',NULL,1,NULL,NULL,NULL);
