INSERT INTO TASK_MODULE_MAPPING  (MODULE_CODE,SUB_MODULE_CODE,TASK_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,2,'1',NOW(),'fibi_admin');
INSERT INTO TASK_MODULE_MAPPING  (MODULE_CODE,SUB_MODULE_CODE,TASK_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,2,'2',NOW(),'fibi_admin');
INSERT INTO TASK_MODULE_MAPPING  (MODULE_CODE,SUB_MODULE_CODE,TASK_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,2,'3',NOW(),'fibi_admin');
INSERT INTO TASK_MODULE_MAPPING  (MODULE_CODE,SUB_MODULE_CODE,TASK_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,2,'4',NOW(),'fibi_admin');
INSERT INTO TASK_MODULE_MAPPING  (MODULE_CODE,SUB_MODULE_CODE,TASK_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,2,'5',NOW(),'fibi_admin');
INSERT INTO TASK_MODULE_MAPPING  (MODULE_CODE,SUB_MODULE_CODE,TASK_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,2,'6',NOW(),'fibi_admin');
INSERT INTO TASK_MODULE_MAPPING  (MODULE_CODE,SUB_MODULE_CODE,TASK_TYPE_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,2,'7',NOW(),'fibi_admin');
