INSERT INTO UNIT_TYPE  (UNIT_TYPE_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Subdivision',NOW(),'fibi_admin','Y');
INSERT INTO UNIT_TYPE  (UNIT_TYPE_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Center/Institute',NOW(),'fibi_admin','Y');
INSERT INTO UNIT_TYPE  (UNIT_TYPE_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','External',NOW(),'fibi_admin','Y');
INSERT INTO UNIT_TYPE  (UNIT_TYPE_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','College/School',NOW(),'fibi_admin','Y');
INSERT INTO UNIT_TYPE  (UNIT_TYPE_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Admin Department',NOW(),'fibi_admin','Y');
INSERT INTO UNIT_TYPE  (UNIT_TYPE_ID,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','University Joint Research Entity',NOW(),'fibi_admin','Y');
