INSERT INTO VALID_REPORT_CLASS  (REPORT_CLASS_ID,REPORT_CLASS_CODE,REPORT_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'1','1',NOW(),'fibi_admin');
INSERT INTO VALID_REPORT_CLASS  (REPORT_CLASS_ID,REPORT_CLASS_CODE,REPORT_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'1','10',NOW(),'fibi_admin');
INSERT INTO VALID_REPORT_CLASS  (REPORT_CLASS_ID,REPORT_CLASS_CODE,REPORT_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'1','11',NOW(),'fibi_admin');
INSERT INTO VALID_REPORT_CLASS  (REPORT_CLASS_ID,REPORT_CLASS_CODE,REPORT_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (4,'3','12',NOW(),'fibi_admin');
INSERT INTO VALID_REPORT_CLASS  (REPORT_CLASS_ID,REPORT_CLASS_CODE,REPORT_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (5,'3','13',NOW(),'fibi_admin');
INSERT INTO VALID_REPORT_CLASS  (REPORT_CLASS_ID,REPORT_CLASS_CODE,REPORT_CODE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (6,'3','11',NOW(),'fibi_admin');
