INSERT INTO WORKFLOW_MAP_TYPE  (MAP_TYPE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,IS_ACTIVE) VALUES ('E','Evaluation','fibi_admin',NOW(),'Y');
INSERT INTO WORKFLOW_MAP_TYPE  (MAP_TYPE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,IS_ACTIVE) VALUES ('R','Routing','fibi_admin',NOW(),'Y');
