DELIMITER //
CREATE PROCEDURE `MARK_DISCLOSURES_AS_EXPIRED`()
BEGIN
DECLARE LS_OPA_LOG_DESCRIPTION VARCHAR(200);
DECLARE LS_COI_LOG_DESCRIPTION VARCHAR(200);

    -- GET OPA LOG DESCRIPTION
    SELECT MESSAGE INTO LS_OPA_LOG_DESCRIPTION 
    FROM OPA_ACTION_LOG_TYPE 
    WHERE ACTION_TYPE_CODE = 22;

    -- GET COI LOG DESCRIPTION 
    SELECT MESSAGE INTO LS_COI_LOG_DESCRIPTION 
    FROM DISCLOSURE_ACTION_TYPE 
    WHERE ACTION_TYPE_CODE = 12;

    -- DISABLE SAFE UPDATES TEMPORARILY
    SET SQL_SAFE_UPDATES = 0;
    START TRANSACTION;

    -- DROP TEMP TABLE IF EXISTS
    DROP TEMPORARY TABLE IF EXISTS TEMP_EXPIRED_DISCLOSURES_TO_NOTIFY;

	 -- CREATE TEMP TABLE TO STORE COMBINED DISCLOSURES
    CREATE TEMPORARY TABLE TEMP_EXPIRED_DISCLOSURES_TO_NOTIFY (
        DISCLOSURE_ID INT,
        DISCLOSURE_NUMBER VARCHAR(100),
        PERSON_ID VARCHAR(40),
        DISCLOSURE_TYPE VARCHAR(50),
        IS_LEGACY_DISCLOSURE VARCHAR(1) DEFAULT 'N',
        EXPIRATION_DATE DATE,
        CERTIFICATION_DATE DATE,
        VERSION_STATUS VARCHAR(45),
        REPORTER_NAME VARCHAR(90),
        DEPARTMENT_NUMBER VARCHAR(8),
        DEPARTMENT_NAME VARCHAR(200),
        DISPOSITION_STATUS VARCHAR(20)
    );

    -- INSERT EXPIRED OPA DISCLOSURES
    INSERT INTO TEMP_EXPIRED_DISCLOSURES_TO_NOTIFY (DISCLOSURE_ID, DISCLOSURE_NUMBER, PERSON_ID, DISCLOSURE_TYPE, EXPIRATION_DATE, VERSION_STATUS, CERTIFICATION_DATE, DISPOSITION_STATUS, REPORTER_NAME, DEPARTMENT_NUMBER, DEPARTMENT_NAME)
    SELECT 
        D.OPA_DISCLOSURE_ID,        
        D.OPA_DISCLOSURE_NUMBER,
        D.PERSON_ID,
        'OPA',
        D.EXPIRATION_DATE,
        D.VERSION_STATUS,
        D.SUBMISSION_TIMESTAMP AS CERTIFICATION_TIMESTAMP,
        ODST.DESCRIPTION AS DISPOSITION_STATUS,
        P.FULL_NAME AS REPORTER_NAME,
        U.UNIT_NUMBER AS DEPARTMENT_NUMBER,
        U.UNIT_NAME AS DEPARTMENT_NAME
    FROM OPA_DISCLOSURE D
    LEFT JOIN PERSON P ON P.PERSON_ID = D.PERSON_ID
    LEFT JOIN UNIT U ON P.HOME_UNIT = U.UNIT_NUMBER
    LEFT JOIN OPA_DISPOSITION_STATUS_TYPE ODST ON ODST.DISPOSITION_STATUS_CODE = D.DISPOSITION_STATUS_CODE
    WHERE D.OPA_DISCLOSURE_ID = (
        SELECT MAX(OPA_DISCLOSURE_ID)
        FROM OPA_DISCLOSURE D2
        WHERE D2.OPA_DISCLOSURE_NUMBER = D.OPA_DISCLOSURE_NUMBER
    )
    AND D.OPA_DISCLOSURE_NUMBER IN (
        SELECT DISTINCT OPA_DISCLOSURE_NUMBER
        FROM OPA_DISCLOSURE
        WHERE DISPOSITION_STATUS_CODE = '3'
          AND VERSION_STATUS = 'ACTIVE'
          AND EXPIRATION_DATE < DATE(UTC_TIMESTAMP())
    )
    AND (
        D.EXPIRATION_DATE < DATE(UTC_TIMESTAMP())
        OR D.REVIEW_STATUS_CODE IN (1, 5, 6)
    )
    AND FN_OPA_DISCLOSURE_REQUIRED(D.person_id) = TRUE;

    -- INSERT EXPIRED COI DISCLOSURES
    INSERT INTO TEMP_EXPIRED_DISCLOSURES_TO_NOTIFY (DISCLOSURE_ID, DISCLOSURE_NUMBER, PERSON_ID,  DISCLOSURE_TYPE, EXPIRATION_DATE, CERTIFICATION_DATE, VERSION_STATUS, DISPOSITION_STATUS, REPORTER_NAME, DEPARTMENT_NUMBER, DEPARTMENT_NAME)
    SELECT 
        CD.DISCLOSURE_ID,
        CD.DISCLOSURE_NUMBER,
        CD.PERSON_ID,
        CASE CD.FCOI_TYPE_CODE
            WHEN '2' THEN 'PROJECT'
            ELSE 'FCOI'
        END,
        CD.EXPIRATION_DATE,
        CD.CERTIFIED_AT,
        CD.VERSION_STATUS,
        CDST.DESCRIPTION AS DISPOSITION_STATUS,
        P.FULL_NAME AS REPORTER_NAME,
        U.UNIT_NUMBER AS DEPARTMENT_NUMBER,
        U.UNIT_NAME AS DEPARTMENT_NAME
    FROM COI_DISCLOSURE CD
    LEFT JOIN PERSON P ON P.PERSON_ID = CD.PERSON_ID
    LEFT JOIN UNIT U ON P.HOME_UNIT = U.UNIT_NUMBER
    LEFT JOIN COI_DISPOSITION_STATUS_TYPE CDST ON CDST.DISPOSITION_STATUS_CODE = CD.DISPOSITION_STATUS_CODE
    WHERE CD.DISCLOSURE_ID = (
        SELECT MAX(DISCLOSURE_ID)
        FROM COI_DISCLOSURE CD2
        WHERE CD2.DISCLOSURE_NUMBER = CD.DISCLOSURE_NUMBER
    )
    AND CD.DISCLOSURE_NUMBER IN (
        SELECT DISTINCT DISCLOSURE_NUMBER
        FROM COI_DISCLOSURE
        WHERE DISPOSITION_STATUS_CODE = '3'
          AND VERSION_STATUS = 'ACTIVE'
          AND EXPIRATION_DATE < DATE(UTC_TIMESTAMP())
    )
    AND (
        CD.EXPIRATION_DATE < DATE(UTC_TIMESTAMP())
        OR CD.REVIEW_STATUS_CODE IN (1, 5, 6)
    ) AND (CD.FCOI_TYPE_CODE = 2 OR (FN_FCOI_DISCLOSURE_REQUIRED(CD.PERSON_ID) = TRUE));

    -- INSERT ACTION LOGS FOR OPA
    INSERT INTO OPA_ACTION_LOG (
        OPA_DISCLOSURE_ID,
        OPA_DISCLOSURE_NUMBER,
        ACTION_TYPE_CODE,
        DESCRIPTION,
        UPDATE_TIMESTAMP
    )
    SELECT 
        D.OPA_DISCLOSURE_ID,
        D.OPA_DISCLOSURE_NUMBER,
        22,
        LS_OPA_LOG_DESCRIPTION,
        UTC_TIMESTAMP()
    FROM OPA_DISCLOSURE D
    WHERE D.DISPOSITION_STATUS_CODE = '3'
      AND D.VERSION_STATUS = 'ACTIVE'
      AND D.EXPIRATION_DATE < DATE(UTC_TIMESTAMP())
      AND FN_OPA_DISCLOSURE_REQUIRED(D.person_id) = TRUE;

    -- INSERT ACTION LOGS FOR COI
    INSERT INTO DISCLOSURE_ACTION_LOG (
        DISCLOSURE_ID,
        DISCLOSURE_NUMBER,
        ACTION_TYPE_CODE,
        DESCRIPTION,
        UPDATE_TIMESTAMP
    )
    SELECT 
        CD.DISCLOSURE_ID,
        CD.DISCLOSURE_NUMBER,
        12,
        REPLACE(
            LS_COI_LOG_DESCRIPTION,
            '{FCOI /Project /Travel}',
            (SELECT DESCRIPTION FROM COI_DISCLOSURE_FCOI_TYPE WHERE FCOI_TYPE_CODE = CD.FCOI_TYPE_CODE)
        ) AS DESCRIPTION,
        UTC_TIMESTAMP()
    FROM COI_DISCLOSURE CD
    WHERE CD.DISPOSITION_STATUS_CODE = '3'
      AND CD.VERSION_STATUS = 'ACTIVE'
      AND CD.EXPIRATION_DATE < DATE(UTC_TIMESTAMP());

    -- UPDATE OPA DISCLOSURES
    UPDATE OPA_DISCLOSURE D
    SET D.DISPOSITION_STATUS_CODE = 4
    WHERE D.DISPOSITION_STATUS_CODE = '3'
      AND D.VERSION_STATUS = 'ACTIVE'
      AND D.EXPIRATION_DATE < DATE(UTC_TIMESTAMP())
      AND FN_OPA_DISCLOSURE_REQUIRED(D.person_id) = TRUE;

    -- UPDATE COI DISCLOSURES
    UPDATE COI_DISCLOSURE CD
    SET CD.DISPOSITION_STATUS_CODE = 4
    WHERE CD.DISPOSITION_STATUS_CODE = '3'
      AND CD.VERSION_STATUS = 'ACTIVE'
      AND CD.EXPIRATION_DATE < DATE(UTC_TIMESTAMP());

    -- MARK EXPIRED FOR LEGACY COI DISCLOSURES
        -- INSERT EXPIRED LEGACY COI DISCLOSURES
        INSERT INTO TEMP_EXPIRED_DISCLOSURES_TO_NOTIFY (DISCLOSURE_ID, DISCLOSURE_NUMBER, PERSON_ID, DISCLOSURE_TYPE, IS_LEGACY_DISCLOSURE, EXPIRATION_DATE, CERTIFICATION_DATE, VERSION_STATUS, REPORTER_NAME, DEPARTMENT_NUMBER, DEPARTMENT_NAME, DISPOSITION_STATUS)
        SELECT
            DISTINCT
            CD.LEGACY_DISCLOSURE_ID,
            CD.COI_DISCLOSURE_NUMBER,
            CD.PERSON_ID,
            'FCOI' AS DISCLOSURE_TYPE,
            'Y' AS IS_LEGACY_DISCLOSURE,
            CD.EXPIRATION_DATE,
            CD.CERTIFICATION_TIMESTAMP,
            'ACTIVE' AS VERSION_STATUS,
			P.FULL_NAME,
			U.UNIT_NUMBER,
			U.UNIT_NAME,
            'Approved' AS DISPOSITION_STATUS
        FROM LEGACY_COI_DISCLOSURE CD
        JOIN LEGACY_COI_DISC_DETAILS CDP
            ON CDP.LEGACY_DISCLOSURE_ID = CD.LEGACY_DISCLOSURE_ID
		LEFT JOIN PERSON P ON P.PERSON_ID = CD.PERSON_ID
		LEFT JOIN UNIT U ON P.HOME_UNIT = U.UNIT_NUMBER
        WHERE CD.DISCLOSURE_DISPOSITION_CODE = 1
        AND CD.DISC_ACTIVE_STATUS = 1
        AND CD.EVENT_TYPE_CODE IN (5, 6)
        AND CD.EXPIRATION_DATE < DATE(UTC_TIMESTAMP())
        AND (
                NOT EXISTS (
                    SELECT 1
                    FROM COI_DISCL_PROJECTS T1
                    JOIN COI_DISCLOSURE T2
                        ON T1.DISCLOSURE_ID = T2.DISCLOSURE_ID
                    AND T2.PERSON_ID = CD.PERSON_ID
                    WHERE T2.REVIEW_STATUS_CODE NOT IN (1, 5, 6)
                    AND T2.VERSION_STATUS = 'ACTIVE'
                )
        )
        AND CD.SEQUENCE_NUMBER = (SELECT MAX(t1.SEQUENCE_NUMBER) from LEGACY_COI_DISCLOSURE t1 WHERE t1.COI_DISCLOSURE_NUMBER = CD.COI_DISCLOSURE_NUMBER)
        AND FN_FCOI_DISCLOSURE_REQUIRED(CD.PERSON_ID) = TRUE;

		-- INSERT ACTION LOGS FOR LEGACY COI
        INSERT INTO DISCLOSURE_ACTION_LOG (
        DISCLOSURE_NUMBER,
        ACTION_TYPE_CODE,
        DESCRIPTION,
        UPDATE_TIMESTAMP
        )
        SELECT
            CD.COI_DISCLOSURE_NUMBER,
            12,
            REPLACE(
                LS_COI_LOG_DESCRIPTION,
                '{FCOI /Project /Travel}',
                (CD.EVENT_TYPE)
            ) AS DESCRIPTION,
            UTC_TIMESTAMP()
        FROM LEGACY_COI_DISCLOSURE CD
        WHERE CD.DISCLOSURE_DISPOSITION_CODE = 1
        AND CD.DISC_ACTIVE_STATUS = 1
        AND CD.EXPIRATION_DATE < DATE(UTC_TIMESTAMP());

		-- UPDATE LEGACY COI DISCLOSURES
        UPDATE LEGACY_COI_DISCLOSURE CD
        SET CD.DISCLOSURE_DISPOSITION_CODE = 5,
            CD.DISCLOSURE_DISPOSITION = 'Expired',
            CD.UPDATE_TIMESTAMP = UTC_TIMESTAMP(),
            CD.UPDATE_USER = 'system'
        WHERE CD.DISCLOSURE_DISPOSITION_CODE = 1
            AND CD.DISC_ACTIVE_STATUS = 1
            AND CD.EXPIRATION_DATE < DATE(UTC_TIMESTAMP());

    COMMIT;

    -- RE-ENABLE SAFE UPDATES
    SET SQL_SAFE_UPDATES = 1;

    -- RETURN FINAL RESULT FROM TEMP TABLE
    SELECT * FROM TEMP_EXPIRED_DISCLOSURES_TO_NOTIFY;
    
        -- DROP TEMP TABLE IF EXISTS
    DROP TEMPORARY TABLE IF EXISTS TEMP_EXPIRED_DISCLOSURES_TO_NOTIFY;
END
//
