SET @unit_collation = (
    SELECT COLLATION_NAME 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'unit' 
    AND COLUMN_NAME = 'UNIT_NUMBER'
    LIMIT 1
);

SET @sql = CONCAT('
CREATE TABLE IF NOT EXISTS disclosure_affiliated_units (
    DISCLOSURE_AFFILIATED_UNIT_ID INT AUTO_INCREMENT,
    DISCLOSURE_ID INT NULL,
    UNIT_NUMBER VARCHAR(8) NOT NULL COLLATE ', @unit_collation, ',
    MODULE_CODE INT NULL,
    UPDATED_BY VARCHAR(60) NULL,
    UPDATE_TIMESTAMP DATETIME NULL,
    PRIMARY KEY (DISCLOSURE_AFFILIATED_UNIT_ID),
    INDEX DISCLOSURE_AFFILIATED_UNITS_IDX (UNIT_NUMBER),
    CONSTRAINT DISCLOSURE_AFFILIATED_UNITS_FK1
        FOREIGN KEY (UNIT_NUMBER) REFERENCES unit (UNIT_NUMBER)
)');

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
