CREATE TABLE coi_discl_person_entity_rel (
  COI_DISCL_PERSON_ENTITY_REL_ID int NOT NULL AUTO_INCREMENT,
  PERSON_ENTITY_ID int DEFAULT NULL,
  PERSON_ENTITY_NUMBER int DEFAULT NULL,
  PREVIOUS_PERSON_ENTITY_ID int DEFAULT NULL,
  ENTITY_ID int DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  DISCLOSURE_ID int DEFAULT NULL,
  PRIMARY KEY (COI_DISCL_PERSON_ENTITY_REL_ID),
  KEY COI_DISCL_PERSON_ENTITY_REL_FK1_idx (PERSON_ENTITY_ID),
  KEY COI_DISCL_PERSON_ENTITY_REL_FK2_idx (ENTITY_ID),
  KEY COI_DISCL_PERSON_ENTITY_REL_FK3 (DISCLOSURE_ID),
  CONSTRAINT COI_DISCL_PERSON_ENTITY_REL_FK1 FOREIGN KEY (PERSON_ENTITY_ID) REFERENCES person_entity (PERSON_ENTITY_ID),
  CONSTRAINT COI_DISCL_PERSON_ENTITY_REL_FK2 FOREIGN KEY (ENTITY_ID) REFERENCES entity (ENTITY_ID),
  CONSTRAINT COI_DISCL_PERSON_ENTITY_REL_FK3 FOREIGN KEY (DISCLOSURE_ID) REFERENCES coi_disclosure (DISCLOSURE_ID)
);
