DELIMITER //
CREATE PROCEDURE `COI_DECLARATION_EXPIRY_REMINDER`(AV_DAYS INT)
BEGIN

    SELECT DISTINCT t1.DECLARATION_ID AS MODULE_ITEM_KEY, 0 AS SUB_MODULE_ITEM_KEY, 28 AS MODULE_CODE, 0 AS SUB_MODULE_CODE
    	FROM COI_DECLARATION t1
        WHERE t1.VERSION_STATUS = 'ACTIVE'
    	AND DATE(EXPIRATION_DATE) = DATE_ADD(UTC_DATE(), INTERVAL AV_DAYS DAY)
        AND t1.DECLARATION_ID = (
            SELECT MAX(DECLARATION_ID)
            FROM COI_DECLARATION CD
            WHERE CD.DECLARATION_NUMBER = t1.DECLARATION_NUMBER
            AND CD.REVIEW_STATUS_CODE NOT IN (1, 5, 4)
        ) AND FN_CHK_CAN_CREATE_DECLARATION(t1.PERSON_ID, t1.DECLARATION_TYPE_CODE) = TRUE;
END
//
