INSERT INTO `business_rule_variable` (`VARIABLE_NAME`, `MODULE_CODE`, `SUB_MODULE_CODE`, `DESCRIPTION`, `TABLE_NAME`, `COLUMN_NAME`, `SHOW_LOOKUP`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `LOOKUP_WINDOW_NAME`) VALUES
 ('Coi Project Type', '8', '0', 'Coi Project Type', 'COI_PROJECT_TYPE', 'COI_PROJECT_TYPE_CODE', 'Y', now(), 'quickstart', 'COI_PROJECT_TYPE_LOOKUP');
 INSERT INTO `lookup_window` (`LOOKUP_WINDOW_NAME`, `DESCRIPTION`, `TABLE_NAME`, `COLUMN_NAME`, `OTHERS_DISPLAY_COLUMNS`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `DATA_TYPE_CODE`) VALUES 
 ('COI_PROJECT_TYPE_LOOKUP', 'Coi Project type drop down', 'COI_PROJECT_TYPE', 'COI_PROJECT_TYPE_CODE', 'DESCRIPTION', now(), 'quickstart', '8');
