ALTER TABLE `OPA_PERSON`
ADD COLUMN `IS_DISCLOSURE_REQUIRED` VARCHAR(1) NULL,
ADD COLUMN `REQUIREMENT_REASON` VARCHAR(225) NULL,
ADD COLUMN `IS_RULE_BASED` VARCHAR(1) NULL,
ADD COLUMN `EXEMPT_FROM_DATE` DATETIME NULL,
ADD COLUMN `EXEMPT_TO_DATE` DATETIME NULL,
ADD COLUMN `EXEMPTION_REASON` VARCHAR(225) NULL,
ADD COLUMN `CREATE_TIMESTAMP` DATETIME NULL,
ADD COLUMN `UPDATE_TIMESTAMP` DATETIME NULL,
ADD COLUMN `HR_ORG_UNIT_ID` VARCHAR(10) NULL;


CREATE TABLE `OPA_DISCL_PERSON_SNAP` (
  `OPA_DISCL_PERSON_SNAP_ID` INT NOT NULL AUTO_INCREMENT,
  `OPA_DISCLOSURE_ID` INT NULL,
  `PERSON_ID` VARCHAR(40) NULL,
  `JOB_TITLE` VARCHAR(50) NULL,
  `ADMIN_EMPLOYEE_TYPE` VARCHAR(40) NULL,
  `ADMIN_ORG_UNIT_TITLE` VARCHAR(50) NULL,
  `ADMIN_POSITION_TITLE` VARCHAR(50) NULL,
  `EMPLOYMENT_PERCENT` DECIMAL(5,2) NULL,
  `IS_CONSULT_PRIV` VARCHAR(1) NULL,
  `IS_PAID_APPT` VARCHAR(1) NULL,
  `IS_SUMMER_SESSION_APPT` VARCHAR(1) NULL,
  `IS_SABBATICAL` VARCHAR(1) NULL,
  `OPA_REQUIREMENT_REASON` VARCHAR(225) NULL,
  `IS_RULE_BASED` VARCHAR(1) NULL,
  `SABBATICAL_BEGIN_DATE` DATETIME NULL,
  `SABBATICAL_END_DATE` DATETIME NULL,
  `CREATE_TIMESTAMP` DATETIME NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `HR_ORG_UNIT_ID` VARCHAR(10) NULL,
  `HR_DEPARTMENT_NAME` VARCHAR(50) NULL,
  PRIMARY KEY (`OPA_DISCL_PERSON_SNAP_ID`),
  INDEX `OPA_DISCL_PERSON_SNAP_IDX1` (`OPA_DISCLOSURE_ID` ASC) VISIBLE,
  INDEX `OPA_DISCL_PERSON_SNAP_IDX2` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `OPA_DISCL_PERSON_SNAP_FK_1`
    FOREIGN KEY (`OPA_DISCLOSURE_ID`)
    REFERENCES `OPA_DISCLOSURE` (`OPA_DISCLOSURE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OPA_DISCL_PERSON_SNAP_FK_2`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
