INSERT IGNORE INTO `mq_router_trigger_configuration` (`TRIGGER_TYPE`, `IS_ACTIVE`, `QUEUE_NAME`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES ('FCOI_ROUTELOG_APPROVE', 'Y', 'Q_NOTIFICATION', 'Notification trigger while routelog approval', now(), 'admin');

INSERT IGNORE INTO `mq_router_trigger_configuration` (`TRIGGER_TYPE`, `IS_ACTIVE`, `QUEUE_NAME`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES ('FCOI_ROUTELOG_BYPASSED', 'Y', 'Q_NOTIFICATION', 'Notification trigger while routelog bypass', now(), 'admin');

INSERT IGNORE INTO `notify_placeholder_header` (`MODULE_CODE`, `SUB_MODULE_CODE`, `QUERY_TYPE`, `ELEMENT_TYPE`, `IS_ACTIVE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `UNIQUE_DISPLAY_NAME`)
VALUES ( '8', '0', 'S', 'S', 'Y', 'Hardcoded Placeholders', now(), 'admin', 'COI_DISCL_ROUTLOG');

INSERT IGNORE INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES ((select max(NOTIFY_PLACEHOLDER_HEADER_ID) from notify_placeholder_header), 'APPROVER_STOP_NAME', 'Approver Stop Name', now(), 'admin');
INSERT IGNORE INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES ((select max(NOTIFY_PLACEHOLDER_HEADER_ID) from notify_placeholder_header), 'WORKFLOW_COMMENT', 'Workflow Comment', now(), 'admin');

INSERT IGNORE INTO notification_type
(NOTIFICATION_TYPE_ID, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, SUBJECT, MESSAGE, PROMPT_USER, IS_ACTIVE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, IS_SYSTEM_SPECIFIC, SHOW_TEMPLATE_IN_MODULE, SENT_TO_INITIATOR)
VALUES(8093, 8, 0, 'Notification to workflow person in sequential stop when FCOI Disclosure is routed for their review.', 'Action required: Approval for COI Annual Disclosure at {COI_DISCL_ROUTLOG#APPROVER_STOP_NAME} stop. ', '<p>Dear Reviewer,</p><p>The following COI Annual Disclosure has been submitted for approval. Please find the details below:</p><p><strong>Submitted by</strong>:  {COI_DISCLOSURE#REPORTER_NAME}</p><p><strong>Department </strong>: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p><strong>Disclosure Status:</strong> {COI_DISCLOSURE#DISPOSITION_STATUS}</p><p>Please go to <a href="{COI_DISCL_URL#DISCLOSURE_URL}"><strong>this link</strong></a> to view the details.</p><p>Thank you.<br> </p><p>Note: This is a system-generated email. Please do not reply to this email.</p>', 'N', 'Y', 'admin', now(), '', NULL, 'Y', NULL, NULL);
INSERT IGNORE INTO notification_type
(NOTIFICATION_TYPE_ID, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, SUBJECT, MESSAGE, PROMPT_USER, IS_ACTIVE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, IS_SYSTEM_SPECIFIC, SHOW_TEMPLATE_IN_MODULE, SENT_TO_INITIATOR)
VALUES(8094, 8, 0, ' Notification to workflow person in sequential stop when Project Disclosure is routed for their review.', 'Action required: Approval for Project Disclosure at {COI_DISCL_ROUTLOG#APPROVER_STOP_NAME} stop.', '<p>Dear Reviewer,</p><p>The following Project Disclosure has been submitted for approval. Please find the details below:</p><p><strong>Project:</strong><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"> {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</span></p><p><strong>Submitted by</strong>: {COI_DISCLOSURE#REPORTER_NAME}</p><p><strong>Department </strong>: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p><strong>Disclosure Status:</strong> {COI_DISCLOSURE#DISPOSITION_STATUS}</p><p>Please go to <a href="{COI_DISCL_URL#DISCLOSURE_URL}"><strong>this link</strong></a> to view the details.</p><p>Thank you.<br> </p><p>Note: This is a system-generated email. Please do not reply to this email.</p>', 'N', 'Y', 'admin', now(), 'admin', now(), 'Y', NULL, NULL);
INSERT IGNORE INTO notification_type
(NOTIFICATION_TYPE_ID, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, SUBJECT, MESSAGE, PROMPT_USER, IS_ACTIVE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, IS_SYSTEM_SPECIFIC, SHOW_TEMPLATE_IN_MODULE, SENT_TO_INITIATOR)
VALUES(8095, 8, 0, 'Notification to workflow person in sequential stop when a FCOI Disclosure has been bypassed.', ' COI Annual Disclosure has been bypassed at {COI_DISCL_ROUTLOG#APPROVER_STOP_NAME} stop.', '<p>Dear Reviewer,</p><p>Your assigned COI Annual Disclosure was bypassed by {COI_DISCL_ROUTLOG#WORKFLOW_ACTION_USER_NAME} for the following reason <strong>“{COI_DISCL_ROUTLOG#WORKFLOW_COMMENT}”</strong>. Therefore, no further action is required from your side. Please find the disclosure details below:</p><p><strong>Submitted by</strong>: {COI_DISCLOSURE#REPORTER_NAME}</p><p><strong>Department </strong>: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p><strong>Disclosure Status:</strong> {COI_DISCLOSURE#DISPOSITION_STATUS}</p><p>Please go to <a href="{COI_DISCL_URL#DISCLOSURE_URL}"><strong>this link</strong></a> to view the details.</p><p>Thank you.<br> </p><p>Note: This is a system-generated email. Please do not reply to this email.</p>', 'N', 'Y', 'admin', now(), 'admin', now(), 'Y', NULL, NULL);
INSERT IGNORE INTO notification_type
(NOTIFICATION_TYPE_ID, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, SUBJECT, MESSAGE, PROMPT_USER, IS_ACTIVE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, IS_SYSTEM_SPECIFIC, SHOW_TEMPLATE_IN_MODULE, SENT_TO_INITIATOR)
VALUES(8096, 8, 0, 'Notification to workflow person in sequential stop when a Project Disclosure has been bypassed.', 'Project Disclosure has been bypassed at {COI_DISCL_ROUTLOG#APPROVER_STOP_NAME} stop.', '<p>Dear Reviewer,</p><p>Your assigned Project Disclosure was bypassed by {COI_DISCL_ROUTLOG#WORKFLOW_ACTION_USER_NAME} for the following reason <strong>“{COI_DISCL_ROUTLOG#WORKFLOW_COMMENT}”</strong>. Therefore, no further action is required from your side. Please find the disclosure details below:</p><p><strong>Project:</strong><span style="background-color:rgb(255,255,255);color:rgb(0,0,0);"> {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</span></p><p><strong>Submitted by</strong>: {COI_DISCLOSURE#REPORTER_NAME}</p><p><strong>Department </strong>: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p><strong>Disclosure Status:</strong> {COI_DISCLOSURE#DISPOSITION_STATUS}</p><p>Please go to <a href="{COI_DISCL_URL#DISCLOSURE_URL}"><strong>this link</strong></a> to view the details.</p><p>Thank you.<br> </p><p>Note: This is a system-generated email. Please do not reply to this email.</p>', 'N', 'Y', 'admin', now(), '', NULL, 'N', NULL, NULL);
