INSERT INTO notify_placeholder_columns (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME)
SELECT * FROM (
    SELECT '2', 'DISPOSITION_STATUS', 'Disposition Status'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM notify_placeholder_columns 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = '2'
      AND QUERY_COLUMN_NAME = 'DISPOSITION_STATUS'
      AND LABEL_NAME = 'Disposition Status'
);

INSERT INTO notify_placeholder_columns (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME)
SELECT * FROM (
    SELECT '2', 'DEPARTMENT_NAME', 'Department Name'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM notify_placeholder_columns 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = '2'
      AND QUERY_COLUMN_NAME = 'DEPARTMENT_NAME'
      AND LABEL_NAME = 'Department Name'
);

INSERT INTO notify_placeholder_columns (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME)
SELECT * FROM (
    SELECT '2', 'DEPARTMENT_NUMBER', 'Department Number'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM notify_placeholder_columns 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = '2'
      AND QUERY_COLUMN_NAME = 'DEPARTMENT_NUMBER'
      AND LABEL_NAME = 'Department Number'
);

INSERT INTO notify_placeholder_columns (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME)
SELECT * FROM (
    SELECT '2', 'REPORTER_NAME', 'Reporter Name'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM notify_placeholder_columns 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = '2'
      AND QUERY_COLUMN_NAME = 'REPORTER_NAME'
      AND LABEL_NAME = 'Reporter Name'
);

INSERT INTO notify_placeholder_columns (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME)
SELECT * FROM (
    SELECT '2', 'EXPIRATION_DATE', 'Expiration Date'
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM notify_placeholder_columns 
    WHERE NOTIFY_PLACEHOLDER_HEADER_ID = '2'
      AND QUERY_COLUMN_NAME = 'EXPIRATION_DATE'
      AND LABEL_NAME = 'Expiration Date'
);

DELETE FROM `NOTIFICATION_RECIPIENT` WHERE `NOTIFICATION_TYPE_ID` = 8004;

INSERT INTO `NOTIFICATION_RECIPIENT` 
(`NOTIFICATION_TYPE_ID`, `RECIPIENT_PERSON_ID`, `ROLE_TYPE_CODE`, `CREATE_USER`, `CREATE_TIMESTAMP`, 
`UPDATE_USER`, `UPDATE_TIMESTAMP`, `RECIPIENT_TYPE`, `RECIPIENT_NAME`)
SELECT * FROM (
    SELECT 
        8004 AS NOTIFICATION_TYPE_ID,
        NULL AS RECIPIENT_PERSON_ID,
        56 AS ROLE_TYPE_CODE,
        'admin' AS CREATE_USER,
        UTC_TIMESTAMP() AS CREATE_TIMESTAMP,
        'admin' AS UPDATE_USER,
        UTC_TIMESTAMP() AS UPDATE_TIMESTAMP,
        'TO' AS RECIPIENT_TYPE,
        'COI Primary Administrator' AS RECIPIENT_NAME
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM `NOTIFICATION_RECIPIENT` 
    WHERE `NOTIFICATION_TYPE_ID` = 8004
      AND `ROLE_TYPE_CODE` = 56
      AND `RECIPIENT_TYPE` = 'TO'
      AND `RECIPIENT_NAME` = 'COI Primary Administrator'
);
