DELIMITER //
CREATE PROCEDURE `GET_COI_AWARD_PROJECT_OVERVIEW`(
AV_AWARD_TITLE		  VARCHAR(1000),
AV_AWARD_NUMBER		  VARCHAR(20),
AV_UNIT            VARCHAR(200),
AV_PERSON    		  VARCHAR(90),
AV_AWARD_STATUS        VARCHAR(200),
AV_REVIEW_STATUS 		  VARCHAR(200),
AV_SPONSOR 					VARCHAR(200),
AV_PRIME_SPONSOR 			VARCHAR(200),
AV_AWARD_START_DATE 		VARCHAR(20),
AV_AWARD_END_DATE 		VARCHAR(20),
AV_PAGED                        INT(10),
AV_LIMIT                        INT(10),
AV_UNLIMITED                    BOOLEAN,
AV_TYPE						 VARCHAR(1),
AV_SORT_TYPE 				VARCHAR(2000),
AV_ACCOUNT_NUMBER 		VARCHAR(20),
AV_PI_PERSON 		VARCHAR(90),
AV_LOGIN_PERSON_ID	VARCHAR(40),
AV_SUBMISSION_STATUS VARCHAR(100),
AV_CA_PERSON VARCHAR(90),
AV_FREE_TEXT_SEARCH_FIELDS      VARCHAR(500)
)
BEGIN
DECLARE LS_FILTER_CONDITION 		LONGTEXT;
DECLARE LS_JOIN_CONDITION			LONGTEXT;
DECLARE LS_PAGINATION_CONDITION 	VARCHAR(60);
DECLARE LS_DYN_SQL					LONGTEXT;
DECLARE LS_DYN_SQL1					LONGTEXT;
DECLARE LI_CA_ADMIN					INT;
DECLARE LI_CAN_VIEW_PRIVATE_COMMENT	INT;

DECLARE LS_OFFSET 					INT(11);
DECLARE LS_ORDER_BY 				LONGTEXT;
DECLARE LS_OFFSET_CONDITION			LONGTEXT;
DECLARE LS_FILTER_CONDITION_1		TEXT DEFAULT '';	
DECLARE LS_REVIEW_STATUS            VARCHAR(200);
DECLARE LI_TRAINING_CODE			VARCHAR(500);
DECLARE LS_CA_UNIT_NUMBER			VARCHAR(8);

SET LI_TRAINING_CODE = '';

SET LS_DYN_SQL ='';
SET LS_FILTER_CONDITION = '';
SET LS_PAGINATION_CONDITION = '';
SET LS_JOIN_CONDITION = '';
SET LS_OFFSET = (AV_LIMIT * AV_PAGED);


 SET LS_DYN_SQL1 ='';
 	
    SET LS_JOIN_CONDITION = CONCAT(LS_JOIN_CONDITION, ' LEFT JOIN PERSON P ON T2.KEY_PERSON_ID = P.PERSON_ID
														LEFT JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T1.SPONSOR_CODE
														LEFT JOIN SPONSOR T4 ON T4.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE	
														INNER JOIN eps_prop_person_role T7 ON T7.PROP_PERSON_ROLE_ID = T2.KEY_PERSON_ROLE_CODE														
														LEFT JOIN UNIT T8 ON T8.UNIT_NUMBER = P.HOME_UNIT													
														INNER JOIN COI_PROJECT_TYPE T10 ON T10.COI_PROJECT_TYPE_CODE = ''1''
                                                        INNER JOIN COI_INT_STAGE_AWARD_STATUS T11 ON T11.STATUS_CODE = T1.PROJECT_STATUS_CODE
                                                         ');

IF AV_TYPE ='A' THEN

    IF AV_AWARD_TITLE IS NOT NULL AND AV_AWARD_TITLE <> '' THEN
		 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T1.TITLE LIKE ''%', AV_AWARD_TITLE, '%'' ');
	END IF;

    IF AV_AWARD_NUMBER IS NOT NULL  AND AV_AWARD_NUMBER <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.PROJECT_NUMBER LIKE ''%',AV_AWARD_NUMBER, '%'' ');
	END IF;
    
		IF AV_UNIT IS NOT NULL AND AV_UNIT <> '' THEN
				IF FIND_IN_SET('UNIT', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
					IF INSTR(AV_UNIT, '*') > 0 THEN
						SET AV_UNIT = REPLACE(AV_UNIT, '*', '%');
					ELSE
						SET AV_UNIT = CONCAT('%', AV_UNIT, '%');
					END IF;
					SET LS_FILTER_CONDITION = CONCAT(
						LS_FILTER_CONDITION,
						' AND (T1.LEAD_UNIT_NAME LIKE ''', AV_UNIT,
						''' OR T1.LEAD_UNIT_NUMBER LIKE ''', AV_UNIT, ''') '
					);
				ELSE
					SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.LEAD_UNIT_NUMBER = ''',AV_UNIT,''' ');
				END IF;
			END IF;

    IF AV_PERSON IS NOT NULL AND AV_PERSON <> '' THEN
        IF FIND_IN_SET('PERSON', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
            IF INSTR(AV_PERSON, '*') > 0 THEN
                SET AV_PERSON = REPLACE(AV_PERSON, '*', '%');
            ELSE
                SET AV_PERSON = CONCAT('%', AV_PERSON, '%');
            END IF;
            
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, 
                ' AND (T2.KEY_PERSON_ID LIKE ''', AV_PERSON, ''' OR T2.KEY_PERSON_NAME LIKE ''', AV_PERSON, ''')');
        ELSE
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, 
                ' AND T2.KEY_PERSON_ID = ''', AV_PERSON, '''');
        END IF;
    END IF;

    IF AV_AWARD_STATUS IS NOT NULL AND AV_AWARD_STATUS <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T11.STATUS_CODE IN (', AV_AWARD_STATUS, ') ');
    END IF;

    IF AV_REVIEW_STATUS IS NOT NULL AND AV_REVIEW_STATUS <> '' THEN
		 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T2.DISCLOSURE_REVIEW_STATUS IN (', 
							'SELECT GROUP_CONCAT((CASE WHEN CR.REVIEW_STATUS_CODE IN  (2,3,4,7,8) THEN ''DISCLOSURE_COMPLETED'' 
									WHEN CR.REVIEW_STATUS_CODE IN  (1,5,6) THEN ''DISCLOSURE_PENDING''				
								   ELSE  CR.DESCRIPTION	
								  END)) 
						FROM COI_REVIEW_STATUS_TYPE CR
						WHERE CR.REVIEW_STATUS_CODE IN (''' ,AV_REVIEW_STATUS,''')', ') ');
    END IF;

    IF AV_SPONSOR IS NOT NULL AND AV_SPONSOR <> '' THEN
            IF FIND_IN_SET('SPONSOR', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
            IF INSTR(AV_SPONSOR, '*') > 0 THEN
                SET AV_SPONSOR = REPLACE(AV_SPONSOR, '*', '%');
            ELSE
                SET AV_SPONSOR = CONCAT('%', AV_SPONSOR, '%');
            END IF;
                SET LS_FILTER_CONDITION = CONCAT(
                    LS_FILTER_CONDITION,
                    ' AND (T1.SPONSOR_NAME LIKE ''', AV_SPONSOR,
                    ''' OR T3.SPONSOR_CODE LIKE ''', AV_SPONSOR, ''') '
                );
            ELSE
               SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T3.SPONSOR_CODE = ''',AV_SPONSOR,''' ');
            END IF;
        END IF;
    
    IF AV_PRIME_SPONSOR IS NOT NULL AND AV_PRIME_SPONSOR <> '' THEN
        IF FIND_IN_SET('PRIME_SPONSOR', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
        IF INSTR(AV_PRIME_SPONSOR, '*') > 0 THEN
            SET AV_PRIME_SPONSOR = REPLACE(AV_PRIME_SPONSOR, '*', '%');
        ELSE
            SET AV_PRIME_SPONSOR = CONCAT('%', AV_PRIME_SPONSOR, '%');
        END IF;
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' AND (T1.PRIME_SPONSOR_NAME LIKE ''', AV_PRIME_SPONSOR,
                ''' OR T4.SPONSOR_CODE LIKE ''', AV_PRIME_SPONSOR, ''') '
            );
        ELSE
           SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T4.SPONSOR_CODE = ''',AV_PRIME_SPONSOR,''' ');
        END IF;
    END IF;

    IF AV_AWARD_START_DATE IS NOT NULL AND AV_AWARD_START_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND DATE(T1.PROJECT_START_DATE) >= DATE_FORMAT(''',AV_AWARD_START_DATE,''',''%Y-%m-%d'') ');
    END IF;

    IF AV_AWARD_END_DATE IS NOT NULL AND AV_AWARD_END_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND DATE(T1.PROJECT_END_DATE) <= DATE_FORMAT(''',AV_AWARD_END_DATE,''',''%Y-%m-%d'') ');
    END IF;
 
	IF AV_ACCOUNT_NUMBER IS NOT NULL AND AV_ACCOUNT_NUMBER <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.ACCOUNT_NUMBER LIKE ''%',AV_ACCOUNT_NUMBER, '%'' ');
    END IF;
	
	IF AV_PI_PERSON IS NOT NULL AND AV_PI_PERSON <> '' THEN
    IF FIND_IN_SET('PRINCIPAL_INVESTIGATOR', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
        IF INSTR(AV_PI_PERSON, '*') > 0 THEN
            SET AV_PI_PERSON = REPLACE(AV_PI_PERSON, '*', '%');
        ELSE
            SET AV_PI_PERSON = CONCAT('%', AV_PI_PERSON, '%');
        END IF;
        
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, 
            ' AND EXISTS (SELECT 1
                          FROM COI_INT_STAGE_AWARD_PERSON CP 
                          WHERE CP.PROJECT_NUMBER = T1.PROJECT_NUMBER
                            AND (CP.KEY_PERSON_ID LIKE ''', AV_PI_PERSON, '''
                                 OR CP.KEY_PERSON_NAME LIKE ''', AV_PI_PERSON, ''')
                            AND CP.KEY_PERSON_ROLE_NAME = ''Principal Investigator''
                            AND CP.STATUS <> ''I'')');
    ELSE
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, 
            ' AND EXISTS (SELECT 1
                          FROM COI_INT_STAGE_AWARD_PERSON CP 
                          WHERE CP.PROJECT_NUMBER = T1.PROJECT_NUMBER
                            AND CP.KEY_PERSON_ID = ''', AV_PI_PERSON, '''
                            AND CP.KEY_PERSON_ROLE_NAME = ''Principal Investigator''
                            AND CP.STATUS <> ''I'')');
    END IF;
END IF;

	IF AV_CA_PERSON IS NOT NULL AND AV_CA_PERSON <> '' THEN
    IF FIND_IN_SET('CONTRACT_ADMINISTRATOR', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
        IF INSTR(AV_CA_PERSON, '*') > 0 THEN
            SET AV_CA_PERSON = REPLACE(AV_CA_PERSON, '*', '%');
        ELSE
            SET AV_CA_PERSON = CONCAT('%', AV_CA_PERSON, '%');
        END IF;
        
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, 
            ' AND EXISTS (SELECT 1
                          FROM COI_INT_STAGE_AWARD CISA 
                          WHERE CISA.PROJECT_NUMBER = T1.PROJECT_NUMBER
                            AND CISA.LEAD_UNIT_NUMBER IN (
                                SELECT DISTINCT ua.UNIT_NUMBER
                                FROM UNIT_ADMINISTRATOR ua
                                INNER JOIN PERSON p ON ua.PERSON_ID = p.PERSON_ID
                                WHERE ua.UNIT_ADMINISTRATOR_TYPE_CODE = 2
                                  AND (p.FULL_NAME LIKE ''', AV_CA_PERSON, '''
                                       OR p.PERSON_ID LIKE ''', AV_CA_PERSON, ''')
                            )
                         )');
    ELSE
         SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
            ' AND EXISTS (SELECT 1
                          FROM COI_INT_STAGE_AWARD CISA 
                          WHERE CISA.PROJECT_NUMBER = T1.PROJECT_NUMBER
                            AND CISA.LEAD_UNIT_NUMBER IN (
                                SELECT DISTINCT UA.UNIT_NUMBER 
                                FROM UNIT_ADMINISTRATOR UA 
                                WHERE UA.PERSON_ID = ''', AV_CA_PERSON, '''
                            )
                         )');
    END IF;
END IF;

    IF AV_SUBMISSION_STATUS IS NOT NULL AND AV_SUBMISSION_STATUS <> '' THEN 
        SET LS_FILTER_CONDITION_1 = CONCAT(' WHERE FIND_IN_SET(T.PROJECT_SUBMISSION_STATUS,''',AV_SUBMISSION_STATUS,''') ');
    END IF;	   
END IF;

IF AV_TYPE <> 'A' THEN
	SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND  (T1.PROJECT_STATUS_CODE = 6)');
END IF;



IF AV_SORT_TYPE IS NOT NULL AND  AV_SORT_TYPE <> '' THEN 
SET LS_ORDER_BY = CONCAT(' ORDER BY T1.PROJECT_SUBMISSION_STATUS IS NULL, T1.PROJECT_REVIEW_STATUS IS NULL,
 ',AV_SORT_TYPE,', T1.UPDATE_TIMESTAMP DESC, T1.PROJECT_ID ASC, T1.SORT_ID ASC');
ELSE 

SET LS_ORDER_BY = ' ORDER BY T1.UPDATE_TIMESTAMP DESC, T1.PROJECT_ID ASC, T1.SORT_ID ASC ';

END IF;

IF AV_UNLIMITED <> TRUE  THEN


IF AV_LIMIT IS NOT NULL AND LS_OFFSET IS NOT NULL THEN
    SET LS_OFFSET_CONDITION =CONCAT(' WHERE T.ROWNUMBER BETWEEN ', (SELECT CASE WHEN LS_OFFSET = 0 THEN LS_OFFSET ELSE LS_OFFSET+1 END), ' AND ', ( LS_OFFSET + AV_LIMIT));
END IF;

ELSE 
SET LS_OFFSET_CONDITION = '';
END IF;

SELECT COUNT(1) INTO LI_CA_ADMIN
FROM PERSON_ROLES PR
JOIN ROLE_RIGHTS RR ON PR.ROLE_ID = RR.ROLE_ID
JOIN RIGHTS RT ON RR.RIGHT_ID = RT.RIGHT_ID
WHERE PR.PERSON_ID = AV_LOGIN_PERSON_ID AND RT.RIGHT_NAME = 'CONTRACT_ADMINISTRATOR';

SELECT COUNT(1) INTO LI_CAN_VIEW_PRIVATE_COMMENT
FROM PERSON_ROLES PR
JOIN ROLE_RIGHTS RR ON PR.ROLE_ID = RR.ROLE_ID
JOIN RIGHTS RT ON RR.RIGHT_ID = RT.RIGHT_ID
WHERE PR.PERSON_ID = AV_LOGIN_PERSON_ID AND RT.RIGHT_NAME IN ('VIEW_COI_PRIVATE_COMMENTS','MAINTAIN_COI_PRIVATE_COMMENTS');

SET LS_DYN_SQL = CONCAT(
    LS_DYN_SQL,
    'WITH CommentsCount AS (
        SELECT MODULE_ITEM_KEY, MODULE_CODE, COUNT(*) AS COMMENT_COUNT
        FROM coi_project_comment
        where MODULE_CODE = 1
        GROUP BY MODULE_ITEM_KEY
    ),
	 PersonCommentsCount AS (
        SELECT MODULE_ITEM_KEY, MODULE_CODE,DOCUMENT_OWNER_PERSON_ID,COUNT(*) AS PERSON_COMMENT_COUNT
        FROM DISCL_COMMENT
        where MODULE_CODE = 8 AND PARENT_COMMENT_ID IS NULL
		AND ((',LI_CA_ADMIN,' = 0 AND COMPONENT_TYPE_CODE IN (3, 4, 5, 6, 8, 9, 2, 10, 11, 12)) 
            OR (',LI_CA_ADMIN,' = 1 AND COMPONENT_TYPE_CODE = 12)
        )
		AND ((',LI_CAN_VIEW_PRIVATE_COMMENT,' = 0 AND IS_PRIVATE = ''N'') 
            OR (',LI_CAN_VIEW_PRIVATE_COMMENT,' > 0 AND IS_PRIVATE IN (''Y'',''N''))
        )
        GROUP BY MODULE_ITEM_KEY,DOCUMENT_OWNER_PERSON_ID
    )'
);

SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '
SELECT * FROM (
SELECT *,
    @row_number := IF(@prev_value = T.PROJECT_ID, @row_number, @row_number + 1) AS rownumber,
	@prev_value := T.PROJECT_ID AS PROJECT_IDS
FROM (SELECT 
	T1.PROJECT_ID,
    T1.PROJECT_NUMBER,
    T1.TITLE,
	T1.PI_PERSON_ID,
    T1.PI_NAME,
    T1.KEY_PERSON_ID,
    T1.KEY_PERSON_NAME,
    T1.KEY_PERSON_ROLE_CODE,
    T1.KEY_PERSON_ROLE,
    T1.SPONSOR_NAME,
    T1.SPONSOR_CODE,
    T1.PRIME_SPONSOR_NAME,
    T1.PRIME_SPONSOR_CODE,
    T1.LEAD_UNIT_NUMBER,
    T1.LEAD_UNIT_NAME,
    T1.HOME_UNIT,
    T1.HOME_UNIT_NAME,
    T1.AWARD_START_DATE,
    T1.AWARD_END_DATE,
    T1.PROJECT_STATUS,
    T1.DISCLOSURE_ID,
    T1.DISCLOSURE_REVIEW_STATUS,
    T1.FCOI_TYPE_CODE,
    T1.PROJECT_TYPE_CODE,
    T1.PROJECT_TYPE,
    T1.BADGE_COLOR,
    T1.UPDATE_TIMESTAMP,
    null as CERTIFICATION_FLAG,
    T1.DISCLOSURE_REQUIRED_FLAG,
    T1.COMMENT_COUNT ,
    T1.DISCLOSURE_COMPLETION_STATUS,
    T1.PROJECT_ICON,
    T1.DOCUMENT_NUMBER,
    T1.ACCOUNT_NUMBER,
   CASE
    WHEN T1.DISCLOSURE_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
	WHEN T1.DISCLOSURE_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''
    WHEN (T1.DISCLOSURE_STATUS =''DISCLOSURE_NOT_REQUIRED'' OR (T1.DISCLOSURE_STATUS IS NULL AND T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED'' AND IFNULL(T1.DISCLOSURE_VALIDATION_FLAG,''x'' <> ''SELF''))) THEN ''Not Required''
    WHEN (T1.DISCLOSURE_STATUS =''NOT_YET_DISCLOSED'' OR T1.DISCLOSURE_STATUS IS NULL) THEN ''Yet to disclose''
    END AS PERSON_SUBMISSION_STATUS ,
 	CASE   
    WHEN T1.DISCLOSURE_REVIEW_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
    WHEN (T1.DISCLOSURE_REVIEW_STATUS =''DISCLOSURE_REVIEW_NA'' OR (T1.DISCLOSURE_STATUS IS NULL AND T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED'' AND IFNULL(T1.DISCLOSURE_VALIDATION_FLAG,''x'' <> ''SELF''))) THEN ''N/A''
	WHEN T1.DISCLOSURE_REVIEW_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''    
    ELSE T1.DISCLOSURE_REVIEW_STATUS
    END AS PERSON_REVIEW_STATUS , 
	 	CASE   
    WHEN T1.PROJECT_REVIEW_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
    WHEN ( T1.PROJECT_REVIEW_STATUS =''DISCLOSURE_REVIEW_NA''  OR (T1.PROJECT_REVIEW_STATUS IS NULL AND T1.DISCL_RQD = ''NR'')) THEN ''N/A''
	WHEN T1.PROJECT_REVIEW_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''    
    ELSE T1.PROJECT_REVIEW_STATUS
    END AS PROJECT_REVIEW_STATUS , 
	 CASE
    WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
	WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''
    WHEN (T1.PROJECT_SUBMISSION_STATUS =''DISCLOSURE_NOT_REQUIRED''  OR (T1.PROJECT_SUBMISSION_STATUS IS NULL AND T1.DISCL_RQD = ''NR''))THEN ''Not Required''
    WHEN (T1.PROJECT_SUBMISSION_STATUS =''NOT_YET_DISCLOSED'' OR  T1.PROJECT_SUBMISSION_STATUS IS NULL) THEN ''Yet to disclose''
    END AS PROJECT_SUBMISSION_STATUS ,
    T1.Complete_count,
     T1.PCK,
     T1.DISCLOSURE_VALIDATION_FLAG,
    T1.SPONSOR_HIERARCY,
    T1.Incomplete_count,
    T1.RESUBMISSION_FLAG,
           (CASE 
	WHEN T1.INCOMPLETE_COUNT = 0 AND T1.DISCLOSURE_VALIDATION_FLAG = ''SELF'' THEN
		"COI Admin has previously requested a disclosure against this award. All key persons have submitted their disclosures for this award."
    WHEN T1.PROJECT_STATUS = ''Hold'' THEN
        CASE 
            WHEN T1.SPONSOR_HIERARCY = ''YES'' THEN CONCAT(
                "This award is on hold due to ",
                "the sponsor\'s requirement for a disclosure",
                CASE 
                    WHEN T1.DISCLOSURE_VALIDATION_FLAG = ''SELF'' THEN ", A Disclosure Request has been triggered by the COI Admin for this award."
                    ELSE \'\'
                END,
                CASE 
                    WHEN T1.PCK != ''N/A'' THEN ", and the need for the PI/COI/keyperson to complete their disclosures."
                    ELSE \'\'
                END
            )
            WHEN T1.DISCLOSURE_VALIDATION_FLAG = ''SELF'' THEN CONCAT(
                "A Disclosure Request has been triggered by the COI Admin for this award.",
                CASE 
                    WHEN T1.PCK != ''N/A'' THEN ", and the need for the PI/COI/keyperson to complete their disclosures."
                    ELSE \'\'
                END
            )
            WHEN T1.PCK != ''N/A'' THEN CONCAT(
                "This award is on hold due to ",
                "the need for the PI/COI/keyperson to complete their disclosures."
            )
            ELSE NULL
        END
        WHEN T1.DISCLOSURE_VALIDATION_FLAG = ''SELF'' THEN
			"A Disclosure Request has been triggered by the COI Admin for this award."
    ELSE NULL
END) AS INFO,
    T1.NON_EMPLOYEE_FLAG,
    T1.PERSON_COMMENT_COUNT,
    T1.TRAINING_STATUS
    FROM
(SELECT DISTINCT 
    T1.PROJECT_ID,
    T1.PROJECT_NUMBER,
    T1.TITLE,
	   (SELECT 
                `coi_int_stage_award_person`.`KEY_PERSON_ID`
            FROM
                `coi_int_stage_award_person`
            WHERE
                ((`coi_int_stage_award_person`.`KEY_PERSON_ROLE_NAME` = ''Principal Investigator'')
                    AND (`coi_int_stage_award_person`.`PROJECT_NUMBER` = `T1`.`PROJECT_NUMBER`)
                    AND (`coi_int_stage_award_person`.`STATUS` <> ''I''))
            LIMIT 1) AS `PI_PERSON_ID`,
     (SELECT 
                `coi_int_stage_award_person`.`KEY_PERSON_NAME`
            FROM
                `coi_int_stage_award_person`
            WHERE
                ((`coi_int_stage_award_person`.`KEY_PERSON_ROLE_NAME` = ''Principal Investigator'')
                    AND (`coi_int_stage_award_person`.`PROJECT_NUMBER` = `T1`.`PROJECT_NUMBER`)
                    AND (`coi_int_stage_award_person`.`STATUS` <> ''I''))
            LIMIT 1) AS `PI_NAME`,
    T2.KEY_PERSON_ID,
    T2.KEY_PERSON_NAME,
    T2.KEY_PERSON_ROLE_CODE,
    T7.DESCRIPTION AS KEY_PERSON_ROLE,
    T1.SPONSOR_NAME,
    T3.SPONSOR_CODE,
    T1.PRIME_SPONSOR_NAME,
    T4.SPONSOR_CODE AS PRIME_SPONSOR_CODE,
    T1.LEAD_UNIT_NUMBER,
    T1.LEAD_UNIT_NAME,
    P.HOME_UNIT,
    T8.UNIT_NAME AS HOME_UNIT_NAME,
    T1.PROJECT_START_DATE AS AWARD_START_DATE,
    T1.PROJECT_END_DATE AS AWARD_END_DATE,
    T1.PROJECT_STATUS,
    T2.MAX_DISCLOSURE_ID AS DISCLOSURE_ID, 
	-- T2.DISCLOSURE_REVIEW_STATUS,    
	(SELECT FCOI_TYPE_CODE FROM COI_DISCLOSURE WHERE DISCLOSURE_ID = T2.MAX_DISCLOSURE_ID) AS FCOI_TYPE_CODE,
	1 AS PROJECT_TYPE_CODE,
    T10.DESCRIPTION AS PROJECT_TYPE,
    T7.SORT_ID ,
    T10.BADGE_COLOR,
    T1.SRC_SYS_UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP,
    null as CERTIFICATION_FLAG,
    T2.DISCLOSURE_REQUIRED_FLAG,
    (SELECT COALESCE(COMMENT_COUNT, 0) FROM CommentsCount WHERE MODULE_ITEM_KEY = T1.PROJECT_NUMBER AND MODULE_CODE = 1 LIMIT 1) AS COMMENT_COUNT,
    CASE 
        WHEN DISCLOSURE_STATUS IN ( ''DISCLOSURE_COMPLETED'',''DISCLOSURE_NOT_REQUIRED'')
        THEN "Yes"
        ELSE "No"
    END AS DISCLOSURE_COMPLETION_STATUS, 
    T10.PROJECT_ICON,
    T1.ATTRIBUTE_2_VALUE AS DOCUMENT_NUMBER,
    T1.ACCOUNT_NUMBER,
    T1.ATTRIBUTE_1_VALUE AS PCK,
    T1.DISCLOSURE_VALIDATION_FLAG,
    (case when (T1.SPONSOR_CODE IN (SELECT T21.SPONSOR_CODE FROM SPONSOR_DISCLOSURE_REQUIREMENTS T21)
      OR T1.PRIME_SPONSOR_CODE IN (SELECT T21.SPONSOR_CODE FROM SPONSOR_DISCLOSURE_REQUIREMENTS T21) )
      THEN ''YES'' ELSE ''NO'' END) AS SPONSOR_HIERARCY,
	T2.DISCLOSURE_STATUS,
	T2.DISCLOSURE_REVIEW_STATUS,
	T1.OVERALL_DISCL_REVIEW_STATUS AS PROJECT_REVIEW_STATUS ,
	T1.OVERALL_DISCLOSURE_STATUS AS PROJECT_SUBMISSION_STATUS,
	CASE WHEN  IFNULL(T1.DISCLOSURE_VALIDATION_FLAG,''x'') <>''SELF'' AND NOT EXISTS 
						(SELECT 1 
							FROM COI_INT_STAGE_AWARD_PERSON 
							WHERE PROJECT_NUMBER = T1.PROJECT_NUMBER 							
							AND  DISCLOSURE_REQUIRED_FLAG <> ''NOT_REQUIRED'')  THEN ''NR''
		ELSE ''R''
		END AS DISCL_RQD,							
    (SELECT COUNT(*) FROM  COI_INT_STAGE_AWARD_PERSON WHERE DISCLOSURE_STATUS = ''DISCLOSURE_COMPLETED'' AND PROJECT_NUMBER = T1.PROJECT_NUMBER) AS complete_count,
    (SELECT COUNT(*) FROM  COI_INT_STAGE_AWARD_PERSON WHERE IFNULL(DISCLOSURE_STATUS,''x'') <>''DISCLOSURE_COMPLETED'' AND PROJECT_NUMBER = T1.PROJECT_NUMBER) AS Incomplete_count,    
     (CASE
    WHEN ( T2.NEW_DISCLOSURE_REQUIRED = ''Y'' AND T2.STATUS != ''I''
    AND T2.ATTRIBUTE_1_VALUE = ''N'') THEN ''Y''
    ELSE ''N''
  END) AS RESUBMISSION_FLAG,
  T2.ATTRIBUTE_1_VALUE AS NON_EMPLOYEE_FLAG,
  COALESCE(PC.PERSON_COMMENT_COUNT, 0) AS PERSON_COMMENT_COUNT,
  CASE
		WHEN T2.ATTRIBUTE_1_VALUE = ''Y'' THEN ''Training Not Required''
		WHEN ''',LI_TRAINING_CODE,''' IS NOT NULL AND ''',LI_TRAINING_CODE,''' <> '''' THEN
			CASE 
				WHEN EXISTS (SELECT 1
							FROM PERSON_TRAINING PT
							WHERE PT.PERSON_ID = T2.KEY_PERSON_ID
								AND FIND_IN_SET(''',LI_TRAINING_CODE,''',PT.TRAINING_CODE)
								AND PT.FOLLOWUP_DATE > CURRENT_TIMESTAMP()) THEN ''Training Completed''
				ELSE ''Training Required''
			END
		ELSE ''Training Not Required''
	END AS TRAINING_STATUS
	FROM COI_INT_STAGE_AWARD T1		
	     LEFT JOIN COI_INT_STAGE_AWARD_PERSON T2 ON (T1.PROJECT_NUMBER = T2.PROJECT_NUMBER)	     
	 ',IFNULL(LS_JOIN_CONDITION,''), '
  	 LEFT JOIN PersonCommentsCount PC ON (PC.MODULE_ITEM_KEY = T2.MAX_DISCLOSURE_ID  
                                          AND PC.DOCUMENT_OWNER_PERSON_ID = T2.KEY_PERSON_ID)
	WHERE T2.STATUS!= ''I''  ',IFNULL(LS_FILTER_CONDITION,''), ' ) T1',IFNULL(LS_ORDER_BY,''),' )T '
    ,LS_FILTER_CONDITION_1 ,') T',IFNULL(LS_OFFSET_CONDITION,''),' ');

 
 IF AV_UNLIMITED = TRUE THEN

    SET LS_DYN_SQL = CONCAT('SELECT count(distinct PROJECT_ID) AS AWARD_COUNT FROM ( ',LS_DYN_SQL,' ) T');

 END IF; 

SET @row_number = 0;
SET @prev_value = NULL;		


SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;


END
//
