DROP PROCEDURE IF EXISTS GET_COI_AWARD_PROJECT_OVERVIEW;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;

DROP FUNCTION IF EXISTS FN_GET_OVAL_AWD_PRJT_DISCL_STATUS;
DROP FUNCTION IF EXISTS FN_GET_OVRAL_AWD_PRJT_DISCL_RVW_STATUS;
DROP FUNCTION IF EXISTS FN_GET_OVERALL_PRJT_DISCL_RVW_STATUS;
DROP FUNCTION IF EXISTS FN_GET_OVERALL_PRJT_DISCL_STATUS;