\. ./FIBI-COI-5.1.3.P4/FC-1166-Bug-Fixes/Procedures/GET_COI_AWARD_PROJECT_OVERVIEW.sql
\. ./FIBI-COI-5.1.3.P4/FC-1166-Bug-Fixes/Procedures/GET_PROJECT_OVERVIEW.sql

\. ./FIBI-COI-5.1.3.P4/FC-1166-Bug-Fixes/Functions/FN_GET_OVAL_AWD_PRJT_DISCL_STATUS.sql
\. ./FIBI-COI-5.1.3.P4/FC-1166-Bug-Fixes/Functions/FN_GET_OVRAL_AWD_PRJT_DISCL_RVW_STATUS.sql
\. ./FIBI-COI-5.1.3.P4/FC-1166-Bug-Fixes/Functions/FN_GET_OVERALL_PRJT_DISCL_RVW_STATUS.sql
\. ./FIBI-COI-5.1.3.P4/FC-1166-Bug-Fixes/Functions/FN_GET_OVERALL_PRJT_DISCL_STATUS.sql
