UPDATE MESSAGE 
SET DESCRIPTION = 'FCOI Disclosure Renewal Required',
    UPDATE_TIMESTAMP = UTC_TIMESTAMP(),
    UPDATE_USER = 'admin'
WHERE MESSAGE_TYPE_CODE = '165';

UPDATE MESSAGE
SET DESCRIPTION='OPA Disclosure Renewal Required',
    UPDATE_TIMESTAMP = UTC_TIMESTAMP(),
    UPDATE_USER = 'admin'
WHERE MESSAGE_TYPE_CODE='166';
