package com.polus.fibicomp.constants;

public interface ActionTypes {

    String FCOI_SUBMIT = "FCOI_SUBMIT"; // FCOI Disclosure Submit
    String PROJECT_SUBMIT = "PROJECT_SUBMIT"; // Project Disclosure Submit
    String FCOI_COMPLETE = "FCOI_COMPLETE"; // FCOI Disclosure complete/approve
    String PROJECT_COMPLETE = "PROJECT_COMPLETE"; // Project Disclosure complete/approve
    String FCOI_RETURN = "FCOI_RETURN"; // FCOI Disclosure Return
    String PROJECT_RETURN = "PROJECT_RETURN"; // Project Disclosure Return
    String FCOI_WITHDRAW = "FCOI_WITHDRAW"; // FCOI Disclosure Withdraw
    String PROJECT_WITHDRAW = "PROJECT_WITHDRAW"; // Project Disclosure Withdraw
    String FCOI_REVIEWER_ASSIGN = "FCOI_REVIEWER_ASSIGN"; // FCOI Disclosure Reviewer added
    String PROJECT_REVIEWER_ASSIGN = "PROJECT_REVIEWER_ASSIGN"; // Project Disclosure Reviewer updated
    String FCOI_REVIEWER_UPDATE = "FCOI_REVIEWER_UPDATE"; // FCOI Disclosure  Reviewer added
    String PROJECT_REVIEWER_UPDATE = "PROJECT_REVIEWER_UPDATE"; // Project Disclosure Reviewer updated
    String FCOI_LOCATION_ASSIGN = "FCOI_LOCATION_ASSIGN"; // FCOI Disclosure Reviewer Location added
    String PROJ_LOCATION_REVIEW_ASSIGNED_WITHOUT_REVIEWER = "PROJ_LOC_ASSIGNED_NO_REVIEWER"; // Project Disclosure Review Location added without Reviewer
    String FCOI_LOCATION_REVIEW_ASSIGNED_WITHOUT_REVIEWER = "FCOI_LOC_ASSIGNED_NO_REVIEWER"; // FCOI Disclosure Review Location added without Reviewer
    String FCOI_LOCATION_UPDATE = "FCOI_LOCATION_UPDATE"; // FCOI Disclosure  Reviewer Location updated
    String PROJECT_LOCATION_UPDATE = "PROJECT_LOCATION_UPDATE"; // Project Disclosure Reviewer Location updated
    String FCOI_ASSIGN_ADMIN = "FCOI_ASSIGN_ADMIN"; // FCOI Disclosure Assign Administrator
    String PROJECT_ASSIGN_ADMIN = "PROJECT_ASSIGN_ADMIN"; // Project Disclosure Assign Administrator
    String FCOI_REASSIGN_ADMIN = "FCOI_REASSIGN_ADMIN"; // FCOI Disclosure Reassign Administrator
    String PROJECT_REASSIGN_ADMIN = "PROJECT_REASSIGN_ADMIN"; //Project Disclosure Reassign Administrator
    String FCOI_RESUBMIT = "FCOI_RESUBMIT"; // FCOI Disclosure Resubmit/Re-certify
    String PROJECT_RESUBMIT = "PROJECT_RESUBMIT";  // Project Disclosure Resubmit/Re-certify
    String PROJECT_NOTIFY = "PROJECT_NOTIFY"; // Incomplete Project Disclosure Notification
    String FCOI_REVIEWER_REVIEW_COMPLETE = "FCOI_REVIEWER_REVIEW_COMPLETE";
    String PROJ_REVIEWER_REVIEW_COMPLETE = "PROJ_REVIEWER_REVIEW_COMPLETE";
    String FCOI_REVIEWER_REVIEW_COMPLETE_BY_ADMIN = "FCOI_REVIEWER_ADMIN_COMPLETE";
    String PROJ_REVIEWER_REVIEW_COMPLETE_BY_ADMIN = "PROJ_REVIEWER_ADMIN_COMPLETE";
    String FCOI_LOCATION_REVIEW_COMPLETED_ACK = "FCOI_LOCATION_REVIEWER_ACK";
    String PROJ_LOCATION_REVIEW_COMPLETED_ACK = "PROJECT_LOCATION_REVIEWER_ACK";
    String FCOI_DISCL_RISK_MODIFY = "FCOI_DISCL_RISK_MODIFY";
    String PROJECT_DISCL_RISK_MODIFY = "PROJECT_DISCL_RISK_MODIFY";
    String FCOI_DISCL_CONFLICT_MODIFY = "FCOI_DISCL_CONFLICT_MODIFY";
    String PROJECT_DISCL_CONFLICT_MODIFY = "PROJECT_DISCL_CONFLICT_MODIFY";
    String ENTITY_CREATION = "ENTITY_CREATION";
    String ENTITY_MODIFY = "ENTITY_MODIFY";
    String ENTITY_INACTIVATE = "ENTITY_INACTIVATE";
    String FCOI_REVIEWER_REMOVE = "FCOI_REVIEWER_REMOVE";
    String PROJECT_REVIEWER_REMOVE = "PROJECT_REVIEWER_REMOVE";
    String FCOI_REQUEST_WITHDRAWAL = "FCOI_REQUEST_WITHDRAWAL";
    String FCOI_REQ_WITHDRAWAL_DENY = "FCOI_REQ_WITHDRAWAL_DENY";
    String FCOI_REVISE_ON_ENG_CREATE = "FCOI_REVISE_ON_ENG_CREATE";
    String DISCLOSURE_RESUBMISSION = "DISCLOSURE_RESUBMISSION";
	String FCOI_ADMIN_REMOVE = "FCOI_ADMIN_REMOVE";
	String PROJECT_ADMIN_REMOVE = "PROJECT_ADMIN_REMOVE";
    //Travel
    String TRAVEL_CREATION = "TRAVEL_CREATION";
    String TRAVEL_ASSIGN_ADMIN = "TRAVEL_ASSIGN_ADMIN";
    String TRAVEL_REASSIGN_ADMIN = "TRAVEL_REASSIGN_ADMIN";
    String TRAVEL_SUBMIT = "TRAVEL_SUBMIT";
    String TRAVEL_RESUBMIT = "TRAVEL_RESUBMIT";
    String TRAVEL_WITHDRAW = "TRAVEL_WITHDRAW";
    String TRAVEL_RETURN = "TRAVEL_RETURN";
    String TRAVEL_ADMIN_APPROVE = "TRAVEL_ADMIN_APPROVE";
    String ENTITY_MODIFY_NOTIFY = "ENTITY_MODIFY_NOTIFY";
    String ENTITY_INACTIVATE_REP_NOTIFY = "ENTITY_INACTIVATE_REP_NOTIFY";
    String NOTIFY_PER_ENG_DIS_CREATION_REQ = "ENG_DIS_CREATION";
    String TRAVEL_WITHDRAWN_RESUBMISSION = "TRAVEL_WITHDRAWN_RESUBMISSION";
    String TRAVEL_RETURNED_RESUBMISSION = "TRAVEL_RETURNED_RESUBMISSION";
    String PROJ_ALL_KP_DISCL_SUB_DONE="PROJ_ALL_KP_DISCL_SUB_DONE";
    String PROJ_ALL_KP_DISCL_RVW_DONE="PROJ_ALL_KP_DISCL_RVW_DONE";
	String TRAVEL_ADMIN_REMOVE = "TRAVEL_ADMIN_REMOVE";
	// OPA
	String OPA_SUBMIT = "OPA_SUBMIT";
	String OPA_WITHDRAW = "OPA_WITHDRAW";
	String OPA_RETURN = "OPA_RETURN";
	String OPA_WITHDRAWN_RESUBMISSION = "OPA_WITHDRAWN_RESUBMISSION";
	String OPA_RETURNED_RESUBMISSION = "OPA_RETURNED_RESUBMISSION";
	String OPA_ASSIGN_ADMIN = "OPA_ASSIGN_ADMIN";
	String OPA_REASSIGN_ADMIN = "OPA_REASSIGN_ADMIN";
	String OPA_FIRST_STOP_APPROVER = "OPA_FIRST_STOP_APPROVER";
	String OPA_REVIEWER_ASSIGN = "OPA_REVIEWER_ASSIGN";
	String OPA_REVIEWER_REVIEW_COMPLETE = "OPA_REVIEWER_REVIEW_COMPLETE";
	String OPA_ADMIN_REVIEWER_COMPLETE = "OPA_ADMIN_REVIEWER_COMPLETE";
	String OPA_ADMIN_REMOVE = "OPA_ADMIN_REMOVE";
	String OPA_REVIEWER_REMOVE = "OPA_REVIEWER_REMOVE";
	String OPA_REVIEWER_REVIEW_COMPLETE_BY_ADMIN = "OPA_REVIEWER_ADMIN_COMPLETE";
	String OPA_LOCATION_REVIEW_COMPLETED_ACK = "OPA_LOCATION_REVIEWER_ACK";
    String OPA_LOCATION_REVIEW_ASSIGNED_WITHOUT_REVIEWER = "OPA_LOC_ASSIGNED_NO_REVIEWER"; // OPA Disclosure Review Location added without Reviewer

    String DECLARATION_ADMIN_REMOVE = "DECLARATION_ADMIN_REMOVE";
    String DECLARATION_REASSIGN_ADMIN = "DECLARATION_REASSIGN_ADMIN";
    String DECLARATION_ASSIGN_ADMIN = "DECLARATION_ASSIGN_ADMIN";
    String DECLARATION_WITHDRAW = "DECLARATION_WITHDRAW";
    String DECLARATION_RETURN = "DECLARATION_RETURN";
    String DECLARATION_SUBMIT = "DECLARATION_SUBMIT";
    String DECLARATION_RESUBMIT = "DECLARATION_RESUBMIT";
    String DECLARATION_REVIEW_COMPLETED = "DECLARATION_REVIEW_COMPLETED";

    String PERS_DISC_REQ_NOTIFY = "PERS_DISC_REQ_NOTIFY";
    String DECLARATION_REVIEW_APPROVED = "DECLARATION_REVIEW_APPROVED";
    String DECLARATION_REVIEW_REJECTED = "DECLARATION_REVIEW_REJECTED";
}
