package com.polus.fibicomp.constants;

public interface Constants {


    // Security constants
    String SECRET = "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJt6Aa8aOs06KyiBZ3pwiKdfgmdbosVuNPpxO9hUd6gsKk3lxTx+pBpkaONP/WHWkv5g/GvgOt9R+aItSxf3LEcCAwEAAQ==";
    long EXPIRATION_TIME = 43_200_000; // 12 hour
    String TOKEN_PREFIX = "Bearer ";
    String HEADER_STRING = "Authorization";
    String SIGN_UP_URL = "/fibi-comp/login";
    String EXTERNAL_AUTHORIZATION = "EXTERNALAUTH";
    String TRUE = "Y";
    Integer UNAUTHORIZED = 401;
    String LOGIN_PERSON_ID = "personId";
    String LOGIN_PERSON_UNIT = "unitNumber";
    String LOGIN_USER_FULL_NAME = "fullName";
    String IS_EXTERNAL_USER = "isExternalUser";

    // Grant Call


    // Module Code
    Integer AWARD_MODULE_CODE = 1;
    Integer INST_PROPOSAL_MODULE_CODE = 2;
    Integer DEV_PROPOSAL_MODULE_CODE = 3;

    String YES = "Y";
    String NO = "N";

    String JAVA_ERROR = "ERR";
    String DB_PROC_ERROR = "ERRP";
    String DB_FN_ERROR = "ERRF";
	String PROPOSAL_DISCLOSURE = "2";
    String AWARD_DISCLOSURE = "3";
	String DISCLOSURE_SEQUENCE_STATUS_PENDING = "1";
	String DISCLOSURE_SEQUENCE_STATUS_ACTIVE = "2";
	String DISCLOSURE_STATUS_PENDING = "1";
    /** COI */
    Integer COI_MODULE_CODE = 8;
    Integer COI_SUBMODULE_CODE = 0;
    Integer COI_SFI_SUBMODULE_CODE = 801;

    String COI_ACTIVE_STATUS = "ACTIVE";
    String COI_ARCHIVE_STATUS = "ARCHIVE";
    Integer COI_INITIAL_VERSION_NUMBER = 1;
    String COI_PENDING_STATUS = "PENDING";
    String COI_INACTIVE_STATUS = "INACTIVE";
    String COI_CANCELLED_STATUS =  "CANCELLED";



    String TYPE_SYNC_FCOI_ON_CREATE = "F";
    String TYPE_SYNC_PROJECT_DISCLOSURE_ON_CREATE = "P";
    String TYPE_SYNC_SFI_WITH_DISCLOSURE_PROJECTS = "SD";
    
    String TRAVEL_STATUS_CODE = "1";
    String TRAVEL_DOCUMENT_STATUS_CODE_DRAFT = "1";
    String TRAVEL_DOCUMENT_STATUS_CODE_APPROVED = "2";
    String TRAVEL_DISCLOSURE_STATUS_CODE = "1";

    String TRAVEL_REVIEW_STATUS_CODE_PENDING = "1";
    String TRAVEL_REVIEW_STATUS_CODE_SUBMITTED = "2";
    String TRAVEL_REVIEW_STATUS_CODE_REVIEW_INPROGRESS = "3";
    String TRAVEL_REVIEW_STATUS_CODE_RETURNED = "4";
    String TRAVEL_REVIEW_STATUS_CODE_WITHDRAWN = "5";
    String TRAVEL_REVIEW_STATUS_CODE_COMPLETED = "6";
    String TRAVEL_REVIEW_STATUS_CODE_APPROVED = "7";
    String TRAVEL_VERSION_STATUS_CODE = "1";
    String TRAVEL_VERSION_STATUS_PENDING = "PENDING";
    String TRAVE_VERSION_STATUS_ACTIVE = "ACTIVE";
    Integer DEFAULT_TRAVEL_VERSION_NUMBER = 1;
    String COI_ENTITY_STATUS_VERIFIED = "1";

    String COI_ENTITY_CREATE_ACTION_LOG_CODE = "1";
    String COI_ENTITY_ACTIVATE_ACTION_LOG_CODE = "2";
    String COI_ENTITY_INACTIVATE_ACTION_LOG_CODE = "3";
    String COI_ENTITY_VERIFY_ACTION_LOG_CODE = "4";
    String COI_ENTITY_MODIFY_RISK_ACTION_LOG_CODE = "5";
    String COI_ENTITY_MODIFY_ACTION_LOG_CODE = "6";
    String COI_ENTITY_RISK_ADD_ACTION_LOG_CODE = "7";

    String COI_DISCLOSURE_ACTION_LOG_CREATED = "1";
    String COI_DISCLOSURE_ACTION_LOG_REVISED = "28";
    String COI_DISCLOSURE_ACTION_LOG_SUBMITTED = "2";
    String COI_DISCLOSURE_ACTION_LOG_WITHDRAWN = "3";
    String COI_DISCLOSURE_ACTION_LOG_ASSIGN_ADMIN = "4";
    String COI_DISCLOSURE_ACTION_LOG_REASSIGN_ADMIN = "5";
    String COI_DISCLOSURE_ACTION_LOG_RETURNED = "6";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_REVIEW_COMPLETED = "11";
    String COI_DISCLOSURE_ACTION_LOG_ASSIGNED_FOR_REVIEW = "7";
    String COI_DISCLOSURE_ACTION_LOG_ASSIGNED_REVIEW_COMPLETED = "8";
    String COI_DISCLOSURE_ACTION_LOG_MODIFY_RISK = "10";
    String COI_DISCLOSURE_ACTION_LOG_ADD_CONFLICT_STATUS = "30";
    String COI_DISCLOSURE_ACTION_LOG_MODIFY_CONFLICT_STATUS = "29";
    String COI_DISCLOSURE_ACTION_LOG_ADD_RISK = "9";
    String COI_DIS_ACTION_LOG_CREATED_REVIEW_WITH_REVIEWER = "16";
    String COI_DISCLOSURE_ACTION_LOG_REVIEWER_START_REVIEW = "17";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_START_REVIEW_WITH_REVIEWER = "18";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_START_REVIEW_WITHOUT_REVIEWER = "25";
    String COI_DISCLOSURE_ACTION_LOG_REVIEWER_COMPLETE_REVIEW = "19";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_COMPLETE_REVIEW_WITH_REVIEWER = "20";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_COMPLETE_REVIEW_WITHOUT_REVIEWER = "26";
    String COI_DISCLOSURE_ACTION_LOG_REVIEW_REMOVED_WITH_REVIEWER = "21";
    String COI_DISCLOSURE_ACTION_LOG_REVIEW_REMOVED_WITHOUT_REVIEWER = "27";
    String COI_DIS_ACTION_LOG_MODIFIED_REVIEW_WITH_REVIEWER = "22";
    String COI_DIS_ACTION_LOG_MODIFIED_REVIEW_WITHOUT_REVIEWER = "24";
    String COI_DIS_ACTION_LOG_CREATED_REVIEW_WITHOUT_REVIEWER = "23";
    String COI_DIS_ACTION_LOG_REQUEST_WITHDRAWAL = "32";
    String COI_DIS_ACTION_LOG_REQUEST_WITHDRAWAL_DENY = "33";
    String COI_DIS_ACTION_LOG_EXPIRY_EXTENDED = "34";
    String COI_DIS_ACTION_LOG_ROUTELOG_COMPLETED = "35";
    String COI_DIS_ACTION_LOG_DISCL_MARKED_VOID_BY_REVISION = "36";
    String COI_DIS_ACTION_LOG_DISCL_MARKED_VOID_BY_ENG = "37";
    String COI_DIS_ACTION_LOG_DISCL_MARKED_VOID_BY_QUEST = "38";
    String COI_DIS_ACTION_LOG_DISCL_MARKED_VOID_BY_PRJCT_CLOSED = "39";
    String COI_DIS_ACTION_LOG_DISCL_MARKED_VOID_BY_KEY_PRSN_REMVL = "40";
    String COI_DIS_ACTION_LOG_DISCL_MARKED_VOID_BY_KEY_PRSN_ROLE = "41";

    String COI_DISCLOSURE_STATUS_WITHDRAW = "6";
    String COI_DISCLOSURE_STATUS_RETURN = "5";
    String COI_DISCLOSURE_STATUS_COMPLETED = "4";
    String COI_DISCLOSURE_STATUS_SUBMITTED = "2";
    String COI_DISCLOSURE_STATUS_REVIEW_IN_PROGRESS = "3";
    String COI_DISCLOSURE_STATUS_ROUTING_INPROGRESS = "9";
    String COI_DISCLOSURE_STATUS_INPROGRESS = "1";

    String COI_DIS_ACTION_LOG_DISCLOSURE_SYNCED = "31";

    String COI_REVIEWER_REVIEW_STATUS_COMPLETED = "2";
    String COI_REVIEWER_REVIEW_STATUS_START = "3";
    String COI_DISCLOSURE_REVIEWER_STATUS_COMPLETED = "8";
    String COI_DISCLOSURE_REVIEWER_STATUS_ASSIGNED = "7";

    Integer OPA_MODULE_CODE = 23;
    String OPA_DISCLOSURE_STATUS_SUBMIT = "2";
    String OPA_DISCLOSURE_STATUS_REVIEW_IN_PROGRESS = "3";
    String OPA_DISCLOSURE_STATUS_WITHDRAW = "6";
    String OPA_DISCLOSURE_STATUS_RETURN = "5";
    String OPA_DISCLOSURE_STATUS_COMPLETED = "4";
    String OPA_DISCLOSURE_STATUS_REVIEW_ASSIGNED = "7";
    String OPA_DISCLOSURE_STATUS_REVIEW_COMPLETED = "8";
    String OPA_DISCLOSURE_STATUS_PENDING = "1";
    String OPA_DISCLOSURE_STATUS_ROUTING_INPROGRESS = "9";

    String OPA_DISPOSITION_STATUS_PENDING = "1";
    String OPA_DISPOSITION_STATUS_COMPLETED = "3";
    String OPA_DISPOSITION_STATUS_EXPIRED = "4";

    String OPA_ACTION_LOG_TYPE_CREATED = "1";
    String OPA_ACTION_LOG_TYPE_SUBMITTED = "2";
    String OPA_ACTION_LOG_TYPE_WITHDRAWN = "3";
    String OPA_ACTION_LOG_TYPE_RETURNED = "4";
    String OPA_ACTION_LOG_TYPE_APPROVED = "5";
    String OPA_ACTION_LOG_TYPE_ADMIN_ASSIGNED = "6";
    String OPA_ACTION_LOG_TYPE_ADMIN_REASSIGNED = "7";
    String OPA_ACTION_LOG_TYPE_ROUTELOG_COMPLETED = "20";
    String OPA_ACTION_LOG_TYPE_REVISED = "21";

    // Consulting Disclosure
    Integer CONSULT_DISCL_MODULE_CODE = 27;
    String CONSULT_DISCL_MODULE_ITEM_CODE = "27";
    String CONSULT_DISCL_MODULE_SUB_ITEM_CODE = "0";
    String CONSULT_DISCL_STATUS_SUBMIT = "2";
    String CONSULT_DISCL_STATUS_REVIEW_IN_PROGRESS = "3";
    String CONSULT_DISCL_STATUS_WITHDRAW = "7";
    String CONSULT_DISCL_STATUS_RETURN = "8";
    String CONSULT_DISCL_STATUS_COMPLETED = "6";
    String CONSULT_DISCL_STATUS_REVIEW_ASSIGNED = "4";
    String CONSULT_DISCL_STATUS_REVIEW_COMPLETED = "6";
    String CONSULT_DISCL_STATUS_PENDING = "1";

    String CONSULT_DISCL_DISPOSITION_STATUS_PENDING = "1";
    String CONSULT_DISCL_DISPOSITION_STATUS_COMPLETED = "2";

    String CONSULT_DISCL_ACTION_LOG_TYPE_CREATED = "1";
    String CONSULT_DISCL_ACTION_LOG_TYPE_SUBMITTED = "2";
    String CONSULT_DISCL_ACTION_LOG_TYPE_WITHDRAWN = "3";
    String CONSULT_DISCL_ACTION_LOG_TYPE_RETURNED = "4";
    String CONSULT_DISCL_ACTION_LOG_TYPE_APPROVED = "5";
    String CONSULT_DISCL_ACTION_LOG_TYPE_ADMIN_ASSIGNED = "6";
    String CONSULT_DISCL_ACTION_LOG_TYPE_ADMIN_REASSIGNED = "7";
    //

    String COI_PERSON_ENTITY_ACTION_LOG_CREATED = "1";
    String COI_PERSON_ENTITY_ACTION_LOG_ACTIVATED = "2";
    String COI_PERSON_ENTITY_ACTION_LOG_INACTIVATED = "3";
    String COI_PERSON_ENTITY_ACTION_LOG_MODIFIED = "4";
    String COI_PERSON_ENTITY_ACTION_LOG_REL_ADDED = "5";
    String COI_PERSON_ENTITY_ACTION_LOG_REL_REMOVED = "6";
    String COI_PERSON_ENTITY_ACTION_LOG_FORM_COMPLETED = "7";
    String COI_DISCLOSURE_REVIEW_STATUS_PENDING = "1";
    String COI_DISCLOSURE_REVIEW_STATUS_COMPLETED = "4";
    String OPA_MODULE_ITEM_CODE = "23";
    String OPA_MODULE_SUB_ITEM_CODE = "0";
    String OPA_REVIEW_ASSIGNED = "1";
    String OPA_REVIEW_IN_PROGRESS = "2";
    String OPA_REVIEW_COMPLETED = "3";

    String OPA_DIS_ACTION_LOG_MODIFIED_REVIEW_WITH_REVIEWER = "10";
    String OPA_DIS_ACTION_LOG_MODIFIED_REVIEW_WITHOUT_REVIEWER = "11";
    String OPA_DIS_ACTION_LOG_CREATED_REVIEW_WITHOUT_REVIEWER = "9";
    String OPA_DIS_ACTION_LOG_CREATED_REVIEW_WITH_REVIEWER = "8";
    String OPA_DIS_ACTION_LOG_ADMIN_START_REVIEW_WITH_REVIEWER = "12";
    String OPA_DIS_ACTION_LOG_ADMIN_START_REVIEW_WITHOUT_REVIEWER = "13";
    String OPA_DIS_ACTION_LOG_ADMIN_START_REVIEW_BY_REVIEWER = "14";
    String OPA_DIS_ACTION_LOG_ADMIN_COMPLETE_REVIEW_BY_REVIEWER = "17";
    String OPA_DIS_ACTION_LOG_ADMIN_COMPLETE_REVIEW_WITH_REVIEWER = "16";
    String OPA_DIS_ACTION_LOG_ADMIN_COMPLETE_REVIEW_WITHOUT_REVIEWER = "15";
    String OPA_DIS_ACTION_LOG_ADMIN_REMOVED_REVIEW_WITH_REVIEWER = "19";
    String OPA_DIS_ACTION_LOG_ADMIN_REMOVED_REVIEW_WITHOUT_REVIEWER = "18";
    String OPA_DISCLOSURE_DETAIL_COMMENT_TYPE = "3";

    String COI_DISCL_CONFLICT_RELATION_COMMENT_TYPE = "1";
    String COI_DISCL_CONFLICT_RELATION_COMPONENT_TYPE = "1";
    String COI_TRAVEL_DISCL_CONFLICT_RELATION_COMPONENT_TYPE = "2";
    String COI_DISCL_REVIEW_COMPONENT_TYPE = "8";
    String ACTIVE_ANSWERED_UNANSWERED = "ACTIVE_ANSWERED_UNANSWERED";
    Integer TRAVEL_MODULE_CODE = 24;
    String COI_VALIDATION_PRO_SFI_ACTION_TYPE = "PS";
    Integer TRAVEL_SELF_RELATIONSHIP = 4;
    String TRAVEL_SELF_RELATIONSHIP_DESC = "Travel : Self";

    String DISCLOSURE_TYPE_CODE_FCOI = "1";
    String DISCLOSURE_TYPE_CODE_OPA = "2";
    String DISCLOSURE_TYPE_CODE_AWARD = "3";
    String DISCLOSURE_TYPE_CODE_PROPOSAL = "2";
    String DISCLOSURE_TYPE_CODE_REVISION = "3";
    String FCOI_TYPE_CODE_PROJECT = "2";
    String COI_DISCL_DISPOSITION_STATUS_VOID = "2";
    String COI_DISCL_DISPOSITION_STATUS_APPROVED = "3";

    String DATE_FORMAT = "yyyy-MM-dd";
    String MESSAGE_EVENT_TYPE_TRIGGER = "T";
    //Notification
    String DISCLOSURE_CREATION_NOTIFICATION_TYPE_ID = "8015";
    String DISCLOSURE_SUBMISSION_NOTIFICATION_TYPE_ID = "8055";
    // Inbox message type codes

    String INBOX_CREATE_DISCLOSURE = "8001";
    String INBOX_PROPOSAL_DISCLOSURE_SUBMISSION = "8002";
    String INBOX_SUBMIT_FCOI_DISCLOSURE = "147";
    String INBOX_RETURN_FCOI_DISCLOSURE = "148";
    String INBOX_ADMIN_ASSIGN_FCOI_DISCLOSURE = "149";
    String INBOX_REVIEW_ASSIGN_FCOI_DISCLOSURE = "150";
    String INBOX_REVISE_FCOI_DISCLOSURE = "151";
    String INBOX_SUBMIT_PROJECT_DISCLOSURE = "152";
    String INBOX_RETURN_PROJECT_DISCLOSURE = "153";
    String INBOX_ADMIN_ASSIGN_PROJECT_DISCLOSURE = "154";
    String INBOX_REVIEW_ASSIGN_PROJECT_DISCLOSURE = "155";
    String INBOX_INACTIVATE_ENTITY = "156";
    String INBOX_MODIFY_ENTITY = "157";
	String INBOX_CREATE_ENTITY = "158";
    String INBOX_FCOI_DISCLOSURE_REQUEST_WITHDRAWAL = "159";
    String INBOX_FCOI_DISCLOSURE_REQUEST_WITHDRAWAL_DENY = "160";
    String INBOX_FCOI_DISCLOSURE_REQUEST_REVISION_OR_WITHDRAWAL = "161";
    String INBOX_FCOI_DISCLOSURE_CREATION = "163";
    String INBOX_FCOI_DISCLOSURE_REVISION = "164";
    String INBOX_FCOI_DISCLOSURE_WITHDRAWAL = "165";
    String INBOX_FCOI_DISCLOSURE_REQUIRED = "8034";

    String INBOX_OPA_DISCLOSURE_CREATION = "166";
    String INBOX_OPA_DISCLOSURE_RETURNED = "8028";
    String INBOX_OPA_DISCLOSURE_SUBMIT = "8029";
    String INBOX_OPA_WAITING_ADMIN_REVIEW = "8030";
    String INBOX_OPA_WAITING_REVIEWER_REVIEW = "8031";
    String INBOX_OPA_DISCLOSURE_REVISION = "8032";
    String INBOX_REVISE_OPA_DISCLOSURE = "8035";

    String INBOX_TRAVEL_DISCLOSURE_CREATION = "167";
    String INBOX_TRAVEL_DISCL_REIMBURSED_COST_LIMIT_EXCEEDED = "162";
    String INBOX_SUBMIT_TRAVEL_DISCLOSURE = "168";
    String INBOX_TRAVEL_WAITING_ADMIN_REVIEW = "169";
    String INBOX_TRAVEL_RETURNED = "170";
    String INBOX_DUNS_REFRESH_VERIFY = "8026";

    String SUBJECT_TYPE_COI = "C";
    String BANNER_TYPE = "B";
    String PROJECT_TYPE_AWARD = "Award";
    String PROJECT_TYPE_PROPOSAL = "Development Proposal";

    Integer GLOBAL_ENTITY_MODULE_CODE = 26;
    Integer GLOBAL_ENTITY_SUB_MODULE_CODE_SPONSOR = 1;
    Integer GLOBAL_ENTITY_SUB_MODULE_CODE_SUB_AWARD = 2;
    Integer GLOBAL_ENTITY_SUB_MODULE_CODE_COMPLIANCE = 3;

    String ENTITY_ACTION_LOG_MODIFY = "15";
	Integer FINANCIAL_SELF_RELATION_TYPE = 1;
	Integer FINANCIAL_SPOUSE_RELATION_TYPE = 2;
	Integer FINANCIAL_DEPENDENT_RELATION_TYPE = 3;
    String GLOBAL_ENTITY_STATUS_CODE_MODIFYING = "3";
    String GLOBAL_ENTITY_STATUS_CODE_DUNS_REFRESH_MODIFYING = "4";
    String FINANCIAL_RELATION_TYPE = "1";

    // Travel Disclosure
    String TRAVEL_ACTION_LOG_CREATED = "1";
    String TRAVEL_ACTION_LOG_ASSIGN_ADMIN = "4";
    String TRAVEL_ACTION_LOG_REASSIGN_ADMIN = "5";
    String TRAVEL_ACTION_LOG_SUBMITTED = "2";
    String TRAVEL_ACTION_LOG_RETURNED = "6";
    String TRAVEL_ACTION_LOG_WITHDRAWN = "3";
    String TRAVEL_ACTION_LOG_APPROVED = "13";
    String DISCLOSURE_TYPE_CODE_TRAVEL = "3";
    String COI_REIMBURSE_COST_EXCEEDED_NOTIFICATION_TYPE_ID = "8044";

    String TRAVEL_FUNDING_TYPE_INTERNAL = "1";

    String IS_UNIFIED_QUESTIONNAIRE_ENABLED = "IS_UNIFIED_QUESTIONNAIRE_ENABLED";
    String ENGAGEMENT_FLOW_TYPE = "ENGAGEMENT_FLOW_TYPE";
    String ENGAGEMENT_FLOW_TYPE_REL_COMP = "REL_COMP";
    String ENGAGEMENT_FLOW_TYPE_REL_SUB_DIVISION = "REL_SUB_DIVISION";
    String ENGAGEMENT_FLOW_TYPE_REL_SUMMARY = "REL_SUMMARY";
	String PROJECT_AWARD_TAB = "AWARD";
	String DEFAULT_MODULE_ITEM_KEY = "0";

    String UPDATED_BY_SYSTEM = "system";
    String NOTIFICATION_RECIPIENTS = "NOTIFICATION_RECIPIENTS";
    String NOTIFICATION_TYPE_ID = "notificationTypeId";

    String ELASTIC_INDEX_ENTITY = "entity";

    String ELASTIC_ACTION_INSERT = "INSERT";
    String ELASTIC_ACTION_UPDATE = "UPDATE";
    String ELASTIC_ACTION_DELETE = "DELETE";

    String ADDITIONAL_ADDRESS_TYPE_SPONSOR_ADDRESS = "3";
    String ADDITIONAL_ADDRESS_TYPE_ORGANIZATION_ADDRESS = "4";
    
    String TRAVEL_DISCLOSURE_TYPE_CODE = "3";
    String CONSULTING_DISCLOSURE_TYPE_CODE = "4";

	String DISCLOSURE_REVIEW_SUBMITTED = "2";
	String DISCLOSURE_REVIEW_IN_PROGRESS = "3";
	String DISCLOSURE_REVIEW_ASSIGNED = "7";
	String DISCLOSURE_ASSIGNED_REVIEW_COMPLETED = "8";

    String NOTIFICATION_TYPE_ID_ROUTELOG_OPA_APPROVE = "8062";
    String NOTIFICATION_TYPE_ID_ROUTELOG_OPA_BYPASSED = "8073";
    String NOTIFICATION_TYPE_ID_OPA_DISCLOSURE_EXPIRED = "8078";
    String NOTIFICATION_TYPE_ID_FCOI_DISCLOSURE_EXPIRED = "8079";
    String NOTIFICATION_TYPE_ID_PROJECT_DISCLOSURE_EXPIRED = "8080";
    String NOTIFICATION_TYPE_ID_FCOI_DISCL_RENEWAl_REMAINDER = "8022";
    String NOTIFICATION_TYPE_ID_OPA_DISCL_RENEWAl_REMAINDER = "8090";
    String NOTIFICATION_TYPE_ID_FCOI_LEGACY_DISCL_RENEWAl_REMAINDER = "8092";
    String NOTIFICATION_TYPE_ID_FCOI_LEGACY_DISCLOSURE_EXPIRED = "8091";
    String NOTIFICATION_TYPE_ID_FCOI_DISCL_ROUTELOG_APPROVE = "8093";
    String NOTIFICATION_TYPE_ID_PROJECT_DISCL_ROUTELOG_APPROVE = "8094";
    String NOTIFICATION_TYPE_ID_FCOI_DISCL_ROUTELOG_BYPASS="8095";
    String NOTIFICATION_TYPE_ID_PROJECT_DISCL_ROUTELOG_BYPASS="8096";
    String NOTIFICATION_TYPE_ID_PROJECT_DISCL_MARKED_AS_VOID = "8122";

    String PROJECT_COMMENT_TYPE_GENERAL = "1";

    String ENGAGEMENT_TYPE_FOR_COI_DISCLOSURE = "ENGAGEMENT_TYPE_FOR_COI_DISCLOSURE";
    String ALL_ENGAGEMENT = "ALL_ENG";
    String ALL_FINANCIAL_ENGAGEMENT = "ALL_FIN";
    String ALL_SFI_ENGAGEMENT = "ALL_SFI";
    
	// OPA Approval Flow Types
	String OPA_APPROVAL_FLOW_TYPE = "OPA_APPROVAL_FLOW_TYPE";
	String ROUTING_AND_ADMIN_REVIEW = "ROUTING_AND_ADMIN_REVIEW";
	String ROUTING_REVIEW = "ROUTING_REVIEW";
	String ADMIN_REVIEW = "ADMIN_REVIEW";
	String NO_REVIEW = "NO_REVIEW";

    String COI_JOB_GROUP = "coi";

    Integer COI_DECLARATION_MODULE_CODE = 28;

    String FCOI_APPROVAL_FLOW_TYPE = "FCOI_APPROVAL_FLOW_TYPE";

    String INBOX_FCOI_DISCLOSURE_ROUTE_LOG_REVIEW_REQUEST = "8036";
    String INBOX_PROJECT_DISCLOSURE_ROUTE_LOG_REVIEW_REQUEST = "8037";

    String FCOI_DISCLOSURE = "FCOI_DISCLOSURE";
    String PROJECT_DISCLOSURE = "PROJECT_DISCLOSURE";

    String COI_DECLARATION_REVIEW_STATUS_IN_PROGRESS = "1";
    String COI_DECLARATION_REVIEW_STATUS_SUBMIT = "2";
    String COI_DECLARATION_REVIEW_STATUS_REVIEW_IN_PROGRESS = "3";
    String COI_DECLARATION_REVIEW_STATUS_WITHDRAW = "4";
    String COI_DECLARATION_REVIEW_STATUS_RETURN = "5";
    String COI_DECLARATION_REVIEW_STATUS_REVIEW_COMPLETED = "6";
    String COI_DECLARATION_REVIEW_STATUS_EXPIRED = "7";
    String COI_DECLARATION_REVIEW_STATUS_REVIEW_NOT_REQUIRED = "8";

    String COI_DECLARATION_APPROVAL_STATUS_PENDING = "1";
    String COI_DECLARATION_APPROVAL_STATUS_APPROVED = "2";
    String COI_DECLARATION_APPROVAL_STATUS_REJECTED = "3";
    String COI_DECLARATION_APPROVAL_STATUS_VOID = "4";

    String COI_DECLARATION_ACTION_LOG_TYPE_CREATED = "1";
    String COI_DECLARATION_ACTION_LOG_TYPE_SUBMITTED = "2";
    String COI_DECLARATION_ACTION_LOG_TYPE_REVISED = "3";
    String COI_DECLARATION_ACTION_LOG_TYPE_EXPIRED = "4";
    String COI_DECLARATION_ACTION_LOG_TYPE_WITHDRAWN = "5";
    String COI_DECLARATION_ACTION_LOG_TYPE_RETURN = "6";
    String COI_DECLARATION_ACTION_LOG_TYPE_ADMIN_ASSIGN = "7";
    String COI_DECLARATION_ACTION_LOG_TYPE_ADMIN_REASSIGN = "8";
    String COI_DECLARATION_ACTION_LOG_TYPE_ADMIN_REVIEW_COMPLETED = "9";
    String COI_DECLARATION_ACTION_LOG_TYPE_MARKED_AS_VOID = "10";

    String COI_DECLARATION_INBOX_MSG_TYPE_SUBMIT = "8038";
    String COI_DECLARATION_INBOX_MSG_TYPE_RETURNED = "8039";
    String COI_DECLARATION_INBOX_MSG_TYPE_WAITING_ADMIN_REVIEW = "8040";

    String PREFERENCE_TYPE_CODE_DEFAULT_REW_DASH_CHILD_UNIT = "8002";
    String PREFERENCE_TYPE_CODE_DEFAULT_REW_DASH_UNIT = "8001";

    String DECLARATION_TYPE_MFTRP = "1";

    Integer COI_MANAGEMENT_PLAN_MODULE_CODE = 29;
    String COI_MANAGEMENT_PLAN_REVIEW_STATUS_IN_PROGRESS = "1";
    String COI_MANAGEMENT_PLAN_LETTER_TEMPLATE_TYPE_CODE = "8020";
    String COI_MANAGEMENT_PLAN_REVIEWER_REVIEW_STATUS_COMPLETED = "3";
    String CMP_COMPONENT_TYPE_GENERAL="17";
    String CMP_COMPONENT_TYPE_SECTION="18";
    String CMP_COMPONENT_TYPE_SECTION_COMPONENT="19";

    String COI_MANAGEMENT_PLAN_ACTION_LOG_CREATED        = "1";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_DRAFT_STARTED  = "2";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_VOIDED         = "3";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_FINALIZED      = "4";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_EXECUTED       = "5";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_PLAN_EDIT      = "6";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_PLAN_CLOSED    = "7";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_DRAFT_CLOSED   = "8";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_SECTION_ADDED   = "22";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_SECTION_DELETED   = "23";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_DOCUMENT_GENERATED   = "24";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_DOCUMET_REGENERATED   = "25";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_DOCUMET_UPLOAD   = "26";
    String COI_MANAGEMENT_PLAN_ACTION_LOG_DOCUMET_REPLACE   = "27";

    String COI_MANAGEMENT_PLAN_REVIEW_MODIFIED_WITH_REVIEWER    = "9";
    String COI_MANAGEMENT_PLAN_REVIEW_MODIFIED_WITHOUT_REVIEWER = "10";
    String COI_MANAGEMENT_PLAN_REVIEW_STARTED_BY_ADMIN_WITH_REVIEWER    = "11";
    String COI_MANAGEMENT_PLAN_REVIEW_STARTED_BY_ADMIN_WITHOUT_REVIEWER = "12";
    String COI_MANAGEMENT_PLAN_REVIEW_STARTED_BY_REVIEWER               = "13";
    String COI_MANAGEMENT_PLAN_REVIEW_COMPLETED_BY_ADMIN_WITHOUT_REVIEWER = "14";
    String COI_MANAGEMENT_PLAN_REVIEW_COMPLETED_BY_ADMIN_WITH_REVIEWER    = "15";
    String COI_MANAGEMENT_PLAN_REVIEW_COMPLETED_BY_REVIEWER               = "16";
    String COI_MANAGEMENT_PLAN_REVIEW_DELETED_WITHOUT_REVIEWER = "17";
    String COI_MANAGEMENT_PLAN_REVIEW_DELETED_WITH_REVIEWER    = "18";
    String COI_MANAGEMENT_PLAN_REVIEW_ADDED_WITH_REVIEWER    = "19";
    String COI_MANAGEMENT_PLAN_REVIEW_ADDED_WITHOUT_REVIEWER = "20";

    String CMP_TASK_STATUS_COMPLETED_CODE = "4";

    String CMP_TASK_ACTION_LOG_CREATED    = "28";
    String CMP_TASK_ACTION_LOG_UPDATED    = "29";
    String CMP_TASK_ACTION_LOG_REASSIGNED = "30";
    String CMP_TASK_ACTION_LOG_STARTED    = "31";
    String CMP_TASK_ACTION_LOG_COMPLETED  = "32";
    String CMP_TASK_ACTION_LOG_DELETED    = "33";
    
}
