package com.polus.fibicomp.constants;

public interface TriggerTypes {

    String NOTIFY_DISCLOSURE_CREATION = "NOTIFY_DISCLOSURE_CREATION"; // Create project Disclosure or Intial or Revision Disclosure Notification
    String TRAVEL_DISCL_REIMBURSED_COST_LIMIT_EXCEEDED = "TRAVEL_REIMBU_COST_EXCEEDED";
    String NOTIFY_DISCLOSURE_SUBMISSION = "NOTIFY_DISCLOSURE_SUBMISSION";
    String OPA_ROUTELOG_APPROVE = "OPA_ROUTELOG_APPROVE";
    String OPA_ROUTELOG_BYPASSED = "OPA_ROUTELOG_BYPASSED";
    String NOTIFY_PROJECT_DISCLOSURE_EXPIRED = "NOTIFY_PROJECT_DISCLOSURE_EXPIRED";
    String NOTIFY_FCOI_DISCLOSURE_EXPIRED = "NOTIFY_FCOI_DISCLOSURE_EXPIRED";
    String NOTIFY_OPA_DISCLOSURE_EXPIRED = "NOTIFY_OPA_DISCLOSURE_EXPIRED";
    String NOTIFY_DECLARATION_EXPIRED = "NOTIFY_DECLARATION_EXPIRED";
    String FCOI_ROUTELOG_APPROVE = "FCOI_ROUTELOG_APPROVE";
    String FCOI_ROUTELOG_BYPASSED = "FCOI_ROUTELOG_BYPASSED";
    String COI_DECLARATION_INTEGRATION = "COI_DECLARATION_INTEGRATION";
    String NOTIFY_PROJECT_DISCLOSURE_MARKED_AS_VOID = "NOTIFY_PROJECT_DISCLOSURE_MARKED_AS_VOID";
}
