CREATE TABLE COI_NOTIFICATION_LOG (
    NOTIFICATION_LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOTIFICATION_TYPE_ID INT,
    MODULE_ITEM_KEY VARCHAR(20),
    MODULE_SUB_ITEM_KEY VARCHAR(20),
    MODULE_CODE INT,
    SUBJECT VARCHAR(2000),
    MESSAGE LONGTEXT,
    SEND_DATE datetime,
    REQUESTED_BY VARCHAR(40),
    MESSAGE_ID VARCHAR(100),
    ACTION_TYPE VARCHAR(200)
);

CREATE TABLE COI_NOTIFICATION_LOG_RECIPIENT (
    NOTIFICATION_LOG_RECIPIENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOTIFICATION_LOG_ID INT,
    RECIPIENT_EMAIL_ID VARCHAR(200),
	RECIPIENT_PERSON_ID VARCHAR(40),
	ROLE_TYPE_CODE INT,
    CONSTRAINT COI_NOTIFICATION_LOG_RECIPIENT_FK1 
        FOREIGN KEY (NOTIFICATION_LOG_ID) 
        REFERENCES COI_NOTIFICATION_LOG (NOTIFICATION_LOG_ID)
        ON DELETE CASCADE
);
