
DROP TABLE IF EXISTS coi_project_comment_type;
CREATE TABLE coi_project_comment_type ( 
  COMMENT_TYPE_CODE varchar (3) NOT NULL, 
  DESCRIPTION VARCHAR (200) DEFAULT NULL, 
  IS_ACTIVE VARCHAR (1) DEFAULT NULL, 
  UPDATE_TIMESTAMP datetime DEFAULT NULL, 
  UPDATED_BY VARCHAR (60) DEFAULT NULL, 
  PRIMARY KEY (COMMENT_TYPE_CODE)
);

DROP TABLE IF EXISTS coi_project_comment;
CREATE TABLE coi_project_comment ( 
  COMMENT_ID INT NOT NULL AUTO_INCREMENT, 
  COMMENT_BY VARCHAR (40) NULL, 
  PARENT_COMMENT_ID INT NULL, 
  COMMENT LONGTEXT NULL, 
  COMMENT_TYPE_CODE VARCHAR (3) NULL, 
  IS_PRIVATE VARCHAR (1) NULL, 
  MODULE_CODE TINYINT NULL,	
  MODULE_ITEM_KEY VARCHAR (20) NULL, 	  
  UPDATED_BY VARCHAR (60) NULL, 
  UPDATE_TIMESTAMP DATETIME NULL, 
  PRIMARY KEY (COMMENT_ID), 
  CONSTRAINT COI_PROJECT_COMMENT_FK1 
  FOREIGN KEY (COMMENT_BY) 
  REFERENCES person (PERSON_ID),
  CONSTRAINT COI_PROJECT_COMMENT_FK2  
  FOREIGN KEY (COMMENT_TYPE_CODE)  
  REFERENCES COI_PROJECT_COMMENT_TYPE (COMMENT_TYPE_CODE)
);

DROP TABLE IF EXISTS sponsor_disclosure_requirements;
CREATE TABLE sponsor_disclosure_requirements (
  SPONSOR_CODE varchar(6) NOT NULL,
  KEY_PERSON_DISCL_REQUIREMENT varchar(10) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(40) DEFAULT NULL,
  PRIMARY KEY (SPONSOR_CODE),
  CONSTRAINT SPONSOR_DISCLOSURE_REQUIREMENTS_FK1 FOREIGN KEY (SPONSOR_CODE) REFERENCES sponsor (SPONSOR_CODE),
  CONSTRAINT CHK_KEY_PERSON_DISCL_REQUIREMENT CHECK (KEY_PERSON_DISCL_REQUIREMENT IN ('ALL', 'PI-COI'))
);

DROP TABLE IF EXISTS coi_int_stage_dev_proposal_status;
CREATE TABLE coi_int_stage_dev_proposal_status (
  STATUS_CODE int NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  PRIMARY KEY (STATUS_CODE)
);
