DROP PROCEDURE IF EXISTS COI_UPD_ANS_TO_NEW_QUEST_VERSN;
DROP PROCEDURE IF EXISTS COI_VALIDATE_DISCLOSURE_CONFLICTS;
DROP PROCEDURE IF EXISTS INSERT_OPA_DISCLOSURE_DETAILS;
DROP PROCEDURE IF EXISTS PROC_SYNC_OPA_PER_ENTITY;
DROP PROCEDURE IF EXISTS SYNC_SFIS_AND_DISCLOSURE;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP PROCEDURE IF EXISTS GET_PERSON_HAS_PERMISSION;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_RELATIONS;

DROP FUNCTION IF EXISTS FN_EVAL_DISCLOSURE_STATUS;

DROP VIEW IF EXISTS coi_project_proposal_status_v;

