\. ./FIBI-COI-5.6/FC-1115/Procedures/COI_COPY_GLOBAL_ENTITY.sql
\. ./FIBI-COI-5.6/FC-1115/Procedures/DUNS_REFRESH_ENTITY_HEADER.sql
\. ./FIBI-COI-5.6/FC-1115/Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_COUNT.sql
\. ./FIBI-COI-5.6/FC-1115/Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_DATA.sql
\. ./FIBI-COI-5.6/FC-1115/Procedures/VALIDATE_ENTITY_MANDATORY_FIELDS.sql
