SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS CITI_TRAINING_FEED_DETAILS (
  FEED_DETAIL_ID INT NOT NULL AUTO_INCREMENT,
  CURRICULUM_GRADEBOOK VARCHAR(255) DEFAULT NULL,
  `GROUP` VARCHAR(255) DEFAULT NULL,
  STAGE VARCHAR(255) DEFAULT NULL,
  STAGE_NUMBER INT DEFAULT NULL,
  CR_NUMBER VARCHAR(255) DEFAULT NULL,
  DATE_COMPLETED VARCHAR(255) DEFAULT NULL,
  EXPIRATION_DATE VARCHAR(255) DEFAULT NULL,
  LEARNER_ID VARCHAR(255) DEFAULT NULL,
  FIRST_NAME VARCHAR(255) DEFAULT NULL,
  LAST_NAME VARCHAR(255) DEFAULT NULL,
  USERNAME VARCHAR(255) DEFAULT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  CUSTOM_FIELD_1 VARCHAR(255) DEFAULT NULL,
  CUSTOM_FIELD_2 VARCHAR(255) DEFAULT NULL,
  MODULE VARCHAR(255) DEFAULT NULL,
  EXAM_ID VARCHAR(255) DEFAULT NULL,
  EXAM_SCORE INT DEFAULT NULL,
  PASSING_SCORE INT DEFAULT NULL,
  MODULE_COMPLETION_DATE VARCHAR(200) DEFAULT '',
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  PRIMARY KEY (FEED_DETAIL_ID)
);

-- ALTER TABLE CITI_TRAINING_FEED_DETAILS 
-- ADD COLUMN STAGE_NUMBER INT NULL DEFAULT NULL AFTER UPDATE_TIMESTAMP,
-- ADD COLUMN CUSTOM_FIELD_2 VARCHAR(255) NULL DEFAULT NULL AFTER STAGE_NUMBER,
-- ADD COLUMN PASSING_SCORE INT NULL DEFAULT NULL AFTER CUSTOM_FIELD_2;



CREATE TABLE IF NOT EXISTS CITI_TRAINING_FEED_INFO (
  FEED_INFO_ID INT NOT NULL AUTO_INCREMENT,
  FILE_NAME VARCHAR(255) DEFAULT NULL,
  FILE_TYPE VARCHAR(255) DEFAULT NULL,
  FEED_START_TIME DATETIME DEFAULT NULL,
  FEED_END_TIME DATETIME DEFAULT NULL,
  NO_OF_RECORDS INT DEFAULT NULL,
  NO_OF_FAILED_RECORDS INT DEFAULT NULL,
  FEED_TYPE VARCHAR(255) DEFAULT NULL,
  FEED_STATUS VARCHAR(255) DEFAULT NULL,
  UPDATED_TIMESTAMP DATETIME DEFAULT NULL,
  CREATED_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  COMMENT VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (FEED_INFO_ID)
);

CREATE TABLE IF NOT EXISTS CITI_TRAINING_FEED_EXCEPTION (
  FEED_EXCEPTION_ID INT NOT NULL AUTO_INCREMENT,
  ERROR_CODE VARCHAR(255) DEFAULT NULL,
  ERROR_MESSAGE VARCHAR(255) DEFAULT NULL,
  STACK_TRACE BLOB,
  ERROR_TYPE VARCHAR(255) DEFAULT NULL,
  ERROR_AT VARCHAR(255) DEFAULT NULL,
  FEED_INFO_ID INT DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (FEED_EXCEPTION_ID)
);

CREATE TABLE IF NOT EXISTS CITI_TRAINING_FEED_CONFIG (
  CONFIGURATION_KEY VARCHAR(255) NOT NULL,
  CONFIGURATION_VALUE VARCHAR(255) DEFAULT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (CONFIGURATION_KEY)
);

/* Not needed in instances with FIBI
CREATE TABLE SOURCE_TYPE (
  SOURCE_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(100) DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  PRIMARY KEY (SOURCE_TYPE_CODE)
);
*/

CREATE TABLE IF NOT EXISTS PERSON_TRAINING_EXT (
  PERSON_TRAINING_EXT_ID int NOT NULL AUTO_INCREMENT,
  PERSON_TRAINING_ID int DEFAULT NULL,
  CERTIFICATION_NAME varchar(600) DEFAULT NULL,
  INSTITUTION_NAME varchar(200) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  IS_HIGHLIGHTED varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SOURCE_TYPE_CODE varchar(3) DEFAULT NULL,
  STATUS varchar(1) DEFAULT NULL,
  ATTACHMENT_STATUS varchar(1) DEFAULT NULL,
  DESCRIPTION varchar(2000) DEFAULT NULL,
  URL varchar(400) DEFAULT NULL,
  PRIMARY KEY (PERSON_TRAINING_EXT_ID),
  KEY PERSON_TRAINING_EXT_FK1 (PERSON_TRAINING_ID),
  KEY PERSON_TRAINING_EXT_FK2 (SOURCE_TYPE_CODE),
  CONSTRAINT PERSON_TRAINING_EXT_FK1 FOREIGN KEY (PERSON_TRAINING_ID) REFERENCES PERSON_TRAINING (PERSON_TRAINING_ID),
  CONSTRAINT PERSON_TRAINING_EXT_FK2 FOREIGN KEY (SOURCE_TYPE_CODE) REFERENCES SOURCE_TYPE (SOURCE_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS TRAINING
   (TRAINING_CODE INT PRIMARY KEY, 
	DESCRIPTION VARCHAR(200) NOT NULL, 
	UPDATE_TIMESTAMP DATETIME NOT NULL, 
	UPDATE_USER VARCHAR(60) NOT NULL);

CREATE TABLE IF NOT EXISTS TRAINING_MODULES 
   (TRAINING_MODULES_ID INT, 
	TRAINING_CODE INT, 
	MODULE_CODE INT NOT NULL, 
	SUB_MODULE_CODE INT, 
	DESCRIPTION VARCHAR(200) NOT NULL, 
	UPDATE_TIMESTAMP DATETIME NOT NULL, 
	UPDATE_USER VARCHAR(60) NOT NULL);

CREATE INDEX PERSON_TRAINING_IDX
ON PERSON_TRAINING (PERSON_ID, TRAINING_CODE, DATE_SUBMITTED, FOLLOWUP_DATE, SCORE);

SET FOREIGN_KEY_CHECKS = 1;

