DROP FUNCTION IF EXISTS FN_RULE_BUILD_WORKFLOW;
DROP FUNCTION IF EXISTS FN_WORKFLOW_APPROVE;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_EXPRESSION;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_FUNCTION;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_WORKFLOW;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
DROP FUNCTION IF EXISTS FN_FOR_ALL_OPA;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
