DROP TABLE IF EXISTS DISCL_ATTACHMENT;
CREATE TABLE DISCL_ATTACHMENT (
ATTACHMENT_ID INT NOT NULL AUTO_INCREMENT, 
ATTACHMENT_NUMBER INT NULL, 
VERSION_NUMBER INT NULL, 
DISCLOSURE_ID INT NULL, 
DESCRIPTION VARCHAR(500) NULL, 
ATTACHMENT_TYPE_CODE VARCHAR(3) NULL, 
FILE_NAME VARCHAR(200) NULL, 
MIME_TYPE VARCHAR(255) NULL, 
FILE_DATA_ID VARCHAR(100) NULL, 
CREATE_TIMESTAMP DATETIME NULL DEFAULT NULL, 
CREATE_USER VARCHAR(60) NULL DEFAULT NULL, 
UPDATE_TIMESTAMP DATETIME NULL DEFAULT NULL, 
UPDATE_USER VARCHAR(60) NULL DEFAULT NULL, 
PRIMARY KEY (ATTACHMENT_ID), 
INDEX DISCL_ATTACHMENT_FK1_idx (DISCLOSURE_ID ASC) VISIBLE, 
INDEX DISCL_ATTACHMENT_FK2_idx (ATTACHMENT_TYPE_CODE ASC) VISIBLE, 
CONSTRAINT DISCL_ATTACHMENT_FK1 
FOREIGN KEY (DISCLOSURE_ID) 
REFERENCES COI_DISCLOSURE (DISCLOSURE_ID) , 
CONSTRAINT DISCL_ATTACHMENT_FK2 
FOREIGN KEY (ATTACHMENT_TYPE_CODE) 
REFERENCES DISCL_ATTA_TYPE (ATTA_TYPE_CODE) 
); 


DROP TABLE IF EXISTS DISCL_FILE_DATA;
CREATE TABLE DISCL_FILE_DATA ( 
FILE_DATA_ID varchar(100), 
MODULE_CODE VARCHAR(3) DEFAULT NULL, 
SUB_MODULE_CODE VARCHAR(3) DEFAULT NULL, 
FILE_PATH varchar(255), 
ORIGINAL_FILE_NAME varchar(500), 
FILE_NAME VARCHAR(200), 
IS_ARCHIVED char(1), 
FILE longblob, 
UPDATE_TIMESTAMP DATETIME, 
UPDATE_USER varchar(60), 
PRIMARY KEY (FILE_DATA_ID) 
); 
