RENAME TABLE discl_attachment TO review_attachment;

RENAME TABLE discl_file_data TO person_file_data;

ALTER TABLE review_attachment 
DROP FOREIGN KEY  DISCL_ATTACHMENT_FK1;
ALTER TABLE review_attachment 
DROP FOREIGN KEY  DISCL_ATTACHMENT_FK2;
ALTER TABLE review_attachment 
DROP FOREIGN KEY  DISCL_ATTACHMENT_FK3;
ALTER TABLE review_attachment 
DROP FOREIGN KEY  DISCL_ATTACHMENT_FK4;


ALTER TABLE review_attachment 
ADD CONSTRAINT REVIEW_ATTACHMENT_FK1 FOREIGN KEY (COMMENT_ID) REFERENCES discl_comment(COMMENT_ID);
ALTER TABLE review_attachment 
ADD CONSTRAINT REVIEW_ATTACHMENT_FK2 FOREIGN KEY (COMPONENT_TYPE_CODE) REFERENCES discl_component_type(COMPONENT_TYPE_CODE);
ALTER TABLE review_attachment 
ADD CONSTRAINT REVIEW_ATTACHMENT_FK3 FOREIGN KEY (ATTA_TYPE_CODE) REFERENCES discl_atta_type(ATTA_TYPE_CODE);
ALTER TABLE review_attachment 
ADD CONSTRAINT REVIEW_ATTACHMENT_FK4 FOREIGN KEY (ATTA_STATUS_CODE) REFERENCES discl_atta_status(ATTA_STATUS_CODE);

ALTER TABLE REVIEW_ATTACHMENT RENAME INDEX DISCL_ATTACHMENT_FK1_idx TO REVIEW_ATTACHMENT_FK1_idx;
ALTER TABLE REVIEW_ATTACHMENT RENAME INDEX DISCL_ATTACHMENT_FK2_idx TO REVIEW_ATTACHMENT_FK2_idx;
ALTER TABLE REVIEW_ATTACHMENT RENAME INDEX DISCL_ATTACHMENT_FK3_idx TO REVIEW_ATTACHMENT_FK3_idx;
ALTER TABLE REVIEW_ATTACHMENT RENAME INDEX DISCL_ATTACHMENT_FK4_idx TO REVIEW_ATTACHMENT_FK4_idx;

ALTER TABLE PERSON_FILE_DATA
ADD COLUMN SUB_MODULE_CODE VARCHAR(3) DEFAULT NULL AFTER MODULE_CODE;
