INSERT INTO BUSINESS_RULE_FUNCTION (`FUNCTION_NAME`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`DB_FUNCTION_NAME`,`UPDATE_TIMESTAMP`,`UPDATE_USER`)
VALUES ('For All OPAs',23,0,NULL,'FN_FOR_ALL_OPA',NOW(),'ADMIN');

INSERT INTO `OPA_REVIEW_STATUS_TYPE` (`REVIEW_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `SORT_ORDER`)
VALUES ('9', 'Routing in progress', 'Y', NOW(), 'quickstart', '9');

INSERT INTO BUSINESS_RULE_FUNCTION_ARG (FUNCTION_NAME, ARGUMENT_SEQUENCE_NUMBER, ARGUMENT_NAME, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES ('For All OPAs', '1', 'AV_OPA_ID', 'Check with OPA disclosure id', now(), 'admin');
