SET SQL_SAFE_UPDATES = 0;
UPDATE `notification_type` SET `SENT_TO_INITIATOR` = 'N' WHERE (`NOTIFICATION_TYPE_ID` = '8069');
UPDATE `notification_type` SET `SENT_TO_INITIATOR` = 'N' WHERE (`NOTIFICATION_TYPE_ID` = '8070');
UPDATE `notification_type` SET `SENT_TO_INITIATOR` = 'N' WHERE (`NOTIFICATION_TYPE_ID` = '8071');
UPDATE `notification_type` SET `SENT_TO_INITIATOR` = 'N' WHERE (`NOTIFICATION_TYPE_ID` = '8075');
UPDATE `notification_type` SET `SENT_TO_INITIATOR` = 'N' WHERE (`NOTIFICATION_TYPE_ID` = '8095');

UPDATE `notification_type` SET `IS_ACTIVE` = 'N' WHERE (`NOTIFICATION_TYPE_ID` = '8006');
SET SQL_SAFE_UPDATES = 1;
