\. ./FIBI-COI-5.5.1/FC-1342/Procedures/BULK_UPDATE_GLOBAL_ENTITY_FOREIGN_FLAG.sql
\. ./FIBI-COI-5.5.1/FC-1342/Procedures/COI_COPY_GLOBAL_ENTITY.sql
\. ./FIBI-COI-5.5.1/FC-1342/Procedures/ENRICH_ENTITY_CORPORATE_LINKAGE.sql
\. ./FIBI-COI-5.5.1/FC-1342/Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_DATA.sql
\. ./FIBI-COI-5.5.1/FC-1342/Procedures/GET_ENTITY_HIERARCHY.sql
\. ./FIBI-COI-5.5.1/FC-1342/Procedures/UPDATE_GLOBAL_ENTITY_FOREIGN_FLAG.sql
