ALTER TABLE ENTITY_FAMILY_TREE
ADD COLUMN ENTITY_NUMBER INT NULL,
ADD COLUMN PARENT_ENTITY_NUMBER INT NULL,
ADD COLUMN IS_SYSTEM_CREATED VARCHAR(1) NULL;

ALTER TABLE ENTITY_FAMILY_TREE
DROP FOREIGN KEY ENTITY_FAMILY_TREE_FK2,
DROP FOREIGN KEY ENTITY_FAMILY_TREE_FK1;
ALTER TABLE ENTITY_FAMILY_TREE
DROP COLUMN GLOBAL_ULTIMATE_ENTITY_ID,
DROP COLUMN PARENT_ENTITY_ID,
DROP COLUMN ENTITY_ID, ADD COLUMN GLOBAL_ULTIMATE_ENTITY_NUMBER INT NULL AFTER IS_SYSTEM_CREATED,
DROP INDEX ENTITY_FAMILY_TREE_FK2_idx ,
DROP INDEX ENTITY_FAMILY_TREE_FK1_idx ;

ALTER TABLE ENTITY_FAMILY_TREE_ROLE
DROP FOREIGN KEY ENTITY_FAMILY_TREE_ROLE_FK1;
ALTER TABLE ENTITY_FAMILY_TREE_ROLE CHANGE COLUMN ENTITY_ID ENTITY_NUMBER INT NULL DEFAULT NULL ,
DROP INDEX ENTITY_FAMILY_TREE_ROLE_FK1_idx ;

UPDATE `ENTITY_ACTION_TYPE` SET `MESSAGE` = 'Entity <b>created</b> as part of corporate family generation' WHERE (`ACTION_TYPE_CODE` = '21');
