Analyze table QUEST_QUESTION;
SET @sql := IF(
    (SELECT COUNT(*)
     FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() 
       AND TABLE_NAME = 'QUEST_QUESTION' 
       AND COLUMN_NAME = 'IS_MANDATORY') = 0,
    'ALTER TABLE QUEST_QUESTION ADD COLUMN IS_MANDATORY VARCHAR(1) DEFAULT ''N'';',
    'DO 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

Analyze table QUEST_QUESTION;
SET @sql := IF(
    (SELECT COUNT(*)
     FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() 
       AND TABLE_NAME = 'QUEST_QUESTION' 
       AND COLUMN_NAME = 'MANDATORY_MESSAGE') = 0,
    'ALTER TABLE QUEST_QUESTION ADD COLUMN MANDATORY_MESSAGE VARCHAR(2000) DEFAULT NULL;',
    'DO 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
 
UPDATE QUEST_QUESTION QQ 
JOIN QUEST_USAGE QU ON QQ.QUESTIONNAIRE_ID = QU.QUESTIONNAIRE_ID AND QU.IS_MANDATORY = 'Y' 
SET QQ.IS_MANDATORY = 'Y';
