DROP TABLE FIBI_COI_PERSON;

  CREATE TABLE "FIBI_COI_PERSON" 
   (	"PERSON_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(30 BYTE), 
	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"MIDDLE_NAME" VARCHAR2(30 BYTE), 
	"FULL_NAME" VARCHAR2(90 BYTE), 
	"PRIOR_NAME" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(60 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(60 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"AGE" NUMBER, 
	"AGE_BY_FISCAL_YEAR" NUMBER, 
	"GENDER" VARCHAR2(30 BYTE), 
	"EDUCATION_LEVEL" VARCHAR2(30 BYTE), 
	"OFFICE_LOCATION" VARCHAR2(30 BYTE), 
	"OFFICE_PHONE" VARCHAR2(20 BYTE), 
	"SECONDRY_OFFICE_LOCATION" VARCHAR2(30 BYTE), 
	"SECONDRY_OFFICE_PHONE" VARCHAR2(20 BYTE), 
	"SCHOOL" VARCHAR2(50 BYTE), 
	"DIRECTORY_DEPARTMENT" VARCHAR2(30 BYTE), 
	"SALUTATION" VARCHAR2(30 BYTE), 
	"COUNTRY_OF_CITIZENSHIP" VARCHAR2(30 BYTE), 
	"PRIMARY_TITLE" VARCHAR2(51 BYTE), 
	"DIRECTORY_TITLE" VARCHAR2(50 BYTE), 
	"HOME_UNIT" VARCHAR2(8 BYTE), 
	"IS_FACULTY" CHAR(1 BYTE), 
	"IS_GRADUATE_STUDENT_STAFF" CHAR(1 BYTE), 
	"IS_RESEARCH_STAFF" CHAR(1 BYTE), 
	"IS_SERVICE_STAFF" CHAR(1 BYTE), 
	"IS_SUPPORT_STAFF" CHAR(1 BYTE), 
	"IS_OTHER_ACCADEMIC_GROUP" CHAR(1 BYTE), 
	"IS_MEDICAL_STAFF" CHAR(1 BYTE), 
	"ADDRESS_LINE_1" VARCHAR2(80 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(80 BYTE), 
	"ADDRESS_LINE_3" VARCHAR2(80 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"COUNTY" VARCHAR2(30 BYTE), 
	"STATE" VARCHAR2(30 BYTE), 
	"POSTAL_CODE" VARCHAR2(15 BYTE), 
	"COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"FAX_NUMBER" VARCHAR2(20 BYTE), 
	"PAGER_NUMBER" VARCHAR2(20 BYTE), 
	"MOBILE_PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"VISA_CODE" VARCHAR2(20 BYTE), 
	"VISA_TYPE" VARCHAR2(30 BYTE), 
	"VISA_RENEWAL_DATE" DATE, 
	"STATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
	"SALARY_ANNIVERSARY_DATE" DATE, 
	"UPDATE_TIMESTAMP" DATE, 
	"UPDATE_USER" VARCHAR2(60 BYTE), 
	"SYNC_STATUS" VARCHAR2(500 BYTE), 
	 CONSTRAINT "PK_FIBI_COI_PERSON" PRIMARY KEY ("PERSON_ID")
   ) ;
 


 


 

