DROP PROCEDURE IF EXISTS GET_COI_TRAVEL_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_DECLARATION_DASHBOARD_DYNAMIC_DATA;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_OPA_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
DROP FUNCTION IF EXISTS FN_PERSON_HAS_RIGHTS;
DROP FUNCTION IF EXISTS FN_CHK_IS_HOME_UNIT_SUBMISSION;
