\. ./FIBI-COI-5.8.4/FC-1681/Procedures/GET_COI_TRAVEL_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./FIBI-COI-5.8.4/FC-1681/Procedures/GET_DECLARATION_DASHBOARD_DYNAMIC_DATA.sql
\. ./FIBI-COI-5.8.4/FC-1681/Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./FIBI-COI-5.8.4/FC-1681/Procedures/GET_COI_OPA_DASHBOARD.sql
\. ./FIBI-COI-5.8.4/FC-1681/Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./FIBI-COI-5.8.4/FC-1681/Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
\. ./FIBI-COI-5.8.4/FC-1681/Functions/FN_PERSON_HAS_RIGHTS.sql
\. ./FIBI-COI-5.8.4/FC-1681/Functions/FN_CHK_IS_HOME_UNIT_SUBMISSION.sql
