DELIMITER //
CREATE PROCEDURE `GET_MIG_ENG_ENTITY`(AV_ENG_ID INT)
BEGIN
    DECLARE LS_ENTITY_NAME VARCHAR(60) DEFAULT '';
	DECLARE LS_CLEANED VARCHAR(60);
	DECLARE FILTER_CONDITION TEXT;
    DECLARE LS_DYN_SQL TEXT;
    DECLARE LS_FIRST_WORD VARCHAR(60) DEFAULT '';

    SELECT LOWER(TRIM(ENTITY_NAME)) INTO LS_ENTITY_NAME
    FROM LEGACY_COI_ENGAGEMENTS
    WHERE ENGAGEMENT_ID = AV_ENG_ID;

	SET LS_ENTITY_NAME = REPLACE(LS_ENTITY_NAME, '''', '''''');
    SET LS_CLEANED = LS_ENTITY_NAME;

    -- Remove join, stop words and symbols (space padded to match whole word)
    SET LS_CLEANED = REPLACE(CONCAT(' ', LS_CLEANED, ' '), ' the ', ' ');
    SET LS_CLEANED = REPLACE(LS_CLEANED, ' a ', ' ');
    SET LS_CLEANED = REPLACE(LS_CLEANED, ' an ', ' ');
    SET LS_CLEANED = REPLACE(LS_CLEANED, ' of ', ' ');
    SET LS_CLEANED = REPLACE(LS_CLEANED, ' and ', ' ');
    SET LS_CLEANED = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LS_CLEANED, '_', ' '), '''', ' '), '\\', ' '), ',', ' '), '.', ' '), '&', ' '), '-', ' '), '/', ' '), '(', ' '), ')', ' ');

    -- Normalize extra spaces
    WHILE INSTR(LS_CLEANED, '  ') > 0 DO
        SET LS_CLEANED = REPLACE(LS_CLEANED, '  ', ' ');
    END WHILE;

    -- Replace spaces with wildcards and add surrounding %
    SET LS_CLEANED = TRIM(LS_CLEANED);
    SET LS_FIRST_WORD = SUBSTRING_INDEX(LS_CLEANED, ' ', 1);
    SET LS_CLEANED = CONCAT('%', REPLACE(LS_CLEANED, ' ', '%'), '%');

	SET FILTER_CONDITION = CONCAT('LOWER(e.PRIMARY_NAME) LIKE ''', LS_CLEANED, ''' ');

    -- Main query
    SET LS_DYN_SQL = CONCAT('SELECT 
        e.ENTITY_ID,
        e.ENTITY_NUMBER,
        e.PRIMARY_NAME,
        e.PRIMARY_ADDRESS_LINE_1,
        e.PRIMARY_ADDRESS_LINE_2,
        e.CITY,
        e.STATE,
        c.COUNTRY_NAME,
        e.DUNS_NUMBER,
        e.UEI_NUMBER,
        o.ORGANIZATION_ID,
        s.SPONSOR_CODE,
        e.POST_CODE,
        e.CAGE_NUMBER,
        e.WEBSITE_ADDRESS,
        ow.DESCRIPTION AS OWNERSHIP_TYPE,
        b.DESCRIPTION AS BUSINESS_TYPE
    FROM ENTITY e
    INNER JOIN COUNTRY c ON c.COUNTRY_CODE = e.COUNTRY_CODE
    LEFT JOIN ENTITY_SUB_ORG_INFO o ON o.ENTITY_ID = e.ENTITY_ID
    LEFT JOIN ENTITY_SPONSOR_INFO s ON s.ENTITY_ID = e.ENTITY_ID
    LEFT JOIN ENTITY_OWNERSHIP_TYPE ow ON ow.OWNERSHIP_TYPE_CODE = e.ENTITY_OWNERSHIP_TYPE_CODE
    LEFT JOIN ENTITY_BUSINESS_TYPE b ON b.BUSINESS_TYPE_CODE = e.BUSINESS_TYPE_CODE
    WHERE e.ENTITY_STATUS_TYPE_CODE != 3
      AND e.VERSION_STATUS NOT IN (''ARCHIVE'', ''CANCELLED'')
      AND e.DOCUMENT_STATUS_TYPE_CODE NOT IN (''2'',''3'')
      AND (
            LOWER(TRIM(e.PRIMARY_NAME)) = ''', LS_ENTITY_NAME,''' 
			OR LOWER(TRIM(e.PRIMARY_NAME)) LIKE CONCAT(''%', LS_ENTITY_NAME, '%'') 
			OR ', FILTER_CONDITION, '
            OR LOWER(TRIM(e.PRIMARY_NAME)) REGEXP ''\\\\b', LS_FIRST_WORD, '\\\\b'' )
    ORDER BY 
		CASE 
			WHEN LOWER(TRIM(e.PRIMARY_NAME)) = ''', LS_ENTITY_NAME, ''' THEN 1
			WHEN LOWER(TRIM(e.PRIMARY_NAME)) LIKE CONCAT(''%', LS_ENTITY_NAME, '%'')  THEN 2
			WHEN ', FILTER_CONDITION, ' THEN 3
			WHEN LOWER(TRIM(e.PRIMARY_NAME)) REGEXP ''\\\\b', LS_FIRST_WORD, '\\\\b'' THEN 4
			ELSE 0
		END ASC,
		e.PRIMARY_NAME ASC
	LIMIT 20');

    SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
END
//
