\. ./FIBI-COI-5.1/FC-1048/Procedures/GET_ENTITY_MANDATORY_FIELDS.sql
\. ./FIBI-COI-5.1/FC-1048/Procedures/GET_ENTITY_TAB_STATUS.sql
\. ./FIBI-COI-5.1/FC-1048/Procedures/VALIDATE_ENTITY_MANDATORY_FIELDS.sql
\. ./FIBI-COI-5.1/FC-1048/Procedures/GET_COI_PROJECTS.sql
\. ./FIBI-COI-5.1/FC-1048/Procedures/COI_SYNC_FCOI_DISCLOSURE.sql
\. ./FIBI-COI-5.1/FC-1048/Procedures/COI_SYNC_INSERT_DISCL_PROJECTS.sql
\. ./FIBI-COI-5.1/FC-1048/Procedures/VALIDATE_PROJECT_DISCLOSURE.sql
\. ./FIBI-COI-5.1/FC-1048/Procedures/GET_PROJECT_OVERVIEW.sql
