DELIMITER //
CREATE FUNCTION `FN_IS_SABB_FILLED_IN_DISCL_ENG`(
    AV_OPA_DISCLOSURE_ID VARCHAR(100)
) RETURNS TINYINT(1)
    DETERMINISTIC
BEGIN

    DECLARE LS_IS_VALID BOOLEAN DEFAULT TRUE;

    SELECT
      CASE
        WHEN (D.IS_FALL_SABATICAL = 'Y' AND NOT EXISTS (
            SELECT 1
            FROM OPA_DISCL_PERSON_ENTITY_REL R
            WHERE R.DISCLOSURE_ID = D.OPA_DISCLOSURE_ID
              AND R.IS_FALL_SABATICAL = 'Y'
        )) THEN FALSE
        WHEN (D.IS_SPRING_SABATICAL = 'Y' AND NOT EXISTS (
            SELECT 1
            FROM OPA_DISCL_PERSON_ENTITY_REL R
            WHERE R.DISCLOSURE_ID = D.OPA_DISCLOSURE_ID
              AND R.IS_SPRING_SABATICAL = 'Y'
        )) THEN FALSE
        ELSE TRUE
      END AS IS_VALID into LS_IS_VALID
    FROM OPA_DISCLOSURE D
    WHERE D.OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;

   RETURN LS_IS_VALID;
END
//
