\. ./FIBI-COI-5.7.9/FC-1514/Procedures/GET_DECLARATION_DASHBOARD_DYNAMIC_DATA.sql
\. ./FIBI-COI-5.7.9/FC-1514/Procedures/GET_APPROVERS_FOR_ROLE_TYPE.sql
\. ./FIBI-COI-5.7.9/FC-1514/Procedures/GET_ALL_RIGHTS_FOR_A_MODULE.sql

\. ./FIBI-COI-5.7.9/FC-1514/Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
