INSERT IGNORE INTO entity_source_type (ENTITY_SOURCE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATED_BY) VALUES ('4','Compliance','Y',UTC_TIMESTAMP(),'admin');
INSERT IGNORE INTO entity_source_type (ENTITY_SOURCE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATED_BY) VALUES ('5','DST','Y',UTC_TIMESTAMP(),'admin');
INSERT IGNORE INTO entity_source_type (ENTITY_SOURCE_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATED_BY) VALUES ('6','Entity - Admin','Y',UTC_TIMESTAMP(),'admin');

SET SQL_SAFE_UPDATES= 0;
UPDATE entity_source_type
SET DESCRIPTION = 'COI - Reporter',
    UPDATE_TIMESTAMP = UTC_TIMESTAMP(),
    UPDATED_BY = 'admin'
WHERE ENTITY_SOURCE_TYPE_CODE = '3';
SET SQL_SAFE_UPDATES= 1;
