DELIMITER //
CREATE PROCEDURE `GET_MIG_ENG_MATRIX_ANS`(AV_ENG_ID INT, AV_IS_MATRIX_FILTERED BOOLEAN)
BEGIN
DECLARE LS_DYN_SQL TEXT;
DECLARE LS_JOIN_CONDITION VARCHAR(150) DEFAULT ' INNER JOIN LEGACY_COI_MATRIX_QUESTION T1 ON T1.MATRIX_QUESTION_ID = LCEMM.MATRIX_QUESTION_ID';
DECLARE LS_FILTER_CONDITION VARCHAR(250) DEFAULT '';

IF AV_IS_MATRIX_FILTERED THEN
	SET LS_JOIN_CONDITION = (' INNER JOIN PER_ENT_MATRIX_QUESTION T1 ON T1.MATRIX_QUESTION_ID = LCEMM.MATRIX_QUESTION_ID');
	SET LS_FILTER_CONDITION = (' AND LCEM.MATRIX_NAME IN (''INCOME_ROYALTY'', ''INCOME_BOARD_MEMBER'', ''INCOME_CONSULTING'', ''INCOME_EMPLOYEE'', ''INCOME_SPEAKING'')');
END IF;

SET LS_DYN_SQL = CONCAT(' SELECT 
		LCEM.ENTITY_MATRIX_ID,
		LCEMM.MATRIX_QUESTION_ID,
		CASE 
			WHEN T1.ANSWER_TYPE_CODE = 2 THEN LCEM.MATRIX_VALUE
			ELSE NULLIF(AVL.DESCRIPTION, ''None'')
		END AS MATRIX_VALUE,
		LCEM.RELATIONSHIP_TYPE_CODE,
		LCEM.UPDATE_TIMESTAMP,
		LCEM.UPDATE_USER,
        LCEM.COMMENTS
	FROM LEGACY_COI_ENTITY_MATRIX LCEM
	LEFT JOIN LEGACY_COI_ENT_MAT_MAPPING LCEMM ON LCEMM.MATRIX_NAME = LCEM.MATRIX_NAME
	', LS_JOIN_CONDITION,'
	LEFT JOIN ARG_VALUE_LOOKUP AVL ON AVL.ARGUMENT_NAME = T1.LOOKUP_VALUE AND LPAD(LCEM.MATRIX_VALUE, 8, ''0'') = AVL.ARGUMENT_VALUE
	WHERE LCEM.ENGAGEMENT_ID = ', AV_ENG_ID,
    LS_FILTER_CONDITION);

SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STATEMENT;
END
//
