SET @sql := IF ( 
   (SELECT COUNT(*) FROM information_schema.COLUMNS 
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_PROJ_CONFLICT_STATUS_TYPE' AND COLUMN_NAME = 'DEFAULT_CONFLICT_COMMENT') = 0, 
   'ALTER TABLE COI_PROJ_CONFLICT_STATUS_TYPE ADD COLUMN DEFAULT_CONFLICT_COMMENT VARCHAR(500) NULL AFTER IS_ACTIVE;', 
   'DO 1' 
); 
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

UPDATE CODE_TABLE_CONFIGURATION SET CONTENT = '{"group":"COI","codeTableName":"COI Disclosure Project Conflict Status","description":"List of all COI Disclosure Project Conflict Status","databaseTableName":"COI_PROJ_CONFLICT_STATUS_TYPE","fields": [{"columnName":"PROJECT_CONFLICT_STATUS_CODE","displayName":"Project Conflict Status Code","dataType":"String","isEditable": true,"length": 3,"canEmpty": false,"visible": true,"valueChanged": null,"index": null,"filterType": null,"valueField": null,"isTransient": null,"values": null,"refColumnName": null,"defaultValue": null},{"columnName":"DESCRIPTION","displayName":"Description","dataType":"String","isEditable":true,"length": 200,"canEmpty":true,"visible": true,"valueChanged": null,"index": null,"filterType": null,"valueField": null,"isTransient": null,"values": null,"refColumnName": null,"defaultValue": null},{"columnName": "DEFAULT_CONFLICT_COMMENT","displayName": "Default Conflict Comment","dataType": "String","isEditable": true,"length": 500,"canEmpty": true,"visible": true,"valueChanged": null,"index": null,"filterType": null,"valueField": null,"isTransient": null,"values": null,"refColumnName": null,"defaultValue": null},{"columnName": "UPDATE_TIMESTAMP","displayName": "Update Timestamp","dataType": "Date","isEditable": false,"length": null,"canEmpty": false,"visible": true,"valueChanged": null,"index": null,"filterType": null,"valueField": null,"isTransient": null,"values": null,"refColumnName": null,"defaultValue": null},{"columnName": "UPDATE_USER","displayName": "Update User","dataType": "String","isEditable": false,"length": 60,"canEmpty": false,"visible": true,"valueChanged": null,"index": null,"filterType": null,"valueField": null,"isTransient": null,"values": null,"refColumnName": "PERSON#USER_NAME","defaultValue": null},{"columnName": "IS_ACTIVE","displayName": "Active Flag","dataType": "String","isEditable": true,"length": 1,"canEmpty": false,"visible": true,"valueChanged": null,"index": null,"filterType": "switch","valueField": null,"isTransient": null,"values": null,"refColumnName": null,"defaultValue": null}],"primaryKey": ["PROJECT_CONFLICT_STATUS_CODE"    ],    "dependency": [{"displayName": "Coi Disclosure","table_name": "COI_DISCL_ENT_PROJ_DETAILS","columnName": "PROJECT_CONFLICT_STATUS_CODE"}],"actions": null}' WHERE (TABLE_NAME = 'COI_PROJ_CONFLICT_STATUS_TYPE');
