INSERT INTO coeus_sub_module(COEUS_SUB_MODULE_ID, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, REQUIRE_UNIQUE_QUESTIONNAIRE, IS_ACTIVE)
VALUES(2604,6,803,'COI pesron attachment',NOW(),'admin', 'N', 'Y');

INSERT INTO ATTACHMENT_NUMBER_COUNTER(counter_name, counter_value)
VALUES('DISCL_ATTACHMENT_COUNTER',1);

INSERT INTO RIGHTS(RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
VALUES((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A),'VIEW_DISCLOSURE_ATTACHMENT', 'To view disclosure attachment', 'quickstart', now(),1);

INSERT INTO RIGHTS(RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
VALUES((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A),'MANAGE_DISCLOSURE_ATTACHMENT', 'To manage disclosure attachment', 'quickstart', now(),1);
