\. ./FIBI-COI-5.0.8/Procedures/COI_INT_GET_ENTITY_DETAILS.sql
\. ./FIBI-COI-5.0.8/Procedures/GET_PROJECT_OVERVIEW.sql
\. ./FIBI-COI-5.0.8/Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
\. ./FIBI-COI-5.0.8/Procedures/COI_DISCL_GENERATE_JSON_PROJECT_SNAPSHOT.sql
\. ./FIBI-COI-5.0.8/Procedures/GET_DISCLOSURE_PROJECTS.sql
\. ./FIBI-COI-5.0.8/Procedures/GET_HEIR_PROJECT_DETAIL.sql
\. ./FIBI-COI-5.0.8/Procedures/GET_HEIR_PROJECT_TREE.sql
\. ./FIBI-COI-5.0.8/Procedures/GET_COI_PROJECTS.sql
\. ./FIBI-COI-5.0.8/Procedures/COI_INT_KC_SPON_ORG_RESPONSE.sql
\. ./FIBI-COI-5.0.8/Procedures/COI_SYNC_FCOI_DISCLOSURE.sql
\. ./FIBI-COI-5.0.8/Procedures/COI_SYNC_INSERT_DISCL_PROJECTS.sql
\. ./FIBI-COI-5.0.8/Procedures/GET_COI_DISCL_GENERAL_DETAILS.sql
\. ./FIBI-COI-5.0.8/Procedures/COI_SYNC_REMOVE_DEACTIVATED_PROJECTS.sql
\. ./FIBI-COI-5.0.8/Procedures/COI_SYNC_UPDATE_DISCL_INTEG_UPDATES.sql
\. ./FIBI-COI-5.0.8/Procedures/GET_COI_DISCLOSURE_HISTORY.sql
\. ./FIBI-COI-5.0.8/Procedures/VALIDATE_PROJECT_DISCLOSURE.sql
\. ./FIBI-COI-5.0.8/Procedures/COI_INT_PROP_PERSON_DISCL_STATUS.sql
\. ./FIBI-COI-5.0.8/Functions/COI_INT_PROP_DISCL_STATUS.sql
\. ./FIBI-COI-5.0.8/Functions/COI_INT_PRSN_DISCL_EXP_DATE.sql

-- \. ./FIBI-COI-5.0.8/Procedures/COI_INT_PROJECT_DISCL_STATUS.sql
\. ./FIBI-COI-5.0.8/Procedures/GET_COI_DISCL_REVIEW_DETAILS.sql
\. ./FIBI-COI-5.0.8/Procedures/COI_INT_PROJECT_PRSN_DISCL_STATUS.sql

-- \. ./FIBI-COI-5.0.8/IntegrationScripts/Procedures/FIBI_COI_FEED_ENTITY.sql
-- \. ./FIBI-COI-5.0.8/IntegrationScripts/Procedures/FIBI_COI_GET_AWARD.sql
-- \. ./FIBI-COI-5.0.8/IntegrationScripts/Procedures/FIBI_COI_GET_DEV_PROP_DTLS.sql
-- \. ./FIBI-COI-5.0.8/IntegrationScripts/Procedures/FIBI_COI_GET_INST_PROPOSAL.sql