INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
SELECT (SELECT IFNULL(MAX(RIGHT_ID), 0) + 1 FROM RIGHTS), 'MAINTAIN_OPA_REVIEWER', 'To enable managing reviewers in the OPA Reviewer tab', 'admin', NOW(), '2'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM RIGHTS WHERE RIGHT_NAME = 'MAINTAIN_OPA_REVIEWER');

INSERT IGNORE INTO parameter (`PARAMETER_NAME`, `VALUE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) 
VALUES ('ENABLE_ROUTELOG_USER_ADD_OPA_REVIEWER', 'Y', 'If value set to Y, enables route log users to add OPA reviewers to the document', now(), 'admin');
