ANALYZE TABLE COI_INT_STAGE_AWARD;

SET @SQL := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_INT_STAGE_AWARD' AND COLUMN_NAME = 'OVERALL_DISCLOSURE_STATUS') = 0,
     
    'ALTER TABLE COI_INT_STAGE_AWARD ADD COLUMN OVERALL_DISCLOSURE_STATUS VARCHAR(50) DEFAULT NULL;',
    
    'DO 1'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

ANALYZE TABLE COI_INT_STAGE_AWARD;

SET @SQL := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_INT_STAGE_AWARD' AND COLUMN_NAME = 'OVERALL_DISCL_REVIEW_STATUS') = 0,
     
    'ALTER TABLE COI_INT_STAGE_AWARD ADD COLUMN OVERALL_DISCL_REVIEW_STATUS VARCHAR(50) DEFAULT NULL;',
    
    'DO 1'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

ANALYZE TABLE COI_INT_STAGE_AWARD_PERSON;

SET @SQL := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_INT_STAGE_AWARD_PERSON' AND COLUMN_NAME = 'DISCLOSURE_STATUS') = 0,
     
    'ALTER TABLE COI_INT_STAGE_AWARD_PERSON ADD COLUMN DISCLOSURE_STATUS VARCHAR(50) DEFAULT NULL;',
    
    'DO 1'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

ANALYZE TABLE COI_INT_STAGE_AWARD_PERSON;

SET @SQL := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_INT_STAGE_AWARD_PERSON' AND COLUMN_NAME = 'DISCLOSURE_REVIEW_STATUS') = 0,
     
    'ALTER TABLE COI_INT_STAGE_AWARD_PERSON ADD COLUMN DISCLOSURE_REVIEW_STATUS VARCHAR(50) DEFAULT NULL;',
    
    'DO 1'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

ANALYZE TABLE COI_INT_STAGE_AWARD_PERSON;

SET @SQL := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_INT_STAGE_AWARD_PERSON' AND COLUMN_NAME = 'MAX_DISCLOSURE_ID') = 0,
     
    'ALTER TABLE COI_INT_STAGE_AWARD_PERSON ADD COLUMN MAX_DISCLOSURE_ID INT DEFAULT NULL;',
    
    'DO 1'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;


ANALYZE TABLE COI_INT_STAGE_DEV_PROPOSAL;

SET @SQL := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_INT_STAGE_DEV_PROPOSAL' AND COLUMN_NAME = 'OVERALL_DISCLOSURE_STATUS') = 0,
     
    'ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL ADD COLUMN OVERALL_DISCLOSURE_STATUS VARCHAR(50) DEFAULT NULL;',
    
    'DO 1'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

ANALYZE TABLE COI_INT_STAGE_DEV_PROPOSAL;

SET @SQL := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_INT_STAGE_DEV_PROPOSAL' AND COLUMN_NAME = 'OVERALL_DISCL_REVIEW_STATUS') = 0,
     
    'ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL ADD COLUMN OVERALL_DISCL_REVIEW_STATUS VARCHAR(50) DEFAULT NULL;',
    
    'DO 1'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

ANALYZE TABLE COI_INT_STAGE_DEV_PROPOSAL;

SET @SQL := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_INT_STAGE_DEV_PROPOSAL' AND COLUMN_NAME = 'DISCLOSURE_STATUS') = 0,
     
    'ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL ADD COLUMN DISCLOSURE_STATUS VARCHAR(50) DEFAULT NULL;',
    
    'DO 1'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

ANALYZE TABLE COI_INT_STAGE_DEV_PROPOSAL;

SET @SQL := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_INT_STAGE_DEV_PROPOSAL' AND COLUMN_NAME = 'DISCLOSURE_REVIEW_STATUS') = 0,
     
    'ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL ADD COLUMN DISCLOSURE_REVIEW_STATUS VARCHAR(50) DEFAULT NULL;',
    
    'DO 1'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;
