DROP TABLE IF EXISTS NOTIFY_PLACEHOLDER_COLUMNS;
DROP TABLE IF EXISTS NOTIFY_PLACEHOLDER_HEADER;
DROP TABLE IF EXISTS NOTIFY_MSG_BODY_PREDEFINED_OBJ;
DROP TABLE IF EXISTS NOTIFY_ACTION_TYPE_MAP;
DROP TABLE IF EXISTS MODULE_ACTION_TYPE;

DROP PROCEDURE IF EXISTS GET_COI_DISCL_REVIEW_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_DISCL_GENERAL_DETAILS;
DROP PROCEDURE IF EXISTS GET_APPROVERS_FOR_ROLE_TYPE;

DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_TRAVEL_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_PROJECTS;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_RELATIONS;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP FUNCTION IF EXISTS FN_INT_CAN_CREATE_PROP_DISCL;

DROP VIEW IF EXISTS coi_project_proposal_status_v;
DROP VIEW IF EXISTS coi_project_proposal_qnr_ans_v;
DROP VIEW IF EXISTS coi_project_institute_proposal_v;
DROP VIEW IF EXISTS coi_project_proposal_v;
DROP VIEW IF EXISTS coi_project_award_v;
