ALTER TABLE PERSON ADD COLUMN ALIAS_NAME VARCHAR (30) DEFAULT NULL;
ALTER TABLE PERSON ADD COLUMN GENDER_CODE varchar(3) DEFAULT NULL;
ALTER TABLE PERSON ADD COLUMN ALTERNATE_MOBILE_NUMBER varchar(20) DEFAULT NULL;
ALTER TABLE PERSON ADD COLUMN SECONDARY_EMAIL_ADDRESS varchar(60) DEFAULT NULL;

CREATE TABLE `GENDER` (
  `GENDER_CODE` VARCHAR(3) NOT NULL,
  `GENDER_NAME` VARCHAR(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` DATETIME DEFAULT NULL,
  `UPDATE_USER` VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (`GENDER_CODE`)
);
 
ALTER TABLE GENDER RENAME COLUMN GENDER_NAME TO DESCRIPTION;
 
INSERT INTO `gender` (`GENDER_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('F','Female',now(),'admin');
INSERT INTO `gender` (`GENDER_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('M','Male',now(),'admin');

ALTER TABLE PERSON ADD KEY `PERSON_FK2` (`GENDER_CODE`);
ALTER TABLE PERSON ADD FOREIGN KEY (GENDER_CODE) REFERENCES GENDER(GENDER_CODE);
 
UPDATE person AS t1
SET t1.GENDER_CODE = (
    SELECT t2.GENDER_CODE
    FROM gender AS t2
    WHERE LOWER(t2.DESCRIPTION) = LOWER(t1.GENDER)
)
WHERE GENDER_CODE is null;
 
 
ALTER TABLE UNIT RENAME COLUMN ACTIVE_FLAG TO IS_ACTIVE;
ALTER TABLE UNIT_LEVEL RENAME COLUMN ACTIVE_FLAG TO IS_ACTIVE;
ALTER TABLE ROLODEX RENAME COLUMN ACTV_IND TO IS_ACTIVE;
ALTER TABLE SPONSOR RENAME COLUMN ACTV_IND TO IS_ACTIVE;

ALTER TABLE PERSON ADD COLUMN IS_MFA_ENABLED varchar(1) DEFAULT NULL, ADD COLUMN SECRET varchar(100) DEFAULT NULL;

ALTER TABLE SPONSOR ADD COLUMN CITY  VARCHAR(200);

CREATE TABLE `MQ_ROUTER_TRIGGER_CONFIGURATION` (
  `MQ_ROUTER_TRIGGER_CONFIG_ID` int NOT NULL AUTO_INCREMENT,
  `TRIGGER_TYPE` varchar(255) DEFAULT NULL,
  `IS_ACTIVE` varchar(255) DEFAULT NULL,
  `QUEUE_NAME` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`MQ_ROUTER_TRIGGER_CONFIG_ID`)
);

CREATE TABLE `MQ_ROUTER_ACTION_CONFIGURATION` (
  `MQ_ROUTER_ACTION_CONFIG_ID` INT NOT NULL AUTO_INCREMENT,
  `ACTION_TYPE` VARCHAR(255) DEFAULT NULL,
  `IS_ACTIVE` VARCHAR(1) DEFAULT NULL,
  `MODULE_CODE` INT DEFAULT NULL,
  `QUEUE_NAME` VARCHAR(255) DEFAULT NULL,
  `SUB_MODULE_CODE` INT DEFAULT NULL,
  `UPDATE_TIMESTAMP` DATETIME(6) DEFAULT NULL,
  `UPDATE_USER` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`MQ_ROUTER_ACTION_CONFIG_ID`));

CREATE TABLE `MQ_EXCEPTION_LOG` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ACTION_TYPE` VARCHAR(25) DEFAULT NULL,
  `ERROR_CODE` VARCHAR(10) DEFAULT NULL,
  `ERROR_MESSAGE` VARCHAR(255) DEFAULT NULL,
  `MESSAGE_ID` VARCHAR(100) NOT NULL,
  `MODULE_CODE` INT DEFAULT NULL,
  `QUEUE_EXCHANGE` VARCHAR(60) DEFAULT NULL,
  `QUEUE_MESSAGE` TEXT NOT NULL,
  `SOURCE_QUEUE_NAME` VARCHAR(60) DEFAULT NULL,
  `DESTINATION_QUEUE_NAME` VARCHAR(60) DEFAULT NULL,
  `STACK_TRACE` TEXT,
  `SUB_MODULE_CODE` INT DEFAULT NULL,
  `UPDATE_TIMESTAMP` DATETIME DEFAULT NULL,
  `UPDATE_USER` VARCHAR(60) DEFAULT NULL,
  `USER_TYPE` VARCHAR(3) DEFAULT 'S',
  `EVENT_TYPE` VARCHAR(3) DEFAULT NULL,
  `TRIGGER_TYPE` VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);


DROP PROCEDURE IF EXISTS GET_UNIT_BASED_PERSON_AND_RIGHT;
DROP PROCEDURE IF EXISTS GET_UNIT_HIERARCHY;
\. ./Procedures/GET_UNIT_BASED_PERSON_AND_RIGHT.sql
\. ./Procedures/GET_UNIT_HIERARCHY.sql
