DROP PROCEDURE IF EXISTS GET_TRAVEL_DETAILS_OF_ENGAGEMENT;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
DROP FUNCTION IF EXISTS FN_CHK_MATRIX_COMPLETED;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_FUNCTION;
