-- Migration matrix mapping data.
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'INCOME_ROYALTY', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'STOCK_ANY_EQUITY', '2', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('4', 'INCOME_BOARD_MEMBER', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('5', 'INCOME_CONSULTING', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('6', 'INCOME_EMPLOYEE', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('7', 'INCOME_SPEAKING', '1', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'STOCK_COMMON', '2', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('9', 'STOCK_OPTIONS', '2', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('8', 'STOCK_OTHER', '2', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('10', 'OTHER_GOODS', '3', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('12', 'OTHER_SUB', '3', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('11', 'OTHER_GIFTS', '3', UTC_TIMESTAMP(), 'admin');
INSERT INTO `LEGACY_COI_ENT_MAT_MAPPING` (`MATRIX_QUESTION_ID`, `MATRIX_NAME`, `DATA_GROUP_ID`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('13', 'OTHER', '3', UTC_TIMESTAMP(), 'admin');
