INSERT INTO AGREEMENT_ATTACHMENT_TYPE (AGREEMENT_ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Draft Agreement',NOW(),'fibi_admin','Y');
INSERT INTO AGREEMENT_ATTACHMENT_TYPE (AGREEMENT_ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Final Agreement',NOW(),'fibi_admin','Y');
INSERT INTO AGREEMENT_ATTACHMENT_TYPE (AGREEMENT_ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Other Attachments',NOW(),'fibi_admin','Y');
INSERT INTO AGREEMENT_ATTACHMENT_TYPE (AGREEMENT_ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Generated Agreement',NOW(),'fibi_admin','Y');
INSERT INTO AGREEMENT_ATTACHMENT_TYPE (AGREEMENT_ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('8','ESignature Attachments',NOW(),'fibi_admin','Y');
