INSERT INTO BUDGET_CATEGORY_TYPE  (BUDGET_CATEGORY_TYPE_CODE,DESCRIPTION,SORT_ID,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('E','Equipment',2,NOW(),'fibi_admin');
INSERT INTO BUDGET_CATEGORY_TYPE  (BUDGET_CATEGORY_TYPE_CODE,DESCRIPTION,SORT_ID,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('H','Proposal Hierarchy Sub-Projects',6,NOW(),'fibi_admin');
INSERT INTO BUDGET_CATEGORY_TYPE  (BUDGET_CATEGORY_TYPE_CODE,DESCRIPTION,SORT_ID,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('N','Summary Items',7,NOW(),'fibi_admin');
INSERT INTO BUDGET_CATEGORY_TYPE  (BUDGET_CATEGORY_TYPE_CODE,DESCRIPTION,SORT_ID,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('O','Other Direct',5,NOW(),'fibi_admin');
INSERT INTO BUDGET_CATEGORY_TYPE  (BUDGET_CATEGORY_TYPE_CODE,DESCRIPTION,SORT_ID,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('P','Personnel',1,NOW(),'fibi_admin');
INSERT INTO BUDGET_CATEGORY_TYPE  (BUDGET_CATEGORY_TYPE_CODE,DESCRIPTION,SORT_ID,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('S','Participant Support',4,NOW(),'fibi_admin');
INSERT INTO BUDGET_CATEGORY_TYPE  (BUDGET_CATEGORY_TYPE_CODE,DESCRIPTION,SORT_ID,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('T','Travel',3,NOW(),'fibi_admin');
