INSERT INTO BUDGET_TEMPLATE_TYPE  (BUDGET_TEMPLATE_TYPE_ID,DESCRIPTION,MODULE_CODE,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Budget Template 1',3,'Y',NOW(),'fibi_admin');
INSERT INTO BUDGET_TEMPLATE_TYPE  (BUDGET_TEMPLATE_TYPE_ID,DESCRIPTION,MODULE_CODE,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Budget Template 1',1,'Y',NOW(),'fibi_admin');
INSERT INTO BUDGET_TEMPLATE_TYPE  (BUDGET_TEMPLATE_TYPE_ID,DESCRIPTION,MODULE_CODE,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'Student Research Budget',3,'Y',NOW(),'fibi_admin');
