INSERT INTO COI_REVIEW_STATUS_TYPE  (REVIEW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Pending','Y',NOW(),'fibi_admin');
INSERT INTO COI_REVIEW_STATUS_TYPE  (REVIEW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Submitted','Y',NOW(),'fibi_admin');
INSERT INTO COI_REVIEW_STATUS_TYPE  (REVIEW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Review in progress','Y',NOW(),'fibi_admin');
INSERT INTO COI_REVIEW_STATUS_TYPE  (REVIEW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Completed','Y',NOW(),'fibi_admin');
INSERT INTO COI_REVIEW_STATUS_TYPE  (REVIEW_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Revison requested','Y',NOW(),'fibi_admin');
