INSERT INTO CONTACT_ROLE_TYPE  (CONTACT_ROLE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('COI','Co-Investigator',NOW(),'fibi_admin');
INSERT INTO CONTACT_ROLE_TYPE  (CONTACT_ROLE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('KP','Key Person',NOW(),'fibi_admin');
INSERT INTO CONTACT_ROLE_TYPE  (CONTACT_ROLE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('PI','Principal Investigator',NOW(),'fibi_admin');
