INSERT INTO COST_SHARING_TYPE  (COST_SHARE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (1,'None',NOW(),'fibi_admin','Y');
INSERT INTO COST_SHARING_TYPE  (COST_SHARE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (2,'Prohibited',NOW(),'fibi_admin','Y');
INSERT INTO COST_SHARING_TYPE  (COST_SHARE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (3,'Required by Sponsor',NOW(),'fibi_admin','Y');
INSERT INTO COST_SHARING_TYPE  (COST_SHARE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (4,'Voluntary',NOW(),'fibi_admin','Y');
