INSERT INTO DELEGATIONS_STATUS  (DELEGATION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('A','Accepted','Y',NOW(),'fibi_admin');
INSERT INTO DELEGATIONS_STATUS  (DELEGATION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('D','Denied','Y',NOW(),'fibi_admin');
INSERT INTO DELEGATIONS_STATUS  (DELEGATION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('R','Requested','Y',NOW(),'fibi_admin');
INSERT INTO DELEGATIONS_STATUS  (DELEGATION_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('X','Deleted','Y',NOW(),'fibi_admin');
