INSERT INTO ENTITY_STATUS  (ENTITY_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Active','Y',NOW(),'fibi_admin');
INSERT INTO ENTITY_STATUS  (ENTITY_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Inactive','Y',NOW(),'fibi_admin');
INSERT INTO ENTITY_STATUS  (ENTITY_STATUS_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Unverified','Y',NOW(),'fibi_admin');
