INSERT INTO EPS_PROP_DISCIPLINE_CLUSTER  (CLUSTER_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'EP2',NOW(),'fibi_admin');
INSERT INTO EPS_PROP_DISCIPLINE_CLUSTER  (CLUSTER_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'EP4',NOW(),'fibi_admin');
INSERT INTO EPS_PROP_DISCIPLINE_CLUSTER  (CLUSTER_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'N/A',NOW(),'fibi_admin');
