INSERT INTO ESIGN_RECIPIENT_TYPE  (ESIGN_RECIPIENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Signer',NOW(),'fibi_admin','Y');
INSERT INTO ESIGN_RECIPIENT_TYPE  (ESIGN_RECIPIENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Carbon Copy',NOW(),'fibi_admin','Y');
INSERT INTO ESIGN_RECIPIENT_TYPE  (ESIGN_RECIPIENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Viewer',NOW(),'fibi_admin','Y');
