INSERT INTO EXT_REVIEW_STATUS  (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (1,'In-Progress',NOW(),'fibi_admin','Y');
INSERT INTO EXT_REVIEW_STATUS  (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (2,'Sent For Review',NOW(),'fibi_admin','Y');
INSERT INTO EXT_REVIEW_STATUS  (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (3,'Completed',NOW(),'fibi_admin','Y');
INSERT INTO EXT_REVIEW_STATUS  (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (4,'Review Draft',NOW(),'fibi_admin','Y');
INSERT INTO EXT_REVIEW_STATUS  (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (5,'Review Pending',NOW(),'fibi_admin','Y');
INSERT INTO EXT_REVIEW_STATUS  (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (6,'Review In Progress',NOW(),'fibi_admin','Y');
INSERT INTO EXT_REVIEW_STATUS  (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (7,'Review Recalled',NOW(),'fibi_admin','Y');
