INSERT INTO IOI_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (1,'Draft',NOW(),'fibi_admin','Y');
INSERT INTO IOI_STATUS (STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (2,'Submitted',NOW(),'fibi_admin','Y');
