INSERT INTO KPI_MANPOWER_DEVELOPMENT_CURRENT_STATUS (CURRENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Active',NOW(),'fibi_admin','Y');
INSERT INTO KPI_MANPOWER_DEVELOPMENT_CURRENT_STATUS (CURRENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Graduated',NOW(),'fibi_admin','Y');
