INSERT INTO MANPOWER_BUDGET_REFERENCE_TYPE  (BUDGET_REFERENCE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,IS_ACTIVE) VALUES ('1','WBS','fibi_admin',NOW(),'Y');
INSERT INTO MANPOWER_BUDGET_REFERENCE_TYPE  (BUDGET_REFERENCE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,IS_ACTIVE) VALUES ('2','B','fibi_admin',NOW(),'Y');
