INSERT INTO NEGOTIATION_PERSONNEL_TYPE  (PERSONNEL_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Legal Person',NOW(),'fibi_admin','Y');
INSERT INTO NEGOTIATION_PERSONNEL_TYPE  (PERSONNEL_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Principal Investigator',NOW(),'fibi_admin','Y');
