INSERT INTO NEGOTIATION_COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Legal Comment',NOW(),'fibi_admin');
INSERT INTO NEGOTIATION_COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Summary Comment',NOW(),'fibi_admin');
INSERT INTO NEGOTIATION_COMMENT_TYPE  (COMMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Neotiator comment',NOW(),'fibi_admin');
