INSERT INTO PRE_REVIEW_STATUS  (PRE_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','In Progress',NOW(),'fibi_admin');
INSERT INTO PRE_REVIEW_STATUS  (PRE_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Complete',NOW(),'fibi_admin');
INSERT INTO PRE_REVIEW_STATUS  (PRE_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Revision Requested',NOW(),'fibi_admin');
