INSERT INTO PROGRESS_REPRT_MILESTONE_STATUS  (MILESTONE_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Completed',NOW(),'fibi_admin','Y');
INSERT INTO PROGRESS_REPRT_MILESTONE_STATUS  (MILESTONE_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Dropped',NOW(),'fibi_admin','Y');
INSERT INTO PROGRESS_REPRT_MILESTONE_STATUS  (MILESTONE_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Not Started',NOW(),'fibi_admin','Y');
INSERT INTO PROGRESS_REPRT_MILESTONE_STATUS  (MILESTONE_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','On Going',NOW(),'fibi_admin','Y');
