INSERT INTO PROPOSAL_RESRCH_TYPE  (RESRCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Area of Research',NOW(),'fibi_admin');
INSERT INTO PROPOSAL_RESRCH_TYPE  (RESRCH_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Societal Challenge Areas',NOW(),'fibi_admin');
