INSERT INTO RATE_CLASS_TYPE  (SORT_ID,PREFIX_ACTIVITY_TYPE,RATE_CLASS_TYPE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'N','E','Fringe Benefits',NOW(),'fibi_admin');
INSERT INTO RATE_CLASS_TYPE  (SORT_ID,PREFIX_ACTIVITY_TYPE,RATE_CLASS_TYPE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'N','I','Inflation',NOW(),'fibi_admin');
INSERT INTO RATE_CLASS_TYPE  (SORT_ID,PREFIX_ACTIVITY_TYPE,RATE_CLASS_TYPE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (6,'N','L','Lab Allocation - Other',NOW(),'fibi_admin');
INSERT INTO RATE_CLASS_TYPE  (SORT_ID,PREFIX_ACTIVITY_TYPE,RATE_CLASS_TYPE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Y','O','F & A',NOW(),'fibi_admin');
INSERT INTO RATE_CLASS_TYPE  (SORT_ID,PREFIX_ACTIVITY_TYPE,RATE_CLASS_TYPE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (4,'N','V','Vacation',NOW(),'fibi_admin');
INSERT INTO RATE_CLASS_TYPE  (SORT_ID,PREFIX_ACTIVITY_TYPE,RATE_CLASS_TYPE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (7,'N','X','Other',NOW(),'fibi_admin');
INSERT INTO RATE_CLASS_TYPE  (SORT_ID,PREFIX_ACTIVITY_TYPE,RATE_CLASS_TYPE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (5,'N','Y','Lab Allocation - Salaries',NOW(),'fibi_admin');
