INSERT INTO REPORT_COLUMNS  (REPORT_COLUMN_ID,TYPE_CODE,COLUMN_ID,IS_FILTER,IS_COLUMN,DISPLAY_NAME,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (6,'96',7,'Y','Y','Person','fibi_admin',NOW());
INSERT INTO REPORT_COLUMNS  (REPORT_COLUMN_ID,TYPE_CODE,COLUMN_ID,IS_FILTER,IS_COLUMN,DISPLAY_NAME,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (7,'101',7,'Y','Y','Person','fibi_admin',NOW());
INSERT INTO REPORT_COLUMNS  (REPORT_COLUMN_ID,TYPE_CODE,COLUMN_ID,IS_FILTER,IS_COLUMN,DISPLAY_NAME,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (8,'101',8,'Y','Y','Other support as of','fibi_admin',NOW());
INSERT INTO REPORT_COLUMNS  (REPORT_COLUMN_ID,TYPE_CODE,COLUMN_ID,IS_FILTER,IS_COLUMN,DISPLAY_NAME,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (9,'102',1,'Y','Y','Unit','fibi_admin',NOW());
