INSERT INTO SOCIETAL_CHALLENGE_AREA  (CHALLENGE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Interpreting Economies & Financial Markets',NOW(),'fibi_admin','Y');
INSERT INTO SOCIETAL_CHALLENGE_AREA  (CHALLENGE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Strengthening Social Fabric & Quality of Life',NOW(),'fibi_admin','N');
INSERT INTO SOCIETAL_CHALLENGE_AREA  (CHALLENGE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Navigating Boundaries & Borders',NOW(),'fibi_admin','N');
INSERT INTO SOCIETAL_CHALLENGE_AREA  (CHALLENGE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Managing for Sustainability',NOW(),'fibi_admin','Y');
INSERT INTO SOCIETAL_CHALLENGE_AREA  (CHALLENGE_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Advancing Innovation & Technology',NOW(),'fibi_admin','N');
