INSERT INTO SR_ROLE_TYPE  (ROLE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','DLC',NOW(),'fibi_admin');
INSERT INTO SR_ROLE_TYPE  (ROLE_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','CA',NOW(),'fibi_admin');
