INSERT INTO TASK_STATUS  (TASK_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Open',NOW(),'fibi_admin');
INSERT INTO TASK_STATUS  (TASK_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','In Progress',NOW(),'fibi_admin');
INSERT INTO TASK_STATUS  (TASK_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Approval In Progress',NOW(),'fibi_admin');
INSERT INTO TASK_STATUS  (TASK_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Returned',NOW(),'fibi_admin');
INSERT INTO TASK_STATUS  (TASK_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Completed',NOW(),'fibi_admin');
INSERT INTO TASK_STATUS  (TASK_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('6','Cancelled',NOW(),'fibi_admin');
