INSERT INTO UNIT_ADMINISTRATOR_TYPE  (UNIT_ADMINISTRATOR_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,DEFAULT_GROUP_FLAG,IS_ACTIVE) VALUES ('1','Administrative Officer',NOW(),'fibi_admin',NULL,'Y');
INSERT INTO UNIT_ADMINISTRATOR_TYPE  (UNIT_ADMINISTRATOR_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,DEFAULT_GROUP_FLAG,IS_ACTIVE) VALUES ('11','Provost',NOW(),'fibi_admin',NULL,'Y');
INSERT INTO UNIT_ADMINISTRATOR_TYPE  (UNIT_ADMINISTRATOR_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,DEFAULT_GROUP_FLAG,IS_ACTIVE) VALUES ('2','OSP Administrator',NOW(),'fibi_admin',NULL,'Y');
INSERT INTO UNIT_ADMINISTRATOR_TYPE  (UNIT_ADMINISTRATOR_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,DEFAULT_GROUP_FLAG,IS_ACTIVE) VALUES ('3','Department Admin',NOW(),'fibi_admin',NULL,'Y');
INSERT INTO UNIT_ADMINISTRATOR_TYPE  (UNIT_ADMINISTRATOR_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,DEFAULT_GROUP_FLAG,IS_ACTIVE) VALUES ('4','Dean VP',NOW(),'fibi_admin',NULL,'Y');
INSERT INTO UNIT_ADMINISTRATOR_TYPE  (UNIT_ADMINISTRATOR_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,DEFAULT_GROUP_FLAG,IS_ACTIVE) VALUES ('7','Administrative Contact',NOW(),'fibi_admin',NULL,'Y');
INSERT INTO UNIT_ADMINISTRATOR_TYPE  (UNIT_ADMINISTRATOR_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,DEFAULT_GROUP_FLAG,IS_ACTIVE) VALUES ('8','Financial Contact',NOW(),'fibi_admin',NULL,'Y');
