INSERT INTO WEB_SOCKET_CON_CONFIG  (CONFIGURATION_KEY,CONFIGURATION_VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('ENABLE_LOCK','N','To enable lock',NOW(),'fibi_admin');
INSERT INTO WEB_SOCKET_CON_CONFIG  (CONFIGURATION_KEY,CONFIGURATION_VALUE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('ENABLE_SOCKET','N','To enable socket',NOW(),'fibi_admin');
