INSERT INTO PERSON_ROLE_TYPE (ROLE_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE) 
SELECT 8068, 'Cancelled Approvers', utc_timestamp(), 'admin', 'Y'
WHERE NOT EXISTS (
SELECT 1 FROM PERSON_ROLE_TYPE WHERE ROLE_TYPE_CODE = 8068 AND DESCRIPTION = 'Cancelled Approvers');
