ALTER TABLE `OPA_DISCLOSURE`
DROP FOREIGN KEY `OPA_DISCLOSURE_FK4`;
ALTER TABLE `OPA_DISCLOSURE`
ADD INDEX `OPA_DISCLOSURE_IDX4` (`PERSON_ID` ASC) VISIBLE,
DROP INDEX `OPA_DISCLOSURE_FK4_idx` ;

ALTER TABLE `OPA_DISCLOSURE`
ADD CONSTRAINT `OPA_DISCLOSURE_FK4`
  FOREIGN KEY (`PERSON_ID`)
  REFERENCES `PERSON` (`PERSON_ID`);

ALTER TABLE `OPA_PERSON`
DROP COLUMN `EXEMPTION_REASON`,
DROP COLUMN `EXEMPT_TO_DATE`,
DROP COLUMN `EXEMPT_FROM_DATE`,
DROP COLUMN `IS_RULE_BASED`,
ADD COLUMN `OPA_PERSON_ID` INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `PERSON_ID` `PERSON_ID` VARCHAR(40) NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`OPA_PERSON_ID`);

ALTER TABLE `OPA_DISCLOSURE`
ADD COLUMN `OPA_PERSON_ID` INT NULL ,
ADD INDEX `OPA_DISCLOSURE_IDX5` (`OPA_PERSON_ID` ASC) VISIBLE;

ALTER TABLE `OPA_DISCLOSURE`
ADD CONSTRAINT `OPA_DISCLOSURE_FK5`
  FOREIGN KEY (`OPA_PERSON_ID`)
  REFERENCES `OPA_PERSON` (`OPA_PERSON_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

CREATE TABLE `PERSON_DISCL_REQUIREMENT` (
  `PERSON_DISCL_REQUIREMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `CAN_CREATE_OPA` VARCHAR(1) NULL,
  `IS_OPA_RULE_BASED` VARCHAR(1) NULL,
  `CREATE_OPA_ADMIN_FORCE_ALLOWED` VARCHAR(1) NULL DEFAULT 'N',
  `OPA_EXEMPT_FROM_DATE` DATETIME NULL,
  `OPA_EXEMPT_TO_DATE` DATETIME NULL,
  `OPA_EXEMPTION_REASON` VARCHAR(225) NULL,
  `PERSON_ID` VARCHAR(40) NULL,
  `CREATE_TIMESTAMP` DATETIME NULL,
  `CREATED_BY` VARCHAR(40) NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATED_BY` VARCHAR(40) NULL,
  PRIMARY KEY (`PERSON_DISCL_REQUIREMENT_ID`),
  INDEX `PERSON_DISCL_REQUIREMENT_IDX1` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `PERSON_DISCL_REQUIREMENT_FK1`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `PERSON` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
