
DROP TABLE IF EXISTS entity_document_status_type;
CREATE TABLE entity_document_status_type (
  DOCUMENT_STATUS_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(500) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP timestamp NULL DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (DOCUMENT_STATUS_TYPE_CODE)
);

DROP TABLE IF EXISTS entity_risk_action_log;
CREATE TABLE entity_risk_action_log (
  ACTION_LOG_ID int NOT NULL AUTO_INCREMENT,
  ENTITY_ID int DEFAULT NULL,
  ENTITY_RISK_ID int DEFAULT NULL,
  ACTION_TYPE_CODE varchar(3) DEFAULT NULL,
  DESCRIPTION varchar(500) DEFAULT NULL,
  OLD_RISK_LEVEL varchar(500) DEFAULT NULL,
  NEW_RISK_LEVEL varchar(500) DEFAULT NULL,
  OLD_COMMENT varchar(4000) DEFAULT NULL,
  NEW_COMMENT varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_LOG_ID),
  KEY ENTITY_RISK_ACTION_LOG_FK1_idx (ACTION_TYPE_CODE),
  CONSTRAINT ENTITY_RISK_ACTION_LOG_FK1 FOREIGN KEY (ACTION_TYPE_CODE) REFERENCES entity_action_type (ACTION_TYPE_CODE)
);
