\. ./FIBI-COI-5.0.7/Procedures/CLENSEMATCH_ENT_INFO_BY_DUNS.sql
\. ./FIBI-COI-5.0.7/Procedures/COI_DISCL_GENERATE_JSON_PROJECT_DETAILS.sql
\. ./FIBI-COI-5.0.7/Procedures/COI_DISCL_VOID_DEACTIVATED_PROJECT.sql
\. ./FIBI-COI-5.0.7/Procedures/COI_INT_KC_SPON_ORG_RESPONSE.sql
\. ./FIBI-COI-5.0.7/Procedures/GENERATE_ATTACHMENT_NUMBER.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_COI_ENTITY_PERSON_ENTITY_DETAILS.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_COI_OPA_DASHBOARD.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_CONSULTING_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_COUNT.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_DATA.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_OPA_PERSON_ENTITY_DETAILS.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_PERSON_ENTITY_INFO.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_ENTITY_TAB_STATUS.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_PROJECT_OVERVIEW.sql
\. ./FIBI-COI-5.0.7/Procedures/UPD_DOCS_WITH_ORG_ENTITY.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_COI_DISCLOSURE_HISTORY.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_HEIR_PERSON_DISCLOSURES.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_HEIR_PROJECT_TREE.sql
\. ./FIBI-COI-5.0.7/Procedures/GET_HEIR_PROJECT_DETAIL.sql
\. ./FIBI-COI-5.0.7/Procedures/ENRICH_ENTITY_HEADER.sql
\. ./FIBI-COI-5.0.7/Procedures/ENRICH_ENTITY_REGISTRATION.sql
\. ./FIBI-COI-5.0.7/Procedures/ENRICH_FOREIGN_NAME.sql
\. ./FIBI-COI-5.0.7/Procedures/VALIDATE_PROJECT_DISCLOSURE.sql
\. ./FIBI-COI-5.0.7/Procedures/COI_SYNC_REMOVE_DEACTIVATED_PROJECTS.sql
\. ./FIBI-COI-5.0.7/Procedures/COI_SYNC_FCOI_DISCLOSURE.sql
\. ./FIBI-COI-5.0.7/Procedures/COI_SYNC_INSERT_DISCL_PROJECTS.sql

\. ./FIBI-COI-5.0.7/Functions/FN_INT_CAN_MARK_DISCL_VOID.sql
\. ./FIBI-COI-5.0.7/Functions/FN_INT_CAN_CREATE_PROP_DISCL.sql


-- \. ./FIBI-COI-5.0.7/IntegrationScripts/Functions/FIBI_COI_DEV_PER_COI_DISC_FLAG.sql
-- \. ./FIBI-COI-5.0.7/IntegrationScripts/Procedures/FIBI_COI_GET_AWARD.sql