export interface RolodexAuditLog {
        "active" ?: string,
        "addressLine1"?: string,
        "addressLine2"?:string,
        "addressLine3"?: string,
        "city"?: string,
        "comments"?: string,
        "country"?: string,
        "createUser"?: string,
        "designation"?: string,
        "emailAddress"?: string,
        "faxNumber"?: string,
        "firstName"?: string,
        "fullName"?: string,
        "lastName"?: string,
        "middleName"?: string,
        "organization"?: string,
        "phoneNumber"?: string,
        "postalCode"?: string,
        "prefix"?: string,
        "rolodexId"?: string,
        "sponsor"?: string,
        "state"?: string,
        "suffix"?: string,
        "title"?: string
}
