INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (52,'COI Administrators',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (58,'Entity Admins',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (66,'OPA Administrators',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (2301,'OPA Department Administrators',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (2302,'DAF',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (2303,'OPA Viewers',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (2601,'Entity COI Administrators',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (8001,'Assistant Dean',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (8002,'COI Department Administrators',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) 
VALUES (8065,'Contract Administrators',UTC_TIMESTAMP(),'admin','Y')
ON DUPLICATE KEY UPDATE 
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);



INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1338,'COI Administrator','COI Administrator','1','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1340,'OPA Administrator','OPA Administrator','1','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1345,'Entity Manager','Entity Manager','1','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1350,'COI Entity Administrator','COI Entity Administrator','1','Y',UTC_TIMESTAMP(),'sdahill',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1353,'Contract Administrator','Contract Administrator','1','Y',UTC_TIMESTAMP(),'vineeth',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1374,'OPA Department Administrator','OPA Department Administrator','2','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1375,'DAF','DAF','2','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1376,'COI Department Administrator','COI Department Administrator','1','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1377,'Assistant Dean','Assistant Dean','1','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);

INSERT INTO `role` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES (1378,'OPA Viewer','OPA Viewer','1','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin')
ON DUPLICATE KEY UPDATE 
    `ROLE_NAME` = VALUES(`ROLE_NAME`),
    `DESCRIPTION` = VALUES(`DESCRIPTION`),
    `UPDATE_TIMESTAMP` = UTC_TIMESTAMP(),
    `UPDATE_USER` = VALUES(`UPDATE_USER`);
