SET SQL_SAFE_UPDATES = 0;
UPDATE `reminder_notification` SET `PLACEHOLDER_VALUES` = 'HTML_CONTENT,EXPIRATION_DATE,NOTIFICATION_RECIPIENTS' WHERE (`PROCEDURE_NAME` = 'FCOI_DISCL_RENWAL_REMNDR_SUMRY');
SET SQL_SAFE_UPDATES = 1;
