DROP TABLE IF EXISTS form_section_component_rules;

DROP PROCEDURE IF EXISTS EVALUATE_FORM_MANDATORY_VALIDATION;
DROP PROCEDURE IF EXISTS GET_COMPONENT_RULE_ID;
DROP PROCEDURE IF EXISTS EVALUATE_FORM_VALIDATION;
DROP PROCEDURE IF EXISTS COI_EVALUATE_VALIDATION;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;

DROP FUNCTION IF EXISTS FN_EVAL_DISCLOSURE_QUESTIONNAIRE;