DELIMITER //
CREATE PROCEDURE `GET_CMP_REPORTER_DASHBOARD`(
    AV_PERSON_ID 	   VARCHAR(40),
    AV_LOGIN_PERSON_ID VARCHAR(40),
    AV_SORT_TYPE 	   VARCHAR(500),
    AV_UNLIMITED 	   BOOLEAN,
	AV_PAGED 		   INT,
	AV_LIMIT 		   INT,
	AV_IS_COUNT 	   BOOLEAN
)
BEGIN
	DECLARE LS_DYN_SQL 			 LONGTEXT;
	DECLARE LS_OFFSET_CONDITION  VARCHAR(600);
	DECLARE LS_OFFSET 			 INT;
	DECLARE SELECTED_FIELD_LIST  LONGTEXT;

	SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
	SET LS_DYN_SQL = '';
	SET SELECTED_FIELD_LIST= '';

    IF AV_IS_COUNT THEN
		SET SELECTED_FIELD_LIST = ' COUNT(*) ';
	ELSE
		SET SELECTED_FIELD_LIST = ' T.CMP_ID,
									T.CMP_NUMBER,
									T.CMP_TYPE_CODE,
									T.CMP_TYPE,
									T.CMP_STATUS_CODE,
									T.CMP_STATUS,
                                    T.CMP_STATUS_BADGE_COLOR,
                                    T.VERSION_STATUS,
									T.PERSON_ID,
									T.PERSON_NAME,
									T.ROLODEX_ID,
									T.ROLODEX_NAME,
									T.HOME_UNIT_NUMBER,
									T.HOME_UNIT_NAME,
									T.APPROVAL_DATE,
									T.EXPIRATION_DATE,
									T.PROJECT_NUMBER,
                                    T.PROJECT_ID,
									T.PROJECT_TITLE,
									T.PROJECT_START_DATE,
									T.PROJECT_END_DATE,
									T.PROJECT_TYPE_CODE,
									T.SPONSOR_AWARD_NUMBER,
									T.LEAD_UNIT_NUMBER,
									T.LEAD_UNIT_NAME,
									T.ENTITY_NUMBER,
									T.ENTITY_NAME,
									T.ENTITY_ID,
									T.UPDATED_BY_FULL_NAME,
									T.UPDATE_TIMESTAMP,
									T.UNIT_ACCESS_TYPE,
                                    T.PI_ID,
                                    T.SPONSOR_CODE,
									T.SPONSOR_NAME,
                                    T.PRIME_SPONSOR_CODE,
                                    T.PRIME_SPONSOR_NAME,
                                    T.TOTAL_COMMENTS_COUNT,
                                    T.IS_SHOW_DOWNLOAD,
                                    T.IS_VIEW_ALLOWED
                                    ';
	END IF;

    SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP AS (SELECT UNIT_NUMBER
												FROM PERSON_ROLES T1
												INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
												INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
												WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
												AND RIGHT_NAME IN (''VIEW_CMP'', ''MAINTAIN_CMP'')
												UNION
                                                SELECT T1.UNIT_NUMBER
                                                FROM PERSON_ROLES T1
												INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID
												WHERE T2.MODULE_CODE= 29 AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
												UNION
                                                SELECT CHILD_UNIT_NUMBER
                                                FROM UNIT_WITH_CHILDREN
												WHERE UNIT_NUMBER IN (SELECT UNIT_NUMBER
																		FROM PERSON_ROLES T1
																		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
																		INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
																		WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
																		AND RIGHT_NAME IN (''VIEW_CMP'', ''MAINTAIN_CMP''))),
								 ACCESS_COMMENTS AS (SELECT UNIT_NUMBER
														FROM PERSON_ROLES T1
														INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
														INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
														WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
														AND RIGHT_NAME IN (''VIEW_CMP_COMMENTS'', ''MAINTAIN_CMP_COMMENTS'') 
														UNION
														SELECT CHILD_UNIT_NUMBER 
														FROM UNIT_WITH_CHILDREN 
														WHERE UNIT_NUMBER IN (SELECT UNIT_NUMBER
																				FROM PERSON_ROLES T1
																				INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
																				INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
																				WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
																				AND RIGHT_NAME IN (''VIEW_CMP_COMMENTS'', ''MAINTAIN_CMP_COMMENTS''))),
								  ACCESS_PRIVATE_COMMENTS AS (SELECT UNIT_NUMBER
																FROM PERSON_ROLES T1
																INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
																INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
																WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
																AND RIGHT_NAME IN (''VIEW_CMP_PRIVATE_COMMENTS'', ''MAINTAIN_CMP_PRIVATE_COMMENTS'') 
																UNION
																SELECT CHILD_UNIT_NUMBER 
																FROM UNIT_WITH_CHILDREN 
																WHERE UNIT_NUMBER IN (SELECT UNIT_NUMBER
																						FROM PERSON_ROLES T1
																						INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
																						INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
																						WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
																						AND RIGHT_NAME IN (''VIEW_CMP_PRIVATE_COMMENTS'', ''MAINTAIN_CMP_PRIVATE_COMMENTS''))),
								  COMMENT_COUNTS AS (SELECT
														DC.MODULE_ITEM_KEY AS CMP_ID,
														COUNT(
															CASE
																WHEN DC.IS_PRIVATE = ''N''
																 AND EXISTS (
																	 SELECT 1
																	 FROM ACCESS_COMMENTS AC
																	 WHERE AC.UNIT_NUMBER = P.HOME_UNIT
																 )
																THEN 1
															END
														) AS PUBLIC_COMMENTS_COUNT,
														COUNT(
															CASE
																WHEN DC.IS_PRIVATE = ''Y''
																 AND EXISTS (
																	 SELECT 1
																	 FROM ACCESS_PRIVATE_COMMENTS APC
																	 WHERE APC.UNIT_NUMBER = P.HOME_UNIT
																 )
																THEN 1
															END
														) AS PRIVATE_COMMENTS_COUNT
													FROM DISCL_COMMENT DC
													JOIN COI_MANAGEMENT_PLAN CMP ON CMP.CMP_ID = DC.MODULE_ITEM_KEY
													JOIN PERSON P ON CMP.PERSON_ID = P.PERSON_ID
													WHERE DC.MODULE_CODE = 29
													  AND DC.COMPONENT_TYPE_CODE = 17
                                                      AND CMP.STATUS_CODE != 7
                                                      AND DC.DOCUMENT_OWNER_PERSON_ID = ''', AV_PERSON_ID,'''
													GROUP BY DC.MODULE_ITEM_KEY
												)');

	SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '
							 SELECT
								T1.CMP_ID,
								T1.CMP_NUMBER,
								T1.CMP_TYPE_CODE,
								T2.DESCRIPTION AS CMP_TYPE,
								T1.STATUS_CODE AS CMP_STATUS_CODE,
								T3.DESCRIPTION AS CMP_STATUS,
                                T3.BADGE_COLOR AS CMP_STATUS_BADGE_COLOR,
                                T1.VERSION_STATUS,
								T1.PERSON_ID,
								T4.FULL_NAME AS PERSON_NAME,
								T1.ROLODEX_ID,
								T5.FULL_NAME AS ROLODEX_NAME,
								T6.UNIT_NUMBER AS HOME_UNIT_NUMBER,
								T6.UNIT_NAME AS HOME_UNIT_NAME,
								T1.APPROVAL_DATE,
								T1.EXPIRATION_DATE,
								T7.MODULE_ITEM_KEY AS PROJECT_NUMBER,
                                COALESCE(A.STAGE_AWARD_ID, PD.STAGE_PROPOSAL_ID, IP.STAGE_PROPOSAL_ID) AS PROJECT_ID,
								COALESCE(A.TITLE, PD.TITLE, IP.TITLE) AS PROJECT_TITLE,
								COALESCE(A.PROJECT_START_DATE, PD.PROPOSAL_START_DATE, IP.PROJECT_START_DATE) AS PROJECT_START_DATE,
								COALESCE(A.PROJECT_END_DATE, PD.PROPOSAL_END_DATE, IP.PROJECT_END_DATE) AS PROJECT_END_DATE,
								COALESCE(A.SPONSOR_GRANT_NUMBER, PD.SPONSOR_GRANT_NUMBER, IP.SPONSOR_GRANT_NUMBER) AS SPONSOR_AWARD_NUMBER,
								COALESCE(A.LEAD_UNIT_NUMBER, PD.LEAD_UNIT, IP.LEAD_UNIT_NUMBER) AS LEAD_UNIT_NUMBER,
								COALESCE(A.LEAD_UNIT_NAME, PD.LEAD_UNIT_NAME, IP.LEAD_UNIT_NAME) AS LEAD_UNIT_NAME,
								COALESCE(AP.KEY_PERSON_ID, PDP.KEY_PERSON_ID, IPP.KEY_PERSON_ID) AS PI_ID,
								COALESCE(A.SPONSOR_CODE, PD.SPONSOR_CODE, IP.SPONSOR_CODE) AS SPONSOR_CODE,
								COALESCE(A.SPONSOR_NAME, PD.SPONSOR, IP.SPONSOR_NAME) AS SPONSOR_NAME,
                                COALESCE(A.PRIME_SPONSOR_CODE, PD.PRIME_SPONSOR_CODE, IP.PRIME_SPONSOR_CODE) AS PRIME_SPONSOR_CODE,
                                COALESCE(A.PRIME_SPONSOR_NAME, PD.PRIME_SPONSOR, IP.PRIME_SPONSOR_NAME) AS PRIME_SPONSOR_NAME,
                                CASE
									WHEN A.PROJECT_NUMBER IS NOT NULL THEN ''1''
									WHEN IP.PROJECT_NUMBER IS NOT NULL THEN ''2''
									WHEN PD.PROPOSAL_NUMBER IS NOT NULL THEN ''3''
								END AS PROJECT_TYPE_CODE,
								T9.ENTITY_NUMBER,
								T10.PRIMARY_NAME AS ENTITY_NAME,
								T10.ENTITY_ID,
								T12.FULL_NAME AS UPDATED_BY_FULL_NAME,
								T1.UPDATE_TIMESTAMP,
								CASE
									WHEN T6.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS_TMP) THEN ''HOME_UNIT''
									WHEN EXISTS (SELECT 1
												FROM PERSON_AFFILIATED_UNITS PAU
												WHERE PAU.PERSON_ID = T1.PERSON_ID
												AND PAU.AFFILIATION_TYPE_CODE = ''1''
												AND PAU.IS_ACTIVE = ''Y''
												AND PAU.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS_TMP)) THEN ''AFFILIATED_UNIT''
									ELSE NULL
								END AS UNIT_ACCESS_TYPE,
								COALESCE(T13.PUBLIC_COMMENTS_COUNT, 0) + COALESCE(T13.PRIVATE_COMMENTS_COUNT, 0) AS TOTAL_COMMENTS_COUNT,
								CASE
									WHEN
										EXISTS (SELECT 1
												FROM COI_MANAGEMENT_PLAN_ATTACHMENT CMPA
                                                WHERE CMPA.CMP_ID = T1.CMP_ID
                                                AND CMPA.ATTACHMENT_TYPE_CODE = 1)
										THEN TRUE
									ELSE FALSE
								END AS IS_SHOW_DOWNLOAD,
                                (T1.PERSON_ID =  ''', AV_LOGIN_PERSON_ID,''' 
                                OR T4.HOME_UNIT IN (SELECT UNIT_NUMBER FROM ACCESS_TMP)
                                OR EXISTS (SELECT 1
										FROM COI_CMP_REVIEW CR
										WHERE CR.CMP_ID = T1.CMP_ID
										AND CR.ASSIGNEE_PERSON_ID = ''', AV_LOGIN_PERSON_ID,''')) AS IS_VIEW_ALLOWED
							FROM COI_MANAGEMENT_PLAN T1
							JOIN COI_MANAGEMENT_PLAN_TYPE T2 ON T2.CMP_TYPE_CODE = T1.CMP_TYPE_CODE
							JOIN COI_MGMT_PLAN_STATUS_TYPE T3 ON T3.STATUS_CODE = T1.STATUS_CODE
							LEFT JOIN PERSON T4 ON T4.PERSON_ID = T1.PERSON_ID
							LEFT JOIN ROLODEX T5 ON T5.ROLODEX_ID = T1.ROLODEX_ID
							LEFT JOIN UNIT T6 ON T6.UNIT_NUMBER = T4.HOME_UNIT
							LEFT JOIN COI_MGMT_PLAN_PROJ_REL T7 ON T7.CMP_ID = T1.CMP_ID
							LEFT JOIN COI_INT_STAGE_AWARD A
								ON A.PROJECT_NUMBER = T7.MODULE_ITEM_KEY
							   AND T7.MODULE_CODE = 1
							LEFT JOIN COI_INT_STAGE_DEV_PROPOSAL PD
								ON PD.PROPOSAL_NUMBER = T7.MODULE_ITEM_KEY
							   AND T7.MODULE_CODE = 3
							LEFT JOIN COI_INT_STAGE_PROPOSAL IP
								ON IP.PROJECT_NUMBER = T7.MODULE_ITEM_KEY
							   AND T7.MODULE_CODE = 2
							LEFT JOIN COI_INT_STAGE_AWARD_PERSON AP
								ON AP.PROJECT_NUMBER = A.PROJECT_NUMBER
								AND AP.KEY_PERSON_ROLE_CODE = 3
								AND AP.STATUS = ''A''
							LEFT JOIN COI_INT_STAGE_DEV_PROPOSAL_PERSON PDP
								ON PDP.PROPOSAL_NUMBER = PD.PROPOSAL_NUMBER
								AND PDP.KEY_PERSON_ROLE_CODE = 3
								AND PDP.STATUS = ''A''
							LEFT JOIN COI_INT_STAGE_PROPOSAL_PERSON IPP
								ON IPP.PROJECT_NUMBER = IP.PROJECT_NUMBER
								AND IPP.KEY_PERSON_ROLE_CODE = 3
								AND IPP.STATUS = ''A''
							LEFT JOIN COI_MGMT_PLAN_ENTITY_REL T9 ON T9.CMP_ID = T1.CMP_ID
							LEFT JOIN ENTITY T10 ON T10.ENTITY_NUMBER = T9.ENTITY_NUMBER
							LEFT JOIN (
								SELECT ENTITY_NUMBER, MAX(VERSION_NUMBER) AS MAX_VERSION
								FROM ENTITY
								WHERE VERSION_STATUS = ''ACTIVE''
								GROUP BY ENTITY_NUMBER
							) T11 ON T11.ENTITY_NUMBER = T10.ENTITY_NUMBER
                            LEFT JOIN PERSON T12 ON T12.PERSON_ID = T1.UPDATED_BY
							LEFT JOIN COMMENT_COUNTS T13 ON T13.CMP_ID = T1.CMP_ID
							WHERE T10.VERSION_NUMBER = T11.MAX_VERSION
                            AND T1.STATUS_CODE != 7
                            AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                            ');
	-- SORT LOGIC
	IF AV_IS_COUNT = FALSE THEN
		IF AV_SORT_TYPE IS NULL OR AV_SORT_TYPE = '' THEN
				SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
		ELSE
			SET AV_SORT_TYPE = CONCAT(' ORDER BY ', AV_SORT_TYPE);
		END IF;
	ELSE
		SET AV_SORT_TYPE = '';
	END IF;

	-- PAGINATION LOGIC
	IF AV_UNLIMITED = TRUE OR AV_IS_COUNT = TRUE THEN
		SET LS_OFFSET_CONDITION = '';
	ELSE
		SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ', AV_LIMIT,' OFFSET ', LS_OFFSET);
	END IF;

	SET LS_DYN_SQL = CONCAT('SELECT ', SELECTED_FIELD_LIST, ' FROM (', LS_DYN_SQL,' ) T ', AV_SORT_TYPE, LS_OFFSET_CONDITION);

	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;

END
//
