DELIMITER //
CREATE PROCEDURE `COI_DISCL_PROJ_ENTITY_INSERTION`(
	AV_COI_DISCL_PROJECTS_ID          	INT,
	AV_DISCLOSURE_ID 					INT,
	AV_DISCLOSURE_NUMBER 				INT,
	AV_MODULE_CODE						INT,
	AV_MODULE_ITEM_KEY					VARCHAR(100),
	AV_PERSON_ID        				VARCHAR(40),
	AV_UPDATED_BY        				VARCHAR(40),
	AV_SFI_JSON_ARRAY      				JSON
    )
    BEGIN

    DECLARE i INT DEFAULT 0;
    DECLARE array_length INT DEFAULT JSON_LENGTH(AV_SFI_JSON_ARRAY);

    DECLARE LS_PROJECT_ENGAGEMENT_DETAILS VARCHAR(2000);
    DECLARE LS_PROJECT_CONFLICT_STATUS_CODE VARCHAR(10);
    DECLARE LS_UPDATE_USER VARCHAR(60);
    DECLARE LI_COI_DISCL_PROJECT_ENTITY_REL_ID INT;

    DECLARE LI_ENTITY_ID INT;
    DECLARE LI_PERSON_ENTITY_ID INT;
    DECLARE LI_PERSON_ENTITY_NUMBER VARCHAR(50);
	DECLARE LI_PARENT_COMMENT_ID INT;

    DECLARE done INT DEFAULT FALSE;

    DECLARE V_COMMENT TEXT;
    DECLARE V_COMPONENT_TYPE_CODE VARCHAR(10);
    DECLARE V_COMMENT_BY_PERSON_ID VARCHAR(40);
	DECLARE V_PARENT_COMMENT_ID INT;
    DECLARE V_IS_PRIVATE CHAR(1);
    DECLARE V_UPDATE_USER VARCHAR(40);
    DECLARE V_PREV_DISCLOSURE_ID INT;

    DECLARE DISCL_CURSOR CURSOR FOR
        SELECT COMMENT, COMPONENT_TYPE_CODE, COMMENT_BY_PERSON_ID, PARENT_COMMENT_ID, IS_PRIVATE, UPDATE_USER
        FROM DISCL_COMMENT
        WHERE COMPONENT_TYPE_CODE = '6' AND MODULE_CODE = 8
          AND SUB_MODULE_ITEM_KEY = LI_COI_DISCL_PROJECT_ENTITY_REL_ID
          AND MODULE_ITEM_KEY = V_PREV_DISCLOSURE_ID;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    WHILE i < array_length DO
        START TRANSACTION;

        SET @json_obj = JSON_EXTRACT(AV_SFI_JSON_ARRAY, CONCAT('$[', i, ']'));
        SET LI_ENTITY_ID = JSON_UNQUOTE(JSON_EXTRACT(@json_obj, '$.ENTITY_ID'));
        SET LI_PERSON_ENTITY_ID = JSON_UNQUOTE(JSON_EXTRACT(@json_obj, '$.PERSON_ENTITY_ID'));
        SET LI_PERSON_ENTITY_NUMBER = JSON_UNQUOTE(JSON_EXTRACT(@json_obj, '$.PERSON_ENTITY_NUMBER'));
        SET LI_COI_DISCL_PROJECT_ENTITY_REL_ID = NULL;
        SET @PROJECT_ENT_REL_ID = NULL;

        -- Project details query
        SELECT T1.PROJECT_CONFLICT_STATUS_CODE, T1.PROJECT_ENGAGEMENT_DETAILS, T1.UPDATED_BY, T1.COI_DISCL_PROJECT_ENTITY_REL_ID
        INTO LS_PROJECT_CONFLICT_STATUS_CODE, LS_PROJECT_ENGAGEMENT_DETAILS, LS_UPDATE_USER, LI_COI_DISCL_PROJECT_ENTITY_REL_ID
        FROM COI_DISCL_PROJECT_ENTITY_REL T1
        INNER JOIN COI_DISCL_PROJECTS T2 ON T2.COI_DISCL_PROJECTS_ID = T1.COI_DISCL_PROJECTS_ID
        WHERE T1.PERSON_ENTITY_NUMBER = LI_PERSON_ENTITY_NUMBER AND T1.ENTITY_ID = LI_ENTITY_ID
            AND ((T2.MODULE_CODE = AV_MODULE_CODE AND T2.MODULE_ITEM_KEY = AV_MODULE_ITEM_KEY)
                OR T1.COI_DISCL_PROJECTS_ID IN (
                    SELECT t1.COI_DISCL_PROJECTS_ID 
                    FROM COI_DISCL_PROJECTS t1
                    LEFT JOIN COI_PROJECT_INSTITUTE_PROPOSAL_V t2 
                        ON t2.LINKED_AWARD_PROJECT_NUMBER = AV_MODULE_ITEM_KEY AND t1.MODULE_CODE = 2
                    LEFT JOIN COI_PROJECT_PROPOSAL_V t3 
                        ON t3.LINKED_IP_NUMBER = AV_MODULE_ITEM_KEY AND t1.MODULE_CODE = 3
                    WHERE t2.PROPOSAL_NUMBER = t1.MODULE_ITEM_KEY OR t3.PROPOSAL_NUMBER = t1.MODULE_ITEM_KEY
                )
            )
        ORDER BY T1.UPDATE_TIMESTAMP DESC 
        LIMIT 1;

        INSERT INTO COI_DISCL_PROJECT_ENTITY_REL (COI_DISCL_PROJECTS_ID, PERSON_ENTITY_ID, PERSON_ENTITY_NUMBER, ENTITY_ID,
            PROJECT_CONFLICT_STATUS_CODE, PROJECT_ENGAGEMENT_DETAILS, UPDATED_BY, UPDATE_TIMESTAMP)
        VALUES (AV_COI_DISCL_PROJECTS_ID, LI_PERSON_ENTITY_ID, LI_PERSON_ENTITY_NUMBER, LI_ENTITY_ID,
            LS_PROJECT_CONFLICT_STATUS_CODE, LS_PROJECT_ENGAGEMENT_DETAILS, LS_UPDATE_USER, UTC_TIMESTAMP());

        SET @PROJECT_ENT_REL_ID = LAST_INSERT_ID();

        SELECT DISCLOSURE_ID INTO V_PREV_DISCLOSURE_ID
        FROM COI_DISCLOSURE
        WHERE DISCLOSURE_ID <> AV_DISCLOSURE_ID AND PERSON_ID = AV_PERSON_ID
        ORDER BY DISCLOSURE_ID DESC
        LIMIT 1;

        -- Open and process cursor
        OPEN DISCL_CURSOR;

        READ_LOOP: LOOP
            FETCH DISCL_CURSOR INTO V_COMMENT, V_COMPONENT_TYPE_CODE, V_COMMENT_BY_PERSON_ID, V_PARENT_COMMENT_ID, V_IS_PRIVATE, V_UPDATE_USER;
            IF done THEN
                LEAVE READ_LOOP;
            END IF;

			SELECT MAX(COMMENT_ID)  INTO LI_PARENT_COMMENT_ID FROM DISCL_COMMENT 
			WHERE COMMENT = (SELECT COMMENT FROM DISCL_COMMENT
			WHERE COMMENT_ID = V_PARENT_COMMENT_ID);
			

            INSERT INTO DISCL_COMMENT (COMMENT, MODULE_CODE, MODULE_ITEM_KEY, MODULE_ITEM_NUMBER, SUB_MODULE_ITEM_KEY,
                COMPONENT_TYPE_CODE, DOCUMENT_OWNER_PERSON_ID, COMMENT_BY_PERSON_ID, PARENT_COMMENT_ID,
                IS_PRIVATE, UPDATE_USER, UPDATE_TIMESTAMP)
            VALUES (V_COMMENT, 8, AV_DISCLOSURE_ID, AV_DISCLOSURE_NUMBER, @PROJECT_ENT_REL_ID,
                V_COMPONENT_TYPE_CODE, AV_PERSON_ID, V_COMMENT_BY_PERSON_ID, LI_PARENT_COMMENT_ID,
                V_IS_PRIVATE, V_UPDATE_USER, UTC_TIMESTAMP());
			
			
        END LOOP;

        CLOSE DISCL_CURSOR;

        COMMIT;

        SET i = i + 1;
        SET done = FALSE;
    END WHILE;

    START TRANSACTION;
    UPDATE COI_DISCLOSURE SET SYNC_NEEDED = 'N' WHERE DISCLOSURE_ID = AV_DISCLOSURE_ID;
    COMMIT;
END;
//
