Spool log_all.log;
set heading off;
set define off;
set term on;
set serveroutput on;
select '*-*-*-*-*-*-*- Started building ac database objects. 30082023'|| localtimestamp from dual;
@SCRIPTS/ddl.sql
@FUNCTIONS/FIBI_COI_AWD_PER_IS_DISCL_REQ.sql
@FUNCTIONS/FIBI_COI_DEV_PER_CERT_FLAG.sql
@FUNCTIONS/FIBI_COI_DEV_PER_COI_DISC_FLAG.sql
@FUNCTIONS/FIBI_COI_DEV_PER_IS_CERT_REQ.sql
@PROCEDURES/FIBI_COI_FEED_ENTITY.sql
@PROCEDURES/FIBI_COI_GET_AWARD.sql
@PROCEDURES/FIBI_COI_GET_AWARD_PERSONS.sql
@PROCEDURES/FIBI_COI_GET_DEV_PROP_DTLS.sql
@PROCEDURES/FIBI_COI_GET_DEV_PROP_NUM.sql
@PROCEDURES/FIBI_COI_GET_DEV_PROP_PER_DTLS.sql
@PROCEDURES/FIBI_COI_GET_DEV_PROP_QNR_DTLS.sql
@PROCEDURES/FIBI_COI_GET_INST_PROP_PERSONS.sql
@PROCEDURES/FIBI_COI_GET_INST_PROPOSAL.sql
@PROCEDURES/FIBI_COI_SYNC_PERSON_DETAILS.sql
@PROCEDURES/FIBI_COI_SYNC_ROLODEX_DETAILS.sql
@PROCEDURES/FIBI_COI_GET_PERSON_PROJECTS.sql
/
select '*-*-*-*-*-*-*- Completed building ac database objects. 30082023'|| localtimestamp from dual;
Spool Off;
Set define On;
Set feedback On;
EXIT
/