-- Step 1: Create Oracle staging tables for COI disclosure migration

    CREATE TABLE "LEGACY_COI_DISCLOSURE" (
        "COI_DISCLOSURE_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE,
        "SEQUENCE_NUMBER" NUMBER(6,0) NOT NULL ENABLE,
        "PERSON_ID" VARCHAR2(9 BYTE) NOT NULL ENABLE,
        "HOME_UNIT" VARCHAR2(8),
        "CERTIFICATION_TEXT" CLOB,
        "CERTIFIED_BY" VARCHAR2(20 BYTE),
        "CERTIFICATION_TIMESTAMP" DATE,
        "DISCLOSURE_DISPOSITION_CODE" NUMBER(3,0) NOT NULL ENABLE,
        "DISCLOSURE_DISPOSITION" VARCHAR2(200 BYTE),
        "DISCLOSURE_STATUS_CODE" NUMBER(3,0) NOT NULL ENABLE,
        "DISCLOSURE_STATUS" VARCHAR2(200 BYTE),
        "EXPIRATION_DATE" DATE NOT NULL ENABLE,
        "SRC_UPDATE_TIMESTAMP" DATE NOT NULL ENABLE,
        "SRC_UPDATE_USER" VARCHAR2(20 BYTE) NOT NULL ENABLE,
        "EVENT_TYPE_CODE" NUMBER(3,0),
        "EVENT_TYPE" VARCHAR2(200 BYTE),
        "REVIEW_STATUS_CODE" NUMBER(3,0),
        "REVIEW_STATUS" VARCHAR2(200 BYTE),
        "DISC_ACTIVE_STATUS" NUMBER(1,0) DEFAULT 1,
        "MODULE_ITEM_KEY" VARCHAR2(20 BYTE),
        "SRC_CREATE_TIMESTAMP" DATE,
        "SRC_CREATE_USER" VARCHAR2(8 BYTE),
        CONSTRAINT "LEGACY_COI_DISCLOSURE_PK" PRIMARY KEY ("COI_DISCLOSURE_NUMBER", "SEQUENCE_NUMBER")
    );

    CREATE TABLE "LEGACY_COI_DISC_DETAILS" (
        "COI_DISCLOSURE_NUMBER" VARCHAR2(20 BYTE) NOT NULL ENABLE,
        "SEQUENCE_NUMBER" NUMBER(6,0) NOT NULL ENABLE,
        "COI_DISC_DETAILS_NUMBER" NUMBER(7,0) NOT NULL ENABLE,
        "MODULE_CODE" NUMBER(3,0),
        "MODULE_ITEM_KEY" VARCHAR2(20 BYTE),
        "ENTITY_NUMBER" VARCHAR2(10 BYTE),
        "ENTITY_SEQUENCE_NUMBER" NUMBER(6,0),
        "COI_PROJECT_STATUS_CODE" NUMBER(3,0) NOT NULL ENABLE,
        "COI_PROJECT_STATUS" VARCHAR2(200 BYTE),
        "RELATIONSHIP_DESCRIPTION" VARCHAR2(4000 BYTE) NOT NULL ENABLE,
        "SRC_UPDATE_TIMESTAMP" DATE NOT NULL ENABLE,
        "SRC_UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE,
        "ORG_RELATION_DESCRIPTION" VARCHAR2(4000 BYTE),
        CONSTRAINT "LEGACY_COI_DISC_DETAILS_PK" PRIMARY KEY ("COI_DISCLOSURE_NUMBER", "SEQUENCE_NUMBER", "COI_DISC_DETAILS_NUMBER"),
        CONSTRAINT "LEGACY_COI_DISC_DETAILS_FK2" FOREIGN KEY ("COI_DISCLOSURE_NUMBER", "SEQUENCE_NUMBER")
        REFERENCES "LEGACY_COI_DISCLOSURE" ("COI_DISCLOSURE_NUMBER", "SEQUENCE_NUMBER") ENABLE
    );

-- Step 2: Load legacy disclosure data into staging tables

    INSERT INTO LEGACY_COI_DISCLOSURE (
        COI_DISCLOSURE_NUMBER,
        SEQUENCE_NUMBER,
        PERSON_ID,
        HOME_UNIT,
        CERTIFICATION_TEXT,
        CERTIFIED_BY,
        CERTIFICATION_TIMESTAMP,
        DISCLOSURE_DISPOSITION_CODE,
        DISCLOSURE_DISPOSITION,
        DISCLOSURE_STATUS_CODE,
        DISCLOSURE_STATUS,
        EXPIRATION_DATE,
        SRC_UPDATE_TIMESTAMP,
        SRC_UPDATE_USER,
        EVENT_TYPE_CODE,
        EVENT_TYPE,
        REVIEW_STATUS_CODE,
        REVIEW_STATUS,
        DISC_ACTIVE_STATUS,
        MODULE_ITEM_KEY,
        SRC_CREATE_TIMESTAMP,
        SRC_CREATE_USER
    )
    (SELECT
        CD.COI_DISCLOSURE_NUMBER,
        CD.SEQUENCE_NUMBER,
        CD.PERSON_ID,
        P.HOME_UNIT,
        CD.CERTIFICATION_TEXT,
        CD.CERTIFIED_BY,
        CD.CERTIFICATION_TIMESTAMP,
        CD.DISCLOSURE_DISPOSITION_CODE,
        DS.DESCRIPTION AS DISCLOSURE_DISPOSITION,
        CD.DISCLOSURE_STATUS_CODE,
        CS.DESCRIPTION AS DISCLOSURE_STATUS,
        CD.EXPIRATION_DATE,
        CD.UPDATE_TIMESTAMP,
        CD.UPDATE_USER,
        CD.EVENT_TYPE_CODE,
        ET.DESCRIPTION AS EVENT_TYPE,
        CD.REVIEW_STATUS_CODE,
        RS.DESCRIPTION AS REVIEW_STATUS,
        CD.DISC_ACTIVE_STATUS,
        CD.MODULE_ITEM_KEY,
        CD.CREATE_TIMESTAMP,
        CD.CREATE_USER
    FROM
    OSP$COI_DISCLOSURE CD
    LEFT JOIN OSP$PERSON P ON CD.PERSON_ID = P.PERSON_ID
    INNER JOIN OSP$COI_DISPOSITION_STATUS DS ON CD.DISCLOSURE_DISPOSITION_CODE = DS.COI_DISPOSITION_CODE
    INNER JOIN OSP$COI_DISCL_STATUS CS ON CD.DISCLOSURE_STATUS_CODE = CS.COI_DISCLOSURE_STATUS_CODE
    INNER JOIN OSP$COI_DISCLOSURE_EVENT_TYPE ET ON CD.EVENT_TYPE_CODE = ET.EVENT_TYPE_CODE
    INNER JOIN OSP$COI_REVIEW_STATUS RS ON CD.REVIEW_STATUS_CODE = RS.REVIEW_STATUS_CODE
    );

    INSERT INTO LEGACY_COI_DISC_DETAILS (
        COI_DISCLOSURE_NUMBER,
        SEQUENCE_NUMBER,
        COI_DISC_DETAILS_NUMBER,
        MODULE_CODE,
        MODULE_ITEM_KEY,
        ENTITY_NUMBER,
        ENTITY_SEQUENCE_NUMBER,
        COI_PROJECT_STATUS_CODE,
        COI_PROJECT_STATUS,
        RELATIONSHIP_DESCRIPTION,
        SRC_UPDATE_TIMESTAMP,
        SRC_UPDATE_USER,
        ORG_RELATION_DESCRIPTION)
    (SELECT
        CDD.COI_DISCLOSURE_NUMBER,
        CDD.SEQUENCE_NUMBER,
        CDD.COI_DISC_DETAILS_NUMBER,
        CDD.MODULE_CODE,
        CDD.MODULE_ITEM_KEY,
        CDD.ENTITY_NUMBER,
        CDD.ENTITY_SEQUENCE_NUMBER,
        CDD.COI_PROJECT_STATUS_CODE,
        CS.DESCRIPTION AS COI_PROJECT_STATUS,
        CDD.RELATIONSHIP_DESCRIPTION,
        CDD.UPDATE_TIMESTAMP,
        CDD.UPDATE_USER,
        CDD.ORG_RELATION_DESCRIPTION
    FROM OSP$COI_DISC_DETAILS CDD
    INNER JOIN OSP$COI_DISCL_STATUS CS ON CDD.COI_PROJECT_STATUS_CODE = CS.COI_DISCLOSURE_STATUS_CODE);

-- Staging tables in MySQL (Already in MySQL. Created through release scripts)

    CREATE TABLE LEGACY_COI_DISCLOSURE (
        LEGACY_DISCLOSURE_ID INT AUTO_INCREMENT PRIMARY KEY,
        COI_DISCLOSURE_NUMBER VARCHAR(20) NOT NULL,
        SEQUENCE_NUMBER INT NOT NULL,
        PERSON_ID VARCHAR(40) NOT NULL,
        HOME_UNIT VARCHAR(8), -- note
        CERTIFICATION_TEXT TEXT,
        CERTIFIED_BY VARCHAR(40),
        CERTIFICATION_TIMESTAMP DATETIME,
        DISCLOSURE_DISPOSITION_CODE INT,
        DISCLOSURE_DISPOSITION VARCHAR(200),
        DISCLOSURE_STATUS_CODE INT,
        DISCLOSURE_STATUS VARCHAR(200),
        EXPIRATION_DATE DATE,
        SRC_UPDATE_TIMESTAMP DATETIME,
        SRC_UPDATE_USER VARCHAR(60),
        EVENT_TYPE_CODE INT,
        EVENT_TYPE VARCHAR(200),
        REVIEW_STATUS_CODE INT,
        REVIEW_STATUS VARCHAR(200),
        DISC_ACTIVE_STATUS TINYINT,
        MODULE_ITEM_KEY VARCHAR(20),
        SRC_CREATE_TIMESTAMP DATETIME,
        SRC_CREATE_USER VARCHAR(60),
        SYNC_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
        UPDATE_TIMESTAMP DATETIME,
        UPDATE_USER VARCHAR(60),
        KEY LEGACY_COI_DISCLOSURE_IDX1 (COI_DISCLOSURE_NUMBER),
        KEY LEGACY_COI_DISCLOSURE_IDX2 (COI_DISCLOSURE_NUMBER,SEQUENCE_NUMBER));

    CREATE TABLE LEGACY_COI_DISC_DETAILS (
        LEGACY_DISC_DETAILS_ID INT AUTO_INCREMENT PRIMARY KEY,
        LEGACY_DISCLOSURE_ID INT,
        COI_DISCLOSURE_NUMBER VARCHAR(20) NOT NULL,
        SEQUENCE_NUMBER INT NOT NULL,
        COI_DISC_DETAILS_NUMBER INT NOT NULL,
        MODULE_CODE INT,
        MODULE_ITEM_KEY VARCHAR(20),
        ENTITY_NUMBER VARCHAR(10),
        ENTITY_SEQUENCE_NUMBER INT,
        COI_PROJECT_STATUS_CODE INT,
        COI_PROJECT_STATUS VARCHAR(200),
        RELATIONSHIP_DESCRIPTION TEXT,
        SRC_UPDATE_TIMESTAMP DATETIME,
        SRC_UPDATE_USER VARCHAR(60),
        ORG_RELATION_DESCRIPTION TEXT,
        UPDATE_TIMESTAMP DATETIME,
        UPDATE_USER VARCHAR(60)
        PRIMARY KEY (COI_DISCLOSURE_NUMBER, SEQUENCE_NUMBER, COI_DISC_DETAILS_NUMBER),
        FOREIGN KEY LEGACY_COI_DISC_DETAILS_FK1 (LEGACY_DISCLOSURE_ID)
            REFERENCES LEGACY_COI_DISCLOSURE(LEGACY_DISCLOSURE_ID)
    );

-- Step 4: Load data into MySQL staging tables from Oracle staging tables

-- Step 5: Update LEGACY_COI_DISC_DETAILS with LEGACY_DISCLOSURE_ID

    SET SQL_SAFE_UPDATES = 0;
    UPDATE LEGACY_COI_DISC_DETAILS T1
    JOIN LEGACY_COI_DISCLOSURE T2 ON T2.COI_DISCLOSURE_NUMBER = T1.COI_DISCLOSURE_NUMBER AND T2.SEQUENCE_NUMBER = T1.SEQUENCE_NUMBER
    SET T1.LEGACY_DISCLOSURE_ID = T2.LEGACY_DISCLOSURE_ID;
    SET SQL_SAFE_UPDATES = 1;

-- Step 6: Update award number in LEGACY_COI_DISC_DETAILS table

    SET SQL_SAFE_UPDATES = 0;
    UPDATE LEGACY_COI_DISC_DETAILS
    SET MODULE_ITEM_KEY = CONCAT(
                        SUBSTRING_INDEX(MODULE_ITEM_KEY, '-', 1),         -- part before hyphen
                        '-',
                        LPAD(SUBSTRING_INDEX(MODULE_ITEM_KEY, '-', -1), 5, '0'))  -- part after hyphen, padded to 5 digits
    WHERE MODULE_CODE = 1;
    SET SQL_SAFE_UPDATES = 1;
