INSERT INTO `NOTIFICATION_TYPE` (`NOTIFICATION_TYPE_ID`, `MODULE_CODE`, `SUB_MODULE_CODE`, `DESCRIPTION`, `SUBJECT`, `MESSAGE`, `PROMPT_USER`, `IS_ACTIVE`, `CREATE_USER`, `CREATE_TIMESTAMP`, `UPDATE_USER`, `UPDATE_TIMESTAMP`, `IS_SYSTEM_SPECIFIC`) VALUES ('8015', '8', '0', 'Create Award Or Fcoi Disclosure', 'Action required: Disclosure Creation Request', '<p>Dear {PROJECT_DETAIL#PROJECT_PERSON_NAME},</p> <p>Kindly create an Award Disclosure or revise/create a Financial Conflict of Interest (FCOI) disclosure for the following Award:</p> <p><strong>Award: {PROJECT_DETAIL#PROJECT_MODULE_ITEM_KEY} - {PROJECT_DETAIL#PROJECT_TITLE} </strong></p> <p><br /><span >Please log in to the COI system and submit the required disclosure at your earliest convenience.</span></p> <p>&nbsp;</p>', 'N', 'Y', 'quickstart', now(), 'quickstart', now(), 'N');
INSERT INTO `MQ_ROUTER_TRIGGER_CONFIGURATION` (`MQ_ROUTER_TRIGGER_CONFIG_ID`, `TRIGGER_TYPE`, `IS_ACTIVE`, `QUEUE_NAME`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'NOTIFY_DISCLOSURE_CREATION', 'Y', 'Q_NOTIFICATION', 'Create Award DIsclosure or Fcoi Disclosure Notification', now(), 'quickstart');
INSERT INTO `MESSAGE` (`MESSAGE_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('8001', 'Disclosure Required', now(), 'quickstart');
-- INSERT INTO `MESSAGE` (`MESSAGE_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('146', 'Revise Disclosure or Create Project Disclosure', now(), 'quickstart');
-- Cross check the above query with Fibi-Base (Existed in Base)
INSERT INTO `NOTIFY_PLACEHOLDER_HEADER` (`NOTIFY_PLACEHOLDER_HEADER_ID`, `MODULE_CODE`, `SUB_MODULE_CODE`, `QUERY_DEFINITION`, `QUERY_TYPE`, `ELEMENT_NAME`, `ELEMENT_TYPE`, `IS_ACTIVE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `UNIQUE_DISPLAY_NAME`) VALUES ('4', '8', '0', '', 'S', '', 'S', 'Y', 'Hardcoded Placeholders', now(), 'quickstart', 'PROJECT_DETAIL');
INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('22', '4', 'PROJECT_MODULE_ITEM_KEY', 'Project Number', now(), 'quickstart');
INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('23', '4', 'PROJECT_PERSON_NAME', 'Project Person Name', now(), 'quickstart');
INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('24', '4', 'PROJECT_TITLE', 'Project Title', now(), 'quickstart');
