ALTER TABLE FORM_BUILDER_HEADER MODIFY TITLE VARCHAR(1000), MODIFY DESCRIPTION VARCHAR(4000);
ALTER TABLE FORM_BUILDER_HEADER ADD COLUMN PUBLISHED_DATE DATETIME DEFAULT NULL;
ALTER TABLE FB_COMP_CUSTOM_ELEMENT MODIFY PLACE_HOLDER_TEXT VARCHAR(300);
ALTER TABLE FORM_BUILDER_SECTION_COMPONENT MODIFY VALIDATION_MESSAGE VARCHAR(1000) DEFAULT NULL;
ALTER TABLE FB_COMP_CUSTOM_ELEMENT_OPTIONS MODIFY OPTION_NAME VARCHAR(1000) DEFAULT NULL;
