create or replace PROCEDURE FIBI_COI_FEED_ENTITY(
AV_SPONCOR_CODE            IN VARCHAR2,
AV_ORGANIZATION_ID         IN VARCHAR2,
AV_ENTITY_ID 			   IN NUMBER,
AV_ROLODEX_ID 			   IN NUMBER,
IS_SPONSOR_SYNC_FLAG       IN VARCHAR2,
IS_ORGANIZATION_SYNC_FLAG  IN VARCHAR2,
AV_PRIMARY_NAME       	   IN VARCHAR2,
AV_SPON_ADDRESS_LINE_1     IN VARCHAR2, 
AV_SPON_ADDRESS_LINE_2     IN VARCHAR2,
AV_SPON_CITY               IN VARCHAR2,
AV_SPON_STATE              IN VARCHAR2,
AV_SPON_POSTAL_CODE   	   IN VARCHAR2,
AV_SPON_COUNTRY_CODE   	   IN VARCHAR2,
AV_ORG_ADDRESS_LINE_1      IN VARCHAR2,
AV_ORG_ADDRESS_LINE_2      IN VARCHAR2,
AV_ORG_CITY                IN VARCHAR2,
AV_ORG_STATE               IN VARCHAR2,
AV_ORG_POSTAL_CODE   	   IN VARCHAR2,
AV_ORG_COUNTRY_CODE   	   IN VARCHAR2,
AV_EMAIL_ADDRESS           IN VARCHAR2,
AV_TELEPHONE_NUMBER        IN VARCHAR2,
AV_UPDATE_BY    		   IN VARCHAR2,
AV_SPONSOR_TYPE_CODE       IN VARCHAR2,
AV_CUSTOMER_NUMBER		   IN VARCHAR2,
AV_AUDIT_REPORT_SENT 	   IN VARCHAR2,
AV_UEI					   IN VARCHAR2,
AV_DODAC_NUMBER 		   IN VARCHAR2,
AV_DUNS_NUMBER 			   IN VARCHAR2,
AV_ACRONYM 				   IN VARCHAR2,
AV_CAGE_NUMBER 			   IN VARCHAR2,
AV_DUNNING_CAMPAIGN_ID 	   IN VARCHAR2,
AV_NUMBER_OF_EMPLOYEES     IN NUMBER,
AV_IRS_TAX_EXCEMPTION      IN VARCHAR2,
AV_FEDRAL_EMPLOYER_ID      IN VARCHAR2,
AV_MASS_TAX_EXCEMPT_NUM    IN VARCHAR2,
AV_AGENCY_SYMBOL           IN VARCHAR2,
AV_VENDOR_CODE             IN VARCHAR2,
AV_COM_GOV_ENTITY_CODE     IN VARCHAR2,
AV_MASS_EMPLOYEE_CLAIM     IN VARCHAR2,
AV_HUMAN_SUB_ASSURANCE     IN VARCHAR2,
AV_ANIMAL_WELFARE_ASS 	   IN VARCHAR2,
AV_SCIENCE_MISCOMPL_DT     IN DATE,
AV_PHS_ACOUNT              IN VARCHAR2,
AV_NSF_INSTITUTIONAL_CODE  IN VARCHAR2,
AV_INDIRECT_COST_RATE_AG   IN VARCHAR2,
AV_COGNIZANT_AUDITOR       IN NUMBER,	
AV_ONR_RESIDENT_REP        IN NUMBER,
AV_LOBBYING_REGISTRANT     IN VARCHAR2,
AV_LOBBYING_INDIVIDUAL     IN VARCHAR2,
AV_SAM_EXPIRATION_DATE     IN DATE,
AV_INCORPORATED_DATE       IN DATE,
AV_INCORPORATED_IN         IN VARCHAR2,
AV_RISK_LEVEL 			   IN varchar2,
cur_generic  			   OUT SYS_REFCURSOR
) IS
LI_ROL_CNT 					INT;
LI_SPONSOR_CNT				INT;
LI_ORG_CNT 					INT;
LI_SEQ_ROLODEX_ID 			ROLODEX.ROLODEX_ID%TYPE           		 := '';
LI_ORG_SEQ_ROLODEX_ID       ROLODEX.ROLODEX_ID%TYPE           		 := NULL;
LI_SPON_SEQ_ROLODEX_ID      ROLODEX.ROLODEX_ID%TYPE           		 := NULL;
LI_SEQ_SPONSOR_CODE 		SPONSOR.SPONSOR_CODE%TYPE         		 := NULL;
LI_SEQ_ORGANIZATION_ID 		ORGANIZATION.ORGANIZATION_ID%TYPE 		 := NULL;
LS_UPDATE_USER 				PERSON.USER_NAME%TYPE;		 
LS_LAST_NAME  				ROLODEX.LAST_NAME%TYPE            		 := NULL;
LS_FIRST_NAME  				ROLODEX.FIRST_NAME%TYPE           		 := NULL;
LS_MIDDLE_NAME  			ROLODEX.MIDDLE_NAME%TYPE          		 := NULL;
LS_ADDRESS_LINE_3 			ROLODEX.ADDRESS_LINE_3%TYPE       		 := NULL;
LS_COUNTY 					ROLODEX.COUNTY%TYPE               		 := NULL;
LS_OWNED_BY_UNIT 			ROLODEX.OWNED_BY_UNIT%TYPE        		 := '000001';
LS_COMMENTS 				ROLODEX.COMMENTS%TYPE             		 := 'Sponsor Base Address';
LS_SPONSOR_ADDRESS_FLAG 	ROLODEX.SPONSOR_ADDRESS_FLAG%TYPE        := 'Y';
LI_VER_NBR 					CHAR(1)                          		 := '1';
LS_ACTV_IND 				CHAR(1)            				  		 := 'Y';
LS_CABLE_ADDRESS		    ORGANIZATION.CABLE_ADDRESS%TYPE   		 := NULL;
LS_CONGRESSIONAL_DISTRICT   ORGANIZATION.CONGRESSIONAL_DISTRICT%TYPE := NULL;
LS_DUNS_PLUS_FOUR_NUMBER    ORGANIZATION.DUNS_PLUS_FOUR_NUMBER%TYPE  := NULL;
LS_ANSWER					VARCHAR2(10);
LS_EXPLANATION              ORGANIZATION_YNQ.EXPLANATION%TYPE        := NULL;
LD_REVIEW_DATE              ORGANIZATION_YNQ.REVIEW_DATE%TYPE        := NULL;
LS_ORG_ERROR_MESGE 			VARCHAR2(4000)						     := NULL;
LS_SPONSOR_ERROR_MESGE 		VARCHAR2(4000)						     := NULL;
LS_PERSON_ERROR             VARCHAR2(4000);
LS_ADDRESS                  VARCHAR2(4000)   := AV_ORG_ADDRESS_LINE_1||AV_ORG_CITY||','||AV_ORG_STATE||','||AV_ORG_POSTAL_CODE||','||AV_ORG_COUNTRY_CODE;

BEGIN
		BEGIN

			SELECT USER_NAME INTO LS_UPDATE_USER 
			FROM PERSON 
			WHERE PERSON_ID = AV_UPDATE_BY; 
            
        IF LS_UPDATE_USER IS NULL THEN 
        LS_UPDATE_USER := 'KCSO';
        END IF;

        EXCEPTION
		WHEN OTHERS THEN
			LS_UPDATE_USER := AV_UPDATE_BY;
			LS_PERSON_ERROR := 'Error fetching update user: ' || SQLERRM;
		END;	

	    BEGIN
	           LS_ADDRESS := SUBSTR(LS_ADDRESS,1,60);

		IF UPPER(AV_RISK_LEVEL) = 'LOW' THEN
		LS_ANSWER := 'Y';
		ELSIF UPPER(AV_RISK_LEVEL) = 'MEDIUM' OR  UPPER(AV_RISK_LEVEL) = 'HIGH' THEN
		LS_ANSWER := 'N';
		ELSIF UPPER(AV_RISK_LEVEL) = 'NOT APPLICABLE' THEN
		LS_ANSWER := 'X';
		END IF;

		IF (UPPER(IS_ORGANIZATION_SYNC_FLAG) = 'TRUE' OR IS_ORGANIZATION_SYNC_FLAG = 1) THEN 

        BEGIN 
		IF AV_ORGANIZATION_ID IS NULL THEN 


			 SELECT SEQ_ROLODEX_ID.NEXTVAL INTO LI_ORG_SEQ_ROLODEX_ID FROM dual;

 			INSERT INTO ROLODEX (ROLODEX_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, ORGANIZATION, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, EMAIL_ADDRESS, CITY, COUNTY, STATE, POSTAL_CODE, COMMENTS, PHONE_NUMBER, COUNTRY_CODE, SPONSOR_CODE, OWNED_BY_UNIT, SPONSOR_ADDRESS_FLAG, CREATE_USER, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID, ACTV_IND)
			VALUES (LI_ORG_SEQ_ROLODEX_ID, LS_LAST_NAME, LS_FIRST_NAME, LS_MIDDLE_NAME, AV_PRIMARY_NAME, AV_ORG_ADDRESS_LINE_1, AV_ORG_ADDRESS_LINE_2, LS_ADDRESS_LINE_3, AV_EMAIL_ADDRESS, AV_ORG_CITY, LS_COUNTY, AV_ORG_STATE, AV_ORG_POSTAL_CODE, LS_COMMENTS, AV_TELEPHONE_NUMBER, AV_ORG_COUNTRY_CODE, LI_SEQ_SPONSOR_CODE, LS_OWNED_BY_UNIT, LS_SPONSOR_ADDRESS_FLAG, LS_UPDATE_USER, SYSDATE(), LS_UPDATE_USER, LI_VER_NBR, SYS_GUID(), LS_ACTV_IND);

			 SELECT SEQ_ORGANIZATION_ID.NEXTVAL INTO LI_SEQ_ORGANIZATION_ID FROM dual;

			INSERT INTO ORGANIZATION (ORGANIZATION_ID, ORGANIZATION_NAME, CONTACT_ADDRESS_ID, ADDRESS, CABLE_ADDRESS, TELEX_NUMBER, COUNTY, CONGRESSIONAL_DISTRICT, INCORPORATED_IN, INCORPORATED_DATE, NUMBER_OF_EMPLOYEES, IRS_TAX_EXCEMPTION, FEDRAL_EMPLOYER_ID, MASS_TAX_EXCEMPT_NUM, AGENCY_SYMBOL, VENDOR_CODE, COM_GOV_ENTITY_CODE, MASS_EMPLOYEE_CLAIM, DUNS_NUMBER, DUNS_PLUS_FOUR_NUMBER, DODAC_NUMBER, CAGE_NUMBER, HUMAN_SUB_ASSURANCE, ANIMAL_WELFARE_ASSURANCE, SCIENCE_MISCONDUCT_COMPL_DATE, PHS_ACOUNT, NSF_INSTITUTIONAL_CODE, INDIRECT_COST_RATE_AGREEMENT, COGNIZANT_AUDITOR, ONR_RESIDENT_REP, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID, UEI, LOBBYING_REGISTRANT, LOBBYING_INDIVIDUAL, SAM_EXPIRATION_DATE, ENTITY_ID) 
			VALUES (LI_SEQ_ORGANIZATION_ID, AV_PRIMARY_NAME, LI_ORG_SEQ_ROLODEX_ID, LS_ADDRESS, LS_CABLE_ADDRESS, AV_TELEPHONE_NUMBER, LS_COUNTY, LS_CONGRESSIONAL_DISTRICT, AV_INCORPORATED_IN, AV_INCORPORATED_DATE, AV_NUMBER_OF_EMPLOYEES, AV_IRS_TAX_EXCEMPTION, AV_FEDRAL_EMPLOYER_ID, AV_MASS_TAX_EXCEMPT_NUM, AV_AGENCY_SYMBOL, AV_VENDOR_CODE, AV_COM_GOV_ENTITY_CODE, AV_MASS_EMPLOYEE_CLAIM, AV_DUNS_NUMBER, LS_DUNS_PLUS_FOUR_NUMBER, AV_DODAC_NUMBER, AV_CAGE_NUMBER, AV_HUMAN_SUB_ASSURANCE, AV_ANIMAL_WELFARE_ASS, AV_SCIENCE_MISCOMPL_DT, AV_PHS_ACOUNT, AV_NSF_INSTITUTIONAL_CODE, AV_INDIRECT_COST_RATE_AG, AV_COGNIZANT_AUDITOR, AV_ONR_RESIDENT_REP, SYSDATE(), LS_UPDATE_USER, LI_VER_NBR, SYS_GUID(),AV_UEI, AV_LOBBYING_REGISTRANT, AV_LOBBYING_INDIVIDUAL, AV_SAM_EXPIRATION_DATE, AV_ENTITY_ID);

            IF LS_ANSWER IS NOT NULL THEN
			INSERT INTO ORGANIZATION_YNQ (ORGANIZATION_ID, QUESTION_ID, ANSWER, EXPLANATION, REVIEW_DATE, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID) 
			VALUES (LI_SEQ_ORGANIZATION_ID, 'KC2', LS_ANSWER, LS_EXPLANATION, LD_REVIEW_DATE, SYSDATE(), LS_UPDATE_USER, LI_VER_NBR, SYS_GUID());
			END IF;


		ELSE

		    SELECT CONTACT_ADDRESS_ID INTO LI_ORG_SEQ_ROLODEX_ID 
		    FROM ORGANIZATION 
		    WHERE ORGANIZATION_ID = AV_ORGANIZATION_ID
		    AND CONTACT_ADDRESS_ID IS NOT NULL;


		    UPDATE ROLODEX SET LAST_NAME = LS_LAST_NAME, FIRST_NAME = LS_FIRST_NAME, MIDDLE_NAME = LS_MIDDLE_NAME, ORGANIZATION = AV_PRIMARY_NAME, ADDRESS_LINE_1 = AV_ORG_ADDRESS_LINE_1, ADDRESS_LINE_2 = AV_ORG_ADDRESS_LINE_2, ADDRESS_LINE_3 = LS_ADDRESS_LINE_3, EMAIL_ADDRESS = AV_EMAIL_ADDRESS, CITY = AV_ORG_CITY, COUNTY = LS_COUNTY, STATE = AV_ORG_STATE, POSTAL_CODE = AV_ORG_POSTAL_CODE, COMMENTS = LS_COMMENTS, PHONE_NUMBER = AV_TELEPHONE_NUMBER, COUNTRY_CODE = AV_ORG_COUNTRY_CODE, SPONSOR_CODE = AV_SPONCOR_CODE, OWNED_BY_UNIT = LS_OWNED_BY_UNIT, SPONSOR_ADDRESS_FLAG = LS_SPONSOR_ADDRESS_FLAG, CREATE_USER = LS_UPDATE_USER, UPDATE_TIMESTAMP = SYSDATE(), UPDATE_USER = LS_UPDATE_USER, VER_NBR = LI_VER_NBR, OBJ_ID = SYS_GUID(), ACTV_IND = LS_ACTV_IND 
		    WHERE ROLODEX_ID IN (LI_ORG_SEQ_ROLODEX_ID);

		    UPDATE ORGANIZATION SET ORGANIZATION_NAME = AV_PRIMARY_NAME, CONTACT_ADDRESS_ID = LI_ORG_SEQ_ROLODEX_ID, ADDRESS = LS_ADDRESS, CABLE_ADDRESS = LS_CABLE_ADDRESS, TELEX_NUMBER = AV_TELEPHONE_NUMBER, COUNTY = LS_COUNTY, CONGRESSIONAL_DISTRICT = LS_CONGRESSIONAL_DISTRICT, INCORPORATED_IN = AV_INCORPORATED_IN, INCORPORATED_DATE = AV_INCORPORATED_DATE, NUMBER_OF_EMPLOYEES = AV_NUMBER_OF_EMPLOYEES, IRS_TAX_EXCEMPTION = AV_IRS_TAX_EXCEMPTION, FEDRAL_EMPLOYER_ID = AV_FEDRAL_EMPLOYER_ID, MASS_TAX_EXCEMPT_NUM = AV_MASS_TAX_EXCEMPT_NUM, AGENCY_SYMBOL = AV_AGENCY_SYMBOL, VENDOR_CODE = AV_VENDOR_CODE, COM_GOV_ENTITY_CODE = AV_COM_GOV_ENTITY_CODE, MASS_EMPLOYEE_CLAIM = AV_MASS_EMPLOYEE_CLAIM, DUNS_NUMBER = AV_DUNS_NUMBER, DUNS_PLUS_FOUR_NUMBER = LS_DUNS_PLUS_FOUR_NUMBER, DODAC_NUMBER = AV_DODAC_NUMBER, CAGE_NUMBER = AV_CAGE_NUMBER, HUMAN_SUB_ASSURANCE = AV_HUMAN_SUB_ASSURANCE, ANIMAL_WELFARE_ASSURANCE = AV_ANIMAL_WELFARE_ASS, SCIENCE_MISCONDUCT_COMPL_DATE = AV_SCIENCE_MISCOMPL_DT, PHS_ACOUNT = AV_PHS_ACOUNT, NSF_INSTITUTIONAL_CODE = AV_NSF_INSTITUTIONAL_CODE, INDIRECT_COST_RATE_AGREEMENT = AV_INDIRECT_COST_RATE_AG, COGNIZANT_AUDITOR = AV_COGNIZANT_AUDITOR, ONR_RESIDENT_REP = AV_ONR_RESIDENT_REP, UPDATE_TIMESTAMP = SYSDATE(), UPDATE_USER = LS_UPDATE_USER, VER_NBR = LI_VER_NBR, OBJ_ID = SYS_GUID(),UEI = AV_UEI, LOBBYING_REGISTRANT = AV_LOBBYING_REGISTRANT, LOBBYING_INDIVIDUAL = AV_LOBBYING_INDIVIDUAL, SAM_EXPIRATION_DATE = AV_SAM_EXPIRATION_DATE, ENTITY_ID = AV_ENTITY_ID
		    WHERE ORGANIZATION_ID = AV_ORGANIZATION_ID;

             IF LS_ANSWER IS NOT NULL THEN
		    UPDATE ORGANIZATION_YNQ SET ANSWER = LS_ANSWER, UPDATE_TIMESTAMP = SYSDATE(), UPDATE_USER = LS_UPDATE_USER, VER_NBR = LI_VER_NBR, OBJ_ID = SYS_GUID() 
			WHERE ORGANIZATION_ID = AV_ORGANIZATION_ID;
		    END IF;
		END IF;

		    EXCEPTION
            WHEN OTHERS THEN
            LS_ORG_ERROR_MESGE := 'Error during organization sync: ' || SQLERRM;
        END;
        END IF;


		IF (UPPER(IS_SPONSOR_SYNC_FLAG) = 'TRUE' OR IS_SPONSOR_SYNC_FLAG = 1) THEN 

		        BEGIN

				IF AV_SPONCOR_CODE IS NULL THEN 

			   SELECT SEQ_ROLODEX_ID.NEXTVAL INTO LI_SPON_SEQ_ROLODEX_ID FROM dual;

 				INSERT INTO ROLODEX(ROLODEX_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, ORGANIZATION, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, EMAIL_ADDRESS, CITY, COUNTY, STATE, POSTAL_CODE, COMMENTS, PHONE_NUMBER, COUNTRY_CODE, SPONSOR_CODE, OWNED_BY_UNIT, SPONSOR_ADDRESS_FLAG, CREATE_USER, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID, ACTV_IND)
				VALUES (LI_SPON_SEQ_ROLODEX_ID, LS_LAST_NAME, LS_FIRST_NAME, LS_MIDDLE_NAME, AV_PRIMARY_NAME, AV_SPON_ADDRESS_LINE_1, AV_SPON_ADDRESS_LINE_2, LS_ADDRESS_LINE_3, AV_EMAIL_ADDRESS, AV_SPON_CITY, LS_COUNTY, AV_SPON_POSTAL_CODE, AV_SPON_POSTAL_CODE, LS_COMMENTS, AV_TELEPHONE_NUMBER, AV_SPON_COUNTRY_CODE, LI_SEQ_SPONSOR_CODE, LS_OWNED_BY_UNIT, LS_SPONSOR_ADDRESS_FLAG, LS_UPDATE_USER, SYSDATE(), LS_UPDATE_USER, LI_VER_NBR, SYS_GUID(), LS_ACTV_IND);

			 SELECT SEQ_SPONSOR_CODE.NEXTVAL INTO LI_SEQ_SPONSOR_CODE FROM dual;
				INSERT INTO SPONSOR (SPONSOR_CODE, SPONSOR_NAME, ACRONYM, SPONSOR_TYPE_CODE, DUN_AND_BRADSTREET_NUMBER, DODAC_NUMBER, CAGE_NUMBER, POSTAL_CODE, STATE, COUNTRY_CODE, ROLODEX_ID, AUDIT_REPORT_SENT_FOR_FY, OWNED_BY_UNIT, CREATE_USER, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID, ACTV_IND, DUNNING_CAMPAIGN_ID, CUSTOMER_NUMBER, UEI, ENTITY_ID) 
				VALUES (LI_SEQ_SPONSOR_CODE, AV_PRIMARY_NAME, AV_ACRONYM, AV_SPONSOR_TYPE_CODE, AV_DUNS_NUMBER, AV_DODAC_NUMBER, AV_CAGE_NUMBER, AV_SPON_POSTAL_CODE, AV_SPON_STATE, AV_SPON_COUNTRY_CODE, LI_SPON_SEQ_ROLODEX_ID, AV_AUDIT_REPORT_SENT, LS_OWNED_BY_UNIT, LS_UPDATE_USER, SYSDATE(), LS_UPDATE_USER, LI_VER_NBR, SYS_GUID(), LS_ACTV_IND, AV_DUNNING_CAMPAIGN_ID, AV_CUSTOMER_NUMBER, AV_UEI, AV_ENTITY_ID);


				UPDATE ROLODEX SET SPONSOR_CODE = LI_SEQ_SPONSOR_CODE WHERE ROLODEX_ID = LI_SPON_SEQ_ROLODEX_ID;


		ELSE

		        SELECT ROLODEX_ID INTO LI_SPON_SEQ_ROLODEX_ID  
				FROM SPONSOR 
				WHERE SPONSOR_CODE = AV_SPONCOR_CODE
				AND ROLODEX_ID IS NOT NULL; 

				UPDATE ROLODEX SET LAST_NAME = LS_LAST_NAME, FIRST_NAME = LS_FIRST_NAME, MIDDLE_NAME = LS_MIDDLE_NAME, ORGANIZATION = AV_PRIMARY_NAME, ADDRESS_LINE_1 = AV_SPON_ADDRESS_LINE_1, ADDRESS_LINE_2 = AV_SPON_ADDRESS_LINE_2, ADDRESS_LINE_3 = LS_ADDRESS_LINE_3, EMAIL_ADDRESS = AV_EMAIL_ADDRESS, CITY = AV_SPON_CITY, COUNTY = LS_COUNTY, STATE = AV_SPON_STATE, POSTAL_CODE = AV_SPON_POSTAL_CODE, COMMENTS = LS_COMMENTS, PHONE_NUMBER = AV_TELEPHONE_NUMBER, COUNTRY_CODE = AV_SPON_COUNTRY_CODE, SPONSOR_CODE = AV_SPONCOR_CODE, OWNED_BY_UNIT = LS_OWNED_BY_UNIT, SPONSOR_ADDRESS_FLAG = LS_SPONSOR_ADDRESS_FLAG, CREATE_USER = LS_UPDATE_USER, UPDATE_TIMESTAMP = SYSDATE(), UPDATE_USER = LS_UPDATE_USER, VER_NBR = LI_VER_NBR, OBJ_ID = SYS_GUID(), ACTV_IND = LS_ACTV_IND 
				WHERE ROLODEX_ID IN (LI_SPON_SEQ_ROLODEX_ID);

				UPDATE SPONSOR SET SPONSOR_NAME = AV_PRIMARY_NAME, ACRONYM = AV_ACRONYM, SPONSOR_TYPE_CODE = AV_SPONSOR_TYPE_CODE, DUN_AND_BRADSTREET_NUMBER = AV_DUNS_NUMBER, DODAC_NUMBER = AV_DODAC_NUMBER, CAGE_NUMBER = AV_CAGE_NUMBER, POSTAL_CODE = AV_SPON_POSTAL_CODE, STATE = AV_SPON_STATE, COUNTRY_CODE = AV_SPON_COUNTRY_CODE, ROLODEX_ID = LI_SPON_SEQ_ROLODEX_ID, AUDIT_REPORT_SENT_FOR_FY = AV_AUDIT_REPORT_SENT, OWNED_BY_UNIT = LS_OWNED_BY_UNIT, CREATE_USER = LS_UPDATE_USER, UPDATE_TIMESTAMP = SYSDATE(), UPDATE_USER = LS_UPDATE_USER, VER_NBR = LI_VER_NBR, OBJ_ID = SYS_GUID(), ACTV_IND = LS_ACTV_IND, DUNNING_CAMPAIGN_ID = AV_DUNNING_CAMPAIGN_ID, CUSTOMER_NUMBER = AV_CUSTOMER_NUMBER,UEI = AV_UEI, ENTITY_ID = AV_ENTITY_ID 
				WHERE SPONSOR_CODE = AV_SPONCOR_CODE;
		END IF;



            EXCEPTION
            WHEN OTHERS THEN
            LS_SPONSOR_ERROR_MESGE := 'Error during sponsor sync: ' || SQLERRM;
       END;

       END IF;			

		END;      


		IF LI_SEQ_SPONSOR_CODE IS NULL THEN 		
		LI_SEQ_SPONSOR_CODE := AV_SPONCOR_CODE;		
		END IF;

		IF LI_SEQ_ORGANIZATION_ID IS NULL THEN 
		LI_SEQ_ORGANIZATION_ID := AV_ORGANIZATION_ID;
		END IF;


		IF (UPPER(IS_ORGANIZATION_SYNC_FLAG) = 'TRUE' OR IS_ORGANIZATION_SYNC_FLAG = 1) AND LS_ORG_ERROR_MESGE IS NULL THEN 
		LS_ORG_ERROR_MESGE := 'SYNC_SUCCESS';
        ELSE 
        LI_SEQ_ORGANIZATION_ID := NULL;
		END IF;

        IF (UPPER(IS_SPONSOR_SYNC_FLAG) = 'TRUE' OR IS_SPONSOR_SYNC_FLAG = 1) AND LS_SPONSOR_ERROR_MESGE IS NULL THEN 
		LS_SPONSOR_ERROR_MESGE := 'SYNC_SUCCESS';
        ELSE 
        LI_SEQ_SPONSOR_CODE := NULL;
		END IF;

			OPEN CUR_GENERIC FOR SELECT LI_SEQ_SPONSOR_CODE AS SPONSOR_CODE,
			LI_SEQ_ORGANIZATION_ID AS ORGANIZATION_ID, LS_ORG_ERROR_MESGE AS ORG_ERROR,LS_SPONSOR_ERROR_MESGE AS SPONSOR_ERROR FROM DUAL;



END;

