DELIMITER //
CREATE PROCEDURE COI_SYNC_INSERT_DISCL_PROJECTS(
    IN AV_DISCLOSURE_ID INT,
        IN AV_DISCLOSURE_NUMBER INT,
        IN AV_PERSON_ID VARCHAR(40)
    )
    BEGIN

        INSERT INTO COI_DISCL_PROJECTS(DISCLOSURE_ID, DISCLOSURE_NUMBER, MODULE_CODE, MODULE_ITEM_KEY, UPDATED_BY, UPDATE_TIMESTAMP)
        SELECT AV_DISCLOSURE_ID, AV_DISCLOSURE_NUMBER, T.MODULE_CODE, T.MODULE_ITEM_KEY, AV_PERSON_ID, UTC_TIMESTAMP()
        FROM (
            SELECT EXTERNAL_SYSTEM_REF_ID AS MODULE_ITEM_KEY, 3 AS MODULE_CODE
            FROM COI_PROJECT_PROPOSAL_V T1
    		INNER JOIN COI_PROJECT_TYPE T4 ON T4.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
            WHERE KEY_PERSON_ID = AV_PERSON_ID AND T4.FCOI_NEEDED = 'Y' AND T4.IS_ACTIVE = 'Y'
            UNION
            SELECT T1.AWARD_NUMBER AS MODULE_ITEM_KEY, 1 AS MODULE_CODE
            FROM COI_PROJECT_AWARD_V T1
    		LEFT JOIN SPONSOR_DISCLOSURE_REQUIREMENTS T2 ON T2.SPONSOR_CODE = T1.SPONSOR_CODE
    		LEFT JOIN SPONSOR_DISCLOSURE_REQUIREMENTS T3 ON T3.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE
    		INNER JOIN COI_PROJECT_TYPE T4 ON T4.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
            WHERE T1.KEY_PERSON_ID = AV_PERSON_ID AND T1.PERSON_STATUS != 'I'
    		AND T1.AWARD_NUMBER NOT IN (
                SELECT MODULE_ITEM_KEY
                FROM COI_DISCL_PROJECTS
                WHERE DISCLOSURE_ID = AV_DISCLOSURE_ID AND MODULE_CODE = 1
            )  AND (((T2.KEY_PERSON_DISCL_REQUIREMENT = 'ALL' OR ( T2.KEY_PERSON_DISCL_REQUIREMENT = 'PI-COI' AND T1.KEY_PERSON_ROLE_CODE IN(1,3)))
    				OR (T3.KEY_PERSON_DISCL_REQUIREMENT = 'ALL' OR (T3.KEY_PERSON_DISCL_REQUIREMENT = 'PI-COI' AND T1.KEY_PERSON_ROLE_CODE IN(1,3))))
    			OR ((T1.PCK = 'PC' AND T1.KEY_PERSON_ROLE_CODE IN(1,3))
                    OR (T1.PCK = 'PCK' AND T1.KEY_PERSON_ROLE_CODE IN(1,2,3))
                )
    		)
    		AND T1.AWARD_STATUS_CODE IN (1,6,3)
    		AND T4.FCOI_NEEDED = 'Y' AND T4.IS_ACTIVE = 'Y'
            UNION
            SELECT T1.PROPOSAL_NUMBER AS MODULE_ITEM_KEY, 2 AS MODULE_CODE
            FROM COI_PROJECT_INSTITUTE_PROPOSAL_V T1
    		LEFT JOIN SPONSOR_DISCLOSURE_REQUIREMENTS T2 ON T2.SPONSOR_CODE = T1.SPONSOR_CODE
    		LEFT JOIN SPONSOR_DISCLOSURE_REQUIREMENTS T3 ON T3.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE
    		INNER JOIN COI_PROJECT_TYPE T4 ON T4.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
            WHERE T1.KEY_PERSON_ID = AV_PERSON_ID AND T1.PERSON_STATUS != 'I'
            AND T1.LINKED_AWARD_PROJECT_NUMBER IS NULL
    		AND T1.PROPOSAL_NUMBER NOT IN (
                SELECT MODULE_ITEM_KEY
                FROM COI_DISCL_PROJECTS
                WHERE DISCLOSURE_ID = AV_DISCLOSURE_ID AND MODULE_CODE = 2
            )  AND (((T2.KEY_PERSON_DISCL_REQUIREMENT = 'ALL' OR ( T2.KEY_PERSON_DISCL_REQUIREMENT = 'PI-COI' AND T1.KEY_PERSON_ROLE_CODE IN(1,3)))
    				OR (T3.KEY_PERSON_DISCL_REQUIREMENT = 'ALL' OR (T3.KEY_PERSON_DISCL_REQUIREMENT = 'PI-COI' AND T1.KEY_PERSON_ROLE_CODE IN(1,3)))
    			)
    			OR ((T1.PCK = 'PC' AND T1.KEY_PERSON_ROLE_CODE IN(1,3))
    			       OR (T1.PCK = 'PCK' AND T1.KEY_PERSON_ROLE_CODE IN(1,2,3))
    			)
    		)
    		AND T1.PROPOSAL_STATUS_CODE IN (1)
    		AND T4.FCOI_NEEDED = 'Y' AND T4.IS_ACTIVE = 'Y'
        ) T;

        SELECT COI_DISCL_PROJECTS_ID, MODULE_CODE, MODULE_ITEM_KEY
        FROM COI_DISCL_PROJECTS
        WHERE DISCLOSURE_ID = AV_DISCLOSURE_ID;
END
//
