DROP TABLE IF EXISTS entity_notes;
CREATE TABLE `entity_notes` (
  `NOTE_ID` int NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int NOT NULL,
  `TITLE` varchar(500) DEFAULT NULL,
  `CONTENT` text,
  `UPDATED_BY` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`NOTE_ID`),
  KEY `ENTITY_NOTE_FK1_idx` (`ENTITY_ID`),
  CONSTRAINT `ENTITY_NOTE_FK1` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`)
);

DROP TABLE IF EXISTS entity_section_note_ref;
CREATE TABLE entity_section_note_ref (
  ENTITY_SEC_NOTE_REF_ID int NOT NULL AUTO_INCREMENT,
  ENTITY_ID int DEFAULT NULL,
  ENTITY_SECTION_CODE varchar(3) NOT NULL,
  ENTITY_NOTE_ID int DEFAULT NULL,
  UPDATE_TIMESTAMP timestamp NULL DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (ENTITY_SEC_NOTE_REF_ID),
  KEY ENTITY_SEC_NOTE_REF_FK1_idx (ENTITY_ID),
  KEY ENTITY_SEC_NOTE_REF_FK2_idx (ENTITY_SECTION_CODE),
  KEY ENTITY_SEC_NOTE_REF_FK3_idx (ENTITY_NOTE_ID),
  CONSTRAINT ENTITY_SEC_NOTE_REF_FK1 FOREIGN KEY (ENTITY_ID) REFERENCES entity (ENTITY_ID),
  CONSTRAINT ENTITY_SEC_NOTE_REF_FK2 FOREIGN KEY (ENTITY_SECTION_CODE) REFERENCES entity_section (ENTITY_SECTION_CODE),
  CONSTRAINT ENTITY_SEC_NOTE_REF_FK3 FOREIGN KEY (ENTITY_NOTE_ID) REFERENCES entity_notes (NOTE_ID)
);
