
INSERT INTO rights (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'VIEW_ENTITY_OVERVIEW_NOTES', 'To view entity overview notes', 'quickstart', now(), '1');
INSERT INTO rights (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_ENTITY_OVERVIEW_NOTES', 'To manage entity overview notes', 'quickstart', now(), '1');
INSERT INTO rights (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'VIEW_ENTITY_SPONSOR_NOTES', 'To view entity sponsor notes', 'quickstart', now(), '1');
INSERT INTO rights (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_ENTITY_SPONSOR_NOTES', 'To manage entity sponsor notes', 'quickstart', now(), '1');
INSERT INTO rights (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'VIEW_ENTITY_ORGANIZATION_NOTES', 'To view entity organization notes', 'quickstart', now(), '1');
INSERT INTO rights (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_ENTITY_ORGANIZATION_NOTES', 'To manage entity organization notes', 'quickstart', now(), '1');
INSERT INTO rights (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'VIEW_ENTITY_COMPLIANCE_NOTES', 'To view entity compliance notes', 'quickstart', now(), '1');
INSERT INTO rights (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE) VALUES ((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A), 'MANAGE_ENTITY_COMPLIANCE_NOTES', 'To manage entity compliance notes', 'quickstart', now(), '1');

INSERT INTO entity_section (ENTITY_SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('5', 'General - Note', 'Y', now(), '10000000001');
INSERT INTO entity_section (ENTITY_SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('6', 'Sponsor - Note', 'Y', now(), '10000000001');
INSERT INTO entity_section (ENTITY_SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('7', 'Organization - Note', 'Y', now(), '10000000001');
INSERT INTO entity_section (ENTITY_SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('8', 'Compliance - Note', 'Y', now(), '10000000001');

INSERT INTO entity_section_access_right (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('1', '5', 'MANAGE_ENTITY_OVERVIEW_NOTES', now(), '10000000001');
INSERT INTO entity_section_access_right (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('2', '5', 'VIEW_ENTITY_OVERVIEW_NOTES', now(), '10000000001');
INSERT INTO entity_section_access_right (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('3', '6', 'MANAGE_ENTITY_SPONSOR_NOTES', now(), '10000000001');
INSERT INTO entity_section_access_right (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('4', '6', 'VIEW_ENTITY_SPONSOR_NOTES', now(), '10000000001');
INSERT INTO entity_section_access_right (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('5', '7', 'MANAGE_ENTITY_ORGANIZATION_NOTES', now(), '10000000001');
INSERT INTO entity_section_access_right (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('6', '7', 'VIEW_ENTITY_ORGANIZATION_NOTES', now(), '10000000001');
INSERT INTO entity_section_access_right (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('7', '8', 'MANAGE_ENTITY_COMPLIANCE_NOTES', now(), '10000000001');
INSERT INTO entity_section_access_right (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('8', '8', 'VIEW_ENTITY_COMPLIANCE_NOTES', now(), '10000000001');
