DROP TABLE IF EXISTS coi_int_stage_proposal_person;
DROP TABLE IF EXISTS coi_int_stage_proposal;
DROP TABLE IF EXISTS coi_int_stage_award_person;
DROP TABLE IF EXISTS coi_int_stage_award;

DROP PROCEDURE IF EXISTS COI_DISCL_ENT_PROJ_DETAILS;
DROP PROCEDURE IF EXISTS COI_DISCL_PROJ_ENTITY_INSERTION;
DROP PROCEDURE IF EXISTS COI_EVALUATE_VALIDATION;
DROP PROCEDURE IF EXISTS COI_SYNC_DISCLOSURE_RISK;
DROP PROCEDURE IF EXISTS COI_SYNC_FCOI_DISCLOSURE;
DROP PROCEDURE IF EXISTS COI_SYNC_INSERT_DISCL_PROJECTS;
DROP PROCEDURE IF EXISTS COI_VALIDATE_DISCLOSURE_CONFLICTS;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_HISTORY;
DROP PROCEDURE IF EXISTS GET_COI_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_PROJECTS;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_PROJECTS;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITIES;
DROP PROCEDURE IF EXISTS VALIDATE_PROJECT_DISCLOSURE;

DROP VIEW IF EXISTS coi_project_award_v;