ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL_PERSON ADD COLUMN STATUS VARCHAR(1) DEFAULT 'A' AFTER PERCENTAGE_OF_EFFORT;
ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL_PERSON ADD COLUMN CERTIFICATION_FLAG VARCHAR(20) DEFAULT NULL AFTER STATUS;
ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL_PERSON ADD COLUMN DISCLOSURE_REQUIRED_FLAG VARCHAR(20) DEFAULT NULL AFTER CERTIFICATION_FLAG;

ALTER TABLE `coi_discl_project_entity_rel`
DROP FOREIGN KEY `COI_DISCL_PROJECT_ENTITY_REL_FK1`;
ALTER TABLE `coi_discl_project_entity_rel` 
ADD CONSTRAINT `COI_DISCL_PROJECT_ENTITY_REL_FK1`
  FOREIGN KEY (`COI_DISCL_PROJECTS_ID`)
  REFERENCES `coi_discl_projects` (`COI_DISCL_PROJECTS_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


ALTER TABLE `coi_disclosure` 
DROP COLUMN `MODULE_ITEM_KEY`,
DROP COLUMN `MODULE_CODE`,
ADD COLUMN `COI_PROJECT_TYPE_CODE` VARCHAR(10) NULL AFTER `ADMIN_PERSON_ID`,
CHANGE COLUMN `UPDATE_USER` `UPDATED_BY` VARCHAR(60) NULL DEFAULT NULL ,
CHANGE COLUMN `CREATE_USER` `CREATED_BY` VARCHAR(60) NULL DEFAULT NULL ,
ADD INDEX `COI_DISCLOSURE_FK7_idx` (`COI_PROJECT_TYPE_CODE` ASC) VISIBLE;

ALTER TABLE `coi_disclosure`
ADD CONSTRAINT `COI_DISCLOSURE_FK7`
  FOREIGN KEY (`COI_PROJECT_TYPE_CODE`)
  REFERENCES `coi_project_type` (`COI_PROJECT_TYPE_CODE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  
UPDATE `coi_disclosure_fcoi_type` SET `DESCRIPTION` = 'Revision' WHERE (`FCOI_TYPE_CODE` = '3');
DELETE FROM `coi_disclosure_fcoi_type` WHERE (`FCOI_TYPE_CODE` = '4');
UPDATE `coi_disclosure_fcoi_type` SET `DESCRIPTION` = 'Project Disclosure' WHERE (`FCOI_TYPE_CODE` = '2');


ALTER TABLE `coi_project_type` 
ADD COLUMN `PROJECT_ICON` VARCHAR(45) NULL;

UPDATE `coi_project_type` SET `PROJECT_ICON` = 'workspace_premium' WHERE (`COI_PROJECT_TYPE_CODE` = '1');
UPDATE `coi_project_type` SET `PROJECT_ICON` = 'text_snippet' WHERE (`COI_PROJECT_TYPE_CODE` = '2');
UPDATE `coi_project_type` SET `PROJECT_ICON` = 'text_snippet' WHERE (`COI_PROJECT_TYPE_CODE` = '3');

  
ALTER TABLE `coi_disclosure` 
ADD COLUMN `SYNC_NEEDED` VARCHAR(1) NULL DEFAULT 'Y' AFTER `COI_PROJECT_TYPE_CODE`;

ALTER TABLE `coi_project_type` 
ADD COLUMN `FCOI_NEEDED` VARCHAR(1) NULL AFTER `PROJECT_ICON`,
ADD COLUMN `PROJECT_DISCLOSURE_NEEDED` VARCHAR(1) NULL AFTER `FCOI_NEEDED`;

ALTER TABLE `coi_conflict_history`
CHANGE COLUMN `DISCLOSURE_DETAILS_ID` `COI_DISCL_PROJECT_ENTITY_REL_ID` INT NOT NULL ;

ALTER TABLE `coi_conflict_history`
CHANGE COLUMN `UPDATE_USER` `UPDATED_BY` VARCHAR(60) NULL DEFAULT NULL ;


UPDATE `coi_project_type` SET `FCOI_NEEDED` = 'Y', `PROJECT_DISCLOSURE_NEEDED` = 'Y' WHERE (`COI_PROJECT_TYPE_CODE` = '1');
UPDATE `coi_project_type` SET `FCOI_NEEDED` = 'Y', `PROJECT_DISCLOSURE_NEEDED` = 'N' WHERE (`COI_PROJECT_TYPE_CODE` = '2');
UPDATE `coi_project_type` SET `FCOI_NEEDED` = 'N', `PROJECT_DISCLOSURE_NEEDED` = 'Y' WHERE (`COI_PROJECT_TYPE_CODE` = '3');

DROP TABLE `coi_discl_ent_proj_details`;
