ALTER TABLE consulting_disclosure CHANGE COLUMN UPDATE_USER UPDATED_BY VARCHAR(60) NULL DEFAULT NULL;
ALTER TABLE opa_disclosure CHANGE COLUMN UPDATE_USER UPDATED_BY VARCHAR(60) NULL DEFAULT NULL;
ALTER TABLE person_entity CHANGE COLUMN UPDATE_USER UPDATED_BY VARCHAR(60) NULL DEFAULT NULL;
