CREATE TABLE IF NOT EXISTS OPA_HR_ORG_UNIT_MAPPING 
( HR_ORG_UNIT_ID VARCHAR(8) NOT NULL,
 HR_ORG_UNIT_TITLE VARCHAR(75) DEFAULT NULL, 
 HR_ORG_UNIT_LEVEL VARCHAR(30) DEFAULT NULL,
 HR_DEPARTMENT_ID VARCHAR(8) DEFAULT NULL, 
 HR_DEPARTMENT_CODE_OLD VARCHAR(6) DEFAULT NULL,
 ORG_HIER_SCHOOL_AREA_NAME VARCHAR(75) DEFAULT NULL, 
 ORG_HIER_TOP_LEVEL_NAME VARCHAR(75) DEFAULT NULL,
 ORG_HIER_ROOT_NAME VARCHAR(75) DEFAULT NULL,
 WAREHOUSE_LOAD_DATE DATE DEFAULT NULL, 
 UPDATED_TIMESTAMP DATETIME DEFAULT NULL, 
 UPDATED_BY VARCHAR(60) DEFAULT NULL, 
 LAST_FED_TIMESTAMP DATETIME DEFAULT NULL,
 PRIMARY KEY (HR_ORG_UNIT_ID) );
