INSERT IGNORE INTO FORM_SECTION_COMPONENT_TYPE (COMPONENT_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER, SORT_ORDER) VALUES ('CR', 'Currency', 'Y', UTC_TIMESTAMP(), 'admin', '19');
INSERT INTO RIGHTS (
    RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE
)
SELECT 
    (SELECT MAX(RIGHT_ID) + 1 FROM RIGHTS) AS ID,
    'MAINTAIN_FORMBUILDER',
    'To access and modify form builder',
    'admin',
    UTC_TIMESTAMP(),
    '1'
WHERE NOT EXISTS (
    SELECT 1 FROM RIGHTS WHERE RIGHT_NAME = 'MAINTAIN_FORMBUILDER'
);


SET @sql := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_NAME = 'lock_configuration' 
       AND COLUMN_NAME = 'MODULE_KEY' 
       AND TABLE_SCHEMA = DATABASE()) = 0,
    'ALTER TABLE `lock_configuration` ADD COLUMN `MODULE_KEY` VARCHAR(45) NULL AFTER `UPDATE_TIMESTAMP`;',
    'DO 1'
);
 
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
     WHERE TABLE_NAME = 'form_builder_section_component' 
       AND COLUMN_NAME = 'IS_CAPTURE_DESCRIPTION' 
       AND TABLE_SCHEMA = DATABASE()) = 0,
    'ALTER TABLE `form_builder_section_component` ADD COLUMN `IS_CAPTURE_DESCRIPTION` VARCHAR(1) NULL AFTER `IS_MANDATORY`;',
    'DO 1'
);
 
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
