ANALYZE TABLE LEGACY_COI_ENGAGEMENTS;

SET @sql := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LEGACY_COI_ENGAGEMENTS' AND COLUMN_NAME = 'CERTIFICATION_DATE') = 0,

    'ALTER TABLE LEGACY_COI_ENGAGEMENTS ADD COLUMN CERTIFICATION_DATE DATE;',

    'DO 1'
);

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
