DELIMITER //
CREATE PROCEDURE `GET_APPROVERS_FOR_ROLE_TYPE`(
        AV_MODULE_CODE DECIMAL(38, 0),
        AV_MODULE_ITEM_ID VARCHAR(20),
        AV_ROLE_TYPE DECIMAL(38, 0),
        AV_SUBMODULE_CODE DECIMAL(38, 0),
        AV_SUB_MODULE_ITEM_KEY VARCHAR(20)
) DETERMINISTIC
BEGIN
DECLARE LI_RETURN DECIMAL(38, 0);
DECLARE LS_LEAD_UNIT VARCHAR(8);
DECLARE LS_SUBMITING_UNIT_NUMBER VARCHAR(8);
DECLARE LS_UNIT_ADMIN_TYPE_CODE DECIMAL(38, 0);
DECLARE LS_CREATE_USER VARCHAR(20);
DECLARE LS_CODE CHAR(5) DEFAULT '00000';
DECLARE LS_MSG TEXT;
DECLARE LI_MODULE_CODE INT(3);
DECLARE LS_MODULE_ITEM_KEY VARCHAR(20);
DECLARE LS_AWARD_ID VARCHAR(22);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_ACTIVE_AWARD_ID VARCHAR(22);
DECLARE LI_FLAG INT;
DECLARE LS_ADMIN_PERSON_ID VARCHAR(22);
DECLARE LI_GRANT_TYPE INT;
DECLARE LI_FUNDING_SCHEME_ID INT;
DECLARE LI_PERSON_COUNT INT;
DECLARE LS_PERSON_ID VARCHAR(50);
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
BEGIN
        GET DIAGNOSTICS CONDITION 1 LS_CODE = RETURNED_SQLSTATE,LS_MSG = MESSAGE_TEXT;
END;

IF AV_ROLE_TYPE = 52 THEN

		SELECT DISTINCT pr.PERSON_ID FROM PERSON_ROLES pr WHERE pr.ROLE_ID IN (SELECT ag.ROLE_ID FROM ADMIN_GROUP ag WHERE ag.MODULE_CODE = 8);

ELSEIF AV_ROLE_TYPE = 53 THEN
	IF AV_MODULE_CODE = 8 THEN
		SELECT DISTINCT d.PERSON_ID INTO LS_PERSON_ID FROM COI_DISCLOSURE d WHERE d.DISCLOSURE_ID = AV_MODULE_ITEM_ID;
        IF LS_PERSON_ID IS NULL THEN
                SELECT DISTINCT d.PERSON_ID INTO LS_PERSON_ID FROM LEGACY_COI_DISCLOSURE d WHERE d.COI_DISCLOSURE_NUMBER = LPAD(AV_MODULE_ITEM_ID, 10, '0');
        END IF;
        SELECT LS_PERSON_ID AS PERSON_ID;
	END IF;

ELSEIF AV_ROLE_TYPE = 54 THEN
		SELECT DISTINCT T1.PERSON_ID FROM PERSON_ROLES T1 INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID
        WHERE T2.MODULE_CODE=8;

ELSEIF AV_ROLE_TYPE = 55 THEN
	IF AV_MODULE_CODE = 8 THEN
		SELECT DISTINCT T1.ASSIGNEE_PERSON_ID AS PERSON_ID FROM COI_REVIEW T1 WHERE T1.DISCLOSURE_ID = AV_MODULE_ITEM_ID;
	END IF;

ELSEIF AV_ROLE_TYPE = 56 THEN
	IF AV_MODULE_CODE = 8 THEN
        SELECT DISTINCT d.ADMIN_PERSON_ID AS PERSON_ID FROM COI_DISCLOSURE d WHERE d.DISCLOSURE_ID = AV_MODULE_ITEM_ID;
    END IF;

ELSEIF AV_ROLE_TYPE = 57 THEN
	IF AV_MODULE_CODE = 8 THEN
		SELECT DISTINCT T1.ASSIGNEE_PERSON_ID AS PERSON_ID FROM COI_REVIEW T1 WHERE T1.COI_REVIEW_ID = AV_SUB_MODULE_ITEM_KEY;
	END IF;

ELSEIF AV_ROLE_TYPE = 58 THEN
    IF AV_MODULE_CODE = 26 THEN
       	SELECT DISTINCT PR.PERSON_ID AS PERSON_ID
	FROM PERSON_ROLES PR
	JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
	WHERE PR.ROLE_ID = 1345
	  AND P.STATUS = 'A';
    END IF;
ELSEIF AV_ROLE_TYPE = 59 THEN
    IF AV_MODULE_CODE = 26 THEN
        SELECT DISTINCT PERSON_ID FROM PERSON_ENTITY WHERE ENTITY_ID = AV_MODULE_ITEM_ID;
    END IF;

ELSEIF AV_ROLE_TYPE = 60 THEN
    IF AV_MODULE_CODE = 24 THEN
        SELECT DISTINCT PERSON_ID FROM PERSON_ENTITY WHERE PERSON_ENTITY_ID = AV_MODULE_ITEM_ID;
    END IF;

ELSEIF AV_ROLE_TYPE = 61 THEN
    IF AV_MODULE_CODE = 24 THEN
		SELECT DISTINCT t1.PERSON_ID FROM PERSON_ROLES t1
        INNER JOIN (SELECT ROLE_ID,RT.RIGHT_NAME FROM ROLE_RIGHTS RR, RIGHTS RT
        WHERE RR.RIGHT_ID = RT.RIGHT_ID AND RT.RIGHT_NAME IN
        ('MANAGE_TRAVEL_DISCLOSURE')) t2 ON t2.ROLE_ID = t1.ROLE_ID;
    END IF;

ELSEIF AV_ROLE_TYPE = 63 THEN
	IF AV_MODULE_CODE = 24 THEN
        SELECT DISTINCT d.ADMIN_PERSON_ID AS PERSON_ID FROM COI_TRAVEL_DISCLOSURE d WHERE d.TRAVEL_DISCLOSURE_ID = AV_MODULE_ITEM_ID;
    END IF;

ELSEIF AV_ROLE_TYPE = 62 THEN
    IF AV_MODULE_CODE = 24 THEN
		SELECT DISTINCT T1.PERSON_ID FROM PERSON_ROLES T1 INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID WHERE T2.MODULE_CODE=24;
    END IF;

ELSEIF AV_ROLE_TYPE = 64 THEN
	IF AV_MODULE_CODE = 24 THEN
        SELECT DISTINCT d.PERSON_ID AS PERSON_ID FROM COI_TRAVEL_DISCLOSURE d WHERE d.TRAVEL_DISCLOSURE_ID = AV_MODULE_ITEM_ID;
    END IF;

ELSEIF AV_ROLE_TYPE = 8065 THEN
    IF AV_MODULE_CODE IN (1, 2, 3) THEN
        IF AV_MODULE_CODE = 1 THEN
            SELECT DISTINCT LEAD_UNIT_NUMBER INTO LS_LEAD_UNIT
            FROM COI_PROJECT_AWARD_V
            WHERE EXTERNAL_SYSTEM_REF_ID = AV_MODULE_ITEM_ID;
        ELSEIF AV_MODULE_CODE = 2 THEN
            SELECT DISTINCT LEAD_UNIT_NUMBER INTO LS_LEAD_UNIT
            FROM COI_PROJECT_INSTITUTE_PROPOSAL_V
            WHERE EXTERNAL_SYSTEM_REF_ID = AV_MODULE_ITEM_ID;
        ELSEIF AV_MODULE_CODE = 3 THEN
            SELECT DISTINCT LEAD_UNIT_NUMBER INTO LS_LEAD_UNIT
            FROM COI_PROJECT_PROPOSAL_V
            WHERE EXTERNAL_SYSTEM_REF_ID = AV_MODULE_ITEM_ID;
        END IF;
        
        SELECT DISTINCT T1.PERSON_ID
        FROM UNIT_ADMINISTRATOR T1
        INNER JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID
        WHERE T1.UNIT_NUMBER = LS_LEAD_UNIT 
          AND T1.UNIT_ADMINISTRATOR_TYPE_CODE = 2
          AND T2.STATUS = 'A';
    END IF;  

    ELSEIF AV_ROLE_TYPE = 66 THEN
    IF AV_MODULE_CODE = 23 THEN
        SELECT HOME_UNIT INTO LS_LEAD_UNIT
                        FROM OPA_DISCLOSURE
                        WHERE OPA_DISCLOSURE_ID = AV_MODULE_ITEM_ID;

		 SELECT PR.PERSON_ID AS PERSON_ID
                FROM PERSON_ROLES PR
                JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
                WHERE PR.ROLE_ID = 1340
                        AND (
                                (PR.DESCEND_FLAG = 'Y' AND LS_LEAD_UNIT IN (
                                        SELECT CHILD_UNIT_NUMBER 
                                        FROM UNIT_WITH_CHILDREN 
                                        WHERE UNIT_NUMBER = PR.UNIT_NUMBER
                                ))
                                OR (PR.DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT)
                        )
                        AND P.STATUS = 'A';
    END IF;
    
    ELSEIF AV_ROLE_TYPE = 67 THEN
	IF AV_MODULE_CODE = 23 THEN
        SELECT DISTINCT d.ADMIN_PERSON_ID AS PERSON_ID FROM OPA_DISCLOSURE d WHERE d.opa_DISCLOSURE_ID = AV_MODULE_ITEM_ID;
    END IF;
    
    ELSEIF AV_ROLE_TYPE = 68 THEN
	IF AV_MODULE_CODE = 23 THEN
        SELECT DISTINCT d.PERSON_ID AS PERSON_ID FROM OPA_DISCLOSURE d WHERE d.opa_DISCLOSURE_ID = AV_MODULE_ITEM_ID;
    END IF;
    
    ELSEIF AV_ROLE_TYPE = 69 THEN
    IF AV_MODULE_CODE = 23 THEN
		SELECT DISTINCT T1.PERSON_ID FROM PERSON_ROLES T1 INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID WHERE T2.MODULE_CODE=23;
    END IF;
    
    ELSEIF AV_ROLE_TYPE = 70 THEN
	IF AV_MODULE_CODE = 23 THEN
		SELECT DISTINCT T1.ASSIGNEE_PERSON_ID AS PERSON_ID FROM OPA_REVIEW T1 WHERE T1.OPA_REVIEW_ID = AV_SUB_MODULE_ITEM_KEY;
	END IF;

    ELSEIF AV_ROLE_TYPE = 72 THEN
        IF AV_MODULE_CODE = 28 THEN
                SELECT PERSON_ID FROM COI_DECLARATION WHERE DECLARATION_ID = AV_MODULE_ITEM_ID;
        END IF;

        ELSEIF AV_ROLE_TYPE = 2301 THEN
        IF AV_MODULE_CODE = 23 THEN
         SELECT HOME_UNIT INTO LS_LEAD_UNIT
                        FROM OPA_DISCLOSURE
                        WHERE OPA_DISCLOSURE_ID = AV_MODULE_ITEM_ID;

			 SELECT DISTINCT PR.PERSON_ID AS PERSON_ID
                        FROM PERSON_ROLES PR
                        JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
                        WHERE PR.ROLE_ID = 1374
                                AND (
                                        (PR.DESCEND_FLAG = 'Y' AND LS_LEAD_UNIT IN (
                                                SELECT CHILD_UNIT_NUMBER 
                                                FROM UNIT_WITH_CHILDREN 
                                                WHERE UNIT_NUMBER = PR.UNIT_NUMBER
                                        ))
                                        OR (PR.DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT)
                                )
                                AND P.STATUS = 'A';
         END IF;

        ELSEIF AV_ROLE_TYPE = 2302 THEN
        IF AV_MODULE_CODE = 23 THEN
         SELECT HOME_UNIT INTO LS_LEAD_UNIT
                        FROM OPA_DISCLOSURE
                        WHERE OPA_DISCLOSURE_ID = AV_MODULE_ITEM_ID;

		 SELECT DISTINCT PR.PERSON_ID AS PERSON_ID
                FROM PERSON_ROLES PR
                JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
                WHERE PR.ROLE_ID = 1375
                        AND (
                                (PR.DESCEND_FLAG = 'Y' AND LS_LEAD_UNIT IN (
                                        SELECT CHILD_UNIT_NUMBER 
                                        FROM UNIT_WITH_CHILDREN 
                                        WHERE UNIT_NUMBER = PR.UNIT_NUMBER
                                ))
                                OR (PR.DESCEND_FLAG = 'N'
                AND PR.UNIT_NUMBER = LS_LEAD_UNIT)
                        )
                        AND P.STATUS = 'A';
        END IF;

          ELSEIF AV_ROLE_TYPE = 8002 THEN
                IF AV_MODULE_CODE = 8 THEN
        SELECT HOME_UNIT INTO LS_LEAD_UNIT
                        FROM COI_DISCLOSURE
                        WHERE DISCLOSURE_ID = AV_MODULE_ITEM_ID;

             SELECT DISTINCT PR.PERSON_ID AS PERSON_ID
                FROM PERSON_ROLES PR
                JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
                WHERE PR.ROLE_ID = 1376
                        AND (
                                (PR.DESCEND_FLAG = 'Y' AND LS_LEAD_UNIT IN (
                                        SELECT CHILD_UNIT_NUMBER 
                                        FROM UNIT_WITH_CHILDREN 
                                        WHERE UNIT_NUMBER = PR.UNIT_NUMBER
                                ))
                                OR (PR.DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT)
                        )
                        AND P.STATUS = 'A';
        END IF;
        
        ELSEIF AV_ROLE_TYPE = 2601 THEN
    IF AV_MODULE_CODE = 26 THEN
	SELECT DISTINCT PR.PERSON_ID AS PERSON_ID
	FROM PERSON_ROLES PR
	JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
	WHERE PR.ROLE_ID = 1350
	  AND P.STATUS = 'A';
    END IF;
    
    ELSEIF AV_ROLE_TYPE = 2303 THEN
        IF AV_MODULE_CODE = 23 THEN
        SELECT HOME_UNIT INTO LS_LEAD_UNIT
                        FROM OPA_DISCLOSURE
                        WHERE OPA_DISCLOSURE_ID = AV_MODULE_ITEM_ID;

		 SELECT DISTINCT PR.PERSON_ID AS PERSON_ID
                FROM PERSON_ROLES PR
                JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
                WHERE PR.ROLE_ID = 1378
                        AND (
                                (PR.DESCEND_FLAG = 'Y' AND LS_LEAD_UNIT IN (
                                        SELECT CHILD_UNIT_NUMBER 
                                        FROM UNIT_WITH_CHILDREN 
                                        WHERE UNIT_NUMBER = PR.UNIT_NUMBER
                                ))
                                OR (PR.DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT)
                        )
                        AND P.STATUS = 'A';
        END IF;
        
            ELSEIF AV_ROLE_TYPE = 8001 THEN
        IF AV_MODULE_CODE = 23 THEN
        SELECT HOME_UNIT INTO LS_LEAD_UNIT
                        FROM OPA_DISCLOSURE
                        WHERE OPA_DISCLOSURE_ID = AV_MODULE_ITEM_ID;

		 SELECT DISTINCT PR.PERSON_ID AS PERSON_ID
                FROM PERSON_ROLES PR
                JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
                WHERE PR.ROLE_ID = 1377
                AND (
                        (PR.DESCEND_FLAG = 'Y' AND LS_LEAD_UNIT IN (
                                SELECT CHILD_UNIT_NUMBER 
                                FROM UNIT_WITH_CHILDREN 
                                WHERE UNIT_NUMBER = PR.UNIT_NUMBER
                        ))
                        OR (PR.DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT)
                )
                AND P.STATUS = 'A';
        END IF;

        ELSEIF AV_ROLE_TYPE = 2602 THEN
                IF AV_MODULE_CODE = 26 THEN
                        SELECT DISTINCT PR.PERSON_ID AS PERSON_ID
                        FROM PERSON_ROLES PR
                        JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
                        WHERE PR.ROLE_ID = 1380
                        AND P.STATUS = 'A';
                END IF;

ELSEIF AV_ROLE_TYPE = 8066 THEN

     IF AV_MODULE_CODE = 28 THEN
        SELECT t2.HOME_UNIT INTO LS_LEAD_UNIT
            FROM COI_DECLARATION t1
            INNER JOIN PERSON t2 ON t2.PERSON_ID = t1.PERSON_ID
            WHERE t1.DECLARATION_ID = AV_MODULE_ITEM_ID;

		 SELECT DISTINCT PR.PERSON_ID AS PERSON_ID
                FROM PERSON_ROLES PR
                JOIN PERSON P ON PR.PERSON_ID = P.PERSON_ID
                WHERE PR.ROLE_ID = 1384
                AND (
                        (PR.DESCEND_FLAG = 'Y' AND LS_LEAD_UNIT IN (
                                SELECT CHILD_UNIT_NUMBER
                                FROM UNIT_WITH_CHILDREN
                                WHERE UNIT_NUMBER = PR.UNIT_NUMBER
                        ))
                        OR (PR.DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT)
                )
                AND P.STATUS = 'A';
     END IF;
ELSEIF AV_ROLE_TYPE = 8067 THEN
    IF AV_MODULE_CODE = 28 THEN
        SELECT DISTINCT d.ADMIN_PERSON_ID AS PERSON_ID FROM COI_DECLARATION d WHERE d.DECLARATION_ID = AV_MODULE_ITEM_ID;
    END IF;

END IF;

END
//
