DELIMITER //
CREATE PROCEDURE `GET_DECLARATION_DETAILS` (
	AV_COLUMN_NAMES           	VARCHAR(4000),
    AV_MODULE_ITEM_KEY         	INT,
	AV_SUB_MODULE_ITEM_KEY      INT
)
BEGIN
DECLARE LS_DYN_SQL 					LONGTEXT;

SET LS_DYN_SQL = CONCAT('SELECT ', AV_COLUMN_NAMES, ' FROM
	(SELECT t1.DECLARATION_ID,
        t1.DECLARATION_NUMBER,
        t1.PERSON_ID,
        t1.DECLARATION_TYPE_CODE,
        t3.DESCRIPTION AS DECLARATION_TYPE,
        t1.DECLARATION_STATUS_CODE,
        t4.DESCRIPTION AS DECLARATION_STATUS,
        DATE_FORMAT(t1.SUBMISSION_DATE, ''%m-%d-%Y'') AS CERTIFICATION_DATE,
        DATE_FORMAT(t1.EXPIRATION_DATE, ''%m-%d-%Y'') AS EXPIRATION_DATE,
        t1.REVIEW_STATUS_CODE,
        t5.DESCRIPTION as REVIEW_STATUS,
        t6.UNIT_NAME AS DEPARTMENT_NAME,
        t2.HOME_UNIT AS DEPARTMENT_NUMBER,
        t2.FULL_NAME AS REPORTER_NAME,
        t7.FULL_NAME AS ADMINISTRATOR_NAME,
        t8.FULL_NAME AS UPDATED_USER_FULL_NAME
    FROM COI_DECLARATION t1
    INNER JOIN PERSON t2 ON t2.PERSON_ID=t1.PERSON_ID
    INNER JOIN COI_DECLARATION_TYPE t3 ON t3.DECLARATION_TYPE_CODE = t1.DECLARATION_TYPE_CODE
    INNER JOIN COI_DECLARATION_STATUS t4 ON t4.DECLARATION_STATUS_CODE = t1.DECLARATION_STATUS_CODE
    INNER JOIN DECLARATION_REVIEW_STATUS_TYPE t5 ON t5.REVIEW_STATUS_CODE = t1.REVIEW_STATUS_CODE
    INNER JOIN UNIT t6 ON t6.UNIT_NUMBER = t2.HOME_UNIT
    LEFT JOIN PERSON t7 ON t7.PERSON_ID = t1.ADMIN_PERSON_ID
    LEFT JOIN PERSON t8 ON t8.PERSON_ID = t1.UPDATED_BY
    WHERE t1.DECLARATION_ID = ', AV_MODULE_ITEM_KEY, ') T');

SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
END
//
