DELIMITER //
CREATE PROCEDURE `GET_PERSON_ENTITY_INFO`(IN AV_PERSON_ENTITY_ID INT)
BEGIN
  SELECT
        t0.PERSON_ENTITY_ID,
        t0.PERSON_ID,
        t0.ENTITY_NUMBER,
        t5.ENTITY_NAME,
        t6.DESCRIPTION AS ENTITY_TYPE,
        t7.COUNTRY_NAME,
        GROUP_CONCAT(DISTINCT CONCAT(t3.DESCRIPTION, ': ', grouped_descriptions) ORDER BY t3.DESCRIPTION SEPARATOR ':;:') AS REL,
        t0.INVOLVEMENT_START_DATE,
        t0.INVOLVEMENT_END_DATE,
		t8.DESCRIPTION as ENTITY_STATUS,
        t0.IS_FORM_COMPLETED,
        t0.VERSION_STATUS,
        t9.DESCRIPTION AS RISK_CATEGORY
    FROM person_entity t0 
    LEFT OUTER JOIN person_entity_relationship t1 ON t1.PERSON_ENTITY_ID = t0.PERSON_ENTITY_ID
    LEFT OUTER JOIN valid_person_entity_rel_type t2 ON t1.VALID_PERS_ENTITY_REL_TYP_CODE = t2.VALID_PERS_ENTITY_REL_TYP_CODE
    LEFT OUTER JOIN coi_disclosure_type t3 ON t2.DISCLOSURE_TYPE_CODE = t3.DISCLOSURE_TYPE_CODE
    LEFT OUTER JOIN person_entity_rel_type t4 ON t4.RELATIONSHIP_TYPE_CODE = t2.RELATIONSHIP_TYPE_CODE
    INNER JOIN entity t5 ON t5.ENTITY_ID = t0.ENTITY_ID
    INNER JOIN entity_type t6 ON t6.ENTITY_TYPE_CODE = t5.ENTITY_TYPE_CODE
    INNER JOIN country t7 ON t7.COUNTRY_CODE = t5.COUNTRY_CODE
	INNER JOIN entity_status t8 on t8.ENTITY_STATUS_CODE = t5.ENTITY_STATUS_CODE
    INNER JOIN entity_risk_category t9 ON t9.RISK_CATEGORY_CODE = t5.RISK_CATEGORY_CODE
    LEFT JOIN (
        SELECT t0.PERSON_ENTITY_ID, t3.DESCRIPTION, GROUP_CONCAT(DISTINCT t4.DESCRIPTION ORDER BY t4.DESCRIPTION SEPARATOR '/') AS grouped_descriptions
        FROM  person_entity t0
        LEFT OUTER JOIN person_entity_relationship t1 ON t1.PERSON_ENTITY_ID = t0.PERSON_ENTITY_ID
        LEFT OUTER JOIN VALID_PERSON_ENTITY_REL_TYPE t2 ON t1.VALID_PERS_ENTITY_REL_TYP_CODE = t2.VALID_PERS_ENTITY_REL_TYP_CODE
        LEFT OUTER JOIN coi_disclosure_type t3 ON t2.DISCLOSURE_TYPE_CODE = t3.DISCLOSURE_TYPE_CODE
        LEFT OUTER JOIN person_entity_rel_type t4 ON t4.RELATIONSHIP_TYPE_CODE = t2.RELATIONSHIP_TYPE_CODE	
        WHERE t0.person_entity_id = AV_PERSON_ENTITY_ID
        GROUP BY t0.PERSON_ENTITY_ID, t3.DESCRIPTION
    ) AS subquery 
	ON t0.PERSON_ENTITY_ID = subquery.PERSON_ENTITY_ID AND t3.DESCRIPTION = subquery.DESCRIPTION
    WHERE t0.PERSON_ENTITY_ID = AV_PERSON_ENTITY_ID
    GROUP BY t0.PERSON_ENTITY_ID, t0.PERSON_ID, t0.ENTITY_NUMBER, t5.ENTITY_NAME;
END
//
