DELIMITER //
CREATE FUNCTION FN_CHK_CAN_CREATE_DECLARATION(
    AV_PERSON_ID VARCHAR(40),
    AV_DECLARATION_TYPE_CODE VARCHAR(3)
) RETURNS BOOLEAN
    DETERMINISTIC
BEGIN

    DECLARE LI_SFI_FLAG BOOLEAN DEFAULT FALSE;

    SELECT EXISTS (SELECT 1 FROM DECLARATION_PERSON_ELIGIBILITY WHERE PERSON_ID = AV_PERSON_ID
        AND DECLARATION_TYPE_CODE = 1
        AND (CAN_CREATE_DECLARATION = 'Y' OR ADMIN_FORCE_ALLOWED_TO_CREATE = 'Y')) INTO LI_SFI_FLAG;

    RETURN LI_SFI_FLAG;
END
//
