INSERT IGNORE INTO DYN_SECTION_CONFIG (SECTION_CODE, MODULE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER)
    VALUES('OPA232', 'OPA23', 'OPA Disclosure Actions', 'Y', UTC_TIMESTAMP(), 'admin');

INSERT IGNORE INTO DYN_SUBSECTION_CONFIG (SUB_SECTION_CODE, SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER)
    VALUES('232', 'OPA232', 'OPA Disclosure Actions', 'Y', UTC_TIMESTAMP(), 'admin');

INSERT INTO DYN_ELEMENT_CONFIG (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
    SELECT 'opa-print-modal-header', 'OPA Disclosure Print Modal Header', '232', 'OPA232', UTC_TIMESTAMP(), 'admin'
    WHERE NOT EXISTS (SELECT 1 FROM DYN_ELEMENT_CONFIG WHERE UI_REFERENCE_ID = 'opa-print-modal-header');
