INSERT INTO dyn_section_config (SECTION_CODE, MODULE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('COI808', 'COI8', 'Disclosure Engagement', 'Y', now(), 'admin');
INSERT INTO dyn_section_config (SECTION_CODE, MODULE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('TD2402', 'TD24', 'Travel Certificaton', 'Y', now(), 'admin');

INSERT INTO dyn_subsection_config (SUB_SECTION_CODE, SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('814', 'COI808', 'Disclosure Engagement', 'Y', now(), 'admin');
INSERT INTO dyn_subsection_config (SUB_SECTION_CODE, SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('2402', 'TD2402', 'Travel Certification', 'Y', now(), 'admin');

INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, INSTRUCTION, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-disc-proj-rel-info-text', 'Disclosure Relationship', '803', 'COI803', 'Below is a list of your project(s) and engagement(s). Please review each and indicate whether you have a conflict of interest.', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, INSTRUCTION, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-disc-eng-info-text', 'Disclosure Engagement', '814', 'COI808', '>> Here is a list of your Completed, Incomplete, and Inactive Engagements, which you can filter as needed.\n\n>> An Incomplete Engagement must be either Completed or Inactivated before establishing a Project-Engagement relationship.\n\n>> To make changes to an Engagement, click the Modify button.\n\n>> Ensure you have the most up-to-date list of Completed Engagements before proceeding to the next step', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-travel-destination-details', 'Travel Destination Trip title', '2401', 'TD2401', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('travel-discl-stay-start', 'Travel start date', '2401', 'TD2401', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('travel-disclosure-stay-end', 'Travel enddate', '2401', 'TD2401', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, INSTRUCTION, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-travel-cert-info-text', 'Travel certification info', '2402', 'TD2402', 'University policy requires that university officers, faculty, and staff and others acting on its behalf avoid ethical, legal, financial, and other conflicts of interest and ensure that their activities and interests do not conflict with their obligations to the University. Disclosure of financial interests enables the University to determine if a financial interest creates a conflict of interest or the appearance of a conflict of interest. The existence of a conflict or the appearance of one does not imply wrongdoing and does not necessarily mean that a researcher may not retain his or her financial interest and undertake the affected research. Often the University can work with the researcher to manage a conflict or the appearance  of a conflict so that the research can continue in a way that minimizes the possibility of bias and preserves the objectivity of the research. Proper management depends on full and prompt disclosure. COI provides the ability to disclose and maintain your Engagements; identify potential areas of concern related to your proposals and awards; and, disclose reimbursed travel (for NIH compliance).', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, INSTRUCTION, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-travel-cert-cnfrm-text', 'Travel certification confirmation text', '2402', 'TD2402', 'I agree to abide by the University COI policy guidelines and certify that the information provided for the Financial conflict of interest, including, responses to screening questions, list of my pertinent Engagements and possible relationship to my sponsored activity is an accurate and current statement of my reportable outside interests and activities.', 'admin', now());
