DELIMITER //
CREATE PROCEDURE `COI_SYNC_UPDATE_DISCL_INTEG_UPDATES`(
	AV_MODULE_CODE          INT,
	AV_MODULE_ITEM_KEY		VARCHAR(100)
)
BEGIN

	UPDATE COI_DISCLOSURE T1
	INNER JOIN COI_DISCL_PROJECTS T2 ON T2.DISCLOSURE_ID = T1.DISCLOSURE_ID
	SET SYNC_NEEDED = 'Y'
	WHERE T2.MODULE_CODE = AV_MODULE_CODE AND T2.MODULE_ITEM_KEY = AV_MODULE_ITEM_KEY AND T1.REVIEW_STATUS_CODE IN (1,5,6);

END
//