DELIMITER //
CREATE PROCEDURE `COI_SYNC_UPDATE_DISCL_INTEG_UPDATES`(
	AV_MODULE_CODE          INT,
	AV_MODULE_ITEM_KEY		VARCHAR(100)
)
BEGIN

	UPDATE COI_DISCLOSURE T1
	LEFT JOIN COI_DISCL_PROJECTS T2 ON T2.DISCLOSURE_ID = T1.DISCLOSURE_ID
	LEFT JOIN COI_PROJECT_INSTITUTE_PROPOSAL_V T3 ON T3.PROPOSAL_NUMBER = AV_MODULE_ITEM_KEY AND AV_MODULE_CODE = 2
	LEFT JOIN COI_PROJECT_AWARD_V T4 ON T4.AWARD_NUMBER = AV_MODULE_ITEM_KEY AND AV_MODULE_CODE = 1
	SET SYNC_NEEDED = 'Y'
	WHERE ((T2.MODULE_CODE = AV_MODULE_CODE AND T2.MODULE_ITEM_KEY = AV_MODULE_ITEM_KEY) OR T3.KEY_PERSON_ID = T1.PERSON_ID
	    OR T4.KEY_PERSON_ID = T1.PERSON_ID )
	AND T1.REVIEW_STATUS_CODE IN (1,5,6);

END
//