ALTER TABLE OPA_CYCLES ADD COLUMN FREQUENCY VARCHAR(20) DEFAULT NULL;

ALTER TABLE OPA_DISCLOSURE 
ADD COLUMN VERSION_NUMBER INT NULL AFTER CERTIFIED_BY,
ADD COLUMN VERSION_STATUS VARCHAR(45) NULL AFTER VERSION_NUMBER;

SET SQL_SAFE_UPDATES = 0;
UPDATE OPA_CYCLES SET FREQUENCY = 'YEARLY';
UPDATE OPA_DISCLOSURE SET VERSION_STATUS = 'ACTIVE', VERSION_NUMBER = 1 WHERE REVIEW_STATUS_CODE = 4 AND DISPOSITION_STATUS_CODE = 3;
UPDATE OPA_DISCLOSURE SET VERSION_STATUS = 'PENDING', VERSION_NUMBER = 1 WHERE DISPOSITION_STATUS_CODE = 1;
SET SQL_SAFE_UPDATES = 1;

INSERT INTO OPA_ACTION_LOG_TYPE (ACTION_TYPE_CODE, MESSAGE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('21', 'OPA disclosure <b>revised</b> by <b>{REPORTER}</b>', 'Revised', NOW(), 'quickstart');

INSERT INTO MESSAGE (MESSAGE_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('8032', 'OPA disclosure Revision Required', NOW(), 'quickstart');
