ALTER TABLE `LEGACY_COI_ENGAGEMENTS` RENAME COLUMN `UPDATE_USER` TO `UPDATED_BY`;
ALTER TABLE `LEGACY_COI_ENGAGEMENTS` MODIFY COLUMN UPDATED_BY VARCHAR(40) DEFAULT NULL;
ALTER TABLE `LEGACY_COI_ENGAGEMENTS` ADD COLUMN `IS_FINANCIAL` CHAR(1) DEFAULT NULL AFTER `IS_TRAVEL`;
