DROP PROCEDURE IF EXISTS FCOI_DISCL_RENWAL_REMNDR_SUMRY;
DROP PROCEDURE IF EXISTS FCOI_DISCLOSRE_RENEWAL_REMINDER;
DROP PROCEDURE IF EXISTS GET_EXPIRING_FCOI_AND_OPA_DISCLOSURES;
DROP PROCEDURE IF EXISTS OPA_DISCL_RENEWAL_REMINDER;
DROP PROCEDURE IF EXISTS OPA_DISCL_RENWAL_REMNDR_SUMRY;
DROP PROCEDURE IF EXISTS FCOI_DIS_RNWL_RMNDR_MNTLY_SMRY;
DROP PROCEDURE IF EXISTS OPA_DIS_RNWAL_RMNDR_MNTLY_SMRY;
