\. ./FIBI-COI-5.8.2/FC-1650/Procedures/FCOI_DISCL_RENWAL_REMNDR_SUMRY.sql
\. ./FIBI-COI-5.8.2/FC-1650/Procedures/FCOI_DISCLOSRE_RENEWAL_REMINDER.sql
\. ./FIBI-COI-5.8.2/FC-1650/Procedures/GET_EXPIRING_FCOI_AND_OPA_DISCLOSURES.sql
\. ./FIBI-COI-5.8.2/FC-1650/Procedures/OPA_DISCL_RENEWAL_REMINDER.sql
\. ./FIBI-COI-5.8.2/FC-1650/Procedures/OPA_DISCL_RENWAL_REMNDR_SUMRY.sql
\. ./FIBI-COI-5.8.2/FC-1650/Procedures/FCOI_DIS_RNWL_RMNDR_MNTLY_SMRY.sql
\. ./FIBI-COI-5.8.2/FC-1650/Procedures/OPA_DIS_RNWAL_RMNDR_MNTLY_SMRY.sql
