INSERT INTO `BUSINESS_RULE_FUNCTION` (`FUNCTION_NAME`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`DB_FUNCTION_NAME`,`UPDATE_TIMESTAMP`,`UPDATE_USER`)
VALUES ('Check engagement has commitment',8,801,'Check engagement has commitment','FN_IS_ENG_HAS_COMMITMENT',now(),'quickstart');

INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`,`ARGUMENT_SEQUENCE_NUMBER`,`ARGUMENT_NAME`,`DESCRIPTION`,`DATA_TYPE`,`DEFAULT_VALUE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`LOOKUP_WINDOW_NAME`,`LOOKUP_TYPE`,`ARGUMENT_TYPE`,`ARGUMENT_LABEL`)
VALUES ('Check engagement has commitment',1,'AV_PERSON_ENTITY_ID','Check engagement has commitment',NULL,NULL,now(),'quickstart',NULL,NULL,NULL,NULL);
