DELIMITER //
CREATE FUNCTION COI_INT_PRSN_DISCL_EXP_DATE(
AV_PERSON_ID  VARCHAR(40),
AV_TYPE_CODE VARCHAR(3)
) RETURNS varchar(20) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
	DECLARE LS_EXP_DATE VARCHAR(20);
	DECLARE LS_EVENT_TYPE_CODE INT;

SELECT DATE_FORMAT(MAX(CD.EXPIRATION_DATE), '%Y-%m-%d') INTO  LS_EXP_DATE 
		FROM COI_DISCLOSURE CD
		WHERE CD.PERSON_ID = AV_PERSON_ID 
		  AND CD.DISPOSITION_STATUS_CODE = '3' 
		  AND CD.FCOI_TYPE_CODE = AV_TYPE_CODE
		  AND CD.DISCLOSURE_ID = (SELECT MAX(DISCLOSURE_ID) 
								   FROM COI_DISCLOSURE 
								   WHERE PERSON_ID = CD.PERSON_ID 
								   AND DISPOSITION_STATUS_CODE = CD.DISPOSITION_STATUS_CODE
                                   AND FCOI_TYPE_CODE = CD.FCOI_TYPE_CODE);
	-- If LS_EXP_DATE is NULL, check for legacy disclosures
	IF LS_EXP_DATE IS NULL THEN

		IF AV_TYPE_CODE <> 2 THEN
			IF AV_TYPE_CODE = 1 THEN
				SET LS_EVENT_TYPE_CODE = 5; -- Annual
			ELSEIF AV_TYPE_CODE = 3 THEN
				SET LS_EVENT_TYPE_CODE = 6; -- Revision
			END IF;

			SELECT DATE_FORMAT(MAX(CD.EXPIRATION_DATE), '%Y-%m-%d') INTO LS_EXP_DATE
			FROM LEGACY_COI_DISCLOSURE CD
			WHERE CD.PERSON_ID = AV_PERSON_ID
			AND CD.DISCLOSURE_DISPOSITION_CODE = 1
			AND CD.EVENT_TYPE_CODE = LS_EVENT_TYPE_CODE
			AND CD.LEGACY_DISCLOSURE_ID = (SELECT MAX(LEGACY_DISCLOSURE_ID)
									FROM LEGACY_COI_DISCLOSURE
									WHERE PERSON_ID = CD.PERSON_ID
									AND DISCLOSURE_DISPOSITION_CODE = CD.DISCLOSURE_DISPOSITION_CODE
									AND EVENT_TYPE_CODE = CD.EVENT_TYPE_CODE);
		ELSE
			SELECT DATE_FORMAT(MAX(CD.EXPIRATION_DATE), '%Y-%m-%d') INTO LS_EXP_DATE
			FROM LEGACY_COI_DISCLOSURE CD
			WHERE CD.PERSON_ID = AV_PERSON_ID
			AND CD.DISCLOSURE_DISPOSITION_CODE = 1
			AND CD.EVENT_TYPE_CODE IN (1, 2) -- Award or Project
			AND CD.LEGACY_DISCLOSURE_ID = (SELECT MAX(LEGACY_DISCLOSURE_ID)
									FROM LEGACY_COI_DISCLOSURE
									WHERE PERSON_ID = CD.PERSON_ID
									AND DISCLOSURE_DISPOSITION_CODE = CD.DISCLOSURE_DISPOSITION_CODE
									AND EVENT_TYPE_CODE = CD.EVENT_TYPE_CODE);
		END IF;
	END IF;

RETURN LS_EXP_DATE;	
END
//
