
ALTER TABLE `discl_attachment` CHANGE COLUMN `DESCRIPTION` `DESCRIPTION` VARCHAR(500) NULL DEFAULT NULL ;

ALTER TABLE `entity` CHANGE COLUMN `REVISION_REASON` `REVISION_REASON` VARCHAR(500) NULL DEFAULT NULL ;

