INSERT INTO `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`,`ACTION_TYPE`,`MODULE_CODE`,`SUB_MODULE_CODE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (77,'FCOI_ADMIN_REMOVE',8,0,'Y','FCOI Admin Removal',now(),'admin');
INSERT INTO `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`,`ACTION_TYPE`,`MODULE_CODE`,`SUB_MODULE_CODE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (78,'PROJECT_ADMIN_REMOVE',8,0,'Y','Project Admin Removal',now(),'admin');
INSERT INTO `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`,`ACTION_TYPE`,`MODULE_CODE`,`SUB_MODULE_CODE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (79,'TRAVEL_ADMIN_REMOVE',24,0,'Y','Travel Admin Removal',now(),'admin');

INSERT INTO `MQ_ROUTER_ACTION_CONFIGURATION` (`ACTION_TYPE`,`IS_ACTIVE`,`MODULE_CODE`,`QUEUE_NAME`,`SUB_MODULE_CODE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('FCOI_ADMIN_REMOVE','Y',8,'Q_NOTIFICATION',0,now(),'admin');
INSERT INTO `MQ_ROUTER_ACTION_CONFIGURATION` (`ACTION_TYPE`,`IS_ACTIVE`,`MODULE_CODE`,`QUEUE_NAME`,`SUB_MODULE_CODE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('PROJECT_ADMIN_REMOVE','Y',8,'Q_NOTIFICATION',0,now(),'admin');
INSERT INTO `MQ_ROUTER_ACTION_CONFIGURATION` (`ACTION_TYPE`,`IS_ACTIVE`,`MODULE_CODE`,`QUEUE_NAME`,`SUB_MODULE_CODE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('TRAVEL_ADMIN_REMOVE','Y',24,'Q_NOTIFICATION',0,now(),'admin');

UPDATE `NOTIFY_ACTION_TYPE_MAP` SET `MODULE_ACTION_TYPE_ID` = '77' WHERE (`NOTIFICATION_TYPE_ID` = '8005');
UPDATE `NOTIFY_ACTION_TYPE_MAP` SET `MODULE_ACTION_TYPE_ID` = '78' WHERE (`NOTIFICATION_TYPE_ID` = '8011');
UPDATE `NOTIFY_ACTION_TYPE_MAP` SET `MODULE_ACTION_TYPE_ID` = '79' WHERE (`NOTIFICATION_TYPE_ID` = '8050');

DELETE FROM `NOTIFICATION_RECIPIENT` WHERE `NOTIFICATION_TYPE_ID` = 8012 AND `ROLE_TYPE_CODE` = 56 AND `RECIPIENT_TYPE` = 'TO';
