
INSERT INTO `ENTITY_STAGE_ADMIN_ACTION_TYPE` (`ADMIN_ACTION_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATED_BY`, `IS_ACTIVE`)
VALUES ('7', 'Marked as Duplicate and Included-Original Created', now(), '10000000001', 'Y');
INSERT INTO `ENTITY_STAGE_ADMIN_ACTION_TYPE` (`ADMIN_ACTION_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATED_BY`, `IS_ACTIVE`)
VALUES ('8', 'Marked as Duplicate and Excluded-Original Created', now(), '10000000001', 'Y');
