Analyze table COI_TRAVEL_DESTINATIONS;

SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_TRAVEL_DESTINATIONS' AND COLUMN_NAME = 'STAY_START_DATE') = 1
	 AND 
	 (SELECT COUNT(*) FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_TRAVEL_DESTINATIONS' AND COLUMN_TYPE = 'DATE') = 0,
     
    'ALTER TABLE COI_TRAVEL_DESTINATIONS MODIFY COLUMN STAY_START_DATE DATE;',
    
    'DO 1'
);

SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_TRAVEL_DESTINATIONS' AND COLUMN_NAME = 'STAY_END_DATE') = 1
	 AND 
	 (SELECT COUNT(*) FROM information_schema.COLUMNS 
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COI_TRAVEL_DESTINATIONS' AND COLUMN_TYPE = 'DATE') = 0,
     
    'ALTER TABLE COI_TRAVEL_DESTINATIONS MODIFY COLUMN STAY_END_DATE DATE;',
    
    'DO 1'
);

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
