DROP TABLE IF EXISTS MESSAGE_ALERT_MAPPING;
CREATE TABLE MESSAGE_ALERT_MAPPING (
	MESSAGE_ALERT_MAPPING_ID INT NOT NULL AUTO_INCREMENT,
    MESSAGE_TYPE_CODE VARCHAR(50) NOT NULL,
    ALERT_TYPE_CODE VARCHAR(1) NOT NULL, 
	IS_ACTIVE varchar(1) DEFAULT 'Y',
    UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
    PRIMARY KEY (MESSAGE_ALERT_MAPPING_ID)
);

INSERT INTO `MESSAGE_ALERT_MAPPING` (`MESSAGE_ALERT_MAPPING_ID`, `MESSAGE_TYPE_CODE`, `ALERT_TYPE_CODE`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`) 
VALUES ('1', '8001', 'B', 'Y', now());
INSERT INTO `MESSAGE_ALERT_MAPPING` (`MESSAGE_ALERT_MAPPING_ID`, `MESSAGE_TYPE_CODE`, `ALERT_TYPE_CODE`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`) 
VALUES ('2', '151', 'B', 'Y', now());
