DELIMITER //
CREATE PROCEDURE `GET_COI_PROJECTS`(
	AV_MODULE_CODE            INT(3),
	AV_PERSON_ID              VARCHAR(40),
    AV_SEARCH_STRING		  VARCHAR(40),
    AV_MODULE_ITEM_KEY  	VARCHAR(40)
)
BEGIN

    IF AV_MODULE_CODE = 1 THEN

		IF AV_MODULE_ITEM_KEY is not null THEN

			SELECT DISTINCT T2.EXTERNAL_SYSTEM_REF_ID AS AWARD_ID, T2.AWARD_NUMBER, T2.TITLE, T2.AWARD_START_DATE AS BEGIN_DATE, 
            T2.AWARD_END_DATE AS FINAL_EXPIRATION_DATE, T2.LEAD_UNIT_NUMBER, T2.LEAD_UNIT_NAME AS UNIT_NAME,
            T2.PI_NAME AS PI, T2.KEY_PERSON_NAME AS KEY_PERSON, T2.KEY_PERSON_ID, T2.KEY_PERSON_ROLE_NAME, T2.AWARD_STATUS AS STATUS,
            T2.PRIME_SPONSOR_NAME, T2.SPONSOR_CODE, T2.PRIME_SPONSOR_CODE, T2.SPONSOR_NAME,
            T2.ACCOUNT_NUMBER, T2.SPONSOR_AWARD_NUMBER, null AS CONFLICT_DESCRIPTION, null as PROJECT_CONFLICT_STATUS_CODE,
            NULL AS RELATIONSHIP_COUNT FROM COI_PROJECT_AWARD_V T2 WHERE T2.AWARD_NUMBER = AV_MODULE_ITEM_KEY ;

		ELSEIF AV_PERSON_ID is not null THEN

			SELECT DISTINCT T1.EXTERNAL_SYSTEM_REF_ID AS AWARD_ID, T1.AWARD_NUMBER, T1.TITLE, T1.AWARD_START_DATE AS BEGIN_DATE, 
            T1.AWARD_END_DATE AS FINAL_EXPIRATION_DATE, T1.LEAD_UNIT_NUMBER, T1.LEAD_UNIT_NAME AS UNIT_NAME,
            T1.PI_NAME AS PI, T1.KEY_PERSON_NAME AS KEY_PERSON, T1.KEY_PERSON_ID, T1.KEY_PERSON_ROLE_NAME, T1.AWARD_STATUS AS STATUS,
            T1.PRIME_SPONSOR_NAME, T1.SPONSOR_CODE, T1.PRIME_SPONSOR_CODE, T1.SPONSOR_NAME,
			T1.ACCOUNT_NUMBER, T1.SPONSOR_AWARD_NUMBER , null as CONFLICT_DESCRIPTION, null as PROJECT_CONFLICT_STATUS_CODE,
            NULL AS RELATIONSHIP_COUNT  FROM COI_PROJECT_AWARD_V T1
			LEFT JOIN (SELECT AW2.PROJECT_NUMBER
										FROM COI_DISCL_PROJECTS T5 
										INNER JOIN COI_DISCLOSURE T6 ON T6.DISCLOSURE_ID = T5.DISCLOSURE_ID
										INNER JOIN COI_INT_STAGE_AWARD AW1 ON AW1.PROJECT_NUMBER = T5.MODULE_ITEM_KEY
										INNER JOIN COI_INT_STAGE_AWARD AW2 ON AW2.ROOT_PROJECT_NUMBER = AW1.ROOT_PROJECT_NUMBER
										WHERE T6.VERSION_STATUS IN ('ACTIVE', 'PENDING')
										AND T6.PERSON_ID = AV_PERSON_ID ) T2 ON T2.PROJECT_NUMBER = T1.AWARD_NUMBER  
										
            WHERE T1.AWARD_STATUS_CODE IN (1,6,3)
            AND (LOWER(T1.EXTERNAL_SYSTEM_REF_ID) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.AWARD_NUMBER) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.TITLE) LIKE CONCAT('%', AV_SEARCH_STRING, '%')
				OR LOWER(T1.LEAD_UNIT_NUMBER) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.LEAD_UNIT_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.SPONSOR_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.PI_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.KEY_PERSON_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.KEY_PERSON_ID) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.PRIME_SPONSOR_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.ACCOUNT_NUMBER) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				OR LOWER(T1.SPONSOR_AWARD_NUMBER) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
			)
			AND ((T1.DISCLOSURE_VALIDATION_FLAG  IS NOT NULL  AND T1.DISCLOSURE_VALIDATION_FLAG = 'SELF') OR 
				(T1.DISCLOSURE_REQUIRED_FLAG IS NOT NULL AND T1.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED' 
				 AND T1.DISCLOSURE_VALIDATION_FLAG  IS NOT NULL AND T1.DISCLOSURE_VALIDATION_FLAG = 'HIERARCHY' AND T5.PROJECT_NUMBER IS NULL
				 AND NOT EXISTS (SELECT 1
								FROM COI_DISCLOSURE t1
								WHERE t1.PERSON_ID = AV_PERSON_ID
								AND (t1.VERSION_STATUS = 'PENDING' OR t1.VERSION_STATUS = 'ACTIVE')
								AND t1.FCOI_TYPE_CODE IN (1, 3)
							  )
				 ))
            AND T1.KEY_PERSON_ID = AV_PERSON_ID;

        END IF;

	ELSEIF AV_MODULE_CODE = 3 THEN

		IF AV_MODULE_ITEM_KEY is not null THEN

            SELECT DISTINCT T2.EXTERNAL_SYSTEM_REF_ID AS PROPOSAL_ID, T2.TITLE, T2.PROPOSAL_STATUS AS STATUS, T2.PROPOSAL_START_DATE AS START_DATE, T2.PROPOSAL_END_DATE AS END_DATE, 
            T2.LEAD_UNIT_NUMBER AS HOME_UNIT_NUMBER, T2.LEAD_UNIT_NAME AS HOME_UNIT_NAME, T2.SPONSOR_CODE, T2.PRIME_SPONSOR_CODE,
            T2.SPONSOR_NAME, T2.PRIME_SPONSOR_NAME, T2.PI_NAME AS PI, T2.KEY_PERSON_NAME AS KEY_PERSON, T2.KEY_PERSON_ID, T2.KEY_PERSON_ROLE_NAME,
            null AS CONFLICT_DESCRIPTION, null as PROJECT_CONFLICT_STATUS_CODE, NULL AS RELATIONSHIP_COUNT
            FROM COI_PROJECT_PROPOSAL_V T2 WHERE T2.PROPOSAL_NUMBER = AV_MODULE_ITEM_KEY;

		ELSEIF AV_PERSON_ID is not null THEN

			SELECT DISTINCT T1.EXTERNAL_SYSTEM_REF_ID AS PROPOSAL_ID, T1.TITLE, T1.PROPOSAL_STATUS AS STATUS, T1.PROPOSAL_START_DATE AS START_DATE,
            T1.PROPOSAL_END_DATE AS END_DATE, T1.LEAD_UNIT_NUMBER AS HOME_UNIT_NUMBER, T1.LEAD_UNIT_NAME AS HOME_UNIT_NAME,
            T1.SPONSOR_CODE, T1.PRIME_SPONSOR_CODE, T1.SPONSOR_NAME,
            T1.PRIME_SPONSOR_NAME, T1.PI_NAME AS PI, T1.KEY_PERSON_NAME AS KEY_PERSON, T1.KEY_PERSON_ID, T1.KEY_PERSON_ROLE_NAME,
            null as CONFLICT_DESCRIPTION, null as PROJECT_CONFLICT_STATUS_CODE, NULL AS RELATIONSHIP_COUNT
            FROM COI_PROJECT_PROPOSAL_V T1 
            WHERE T1.PROPOSAL_STATUS not IN ("In Progress","Unsuccessful","Inactive","Revision Requested",
            "ORT Director Review Completed","Pending Revisions By PI","Pending Revisions By PI","Not Submitted","Returned","Withdrawn","Awarded") 
            AND (LOWER(T1.EXTERNAL_SYSTEM_REF_ID) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				 OR LOWER(T1.TITLE) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				 OR LOWER(T1.LEAD_UNIT_NUMBER) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				 OR LOWER(T1.LEAD_UNIT_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				 OR LOWER(T1.SPONSOR_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				 OR LOWER(T1.PRIME_SPONSOR_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				 OR LOWER(T1.PI_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				 OR LOWER(T1.KEY_PERSON_NAME) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
				 OR LOWER(T1.KEY_PERSON_ID) LIKE CONCAT('%', LOWER(AV_SEARCH_STRING), '%')
			)
            AND T1.KEY_PERSON_ID = AV_PERSON_ID;
        END IF;
	END IF;
END
//