CREATE TABLE IF NOT EXISTS `OPA_PERSON_FEED_LOG` (
  `OPA_PERSON_FEED_LOG_ID` INT NOT NULL AUTO_INCREMENT,
  `FEED_STARTED_AT` DATETIME NULL,
  `FEED_COMPLETED_AT` DATETIME NULL,
  `FEED_STATUS` VARCHAR(15) NULL,
  `ERROR_MESSAGE` TEXT NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATED_BY` VARCHAR(40) NULL,
  PRIMARY KEY (`OPA_PERSON_FEED_LOG_ID`));


CREATE TABLE IF NOT EXISTS `OPA_PERSON_FEED_LOG_DETAILS` (
  `OPA_PERSON_FEED_LOG_DETAIL_ID` INT NOT NULL AUTO_INCREMENT,
  `OPA_PERSON_FEED_LOG_ID` INT NULL,
  `PERSON_ID` VARCHAR(40) NULL,
  `CREATE_TIMESTAMP` DATETIME NULL,
  PRIMARY KEY (`OPA_PERSON_FEED_LOG_DETAIL_ID`),
  INDEX `OPA_PERSON_FEED_LOG_DETAILS_IDX1` (`OPA_PERSON_FEED_LOG_ID` ASC) VISIBLE,
  CONSTRAINT `OPA_PERSON_FEED_LOG_DETAILS_FK1`
    FOREIGN KEY (`OPA_PERSON_FEED_LOG_ID`)
    REFERENCES `OPA_PERSON_FEED_LOG` (`OPA_PERSON_FEED_LOG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
