CREATE TABLE `DISCLOSUREAWARDPROJECTS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` INT DEFAULT NULL,
  `PROJECT_NUMBER` VARCHAR(20) DEFAULT NULL,
  `KEY_PERSON_ID` VARCHAR(60) DEFAULT NULL,
  `DISCLOSURE_REQUIRED_FLAG` VARCHAR(1000) DEFAULT NULL,
  `DISCLOSURE_ID` INT DEFAULT NULL,
  `DISCLOSURE_STATUS` VARCHAR(1000) DEFAULT NULL,
  `PROJECT_DISCLOSURE_REVIEW_STATUS` VARCHAR(400) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_PROJECT_ID` (`PROJECT_ID`),
  KEY `IDX_PROJECT_NUMBER` (`PROJECT_NUMBER`),
  KEY `IDX_KEY_PERSON_ID` (`KEY_PERSON_ID`),
  KEY `IDX_DISCLOSURE_ID` (`DISCLOSURE_ID`),
  KEY `IDX_PROJECT_PERSON` (`PROJECT_NUMBER`,`KEY_PERSON_ID`)
);
