INSERT INTO `PERSON_ROLE_TYPE` (`ROLE_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `IS_ACTIVE`) VALUES ('65', 'Contract Administrator', now(), 'quickstart', 'Y');

INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` (`NOTIFY_PLACEHOLDER_HEADER_ID`,`QUERY_COLUMN_NAME`,`LABEL_NAME`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`BASE_URL_ID`,`URL_PATH`) VALUES (2,'PROJECT_SUBMISSION_STATUS','Project Submission Status',now(),'quickstart',NULL,NULL);
INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` (`NOTIFY_PLACEHOLDER_HEADER_ID`,`QUERY_COLUMN_NAME`,`LABEL_NAME`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`BASE_URL_ID`,`URL_PATH`) VALUES (2,'PROJECT_OVERALL_REVIEW_STATUS','Project Overall Review Status',now(),'quickstart',NULL,NULL);

INSERT INTO `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`,`ACTION_TYPE`,`MODULE_CODE`,`SUB_MODULE_CODE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (58,'PROJ_ALL_KP_DISCL_SUB_DONE',8,0,'y','Project All Key Personnel Disclosures Submitted',now(),'quickstart');
INSERT INTO `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`,`ACTION_TYPE`,`MODULE_CODE`,`SUB_MODULE_CODE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (59,'PROJ_ALL_KP_DISCL_RVW_DONE',8,0,'y','Project All Key Personnel Disclosures Review Completed',now(),'quickstart');

INSERT INTO `NOTIFICATION_TYPE` (`NOTIFICATION_TYPE_ID`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`SUBJECT`,`MESSAGE`,`PROMPT_USER`,`IS_ACTIVE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`IS_SYSTEM_SPECIFIC`,`SHOW_TEMPLATE_IN_MODULE`,`SENT_TO_INITIATOR`) VALUES (8059,8,0,'Project All Key Personnel Disclosures Submission','All Key Personnel Have Submitted Disclosures – Review Required','<p style=\"margin-left:0px;\">Dear COI Admin ,CA</p><p style=\"margin-left:0px;\">All key personnel for {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE} have submitted their disclosures.</p><p style=\"margin-left:0px;\">Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p style=\"margin-left:0px;\">Project : {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</p><p style=\"margin-left:0px;\">Principal Investigator : {COI_DISCLOSURE#PRINCIPAL_INVESTIGATOR}</p><p style=\"margin-left:0px;\">Submission Status : {COI_DISCL_OTHER#PROJECT_SUBMISSION_STATUS}</p><p style=\"margin-left:0px;\">Overall Review Status : {COI_DISCL_OTHER#PROJECT_OVERALL_REVIEW_STATUS}</p><p style=\"margin-left:0px;\"><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p style=\"margin-left:0px;\"><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Note: This is a system-generated email. Please do not reply to this email.</span></p>','N','Y','quickstart',now(),'quickstart',now(),'N',NULL,'Y');
INSERT INTO `NOTIFICATION_TYPE` (`NOTIFICATION_TYPE_ID`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`SUBJECT`,`MESSAGE`,`PROMPT_USER`,`IS_ACTIVE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`IS_SYSTEM_SPECIFIC`,`SHOW_TEMPLATE_IN_MODULE`,`SENT_TO_INITIATOR`) VALUES (8060,8,0,'Project All Key Personnel Disclosures Review Completion','Review Completed for All Key Persons’ Disclosures –: {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}','<p style=\"margin-left:0px;\">Dear CA,</p><p>The COI Admin has completed the review for all key persons'' disclosures associated with {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}.</p><p style=\"margin-left:0px;\">Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p style=\"margin-left:0px;\">Project : {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</p><p style=\"margin-left:0px;\">Principal Investigator : {COI_DISCLOSURE#PRINCIPAL_INVESTIGATOR}</p><p style=\"margin-left:0px;\">Overall Review Status : {COI_DISCL_OTHER#PROJECT_OVERALL_REVIEW_STATUS}</p><p style=\"margin-left:0px;\"><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p style=\"margin-left:0px;\"><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Note: This is a system-generated email. Please do not reply to this email.</span></p>','N','Y','quickstart',now(),'quickstart',now(),'N',NULL,'Y');

INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8059,NULL,52,NULL, now(),NULL,NULL,'TO','COI Administrators');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8059,NULL,65,NULL,now(),NULL,NULL,'TO','Contract Administrator');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8060,NULL,65,NULL,now(),NULL,NULL,'TO','Contract Administrator');

INSERT INTO `NOTIFY_ACTION_TYPE_MAP` (`NOTIFICATION_TYPE_ID`,`MODULE_ACTION_TYPE_ID`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (8059,58,now(),'quickstart');
INSERT INTO `NOTIFY_ACTION_TYPE_MAP` (`NOTIFICATION_TYPE_ID`,`MODULE_ACTION_TYPE_ID`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (8060,59,now(),'quickstart');

INSERT INTO `MQ_ROUTER_ACTION_CONFIGURATION` (`ACTION_TYPE`,`IS_ACTIVE`,`MODULE_CODE`,`QUEUE_NAME`,`SUB_MODULE_CODE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('PROJ_ALL_KP_DISCL_SUB_DONE','Y',8,'Q_NOTIFICATION',0,now(),'quickstart');
INSERT INTO `MQ_ROUTER_ACTION_CONFIGURATION` (`ACTION_TYPE`,`IS_ACTIVE`,`MODULE_CODE`,`QUEUE_NAME`,`SUB_MODULE_CODE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('PROJ_ALL_KP_DISCL_RVW_DONE','Y',8,'Q_NOTIFICATION',0,now(),'quickstart');
