-- Truncate table scripts

/* Lookup tables

TRUNCATE TABLE ENTITY_TYPE;
TRUNCATE TABLE ENTITY_STATUS;
TRUNCATE TABLE ENTITY_RISK_CATEGORY;
TRUNCATE TABLE ENTITY_RELATIONSHIP_TYPE;
TRUNCATE TABLE ENTITY_REL_NODE_TYPE;
TRUNCATE TABLE COI_DISCLOSURE_TYPE;
TRUNCATE TABLE PERSON_ENTITY_REL_TYPE;
TRUNCATE TABLE VALID_PERSON_ENTITY_REL_TYPE;
TRUNCATE TABLE COI_PROJECT_TYPE;
TRUNCATE TABLE COI_DISCLOSURE_FCOI_TYPE;
TRUNCATE TABLE COI_CONFLICT_STATUS_TYPE;
TRUNCATE TABLE COI_DISPOSITION_STATUS_TYPE;
TRUNCATE TABLE COI_REVIEW_STATUS_TYPE;
TRUNCATE TABLE COI_PROJ_CONFLICT_STATUS_TYPE;
TRUNCATE TABLE DISCL_ATTA_TYPE;
TRUNCATE TABLE DISCL_COMPONENT_TYPE;
TRUNCATE TABLE DISCL_VALID_COMPNENT_ATTA_TY;
TRUNCATE TABLE DISCL_COMMENT_TYPE;
-- TRUNCATE TABLE discl_valid_compnent_comnt_ty;
TRUNCATE TABLE COI_REVIEWER_STATUS_TYPE;
TRUNCATE TABLE COI_REVIEW_LOCATION_TYPE;
TRUNCATE TABLE DISCLOSURE_ACTION_TYPE;
TRUNCATE TABLE ENTITY_ACTION_TYPE;
TRUNCATE TABLE OPA_DISPOSITION_STATUS_TYPE;
TRUNCATE TABLE OPA_ACTION_LOG_TYPE;
TRUNCATE TABLE PERSON_ENTITY_ACTION_TYPE;
TRUNCATE TABLE OPA_STATUS_TYPE;
TRUNCATE TABLE OPA_REVIEW_STATUS_TYPE;
TRUNCATE TABLE OPA_REVIEW_LOCATION_TYPE;
TRUNCATE TABLE OPA_REVIEW_REVIEWER_STATUS_TYPE;
TRUNCATE TABLE OPA_REVIEW_STATUS_TYPE;
TRUNCATE TABLE FORM_SECTION_COMPONENT_TYPE;
TRUNCATE TABLE COI_SECTIONS_TYPE;
TRUNCATE TABLE DISCL_ATTA_STATUS;
TRUNCATE TABLE COI_TRAVEL_STATUS;
TRUNCATE TABLE COI_TRAVEL_DISCLOSURE_STATUS;
TRUNCATE TABLE COI_TRAVEL_REVIEW_STATUS;
TRUNCATE TABLE COI_TRAVEL_DOCUMENT_STATUS;
TRUNCATE TABLE COI_RISK_CATEGORY;
TRUNCATE TABLE COI_TRAVELER;
TRUNCATE TABLE COI_REVIEW_ACTIVITY;

*/

/* Transaction Tables

/* Entity related tables
TRUNCATE TABLE ENTITY;
TRUNCATE TABLE ENTITY_RELATIONSHIP;
TRUNCATE TABLE ENTITY_ACTION_LOG;
*/

/* PersonEntity related tables
TRUNCATE TABLE PERSON_ENTITY;
TRUNCATE TABLE PERSON_ENTITY_RELATIONSHIP;
TRUNCATE TABLE PERSON_ENTITY_ACTION_LOG;
*/

/* COI Disclosure related tables
TRUNCATE TABLE COI_DISCLOSURE;
TRUNCATE TABLE COI_DISCL_ENT_PROJ_DETAILS;
TRUNCATE TABLE DISCL_COMMENT;
TRUNCATE TABLE DISCLOSURE_ACTION_LOG;
TRUNCATE TABLE COI_CONFLICT_HISTORY;
TRUNCATE TABLE COI_REVIEW_COMMENT_TAGS;
TRUNCATE TABLE COI_REVIEW;
TRUNCATE TABLE COI_REVIEW_ASSIGNEE_HISTORY;
TRUNCATE TABLE COI_REVIEW_COMMENT_ATTACHMENT;
*/

/* Travel Disclosure related tables
TRUNCATE TABLE COI_TRAVEL_DISCLOSURE;
TRUNCATE TABLE COI_TRAVEL_DISCLOSURE_TRAVELER;
TRUNCATE TABLE TRAVEL_DISCLOSURE_ACTION_LOG;
TRUNCATE TABLE COI_TRAVEL_CONFLICT_HISTORY;
*/

/* OPA Disclosure related tables
TRUNCATE TABLE OPA_ACTION_LOG;
TRUNCATE TABLE OPA_DISCLOSURE;
TRUNCATE TABLE OPA_REVIEW;
TRUNCATE TABLE OPA_FORM_BUILDER_DETAILS;
TRUNCATE TABLE OPA_INSTITUTE_RESOURCE_USE;
TRUNCATE TABLE OPA_DISCL_PERSON_ENTITY;
TRUNCATE TABLE OPA_DISCL_ACTIVITIES;
TRUNCATE TABLE OPA_OUTSIDE_FIN_INTERESTS;
TRUNCATE TABLE OPA_STUDENT_SUBORDINATE_INVOLVEMENT;
*/

TRUNCATE TABLE COI_QUEST_ANSWER;
TRUNCATE TABLE COI_QUEST_ANSWER_ATTACHMENT;
TRUNCATE TABLE COI_QUEST_TABLE_ANSWER;
TRUNCATE TABLE NOTES;

-- TRUNCATE TABLE FORM_BUILDER_HEADER;
-- TRUNCATE TABLE FORM_BUILDER_PROG_ELEMENT;
-- TRUNCATE TABLE FORM_BUILDER_SECTION;
-- TRUNCATE TABLE FORM_BUILDER_SECTION_COMPONENT;
-- TRUNCATE TABLE FORM_BUILDER_USAGE;

-- TRUNCATE TABLE COI_PROJECT_PROPOSAL;
-- TRUNCATE TABLE COI_PROJECT_AWARD;
-- TRUNCATE TABLE OPA_PERSON;
-- TRUNCATE TABLE OPA_CYCLES;

-- TRUNCATE TABLE ATTACHMENT_NUMBER_COUNTER;
-- TRUNCATE TABLE OPA_DISCLOSURE_NUMBER_COUNTER;

-- TRUNCATE TABLE COI_FILE_DATA;
-- TRUNCATE TABLE DISCL_FILE_DATA;
-- TRUNCATE TABLE DISCL_ATTACHMENT;
-- TRUNCATE TABLE ATTACHMENTS;

*/

