ALTER TABLE `entity_sub_org_info`
CHANGE COLUMN `ORGANIZATION_ID` `ORGANIZATION_ID` VARCHAR(10) NULL DEFAULT NULL ;

ALTER TABLE `ENTITY_EXTERNAL_ID_MAPPING`
CHANGE COLUMN `ORGANIZATION_ID` `ORGANIZATION_ID` VARCHAR(10) NULL DEFAULT NULL ;
