INSERT INTO `mq_router_trigger_configuration` (`TRIGGER_TYPE`, `IS_ACTIVE`, `QUEUE_NAME`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
SELECT * FROM (SELECT 'COI_DECLARATION_INTEGRATION', 'Y', 'Q_COI_DECLARATION_INTEGRATION', 'Coi Declaration integration', now(), 'admin') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM mq_router_trigger_configuration where TRIGGER_TYPE = 'COI_DECLARATION_INTEGRATION');
