DELIMITER //
CREATE FUNCTION `FN_IS_ENG_HAS_COMMITMENT`(
    AV_PERSON_ENTITY_ID INT) RETURNS TINYINT(1)
    READS SQL DATA
    DETERMINISTIC
BEGIN
    IF EXISTS (SELECT 1
        FROM PERSON_ENTITY
            WHERE IS_COMMITMENT = 'Y' AND PERSON_ENTITY_ID = AV_PERSON_ENTITY_ID
        ) THEN
        RETURN TRUE;
    END IF;

    RETURN FALSE;
END
//
