DELIMITER //
CREATE FUNCTION FN_QRY_RVW_DAS_OVRVW_OPA_FIL_COND(
    AV_PERSON_ID VARCHAR(40),
    JSON_INPUT JSON
)
RETURNS TEXT
DETERMINISTIC
BEGIN
    DECLARE LS_FILTER_CONDITION LONGTEXT DEFAULT '';

    DECLARE AV_DISCLOSURE_STATUS_CODES      VARCHAR(30);
    DECLARE AV_DISPOSITION_STATUS_CODES     VARCHAR(30);
    DECLARE AV_HOME_UNIT                    VARCHAR(500);
    DECLARE AV_SEARCH_PERSON                VARCHAR(90);
    DECLARE AV_ENTITY_ID                    VARCHAR(60);
    DECLARE AV_IS_FACULTY                   VARCHAR(10);
    DECLARE AV_PERIOD_START_DATE            VARCHAR(30);
    DECLARE AV_PERIOD_END_DATE              VARCHAR(30);
    DECLARE AV_EXPIRATION_DATE              VARCHAR(30);
    DECLARE AV_ADMIN_PERSON_ID              VARCHAR(1200);
    DECLARE AV_ENTITY                       VARCHAR(500);
    DECLARE AV_OPA_DISCLOSURE_TYPES         VARCHAR(40);
    DECLARE AV_FREE_TEXT_SEARCH_FIELDS      VARCHAR(500);
    DECLARE AV_TAB_TYPE                     VARCHAR(200);
    DECLARE AV_FETCH_TYPE                   VARCHAR(20);
    DECLARE AV_INCLUDE_CHILD_UNITS          BOOLEAN;
    DECLARE AV_CERTIFICATION_DATE           VARCHAR(20);

    SET AV_DISPOSITION_STATUS_CODES = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.DISPOSITION_STATUS_CODES'));
    SET AV_DISCLOSURE_STATUS_CODES  = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.REVIEW_STATUS_CODE'));
    SET AV_HOME_UNIT                = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.HOME_UNIT'));
    SET AV_SEARCH_PERSON            = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.PERSON'));
    SET AV_ENTITY_ID                = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.ENTITY_ID'));
    SET AV_IS_FACULTY               = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.IS_FACULTY'));
    SET AV_PERIOD_START_DATE        = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.PERIOD_START_DATE'));
    SET AV_PERIOD_END_DATE          = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.PERIOD_END_DATE'));
    SET AV_EXPIRATION_DATE          = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.EXPIRATION_DATE'));
    SET AV_ADMIN_PERSON_ID          = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.ADMIN_PERSON_ID'));
    SET AV_ENTITY                   = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.ENTITY'));
    SET AV_OPA_DISCLOSURE_TYPES     = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.OPA_DISCLOSURE_TYPES'));
    SET AV_FREE_TEXT_SEARCH_FIELDS  = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.SEARCH_KEYWORD'));
    SET AV_TAB_TYPE                 = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.TAB_TYPE'));
    SET AV_FETCH_TYPE               = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.FETCH_TYPE'));
    SET AV_INCLUDE_CHILD_UNITS      = JSON_EXTRACT(JSON_INPUT, '$.INCLUDE_CHILD_UNITS');
    SET AV_CERTIFICATION_DATE       = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.CERTIFIED_AT'));

    IF AV_FETCH_TYPE = 'HEADER' THEN
        SET AV_TAB_TYPE = null;
    END IF;

    IF AV_TAB_TYPE IS NOT NULL AND AV_TAB_TYPE <> '' AND AV_TAB_TYPE <> 'ALL_DISCLOSURES' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' (');

        -- REVIEW_PENDING
        IF FIND_IN_SET('REVIEW_PENDING', AV_TAB_TYPE) > 0 THEN
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.REVIEW_STATUS_CODE IN (3,7,8,9,2) ');
        END IF;

        -- EXPIRING
        IF FIND_IN_SET('EXPIRING', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.EXPIRATION_DATE BETWEEN CURRENT_DATE() AND DATE_ADD(CURRENT_DATE(), INTERVAL 30 DAY) ');
        END IF;

        -- EXPIRED
        IF FIND_IN_SET('EXPIRED', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.DISPOSITION_STATUS_CODE = 4 AND T1.EXPIRATION_DATE < CURRENT_DATE() ');
        END IF;

        IF FIND_IN_SET('APPROVED', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.DISPOSITION_STATUS_CODE = 3 ');
        END IF;

        IF FIND_IN_SET('MY_REVIEWS_PENDING', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T1.REVIEW_STATUS_CODE IN (3,7,8,9) AND ((T8.ASSIGNEE_PERSON_ID = ''', AV_PERSON_ID ,'''AND T8.REVIEW_STATUS_TYPE_CODE IN (1,2))
                OR (T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID ,''')
                OR exists  (SELECT 1 FROM WORKFLOW WF
                    INNER JOIN WORKFLOW_DETAIL WFD ON WF.WORKFLOW_ID = WFD.WORKFLOW_ID
                    WHERE WF.MODULE_ITEM_ID = T1.OPA_DISCLOSURE_ID
                    AND WFD.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                    AND WF.MODULE_CODE = 23 AND WF.IS_WORKFLOW_ACTIVE = ''Y''
                    AND WFD.APPROVAL_STATUS = ''W''
                )
            )');
        END IF;

        IF FIND_IN_SET('WITHOUT_ENGAGEMENTS', AV_TAB_TYPE) > 0 THEN
            IF RIGHT(LS_FILTER_CONDITION, 2) <> ' (' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' OR ');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,
                ' T21.NO_OF_SFI < 1 ');
        END IF;

        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ') AND ');
    END IF;

    IF AV_DISPOSITION_STATUS_CODES IS NOT NULL  AND AV_DISPOSITION_STATUS_CODES <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.DISPOSITION_STATUS_CODE IN (',AV_DISPOSITION_STATUS_CODES,') AND ');
	ELSE
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.DISPOSITION_STATUS_CODE != ''2'' AND ');
	END IF;

    IF AV_DISCLOSURE_STATUS_CODES IS NOT NULL  AND AV_DISCLOSURE_STATUS_CODES <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.REVIEW_STATUS_CODE IN (',AV_DISCLOSURE_STATUS_CODES,') AND ');
	END IF;

    IF AV_HOME_UNIT IS NOT NULL AND AV_HOME_UNIT <> '' AND AV_HOME_UNIT <> 'ALL' AND (AV_INCLUDE_CHILD_UNITS IS NULL OR AV_INCLUDE_CHILD_UNITS = FALSE) THEN
        IF FIND_IN_SET('UNIT', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
            IF INSTR(AV_HOME_UNIT, '*') > 0 THEN
                SET AV_HOME_UNIT = REPLACE(AV_HOME_UNIT, '*', '%');
            ELSE
                SET AV_HOME_UNIT = CONCAT('%', AV_HOME_UNIT, '%');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' (T20.UNIT_NAME LIKE ''', AV_HOME_UNIT,
                ''' OR T1.HOME_UNIT LIKE ''', AV_HOME_UNIT, ''') AND '
            );
        ELSE
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' T1.HOME_UNIT = ''', AV_HOME_UNIT, ''' AND '
            );
        END IF;
    ELSEIF AV_INCLUDE_CHILD_UNITS = TRUE THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.HOME_UNIT IN (SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN WHERE UNIT_NUMBER =''',AV_HOME_UNIT,''') AND ');
    END IF;

    IF AV_SEARCH_PERSON IS NOT NULL AND AV_SEARCH_PERSON <> '' THEN
        IF FIND_IN_SET('PERSON', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
            IF INSTR(AV_SEARCH_PERSON, '*') > 0 THEN
                SET AV_SEARCH_PERSON = REPLACE(AV_SEARCH_PERSON, '*', '%');
            ELSE
                SET AV_SEARCH_PERSON = CONCAT('%', AV_SEARCH_PERSON, '%');
            END IF;

            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' (T16.FULL_NAME LIKE ''', AV_SEARCH_PERSON,
                ''' OR T1.PERSON_ID LIKE ''', AV_SEARCH_PERSON, ''') AND '
            );
        ELSE
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' T1.PERSON_ID = ''', AV_SEARCH_PERSON, ''' AND '
            );
        END IF;
    END IF;

    IF AV_ENTITY_ID IS NOT NULL AND AV_ENTITY_ID <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T11.ENTITY_ID = ''',AV_ENTITY_ID,''' AND ');
    END IF;

    IF AV_IS_FACULTY IS NOT NULL AND AV_IS_FACULTY <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T16.IS_FACULTY IN (', AV_IS_FACULTY, ') AND ');
    END IF;

    IF AV_PERIOD_START_DATE IS NOT NULL AND AV_PERIOD_START_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T2.PERIOD_START_DATE >= ''',AV_PERIOD_START_DATE,''' AND ');
    END IF;

    IF AV_PERIOD_END_DATE IS NOT NULL AND AV_PERIOD_END_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T2.PERIOD_END_DATE <= ''',AV_PERIOD_END_DATE,''' AND ');
    END IF;

    IF AV_EXPIRATION_DATE IS NOT NULL AND AV_EXPIRATION_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' DATE(T1.EXPIRATION_DATE) = ''',AV_EXPIRATION_DATE,''' AND ');
    END IF;

    IF AV_ADMIN_PERSON_ID IS NOT NULL AND AV_ADMIN_PERSON_ID <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' FIND_IN_SET(T1.ADMIN_PERSON_ID, ''',AV_ADMIN_PERSON_ID,''') AND ');
    END IF;

    IF AV_ENTITY IS NOT NULL AND AV_ENTITY <> '' THEN
        IF FIND_IN_SET('ENTITY', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
            IF INSTR(AV_ENTITY, '*') > 0 THEN
                SET AV_ENTITY = REPLACE(AV_ENTITY, '*', '%');
            ELSE
                SET AV_ENTITY = CONCAT('%', AV_ENTITY, '%');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' (T18.PRIMARY_NAME LIKE ''', AV_ENTITY,
                ''' OR T18.ENTITY_ID LIKE ''', AV_ENTITY, ''') AND '
            );
        ELSE
            SET LS_FILTER_CONDITION = CONCAT(
                LS_FILTER_CONDITION,
                ' T18.ENTITY_ID = ''', AV_ENTITY, ''' AND '
            );
        END IF;
    END IF;

    IF AV_OPA_DISCLOSURE_TYPES IS NOT NULL AND AV_OPA_DISCLOSURE_TYPES <> '' THEN
		IF FIND_IN_SET('INITIAL', AV_OPA_DISCLOSURE_TYPES) > 0 THEN
			SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' (T1.VERSION_NUMBER = 1 ');
			IF FIND_IN_SET('REVISION', AV_OPA_DISCLOSURE_TYPES) > 0 THEN
			    SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' OR ');
			ELSE
			    SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,') AND ');
			END IF;
		END IF;
		IF FIND_IN_SET('REVISION', AV_OPA_DISCLOSURE_TYPES) > 0 THEN
			SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.VERSION_NUMBER > 1 ');
			IF FIND_IN_SET('INITIAL', AV_OPA_DISCLOSURE_TYPES) > 0 THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,') AND ');
            ELSE
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND ');
            END IF;
		END IF;
    END IF;


    IF AV_CERTIFICATION_DATE IS NOT NULL AND AV_CERTIFICATION_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' DATE(T1.SUBMISSION_TIMESTAMP) = ''',STR_TO_DATE(AV_CERTIFICATION_DATE,'%Y-%m-%d'),''' AND ');
    END IF;

    IF RIGHT(LS_FILTER_CONDITION, 5) = ' AND ' THEN
        SET LS_FILTER_CONDITION = LEFT(LS_FILTER_CONDITION, LENGTH(LS_FILTER_CONDITION) - 5);
    END IF;

    RETURN LS_FILTER_CONDITION;
END
//
