DROP PROCEDURE IF EXISTS BULK_UPDATE_GLOBAL_ENTITY_FOREIGN_FLAG;
DROP PROCEDURE IF EXISTS GET_COI_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_COUNT;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_DATA;
DROP PROCEDURE IF EXISTS GET_ENTITY_HIERARCHY;
DROP PROCEDURE IF EXISTS UPDATE_GLOBAL_ENTITY_FOREIGN_FLAG;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITIES;

