DELIMITER //
CREATE FUNCTION `FN_IS_ALL_OPA_REVIEWS_COMPLETED`(
    AV_OPA_DISCLOSURE_ID INT) RETURNS tinyint
    NOT DETERMINISTIC
    READS SQL DATA
BEGIN
    DECLARE REVIEW_COUNT INT;
    
    SELECT COUNT(R.OPA_REVIEW_ID) INTO REVIEW_COUNT
    FROM OPA_REVIEW R
    WHERE R.OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID
    AND R.REVIEW_STATUS_TYPE_CODE IN (1, 2);
    
    IF REVIEW_COUNT = 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END
//
