SET SQL_SAFE_UPDATES = 0;

INSERT INTO `BUSINESS_RULE_FUNCTION` (`FUNCTION_NAME`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`DB_FUNCTION_NAME`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
VALUES ('Check travel destination added',24,0,'Check travel destination added','FN_IS_TRAVEL_DESTINATION_ADDED',now(),'quickstart');
 
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`,`ARGUMENT_SEQUENCE_NUMBER`,`ARGUMENT_NAME`,`DESCRIPTION`,`DATA_TYPE`,`DEFAULT_VALUE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`LOOKUP_WINDOW_NAME`,`LOOKUP_TYPE`,`ARGUMENT_TYPE`,`ARGUMENT_LABEL`) 
VALUES ('Check travel destination added',1,'TRAVEL_DISCLOSURE_ID','Check travel destination added',NULL,NULL,now(),'quickstart',NULL,NULL,NULL,NULL);

SET SQL_SAFE_UPDATES = 1;
