SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS fb_comp_custom_element;
CREATE TABLE `fb_comp_custom_element` (
  `CUSTOM_DATA_ELEMENTS_ID` int NOT NULL AUTO_INCREMENT,
  `COLUMN_LABEL` varchar(255) DEFAULT NULL,
  `DATA_LENGTH` int DEFAULT NULL,
  `DATA_TYPE` varchar(255) DEFAULT NULL,
  `DEFAULT_VALUE` varchar(255) DEFAULT NULL,
  `HAS_LOOKUP` varchar(255) DEFAULT 'N',
  `LOOKUP_ARGUMENT` varchar(255) DEFAULT NULL,
  `LOOKUP_WINDOW` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'N',
  `CUSTOM_ELEMENT_NAME` varchar(70) DEFAULT NULL,
  `IS_MULTI_SELECT_LOOKUP` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`CUSTOM_DATA_ELEMENTS_ID`),
  KEY `FB_COMP_CUSTOM_ELEMENT_FK1` (`DATA_TYPE`),
  CONSTRAINT `FB_COMP_CUSTOM_ELEMENT_FK1` FOREIGN KEY (`DATA_TYPE`) REFERENCES `form_section_component_type` (`COMPONENT_TYPE_CODE`)
);

DROP TABLE IF EXISTS fb_comp_custom_element_answer;
CREATE TABLE `fb_comp_custom_element_answer` (
  `CUSTOM_DATA_ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOM_DATA_ELEMENTS_ID` int DEFAULT NULL,
  `MODULE_ITEM_CODE` int DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(255) DEFAULT NULL,
  `MODULE_SUB_ITEM_CODE` int DEFAULT NULL,
  `MODULE_SUB_ITEM_KEY` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `VALUE` varchar(4000) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CUSTOM_DATA_ID`),
  KEY `FB_COMP_CUSTOM_ELEMENT_ANSWER_idx2` (`MODULE_ITEM_KEY`),
  KEY `FB_COMP_CUSTOM_ELEMENT_ANSWER_idx3` (`CUSTOM_DATA_ELEMENTS_ID`),
  KEY `FB_COMP_CUSTOM_ELEMENT_ANSWER_idx4` (`MODULE_ITEM_KEY`,`CUSTOM_DATA_ELEMENTS_ID`)
);

DROP TABLE IF EXISTS fb_comp_custom_element_options;
CREATE TABLE `fb_comp_custom_element_options` (
  `CUSTOM_DATA_OPTION_ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOM_DATA_ELEMENTS_ID` int DEFAULT NULL,
  `OPTION_NAME` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CUSTOM_DATA_OPTION_ID`)
);

DROP TABLE IF EXISTS form_builder_counter;
CREATE TABLE `form_builder_counter` (
  `COUNTER_NAME` varchar(255) NOT NULL,
  `COUNTER_VALUE` int DEFAULT NULL,
  PRIMARY KEY (`COUNTER_NAME`)
);

DROP TABLE IF EXISTS consulting_discl_form_builder_details;
CREATE TABLE `consulting_discl_form_builder_details` (
  `CONSULTING_DISCL_FORM_BUILDER_DETAILS_ID` int NOT NULL AUTO_INCREMENT,
  `DISCLOSURE_ID` int NOT NULL,
  `PERSON_ID` varchar(40) NOT NULL,
  `FORM_BUILDER_ID` int NOT NULL,
  `FORM_BUILDER_NUMBER` varchar(20) DEFAULT NULL,
  `IS_PRIMARY_FORM` varchar(1) NOT NULL,
  `UPDATE_TIMESTAMP` datetime NOT NULL,
  `UPDATE_USER` varchar(60) NOT NULL,
  PRIMARY KEY (`CONSULTING_DISCL_FORM_BUILDER_DETAILS_ID`)
);

DROP TABLE IF EXISTS consulting_discl_review_status_type;
CREATE TABLE `consulting_discl_review_status_type` (
  `REVIEW_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `SORT_ORDER` int DEFAULT NULL,
  PRIMARY KEY (`REVIEW_STATUS_CODE`)
);

DROP TABLE IF EXISTS consulting_discl_disposition_status_type;
CREATE TABLE `consulting_discl_disposition_status_type` (
  `DISPOSITION_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `SORT_ORDER` int DEFAULT NULL,
  PRIMARY KEY (`DISPOSITION_STATUS_CODE`)
);

DROP TABLE IF EXISTS consulting_disclosure;
CREATE TABLE `consulting_disclosure` (
  `DISCLOSURE_ID` int NOT NULL AUTO_INCREMENT,
  `PERSON_ID` varchar(45) DEFAULT NULL,
  `DISPOSITION_STATUS_CODE` varchar(3) DEFAULT NULL,
  `PERSON_ENTITY_ID` int DEFAULT NULL,
  `ENTITY_NUMBER` int DEFAULT NULL,
  `REVIEW_STATUS_CODE` varchar(3) DEFAULT NULL,
  `EXPIRATION_DATE` date DEFAULT NULL,
  `CERTIFICATION_TEXT` varchar(1000) DEFAULT NULL,
  `CERTIFIED_BY` varchar(60) DEFAULT NULL,
  `CERTIFIED_AT` datetime DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `CREATE_USER` varchar(60) DEFAULT NULL,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `HOME_UNIT` varchar(8) DEFAULT NULL,
  `ADMIN_GROUP_ID` int DEFAULT NULL,
  `ADMIN_PERSON_ID` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`DISCLOSURE_ID`),
  KEY `CONSULTING_DISCL_FK1` (`PERSON_ID`),
  KEY `CONSULTING_DISCL_FK2` (`DISPOSITION_STATUS_CODE`),
  KEY `CONSULTING_DISCL_FK3` (`REVIEW_STATUS_CODE`),
  KEY `CONSULTING_DISCL_FK4` (`HOME_UNIT`),
  KEY `CONSULTING_DISCL_FK5` (`PERSON_ENTITY_ID`),
  CONSTRAINT `CONSULTING_DISCL_FK2` FOREIGN KEY (`DISPOSITION_STATUS_CODE`) REFERENCES `consulting_discl_disposition_status_type` (`DISPOSITION_STATUS_CODE`),
  CONSTRAINT `CONSULTING_DISCL_FK3` FOREIGN KEY (`REVIEW_STATUS_CODE`) REFERENCES `consulting_discl_review_status_type` (`REVIEW_STATUS_CODE`),
  CONSTRAINT `CONSULTING_DISCL_FK4` FOREIGN KEY (`HOME_UNIT`) REFERENCES `unit` (`UNIT_NUMBER`),
  CONSTRAINT `CONSULTING_DISCL_FK1` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`),
  CONSTRAINT `CONSULTING_DISCL_FK5` FOREIGN KEY (`PERSON_ENTITY_ID`) REFERENCES `person_entity` (`PERSON_ENTITY_ID`)
);

DROP TABLE IF EXISTS consulting_discl_action_log_type;
CREATE TABLE `consulting_discl_action_log_type` (
  `ACTION_TYPE_CODE` varchar(3) NOT NULL,
  `MESSAGE` varchar(200) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ACTION_TYPE_CODE`)
);

DROP TABLE IF EXISTS consulting_discl_action_log;
CREATE TABLE `consulting_discl_action_log` (
  `ACTION_LOG_ID` int NOT NULL AUTO_INCREMENT,
  `DISCLOSURE_ID` int DEFAULT NULL,
  `ACTION_TYPE_CODE` varchar(3) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `COMMENT` varchar(4000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ACTION_LOG_ID`),
  KEY `CONSULTING_ACTION_LOG_FK2` (`ACTION_TYPE_CODE`),
  KEY `CONSULTING_ACTION_LOG_FK1` (`DISCLOSURE_ID`),
  CONSTRAINT `consulting_ACTION_LOG_FK1` FOREIGN KEY (`DISCLOSURE_ID`) REFERENCES `consulting_disclosure` (`DISCLOSURE_ID`),
  CONSTRAINT `consulting_ACTION_LOG_FK2` FOREIGN KEY (`ACTION_TYPE_CODE`) REFERENCES `consulting_discl_action_log_type` (`ACTION_TYPE_CODE`)
);

DROP TABLE IF EXISTS COI_PROJECT_INSTITUTE_PROPOSAL;
CREATE TABLE `COI_PROJECT_INSTITUTE_PROPOSAL` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EXTERNAL_SYSTEM_REF_ID` int DEFAULT NULL,
  `COI_PROJECT_TYPE_CODE` varchar(3) DEFAULT NULL,
  `IP_NUMBER` varchar(45) DEFAULT NULL,
  `TITLE` varchar(2000) DEFAULT NULL,
  `PI_PERSON_ID` varchar(45) DEFAULT NULL,
  `PI_NAME` varchar(60) DEFAULT NULL,
  `SPONSOR_NAME` varchar(60) DEFAULT NULL,
  `PRIME_SPONSOR_NAME` varchar(60) DEFAULT NULL,
  `PROPOSAL_START_DATE` date DEFAULT NULL,
  `PROPOSAL_END_DATE` date DEFAULT NULL,
  `LEAD_UNIT_NAME` varchar(45) DEFAULT NULL,
  `FED_AT` datetime DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `KEY_PERSON_ID` varchar(45) DEFAULT NULL,
  `KEY_PERSON_NAME` varchar(60) DEFAULT NULL,
  `KEY_PERSON_ROLE_CODE` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COI_PROJECT_INST_PROPOSAL_FK1_idx` (`COI_PROJECT_TYPE_CODE`),
  CONSTRAINT `COI_PROJECT_INST_PROPOSAL_FK1` FOREIGN KEY (`COI_PROJECT_TYPE_CODE`) REFERENCES `coi_project_type` (`COI_PROJECT_TYPE_CODE`)
);

SET FOREIGN_KEY_CHECKS=1;
