DROP PROCEDURE IF EXISTS GENERATE_FORM_BUILDER_NUMBER;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_HISTORY;
DROP PROCEDURE IF EXISTS GET_CONSULTING_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
DROP PROCEDURE IF EXISTS COI_DISCL_ENT_PROJ_DETAILS;
DROP PROCEDURE IF EXISTS COI_EVALUATE_VALIDATION;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_PROJECTS;
DROP PROCEDURE IF EXISTS SYNC_SFIS_AND_DISCLOSURE;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITIES;
DROP PROCEDURE IF EXISTS EVALUATE_FORM_MANDATORY_VALIDATION;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_RELATIONS;

DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;

DROP VIEW IF EXISTS coi_project_institute_proposal_v;
DROP VIEW IF EXISTS coi_project_proposal_v;
DROP VIEW IF EXISTS coi_project_award_v;