\. ./FIBI-COI-5.0.1/Procedures/GENERATE_FORM_BUILDER_NUMBER.sql
\. ./FIBI-COI-5.0.1/Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./FIBI-COI-5.0.1/Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./FIBI-COI-5.0.1/Procedures/GET_COI_DISCLOSURE_HISTORY.sql
\. ./FIBI-COI-5.0.1/Procedures/GET_CONSULTING_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./FIBI-COI-5.0.1/Procedures/GET_ALL_RIGHTS_FOR_A_MODULE.sql
\. ./FIBI-COI-5.0.1/Procedures/COI_DISCL_ENT_PROJ_DETAILS.sql
\. ./FIBI-COI-5.0.1/Procedures/COI_EVALUATE_VALIDATION.sql
\. ./FIBI-COI-5.0.1/Procedures/GET_DISCLOSURE_PROJECTS.sql
\. ./FIBI-COI-5.0.1/Procedures/SYNC_SFIS_AND_DISCLOSURE.sql
\. ./FIBI-COI-5.0.1/Procedures/GET_PERSON_ENTITIES.sql
\. ./FIBI-COI-5.0.1/Procedures/EVALUATE_FORM_MANDATORY_VALIDATION.sql
\. ./FIBI-COI-5.0.1/Procedures/GET_DISCLOSURE_RELATIONS.sql

\. ./FIBI-COI-5.0.1/Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
