CREATE TABLE IF NOT EXISTS DIVISION_TYPE (
DIVISION_TYPE_CODE INT PRIMARY KEY,
DIVISION_TYPE_NAME VARCHAR(30)NOT NULL ,
UPDATE_USER VARCHAR(60),
UPDATE_TIMESTAMP DATETIME
);

ALTER TABLE STATES ADD
DIVISION_TYPE_CODE INT,
ADD CONSTRAINT DIVISION_TYPE_FK1 FOREIGN KEY (DIVISION_TYPE_CODE) REFERENCES DIVISION_TYPE(DIVISION_TYPE_CODE);

INSERT INTO DIVISION_TYPE (DIVISION_TYPE_CODE, DIVISION_TYPE_NAME ,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (1, 'State','admin',NOW());
INSERT INTO DIVISION_TYPE (DIVISION_TYPE_CODE, DIVISION_TYPE_NAME ,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (2, 'Island','admin',NOW());
INSERT INTO DIVISION_TYPE (DIVISION_TYPE_CODE, DIVISION_TYPE_NAME ,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (3, 'Municipality','admin',NOW());
INSERT INTO DIVISION_TYPE (DIVISION_TYPE_CODE, DIVISION_TYPE_NAME ,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (4, 'District','admin',NOW());
INSERT INTO DIVISION_TYPE (DIVISION_TYPE_CODE, DIVISION_TYPE_NAME ,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (5, 'Territory','admin',NOW());
INSERT INTO DIVISION_TYPE (DIVISION_TYPE_CODE, DIVISION_TYPE_NAME ,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (6, 'City','admin',NOW());
INSERT INTO DIVISION_TYPE (DIVISION_TYPE_CODE, DIVISION_TYPE_NAME ,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (7, 'Village','admin',NOW());
INSERT INTO DIVISION_TYPE (DIVISION_TYPE_CODE, DIVISION_TYPE_NAME ,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (8, 'Commune','admin',NOW());
INSERT INTO DIVISION_TYPE (DIVISION_TYPE_CODE, DIVISION_TYPE_NAME ,UPDATE_USER,UPDATE_TIMESTAMP) VALUES (9, 'City-state','admin',NOW());

SET SQL_SAFE_UPDATES = 0;
update states set DIVISION_TYPE_CODE = 1;
SET SQL_SAFE_UPDATES = 1;
