ALTER TABLE FORM_BUILDER_HEADER ADD COLUMN VERSION_MODE VARCHAR(1) NOT NULL DEFAULT 'A';
ALTER TABLE FB_COMP_CUSTOM_ELEMENT ADD COLUMN PLACE_HOLDER_TEXT VARCHAR(255) DEFAULT NULL;
ALTER TABLE FORM_BUILDER_HEADER MODIFY TITLE VARCHAR(1000), MODIFY DESCRIPTION VARCHAR(4000);
