CREATE OR REPLACE FUNCTION FIBI_COI_AWD_PER_IS_DISCL_REQ (
  AV_PROJECT_NUMBER IN VARCHAR2,
  AV_PERSON_ID IN VARCHAR2
) RETURN VARCHAR2
IS
  LI_COUNT NUMBER;
  LS_PERSON_ROLE_CODE VARCHAR2(12);
BEGIN
  -- Possbile Return values are NOT_REQUIRED, REQUIRED

  -- If person is non employee then disclosure is not required
    IF AV_PERSON_ID IS NULL THEN
      RETURN 'NOT_REQUIRED';  
    END IF;
	
    SELECT T2.CONTACT_ROLE_CODE INTO LS_PERSON_ROLE_CODE
    FROM AWARD T1
    INNER JOIN AWARD_PERSONS T2 ON T2.AWARD_NUMBER=T1.AWARD_NUMBER
    AND T1.SEQUENCE_NUMBER = T2.SEQUENCE_NUMBER
    WHERE T1.AWARD_NUMBER = AV_PROJECT_NUMBER
    AND T1.AWARD_SEQUENCE_STATUS = 'ACTIVE'
    AND T2.PERSON_ID = AV_PERSON_ID
    AND T2.SEQUENCE_NUMBER = (SELECT MAX(AP.SEQUENCE_NUMBER)
                              FROM AWARD_PERSONS AP
                              WHERE AP.AWARD_NUMBER = AV_PROJECT_NUMBER
                              AND AP.PERSON_ID = AV_PERSON_ID);

    SELECT COUNT(T2.AWARD_ID) INTO LI_COUNT
    FROM AWARD T1
    INNER JOIN AWARD_CUSTOM_DATA T2 ON T1.AWARD_ID = T2.AWARD_ID
    WHERE T1.AWARD_NUMBER = AV_PROJECT_NUMBER
    AND T2.CUSTOM_ATTRIBUTE_ID = 31
    AND T1.AWARD_SEQUENCE_STATUS = 'ACTIVE'
    AND ((LS_PERSON_ROLE_CODE IN ('PI','COI','MPI') AND T2.VALUE IN ('PC','PCK'))
    OR (LS_PERSON_ROLE_CODE ='KP' AND T2.VALUE ='PCK')); 

    IF LI_COUNT > 0 THEN
      RETURN 'REQUIRED';  
    END IF;
  
  -- Check sponsor hierarchy
  WITH GET_SPONSORS_FROM_HIERARCHY AS (
    SELECT SPONSOR_CODE 
    FROM SPONSOR_HIERARCHY
    WHERE HIERARCHY_NAME = 'COI Disclosures' AND
    ((LS_PERSON_ROLE_CODE ='KP' AND LEVEL1 = 'COI Disclosures with KP Req')
	OR (LS_PERSON_ROLE_CODE IN ('PI','COI','MPI')))
  )
  SELECT COUNT(AWARD_NUMBER) INTO LI_COUNT
  FROM AWARD 
  WHERE AWARD_NUMBER = AV_PROJECT_NUMBER
  AND AWARD_SEQUENCE_STATUS = 'ACTIVE'
  AND (SPONSOR_CODE IN (SELECT SPONSOR_CODE FROM GET_SPONSORS_FROM_HIERARCHY) 
      OR 
      PRIME_SPONSOR_CODE IN (SELECT SPONSOR_CODE FROM GET_SPONSORS_FROM_HIERARCHY));

  IF LI_COUNT > 0 THEN
    RETURN 'REQUIRED'; 
  END IF;

  RETURN 'NOT_REQUIRED';  

END FIBI_COI_AWD_PER_IS_DISCL_REQ;
