ANALYZE TABLE WIDGET_LOOKUP;

-- Rename ACTIVE_FLAG to IS_ACTIVE if it exists
SET @SQL := IF(
    EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'WIDGET_LOOKUP'
          AND COLUMN_NAME = 'ACTIVE_FLAG'
    ),
    'ALTER TABLE `WIDGET_LOOKUP` CHANGE COLUMN `ACTIVE_FLAG` `IS_ACTIVE` VARCHAR(1);',
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

-- Add MODULE_CODE column, index, and foreign key if not exist
SET @SQL := IF(
    EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'WIDGET_LOOKUP'
          AND COLUMN_NAME = 'MODULE_CODE'
    ),
    'DO 1',
    'ALTER TABLE `WIDGET_LOOKUP`
        ADD COLUMN `MODULE_CODE` VARCHAR(5) NULL AFTER `IMAGE_PATH`,
        ADD INDEX `WIDGET_LOOKUP_IDX_1` (`MODULE_CODE` ASC) VISIBLE,
        ADD CONSTRAINT `WIDGET_LOOKUP_FK_1`
            FOREIGN KEY (`MODULE_CODE`)
            REFERENCES `DYN_MODULES_CONFIG` (`MODULE_CODE`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;'
);

PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;
