INSERT INTO mq_router_action_configuration (ACTION_TYPE, IS_ACTIVE, MODULE_CODE, QUEUE_NAME, SUB_MODULE_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT 'PERS_DISC_REQ_NOTIFY','Y','23','Q_NOTIFICATION','0',NOW(),'admin'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM mq_router_action_configuration WHERE ACTION_TYPE='PERS_DISC_REQ_NOTIFY');

INSERT INTO `module_action_type` (`ACTION_TYPE`, `MODULE_CODE`, `SUB_MODULE_CODE`, `IS_ACTIVE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
SELECT 'PERS_DISC_REQ_NOTIFY', '23', '0', 'Y', 'OPA Person Notify', NOW(), 'admin'
WHERE NOT EXISTS (SELECT 1 FROM `module_action_type` WHERE `ACTION_TYPE` = 'PERS_DISC_REQ_NOTIFY');

INSERT INTO PREFERENCE_TYPE (PREFERENCES_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT '8001', 'OPA Department', NOW(), 'admin'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PREFERENCE_TYPE WHERE PREFERENCES_TYPE_CODE = '8001');

INSERT INTO PREFERENCE_TYPE (PREFERENCES_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
SELECT '8002', 'OPA Include Child Unit', NOW(), 'admin'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PREFERENCE_TYPE WHERE PREFERENCES_TYPE_CODE = '8002');

INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
SELECT (SELECT IFNULL(MAX(RIGHT_ID), 0) + 1 FROM RIGHTS), 'VIEW_OPA_ELIGIBILITY', 'To View OPA Eligible persons', 'quickstart', NOW(), '1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM RIGHTS WHERE RIGHT_NAME = 'VIEW_OPA_ELIGIBILITY');

INSERT INTO RIGHTS (RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
SELECT (SELECT IFNULL(MAX(RIGHT_ID), 0) + 1 FROM RIGHTS), 'MAINTAIN_OPA_ELIGIBILITY', 'To Maintain OPA Eligible persons', 'quickstart', NOW(), '1'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM RIGHTS WHERE RIGHT_NAME = 'MAINTAIN_OPA_ELIGIBILITY');

INSERT IGNORE INTO `dyn_modules_config` (`MODULE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('RWDS', 'Coi Reviewer Dashboard', 'Y', now(), 'admin');

INSERT IGNORE INTO `WIDGET_LOOKUP` (`WIDGET_ID`, `DESCRIPTION`, `WIDGET_NAME`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `SIZE`, `MODULE_CODE`) 
VALUES ('8001', 'Coi Reviewer Dashboard FCOI', 'FCOI Disclosure', 'Y', now(), 'quickstart', 'S', 'RWDS');

INSERT IGNORE INTO `WIDGET_LOOKUP` (`WIDGET_ID`, `DESCRIPTION`, `WIDGET_NAME`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `SIZE`, `MODULE_CODE`) 
VALUES ('8002', 'Coi Reviewer Dashboard OPA', 'OPA Disclosure', 'Y', now(), 'quickstart', 'S', 'RWDS');

INSERT IGNORE INTO `WIDGET_LOOKUP` (`WIDGET_ID`, `DESCRIPTION`, `WIDGET_NAME`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `SIZE`, `MODULE_CODE`) 
VALUES ('8003', 'Coi Reviewer Dashboard Travel', 'Travel Disclosure', 'Y', now(), 'quickstart', 'S', 'RWDS');
