ANALYZE TABLE PERSON_DISCL_REQUIREMENT;

-- Add IS_EXEMPT_FROM_OPA column
SET @SQL := IF(
    EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'PERSON_DISCL_REQUIREMENT'
          AND COLUMN_NAME = 'IS_EXEMPT_FROM_OPA'
    ),
    'DO 1',
    'ALTER TABLE `PERSON_DISCL_REQUIREMENT` ADD COLUMN `IS_EXEMPT_FROM_OPA` VARCHAR(1) NULL;'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

-- Add VERSION_NUMBER column
SET @SQL := IF(
    EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'PERSON_DISCL_REQUIREMENT'
          AND COLUMN_NAME = 'VERSION_NUMBER'
    ),
    'DO 1',
    'ALTER TABLE `PERSON_DISCL_REQUIREMENT` ADD COLUMN `VERSION_NUMBER` INT NULL;'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

-- Add VERSION_STATUS column
SET @SQL := IF(
    EXISTS (
        SELECT 1
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'PERSON_DISCL_REQUIREMENT'
          AND COLUMN_NAME = 'VERSION_STATUS'
    ),
    'DO 1',
    'ALTER TABLE `PERSON_DISCL_REQUIREMENT` ADD COLUMN `VERSION_STATUS` VARCHAR(10) NULL;'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

SET SQL_SAFE_UPDATES = 0;
Update PERSON_DISCL_REQUIREMENT SEt IS_EXEMPT_FROM_OPA = 'N', VERSION_NUMBER = 1, VERSION_STATUS = 'ACTIVE';
SET SQL_SAFE_UPDATES = 1;
