DROP PROCEDURE IF EXISTS EVALUATE_FORM_VALIDATION;
DROP PROCEDURE IF EXISTS GET_OPA_DISCL_PERSON_ENTITY_REL;
DROP PROCEDURE IF EXISTS SYNC_OPA_DISCL_PERSON_ENTITY_REL;
DROP PROCEDURE IF EXISTS PROC_SYNC_OPA_PER_ENTITY;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_FUNCTION;
DROP FUNCTION IF EXISTS FN_IS_OPA_DISCL_ENG_COMPLETE;
DROP FUNCTION IF EXISTS FN_IS_SABB_FILLED_IN_DISCL_ENG;
