DELIMITER //
CREATE PROCEDURE `GENERATE_ATTACHMENT_NUMBER`()
BEGIN
    DECLARE LOCK_ACQUIRED INT DEFAULT 0;
    DECLARE NEXT_VALUE INT;
    START TRANSACTION;
    SELECT GET_LOCK('LOCK_ON_ATTACHMENT_NUMBER_COUNTER', 30) INTO LOCK_ACQUIRED;
    IF LOCK_ACQUIRED THEN
        SELECT COUNTER_VALUE INTO NEXT_VALUE FROM ATTACHMENT_NUMBER_COUNTER WHERE COUNTER_NAME = 'ATTACHMENT_COUNTER' FOR UPDATE;
		UPDATE ATTACHMENT_NUMBER_COUNTER SET COUNTER_VALUE = COUNTER_VALUE + 1 WHERE COUNTER_NAME = 'ATTACHMENT_COUNTER';
        SELECT RELEASE_LOCK('LOCK_ON_ATTACHMENT_NUMBER_COUNTER');
        COMMIT;
    END IF;
    SELECT NEXT_VALUE;
END
//
