DELIMITER //
CREATE PROCEDURE `COI_DISCL_VOID_DEACTIVATED_PROJECT`(
	AV_MODULE_CODE		VARCHAR(40),
	AV_MODULE_ITEM_KEY	VARCHAR(100),
	AV_PERSON_ID 		VARCHAR(40),
	AV_REMARK	 		VARCHAR(225),
	AV_ACTION_TYPE		VARCHAR(3)
)
BEGIN
	DECLARE LS_DYN_SQL TEXT;
	DECLARE LS_FILTER_CONDITION TEXT;

	DROP TEMPORARY TABLE IF EXISTS VOID_PROJECT_DISCLS;

    CREATE TEMPORARY TABLE VOID_PROJECT_DISCLS (
        DISCLOSURE_ID      INT,
        DISCLOSURE_NUMBER  INT,
        COI_PROJECT_TYPE   VARCHAR(200),
        PROJECT_TITLE      VARCHAR(1000),
        PROJECT_NUMBER     VARCHAR(20),
        PERSON_ID		   VARCHAR(40),
        FULL_NAME          VARCHAR(90)
    );

    SET LS_DYN_SQL = CONCAT('INSERT INTO VOID_PROJECT_DISCLS (
								DISCLOSURE_ID,
								DISCLOSURE_NUMBER,
								COI_PROJECT_TYPE,
								PROJECT_TITLE,
								PROJECT_NUMBER,
								PERSON_ID,
								FULL_NAME
								)
							SELECT
								t1.DISCLOSURE_ID as DISCLOSURE_ID,
								t1.DISCLOSURE_NUMBER as DISCLOSURE_NUMBER,
								T3.description as COI_PROJECT_TYPE,
								COALESCE(aw.TITLE, p.TITLE, ip.TITLE) AS PROJECT_TITLE,
								COALESCE(aw.PROJECT_NUMBER, p.PROPOSAL_NUMBER, ip.PROJECT_NUMBER) AS PROJECT_NUMBER,
								t1.PERSON_ID,
								T4.FULL_NAME
							FROM COI_DISCLOSURE t1
							INNER JOIN COI_DISCL_PROJECTS t2 ON t2.DISCLOSURE_ID = t1.DISCLOSURE_ID
							INNER JOIN COI_PROJECT_TYPE T3 on T3.COI_PROJECT_TYPE_CODE = t1.COI_PROJECT_TYPE_CODE
							LEFT JOIN PERSON T4 ON T1.PERSON_ID = T4.PERSON_ID
							LEFT JOIN coi_int_stage_dev_proposal p
								ON p.PROPOSAL_NUMBER = t2.MODULE_ITEM_KEY
								AND t2.MODULE_CODE = 3
							LEFT JOIN coi_int_stage_award aw
								ON aw.PROJECT_NUMBER = t2.MODULE_ITEM_KEY
								AND t2.MODULE_CODE = 1
							LEFT JOIN coi_int_stage_proposal ip
								ON ip.PROJECT_NUMBER = t2.MODULE_ITEM_KEY
								AND t2.MODULE_CODE = 2
							WHERE t1.FCOI_TYPE_CODE = 2
							AND t2.MODULE_ITEM_KEY = ''',AV_MODULE_ITEM_KEY,'''
							AND t2.MODULE_CODE = ',AV_MODULE_CODE);

	IF AV_PERSON_ID IS NOT NULL THEN
		SET LS_FILTER_CONDITION = CONCAT(' AND t1.REVIEW_STATUS_CODE in (1,5,6) AND t1.PERSON_ID = ''',AV_PERSON_ID,'''');
		SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, LS_FILTER_CONDITION);
		SET @LS_DYN_SQL = LS_DYN_SQL;

		PREPARE STMT FROM @LS_DYN_SQL;
		EXECUTE STMT;
		DEALLOCATE PREPARE STMT;

		SET SQL_SAFE_UPDATES = 0;
        UPDATE COI_DISCLOSURE t1
        JOIN VOID_PROJECT_DISCLS T2 ON T2.DISCLOSURE_ID = T1.DISCLOSURE_ID
        SET t1.DISPOSITION_STATUS_CODE = 2,
        t1.REMARK = AV_REMARK,
        t1.UPDATE_TIMESTAMP = UTC_TIMESTAMP();

		UPDATE INBOX T0
        INNER JOIN VOID_PROJECT_DISCLS T1 ON T1.DISCLOSURE_ID = T0.MODULE_ITEM_KEY
        SET T0.OPENED_FLAG = 'E',
        T0.UPDATE_TIMESTAMP = UTC_TIMESTAMP()
        WHERE T0.MESSAGE_TYPE_CODE=8002
		AND T0.OPENED_FLAG='N';
		SET SQL_SAFE_UPDATES = 1;
    ELSE
		SET @LS_DYN_SQL = LS_DYN_SQL;

		PREPARE STMT FROM @LS_DYN_SQL;
		EXECUTE STMT;
		DEALLOCATE PREPARE STMT;

		SET SQL_SAFE_UPDATES = 0;
		UPDATE COI_DISCLOSURE t1
		INNER JOIN VOID_PROJECT_DISCLS t2 ON t2.DISCLOSURE_ID = t1.DISCLOSURE_ID
        SET t1.DISPOSITION_STATUS_CODE = 2,
        t1.REMARK = AV_REMARK,
        t1.UPDATE_TIMESTAMP = UTC_TIMESTAMP();

        UPDATE INBOX T0
        INNER JOIN VOID_PROJECT_DISCLS T1 ON T1.DISCLOSURE_ID = T0.MODULE_ITEM_KEY
        SET T0.OPENED_FLAG = 'E',
        T0.UPDATE_TIMESTAMP = UTC_TIMESTAMP()
        WHERE T0.MESSAGE_TYPE_CODE=8002
        AND T0.OPENED_FLAG='N';
        SET SQL_SAFE_UPDATES = 1;

    END IF;

    INSERT INTO DISCLOSURE_ACTION_LOG (
	        disclosure_id,
	        disclosure_number,
	        action_type_code,
	        description,
	        update_timestamp,
	        update_user)
    SELECT
        t1.disclosure_id,
        t1.disclosure_number,
        AV_ACTION_TYPE as action_type_code,
    	REPLACE(t2.message, '{DISCLOSURE_TYPE}', t1.COI_PROJECT_TYPE) AS description,
        UTC_TIMESTAMP(),
        'admin'
    FROM VOID_PROJECT_DISCLS t1
    JOIN disclosure_action_type t2 ON t2.action_type_code = AV_ACTION_TYPE;

    SELECT * FROM VOID_PROJECT_DISCLS;
END
//
