DROP FUNCTION IF EXISTS FIBI_COI_AWD_PER_IS_DISCL_REQ;
DROP PROCEDURE IF EXISTS FIBI_COI_GET_AWARD_PERSONS;
DROP PROCEDURE IF EXISTS FIBI_COI_GET_AWARD;
DROP PROCEDURE IF EXISTS FIBI_COI_GET_INST_PROPOSAL;