DELIMITER //
CREATE PROCEDURE `GET_PROP_OVERALL_DISCL_STS`(AV_DISCLOSURE_ID INT)
BEGIN


	
	/*
	 SELECT MODULE_ITEM_KEY 
	    INTO LS_PROPOSAL_NUMBER
	   FROM COI_DISCL_PROJECTS 
	   WHERE MODULE_CODE = '3' 
	   AND DISCLOSURE_ID = AV_DISCLOSURE_ID; */

	
    
    UPDATE COI_INT_STAGE_DEV_PROPOSAL_PERSON CPP,
	    COI_INT_STAGE_DEV_PROPOSAL CIP,
		COI_DISCL_PROJECTS CD,
		COI_DISCLOSURE CDI
	SET CPP.DISCLOSURE_STATUS =(CASE 
								WHEN CPP.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED'
									THEN (SELECT CASE 
											WHEN CDI.REVIEW_STATUS_CODE IN (
													2
													,3
													,4
													,7
													,8
													)
												THEN 'DISCLOSURE_COMPLETED'
											ELSE 'DISCLOSURE_PENDING'
											END
											FROM COI_DISCLOSURE CDI
											WHERE CDI.DISCLOSURE_ID = AV_DISCLOSURE_ID)
								WHEN CPP.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED'
									THEN 'DISCLOSURE_NOT_REQUIRED'
								ELSE 'DISCLOSURE_TO_BE_DETERMINED'
								END),
			CPP.DISCLOSURE_REVIEW_STATUS = (CASE 
										WHEN CPP.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED'
											THEN ( SELECT DESCRIPTION
													FROM COI_REVIEW_STATUS_TYPE CRS,
													      COI_DISCLOSURE CDI
													WHERE CRS.REVIEW_STATUS_CODE = CDI.REVIEW_STATUS_CODE
													  AND CDI.DISCLOSURE_ID = AV_DISCLOSURE_ID)
										WHEN CPP.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED'
											THEN 'DISCLOSURE_REVIEW_NA'
										ELSE NULL
										END )
	 WHERE CD.MODULE_CODE = '3'
	   AND CD.DISCLOSURE_ID  = AV_DISCLOSURE_ID 
	   AND CIP.PROPOSAL_NUMBER = CD.MODULE_ITEM_KEY
	   AND CPP.PROPOSAL_NUMBER = CIP.PROPOSAL_NUMBER
	   AND CPP.STATUS = 'A'
       AND CPP.KEY_PERSON_ID = CDI.PERSON_ID
	   AND CDI.DISCLOSURE_ID = AV_DISCLOSURE_ID;
	   
	   
	   UPDATE COI_INT_STAGE_DEV_PROPOSAL  CIP 
		   SET OVERALL_DISCLOSURE_STATUS = CASE WHEN NOT EXISTS (
																SELECT 1
																FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
																WHERE PROPOSAL_NUMBER = CIP.PROPOSAL_NUMBER
																  AND DISCLOSURE_STATUS NOT IN ('DISCLOSURE_NOT_REQUIRED')
																  AND STATUS = 'A'
															) THEN 'DISCLOSURE_NOT_REQUIRED'
		   
												WHEN NOT EXISTS (
																	SELECT 1
																	FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
																	WHERE PROPOSAL_NUMBER = CIP.PROPOSAL_NUMBER
																	  AND DISCLOSURE_STATUS NOT IN ('DISCLOSURE_COMPLETED','DISCLOSURE_NOT_REQUIRED')
																	  AND STATUS = 'A'
													            ) THEN 'DISCLOSURE_COMPLETED'
												WHEN  EXISTS (
																SELECT 1
																FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
																WHERE PROPOSAL_NUMBER = CIP.PROPOSAL_NUMBER
																  AND DISCLOSURE_STATUS = 'DISCLOSURE_TO_BE_DETERMINED' 
																  AND STATUS = 'A'
															) THEN 'DISCLOSURE_TO_BE_DETERMINED'
												WHEN EXISTS (
																SELECT 1
																FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
																WHERE PROPOSAL_NUMBER = CIP.PROPOSAL_NUMBER
																  AND DISCLOSURE_STATUS = 'DISCLOSURE_PENDING' 
																  AND STATUS = 'A'
															) THEN 'DISCLOSURE_PENDING'	
												END
		 WHERE  PROPOSAL_NUMBER IN   ( SELECT MODULE_ITEM_KEY 
		                              FROM COI_DISCL_PROJECTS 
									  WHERE MODULE_CODE = 3 
									  AND DISCLOSURE_ID = AV_DISCLOSURE_ID);
									  
									  
		UPDATE COI_INT_STAGE_DEV_PROPOSAL  CIP
		   SET OVERALL_DISCL_REVIEW_STATUS = CASE 
												WHEN OVERALL_DISCLOSURE_STATUS = 'DISCLOSURE_NOT_REQUIRED' THEN 'N/A'																														
												WHEN OVERALL_DISCLOSURE_STATUS = 'DISCLOSURE_TO_BE_DETERMINED' THEN '--'
												WHEN NOT EXISTS (
																	SELECT 1
																	FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
																	WHERE PROPOSAL_NUMBER = CIP.PROPOSAL_NUMBER
																	  AND DISCLOSURE_REVIEW_STATUS NOT IN ('Completed','DISCLOSURE_REVIEW_NA')
													            ) THEN 'Completed'
												ELSE 'Pending'
												END
		 WHERE  PROPOSAL_NUMBER IN   ( SELECT MODULE_ITEM_KEY 
		                              FROM COI_DISCL_PROJECTS 
									  WHERE MODULE_CODE = 3 
									  AND DISCLOSURE_ID = AV_DISCLOSURE_ID);	
		
	   /*
	   SELECT MODULE_ITEM_KEY 
	    INTO LS_PROPOSAL_NUMBER
	   FROM COI_DISCL_PROJECTS 
	   WHERE MODULE_CODE = '3' 
	   AND DISCLOSURE_ID = AV_DISCLOSURE_ID;
	   
	   SELECT PERSON_ID 
		 INTO LS_PERSON_ID 
	    FROM COI_DISCLOSURE 
		WHERE DISCLOSURE_ID = AV_DISCLOSURE_ID;
	   
		-- Overall Disclosure Status
		
		SET LS_OVERALL_DISCL_STS := NULL;
	    IF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND (DISCLOSURE_STATUS IS NOT NULL)
		) THEN
			SET LS_OVERALL_DISCL_STS := NULL;
    
		
		ELSEIF EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND (DISCLOSURE_STATUS = 'DISCLOSURE_TO_BE_DETERMINED')
		) THEN
			 SET LS_OVERALL_DISCL_STS := NULL;
    
        ELSEIF  EXISTS (
        SELECT 1
        FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
        WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
          AND DISCLOSURE_STATUS = 'DISCLOSURE_PENDING'
		  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_PENDING';

		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS != 'DISCLOSURE_COMPLETED'
			  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			 SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_COMPLETED';
		
    
		ELSEIF EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS IN ('DISCLOSURE_NOT_REQUIRED' )
			  AND DISCLOSURE_STATUS IS NOT NULL
		) AND EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS = 'DISCLOSURE_TO_BE_DETERMINED'
			  AND DISCLOSURE_STATUS IS NOT NULL
		) AND NOT EXISTS (
				SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS = 'DISCLOSURE_COMPLETED'
			  AND DISCLOSURE_STATUS IS NOT NULL)
		THEN
			SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_NOT_REQUIRED';
		
    

		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS NOT IN ('DISCLOSURE_NOT_REQUIRED')
			  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_NOT_REQUIRED';
		
		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS != 'DISCLOSURE_TO_BE_DETERMINED'
			  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			SET LS_OVERALL_DISCL_STS := NULL;
    
    
        ELSEIF EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS IN ('DISCLOSURE_NOT_REQUIRED', 'DISCLOSURE_TO_BE_DETERMINED')
			  AND DISCLOSURE_STATUS IS NOT NULL
		) AND EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS = 'DISCLOSURE_COMPLETED'
			  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_COMPLETED';
		END IF;
		
		-- Overall Review Status
		SET LS_OVERALL_DISCL_RVW_STS := NULL;
		
		IF NOT EXISTS (
			SELECT 1
				FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
				WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
				  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
				   
			)  THEN
				SET LS_OVERALL_DISCL_RVW_STS := NULL;
		
    
		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
			  AND DISCLOSURE_STATUS != 'DISCLOSURE_PENDING'
			   
		) THEN
			SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_PENDING';	
    
		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_REVIEW_STATUS NOT IN ('DISCLOSURE_REVIEW_NA')
			  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL         
			 
		) THEN
        
			IF EXISTS (
				SELECT 1
				FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
				WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
				  AND DISCLOSURE_REVIEW_STATUS IS NULL
				  AND DISCLOSURE_STATUS = 'DISCLOSURE_PENDING'
				   
				) THEN
			 SET LS_OVERALL_DISCL_RVW_STS := NULL;
			 
			 ELSE 
				SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_NA_REVIEW';
			 END IF;
		

		ELSEIF NOT EXISTS (
				SELECT 1
				FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
				WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
				  AND DISCLOSURE_REVIEW_STATUS NOT IN ('DISCLOSURE_NOT_REQUIRED')
				  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
		   )  THEN
			SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_NOT_REQUIRED';

		ELSEIF EXISTS (
				SELECT 1
				FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
				WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
				  AND DISCLOSURE_REVIEW_STATUS IN ('WITHDRAWN', 'SUBMITTED', 'PENDING', 
											'REVIEW IN PROGRESS', 'REVIEW ASSIGNED', 'RETURNED',
											'ASSIGNED REVIEW COMPLETED')
				   AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
			   
			)  THEN
			SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_PENDING';

		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_REVIEW_STATUS NOT IN ('COMPLETED', 
											'DISCLOSURE_REVIEW_NA', 
											'DISCLOSURE_NOT_REQUIRED')
			  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
			 )  THEN
			SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_COMPLETED';
		END IF;
		
		UPDATE COI_INT_STAGE_DEV_PROPOSAL
		   SET OVERALL_DISCLOSURE_STATUS = LS_OVERALL_DISCL_STS,
		       OVERALL_DISCL_REVIEW_STATUS = LS_OVERALL_DISCL_RVW_STS
		WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER; */

END
//
