DELIMITER //
CREATE PROCEDURE `GET_EXPIRING_FCOI_AND_OPA_DISCLOSURES`()
BEGIN
    DECLARE DONE INT DEFAULT FALSE;
    DECLARE LI_LEGACY_DAYS_TO_DUE_DATE INT;

	-- CURSOR FOR LEGACY COI REMINDER DAYS  
    DECLARE LEGACY_CURSOR CURSOR FOR 
        SELECT DAYS_TO_DUE_DATE 
        FROM REMINDER_NOTIFICATION 
        WHERE NOTIFICATION_TYPE_ID = 8092 AND IS_ACTVE = 'Y';

    -- EXCEPTION HANDLER
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    
     -- DROP TEMP TABLE IF EXISTS
    DROP TEMPORARY TABLE IF EXISTS TEMP_EXPIRING_DISCL_TO_NOTIFY;
    
    -- CREATE TEMP TABLE TO STORE COMBINED DISCLOSURES
    CREATE TEMPORARY TABLE TEMP_EXPIRING_DISCL_TO_NOTIFY (
        DISCLOSURE_ID INT,
        DISCLOSURE_NUMBER VARCHAR(100),
        PERSON_ID VARCHAR(40),
        DISCLOSURE_TYPE VARCHAR(50),
        EXPIRATION_DATE DATE,
        DAYS_TO_DUE_DATE INT,
        IS_LEGACY_DISCLOSURE CHAR(1) DEFAULT 'N',
        VERSION_STATUS VARCHAR(45),
        CERTIFICATION_DATE DATE,
        REPORTER_NAME VARCHAR(90),
        DEPARTMENT_NUMBER VARCHAR(8),
        DEPARTMENT_NAME VARCHAR(200),
        DISPOSITION_STATUS VARCHAR(20)
    );
    -- RESET DONE FLAG FOR LEGACY CURSOR
    SET DONE = FALSE;
    
	-- PROCESS LEGACY DISCLOSURES FOR EACH REMINDER DAY
    OPEN LEGACY_CURSOR;
    LEGACY_LOOP: LOOP
        FETCH LEGACY_CURSOR INTO LI_LEGACY_DAYS_TO_DUE_DATE;
        IF DONE THEN
            LEAVE LEGACY_LOOP;
        END IF;
        
        -- INSERT EXPIRING LEGACY DISCLOSURES FOR CURRENT DAYS_TO_DUE_DATE
        INSERT INTO TEMP_EXPIRING_DISCL_TO_NOTIFY (DISCLOSURE_ID, DISCLOSURE_NUMBER, PERSON_ID, DISCLOSURE_TYPE, EXPIRATION_DATE, DAYS_TO_DUE_DATE, IS_LEGACY_DISCLOSURE, VERSION_STATUS, CERTIFICATION_DATE, REPORTER_NAME, DEPARTMENT_NUMBER, DEPARTMENT_NAME, DISPOSITION_STATUS)
            SELECT
				DISTINCT
				CD.LEGACY_DISCLOSURE_ID,
				CD.COI_DISCLOSURE_NUMBER,
				CD.PERSON_ID,
				'FCOI' DISCLOSURE_TYPE,
				CD.EXPIRATION_DATE,
				LI_LEGACY_DAYS_TO_DUE_DATE,
				'Y' AS IS_LEGACY_DISCLOSURE,
                'ACTIVE' AS VERSION_STATUS,
                CD.CERTIFICATION_TIMESTAMP,
                P.FULL_NAME,
                U.UNIT_NUMBER,
                U.UNIT_NAME,
                'Approved' AS DISPOSITION_STATUS
			FROM LEGACY_COI_DISCLOSURE CD
            JOIN LEGACY_COI_DISC_DETAILS CDP
                ON CDP.LEGACY_DISCLOSURE_ID = CD.LEGACY_DISCLOSURE_ID
            JOIN (
                SELECT MODULE_ITEM_KEY, KEY_PERSON_ID, MODULE_CODE
                FROM (
                    SELECT PROJECT_NUMBER AS MODULE_ITEM_KEY, KEY_PERSON_ID, STATUS, 1 AS MODULE_CODE
                    FROM COI_INT_STAGE_AWARD_PERSON
                    WHERE DISCLOSURE_REQUIRED_FLAG IS NOT NULL AND DISCLOSURE_REQUIRED_FLAG <> 'NOT_REQUIRED'
                    UNION ALL
                    SELECT PROPOSAL_NUMBER AS MODULE_ITEM_KEY, KEY_PERSON_ID, STATUS, 3 AS MODULE_CODE
                    FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
                    WHERE DISCLOSURE_REQUIRED_FLAG IS NOT NULL AND DISCLOSURE_REQUIRED_FLAG <> 'NOT_REQUIRED'
                ) s
                WHERE s.STATUS = 'A'
                GROUP BY MODULE_ITEM_KEY, KEY_PERSON_ID
            ) stage
                ON stage.MODULE_CODE = CDP.MODULE_CODE
                AND stage.MODULE_ITEM_KEY = CDP.MODULE_ITEM_KEY
            AND stage.KEY_PERSON_ID = CD.PERSON_ID
            LEFT JOIN PERSON P ON P.PERSON_ID = CD.PERSON_ID
            LEFT JOIN UNIT U ON P.HOME_UNIT = U.UNIT_NUMBER
            WHERE CD.DISCLOSURE_DISPOSITION_CODE = 1
            AND CD.DISC_ACTIVE_STATUS = 1
            AND CD.EVENT_TYPE_CODE IN (5, 6)
            AND CD.EXPIRATION_DATE = DATE_ADD(CURDATE(), INTERVAL LI_LEGACY_DAYS_TO_DUE_DATE DAY)
            AND (
                    NOT EXISTS (
                        SELECT 1
                        FROM COI_DISCL_PROJECTS T1
                        JOIN COI_DISCLOSURE T2
                            ON T1.DISCLOSURE_ID = T2.DISCLOSURE_ID
                        AND T2.PERSON_ID = CD.PERSON_ID
                        WHERE T1.MODULE_ITEM_KEY = CDP.MODULE_ITEM_KEY
                    )
                    OR EXISTS (
                        SELECT 1
                        FROM COI_DISCL_PROJECTS T1
                        JOIN COI_DISCLOSURE T2
                            ON T1.DISCLOSURE_ID = T2.DISCLOSURE_ID
                        AND T2.PERSON_ID = CD.PERSON_ID
                        WHERE T1.MODULE_ITEM_KEY = CDP.MODULE_ITEM_KEY
                        AND T2.REVIEW_STATUS_CODE IN (1, 9, 10)
                    )
                );

    END LOOP;

    CLOSE LEGACY_CURSOR;

    SELECT * FROM TEMP_EXPIRING_DISCL_TO_NOTIFY;
    DROP TEMPORARY TABLE TEMP_EXPIRING_DISCL_TO_NOTIFY;
END
//
