DELIMITER //
CREATE PROCEDURE `OPA_DISCL_RENEWAL_REMINDER`(AV_DAYS INT)
BEGIN

        SELECT
            0 AS SUB_MODULE_ITEM_KEY,
            OPA_DISCLOSURE_ID AS MODULE_ITEM_KEY,
            23 AS MODULE_CODE,
            0 AS SUB_MODULE_CODE
        FROM OPA_DISCLOSURE
        WHERE  DATE(EXPIRATION_DATE) = DATE(DATE_ADD(utc_timestamp(), INTERVAL AV_DAYS DAY))
        AND VERSION_STATUS = 'ACTIVE';
END
//
