DELIMITER //
CREATE PROCEDURE `GET_EXPIRING_FCOI_AND_OPA_DISCLOSURES`()
BEGIN
    DECLARE DONE INT DEFAULT FALSE;
    DECLARE LS_FCOI_DAYS_TO_DUE_DATE INT;
    DECLARE LS_OPA_DAYS_TO_DUE_DATE INT;

    -- CURSOR FOR FCOI REMINDER DAYS
    DECLARE FCOI_CURSOR CURSOR FOR 
        SELECT DAYS_TO_DUE_DATE 
        FROM REMINDER_NOTIFICATION 
        WHERE NOTIFICATION_TYPE_ID = 8022 AND IS_ACTVE = 'Y';

    -- CURSOR FOR OPA REMINDER DAYS  
    DECLARE OPA_CURSOR CURSOR FOR 
        SELECT DAYS_TO_DUE_DATE 
        FROM REMINDER_NOTIFICATION 
        WHERE NOTIFICATION_TYPE_ID = 8090 AND IS_ACTVE = 'Y';

    -- EXCEPTION HANDLER
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    
     -- DROP TEMP TABLE IF EXISTS
    DROP TEMPORARY TABLE IF EXISTS TEMP_EXPIRING_DISCL_TO_NOTIFY;
    
    -- CREATE TEMP TABLE TO STORE COMBINED DISCLOSURES
    CREATE TEMPORARY TABLE TEMP_EXPIRING_DISCL_TO_NOTIFY (
        DISCLOSURE_ID INT,
        DISCLOSURE_NUMBER VARCHAR(100),
        PERSON_ID VARCHAR(40),
        DISCLOSURE_TYPE VARCHAR(50),
        EXPIRATION_DATE DATE,
        DAYS_TO_DUE_DATE INT,
        IS_LEGACY_DISCLOSURE CHAR(1) DEFAULT 'N'
    );

    -- PROCESS FCOI DISCLOSURES FOR EACH REMINDER DAY
    OPEN FCOI_CURSOR;
    FCOI_LOOP: LOOP
        FETCH FCOI_CURSOR INTO LS_FCOI_DAYS_TO_DUE_DATE;
        IF DONE THEN
            LEAVE FCOI_LOOP;
        END IF;

        -- INSERT EXPIRING FCOI DISCLOSURES FOR CURRENT DAYS_TO_DUE_DATE
        INSERT INTO TEMP_EXPIRING_DISCL_TO_NOTIFY (DISCLOSURE_ID, DISCLOSURE_NUMBER, PERSON_ID, DISCLOSURE_TYPE, EXPIRATION_DATE, DAYS_TO_DUE_DATE)
        SELECT 
            CD.DISCLOSURE_ID,
            CD.DISCLOSURE_NUMBER,
            CD.PERSON_ID,
            'FCOI',
            CD.EXPIRATION_DATE,
            LS_FCOI_DAYS_TO_DUE_DATE
        FROM COI_DISCLOSURE CD
        WHERE CD.FCOI_TYPE_CODE IN (1,3)
        AND CD.DISCLOSURE_ID = (
            SELECT MAX(DISCLOSURE_ID)
            FROM COI_DISCLOSURE CD2
            WHERE CD2.DISCLOSURE_NUMBER = CD.DISCLOSURE_NUMBER
        )
        AND CD.DISCLOSURE_NUMBER IN (
            SELECT DISTINCT DISCLOSURE_NUMBER
            FROM COI_DISCLOSURE
            WHERE DISPOSITION_STATUS_CODE = '3'
              AND VERSION_STATUS = 'ACTIVE'
              AND DATE(EXPIRATION_DATE) = DATE_ADD(CURDATE(), INTERVAL LS_FCOI_DAYS_TO_DUE_DATE DAY)
        )
        AND (DATE(CD.EXPIRATION_DATE) = DATE_ADD(CURDATE(), INTERVAL LS_FCOI_DAYS_TO_DUE_DATE DAY)
        OR CD.REVIEW_STATUS_CODE IN (1, 5, 6));

        -- INSERT EXPIRING LEGACY DISCLOSURES FOR CURRENT DAYS_TO_DUE_DATE
        INSERT INTO TEMP_EXPIRING_DISCL_TO_NOTIFY (DISCLOSURE_ID, DISCLOSURE_NUMBER, PERSON_ID, DISCLOSURE_TYPE, EXPIRATION_DATE, DAYS_TO_DUE_DATE, IS_LEGACY_DISCLOSURE)
            SELECT
				DISTINCT
				CD.LEGACY_DISCLOSURE_ID,
				CD.COI_DISCLOSURE_NUMBER,
				CD.PERSON_ID,
				CASE
					WHEN CD.EVENT_TYPE_CODE IN (1, 2) THEN 'PROJECT'
					ELSE 'FCOI'
				END AS DISCLOSURE_TYPE,
				CD.EXPIRATION_DATE,
				LS_FCOI_DAYS_TO_DUE_DATE,
				'Y' AS IS_LEGACY_DISCLOSURE
			FROM LEGACY_COI_DISCLOSURE CD
            JOIN LEGACY_COI_DISC_DETAILS CDP
                ON CDP.LEGACY_DISCLOSURE_ID = CD.LEGACY_DISCLOSURE_ID
            JOIN (
                SELECT MODULE_ITEM_KEY, KEY_PERSON_ID, MODULE_CODE
                FROM (
                    SELECT PROJECT_NUMBER AS MODULE_ITEM_KEY, KEY_PERSON_ID, STATUS, 1 AS MODULE_CODE
                    FROM COI_INT_STAGE_AWARD_PERSON
                    UNION ALL
                    SELECT PROPOSAL_NUMBER AS MODULE_ITEM_KEY, KEY_PERSON_ID, STATUS, 3 AS MODULE_CODE
                    FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
                    UNION ALL
                    SELECT PROJECT_NUMBER AS MODULE_ITEM_KEY, KEY_PERSON_ID, STATUS, 2 AS MODULE_CODE
                    FROM COI_INT_STAGE_PROPOSAL_PERSON
                ) s
                WHERE s.STATUS = 'A'
                GROUP BY MODULE_ITEM_KEY, KEY_PERSON_ID
            ) stage
                ON stage.MODULE_CODE = CDP.MODULE_CODE
                AND stage.MODULE_ITEM_KEY = CDP.MODULE_ITEM_KEY
            AND stage.KEY_PERSON_ID = CD.PERSON_ID
            WHERE CD.DISCLOSURE_DISPOSITION_CODE = 1
            AND CD.DISC_ACTIVE_STATUS = 1
            AND CD.EXPIRATION_DATE = DATE_ADD(CURDATE(), INTERVAL LS_FCOI_DAYS_TO_DUE_DATE DAY)
            AND (
                    NOT EXISTS (
                        SELECT 1
                        FROM COI_DISCL_PROJECTS T1
                        JOIN COI_DISCLOSURE T2
                            ON T1.DISCLOSURE_ID = T2.DISCLOSURE_ID
                        AND T2.PERSON_ID = CD.PERSON_ID
                        WHERE T1.MODULE_ITEM_KEY = CDP.MODULE_ITEM_KEY
                    )
                    OR EXISTS (
                        SELECT 1
                        FROM COI_DISCL_PROJECTS T1
                        JOIN COI_DISCLOSURE T2
                            ON T1.DISCLOSURE_ID = T2.DISCLOSURE_ID
                        AND T2.PERSON_ID = CD.PERSON_ID
                        WHERE T1.MODULE_ITEM_KEY = CDP.MODULE_ITEM_KEY
                        AND T2.REVIEW_STATUS_CODE IN (1, 9, 10)
                    )
                );

    END LOOP;

    CLOSE FCOI_CURSOR;

    -- RESET DONE FLAG FOR OPA CURSOR
    SET DONE = FALSE;

    -- PROCESS OPA DISCLOSURES FOR EACH REMINDER DAY
    OPEN OPA_CURSOR;
    OPA_LOOP: LOOP
        FETCH OPA_CURSOR INTO LS_OPA_DAYS_TO_DUE_DATE;
        IF DONE THEN
            LEAVE OPA_LOOP;
        END IF;

        -- INSERT EXPIRING OPA DISCLOSURES FOR CURRENT DAYS_TO_DUE_DATE
        INSERT INTO TEMP_EXPIRING_DISCL_TO_NOTIFY (DISCLOSURE_ID, DISCLOSURE_NUMBER, PERSON_ID, DISCLOSURE_TYPE, EXPIRATION_DATE, DAYS_TO_DUE_DATE)
        SELECT 
            D.OPA_DISCLOSURE_ID,        
            D.OPA_DISCLOSURE_NUMBER,
            D.PERSON_ID,
            'OPA',
            D.EXPIRATION_DATE,
            LS_OPA_DAYS_TO_DUE_DATE
        FROM OPA_DISCLOSURE D
        WHERE D.OPA_DISCLOSURE_ID = (
            SELECT MAX(OPA_DISCLOSURE_ID)
            FROM OPA_DISCLOSURE D2
            WHERE D2.OPA_DISCLOSURE_NUMBER = D.OPA_DISCLOSURE_NUMBER
        )
        AND D.OPA_DISCLOSURE_NUMBER IN (
            SELECT DISTINCT OPA_DISCLOSURE_NUMBER
            FROM OPA_DISCLOSURE
            WHERE DISPOSITION_STATUS_CODE = '3'
              AND VERSION_STATUS = 'ACTIVE'
              AND DATE(EXPIRATION_DATE) = DATE_ADD(CURDATE(), INTERVAL LS_OPA_DAYS_TO_DUE_DATE DAY)
        )
        AND (DATE(D.EXPIRATION_DATE) = DATE_ADD(CURDATE(), INTERVAL LS_OPA_DAYS_TO_DUE_DATE DAY)
        OR D.REVIEW_STATUS_CODE IN (1, 5, 6));
    END LOOP;

    CLOSE OPA_CURSOR;

    SELECT * FROM TEMP_EXPIRING_DISCL_TO_NOTIFY;
    DROP TEMPORARY TABLE TEMP_EXPIRING_DISCL_TO_NOTIFY;
END
//
