CREATE TABLE PER_ENT_FORM_BUILDER_DETAILS (
  PER_ENT_FB_DETAILS_ID int NOT NULL AUTO_INCREMENT,
  PERSON_ENTITY_ID int NOT NULL,
  PERSON_ENTITY_NUMBER int NOT NULL,
  PERSON_ID varchar(40) NOT NULL,
  FORM_BUILDER_ID int NOT NULL,
  IS_PRIMARY_FORM varchar(1) NOT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATED_BY varchar(40) NOT NULL,
  PRIMARY KEY (PER_ENT_FB_DETAILS_ID)
);
