\. ./FIBI-COI-5.1.2/FC-1103-CA-Dashbaord/Procedures/GET_COI_AWARD_PROJECT_OVERVIEW.sql
\. ./FIBI-COI-5.1.2/FC-1103-CA-Dashbaord/Procedures/GET_PROJECT_OVERVIEW.sql
\. ./FIBI-COI-5.1.2/FC-1103-CA-Dashbaord/Functions/FN_CHK_HIERARCHY_HAS_DISCL.sql
\. ./FIBI-COI-5.1.2/FC-1103-CA-Dashbaord/Functions/FN_GET_OVAL_AWD_PRJT_DISCL_STATUS.sql
\. ./FIBI-COI-5.1.2/FC-1103-CA-Dashbaord/Functions/FN_GET_OVRAL_AWD_PRJT_DISCL_RVW_STATUS.sql
\. ./FIBI-COI-5.1.2/FC-1103-CA-Dashbaord/Functions/FN_SET_PROJECT_DISCLOSURE_REVIEW_STATUS.sql