
CREATE TABLE IF NOT EXISTS COI_MANAGEMENT_PLAN_TYPE (
  CMP_TYPE_CODE VARCHAR(3) PRIMARY KEY,
  DESCRIPTION VARCHAR(500),
  UPDATED_BY VARCHAR(60),
  UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_STATUS_TYPE (
  STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  BADGE_COLOR VARCHAR(45) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (STATUS_CODE)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_ACTION_TYPE (
  ACTION_TYPE_CODE VARCHAR(3) NOT NULL,
  MESSAGE VARCHAR(200) DEFAULT NULL,
  DESCRIPTION VARCHAR(500) DEFAULT NULL,
  STATUS_CODE varchar(3) DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATE_USER VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_TYPE_CODE),
  CONSTRAINT COI_MGMT_PLAN_ACTION_TYPE_FK1 
      FOREIGN KEY (STATUS_CODE) 
      REFERENCES COI_MGMT_PLAN_STATUS_TYPE (STATUS_CODE)
);

CREATE TABLE IF NOT EXISTS COI_MANAGEMENT_PLAN_ATTA_TYPE (
  ATTA_TYPE_CODE VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(500),
  UPDATED_BY VARCHAR(60),
  UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVE VARCHAR(1) DEFAULT 'Y',
  PRIMARY KEY (ATTA_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS SUB_AWARD_INSTITUTE (
  INSTITUTE_TYPE_CODE VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(500) DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(60) DEFAULT NULL,
  IS_ACTIVE VARCHAR(1) DEFAULT 'Y',
  PRIMARY KEY (INSTITUTE_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS coi_management_plan (
  CMP_ID int NOT NULL AUTO_INCREMENT,
  CMP_NUMBER int NOT NULL,
  CMP_TYPE_CODE varchar(3) NOT NULL,
  VERSION_NUMBER int NOT NULL,
  VERSION_STATUS varchar(50) NOT NULL,
  STATUS_CODE varchar(3) DEFAULT NULL,
  PERSON_ID varchar(60) DEFAULT NULL,
  ROLODEX_ID int DEFAULT NULL,
  ACADEMIC_DEPARTMENT_NUMBER varchar(50) DEFAULT NULL,
  LAB_CENTER_NUMBER varchar(50) DEFAULT NULL,
  SUB_AWARD_INSTITUTE_CODE varchar(20) DEFAULT NULL,
  APPROVAL_DATE datetime DEFAULT NULL,
  EXPIRATION_DATE datetime DEFAULT NULL,
  CREATED_BY varchar(60) DEFAULT NULL,
  CREATED_TIMESTAMP timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY varchar(60) DEFAULT NULL,
  UPDATE_TIMESTAMP timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (CMP_ID),
  KEY COI_MANAGEMENT_PLAN_FK1 (CMP_TYPE_CODE),
  KEY COI_MANAGEMENT_PLAN_FK2 (ACADEMIC_DEPARTMENT_NUMBER),
  KEY COI_MANAGEMENT_PLAN_FK3 (LAB_CENTER_NUMBER),
  KEY COI_MANAGEMENT_PLAN_FK4 (PERSON_ID),
  KEY COI_MANAGEMENT_PLAN_FK5 (ROLODEX_ID),
  KEY COI_MANAGEMENT_PLAN_FK6_idx (SUB_AWARD_INSTITUTE_CODE),
  KEY COI_MANAGEMENT_PLAN_FK7 (STATUS_CODE),
  CONSTRAINT COI_MANAGEMENT_PLAN_FK1 FOREIGN KEY (CMP_TYPE_CODE) REFERENCES coi_management_plan_type (CMP_TYPE_CODE),
  CONSTRAINT COI_MANAGEMENT_PLAN_FK2 FOREIGN KEY (ACADEMIC_DEPARTMENT_NUMBER) REFERENCES unit (UNIT_NUMBER),
  CONSTRAINT COI_MANAGEMENT_PLAN_FK3 FOREIGN KEY (LAB_CENTER_NUMBER) REFERENCES unit (UNIT_NUMBER),
  CONSTRAINT COI_MANAGEMENT_PLAN_FK4 FOREIGN KEY (PERSON_ID) REFERENCES person (PERSON_ID),
  CONSTRAINT COI_MANAGEMENT_PLAN_FK5 FOREIGN KEY (ROLODEX_ID) REFERENCES rolodex (ROLODEX_ID),
  CONSTRAINT COI_MANAGEMENT_PLAN_FK6 FOREIGN KEY (SUB_AWARD_INSTITUTE_CODE) REFERENCES organization (ORGANIZATION_ID),
  CONSTRAINT COI_MANAGEMENT_PLAN_FK7 FOREIGN KEY (STATUS_CODE) REFERENCES coi_mgmt_plan_status_type (STATUS_CODE)
);

CREATE TABLE IF NOT EXISTS COI_MANAGEMENT_PLAN_SECTION (
  SECTION_ID INT AUTO_INCREMENT PRIMARY KEY,
  SECTION_NAME VARCHAR(500) NOT NULL,
  DESCRIPTION TEXT,
  UPDATED_BY VARCHAR(60),
  UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COI_MANAGEMENT_PLAN_TEMPLATE (
  TEMPLATE_ID INT AUTO_INCREMENT PRIMARY KEY,
  TEMPLATE_NAME VARCHAR(500) NOT NULL,
  DESCRIPTION TEXT,
  UPDATED_BY VARCHAR(60),
  UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_ENTITY_REL (
  COI_MGMT_PLAN_ENT_REL_ID INT AUTO_INCREMENT PRIMARY KEY,
  CMP_ID INT NOT NULL,
  PERSON_ENTITY_ID INT,
  PERSON_ENTITY_NUMBER INT,
  ENTITY_ID INT,
  ENTITY_NUMBER INT,
  UPDATED_BY VARCHAR(60),
  UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT COI_MGMT_PLAN_ENTITY_REL_FK1
  FOREIGN KEY (CMP_ID) REFERENCES COI_MANAGEMENT_PLAN(CMP_ID),
  CONSTRAINT COI_MGMT_PLAN_ENTITY_REL_FK2
  FOREIGN KEY (PERSON_ENTITY_ID) REFERENCES PERSON_ENTITY(PERSON_ENTITY_ID),
  CONSTRAINT COI_MGMT_PLAN_ENTITY_REL_FK3
  FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ENTITY_ID)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_PROJ_REL (
  COI_MGMT_PLAN_PROJ_REL_ID INT AUTO_INCREMENT PRIMARY KEY,
  CMP_ID INT NOT NULL,
  MODULE_CODE INT NOT NULL,
  MODULE_ITEM_KEY VARCHAR(20) NOT NULL,
  UPDATED_BY VARCHAR(60),
  UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT COI_MGMT_PLAN_PROJ_REL_FK1
  FOREIGN KEY (CMP_ID) REFERENCES COI_MANAGEMENT_PLAN(CMP_ID)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_SECTION_REL (
  CMP_SECTION_REL_ID INT AUTO_INCREMENT PRIMARY KEY,
  CMP_ID INT NOT NULL,
  SECTION_NAME VARCHAR(500) NOT NULL,
  DESCRIPTION VARCHAR(500),
  SORT_ORDER INT,
  CREATED_BY VARCHAR(60),
  CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(60),
  UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT COI_MGMT_PLAN_SECTION_REL_FK1
  FOREIGN KEY (CMP_ID) REFERENCES COI_MANAGEMENT_PLAN(CMP_ID)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_SECTION_COMP (
  SEC_COMP_ID INT AUTO_INCREMENT PRIMARY KEY,
  CMP_SECTION_REL_ID INT,
  DESCRIPTION TEXT,
  SORT_ORDER INT,
  CREATED_BY VARCHAR(60),
  CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(60),
  UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT COI_MGMT_PLAN_SECTION_COMP_FK1
  FOREIGN KEY (CMP_SECTION_REL_ID) REFERENCES COI_MGMT_PLAN_SECTION_REL (CMP_SECTION_REL_ID)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_TMPL_SEC_MAPPING (
  TMPL_SEC_MAPPING_ID INT AUTO_INCREMENT PRIMARY KEY,
  TEMPLATE_ID INT NOT NULL,
  SECTION_ID INT NOT NULL,
  NAME VARCHAR(500) DEFAULT NULL,
  SORT_ORDER INT NOT NULL,
  UPDATED_BY VARCHAR(60),
  UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT COI_MGMT_PLAN_TMPL_SEC_MAPPING_FK1
  FOREIGN KEY (TEMPLATE_ID) REFERENCES COI_MANAGEMENT_PLAN_TEMPLATE(TEMPLATE_ID),
  CONSTRAINT COI_MGMT_PLAN_TMPL_SEC_MAPPING_FK2
  FOREIGN KEY (SECTION_ID) REFERENCES COI_MANAGEMENT_PLAN_SECTION(SECTION_ID)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_ACTION_LOG (
  CMP_ACTION_LOG_ID INT NOT NULL AUTO_INCREMENT,
  CMP_ID INT NOT NULL,
  CMP_NUMBER INT DEFAULT NULL,
  ACTION_TYPE_CODE VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  COMMENTS VARCHAR(4000) DEFAULT NULL,
  UPDATED_BY VARCHAR(60),
  UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (CMP_ACTION_LOG_ID),
  KEY COI_MGMT_PLAN_ACTION_LOG_FK1 (ACTION_TYPE_CODE),
  KEY COI_MGMT_PLAN_ACTION_LOG_FK2 (CMP_ID),
  CONSTRAINT COI_MGMT_PLAN_ACTION_LOG_FK1 FOREIGN KEY (ACTION_TYPE_CODE) REFERENCES COI_MGMT_PLAN_ACTION_TYPE (ACTION_TYPE_CODE),
  CONSTRAINT COI_MGMT_PLAN_ACTION_LOG_FK2 FOREIGN KEY (CMP_ID) REFERENCES COI_MANAGEMENT_PLAN (CMP_ID)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_SEC_REL_HIST (
  SECTION_REL_HISTORY_ID INT NOT NULL AUTO_INCREMENT,
  CMP_SECTION_REL_ID INT NOT NULL,
  CMP_ID INT NOT NULL,
  ACTION_TYPE VARCHAR(3) NOT NULL,
  OLD_DATA JSON,
  NEW_DATA JSON,
  UPDATED_BY VARCHAR(60),
  UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SECTION_REL_HISTORY_ID),
  KEY CMP_SEC_REL_HIST_IDX1 (CMP_SECTION_REL_ID),
  KEY CMP_SEC_REL_HIST_IDX2 (CMP_ID),
  CONSTRAINT CMP_SEC_REL_HIST_FK1 FOREIGN KEY (CMP_SECTION_REL_ID) REFERENCES COI_MGMT_PLAN_SECTION_REL (CMP_SECTION_REL_ID),
  CONSTRAINT CMP_SEC_REL_HIST_FK2 FOREIGN KEY (CMP_ID) REFERENCES COI_MANAGEMENT_PLAN (CMP_ID)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_SEC_COMP_HIST (
  SECTION_COMP_HISTORY_ID INT NOT NULL AUTO_INCREMENT,
  SEC_COMP_ID INT NOT NULL,
  CMP_SECTION_REL_ID INT NOT NULL,
  ACTION_TYPE VARCHAR(3) NOT NULL,
  OLD_DATA JSON,
  NEW_DATA JSON,
  UPDATED_BY VARCHAR(60),
  UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SECTION_COMP_HISTORY_ID),
  KEY CMP_SEC_COMP_HIST_IDX1 (SEC_COMP_ID),
  KEY CMP_SEC_COMP_HIST_IDX2 (CMP_SECTION_REL_ID),
  CONSTRAINT CMP_SEC_COMP_HIST_FK1 FOREIGN KEY (SEC_COMP_ID) REFERENCES COI_MGMT_PLAN_SECTION_COMP (SEC_COMP_ID),
  CONSTRAINT CMP_SEC_COMP_HIST_FK2 FOREIGN KEY (CMP_SECTION_REL_ID) REFERENCES COI_MGMT_PLAN_SECTION_REL (CMP_SECTION_REL_ID)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_AVAILABLE_ACTION (
  AVAILABLE_ACTION_ID INT NOT NULL AUTO_INCREMENT,
  STATUS_CODE varchar(3) NOT NULL,
  ACTION_TYPE_CODE varchar(3) DEFAULT NULL,
  UPDATED_BY VARCHAR(60) DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  SORT_ORDER INT DEFAULT NULL,
  PRIMARY KEY (AVAILABLE_ACTION_ID),
  KEY COI_MGMT_PLAN_AVAILABLE_ACTION_FK1 (STATUS_CODE),
  KEY COI_MGMT_PLAN_AVAILABLE_ACTION_FK2 (ACTION_TYPE_CODE),
  CONSTRAINT COI_MGMT_PLAN_AVAILABLE_ACTION_FK1
      FOREIGN KEY (STATUS_CODE) 
      REFERENCES COI_MGMT_PLAN_STATUS_TYPE (STATUS_CODE),
  CONSTRAINT COI_MGMT_PLAN_AVAILABLE_ACTION_FK2
      FOREIGN KEY (ACTION_TYPE_CODE) 
      REFERENCES COI_MGMT_PLAN_ACTION_TYPE (ACTION_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS COI_MANAGEMENT_PLAN_ATTACHMENT (
  ATTACHMENT_ID INT NOT NULL AUTO_INCREMENT,
  ATTACHMENT_NUMBER INT,
  VERSION_NUMBER INT,
  CMP_ID INT NOT NULL,
  ATTACHMENT_TYPE_CODE VARCHAR(3),
  DESCRIPTION VARCHAR(1000),
  FILE_NAME VARCHAR(255),
  MIME_TYPE VARCHAR(255),
  FILE_DATA_ID VARCHAR(100),
  CREATED_BY VARCHAR(60),
  CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(60),
  UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ATTACHMENT_ID),
  KEY COI_MANAGEMENT_PLAN_ATTACHMENT_IDX1 (CMP_ID),
  KEY COI_MANAGEMENT_PLAN_ATTACHMENT_IDX2 (ATTACHMENT_TYPE_CODE),
  CONSTRAINT COI_MANAGEMENT_PLAN_ATTACHMENT_FK1 FOREIGN KEY (CMP_ID) REFERENCES COI_MANAGEMENT_PLAN (CMP_ID),
  CONSTRAINT COI_MANAGEMENT_PLAN_ATTACHMENT_FK2 FOREIGN KEY (ATTACHMENT_TYPE_CODE) REFERENCES COI_MANAGEMENT_PLAN_ATTA_TYPE (ATTA_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS COI_MANAGEMENT_PLAN_FILE_DATA (
  FILE_DATA_ID varchar(100) NOT NULL,
  FILE_PATH varchar(255) DEFAULT NULL,
  ORIGINAL_FILE_NAME varchar(500) DEFAULT NULL,
  FILE_NAME varchar(100) DEFAULT NULL,
  IS_ARCHIVED varchar(1) DEFAULT NULL,
  FILE longblob,
  UPDATE_TIMESTAMP timestamp NULL DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (FILE_DATA_ID)
);

CREATE TABLE IF NOT EXISTS COI_MANAGEMENT_PLAN_COUNTER (
  COUNTER_NAME varchar(100) NOT NULL,
  COUNTER_VALUE int DEFAULT NULL,
  PRIMARY KEY (COUNTER_NAME)
);

CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_SEC_COMP_LOCK (
    SEC_COMP_ID        INT NOT NULL,
    LOCKED_BY          VARCHAR(50) NOT NULL,
    LOCKED_AT          TIMESTAMP NOT NULL,
    PRIMARY KEY (SEC_COMP_ID)
);

CREATE TABLE IF NOT EXISTS COI_CMP_TYPE_PROJECT_TYPE_REL (
    CMP_PROJ_TYPE_REL_ID  VARCHAR(3) NOT NULL,
    CMP_TYPE_CODE VARCHAR(3) NOT NULL,
    COI_PROJECT_TYPE_CODE  VARCHAR(3) NOT NULL,
    IS_INCLUDED VARCHAR(1) DEFAULT 'Y',
    UPDATED_BY VARCHAR(60),
    UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CMP_PROJ_TYPE_REL_ID),
    CONSTRAINT CMP_TYPE_PROJECT_TYPE_FK1
        FOREIGN KEY (CMP_TYPE_CODE)
        REFERENCES COI_MANAGEMENT_PLAN_TYPE (CMP_TYPE_CODE),
    CONSTRAINT CMP_TYPE_PROJECT_TYPE_FK2
        FOREIGN KEY (COI_PROJECT_TYPE_CODE)
        REFERENCES COI_PROJECT_TYPE (COI_PROJECT_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS COI_CMP_REVIEWER_STATUS_TYPE (
  REVIEW_STATUS_CODE VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(200) DEFAULT NULL,
  IS_ACTIVE VARCHAR(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (REVIEW_STATUS_CODE)
);

CREATE TABLE IF NOT EXISTS COI_CMP_REVIEW_LOCATION_TYPE (
  LOCATION_TYPE_CODE VARCHAR(3) NOT NULL,
  DESCRIPTION VARCHAR(200) DEFAULT NULL,
  IS_ACTIVE VARCHAR(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (LOCATION_TYPE_CODE)
);

CREATE TABLE IF NOT EXISTS COI_CMP_REVIEW (
  CMP_REVIEW_ID INT NOT NULL AUTO_INCREMENT,
  CMP_ID INT NOT NULL,
  ASSIGNEE_PERSON_ID VARCHAR(40) DEFAULT NULL,
  REVIEW_STATUS_TYPE_CODE VARCHAR(3) DEFAULT NULL,
  LOCATION_TYPE_CODE VARCHAR(3) DEFAULT NULL,
  DESCRIPTION VARCHAR(2000) DEFAULT NULL,
  START_DATE DATE DEFAULT NULL,
  END_DATE DATE DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATED_BY VARCHAR(60) DEFAULT NULL,
  CREATE_TIMESTAMP DATETIME DEFAULT NULL,
  CREATED_BY VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (CMP_REVIEW_ID),
  KEY CMP_REVIEW_FK1 (ASSIGNEE_PERSON_ID),
  KEY CMP_REVIEW_FK2 (CMP_ID),
  KEY CMP_REVIEW_FK3 (REVIEW_STATUS_TYPE_CODE),
  KEY CMP_REVIEW_FK4 (LOCATION_TYPE_CODE),
  CONSTRAINT CMP_REVIEW_FK1 FOREIGN KEY (ASSIGNEE_PERSON_ID)
    REFERENCES PERSON (PERSON_ID),
  CONSTRAINT CMP_REVIEW_FK2 FOREIGN KEY (CMP_ID)
    REFERENCES COI_MANAGEMENT_PLAN (CMP_ID),
  CONSTRAINT CMP_REVIEW_FK3 FOREIGN KEY (REVIEW_STATUS_TYPE_CODE)
    REFERENCES COI_CMP_REVIEWER_STATUS_TYPE (REVIEW_STATUS_CODE),
  CONSTRAINT CMP_REVIEW_FK4 FOREIGN KEY (LOCATION_TYPE_CODE)
    REFERENCES COI_CMP_REVIEW_LOCATION_TYPE (LOCATION_TYPE_CODE)
);


CREATE TABLE IF NOT EXISTS COI_MGMT_PLAN_RECIPIENT (
  CMP_RECIPIENT_ID INT NOT NULL AUTO_INCREMENT,
  CMP_ID INT NOT NULL,
  SIGN_ORDER INT NOT NULL,
  SIGNATURE_BLOCK VARCHAR(500) NOT NULL,
  PERSON_ID VARCHAR(60) DEFAULT NULL,
  DESIGNATION VARCHAR(500) DEFAULT NULL,
  ATTESTATION_STATEMENT VARCHAR(4000) DEFAULT NULL,
  UPDATED_BY VARCHAR(60),
  UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CREATED_BY VARCHAR(60),
  CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CMP_RECIPIENT_ID),
  KEY CMP_RECIPIENT_FK1 (CMP_ID),
  KEY CMP_RECIPIENT_FK2 (PERSON_ID),
  CONSTRAINT CMP_RECIPIENT_FK1 
    FOREIGN KEY (CMP_ID) REFERENCES COI_MANAGEMENT_PLAN (CMP_ID),
  CONSTRAINT CMP_RECIPIENT_FK2 
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID)
);

CREATE TABLE IF NOT EXISTS coi_cmp_review_reviewer_status_type (
  REVIEW_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (REVIEW_STATUS_CODE)
);
