INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-entity-translated-name', 'Entity Sub-Award Organization Details Translated Name', '2612', 'GE2603', 'admin', now());

DELETE FROM `NOTIFICATION_RECIPIENT` WHERE `NOTIFICATION_TYPE_ID` IN (8037, 8038, 8018, 8034) AND `ROLE_TYPE_CODE` = 57 AND `RECIPIENT_TYPE` = 'TO';
UPDATE NOTIFICATION_TYPE SET `SENT_TO_INITIATOR` = 'N' WHERE (`NOTIFICATION_TYPE_ID` = '8018');
UPDATE NOTIFICATION_TYPE SET `SENT_TO_INITIATOR` = 'N' WHERE (`NOTIFICATION_TYPE_ID` = '8034');

