set sql_safe_updates = 0;

ALTER TABLE `COI_TRAVEL_DISCLOSURE_TRAVELER`
DROP FOREIGN KEY `COI_TRAVEL_DISCLOSURE_TRAVELER_FK2`;
ALTER TABLE `COI_TRAVEL_DISCLOSURE_TRAVELER`
CHANGE COLUMN `TRAVELER_TYPE_CODE` `VALID_PERS_ENTITY_REL_TYP_CODE` INT NULL DEFAULT NULL ,
CHANGE COLUMN `UPDATE_USER` `UPDATED_BY` VARCHAR(40) NULL DEFAULT NULL ,
ADD INDEX `COI_TRAVEL_DISCLOSURE_TRAVELER_FK2_idx` (`VALID_PERS_ENTITY_REL_TYP_CODE` ASC) VISIBLE,
DROP INDEX `COI_TRAVEL_DISCLOSURE_TRAVELER_FK2_idx` ;
ALTER TABLE `COI_TRAVEL_DISCLOSURE_TRAVELER`
ADD CONSTRAINT `COI_TRAVEL_DISCLOSURE_TRAVELER_FK2`
  FOREIGN KEY (`VALID_PERS_ENTITY_REL_TYP_CODE`)
  REFERENCES `VALID_PERSON_ENTITY_REL_TYPE` (`VALID_PERS_ENTITY_REL_TYP_CODE`);


ALTER TABLE `coi_travel_disclosure`
DROP FOREIGN KEY `COI_TRAVEL_DISCLOSURE_FK5`;
ALTER TABLE `coi_travel_disclosure`
DROP INDEX `COI_TRAVEL_DISCLOSURE_FK5_idx` ;


ALTER TABLE `coi_travel_disclosure`
DROP FOREIGN KEY `COI_TRAVEL_DISCLOSURE_FK6`;
ALTER TABLE `coi_travel_disclosure`
DROP INDEX `COI_TRAVEL_DISCLOSURE_FK6_idx` ;


ALTER TABLE `coi_travel_disclosure`
DROP FOREIGN KEY `COI_TRAVEL_DISCLOSURE_FK4`;
ALTER TABLE `coi_travel_disclosure`
DROP INDEX `COI_TRAVEL_DISCLOSURE_FK4_idx` ;

ALTER TABLE `coi_travel_disclosure`
DROP COLUMN `RISK_CATEGORY_CODE`,
DROP COLUMN `TRAVELER_TYPE_CODE`,
DROP COLUMN `DISPOSITION_STATUS_CODE`,
DROP COLUMN `TRAVEL_DISCLOSURE_STATUS_CODE`,
DROP COLUMN `DESCRIPTION`,
DROP COLUMN `IS_INTERNATIONAL_TRAVEL`,
DROP COLUMN `STATE`,
DROP COLUMN `CREATE_USER`,
DROP COLUMN `UPDATE_USER`,
DROP COLUMN `ACKNOWLEDGE_AT`,
DROP COLUMN `ACKNOWLEDGE_BY`,
DROP COLUMN `RELATIONSHIP_TO_YOUR_RESEARCH`,
DROP COLUMN `DESTINATION_COUNTRY`,
DROP COLUMN `DESTINATION_CITY`,
DROP COLUMN `NO_OF_DAYS`,
DROP COLUMN `TRAVEL_AMOUNT`,
DROP COLUMN `IS_SPONSORED_TRAVEL`,
ADD COLUMN `RELATIONSHIP_TO_PHS_DOE` VARCHAR(500) NULL,
ADD COLUMN `FUNDING_TYPE_CODE` VARCHAR(3) NULL,
ADD COLUMN `REIMBURSED_COST` DECIMAL(12,2) NULL,
ADD COLUMN `UPDATED_BY` VARCHAR(40) NULL,
ADD COLUMN `CREATED_BY` VARCHAR(40) NULL,
ADD COLUMN `CERTIFICATION_TEXT` VARCHAR(1000) NULL,
ADD COLUMN `PERSON_ENTITY_NUMBER` INT NULL,
CHANGE COLUMN `EXPIRATION_DATE` `EXPIRATION_DATE` DATE NULL,
CHANGE COLUMN `REVIEW_STATUS_CODE` `REVIEW_STATUS_CODE` VARCHAR(3) NULL,
CHANGE COLUMN `UPDATE_TIMESTAMP` `UPDATE_TIMESTAMP` DATETIME NULL,
CHANGE COLUMN `CREATE_TIMESTAMP` `CREATE_TIMESTAMP` DATETIME NULL,
CHANGE COLUMN `TRAVEL_STATUS_CODE` `TRAVEL_STATUS_CODE` VARCHAR(8) NULL DEFAULT NULL ,
CHANGE COLUMN `TRAVEL_START_DATE` `TRAVEL_START_DATE` DATE NULL ,
CHANGE COLUMN `TRAVEL_END_DATE` `TRAVEL_END_DATE` DATE NULL ,
CHANGE COLUMN `SUBMISSION_DATE` `SUBMISSION_DATE` DATETIME NULL ,
CHANGE COLUMN `ADMIN_GROUP_ID` `ADMIN_GROUP_ID` INT NULL ,
CHANGE COLUMN `ADMIN_PERSON_ID` `ADMIN_PERSON_ID` VARCHAR(40) NULL ,
CHANGE COLUMN `CERTIFIED_BY` `CERTIFIED_BY` VARCHAR(40) NULL ,
CHANGE COLUMN `CERTIFIED_AT` `CERTIFIED_AT` DATETIME NULL ,
CHANGE COLUMN `DOCUMENT_STATUS_CODE` `DOCUMENT_STATUS_CODE` VARCHAR(3) NULL ,
ADD INDEX `COI_TRAVEL_DISCLOSURE_FK5_idx` (`FUNDING_TYPE_CODE` ASC) VISIBLE,
ADD INDEX `COI_TRAVEL_DISCLOSURE_FK6_idx` (`DOCUMENT_STATUS_CODE` ASC) VISIBLE,
ADD INDEX `COI_TRAVEL_DISCLOSURE_FK7_idx` (`REVIEW_STATUS_CODE` ASC) VISIBLE;

ALTER TABLE `coi_travel_document_status`
RENAME TO  `coi_travel_document_status_type` ;


ALTER TABLE `coi_travel_disclosure`
ADD CONSTRAINT `COI_TRAVEL_DISCLOSURE_FK4`
  FOREIGN KEY (`TRAVEL_STATUS_CODE`)
  REFERENCES `COI_TRAVEL_STATUS` (`TRAVEL_STATUS_CODE`);
 /*
ALTER TABLE `coi_travel_disclosure`
ADD CONSTRAINT `COI_TRAVEL_DISCLOSURE_FK5`
  FOREIGN KEY (`FUNDING_TYPE_CODE`)
  REFERENCES `coi_travel_funding_type` (`FUNDING_TYPE_CODE`)
  ON DELETE NO ACTION
  ON UPDATE NO action;
  */

CREATE INDEX `IDX_DOCUMENT_STATUS_CODE` ON `COI_TRAVEL_DOCUMENT_STATUS_TYPE` (`DOCUMENT_STATUS_CODE`);
ALTER TABLE `coi_travel_disclosure`
ADD CONSTRAINT `COI_TRAVEL_DISCLOSURE_FK6`
  FOREIGN KEY (`DOCUMENT_STATUS_CODE`)
  REFERENCES `COI_TRAVEL_DOCUMENT_STATUS_TYPE` (`DOCUMENT_STATUS_CODE`)
  ON DELETE NO ACTION
  ON UPDATE NO action;

CREATE INDEX `IDX_REVIEW_STATUS_CODE` ON `COI_TRAVEL_REVIEW_STATUS` (`REVIEW_STATUS_CODE`);
ALTER TABLE `coi_travel_disclosure`
ADD CONSTRAINT `COI_TRAVEL_DISCLOSURE_FK7`
  FOREIGN KEY (`REVIEW_STATUS_CODE`)
  REFERENCES `COI_TRAVEL_REVIEW_STATUS` (`REVIEW_STATUS_CODE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

Update COI_TRAVEL_DOCUMENT_STATUS_TYPE set DESCRIPTION = "Approved" where DOCUMENT_STATUS_CODE = 2;

Update COI_TRAVEL_DOCUMENT_STATUS_TYPE set DESCRIPTION = "Pending" where DOCUMENT_STATUS_CODE = 1;

ALTER TABLE `person_entity_relationship`
ADD COLUMN `IS_SYSTEM_CREATED` VARCHAR(1) NULL;

ALTER TABLE `coi_travel_destinations`
ADD COLUMN `TRAVEL_MEDIUM_DETAIL` VARCHAR(100) NULL;

set sql_safe_updates = 1;


