create or replace PROCEDURE FIBI_COI_GET_INST_PROPOSAL(
AV_PROPOSAL_NUMBER IN PROPOSAL.PROPOSAL_NUMBER%TYPE,
CUR_GENERIC        OUT SYS_REFCURSOR)
IS
LI_LINKED_DEV_PROPOSAL_IDS VARCHAR2(4000);
LS_AWARD_NUMBER VARCHAR2(4000);
LS_PCK_VALUE VARCHAR2(10);
BEGIN

	BEGIN
		SELECT 
		LISTAGG(P1.DEV_PROPOSAL_NUMBER, ',') WITHIN GROUP (ORDER BY P1.DEV_PROPOSAL_NUMBER)
		INTO LI_LINKED_DEV_PROPOSAL_IDS
		FROM PROPOSAL_ADMIN_DETAILS P1 WHERE P1.INST_PROPOSAL_ID IN (SELECT PROPOSAL_ID
		FROM PROPOSAL WHERE PROPOSAL_NUMBER = AV_PROPOSAL_NUMBER
		and PROPOSAL_SEQUENCE_STATUS = 'ACTIVE');


	EXCEPTION    
		WHEN OTHERS THEN
			LI_LINKED_DEV_PROPOSAL_IDS := NULL;
	END;


	BEGIN

		SELECT 
		LISTAGG(A.AWARD_NUMBER, ',') WITHIN GROUP (ORDER BY A.AWARD_NUMBER)
		INTO LS_AWARD_NUMBER
		FROM PROPOSAL P
		LEFT JOIN AWARD_FUNDING_PROPOSALS AFP ON AFP.PROPOSAL_ID = P.PROPOSAL_ID
		LEFT JOIN AWARD A ON A.AWARD_ID = AFP.AWARD_ID
		WHERE P.PROPOSAL_NUMBER = AV_PROPOSAL_NUMBER
		and P.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE';

	EXCEPTION    
		WHEN OTHERS THEN
			LS_AWARD_NUMBER := NULL;
	END;


	BEGIN 

		SELECT DISTINCT NVL(t2.VALUE,'N/A') INTO LS_PCK_VALUE
		from PROPOSAL t1
		inner join PROPOSAL_CUSTOM_DATA t2 on t1.PROPOSAL_ID = t2.PROPOSAL_ID
		WHERE t1.PROPOSAL_NUMBER = AV_PROPOSAL_NUMBER
		AND t2.custom_attribute_id = 31
		AND t1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE'; 

	EXCEPTION    
		WHEN OTHERS THEN
			LS_PCK_VALUE := 'N/A';
	END;	




    OPEN CUR_GENERIC FOR
	SELECT 
    P.PROPOSAL_ID AS PROJECT_ID,
    P.PROPOSAL_NUMBER AS PROJECT_NUMBER,
    P.SEQUENCE_NUMBER AS VERSION_NUMBER,
    LS_AWARD_NUMBER AS LINKED_AWARD_PROJECT_NUMBER,
    P.SPONSOR_PROPOSAL_NUMBER AS SPONSOR_GRANT_NUMBER,
    P.LEAD_UNIT_NUMBER AS LEAD_UNIT_NUMBER,
    U.UNIT_NAME AS LEAD_UNIT_NAME,
    P.REQUESTED_START_DATE_INITIAL AS PROJECT_START_DATE,
    P.REQUESTED_END_DATE_INITIAL AS PROJECT_END_DATE,
    P.PROPOSAL_TYPE_CODE AS PROJECT_TYPE_CODE,
    PT.DESCRIPTION AS PROJECT_TYPE,
    P.TITLE AS TITLE,
    P.STATUS_CODE AS PROJECT_STATUS_CODE,
    PS.DESCRIPTION AS PROJECT_STATUS,
    P.SPONSOR_CODE AS SPONSOR_CODE,
    S1.SPONSOR_NAME AS SPONSOR_NAME,
    P.PRIME_SPONSOR_CODE AS PRIME_SPONSOR_CODE,
    S2.SPONSOR_NAME AS PRIME_SPONSOR_NAME,
    NULL AS DOCUMENT_URL,
    P.UPDATE_TIMESTAMP AS SRC_SYS_UPDATE_TIMESTAMP,
    P.UPDATE_USER AS SRC_SYS_UPDATE_USER_NAME,
    'PCK_FLAG' AS ATTRIBUTE_1_LABEL,
    LS_PCK_VALUE AS ATTRIBUTE_1_VALUE,
    NULL AS ATTRIBUTE_2_LABEL,
    NULL AS ATTRIBUTE_2_VALUE,
    NULL AS ATTRIBUTE_3_LABEL,
    NULL AS ATTRIBUTE_3_VALUE,
    NULL AS ATTRIBUTE_4_LABEL,
    NULL AS ATTRIBUTE_4_VALUE,
    NULL AS ATTRIBUTE_5_LABEL,
    NULL AS ATTRIBUTE_5_VALUE,
	LI_LINKED_DEV_PROPOSAL_IDS AS LINKED_DEV_PROPOSAL_IDS         
	FROM PROPOSAL P
	INNER JOIN UNIT U ON U.UNIT_NUMBER = P.LEAD_UNIT_NUMBER
	LEFT JOIN PROPOSAL_TYPE PT ON PT.PROPOSAL_TYPE_CODE = P.PROPOSAL_TYPE_CODE
	INNER JOIN PROPOSAL_STATUS PS ON PS.PROPOSAL_STATUS_CODE = P.STATUS_CODE
	INNER JOIN SPONSOR S1 ON S1.SPONSOR_CODE = P.SPONSOR_CODE
	LEFT JOIN SPONSOR S2 ON S2.SPONSOR_CODE = P.PRIME_SPONSOR_CODE
	WHERE P.PROPOSAL_NUMBER = AV_PROPOSAL_NUMBER
	and PROPOSAL_SEQUENCE_STATUS = 'ACTIVE';

END;
