INSERT INTO dyn_section_config (SECTION_CODE, MODULE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('COI806', 'COI8', 'Disclosure certification', 'Y', now(), 'admin');
INSERT INTO dyn_subsection_config (SUB_SECTION_CODE, SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('812', 'COI806', 'Disclosure Certification', 'Y', now(), 'admin');

INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-eng-details-info-text', 'Engagement Details Info', '532', 'SFI532', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-eng-rel-details-info-text', 'Engagement Relationship Details Info', '532', 'SFI532', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-eng-related-disc-info-text', 'Engagement related Disclosure  Info', '532', 'SFI532', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-eng-history-info-text', 'Engagement History Info', '532', 'SFI532', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-user-eng-info-text', 'User Engagement', '531', 'SFI531', 'admin', now());

INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, INSTRUCTION, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-disc-cert-info-text', 'Disclosure Certification info', '812', 'COI806', 'University policy requires that university officers, faculty, and staff and others acting on its behalf avoid ethical, legal, financial, and other conflicts of interest and ensure that their activities and interests do not conflict with their obligations to the University. Disclosure of financial interests enables the University to determine if a financial interest creates a conflict of interest or the appearance of a conflict of interest. The existence of a conflict or the appearance of one does not imply wrongdoing and does not necessarily mean that a researcher may not retain his or her financial interest and undertake the affected research. Often the University can work with the researcher to manage a conflict or the appearance of a conflict so that the research can continue in a way that minimizes the possibility of bias and preserves the objectivity of the to disclose and maintain your Engagements; identify potential areas of concern related to your proposals and awards; and, disclose reimbursed travel (for NIH compliance).', 'admin', now());
INSERT INTO dyn_element_config (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, INSTRUCTION, UPDATE_USER, UPDATE_TIMESTAMP) VALUES ('coi-discl-cert-cnfrm-text', 'Disclosure Certification Confirmation text', '812', 'COI806', 'I agree to abide by the University COI policy guidelines and certify that the information provided for the Financial conflict of interest, including, responses to screening questions, list of my pertinent Engagements and possible relationship to my sponsored activity is an accurate and current statement of my reportable outside interests and activities.', 'admin', now());
