
INSERT INTO PARAMETER (PARAMETER_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('ENABLE_SECTIONWISE_CUSTOM_DATA_IN_GLOBAL_ENTITY', '2633', 'To add custom data into these sub sections.', NOW(), 'willsmith');

INSERT INTO DYN_SUBSECTION_CONFIG (SUB_SECTION_CODE, SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('2633', 'GE2601', 'Additional Information', 'Y', NOW(), 'willsmith');

INSERT INTO DYN_ELEMENT_CONFIG (UI_REFERENCE_ID, DESCRIPTION, SUB_SECTION_CODE, SECTION_CODE, HELP, UPDATE_USER, UPDATE_TIMESTAMP) 
VALUES ('coi-overview-add-info-2633', 'Entity additional information', '2633', 'GE2601', 'Entity additional information', 'admin', NOW());
