-- Analyze table to refresh stats
ANALYZE TABLE OPA_PERSON;

-- Add PERSONNEL_SUBAREA if not exists
SET @SQL := IF(
    (
        SELECT COUNT(*)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'OPA_PERSON'
          AND COLUMN_NAME = 'PERSONNEL_SUBAREA'
    ) = 0,
    'ALTER TABLE OPA_PERSON ADD COLUMN `PERSONNEL_SUBAREA` VARCHAR(50) NULL;',
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

-- Add PERSONNEL_SUBAREA_CODE if not exists
SET @SQL := IF(
    (
        SELECT COUNT(*)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'OPA_PERSON'
          AND COLUMN_NAME = 'PERSONNEL_SUBAREA_CODE'
    ) = 0,
    'ALTER TABLE OPA_PERSON ADD COLUMN `PERSONNEL_SUBAREA_CODE` VARCHAR(10) NULL;',
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

-- Add IS_6MO_APPT if not exists
SET @SQL := IF(
    (
        SELECT COUNT(*)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'OPA_PERSON'
          AND COLUMN_NAME = 'IS_6MO_APPT'
    ) = 0,
    'ALTER TABLE OPA_PERSON ADD COLUMN `IS_6MO_APPT` VARCHAR(1) NULL;',
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

-- Analyze table
ANALYZE TABLE OPA_DISCL_PERSON_SNAP;

-- Add PERSONNEL_SUBAREA_CODE if not exists
SET @SQL := IF(
    (
        SELECT COUNT(*)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'OPA_DISCL_PERSON_SNAP'
          AND COLUMN_NAME = 'PERSONNEL_SUBAREA_CODE'
    ) = 0,
    'ALTER TABLE OPA_DISCL_PERSON_SNAP ADD COLUMN `PERSONNEL_SUBAREA_CODE` VARCHAR(10) NULL AFTER HR_DEPARTMENT_NAME;',
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;

-- Add PERSONNEL_SUBAREA if not exists
SET @SQL := IF(
    (
        SELECT COUNT(*)
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'OPA_DISCL_PERSON_SNAP'
          AND COLUMN_NAME = 'PERSONNEL_SUBAREA'
    ) = 0,
    'ALTER TABLE OPA_DISCL_PERSON_SNAP ADD COLUMN `PERSONNEL_SUBAREA` VARCHAR(50) NULL AFTER PERSONNEL_SUBAREA_CODE;',
    'DO 1'
);
PREPARE STMT FROM @SQL;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;
