INSERT INTO `message` (`MESSAGE_TYPE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('161', 'Disclosure revision/withdrawal required', now(), 'quickstart');
INSERT INTO `notification_type` (`NOTIFICATION_TYPE_ID`, `MODULE_CODE`, `SUB_MODULE_CODE`, `DESCRIPTION`, `SUBJECT`, `MESSAGE`, `PROMPT_USER`, `IS_ACTIVE`, `CREATE_USER`, `CREATE_TIMESTAMP`, `UPDATE_USER`, `UPDATE_TIMESTAMP`, `IS_SYSTEM_SPECIFIC`) VALUES ('8041', '8', '0', 'Revise or Withdraw Disclosure to Reflect New Engagement', 'Action Required: Revise or Withdraw Your Disclosure to Reflect New Engagement', '<p>Dear {COI_DISCLOSURE#REPORTER_NAME},</p><p>A new engagement :<strong> {COI_DISCL_OTHER#ENGAGEMENT_NAME} </strong> has been created in the system, and a financial relationship has been marked. Please either revise or withdraw your initial disclosure to reflect this change.</p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p><span style="color:hsl(0,0%,0%);">Note: This is a system-generated email. Please do not reply to this email.</span></p>', 'N', 'Y', 'quickstart', now(), 'willsmith', now(), 'N');
INSERT INTO `module_action_type` (`MODULE_ACTION_TYPE_ID`, `ACTION_TYPE`, `MODULE_CODE`, `SUB_MODULE_CODE`, `IS_ACTIVE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES (41, 'FCOI_REVISE_ON_ENG_CREATE', '8', '0', 'Y', 'Disclosure Revise On Engagement Creation', now(), 'quickstart');
INSERT INTO MQ_ROUTER_ACTION_CONFIGURATION(ACTION_TYPE, IS_ACTIVE, MODULE_CODE, QUEUE_NAME, SUB_MODULE_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES('FCOI_REVISE_ON_ENG_CREATE', 'Y', 8, 'Q_NOTIFICATION', 0, now(), 'quickstart');
INSERT INTO notify_action_type_map(NOTIFICATION_TYPE_ID,MODULE_ACTION_TYPE_ID,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES(8041,41,now(),'quickstart');
INSERT INTO notify_placeholder_columns(NOTIFY_PLACEHOLDER_COLUMN_ID,NOTIFY_PLACEHOLDER_HEADER_ID,QUERY_COLUMN_NAME,LABEL_NAME,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES(67,2,"ENGAGEMENT_NAME","Engagement Name",now(),"Will Smith");

