CREATE TABLE FB_QUEST_ANSWER_HEADER (
  QUESTIONNAIRE_ANS_HEADER_ID INT NOT NULL AUTO_INCREMENT,
  QUESTIONNAIRE_ID INT DEFAULT NULL,
  MODULE_ITEM_CODE INT DEFAULT NULL,
  MODULE_SUB_ITEM_CODE INT DEFAULT NULL,
  MODULE_ITEM_KEY VARCHAR(20) DEFAULT NULL,
  MODULE_SUB_ITEM_KEY VARCHAR(20) DEFAULT NULL,
  QUESTIONNAIRE_COMPLETED_FLAG VARCHAR(1) DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATE_USER VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (QUESTIONNAIRE_ANS_HEADER_ID),
  CONSTRAINT FB_QUEST_ANSWER_HEADER_FK1 FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUEST_HEADER (QUESTIONNAIRE_ID)
);

CREATE TABLE FB_QUEST_ANSWER (
  QUESTIONNAIRE_ANSWER_ID INT NOT NULL AUTO_INCREMENT,
  QUESTIONNAIRE_ANS_HEADER_ID INT DEFAULT NULL,
  QUESTION_ID INT DEFAULT NULL,
  OPTION_NUMBER INT DEFAULT NULL,
  ANSWER_NUMBER INT DEFAULT NULL,
  ANSWER VARCHAR(4000) DEFAULT NULL,
  ANSWER_LOOKUP_CODE VARCHAR(100) DEFAULT NULL,
  EXPLANATION VARCHAR(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATE_USER VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (QUESTIONNAIRE_ANSWER_ID),
  CONSTRAINT FB_QUEST_ANSWER_FK1 FOREIGN KEY (QUESTIONNAIRE_ANS_HEADER_ID) REFERENCES FB_QUEST_ANSWER_HEADER (QUESTIONNAIRE_ANS_HEADER_ID),
  CONSTRAINT FB_QUEST_ANSWER_FK2 FOREIGN KEY (QUESTION_ID) REFERENCES QUEST_QUESTION (QUESTION_ID)
); 

CREATE TABLE FB_QUEST_ANSWER_ATTACHMENT (
  QUESTIONNAIRE_ANSWER_ATT_ID INT NOT NULL AUTO_INCREMENT,
  QUESTIONNAIRE_ANSWER_ID INT DEFAULT NULL,
  ATTACHMENT LONGBLOB,
  FILE_NAME VARCHAR(300) DEFAULT NULL,
  CONTENT_TYPE VARCHAR(100) DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATE_USER VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (QUESTIONNAIRE_ANSWER_ATT_ID),
  CONSTRAINT FB_QUEST_ANSWER_ATTACHMENT_FK1 FOREIGN KEY (QUESTIONNAIRE_ANSWER_ID) REFERENCES FB_QUEST_ANSWER (QUESTIONNAIRE_ANSWER_ID)
);

CREATE TABLE FB_QUEST_TABLE_ANSWER (
  QUEST_TABLE_ANSWER_ID INT NOT NULL AUTO_INCREMENT,
  QUESTIONNAIRE_ANS_HEADER_ID INT DEFAULT NULL,
  QUESTION_ID INT DEFAULT NULL,
  ORDER_NUMBER INT DEFAULT NULL,
  COLUMN_1 VARCHAR(250) DEFAULT NULL,
  COLUMN_2 VARCHAR(250) DEFAULT NULL,
  COLUMN_3 VARCHAR(250) DEFAULT NULL,
  COLUMN_4 VARCHAR(250) DEFAULT NULL,
  COLUMN_5 VARCHAR(250) DEFAULT NULL,
  COLUMN_6 VARCHAR(250) DEFAULT NULL,
  COLUMN_7 VARCHAR(250) DEFAULT NULL,
  COLUMN_8 VARCHAR(250) DEFAULT NULL,
  COLUMN_9 VARCHAR(250) DEFAULT NULL,
  COLUMN_10 VARCHAR(250) DEFAULT NULL,
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  UPDATE_USER VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (QUEST_TABLE_ANSWER_ID),
  CONSTRAINT FB_QUESTIONNAIRE_ANS_HEADER_ID_FK1 FOREIGN KEY (QUESTIONNAIRE_ANS_HEADER_ID) REFERENCES FB_QUEST_ANSWER_HEADER (QUESTIONNAIRE_ANS_HEADER_ID)
);
