-- adding STATE_CODE column to PERSON, SPONSOR and ROLODEX tables
ALTER TABLE SPONSOR ADD COLUMN STATE_CODE VARCHAR(15) DEFAULT NULL, ADD CONSTRAINT SPONSOR_STATE_CODE_FK FOREIGN KEY (STATE_CODE) REFERENCES STATES(STATE_CODE);
ALTER TABLE PERSON ADD COLUMN STATE_CODE VARCHAR(15) DEFAULT NULL, ADD CONSTRAINT PERSON_STATE_CODE_FK FOREIGN KEY (STATE_CODE) REFERENCES STATES(STATE_CODE);
ALTER TABLE ROLODEX ADD COLUMN STATE_CODE VARCHAR(15) DEFAULT NULL, ADD CONSTRAINT ROLODEX_STATE_CODE_FK FOREIGN KEY (STATE_CODE) REFERENCES STATES(STATE_CODE);

-- migration - updating state code for existing state values that matches the values in STATES table
-- UPDATE PERSON JOIN STATES S ON PERSON.STATE = S.STATE_NAME SET PERSON.STATE_CODE = S.STATE_CODE;
-- UPDATE ROLODEX JOIN STATES S ON ROLODEX.STATE = S.STATE_NAME SET ROLODEX.STATE_CODE = S.STATE_CODE;
-- UPDATE SPONSOR JOIN STATES S ON SPONSOR.STATE = S.STATE_NAME SET SPONSOR.STATE_CODE = S.STATE_CODE;

ALTER TABLE STATES
MODIFY COLUMN STATE_CODE VARCHAR(15);
