DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST_COUNT;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_COUNT;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_DATA;
