
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_SAFE_UPDATES = 0;
update ENTITY_RISK set RISK_LEVEL_CODE = "4" where RISK_LEVEL_CODE = "2";
delete from VALID_ENTITY_RISK_LEVEL where RISK_LEVEL_CODE = 2;
DELETE FROM `ENTITY_RISK_LEVEL` WHERE (`RISK_LEVEL_CODE` = '2');
SET SQL_SAFE_UPDATES = 1;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `parameter` (`PARAMETER_NAME`, `VALUE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`)
VALUES ('ADD_DEFAULT_RISK_FOR_ENTITY_ORG', 'Y', 'This parameter is used to add org risk for entity by default(if Y will add default risk)', now(), 'quickstart');

INSERT INTO `ENTITY_RISK_LEVEL` (`RISK_LEVEL_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('2', 'Medium', 'Y', now(), '10000000001');

INSERT INTO `VALID_ENTITY_RISK_LEVEL` (`RISK_TYPE_CODE`, `RISK_LEVEL_CODE`) VALUES ('1', '2');
INSERT INTO `VALID_ENTITY_RISK_LEVEL` (`RISK_TYPE_CODE`, `RISK_LEVEL_CODE`) VALUES ('2', '2');
INSERT INTO `VALID_ENTITY_RISK_LEVEL` (`RISK_TYPE_CODE`, `RISK_LEVEL_CODE`) VALUES ('5', '2');