INSERT IGNORE INTO PARAMETER 
(PARAMETER_NAME, VALUE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES 
('OPA_APPROVAL_FLOW_TYPE', 'ROUTING_AND_ADMIN_REVIEW', 
 'This is used to define the OPA Approval flow type the system follows. Can have values ROUTING_AND_ADMIN_REVIEW, ROUTING_REVIEW, ADMIN_REVIEW, and NO_REVIEW.',
 UTC_TIMESTAMP(), 'admin');

INSERT IGNORE INTO RIGHTS 
(RIGHT_ID,RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)
VALUES 
((SELECT A.ID FROM (SELECT MAX(RIGHT_ID) + 1 AS ID FROM RIGHTS ) AS A),'OPA_DEPARTMENT_ADMINISTRATOR', 
 'To add or manage reviews in OPA.',
 'admin',
 UTC_TIMESTAMP(),
 '2');

INSERT IGNORE INTO `ROLE` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (1374,'OPA Department Administrator','OPA Department Administrator','2','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin');
INSERT IGNORE INTO `ROLE` (`ROLE_ID`,`ROLE_NAME`,`DESCRIPTION`,`ROLE_TYPE_CODE`,`STATUS_FLAG`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (1375,'DAF','DAF','2','Y',UTC_TIMESTAMP(),'admin',UTC_TIMESTAMP(),'admin');

INSERT IGNORE INTO business_rule_function 
(FUNCTION_NAME, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, DB_FUNCTION_NAME, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES
('To check all OPA Reviews are Completed', 
 23, 
 0, 
 'To check all OPA Reviews are Completed',
 'FN_IS_ALL_OPA_REVIEWS_COMPLETED',
 UTC_TIMESTAMP(), 
 'admin');

INSERT IGNORE INTO business_rule_function_arg 
(FUNCTION_NAME, ARGUMENT_SEQUENCE_NUMBER, ARGUMENT_NAME, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER)
VALUES
('To check all OPA Reviews are Completed',
 1,
 'AV_OPA_DISCLOSURE_ID',
 'To check all OPA Reviews are Completed',
 UTC_TIMESTAMP(),
 'admin');

INSERT IGNORE INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES (2301,'OPA Department Administrator',UTC_TIMESTAMP(),'admin','Y');
INSERT IGNORE INTO `person_role_type` (`ROLE_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES (2302,'DAF',UTC_TIMESTAMP(),'admin','Y');
