DELIMITER //
CREATE FUNCTION `FN_CHK_IS_HOME_UNIT_SUBMISSION`(
	AV_DISCLOSURE_ID INT,
    AV_PERSON_ID VARCHAR(60)
) RETURNS tinyint
    DETERMINISTIC
BEGIN
    DECLARE LS_FCOI_TYPE_CODE VARCHAR(3);
    DECLARE LS_HOME_UNIT VARCHAR(8);

    -- Fetch the disclosure's type code and home unit
    SELECT FCOI_TYPE_CODE, HOME_UNIT
    INTO LS_FCOI_TYPE_CODE, LS_HOME_UNIT
    FROM COI_DISCLOSURE
    WHERE DISCLOSURE_ID = AV_DISCLOSURE_ID;

    -- For FCOI_TYPE_CODE 1 or 3 (initial/revision disclosures)
    IF LS_FCOI_TYPE_CODE IN (1, 3) THEN
        IF EXISTS (
            SELECT 1
            FROM PERSON_ROLES T1
            JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.PERSON_ID = AV_PERSON_ID
              AND T1.DESCEND_FLAG = 'N'
              AND T3.RIGHT_NAME IN ('MANAGE_FCOI_DISCLOSURE', 'VIEW_FCOI_DISCLOSURE', 'VIEW_ADMIN_GROUP_COI')
              AND T1.UNIT_NUMBER = LS_HOME_UNIT
        ) OR EXISTS (
            SELECT 1
            FROM UNIT_WITH_CHILDREN U
            JOIN PERSON_ROLES T1 ON U.UNIT_NUMBER = T1.UNIT_NUMBER
            JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.PERSON_ID = AV_PERSON_ID
              AND T1.DESCEND_FLAG = 'Y'
              AND T3.RIGHT_NAME IN ('MANAGE_FCOI_DISCLOSURE', 'VIEW_FCOI_DISCLOSURE', 'VIEW_ADMIN_GROUP_COI')
              AND U.CHILD_UNIT_NUMBER = LS_HOME_UNIT
        ) THEN
            RETURN 1;
        END IF;

    -- For FCOI_TYPE_CODE 2 (project disclosures)
    ELSEIF LS_FCOI_TYPE_CODE = 2 THEN
        IF EXISTS (
            SELECT 1
            FROM PERSON_ROLES T1
            JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.PERSON_ID = AV_PERSON_ID
              AND T1.DESCEND_FLAG = 'N'
              AND T3.RIGHT_NAME IN ('MANAGE_PROJECT_DISCLOSURE', 'VIEW_PROJECT_DISCLOSURE', 'VIEW_ADMIN_GROUP_COI')
              AND T1.UNIT_NUMBER = LS_HOME_UNIT
        ) OR EXISTS (
            SELECT 1
            FROM UNIT_WITH_CHILDREN U
            JOIN PERSON_ROLES T1 ON U.UNIT_NUMBER = T1.UNIT_NUMBER
            JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.PERSON_ID = AV_PERSON_ID
              AND T1.DESCEND_FLAG = 'Y'
              AND T3.RIGHT_NAME IN ('MANAGE_PROJECT_DISCLOSURE', 'VIEW_PROJECT_DISCLOSURE', 'VIEW_ADMIN_GROUP_COI')
              AND U.CHILD_UNIT_NUMBER = LS_HOME_UNIT
        ) THEN
            RETURN 1;
        END IF;
    END IF;

    RETURN 0;
    END;
//
