DROP FUNCTION IF EXISTS FN_RULE_BUILD_WORKFLOW;
DROP FUNCTION IF EXISTS FN_WORKFLOW_APPROVE;
DROP PROCEDURE IF EXISTS GET_WORKFLOW_MISSING_ROLE_TYPE;
DROP PROCEDURE IF EXISTS INSERT_WORKFLOW_ALTER_APPROVER;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_FUNCTION;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_WORKFLOW;
