CREATE TABLE OPA_DISCL_PERSON_ENTITY_REL (
    OPA_PERSON_ENTITY_REL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DISCLOSURE_ID INT NOT NULL,
    PERSON_ENTITY_ID INT NOT NULL,
    PERSON_ENTITY_NUMBER INT NOT NULL,
    PERSON_ID VARCHAR(40) NOT NULL,
    ENTITY_ID INT NOT NULL,
    INVOLVEMENT_START_DATE DATE,
    INVOLVEMENT_END_DATE DATE,
    ENTITY_NAME VARCHAR(500),
    IS_COMPENSATED VARCHAR(1),
    RELATIONSHIPS VARCHAR(100),
    INVOLVEMENT_OF_STUDENTS VARCHAR(3),
    INVOLVEMENT_OF_STAFF VARCHAR(3),
    USE_OF_MIT_RESOURCES VARCHAR(3),
    SABBATICAL_TYPE VARCHAR(15) DEFAULT NULL,
    INCLUDE_IN_OPA_DISCLOSURE VARCHAR(1),
    UPDATE_USER VARCHAR(60),
    UPDATE_TIMESTAMP DATETIME, 
    CONSTRAINT OPA_DISCL_PERSON_ENTITY_REL_FK1 
        FOREIGN KEY (PERSON_ENTITY_ID) REFERENCES PERSON_ENTITY(PERSON_ENTITY_ID),  
    CONSTRAINT OPA_DISCL_PERSON_ENTITY_REL_FK2 
        FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ENTITY_ID), 
    CONSTRAINT OPA_DISCL_PERSON_ENTITY_REL_UQ 
        UNIQUE (DISCLOSURE_ID, PERSON_ID, PERSON_ENTITY_NUMBER)
);
