
CREATE TABLE `NOTIFY_PLACEHOLDER_HEADER` (
  `NOTIFY_PLACEHOLDER_HEADER_ID` INT NOT NULL AUTO_INCREMENT,
  `MODULE_CODE` INT(3) NOT NULL,
  `SUB_MODULE_CODE` INT(3) NOT NULL,
  `QUERY_DEFINITION` TEXT NULL,
  `QUERY_TYPE` VARCHAR(1) NOT NULL,
  `ELEMENT_NAME` VARCHAR(100) NULL,
  `ELEMENT_TYPE` VARCHAR(1) NOT NULL,
  `IS_ACTIVE` VARCHAR(1) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATE_USER` VARCHAR(60) NULL,
  `UNIQUE_DISPLAY_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`NOTIFY_PLACEHOLDER_HEADER_ID`));


  CREATE TABLE `NOTIFY_PLACEHOLDER_COLUMNS` (
  `NOTIFY_PLACEHOLDER_COLUMN_ID` INT NOT NULL AUTO_INCREMENT,
  `NOTIFY_PLACEHOLDER_HEADER_ID` INT NOT NULL,
  `QUERY_COLUMN_NAME` VARCHAR(100) NOT NULL,
  `LABEL_NAME` VARCHAR(100) NOT NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATE_USER` VARCHAR(60) NULL,
  PRIMARY KEY (`NOTIFY_PLACEHOLDER_COLUMN_ID`),
  INDEX `NOTIFY_PLACEHOLDER_COLUMNS_FK1_idx` (`NOTIFY_PLACEHOLDER_HEADER_ID` ASC) VISIBLE,
  CONSTRAINT `NOTIFY_PLACEHOLDER_COLUMNS_FK1`
    FOREIGN KEY (`NOTIFY_PLACEHOLDER_HEADER_ID`)
    REFERENCES `NOTIFY_PLACEHOLDER_HEADER` (`NOTIFY_PLACEHOLDER_HEADER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE `NOTIFY_MSG_BODY_PREDEFINED_OBJ` (
  `NOTIFY_PREDEFINED_OBJ_ID` INT NOT NULL AUTO_INCREMENT,
  `MODULE_CODE` INT(3) NOT NULL,
  `SUB_MODULE_CODE` VARCHAR(3) NOT NULL,
  `OBJECT` TEXT NULL,
  `OBJECT_TYPE` VARCHAR(3) NOT NULL,
  `IS_ACTIVE` VARCHAR(1) NULL,
  `DESCRIPTION` VARCHAR(200) NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATE_USER` VARCHAR(60) NULL,
  PRIMARY KEY (`NOTIFY_PREDEFINED_OBJ_ID`));


CREATE TABLE `MODULE_ACTION_TYPE` (
  `MODULE_ACTION_TYPE_ID` INT NOT NULL AUTO_INCREMENT,
  `ACTION_TYPE` VARCHAR(30) NOT NULL,
  `MODULE_CODE` INT(3) NOT NULL,
  `SUB_MODULE_CODE` INT(3) NOT NULL,
  `IS_ACTIVE` VARCHAR(1) NULL,
  `DESCRIPTION` VARCHAR(200) NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATE_USER` VARCHAR(60) NULL,
  PRIMARY KEY (`MODULE_ACTION_TYPE_ID`));


 CREATE TABLE `NOTIFY_ACTION_TYPE_MAP` (
  `NOTIFY_ACTION_TYPE_MAP_ID` INT NOT NULL AUTO_INCREMENT,
  `NOTIFICATION_TYPE_ID` INT NOT NULL,
  `MODULE_ACTION_TYPE_ID` INT NOT NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATE_USER` VARCHAR(60) NULL,
  PRIMARY KEY (`NOTIFY_ACTION_TYPE_MAP_ID`),
  CONSTRAINT `NOTIFY_ACTION_TYPE_MAP_FK1`
    FOREIGN KEY (`NOTIFICATION_TYPE_ID`)
    REFERENCES `notification_type` (`NOTIFICATION_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NOTIFY_ACTION_TYPE_MAP_FK2`
    FOREIGN KEY (`MODULE_ACTION_TYPE_ID`)
    REFERENCES `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
