CREATE TABLE FIBI_COI_CONNECT_DUMMY (
  DUMMY_ID INT NOT NULL AUTO_INCREMENT,
  TYPE_CODE VARCHAR(3) DEFAULT NULL,
  PROPOSAL_ID INT DEFAULT NULL,
  PERSON_ID VARCHAR(60) DEFAULT NULL,
  UNIT_NUMBER VARCHAR(8) DEFAULT NULL,
  PRIMARY KEY (DUMMY_ID)
);

CREATE TABLE COI_INT_STAGE_DEV_PROPOSAL (
  STAGE_PROPOSAL_ID INT NOT NULL AUTO_INCREMENT,
  PROPOSAL_NUMBER INT NOT NULL,
  VERSION_NUMBER INT DEFAULT NULL,
  IP_NUMBER VARCHAR(20) DEFAULT NULL,
  SPONSOR_GRANT_NUMBER VARCHAR(50) DEFAULT NULL,
  TITLE VARCHAR(1000) DEFAULT NULL,
  PROPOSAL_START_DATE DATETIME DEFAULT NULL,
  PROPOSAL_END_DATE DATETIME DEFAULT NULL,
  LEAD_UNIT VARCHAR(8) DEFAULT NULL,
  LEAD_UNIT_NAME VARCHAR(255) DEFAULT NULL,
  SPONSOR_CODE VARCHAR(50) DEFAULT NULL,
  SPONSOR VARCHAR(255) DEFAULT NULL,
  PRIME_SPONSOR_CODE VARCHAR(50) DEFAULT NULL,
  PRIME_SPONSOR VARCHAR(255) DEFAULT NULL,
  PROPOSAL_STATUS_CODE VARCHAR(255) DEFAULT NULL,
  PROPOSAL_STATUS VARCHAR(255) DEFAULT NULL,
  PROPOSAL_TYPE_CODE VARCHAR(255) DEFAULT NULL,
  PROPOSAL_TYPE VARCHAR(255) DEFAULT NULL,
  DOCUMENT_URL VARCHAR(2000) DEFAULT NULL,
  FIRST_FED_TIMESTAMP DATETIME DEFAULT NULL,
  LAST_FED_TIMESTAMP DATETIME DEFAULT NULL,
  SRC_SYS_UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  SRC_SYS_UPDATE_USER_NAME VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_1_LABEL VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_1_VALUE VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_2_LABEL VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_2_VALUE VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_3_LABEL VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_3_VALUE VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_4_LABEL VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_4_VALUE VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_5_LABEL VARCHAR(255) DEFAULT NULL,
  ATTRIBUTE_5_VALUE VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (STAGE_PROPOSAL_ID),
  KEY COI_PROP_IDX (PROPOSAL_NUMBER)
) ;

CREATE TABLE COI_INT_STAGE_DEV_PROPOSAL_PERSON (
  PROPOSAL_NUMBER int NOT NULL,
  KEY_PERSON_ID varchar(40) NOT NULL,
  KEY_PERSON_ROLE_CODE int NOT NULL,
  KEY_PERSON_ROLE varchar(25) NOT NULL,
  KEY_PERSON_NAME varchar(90) DEFAULT NULL,
  PERCENTAGE_OF_EFFORT decimal(5,2) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  ATTRIBUTE_1_LABEL varchar(90) DEFAULT NULL,
  ATTRIBUTE_1_VALUE varchar(90) DEFAULT NULL,
  ATTRIBUTE_2_LABEL varchar(90) DEFAULT NULL,
  ATTRIBUTE_2_VALUE varchar(90) DEFAULT NULL,
  ATTRIBUTE_3_LABEL varchar(90) DEFAULT NULL,
  ATTRIBUTE_3_VALUE varchar(90) DEFAULT NULL,
  PRIMARY KEY (PROPOSAL_NUMBER,KEY_PERSON_ID,KEY_PERSON_ROLE_CODE,KEY_PERSON_ROLE)
) ;

CREATE TABLE `COI_INT_STAGE_DEV_QNR_ANSWER` (
  `STAGE_PROPOSAL_QNR_ANSWER_ID` int NOT NULL AUTO_INCREMENT,
  `PROPOSAL_NUMBER` int NOT NULL,
  `KEY_PERSON_ID` varchar(40) NOT NULL,
  `QUESTIONNAIRE_ID` int DEFAULT NULL,
  `QUESTION_ID` int DEFAULT NULL,
  `ANSWER` varchar(4000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `ATTRIBUTE_1_LABEL` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_1_VALUE` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_2_LABEL` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_2_VALUE` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_3_LABEL` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_3_VALUE` varchar(90) DEFAULT NULL,
  PRIMARY KEY (`STAGE_PROPOSAL_QNR_ANSWER_ID`)
);

-- CREATE TABLE MQ_EXCEPTION_LOG (
--  ID int NOT NULL AUTO_INCREMENT,
--  ACTION_TYPE varchar(50) DEFAULT NULL,
--  ERROR_CODE varchar(10) DEFAULT NULL,
--  ERROR_MESSAGE varchar(255) DEFAULT NULL,
--  MESSAGE_ID varchar(100) NOT NULL,
--  MODULE_CODE int DEFAULT NULL,
--  QUEUE_EXCHANGE varchar(60) DEFAULT NULL,
--  QUEUE_MESSAGE text NOT NULL,
--  SOURCE_QUEUE_NAME varchar(60) DEFAULT NULL,
--  DESTINATION_QUEUE_NAME varchar(60) DEFAULT NULL,
--  STACK_TRACE text,
--  SUB_MODULE_CODE int DEFAULT NULL,
--  UPDATE_TIMESTAMP datetime DEFAULT NULL,
--  UPDATE_USER varchar(60) DEFAULT NULL,
--  USER_TYPE varchar(3) DEFAULT 'S',
--  EVENT_TYPE varchar(3) DEFAULT NULL,
--  TRIGGER_TYPE varchar(25) DEFAULT NULL,
--  PRIMARY KEY (ID)
-- ) ;

CREATE TABLE `FIBI_COI_QNR_MAPPING` (
  `QNR_MAPPING_ID` smallint NOT NULL AUTO_INCREMENT,
  `SOURCE_QNR_ID` mediumint NOT NULL,
  `SOURCE_QNR_NUM` mediumint NOT NULL,
  `FIBI_QNR_ID` mediumint NOT NULL,
  `FIBI_QNR_NUM` mediumint NOT NULL,
  `UPDATED_BY` varchar(60) NOT NULL,
  `UPDATE_TIMESTAMP` datetime NOT NULL,
  PRIMARY KEY (`QNR_MAPPING_ID`)
);

CREATE TABLE `FIBI_COI_QNR_QSTN_MAPPING` (
  `ID` smallint NOT NULL AUTO_INCREMENT,
  `QNR_MAPPING_ID` smallint DEFAULT NULL,
  `SOURCE_QSTN_ID` mediumint NOT NULL,
  `SOURCE_QSTN_NUM` mediumint NOT NULL,
  `SOURCE_QSTN_DATA_TYPE` varchar(30) DEFAULT NULL,
  `FIBI_QSTN_ID` mediumint NOT NULL,
  `FIBI_QSTN_NUM` mediumint NOT NULL,
  `FIBI_QSTN_DATA_TYPE` varchar(30) DEFAULT NULL,
  `UPDATED_BY` varchar(60) NOT NULL,
  `UPDATE_TIMESTAMP` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FIBI_COI_QNR_QSTN_MAPPING_FK1` (`QNR_MAPPING_ID`),
  CONSTRAINT `FIBI_COI_QNR_QSTN_MAPPING_FK1` FOREIGN KEY (`QNR_MAPPING_ID`) REFERENCES `fibi_coi_qnr_mapping` (`QNR_MAPPING_ID`)
);


INSERT INTO `COEUS_SUB_MODULE` (`COEUS_SUB_MODULE_ID`, `MODULE_CODE`, `SUB_MODULE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `REQUIRE_UNIQUE_QUESTIONNAIRE`, `IS_ACTIVE`) VALUES ('802', '8', '802', 'Integrated Questionnaire', '2019-05-31', 'admin', 'N', 'Y');
ALTER TABLE `COI_INT_STAGE_DEV_PROPOSAL`CHANGE COLUMN `PROPOSAL_NUMBER` `PROPOSAL_NUMBER` VARCHAR(20) NOT NULL ;
ALTER TABLE `COI_INT_STAGE_DEV_PROPOSAL_PERSON`CHANGE COLUMN `PROPOSAL_NUMBER` `PROPOSAL_NUMBER` VARCHAR(20) NOT NULL ;
ALTER TABLE `COI_INT_STAGE_DEV_QNR_ANSWER`CHANGE COLUMN `PROPOSAL_NUMBER` `PROPOSAL_NUMBER` VARCHAR(20) NOT NULL ;

