DROP TABLE IF EXISTS COI_TRAVEL_FUNDING_AGENCY_TYPE;
CREATE TABLE `COI_TRAVEL_FUNDING_AGENCY_TYPE` (
  `FUNDING_AGENCY_CODE` VARCHAR(3) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATED_BY` VARCHAR(40) NULL,
  `IS_ACTIVE` VARCHAR(1) NULL,
  PRIMARY KEY (`FUNDING_AGENCY_CODE`));

DROP TABLE IF EXISTS COI_TRAVEL_FUNDING_TYPE;
CREATE TABLE `COI_TRAVEL_FUNDING_TYPE` (
  `FUNDING_TYPE_CODE` VARCHAR(3) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATED_BY` VARCHAR(40) NULL,
  `IS_ACTIVE` VARCHAR(1) NULL,
  PRIMARY KEY (`FUNDING_TYPE_CODE`));

DROP TABLE IF EXISTS COI_TRAVEL_FUNDING_AGENCIES;
CREATE TABLE `COI_TRAVEL_FUNDING_AGENCIES` (
  `TRAVEL_FUNDING_AGENCY_ID` INT NOT NULL AUTO_INCREMENT,
  `TRAVEL_DISCLOSURE_ID` INT NULL,
  `FUNDING_AGENCY_CODE` VARCHAR(3) NULL,
  `UPDATED_BY` VARCHAR(40) NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  PRIMARY KEY (`TRAVEL_FUNDING_AGENCY_ID`),
  INDEX `COI_TRAVEL_FUNDING_AGENCIES_FK1_idx` (`TRAVEL_DISCLOSURE_ID` ASC) VISIBLE,
  INDEX `COI_TRAVEL_FUNDING_AGENCIES_FK2_idx` (`FUNDING_AGENCY_CODE` ASC) VISIBLE,
  CONSTRAINT `COI_TRAVEL_FUNDING_AGENCIES_FK1`
    FOREIGN KEY (`TRAVEL_DISCLOSURE_ID`)
    REFERENCES `COI_TRAVEL_DISCLOSURE` (`TRAVEL_DISCLOSURE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `COI_TRAVEL_FUNDING_AGENCIES_FK2`
    FOREIGN KEY (`FUNDING_AGENCY_CODE`)
    REFERENCES `COI_TRAVEL_FUNDING_AGENCY_TYPE` (`FUNDING_AGENCY_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

DROP TABLE IF EXISTS coi_travel_destinations;
CREATE TABLE `coi_travel_destinations` (
  `TRAVEL_DESTINATION_ID` INT NOT NULL AUTO_INCREMENT,
  `TRAVEL_DISCLOSURE_ID` INT NULL,
  `PLACE_OF_STAY` VARCHAR(100) NULL,
  `CITY` VARCHAR(100) NULL,
  `STATE` VARCHAR(100) NULL,
  `POST_CODE` VARCHAR(20) NULL,
  `COUNTRY_CODE` VARCHAR(3) NULL,
  `STAY_START_DATE` DATE NULL,
  `STAY_END_DATE` DATE NULL,
  `UPDATE_TIMESTAMP` DATETIME NULL,
  `UPDATED_BY` VARCHAR(40) NULL,
  PRIMARY KEY (`TRAVEL_DESTINATION_ID`));

DROP TABLE IF EXISTS TRAVEL_FORM_BUILDER_DETAILS;
 CREATE TABLE `TRAVEL_FORM_BUILDER_DETAILS` (
   `TRAVEL_FORM_BUILDER_DETAILS_ID` int NOT NULL AUTO_INCREMENT,
   `TRAVEL_DISCLOSURE_ID` int NOT NULL,
   `TRAVEL_NUMBER` int NOT NULL,
   `PERSON_ID` varchar(40) NOT NULL,
   `FORM_BUILDER_ID` int NOT NULL,
   `IS_PRIMARY_FORM` varchar(1) NOT NULL,
   `UPDATE_TIMESTAMP` datetime NOT NULL,
   `UPDATED_BY` varchar(40) NOT NULL,
   PRIMARY KEY (`TRAVEL_FORM_BUILDER_DETAILS_ID`)
 );