
INSERT INTO `NOTIFICATION_TYPE` (`NOTIFICATION_TYPE_ID`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`SUBJECT`,`MESSAGE`,`PROMPT_USER`,`IS_ACTIVE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`IS_SYSTEM_SPECIFIC`,`SHOW_TEMPLATE_IN_MODULE`,`SENT_TO_INITIATOR`) VALUES (8085,8,0,'Project Disclosure Review Location Assign without Reviewer.','Action required: Project disclosure Submitted by {COI_DISCLOSURE#REPORTER_NAME} waiting for review at {COI_DISCL_REVIEW#REVIEW_LOCATION}.','<p><span style=\"color:hsl(0,0%,0%);\">Hello Reviewer,</span></p><p><span style=\"color:hsl(0,0%,0%);\">On {COI_DISCL_REVIEW#REVIEW_ASSIGNED_DATE}, COI Administrator {COI_DISCLOSURE#ADMINISTRATOR_NAME} assigned you to review the Project Disclosure submitted on </span><span style=\"font-family:Arial, Helvetica, sans-serif;\">{COI_DISCLOSURE#CERTIFICATION_DATE}</span><span style=\"color:hsl(0,0%,0%);\"> by {COI_DISCLOSURE#REPORTER_NAME}.</span></p><p><span style=\"color:hsl(0,0%,0%);\"><strong>Department</strong>: </span><span style=\"font-family:Arial, Helvetica, sans-serif;\">{COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style=\"font-family:Arial, Helvetica, sans-serif;\"><strong>Project</strong>: {COI_DISCLOSURE#PROJECT_TYPE} - {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</span></p><p><span style=\"color:hsl(0,0%,0%);\"><strong>Disclosure Status</strong>: </span><span style=\"font-family:Arial, Helvetica, sans-serif;\">{COI_DISCLOSURE#DISCLOSURE_STATUS}</span></p><p><span style=\"color:hsl(0,0%,0%);\"><strong>Review Location</strong>: {COI_DISCL_REVIEW#REVIEW_LOCATION}</span></p><p><span style=\"color:hsl(0,0%,0%);\"><strong>Review Status</strong>: {COI_DISCL_REVIEW#REVIEWER_REVIEW_STATUS}</span></p><p><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p><span style=\"color:hsl(0,0%,0%);\">Note: This is a system-generated email. Please do not reply to this email.</span></p>','N','Y','admin',now(),'admin',now(),'N',NULL,'N');

INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8085,NULL,56,NULL,now(),NULL,NULL,'TO','COI Primary Administrator');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8085,NULL,52,NULL,now(),NULL,NULL,'CC','COI Administrators');

INSERT INTO `MODULE_ACTION_TYPE` (`MODULE_ACTION_TYPE_ID`,`ACTION_TYPE`,`MODULE_CODE`,`SUB_MODULE_CODE`,`IS_ACTIVE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (84,'PROJ_LOC_ASSIGNED_NO_REVIEWER',8,0,'Y','Project Location added without reviewer',now(),'admin');

INSERT INTO `NOTIFY_ACTION_TYPE_MAP` (`NOTIFICATION_TYPE_ID`,`MODULE_ACTION_TYPE_ID`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES (8085,84,now(),'admin');

INSERT INTO `MQ_ROUTER_ACTION_CONFIGURATION` (`ACTION_TYPE`,`IS_ACTIVE`,`MODULE_CODE`,`QUEUE_NAME`,`SUB_MODULE_CODE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('PROJ_LOC_ASSIGNED_NO_REVIEWER','Y',8,'Q_NOTIFICATION',0,now(),'admin');

INSERT INTO `NOTIFY_PLACEHOLDER_COLUMNS` (`NOTIFY_PLACEHOLDER_HEADER_ID`,`QUERY_COLUMN_NAME`,`LABEL_NAME`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`BASE_URL_ID`,`URL_PATH`) VALUES (3,'REVIEW_ASSIGNED_DATE','Review Assigned Date',now(),'admin',NULL,NULL);
