CREATE TABLE IF NOT EXISTS DECLARATION_PERSON_ELIGIBILITY ( PERSON_ELIGIBILITY_ID INT NOT NULL AUTO_INCREMENT,
    PERSON_ID VARCHAR(40) DEFAULT NULL, DECLARATION_TYPE_CODE VARCHAR(3) DEFAULT NULL,
    CAN_CREATE_DECLARATION VARCHAR(1) DEFAULT 'N', ADMIN_FORCE_ALLOWED_TO_CREATE VARCHAR(1) DEFAULT 'N',
    VERSION_STATUS VARCHAR(20) DEFAULT NULL, VERSION_NUMBER INT DEFAULT NULL,
    UPDATED_BY VARCHAR(40) DEFAULT NULL, UPDATE_TIMESTAMP TIMESTAMP NULL,
    PRIMARY KEY (PERSON_ELIGIBILITY_ID),
    CONSTRAINT DECLARATION_PERSON_ELIGIBILITY_FK1 FOREIGN KEY (DECLARATION_TYPE_CODE) REFERENCES COI_DECLARATION_TYPE (DECLARATION_TYPE_CODE) );

CREATE TABLE IF NOT EXISTS DECLARATION_SPONSOR_REQUREMNTS ( SPONSOR_REQUREMNTS_ID INT NOT NULL AUTO_INCREMENT,
    SPONSOR_CODE VARCHAR(6) DEFAULT NULL, DECLARATION_TYPE_CODE VARCHAR(3) DEFAULT NULL,
    UPDATED_BY VARCHAR(40) DEFAULT NULL, UPDATE_TIMESTAMP TIMESTAMP NULL,
    PRIMARY KEY (SPONSOR_REQUREMNTS_ID),
    CONSTRAINT DECLARATION_SPONSOR_REQUREMNTS_FK1 FOREIGN KEY (DECLARATION_TYPE_CODE) REFERENCES COI_DECLARATION_TYPE (DECLARATION_TYPE_CODE) );
