DELIMITER //
CREATE FUNCTION `FN_CHK_HIERARCHY_HAS_DISCL`(
    AWARD_NUMBER VARCHAR(12),
    KEY_PERSON_ID VARCHAR(60)
) RETURNS varchar(255) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
	DECLARE RESULT VARCHAR(255) DEFAULT NULL;
    DECLARE FIRST_PART_AWARD VARCHAR(12) DEFAULT NULL;
    DECLARE RELATED_AWARD_NUMBER VARCHAR(12) DEFAULT NULL;
    DECLARE DISCLOSURE_ID INT DEFAULT 0;
    DECLARE CERTIFIED_AT DATETIME DEFAULT NULL;

    -- Extract the first part of the AWARD_NUMBER before the hyphen (-)
    SET FIRST_PART_AWARD = SUBSTRING_INDEX(AWARD_NUMBER, '-', 1);

    -- Check for related records in coi_discl_projects and coi_disclosure
    SELECT 
        T1.MODULE_ITEM_KEY,
        T2.DISCLOSURE_ID,
        T2.CERTIFIED_AT
    INTO 
        RELATED_AWARD_NUMBER,
        DISCLOSURE_ID,
        CERTIFIED_AT
    FROM 
        COI_DISCL_PROJECTS T1
    INNER JOIN 
        COI_DISCLOSURE T2 
        ON T1.DISCLOSURE_ID = T2.DISCLOSURE_ID
    WHERE 
        T1.MODULE_CODE = 1
        AND T2.DISPOSITION_STATUS_CODE <> 2
        AND T2.VERSION_STATUS <> 'ARCHIVE'
        AND T2.PERSON_ID = KEY_PERSON_ID
        AND t1.MODULE_ITEM_KEY <> AWARD_NUMBER
        AND T1.MODULE_ITEM_KEY LIKE CONCAT(FIRST_PART_AWARD, '-%')
        AND T2.DISCLOSURE_ID = (select max(DISCLOSURE_ID) from COI_DISCLOSURE where DISCLOSURE_NUMBER = T2.DISCLOSURE_NUMBER )
    ORDER BY 
        T2.CERTIFIED_AT DESC
    LIMIT 1;

    -- Determine the result based on the count
    IF DISCLOSURE_ID <> 0 THEN
        SET RESULT = CONCAT('Disclosure is created against award: ', RELATED_AWARD_NUMBER);
    ELSE
        SET RESULT = 'NO DATA';
    END IF;

    RETURN RESULT;
END
//
