DELIMITER //
CREATE FUNCTION `FN_GET_OVAL_AWD_PRJT_DISCL_STATUS`(
AV_PROJECT_NUMBER INT) RETURNS varchar(50) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
    DECLARE PROJECT_STATUS VARCHAR(50);
    
        IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND (DISCLOSURE_STATUS IS NOT NULL)
    ) THEN
        RETURN NULL;
    END IF;
    
            IF EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND (DISCLOSURE_STATUS = 'DISCLOSURE_TO_BE_DETERMINED')
    ) THEN
        RETURN NULL;
    END IF;
    
    IF  EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND DISCLOSURE_STATUS = 'DISCLOSURE_PENDING'
		  AND DISCLOSURE_STATUS IS NOT NULL
    ) THEN
        RETURN 'DISCLOSURE_PENDING';
    END IF;



    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND DISCLOSURE_STATUS != 'DISCLOSURE_COMPLETED'
		  AND DISCLOSURE_STATUS IS NOT NULL
    ) THEN
        RETURN 'DISCLOSURE_COMPLETED';
    END IF;
    
        IF EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND DISCLOSURE_STATUS IN ('DISCLOSURE_NOT_REQUIRED' )
		  AND DISCLOSURE_STATUS IS NOT NULL
    ) AND EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND DISCLOSURE_STATUS = 'DISCLOSURE_TO_BE_DETERMINED'
		  AND DISCLOSURE_STATUS IS NOT NULL
    ) AND NOT EXISTS (
            SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND DISCLOSURE_STATUS = 'DISCLOSURE_COMPLETED'
		  AND DISCLOSURE_STATUS IS NOT NULL)
    THEN
        RETURN 'DISCLOSURE_NOT_REQUIRED';
    END IF;
    

 IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND DISCLOSURE_STATUS NOT IN ('DISCLOSURE_NOT_REQUIRED')
		  AND DISCLOSURE_STATUS IS NOT NULL
    ) THEN
        RETURN 'DISCLOSURE_NOT_REQUIRED';
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND DISCLOSURE_STATUS != 'DISCLOSURE_TO_BE_DETERMINED'
		  AND DISCLOSURE_STATUS IS NOT NULL
    ) THEN
        RETURN NULL;
    END IF;
    
     IF EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND DISCLOSURE_STATUS IN ('DISCLOSURE_NOT_REQUIRED', 'DISCLOSURE_TO_BE_DETERMINED')
		  AND DISCLOSURE_STATUS IS NOT NULL
    ) AND EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND DISCLOSURE_STATUS = 'DISCLOSURE_COMPLETED'
		  AND DISCLOSURE_STATUS IS NOT NULL
    ) THEN
        RETURN 'DISCLOSURE_COMPLETED';
    END IF;


    RETURN NULL;
END
//
