INSERT INTO RIGHTS (`RIGHT_ID`, `RIGHT_NAME`, `DESCRIPTION`, `UPDATE_USER`, `UPDATE_TIMESTAMP`, `RIGHTS_TYPE_CODE`)
SELECT (SELECT COALESCE(MAX(RIGHT_ID), 0) + 1 FROM RIGHTS), 'VIEW_ALL_PERSONAL_DETAILS', 'To view all personal details', 'quickstart', NOW(), '2'
WHERE NOT EXISTS (SELECT 1 FROM RIGHTS WHERE RIGHT_NAME = 'VIEW_ALL_PERSONAL_DETAILS');
