DROP PROCEDURE IF EXISTS GET_COI_OPA_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
DROP PROCEDURE IF EXISTS GET_APPROVERS_FOR_ROLE_TYPE;
DROP PROCEDURE IF EXISTS INSERT_WORKFLOW_FOR_ROLE_TYPE;

DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
DROP FUNCTION IF EXISTS FN_IS_ALL_OPA_REVIEWS_COMPLETED;
