\. ./FIBI-COI-5.7.9/FC-1535/Procedures/GET_COI_OPA_DASHBOARD.sql
\. ./FIBI-COI-5.7.9/FC-1535/Procedures/GET_APPROVERS_FOR_ROLE_TYPE.sql
\. ./FIBI-COI-5.7.9/FC-1535/Procedures/GET_ALL_RIGHTS_FOR_A_MODULE.sql
\. ./FIBI-COI-5.7.9/FC-1535/Procedures/INSERT_WORKFLOW_FOR_ROLE_TYPE.sql

\. ./FIBI-COI-5.7.9/FC-1535/Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
\. ./FIBI-COI-5.7.9/FC-1535/Functions/FN_IS_ALL_OPA_REVIEWS_COMPLETED.sql
