DROP PROCEDURE IF EXISTS BULK_UPDATE_GLOBAL_ENTITY_FOREIGN_FLAG;
DROP PROCEDURE IF EXISTS COI_COPY_GLOBAL_ENTITY;
DROP PROCEDURE IF EXISTS ENRICH_ENTITY_CORPORATE_LINKAGE;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_DATA;
DROP PROCEDURE IF EXISTS GET_ENTITY_HIERARCHY;
DROP PROCEDURE IF EXISTS UPDATE_GLOBAL_ENTITY_FOREIGN_FLAG;
