DROP PROCEDURE IF EXISTS FCOI_DISCLOSRE_RENEWAL_REMINDER;
DROP PROCEDURE IF EXISTS GET_APPROVERS_FOR_ROLE_TYPE;
DROP PROCEDURE IF EXISTS GET_COI_DISCL_GENERAL_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_DISCL_REVIEW_DETAILS;
DROP PROCEDURE IF EXISTS PROJECT_DISCLOSURE_RENEWAL_REMINDER;
DROP PROCEDURE IF EXISTS GET_COI_DISCL_PROJECT_DETAILS;
DROP PROCEDURE IF EXISTS GET_GLOBAL_ENTITY_DETAILS;