ALTER TABLE `notify_placeholder_columns`
ADD COLUMN `BASE_URL_ID` INT NULL AFTER `UPDATE_USER`,
ADD INDEX `NOTIFY_PLACEHOLDER_COLUMNS_FK2_idx` (`BASE_URL_ID` ASC) VISIBLE;

ALTER TABLE `notify_placeholder_columns`
ADD CONSTRAINT `NOTIFY_PLACEHOLDER_COLUMNS_FK2`
  FOREIGN KEY (`BASE_URL_ID`)
  REFERENCES `base_urls` (`BASE_URL_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

 ALTER TABLE `notify_placeholder_header`
 CHANGE COLUMN `QUERY_TYPE` `QUERY_TYPE` VARCHAR(1) NULL ;

ALTER TABLE notify_placeholder_columns ADD URL_PATH TINYTEXT NULL;

UPDATE notification_type
SET SUBJECT='Action required: COI Annual disclosure Submitted by {COI_DISCLOSURE#REPORTER_NAME} waiting for review at {COI_DISCL_REVIEW#REVIEW_LOCATION} with {COI_DISCL_REVIEW#REVIEWER_REVIEW_STATUS} status.', MESSAGE='<p><span style="color:hsl(0,0%,0%);">Hello Reviewer,</span></p><p>COI Administrator {COI_DISCLOSURE#ADMINISTRATOR_NAME} assigned you to review the COI Annual Disclosure submitted on <span style="font-family:Arial, Helvetica, sans-serif;">{COI_DISCLOSURE#CERTIFICATION_DATE}</span><span style="color:hsl(0,0%,0%);"> by {COI_DISCLOSURE#REPORTER_NAME}.</span></p><p><span style="color:hsl(0,0%,0%);">Department: </span><span style="font-family:Arial, Helvetica, sans-serif;">{COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style="color:hsl(0,0%,0%);">Disclosure Status: </span><span style="font-family:Arial, Helvetica, sans-serif;">{COI_DISCLOSURE#DISCLOSURE_STATUS}</span></p><p><span style="color:hsl(0,0%,0%);">Review Location: {COI_DISCL_REVIEW#REVIEW_LOCATION}</span></p><p><span style="color:hsl(0,0%,0%);">Review Status: {COI_DISCL_REVIEW#REVIEWER_REVIEW_STATUS}</span></p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p><span style="color:hsl(0,0%,0%);">Note: This is a system-generated email. Please do not reply to this email.</span></p>'
WHERE NOTIFICATION_TYPE_ID=8006;

UPDATE notification_type SET MESSAGE='<p><span style="font-family:Arial, Helvetica, sans-serif;">A COI Annual Disclosure was submitted by {COI_DISCLOSURE#REPORTER_NAME} on {COI_DISCLOSURE#CERTIFICATION_DATE}.</span></p><p><span style="font-family:Arial, Helvetica, sans-serif;">Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style="font-family:Arial, Helvetica, sans-serif;">Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</span></p><p><span style="color:hsl(0, 0%, 0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0, 0%, 0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p><span style="font-family:Arial, Helvetica, sans-serif;">Note: This is a system-generated email. Please do not reply to this email.</span></p>'
WHERE NOTIFICATION_TYPE_ID=8000;

UPDATE notification_type
SET MESSAGE='<p><span style="color:hsl(0, 0%, 0%);">A COI Annual Disclosure was submitted by {COI_DISCLOSURE#REPORTER_NAME} on {COI_DISCLOSURE#CERTIFICATION_DATE} is Withdrawn for the following reason “{COI_DISCL_OTHER#WITHDRAWAL_REASON}”</span></p><p><span style="color:hsl(0, 0%, 0%);">Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style="color:hsl(0, 0%, 0%);">Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</span></p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p><span style="color:hsl(0, 0%, 0%);">Note: This is a system generated email. Please do not reply to this email.</span></p>'
WHERE NOTIFICATION_TYPE_ID=8001;

UPDATE notification_type
SET MESSAGE='<p><span style="color:hsl(0, 0%, 0%);">Hello {COI_DISCL_OTHER#ADMIN_ASSIGNED_TO},</span></p><p><span style="color:hsl(0, 0%, 0%);">The COI Administrator {COI_DISCL_OTHER#ADMIN_ASSIGNED_BY} assigned you as the Administrator of the COI Annual Disclosure submitted on {COI_DISCLOSURE#CERTIFICATION_DATE} by {COI_DISCLOSURE#REPORTER_NAME}.</span></p><p><span style="color:hsl(0, 0%, 0%);">Department: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style="color:hsl(0, 0%, 0%);">Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</span></p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p><span style="color:hsl(0, 0%, 0%);">Note: This is a system-generated email. Please do not reply to this email.</span></p>'
WHERE NOTIFICATION_TYPE_ID=8004;

UPDATE notification_type
SET MESSAGE='<p><span style="color:hsl(0, 0%, 0%);">Hello {COI_DISCL_OTHER#ADMIN_ASSIGNED_TO},</span></p><p><span style="color:hsl(0, 0%, 0%);">The COI Administrator {COI_DISCL_OTHER#ADMIN_ASSIGNED_BY} assigned you as the Administrator of the COI Annual Disclosure submitted on {COI_DISCLOSURE#CERTIFICATION_DATE} by {COI_DISCLOSURE#REPORTER_NAME}.</span></p><p><span style="color:hsl(0, 0%, 0%);">Department: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style="color:hsl(0, 0%, 0%);">Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</span></p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p><span style="color:hsl(0, 0%, 0%);">Note: This is a system-generated email. Please do not reply to this email.</span></p>'
WHERE NOTIFICATION_TYPE_ID=8012;

UPDATE notification_type
SET MESSAGE='<p><span style="color:hsl(0, 0%, 0%);">Hello {COI_DISCLOSURE#ADMINISTRATOR_NAME},</span></p><p><span style="color:hsl(0, 0%, 0%);">COI Administrator removed you as a Administrator for the COI Annual Disclosure submitted on {COI_DISCLOSURE#CERTIFICATION_DATE} by {COI_DISCLOSURE#REPORTER_NAME}.</span></p><p><span style="color:hsl(0, 0%, 0%);">Department: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style="color:hsl(0, 0%, 0%);">You are no longer responsible for reviewing this disclosure.</span></p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p><span style="color:hsl(0, 0%, 0%);">Note: This is a system-generated email. Please do not reply to this email.</span></p>'
WHERE NOTIFICATION_TYPE_ID=8005;

UPDATE notification_type
SET MESSAGE='<p><span style="color:hsl(0, 0%, 0%);">Your COI annual disclosure submitted on {COI_DISCLOSURE#CERTIFICATION_DATE} was returned for the following reason {COI_DISCL_OTHER#RETURN_REASON}.</span></p><p><span style="color:hsl(0, 0%, 0%);">Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style="color:hsl(0, 0%, 0%);">Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</span></p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p><span style="color:hsl(0, 0%, 0%);">Note: This is a system-generated email. Please do not reply to this email.</span></p>'
WHERE NOTIFICATION_TYPE_ID=8002;

UPDATE notification_type
SET MESSAGE='<p>A Project Disclosure was submitted by {COI_DISCLOSURE#REPORTER_NAME} on {COI_DISCLOSURE#CERTIFICATION_DATE}.</p><p>Project: {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</p><p>Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p>Disclosure Status:{COI_DISCLOSURE#DISCLOSURE_STATUS}</p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>'
WHERE NOTIFICATION_TYPE_ID=8007;

UPDATE notification_type
SET MESSAGE='<p>A Project Disclosure was submitted by {COI_DISCLOSURE#REPORTER_NAME} on {COI_DISCLOSURE#CERTIFICATION_DATE} is Withdrawn for the following reason “{COI_DISCL_OTHER#WITHDRAWAL_REASON}”</p><p>Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p>Project: {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} {COI_DISCLOSURE#PROJECT_TITLE}</p><p>Disclosure Status:{COI_DISCLOSURE#DISCLOSURE_STATUS}</p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>'
WHERE NOTIFICATION_TYPE_ID=8008;

UPDATE notification_type
SET MESSAGE='<p>Dear {COI_DISCLOSURE#REPORTER_NAME},</p><p>Your Project disclosure submitted on {COI_DISCLOSURE#CERTIFICATION_DATE} was returned for the following reason “{COI_DISCL_OTHER#RETURN_REASON}”.</p><p>Department : {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p>Project: {COI_DISCLOSURE#PROJECT_TYPE} : {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</p><p>Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>'
WHERE NOTIFICATION_TYPE_ID=8009;

UPDATE notification_type
SET MESSAGE='<p>Hello {COI_DISCL_OTHER#ADMIN_ASSIGNED_TO},</p><p>COI Administrator {COI_DISCL_OTHER#ADMIN_ASSIGNED_BY} assigned you as the Administrator of the Project Disclosure submitted on {COI_DISCLOSURE#CERTIFICATION_DATE} by {COI_DISCLOSURE#REPORTER_NAME}.</p><p>Department: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p>Project: {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</p><p>Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>'
WHERE NOTIFICATION_TYPE_ID=8010;

UPDATE notification_type
SET MESSAGE='<p><span style="color:hsl(0, 0%, 0%);">Hello {COI_DISCLOSURE#ADMINISTRATOR_NAME},</span></p><p><span style="color:hsl(0, 0%, 0%);">COI Administrator removed you as a Administrator for the Project submitted on {COI_DISCLOSURE#CERTIFICATION_DATE} by {COI_DISCLOSURE#REPORTER_NAME}.</span></p><p><span style="color:hsl(0, 0%, 0%);">Department: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</span></p><p><span style="color:hsl(0, 0%, 0%);">Project: {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</span></p><p><span style="color:hsl(0, 0%, 0%);">You are no longer responsible for reviewing this disclosure.</span></p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p><span style="color:hsl(0, 0%, 0%);">Note: This is a system-generated email. Please do not reply to this email.</span></p>'
WHERE NOTIFICATION_TYPE_ID=8011;

UPDATE notification_type
SET MESSAGE='<p>Hello {COI_DISCL_OTHER#ADMIN_ASSIGNED_TO},</p><p>COI Administrator {COI_DISCL_OTHER#ADMIN_ASSIGNED_BY} assigned you as the Administrator of the Project Disclosure submitted on {COI_DISCLOSURE#CERTIFICATION_DATE} by {COI_DISCLOSURE#REPORTER_NAME}.</p><p>Department: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p>Project: {COI_DISCLOSURE#PROJECT_TYPE}: {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</p><p>Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</p><p><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">Please follow</span><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><span style="color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>'
WHERE NOTIFICATION_TYPE_ID=8013;

UPDATE `NOTIFICATION_TYPE` SET `MESSAGE` = '<p>Dear {COI_DISCLOSURE#REPORTER_NAME},</p> <p>We kindly request you to complete and submit your disclosure for the following:</p> <p><strong>Project:</strong> {COI_DISCLOSURE#PROJECT_NUMBER} - {COI_DISCLOSURE#PROJECT_TITLE}</p> <p><strong>Disclosure Status:</strong> {COI_DISCLOSURE#REVIEW_STATUS}</p> <p><br /><span>Please login to COI and access your disclosure at <a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a> to complete and submit your disclosure.</span></p> <p>&nbsp;</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8014');
UPDATE `NOTIFICATION_TYPE` SET `MESSAGE` = '<p>Your COI annual disclosure submitted on {COI_DISCLOSURE#CERTIFICATION_DATE} was approved.</p><p>Department: {COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p>Disclosure Status: {COI_DISCLOSURE#DISCLOSURE_STATUS}</p><p>You can view the disclosure at <span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span><a href="{COI_DISCL_URL#DISCLOSURE_URL}"><span style="font-family:Arial, Helvetica, sans-serif;">this link</span></a><span style="color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;"> </span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>' WHERE (`NOTIFICATION_TYPE_ID` = '8003');