create or replace PROCEDURE FIBI_COI_GET_DEV_PROP_QNR_DTLS(
AV_PROPOSAL_NUMBER IN EPS_PROPOSAL.PROPOSAL_NUMBER%TYPE,
AV_QUESTIONNAIRE_ID IN QUEST_ANSWER_HEADER.QUESTIONNAIRE_ID%TYPE,
AV_PERSON_ID IN PERSON.PERSON_ID%TYPE,
cur_generic        OUT SYS_REFCURSOR)
IS
LS_PERSON_ID            VARCHAR(60);
LS_PROP_PERSON_ROLE_ID  VARCHAR(20);
LS_QUESTIONNAIRE_ID     INT;
BEGIN

-- PROXY EDGE CASE:
SELECT NVL(PERSON_ID,ROLODEX_ID) INTO LS_PERSON_ID FROM EPS_PROP_PERSON WHERE (PROPOSAL_NUMBER,PROP_PERSON_NUMBER) IN ( 
SELECT PROPOSAL_NUMBER,PROP_PERSON_NUMBER 
FROM EPS_PROP_PERSON_CERT_DETAILS 
WHERE CERTIFIED_BY = AV_PERSON_ID 
AND PROPOSAL_NUMBER =AV_PROPOSAL_NUMBER
AND CERTIFIED_TIME = (SELECT MAX(CERTIFIED_TIME) FROM EPS_PROP_PERSON_CERT_DETAILS WHERE CERTIFIED_BY = AV_PERSON_ID AND PROPOSAL_NUMBER =AV_PROPOSAL_NUMBER));


IF AV_QUESTIONNAIRE_ID IS NULL THEN 

    SELECT PROP_PERSON_ROLE_ID INTO LS_PROP_PERSON_ROLE_ID 
    FROM EPS_PROP_PERSON 
    WHERE PERSON_ID = LS_PERSON_ID AND PROPOSAL_NUMBER = AV_PROPOSAL_NUMBER;

    IF LS_PROP_PERSON_ROLE_ID IN ('PI', 'MPI') THEN 
        LS_QUESTIONNAIRE_ID := 501;

    ELSIF LS_PROP_PERSON_ROLE_ID = 'KP' THEN 
        LS_QUESTIONNAIRE_ID := 502;

    ELSIF LS_PROP_PERSON_ROLE_ID = 'COI' THEN 
        LS_QUESTIONNAIRE_ID := 503;
        
    END IF;

ELSE
    LS_QUESTIONNAIRE_ID := AV_QUESTIONNAIRE_ID;

END IF;


    OPEN cur_generic FOR
       SELECT DISTINCT
                    LS_PERSON_ID AS PERSON_ID,
                    q.question_id,
                    qn.QUESTIONNAIRE_ID as questionnaire_id ,
                    case when QA.ANSWER = 'Y' then 'Yes' when QA.ANSWER = 'N' then 'No' else QA.ANSWER end  as ANSWER,
                    NULL AS ATTRIBUTE_1_LABEL,
                    NULL AS ATTRIBUTE_1_VALUE,
                    NULL AS ATTRIBUTE_2_LABEL,
                    NULL AS ATTRIBUTE_2_VALUE,
                    NULL AS ATTRIBUTE_3_LABEL,
                    NULL AS ATTRIBUTE_3_VALUE,
                    P.HOME_UNIT AS HOME_UNIT,
                    '3' as COI_PROJECT_TYPE_CODE

FROM   questionnaire_answer_header QAH
INNER JOIN questionnaire_answer QA
              ON QA.QUESTIONNAIRE_AH_ID_FK =
                 QAH.QUESTIONNAIRE_ANSWER_HEADER_ID
INNER JOIN question q on q.QUESTION_REF_ID = qa.QUESTION_REF_ID_FK
INNER JOIN QUESTIONNAIRE qn on qn.QUESTIONNAIRE_REF_ID = qah.QUESTIONNAIRE_REF_ID_FK
INNER JOIN PERSON P ON P.PERSON_ID = qah.module_sub_item_key
INNER JOIN EPS_PROP_PERSON EPP ON EPP.PROPOSAL_NUMBER = substr(QAH.module_item_key,1,instr(QAH.module_item_key,'|')-1)
INNER JOIN EPS_PROP_PERSON_CERT_DETAILS EPPCD ON EPPCD.PROPOSAL_NUMBER = EPP.PROPOSAL_NUMBER 
AND EPPCD.PROP_PERSON_NUMBER = EPP.PROP_PERSON_NUMBER

WHERE  substr(QAH.module_item_key,1,instr(QAH.module_item_key,'|')-1) = AV_PROPOSAL_NUMBER  
       AND qn.QUESTIONNAIRE_ID =LS_QUESTIONNAIRE_ID     
       AND QAH.module_sub_item_key = LS_PERSON_ID ; 
       
end;
