ALTER TABLE COI_DISCLOSURE CHANGE COLUMN EXPIRATION_DATE EXPIRATION_DATE DATETIME NULL DEFAULT NULL; 

ALTER TABLE COI_TRAVEL_DISCLOSURE CHANGE COLUMN EXPIRATION_DATE EXPIRATION_DATE DATETIME NULL DEFAULT NULL; 

ALTER TABLE OPA_DISCLOSURE CHANGE COLUMN EXPIRATION_DATE EXPIRATION_DATE DATETIME NULL DEFAULT NULL; 

ALTER TABLE CONSULTING_DISCLOSURE CHANGE COLUMN EXPIRATION_DATE EXPIRATION_DATE DATETIME NULL DEFAULT NULL; 
