DELIMITER //
CREATE PROCEDURE UPDT_OPA_ELIGIBILITY_FROM_FEED (
AV_PERSON_ID            VARCHAR(40)
)
BEGIN
DECLARE LI_OPA_PERSON_COUNT INT(10);
DECLARE LS_CAN_CREATE_OPA VARCHAR(1);
DECLARE LI_PERSON_DISCL_REQUIREMENT_ID INT;

    -- checking requirement details
    SELECT count(*) INTO LI_OPA_PERSON_COUNT FROM OPA_PERSON WHERE
        JOB_TITLE NOT IN('PER DIEM - MEDICAL', 'PER DIEM AUDIOLOGIST', 'PER DIEM MEDICAL DOCTOR', 'PER DIEM NURSE PRACTITIONER',
                         'PER DIEM PHARMACIST', 'PER DIEM REGISTERED NURSE', 'CLUB COACH', 'HOUSE MASTER', 'GRADUATE RESIDENT ADVISOR',
                         'ASSISTANT COACH', 'PER DIEM - MEDICAL', 'PER DIEM AUDIOLOGIST', 'PER DIEM MEDICAL DOCTOR',
                         'PER DIEM NURSE PRACTITIONER', 'PER DIEM PHARMACIST', 'PER DIEM REGISTERED NURSE', 'HOUSEMASTER',
                         'PER DIEM DENTAL HYGIENST', 'PER DIEM LICENSED PRACTICAL NURSE', 'PER DIEM RADIOLOGIC TECHNOLOGIST',
                         'PER DIEM PHARMACY INTERN', 'PER DIEM MEDICAL ASSISTANT', 'PER DIEM MAMMOGRAPHY TECHNOLOGIST', 'PER DIEM ALLERGIST',
                         'PER DIEM DENTIST', 'AFFILIATED ARTIST', 'STAFF AFFILIATE', 'RESEARCH AFFILIATE', 'PER DIEM DENTAL ASSISTANT')
        AND ADMIN_EMPLOYEE_TYPE NOT IN ('STUDENT', 'ADMIN STAFF','MIT INTL ADMIN STAFF', 'SPONSORED RESEARCH STAFF', 'MEDICAL', 'TECH REVIEW ADMIN STAFF')
        AND HR_DEPARTMENT_NAME NOT IN ('LINCOLN LAB', 'CONSORTIUM ON FINANCING HIGHER EDUCATION', 'CREDIT UNION', 'FORUM FOR THE FUTURE OF HIGHER EDUCATION',
                         'STUDENT', 'EDX', 'MA GREEN HIGH PERFORMANCE COMPUTING CTR', 'ROTC AIR FORCE', 'ROTC NAVY', 'ROTC ARMY')
        AND PERSONNEL_SUBAREA NOT IN ('ADMIN STAFF','OTHER-ADM STAFF', 'SPON RES-ADM', 'CAMPUS MEDICAL')
        AND IS_DISCLOSURE_REQUIRED = 'Y'
        AND PERSON_ID = AV_PERSON_ID;

    -- Preparing requirement flag
    IF (LI_OPA_PERSON_COUNT > 0) THEN
        SET LS_CAN_CREATE_OPA = 'Y';
    ELSE
        SET LS_CAN_CREATE_OPA = 'N';
    END IF;

    SELECT PERSON_DISCL_REQUIREMENT_ID INTO LI_PERSON_DISCL_REQUIREMENT_ID FROM PERSON_DISCL_REQUIREMENT WHERE PERSON_ID = AV_PERSON_ID AND VERSION_STATUS = 'ACTIVE';

    -- Updating the requirement status
    IF LI_PERSON_DISCL_REQUIREMENT_ID IS NOT NULL THEN
        INSERT INTO PERSON_DISCL_REQUIREMENT(CAN_CREATE_OPA, PERSON_ID, CREATE_TIMESTAMP, VERSION_STATUS, VERSION_NUMBER, UPDATE_TIMESTAMP, UPDATED_BY,
            CREATE_OPA_ADMIN_FORCE_ALLOWED, IS_EXEMPT_FROM_OPA, OPA_EXEMPT_FROM_DATE, OPA_EXEMPT_TO_DATE, OPA_EXEMPTION_REASON)
        SELECT LS_CAN_CREATE_OPA, AV_PERSON_ID, UTC_TIMESTAMP(), 'ACTIVE', VERSION_NUMBER + 1, UTC_TIMESTAMP(), 'System',
            CREATE_OPA_ADMIN_FORCE_ALLOWED, IS_EXEMPT_FROM_OPA, OPA_EXEMPT_FROM_DATE, OPA_EXEMPT_TO_DATE, OPA_EXEMPTION_REASON
            FROM PERSON_DISCL_REQUIREMENT
            WHERE PERSON_DISCL_REQUIREMENT_ID = LI_PERSON_DISCL_REQUIREMENT_ID;

        UPDATE PERSON_DISCL_REQUIREMENT SET VERSION_STATUS = 'ARCHIVE', UPDATE_TIMESTAMP = UTC_TIMESTAMP(), UPDATED_BY = 'System'
            WHERE PERSON_DISCL_REQUIREMENT_ID = LI_PERSON_DISCL_REQUIREMENT_ID;
    ELSE
        INSERT INTO PERSON_DISCL_REQUIREMENT(CAN_CREATE_OPA, PERSON_ID, CREATE_TIMESTAMP, VERSION_STATUS, VERSION_NUMBER, UPDATE_TIMESTAMP, UPDATED_BY)
            VALUES(LS_CAN_CREATE_OPA, AV_PERSON_ID, 'ACTIVE', 1, UTC_TIMESTAMP(), UTC_TIMESTAMP(), 'System');
    END IF;

    -- Deleting previously failed details if exists
    DELETE FROM OPA_PERSON_FEED_LOG_DETAILS WHERE PERSON_ID = AV_PERSON_ID;

END
//
