ALTER TABLE ENTITY_COMMENT 
ADD COLUMN UPDATE_TIMESTAMP TIMESTAMP NULL DEFAULT NULL AFTER PARENT_COMMENT_ID,
ADD COLUMN UPDATED_BY VARCHAR(60) NULL DEFAULT NULL AFTER UPDATE_TIMESTAMP;

ALTER TABLE entity_section_comment_ref 
ADD COLUMN ENTITY_NUMBER INT NULL AFTER ENTITY_ID;

ALTER TABLE entity_comment
ADD COLUMN ENTITY_NUMBER INT NULL AFTER ENTITY_ID;
