DELIMITER //
CREATE PROCEDURE `GET_DECLARATION_DASHBOARD_DYNAMIC_DATA`(
JSON_FORMAT JSON)
BEGIN
DECLARE LS_DYN_SQL      LONGTEXT DEFAULT '';
DECLARE LS_FILTER_CONDITION   LONGTEXT DEFAULT '';
DECLARE LS_OFFSET_CONDITION   VARCHAR(600) DEFAULT '';
DECLARE LS_OFFSET      INT;
DECLARE LS_DYN_CTE_SQL      LONGTEXT DEFAULT '';

DECLARE AV_TAB_TYPE              VARCHAR(30);
DECLARE AV_SORT_TYPE             VARCHAR(500);
DECLARE AV_LIMIT                 INT;
DECLARE AV_PAGED                 INT;
DECLARE AV_UNLIMITED             BOOLEAN;
DECLARE AV_TYPE                  VARCHAR(1);
DECLARE AV_SEARCH_PERSON         VARCHAR(90);
DECLARE AV_DEPARTMENT     VARCHAR(40);
DECLARE AV_DECLARATION_STATUS   VARCHAR(10);
DECLARE AV_DECLARATION_TYPE   VARCHAR(10);
DECLARE AV_SUBMISSION_DATE    DATE;
DECLARE AV_EXPIRATION_DATE    DATE;
DECLARE AV_EXPORT_TYPE     VARCHAR(10);
DECLARE AV_DOCUMENT_HEADING   VARCHAR(255);
DECLARE AV_FREE_TEXT_SEARCH_FIELDS  VARCHAR(500);
DECLARE AV_VERSION_STATUS   VARCHAR(5);
DECLARE AV_COUNT     BOOLEAN;
DECLARE AV_LOGIN_PERSON_ID    VARCHAR(40);
DECLARE AV_DASHBOARD_TYPE   VARCHAR(1);
DECLARE LS_SELECTED_FIELD_LIST   LONGTEXT;
DECLARE AV_REVIEW_STATUS   VARCHAR(50);
DECLARE AV_ADMINISTRATOR    TEXT;
DECLARE LS_VERSION_STATUS_CONDITION   LONGTEXT DEFAULT '';

SET AV_SEARCH_PERSON = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.PERSON'));
SET AV_SORT_TYPE = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.SORT_TYPE'));
SET AV_DEPARTMENT = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.DEPARTMENT'));
SET AV_DECLARATION_STATUS = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.DECLARATION_STATUS'));
SET AV_DECLARATION_TYPE = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.DECLARATION_TYPE'));
SET AV_SUBMISSION_DATE = STR_TO_DATE(JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.SUBMISSION_DATE')), '%Y-%m-%d');
SET AV_EXPIRATION_DATE = STR_TO_DATE(JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.EXPIRATION_DATE')), '%Y-%m-%d');
SET AV_TAB_TYPE = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.TAB_TYPE'));
SET AV_EXPORT_TYPE = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.EXPORT_TYPE'));
SET AV_DOCUMENT_HEADING = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.DOCUMENT_HEADING'));
SET AV_LIMIT = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.LIMIT'));
SET AV_PAGED = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.PAGED'));
SET AV_UNLIMITED  = JSON_EXTRACT(JSON_FORMAT,'$.UNLIMITED');
SET AV_TYPE = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.TYPE'));
SET AV_FREE_TEXT_SEARCH_FIELDS = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.FREE_TEXT_SEARCH_FIELDS'));
SET AV_VERSION_STATUS = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.VERSION_STATUS'));
SET AV_COUNT  = JSON_EXTRACT(JSON_FORMAT,'$.COUNT');
SET AV_DASHBOARD_TYPE  = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.DASHBOARD_TYPE'));
SET AV_LOGIN_PERSON_ID = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT, '$.LOGIN_PERSON_ID'));
SET AV_REVIEW_STATUS = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.REVIEW_STATUS_CODE'));
SET AV_ADMINISTRATOR = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT,'$.ADMINISTRATOR'));

SET LS_VERSION_STATUS_CONDITION = ' T.VERSION_STATUS IN (''ACTIVE'', ''PENDING'') ';

SET LS_FILTER_CONDITION ='';
SET LS_DYN_SQL ='';

IF AV_TYPE = 'A' THEN

 IF AV_SEARCH_PERSON IS NOT NULL AND AV_SEARCH_PERSON <> '' THEN
  IF FIND_IN_SET('PERSON', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
            IF INSTR(AV_SEARCH_PERSON, '*') > 0 THEN
                SET AV_SEARCH_PERSON = REPLACE(AV_SEARCH_PERSON, '*', '%');
            ELSE
                SET AV_SEARCH_PERSON = CONCAT('%', AV_SEARCH_PERSON, '%');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T.PERSON_FULL_NAME LIKE ''', AV_SEARCH_PERSON, 
         ''' OR T.PERSON_ID LIKE ''', AV_SEARCH_PERSON, ''') ');
  ELSE
   SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T.PERSON_ID = ', AV_SEARCH_PERSON);
 	if AV_LOGIN_PERSON_ID is null then 
 		set AV_LOGIN_PERSON_ID = AV_SEARCH_PERSON;
 	end if;
  END IF;
 END IF;
 

    IF AV_DEPARTMENT IS NOT NULL AND AV_DEPARTMENT <> '' THEN
        IF FIND_IN_SET('DEPARTMENT', AV_FREE_TEXT_SEARCH_FIELDS) > 0 THEN
            IF INSTR(AV_DEPARTMENT, '*') > 0 THEN
                SET AV_DEPARTMENT = REPLACE(AV_DEPARTMENT, '*', '%');
            ELSE
                SET AV_DEPARTMENT = CONCAT('%', AV_DEPARTMENT, '%');
            END IF;
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T.HOME_UNIT_NAME LIKE ''', AV_DEPARTMENT, 
         ''' OR T.HOME_UNIT_NUMBER LIKE ''', AV_DEPARTMENT, ''') ');
        ELSE
           SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T.HOME_UNIT_NUMBER = ', AV_DEPARTMENT);
        END IF;
    END IF;
    
IF AV_DECLARATION_STATUS IS NOT NULL AND AV_DECLARATION_STATUS <> '' THEN
    SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T.DECLARATION_STATUS_CODE IN (''', REPLACE(AV_DECLARATION_STATUS,',',''','''),''')');
    IF FIND_IN_SET('4', AV_DECLARATION_STATUS) > 0 THEN
        SET LS_VERSION_STATUS_CONDITION = ' T.VERSION_STATUS = ''ARCHIVE'' ';
    END IF;
END IF;

IF AV_REVIEW_STATUS IS NOT NULL AND AV_REVIEW_STATUS <> '' THEN
    SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T.REVIEW_STATUS_CODE IN (''', REPLACE(AV_REVIEW_STATUS,',',''','''),''')');
END IF;

IF AV_ADMINISTRATOR IS NOT NULL AND AV_ADMINISTRATOR <> '' THEN
    SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T.ADMIN_PERSON_ID IN (''', REPLACE(AV_ADMINISTRATOR,',',''','''),''')');
END IF;

 IF AV_DECLARATION_TYPE IS NOT NULL AND AV_DECLARATION_TYPE <> '' THEN
  SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T.DECLARATION_TYPE_CODE IN (''', REPLACE(AV_DECLARATION_TYPE,',',''','''),''')');
 END IF;
    
    IF AV_SUBMISSION_DATE IS NOT NULL THEN
  SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T.SUBMISSION_DATE = ''', AV_SUBMISSION_DATE,'''');
 END IF;
    
    IF AV_EXPIRATION_DATE IS NOT NULL THEN
  SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T.EXPIRATION_DATE = ''', AV_EXPIRATION_DATE,'''');
 END IF;

END IF;

IF AV_SORT_TYPE IS NOT NULL THEN
 SET AV_SORT_TYPE = CONCAT(' ORDER BY ', AV_SORT_TYPE);
ELSE
 SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
END IF;

IF AV_DASHBOARD_TYPE = 'A' THEN
    IF AV_TAB_TYPE = "ALL_DECLARATIONS" THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T.HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS) 
																	OR EXISTS (
																	SELECT 1
																	FROM PERSON_AFFILIATED_UNITS PAU
																	WHERE PAU.PERSON_ID = T.PERSON_ID
																	  AND PAU.AFFILIATION_TYPE_CODE = ''1''
																	  AND PAU.IS_ACTIVE = ''Y''
																	  AND PAU.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS)
																)
                    OR T.ADMIN_PERSON_ID = ''',AV_LOGIN_PERSON_ID,''' OR T.PERSON_ID = ''',AV_LOGIN_PERSON_ID,''')');
    ELSEIF AV_TAB_TYPE = "NEW_SUBMISSIONS" THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T.HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS)
																	OR EXISTS (
																	SELECT 1
																	FROM PERSON_AFFILIATED_UNITS PAU
																	WHERE PAU.PERSON_ID = T.PERSON_ID
																	  AND PAU.AFFILIATION_TYPE_CODE = ''1''
																	  AND PAU.IS_ACTIVE = ''Y''
																	  AND PAU.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS)
																) )
                    AND T.VERSION_STATUS = ''PENDING'' AND T.REVIEW_STATUS_CODE = 2 ');
    ELSEIF AV_TAB_TYPE = 'ALL_REVIEWS' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T.REVIEW_STATUS_CODE IN (3,6) AND T.ADMIN_PERSON_ID = ''',AV_LOGIN_PERSON_ID,''') ');
    ELSEIF AV_TAB_TYPE = 'MY_REVIEWS' THEN
            SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T.REVIEW_STATUS_CODE IN (3) AND T.ADMIN_PERSON_ID = ''',AV_LOGIN_PERSON_ID,''') ');
    END IF;

END IF;

IF AV_VERSION_STATUS IS NOT NULL AND AV_VERSION_STATUS = 'ALL' THEN
    SET LS_VERSION_STATUS_CONDITION = ' (T.VERSION_STATUS IN (''ACTIVE'', ''PENDING'') OR (T.DECLARATION_STATUS_CODE = 4 AND T.VERSION_STATUS = ''ARCHIVE'')) ';
END IF;

IF AV_COUNT then
	SET LS_SELECTED_FIELD_LIST = ' COUNT(T.DECLARATION_ID) AS TOTAL ';
ELSE
	SET LS_SELECTED_FIELD_LIST = CONCAT(' T.DECLARATION_ID, T.DECLARATION_NUMBER, T.PERSON_ID, T.PERSON_FULL_NAME, T.HOME_UNIT_NUMBER, T.HOME_UNIT_NAME,
                        T.DECLARATION_TYPE, T.DECLARATION_STATUS, T.SUBMISSION_DATE, T.EXPIRATION_DATE, T.UPDATE_TIMESTAMP, T.UPDATE_USER_FULL_NAME, 
                        T.BADGE_COLOR, T.DECLARATION_TYPE_CODE, T.DECLARATION_STATUS_CODE, T.VERSION_STATUS, T.ADMIN_PERSON_ID, T.ADMINISTRATOR,
                        T.ADMIN_GROUP_ID, T.ADMIN_GROUP_NAME, T.REVIEW_STATUS_CODE, T.REVIEW_STATUS, T.VERSION_NUMBER, T.UNIT_ACCESS_TYPE,
						(T.PERSON_ID =  ''',AV_LOGIN_PERSON_ID,''' OR T.HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS)) AS IS_VIEW_ALLOWED ');
END IF;

SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,' SELECT ', LS_SELECTED_FIELD_LIST,'
      FROM (SELECT
      CD.DECLARATION_ID,
                        CD.DECLARATION_NUMBER,
                        CD.PERSON_ID,
                        P.FULL_NAME AS PERSON_FULL_NAME,
                        P.HOME_UNIT AS HOME_UNIT_NUMBER,
                        U.UNIT_NAME AS HOME_UNIT_NAME,
                        CD.DECLARATION_TYPE_CODE,
                        CDT.BADGE_COLOR,
                        CDT.DESCRIPTION AS DECLARATION_TYPE,
                        CD.DECLARATION_STATUS_CODE,
                        CDS.DESCRIPTION AS DECLARATION_STATUS,
                        CD.SUBMISSION_DATE,
                        CD.EXPIRATION_DATE,
                        CD.UPDATE_TIMESTAMP,
                        P1.FULL_NAME AS UPDATE_USER_FULL_NAME,
                        CD.VERSION_STATUS,
                        CD.ADMIN_PERSON_ID,
                        AP.FULL_NAME AS ADMINISTRATOR,
                        CD.ADMIN_GROUP_ID,
                        AG.ADMIN_GROUP_NAME,
                        CD.REVIEW_STATUS_CODE,
                        R.DESCRIPTION AS REVIEW_STATUS,
                        CD.VERSION_NUMBER,
                        CASE 
						WHEN P.HOME_UNIT IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS) 
							 THEN ''HOME_UNIT''
						WHEN EXISTS (
							SELECT 1
							FROM PERSON_AFFILIATED_UNITS PAU
							WHERE PAU.PERSON_ID = CD.PERSON_ID
							  AND PAU.AFFILIATION_TYPE_CODE = ''1''
							  AND PAU.IS_ACTIVE = ''Y''
							  AND PAU.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS)
						) THEN ''AFFILIATED_UNIT''
					END AS UNIT_ACCESS_TYPE
      FROM COI_DECLARATION CD
                        LEFT JOIN PERSON P ON P.PERSON_ID = CD.PERSON_ID
                        LEFT JOIN PERSON P1 ON P1.PERSON_ID = CD.UPDATED_BY
                        LEFT JOIN UNIT U ON U.UNIT_NUMBER = P.HOME_UNIT
                        LEFT JOIN DECLARATION_REVIEW_STATUS_TYPE R ON R.REVIEW_STATUS_CODE = CD.REVIEW_STATUS_CODE
                        LEFT JOIN ADMIN_GROUP AG ON AG.ADMIN_GROUP_ID = CD.ADMIN_GROUP_ID
                        LEFT JOIN PERSON AP ON AP.PERSON_ID = CD.ADMIN_PERSON_ID
                        INNER JOIN COI_DECLARATION_TYPE CDT 
       ON CDT.DECLARATION_TYPE_CODE = CD.DECLARATION_TYPE_CODE AND CDT.IS_ACTIVE = ''Y''
                        INNER JOIN COI_DECLARATION_STATUS CDS 
       ON CDS.DECLARATION_STATUS_CODE = CD.DECLARATION_STATUS_CODE AND CDS.IS_ACTIVE = ''Y'') T
                        WHERE ', LS_VERSION_STATUS_CONDITION ,LS_FILTER_CONDITION);


SET LS_DYN_CTE_SQL = CONCAT('WITH ACCESS AS
           (
           SELECT UNIT_NUMBER
           FROM PERSON_ROLES T1
           INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
           INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
           WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
           AND RIGHT_NAME IN (''VIEW_MFTRP_DECLARATION'', ''MANAGE_MFTRP_DECLARATION'')
           UNION
           SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
           WHERE UNIT_NUMBER IN (
           SELECT UNIT_NUMBER
           FROM PERSON_ROLES T1
           INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
           INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
           WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
           AND RIGHT_NAME IN (''VIEW_MFTRP_DECLARATION'', ''MANAGE_MFTRP_DECLARATION'')
           ))');

IF AV_UNLIMITED IS NULL THEN
    SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
 SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
END IF;

IF AV_COUNT THEN
 SET LS_DYN_SQL = CONCAT(LS_DYN_CTE_SQL, LS_DYN_SQL);
else
 SET LS_DYN_SQL = CONCAT(LS_DYN_CTE_SQL, LS_DYN_SQL, AV_SORT_TYPE, LS_OFFSET_CONDITION);
END IF;

SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;

END
//
