DELIMITER //
CREATE PROCEDURE `GET_REVIEWER_UNIT_HIERARCHY`(
    AV_PERSON_ID VARCHAR(40),
    AV_SEARCH_KEYWORD VARCHAR(500)
)
BEGIN

    DECLARE LS_DYN_CTE_SQL          LONGTEXT;
    DECLARE LS_DYN_SQL              LONGTEXT;

    SET LS_DYN_CTE_SQL = CONCAT('
        WITH UNIT_ACCESS_TMP AS (SELECT UNIT_NUMBER,UNIT_NAME,PARENT_UNIT_NUMBER, DISPLAY_NAME, IS_ACTIVE,1 AS LVL
            FROM UNIT WHERE PARENT_UNIT_NUMBER is null
            UNION ALL
            SELECT UNIT_NUMBER,UNIT_NAME,PARENT_UNIT_NUMBER, DISPLAY_NAME, IS_ACTIVE,FN_GET_UNIT_HIERARCHY_LEVEL(UNIT_NUMBER) AS LVL
            FROM UNIT
            WHERE PARENT_UNIT_NUMBER is not null
            order by LVL,PARENT_UNIT_NUMBER,UNIT_NUMBER),
        FCOI_ACCESS_TMP AS ( SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            AND RIGHT_NAME IN (''MANAGE_FCOI_DISCLOSURE'', ''VIEW_FCOI_DISCLOSURE'')
            UNION
               SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_COI'')
            UNION
            SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN (
            SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_COI'')
            )
            UNION
               SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN ( SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            AND RIGHT_NAME IN (''MANAGE_FCOI_DISCLOSURE'', ''VIEW_FCOI_DISCLOSURE'')
               )),
            PROJECT_ACCESS_TMP AS
            ( SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            AND RIGHT_NAME IN (''MANAGE_PROJECT_DISCLOSURE'', ''VIEW_PROJECT_DISCLOSURE'')
            UNION
               SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_COI'')
            UNION
            SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN (
            SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_COI'')
            )
            UNION
               SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN (
            SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            AND RIGHT_NAME IN (''MANAGE_PROJECT_DISCLOSURE'', ''VIEW_PROJECT_DISCLOSURE''))),
        OPA_ACCESS_TMP AS ( SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            AND RIGHT_NAME IN (''MANAGE_OPA_DISCLOSURE'', ''VIEW_OPA_DISCLOSURE'')
            UNION
            SELECT T1.UNIT_NUMBER FROM PERSON_ROLES T1
            INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID
            WHERE T2.MODULE_CODE=23 AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
            UNION
            SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN ( SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''MANAGE_OPA_DISCLOSURE'', ''VIEW_OPA_DISCLOSURE'')
                )
        ),
        TRAVEL_ACCESS_TMP AS (
            SELECT UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
            INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
            WHERE T1.DESCEND_FLAG = ''N''
              AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
              AND T3.RIGHT_NAME IN (''MANAGE_TRAVEL_DISCLOSURE'', ''VIEW_TRAVEL_DISCLOSURE'')
            UNION
            SELECT T1.UNIT_NUMBER
            FROM PERSON_ROLES T1
            INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID
            WHERE T2.MODULE_CODE = 24 AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
            UNION
            SELECT CHILD_UNIT_NUMBER
            FROM UNIT_WITH_CHILDREN
            WHERE UNIT_NUMBER IN (
                SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y''
                  AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                  AND T3.RIGHT_NAME IN (''MANAGE_TRAVEL_DISCLOSURE'', ''VIEW_TRAVEL_DISCLOSURE'')
            )
        )');

    SET LS_DYN_SQL = CONCAT(LS_DYN_CTE_SQL, '
        SELECT DISTINCT U.UNIT_NUMBER, U.UNIT_NAME, U.PARENT_UNIT_NUMBER, U.DISPLAY_NAME, U.LVL
        FROM UNIT_ACCESS_TMP U
        LEFT JOIN OPA_DISCLOSURE T1 ON T1.HOME_UNIT = U.UNIT_NUMBER
        LEFT JOIN OPA_REVIEW T8 ON T8.OPA_DISCLOSURE_ID = T1.OPA_DISCLOSURE_ID
        LEFT JOIN COI_DISCLOSURE T2 ON T2.HOME_UNIT = U.UNIT_NUMBER
        LEFT JOIN COI_REVIEW T9 ON T9.DISCLOSURE_ID = T2.DISCLOSURE_ID
        LEFT JOIN COI_TRAVEL_DISCLOSURE T3 ON T3.HOME_UNIT = U.UNIT_NUMBER
        WHERE (U.UNIT_NUMBER IN (
                SELECT UNIT_NUMBER FROM FCOI_ACCESS_TMP
                UNION
                SELECT UNIT_NUMBER FROM PROJECT_ACCESS_TMP
                UNION
                SELECT UNIT_NUMBER FROM OPA_ACCESS_TMP
                UNION
                SELECT UNIT_NUMBER FROM TRAVEL_ACCESS_TMP
            )
            OR (T1.VERSION_STATUS != ''ARCHIVE'' AND  (
                    (T8.ASSIGNEE_PERSON_ID = ''', AV_PERSON_ID ,'''AND T8.REVIEW_STATUS_TYPE_CODE IN (1,2))
                    OR (T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID ,''')
                    OR exists  (SELECT 1 FROM WORKFLOW WF
                           INNER JOIN WORKFLOW_DETAIL WFD ON WF.WORKFLOW_ID = WFD.WORKFLOW_ID
                           WHERE WF.MODULE_ITEM_ID = T1.OPA_DISCLOSURE_ID
                           AND WFD.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                           AND WF.MODULE_CODE = 23 AND WF.IS_WORKFLOW_ACTIVE = ''Y''
                           AND WFD.APPROVAL_STATUS = ''W''
                    )
            ))
            OR (T2.VERSION_STATUS != ''ARCHIVE'' AND (
                   (T9.ASSIGNEE_PERSON_ID = ''', AV_PERSON_ID ,''' AND T9.REVIEW_STATUS_TYPE_CODE IN (1,2))
                   OR T2.ADMIN_PERSON_ID = ''', AV_PERSON_ID ,'''
                   OR exists  (SELECT 1 FROM WORKFLOW WF
                       INNER JOIN WORKFLOW_DETAIL WFD ON WF.WORKFLOW_ID = WFD.WORKFLOW_ID
                       WHERE WF.MODULE_ITEM_ID = T2.DISCLOSURE_ID
                       AND WFD.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                       AND WF.MODULE_CODE = 8 AND WF.IS_WORKFLOW_ACTIVE = ''Y''
                       AND WFD.APPROVAL_STATUS = ''W'' )
                   )
            )
            OR (T3.ADMIN_PERSON_ID = ''', AV_PERSON_ID, ''')
        )');
    IF AV_SEARCH_KEYWORD IS NOT NULL AND AV_SEARCH_KEYWORD <> '' THEN
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ' AND (U.UNIT_NUMBER LIKE ''%', AV_SEARCH_KEYWORD, '%'' OR U.UNIT_NAME LIKE ''%', AV_SEARCH_KEYWORD, '%'') ');
    END IF;

    SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ' LIMIT 50');

    SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STAEMENT;
END
//
