DELIMITER //
CREATE PROCEDURE `REVIEWER_DEPARTMENT_DASH_OVERVIEW`(
    AV_PERSON_ID  VARCHAR(40),
    JSON_INPUT         JSON
)
BEGIN

    DECLARE AV_MODULE_CODE                  VARCHAR(200);
    DECLARE LS_DYN_SQL                      LONGTEXT;
    DECLARE JSON_STRING                     LONGTEXT;
    DECLARE AV_FETCH_TYPE                   VARCHAR(50);
    DECLARE AV_HOME_UNIT                    VARCHAR(500);
    DECLARE LS_DYN_CTE_SQL                  LONGTEXT;
    DECLARE LS_OFFSET_CONDITION             VARCHAR(600) DEFAULT '';
    DECLARE LS_JOIN_CONDITION               VARCHAR(600) DEFAULT '';
    DECLARE LS_OFFSET                       INT;
    DECLARE AV_IS_COUNT                     BOOLEAN;
    DECLARE AV_LIMIT                        INT;
    DECLARE AV_PAGED                        INT;
    DECLARE AV_UNLIMITED                    BOOLEAN;
    DECLARE SELECTED_FIELD_LIST             LONGTEXT DEFAULT '';
    DECLARE LS_GROUP_CONDITION              LONGTEXT;
    DECLARE LS_FILTER_CONDITION LONGTEXT    DEFAULT '';
    DECLARE LI_HAS_USER_PREFERENCE          BOOLEAN;
    DECLARE LI_IS_WIDGET_SELECTED           BOOLEAN;
    DECLARE LI_WIDGET_ORDER_NUMBER          BOOLEAN;
    DECLARE LI_IS_WIDGET_ACTIVE             BOOLEAN;
    DECLARE LI_HAS_PRE_UNIT_CONDITION       BOOLEAN DEFAULT FALSE;
    DECLARE LS_UNIT_FILTER_CONDITION        VARCHAR(600) DEFAULT '';

    -- Convert JSON to text for validation
    SET JSON_STRING = CAST(JSON_INPUT AS CHAR);

    -- Convert JSON to lowercase text
    SET @js_lower = LOWER(CAST(JSON_INPUT AS CHAR));

    -- Block obvious SQL injection patterns
    IF @js_lower REGEXP '(;|--|/\\*|\\*/|#)' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'SQL Injection detected: comment or operator';
    END IF;

    -- Block dangerous SQL keywords as standalone words only
    IF @js_lower REGEXP '(^|[^a-z0-9_])(drop|insert|delete|alter|create|exec|union|grant|revoke|truncate|update |select )' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'SQL Injection detected: SQL keyword found';
    END IF;

    SET AV_MODULE_CODE      = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.MODULE_CODE'));
    SET AV_FETCH_TYPE       = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.FETCH_TYPE'));
    SET AV_HOME_UNIT        = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT, '$.HOME_UNIT'));
    SET AV_LIMIT            = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT,'$.LIMIT'));
    SET AV_PAGED            = JSON_UNQUOTE(JSON_EXTRACT(JSON_INPUT,'$.PAGED'));
    SET AV_UNLIMITED        = JSON_EXTRACT(JSON_INPUT,'$.UNLIMITED');
    SET AV_IS_COUNT         = JSON_EXTRACT(JSON_INPUT,'$.IS_COUNT');

    IF AV_HOME_UNIT IS NOT NULL AND AV_HOME_UNIT <> '' THEN
        SET AV_HOME_UNIT = CONCAT('%', AV_HOME_UNIT, '%');
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (U.DISPLAY_NAME LIKE ''', AV_HOME_UNIT, ''') ');
    END IF;

    SELECT CASE WHEN COUNT(*) > 0 THEN TRUE ELSE FALSE END AS HAS_USER_PREFERENCE INTO LI_HAS_USER_PREFERENCE FROM USER_SELECTED_WIDGET
                WHERE PERSON_ID = AV_PERSON_ID AND WIDGET_ID IN ('8001', '8002', '8003');

    IF LI_HAS_USER_PREFERENCE IS NOT NULL AND LI_HAS_USER_PREFERENCE = FALSE THEN
        INSERT INTO USER_SELECTED_WIDGET (WIDGET_ID, SORT_ORDER, PERSON_ID, UPDATE_TIMESTAMP, UPDATE_USER)
        VALUES
        ('8001', 1, AV_PERSON_ID, NOW(), 'system'),
        ('8002', 2, AV_PERSON_ID, NOW(), 'system'),
        ('8003', 3, AV_PERSON_ID, NOW(), 'system');
        commit;
    END IF;

    SET LS_DYN_CTE_SQL = CONCAT('
        WITH UNIT_ACCESS_TMP AS (SELECT UNIT_NUMBER,UNIT_NAME,PARENT_UNIT_NUMBER, DISPLAY_NAME, IS_ACTIVE,1 AS LVL
            FROM UNIT WHERE PARENT_UNIT_NUMBER is null
            UNION ALL
            SELECT UNIT_NUMBER,UNIT_NAME,PARENT_UNIT_NUMBER, DISPLAY_NAME, IS_ACTIVE,FN_GET_UNIT_HIERARCHY_LEVEL(UNIT_NUMBER) AS LVL
            FROM UNIT
            WHERE PARENT_UNIT_NUMBER is not null
            order by LVL,PARENT_UNIT_NUMBER,UNIT_NUMBER)
    ');

    SELECT CASE WHEN COUNT(t1.WIDGET_ID) > 0 THEN TRUE ELSE FALSE END AS HAS_USER_PREFERENCE,
               CASE WHEN t1.SORT_ORDER IS NULL THEN 1 ELSE t1.SORT_ORDER END AS SORT_ORDER,
               (SELECT CASE WHEN IS_ACTIVE = 'Y' THEN TRUE ELSE FALSE END FROM WIDGET_LOOKUP WHERE WIDGET_ID = '8001') AS IS_ACTIVE
                INTO LI_IS_WIDGET_SELECTED, LI_WIDGET_ORDER_NUMBER, LI_IS_WIDGET_ACTIVE
                FROM USER_SELECTED_WIDGET t1
            WHERE t1.PERSON_ID = AV_PERSON_ID AND t1.WIDGET_ID = '8001';

    IF LI_IS_WIDGET_ACTIVE = TRUE AND (LI_IS_WIDGET_SELECTED = TRUE OR LI_HAS_USER_PREFERENCE = FALSE) THEN

        SET LI_HAS_PRE_UNIT_CONDITION = TRUE;

        SET SELECTED_FIELD_LIST = CONCAT(SELECTED_FIELD_LIST,
            'JSON_OBJECT(''LABEL'', ''Review Pending FCOI'', ''COUNT'', COUNT(DISTINCT CASE WHEN T1.REVIEW_STATUS_CODE IN (2,3,7,8,9) THEN T1.DISCLOSURE_ID END),
            ''MODULE_CODE'', 8, ''UNIQUE_ID'', ''FCOI_REVIEW_PENDING'', ''ORDER_NUMBER'', ',LI_WIDGET_ORDER_NUMBER,', ''SHOW_IN_HEADER'', true, ''MODULE_NAME'', ''FCOI Disclosure''), ');

        SET LS_JOIN_CONDITION = CONCAT(LS_JOIN_CONDITION, '
            LEFT JOIN FCOI_ACCESS_TMP T1 ON T1.HOME_UNIT = U.UNIT_NUMBER
        ');

        SET LS_UNIT_FILTER_CONDITION = CONCAT(LS_UNIT_FILTER_CONDITION, '
            U.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM FCOI_RIGHT_ACCESS_TMP)
            OR U.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PROJECT_ACCESS_TMP)
            OR U.UNIT_NUMBER IN (SELECT HOME_UNIT FROM FCOI_ACCESS_TMP)
        ');

        SET LS_DYN_CTE_SQL = CONCAT(LS_DYN_CTE_SQL,',
            FCOI_RIGHT_ACCESS_TMP AS ( SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''MANAGE_FCOI_DISCLOSURE'', ''VIEW_FCOI_DISCLOSURE'')
                UNION
                   SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_COI'')
                UNION
                SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
                WHERE UNIT_NUMBER IN (
                SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_COI'')
                )
                UNION
                   SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
                WHERE UNIT_NUMBER IN ( SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''MANAGE_FCOI_DISCLOSURE'', ''VIEW_FCOI_DISCLOSURE'')
                   )),
            PROJECT_ACCESS_TMP AS
                ( SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''MANAGE_PROJECT_DISCLOSURE'', ''VIEW_PROJECT_DISCLOSURE'')
                UNION
                   SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_COI'')
                UNION
                SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
                WHERE UNIT_NUMBER IN (
                SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_COI'')
                )
                UNION
                   SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
                WHERE UNIT_NUMBER IN (
                SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''MANAGE_PROJECT_DISCLOSURE'', ''VIEW_PROJECT_DISCLOSURE''))),
            FCOI_ACCESS_TMP AS ( SELECT T1.* FROM COI_DISCLOSURE T1
                LEFT JOIN COI_REVIEW T2 ON T2.DISCLOSURE_ID = T1.DISCLOSURE_ID
                WHERE T1.HOME_UNIT IN (SELECT UNIT_NUMBER FROM FCOI_RIGHT_ACCESS_TMP)
                    OR (T2.ASSIGNEE_PERSON_ID = ''', AV_PERSON_ID, ''' AND T2.REVIEW_STATUS_TYPE_CODE IN (1,2))
                    OR T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID ,'''
                    OR exists  (SELECT 1 FROM WORKFLOW WF
                        INNER JOIN WORKFLOW_DETAIL WFD ON WF.WORKFLOW_ID = WFD.WORKFLOW_ID
                        WHERE WF.MODULE_ITEM_ID = T1.DISCLOSURE_ID
                        AND WFD.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                        AND WF.MODULE_CODE = 8 AND WF.IS_WORKFLOW_ACTIVE = ''Y''
                        AND WFD.APPROVAL_STATUS = ''W''
                    )
            )
        ');
    END IF;

    SELECT CASE WHEN COUNT(t1.WIDGET_ID) > 0 THEN TRUE ELSE FALSE END AS HAS_USER_PREFERENCE,
               CASE WHEN t1.SORT_ORDER IS NULL THEN 1 ELSE t1.SORT_ORDER END AS SORT_ORDER,
               (SELECT CASE WHEN IS_ACTIVE = 'Y' THEN TRUE ELSE FALSE END FROM WIDGET_LOOKUP WHERE WIDGET_ID = '8002') AS IS_ACTIVE
                INTO LI_IS_WIDGET_SELECTED, LI_WIDGET_ORDER_NUMBER, LI_IS_WIDGET_ACTIVE
                FROM USER_SELECTED_WIDGET t1
            WHERE t1.PERSON_ID = AV_PERSON_ID AND t1.WIDGET_ID = '8002';

    IF LI_IS_WIDGET_ACTIVE = TRUE AND (LI_IS_WIDGET_SELECTED = TRUE OR LI_HAS_USER_PREFERENCE = FALSE) THEN

        SET SELECTED_FIELD_LIST = CONCAT(SELECTED_FIELD_LIST,
            'JSON_OBJECT(''LABEL'', ''Review Pending OPA'', ''COUNT'', COUNT(DISTINCT CASE WHEN T2.REVIEW_STATUS_CODE IN (2,3,7,8,9) THEN T2.OPA_DISCLOSURE_ID END),
            ''MODULE_CODE'', 23, ''UNIQUE_ID'', ''OPA_REVIEW_PENDING'', ''ORDER_NUMBER'', ',LI_WIDGET_ORDER_NUMBER,', ''SHOW_IN_HEADER'', true, ''MODULE_NAME'', ''OPA Disclosure''), ');

        SET LS_JOIN_CONDITION = CONCAT(LS_JOIN_CONDITION, '
            LEFT JOIN OPA_ACCESS_TMP T2 ON T2.HOME_UNIT = U.UNIT_NUMBER
        ');

        IF LI_HAS_PRE_UNIT_CONDITION = TRUE THEN
            SET LS_UNIT_FILTER_CONDITION = CONCAT(LS_UNIT_FILTER_CONDITION, ' OR ');
        END IF;
        SET LI_HAS_PRE_UNIT_CONDITION = TRUE;

        SET LS_UNIT_FILTER_CONDITION = CONCAT(LS_UNIT_FILTER_CONDITION, '
            U.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM OPA_RIGHT_ACCESS_TMP)
            OR U.UNIT_NUMBER IN (SELECT HOME_UNIT FROM OPA_ACCESS_TMP)
        ');

        SET LS_DYN_CTE_SQL = CONCAT(LS_DYN_CTE_SQL,',
            OPA_RIGHT_ACCESS_TMP AS ( SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                AND RIGHT_NAME IN (''MANAGE_OPA_DISCLOSURE'', ''VIEW_OPA_DISCLOSURE'')
                UNION
                SELECT T1.UNIT_NUMBER FROM PERSON_ROLES T1
                INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID
                WHERE T2.MODULE_CODE=23 AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                UNION
                SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
                WHERE UNIT_NUMBER IN ( SELECT UNIT_NUMBER
                    FROM PERSON_ROLES T1
                    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                    INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                    WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
                    AND RIGHT_NAME IN (''MANAGE_OPA_DISCLOSURE'', ''VIEW_OPA_DISCLOSURE'')
                    )
            ),
            OPA_ACCESS_TMP AS ( SELECT T1.* FROM OPA_DISCLOSURE T1
                LEFT JOIN OPA_REVIEW T2 ON T2.OPA_DISCLOSURE_ID = T1.OPA_DISCLOSURE_ID
                WHERE T1.VERSION_STATUS != ''ARCHIVE'' AND T1.HOME_UNIT IN (SELECT UNIT_NUMBER FROM OPA_RIGHT_ACCESS_TMP)
                    OR (T2.ASSIGNEE_PERSON_ID = ''', AV_PERSON_ID, ''' AND T2.REVIEW_STATUS_TYPE_CODE IN (1,2))
                    OR T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID ,'''
                    OR exists  (SELECT 1 FROM WORKFLOW WF
                        INNER JOIN WORKFLOW_DETAIL WFD ON WF.WORKFLOW_ID = WFD.WORKFLOW_ID
                        WHERE WF.MODULE_ITEM_ID = T1.OPA_DISCLOSURE_ID
                        AND WFD.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                        AND WF.MODULE_CODE = 23 AND WF.IS_WORKFLOW_ACTIVE = ''Y''
                        AND WFD.APPROVAL_STATUS = ''W''
                    )
            )
        ');
    END IF;

    SELECT CASE WHEN COUNT(t1.WIDGET_ID) > 0 THEN TRUE ELSE FALSE END AS HAS_USER_PREFERENCE,
               CASE WHEN t1.SORT_ORDER IS NULL THEN 1 ELSE t1.SORT_ORDER END AS SORT_ORDER,
               (SELECT CASE WHEN IS_ACTIVE = 'Y' THEN TRUE ELSE FALSE END FROM WIDGET_LOOKUP WHERE WIDGET_ID = '8003') AS IS_ACTIVE
                INTO LI_IS_WIDGET_SELECTED, LI_WIDGET_ORDER_NUMBER, LI_IS_WIDGET_ACTIVE
                FROM USER_SELECTED_WIDGET t1
            WHERE t1.PERSON_ID = AV_PERSON_ID AND t1.WIDGET_ID = '8003';

    IF LI_IS_WIDGET_ACTIVE = TRUE AND (LI_IS_WIDGET_SELECTED = TRUE OR LI_HAS_USER_PREFERENCE = FALSE) THEN

        SET SELECTED_FIELD_LIST = CONCAT(SELECTED_FIELD_LIST,
            'JSON_OBJECT(''LABEL'', ''Review Pending Travel'', ''COUNT'', COUNT(DISTINCT CASE WHEN T3.REVIEW_STATUS_CODE IN (2,3) THEN T3.TRAVEL_DISCLOSURE_ID END),
            ''MODULE_CODE'', 24, ''UNIQUE_ID'', ''TRAVEL_REVIEW_PENDING'', ''ORDER_NUMBER'', ',LI_WIDGET_ORDER_NUMBER,', ''SHOW_IN_HEADER'', true, ''MODULE_NAME'', ''Travel Disclosure'')');

        SET LS_JOIN_CONDITION = CONCAT(LS_JOIN_CONDITION, '
            LEFT JOIN TRAVEL_ACCESS_TMP T3 ON T3.HOME_UNIT = U.UNIT_NUMBER
        ');

        IF LI_HAS_PRE_UNIT_CONDITION = TRUE THEN
            SET LS_UNIT_FILTER_CONDITION = CONCAT(LS_UNIT_FILTER_CONDITION, ' OR ');
        END IF;
        SET LI_HAS_PRE_UNIT_CONDITION = TRUE;

        SET LS_UNIT_FILTER_CONDITION = CONCAT(LS_UNIT_FILTER_CONDITION,'
            U.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM TRAVEL_RIGHT_ACCESS_TMP)
            OR U.UNIT_NUMBER IN (SELECT HOME_UNIT FROM TRAVEL_ACCESS_TMP)
        ');

        SET LS_DYN_CTE_SQL = CONCAT(LS_DYN_CTE_SQL,',
            TRAVEL_RIGHT_ACCESS_TMP AS (
                SELECT UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                WHERE T1.DESCEND_FLAG = ''N''
                  AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                  AND T3.RIGHT_NAME IN (''MANAGE_TRAVEL_DISCLOSURE'', ''VIEW_TRAVEL_DISCLOSURE'')
                UNION
                SELECT T1.UNIT_NUMBER
                FROM PERSON_ROLES T1
                INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID
                WHERE T2.MODULE_CODE = 24 AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                UNION
                SELECT CHILD_UNIT_NUMBER
                FROM UNIT_WITH_CHILDREN
                WHERE UNIT_NUMBER IN (
                    SELECT UNIT_NUMBER
                    FROM PERSON_ROLES T1
                    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
                    INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
                    WHERE T1.DESCEND_FLAG = ''Y''
                      AND T1.PERSON_ID = ''', AV_PERSON_ID, '''
                      AND T3.RIGHT_NAME IN (''MANAGE_TRAVEL_DISCLOSURE'', ''VIEW_TRAVEL_DISCLOSURE'')
                )
            ),
            TRAVEL_ACCESS_TMP AS (SELECT T1.* FROM COI_TRAVEL_DISCLOSURE T1
                WHERE T1.HOME_UNIT IN (SELECT UNIT_NUMBER FROM TRAVEL_RIGHT_ACCESS_TMP)
                OR ADMIN_PERSON_ID = ''', AV_PERSON_ID, '''
            )
        ');

    END IF;

    -- Pagination logic
    IF AV_UNLIMITED IS NULL OR  AV_UNLIMITED != TRUE AND (AV_IS_COUNT IS NULL OR AV_IS_COUNT != TRUE )THEN
        SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
        SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
    ELSE
        SET LS_OFFSET_CONDITION = '';
    END IF;

    IF SELECTED_FIELD_LIST IS NOT NULL AND SELECTED_FIELD_LIST <> '' THEN
        IF AV_IS_COUNT = TRUE THEN
            SET SELECTED_FIELD_LIST = ' COUNT(DISTINCT U.UNIT_NUMBER) AS TOTAL_COUNT ';
            SET LS_GROUP_CONDITION = ' ';
        ELSE
            IF RIGHT(SELECTED_FIELD_LIST, 2) = ', ' THEN
                SET SELECTED_FIELD_LIST = LEFT(SELECTED_FIELD_LIST, LENGTH(SELECTED_FIELD_LIST) - 2);
            END IF;
            SET SELECTED_FIELD_LIST = CONCAT(' U.UNIT_NUMBER, U.UNIT_NAME, U.DISPLAY_NAME, JSON_ARRAY(', SELECTED_FIELD_LIST, ' ) AS COUNT_DETAILS ');
            SET LS_GROUP_CONDITION = ' GROUP BY U.UNIT_NUMBER, U.UNIT_NAME ';
        END IF;

        SET LS_DYN_SQL = CONCAT(LS_DYN_CTE_SQL, ' SELECT ', SELECTED_FIELD_LIST,
            ' FROM UNIT_ACCESS_TMP U ', LS_JOIN_CONDITION,
            ' WHERE (', LS_UNIT_FILTER_CONDITION, ')', LS_FILTER_CONDITION, LS_GROUP_CONDITION, LS_OFFSET_CONDITION);

        SET @QUERY_STATEMENT = LS_DYN_SQL;
        PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
        EXECUTE EXECUTABLE_STAEMENT;
    END IF;
END
//
