ALTER TABLE coi_disclosure_type 
ADD COLUMN DATA_CAPTURING_TYPE_CODE INT NULL DEFAULT NULL AFTER DESCRIPTION,
ADD INDEX COI_DISCLOSURE_TYPE_FK1_idx (DATA_CAPTURING_TYPE_CODE ASC) VISIBLE;

ALTER TABLE coi_disclosure_type 
ADD CONSTRAINT COI_DISCLOSURE_TYPE_FK1
  FOREIGN KEY (DATA_CAPTURING_TYPE_CODE)
  REFERENCES per_ent_data_capturing_type (DATA_CAPTURING_TYPE_CODE)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
UPDATE coi_disclosure_type SET DATA_CAPTURING_TYPE_CODE = '1' WHERE (DISCLOSURE_TYPE_CODE = '1');
UPDATE coi_disclosure_type SET DATA_CAPTURING_TYPE_CODE = '2' WHERE (DISCLOSURE_TYPE_CODE = '2');

ALTER TABLE coi_int_stage_award_person 
ADD COLUMN NEW_DISCLOSURE_REQUIRED VARCHAR(1) NULL DEFAULT 'N' AFTER DISCLOSURE_REQUIRED_FLAG;
