DELIMITER //
CREATE PROCEDURE `COI_INT_VALDTE_PERSN_DETILS`(AV_PERSON_FEED_ID INT)
BEGIN
    DECLARE LS_PERSON_ID VARCHAR(40);
    DECLARE LS_COUNTRY_OF_CITIZENSHIP VARCHAR(30);
    DECLARE LS_COUNTRY_CODE VARCHAR(3);
    DECLARE LS_HOME_UNIT VARCHAR(8);
    DECLARE LI_COUNT INT DEFAULT 0;
    DECLARE NOT_FOUND INT DEFAULT 0;
    DECLARE LS_VALIDATION_STATUS LONGTEXT DEFAULT '';
    DECLARE LS_INVALID_PERSONS LONGTEXT DEFAULT '';
    DECLARE LS_ERROR_MSG VARCHAR(4000) DEFAULT NULL;
    DECLARE LS_PROC_LOC VARCHAR(1000) DEFAULT 'START';
    DECLARE LI_BEFORE_COUNT INT DEFAULT 0;
    DECLARE LI_UPD_COUNT INT DEFAULT 0;
    DECLARE LI_TOTAL_COUNT INT DEFAULT 0;


    DECLARE INVALID_UNIT_PERSONS TEXT DEFAULT '';
    DECLARE INVALID_COUNTRY_CITIZENSHIP_PERSONS TEXT DEFAULT '';
    DECLARE INVALID_COUNTRY_CODE_PERSONS TEXT DEFAULT '';

    DECLARE SEL_DATA CURSOR FOR 
	SELECT PERSON_ID, TRIM(COUNTRY_OF_CITIZENSHIP), TRIM(COUNTRY_CODE), TRIM(HOME_UNIT) 
	FROM FIBI_COI_PERSON 
	WHERE (VALIDATION_STATUS = 'PENDING' OR VALIDATION_STATUS = 'ERROR')
    AND (COUNTRY_OF_CITIZENSHIP IS NOT NULL 
		OR COUNTRY_CODE IS NOT NULL 
		OR HOME_UNIT IS NOT NULL);


    DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;
    
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN	
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			 
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			
			SELECT @full_error INTO LS_ERROR_MSG;
            
			INSERT INTO COI_INT_ERROR_LOG (SECTION,ERROR_TYPE,ERROR_MESSAGE,ERROR_DETAILS,MODULE_CODE,MODULE_ITEM_KEY, 
			MODULE_SUB_ITEM_KEY,UPDATE_TIMESTAMP) VALUES ('PERSON','DATABASE',LS_ERROR_MSG, CONCAT('ERROR IN COI_INT_VALDTE_PERSN_DETILS : ',LS_ERROR_MSG,' AT ',LS_PROC_LOC),
			'6',LS_PERSON_ID,NULL,CURRENT_TIMESTAMP);		
		END;
    SET LS_PROC_LOC = 'SEL_DATA'; 

SELECT COUNT(1) INTO LI_BEFORE_COUNT FROM PERSON;

SET SQL_SAFE_UPDATES = 0;
    OPEN SEL_DATA;

    SEL_DATA: LOOP
    SET NOT_FOUND = 0;
        FETCH SEL_DATA INTO LS_PERSON_ID, LS_COUNTRY_OF_CITIZENSHIP, LS_COUNTRY_CODE, LS_HOME_UNIT;

        IF NOT_FOUND = 1 THEN
            LEAVE SEL_DATA;
        END IF;
        
      IF LS_HOME_UNIT IS NOT NULL AND LS_HOME_UNIT<> '' THEN 
        SET LI_COUNT = 0;
        SELECT COUNT(1) INTO LI_COUNT FROM UNIT WHERE UPPER(UNIT_NUMBER) = UPPER(LS_HOME_UNIT);

        IF LI_COUNT = 0 THEN 
            UPDATE FIBI_COI_PERSON SET VALIDATION_STATUS = 'ERROR', VALIDATION_MESSEGE = CONCAT(LS_PERSON_ID,' - Person Home unit ''',LS_HOME_UNIT,''' is not Available in Unit Table') WHERE PERSON_ID = LS_PERSON_ID;
            ITERATE SEL_DATA;
        END IF;
	  END IF;
      
      IF LS_COUNTRY_OF_CITIZENSHIP IS NOT NULL AND LS_COUNTRY_OF_CITIZENSHIP <> '' THEN 
        SET LI_COUNT = 0;
        SELECT COUNT(1) INTO LI_COUNT FROM COUNTRY WHERE UPPER(COUNTRY_NAME) = UPPER(LS_COUNTRY_OF_CITIZENSHIP);

        IF LI_COUNT = 0 THEN 
            UPDATE FIBI_COI_PERSON SET VALIDATION_STATUS = 'ERROR', VALIDATION_MESSEGE = CONCAT(LS_PERSON_ID,' - Person Country of Citizen Code ''',LS_COUNTRY_OF_CITIZENSHIP,''' is not Available in Country Table') WHERE PERSON_ID = LS_PERSON_ID;
            ITERATE SEL_DATA;
        END IF;
        
	END IF;

		IF LS_COUNTRY_CODE IS NOT NULL AND LS_COUNTRY_CODE <> '' THEN 
        SET LI_COUNT = 0;
        SELECT COUNT(1) INTO LI_COUNT FROM COUNTRY WHERE ((UPPER(COUNTRY_CODE_ISO2) = UPPER(LS_COUNTRY_CODE)) OR (UPPER(COUNTRY_CODE) = UPPER(LS_COUNTRY_CODE)));
        IF LI_COUNT = 0 THEN 
            UPDATE FIBI_COI_PERSON SET VALIDATION_STATUS = 'ERROR', VALIDATION_MESSEGE = CONCAT(LS_PERSON_ID,' - Person Country Code ''',LS_COUNTRY_CODE,''' is not Available in Country Table') WHERE PERSON_ID = LS_PERSON_ID;
            ITERATE SEL_DATA;
        END IF;
		END IF;
    
	COMMIT;

    END LOOP;    

    CLOSE SEL_DATA;
    UPDATE FIBI_COI_PERSON SET VALIDATION_STATUS = 'SUCCESS' WHERE VALIDATION_STATUS = 'PENDING';
    
    SET LS_PROC_LOC = 'PERSON_INTEGRATION';   

    SELECT COUNT(1) INTO LI_UPD_COUNT FROM PERSON WHERE PERSON_ID IN (SELECT PERSON_ID FROM FIBI_COI_PERSON WHERE VALIDATION_STATUS = 'SUCCESS');
 
    SET FOREIGN_KEY_CHECKS = 0;
    DELETE FROM PERSON WHERE PERSON_ID IN (SELECT PERSON_ID FROM FIBI_COI_PERSON WHERE VALIDATION_STATUS = 'SUCCESS');
    SET FOREIGN_KEY_CHECKS = 1;

		INSERT INTO PERSON (
			PERSON_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, PRIOR_NAME,
			USER_NAME, EMAIL_ADDRESS, DATE_OF_BIRTH, AGE, AGE_BY_FISCAL_YEAR, GENDER,
			EDUCATION_LEVEL, OFFICE_LOCATION, OFFICE_PHONE, SECONDRY_OFFICE_LOCATION, 
			SECONDRY_OFFICE_PHONE, SCHOOL, DIRECTORY_DEPARTMENT, SALUTATION,
			COUNTRY_OF_CITIZENSHIP, PRIMARY_TITLE, DIRECTORY_TITLE, HOME_UNIT, IS_FACULTY,
			IS_GRADUATE_STUDENT_STAFF, IS_RESEARCH_STAFF, IS_SERVICE_STAFF, IS_SUPPORT_STAFF,
			IS_OTHER_ACCADEMIC_GROUP, IS_MEDICAL_STAFF, ADDRESS_LINE_1, ADDRESS_LINE_2,
			ADDRESS_LINE_3, CITY, COUNTY, STATE, POSTAL_CODE, COUNTRY_CODE,
			FAX_NUMBER, PAGER_NUMBER, MOBILE_PHONE_NUMBER, VISA_CODE, VISA_TYPE,
			VISA_RENEWAL_DATE, STATUS, SALARY_ANNIVERSARY_DATE, UPDATE_TIMESTAMP,
			UPDATE_USER
		)
		SELECT 
			CONVERT(T1.PERSON_ID USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.LAST_NAME USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.FIRST_NAME USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.MIDDLE_NAME USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.FULL_NAME USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.PRIOR_NAME USING latin1) COLLATE latin1_swedish_ci,
			CONVERT(T1.USER_NAME USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.EMAIL_ADDRESS USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.DATE_OF_BIRTH USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.AGE USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.AGE_BY_FISCAL_YEAR USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.GENDER USING latin1) COLLATE latin1_swedish_ci,
			CONVERT(T1.EDUCATION_LEVEL USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.OFFICE_LOCATION USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.OFFICE_PHONE USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.SECONDRY_OFFICE_LOCATION USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.SECONDRY_OFFICE_PHONE USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.SCHOOL USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.DIRECTORY_DEPARTMENT USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.SALUTATION USING latin1) COLLATE latin1_swedish_ci,
			(SELECT COUNTRY_CODE FROM COUNTRY WHERE UPPER(TRIM(CONVERT(COUNTRY_NAME USING latin1))) COLLATE latin1_swedish_ci = UPPER(TRIM(CONVERT(T1.COUNTRY_OF_CITIZENSHIP USING latin1))) COLLATE latin1_swedish_ci),
			CONVERT(T1.PRIMARY_TITLE USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.DIRECTORY_TITLE USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.HOME_UNIT USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.IS_FACULTY USING latin1) COLLATE latin1_swedish_ci,
			CONVERT(T1.IS_GRADUATE_STUDENT_STAFF USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.IS_RESEARCH_STAFF USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.IS_SERVICE_STAFF USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.IS_SUPPORT_STAFF USING latin1) COLLATE latin1_swedish_ci,
			CONVERT(T1.IS_OTHER_ACCADEMIC_GROUP USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.IS_MEDICAL_STAFF USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.ADDRESS_LINE_1 USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.ADDRESS_LINE_2 USING latin1) COLLATE latin1_swedish_ci,
			CONVERT(T1.ADDRESS_LINE_3 USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.CITY USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.COUNTY USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.STATE USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.POSTAL_CODE USING latin1) COLLATE latin1_swedish_ci, 
			(SELECT COUNTRY_CODE FROM COUNTRY WHERE UPPER(TRIM(CONVERT(COUNTRY_CODE_ISO2 USING latin1))) COLLATE latin1_swedish_ci = UPPER(TRIM(CONVERT(T1.COUNTRY_CODE USING latin1))) COLLATE latin1_swedish_ci),
			CONVERT(T1.FAX_NUMBER USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.PAGER_NUMBER USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.MOBILE_PHONE_NUMBER USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.VISA_CODE USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.VISA_TYPE USING latin1) COLLATE latin1_swedish_ci,
			CONVERT(T1.VISA_RENEWAL_DATE USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.STATUS USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.SALARY_ANNIVERSARY_DATE USING latin1) COLLATE latin1_swedish_ci, 
			CONVERT(T1.UPDATE_TIMESTAMP USING latin1) COLLATE latin1_swedish_ci,
			CONVERT(T1.UPDATE_USER USING latin1) COLLATE latin1_swedish_ci
		FROM FIBI_COI_PERSON T1 
		WHERE T1.VALIDATION_STATUS = 'SUCCESS';
    
     SET LS_PROC_LOC = 'PERSON_INTEGRATION_STATUS_SETUP'; 

     SELECT COUNT(1) INTO LI_TOTAL_COUNT FROM PERSON;

	SET SESSION group_concat_max_len = 4294967295;
    SELECT GROUP_CONCAT(CONCAT(PERSON_ID,' : ',VALIDATION_MESSEGE)) INTO LS_VALIDATION_STATUS FROM FIBI_COI_PERSON WHERE VALIDATION_STATUS = 'ERROR';
    SELECT GROUP_CONCAT(PERSON_ID) INTO LS_INVALID_PERSONS FROM FIBI_COI_PERSON WHERE VALIDATION_STATUS = 'ERROR';  
   
    SET SQL_SAFE_UPDATES = 1;
    SELECT IFNULL(LS_VALIDATION_STATUS,'SUCCESS') AS VALIDATION_MESSAGE,LS_INVALID_PERSONS AS INVALID_PERSON_IDS,IFNULL(CASE WHEN (LI_TOTAL_COUNT - LI_BEFORE_COUNT) < 0 THEN 0 END,0) AS NO_OF_NEW_RECORDS,
     IFNULL(LI_UPD_COUNT,0) AS NO_OF_UPDATE_RECORDS;
END
//
