SET FOREIGN_KEY_CHECKS=0;

UPDATE valid_person_entity_rel_type SET DESCRIPTION = 'Travel : Self' WHERE (VALID_PERS_ENTITY_REL_TYP_CODE = '4');
ALTER TABLE coi_conflict_history ADD COLUMN MESSAGE VARCHAR(200) NULL AFTER DISCLOSURE_ID;

ALTER TABLE sponsor 
CHANGE COLUMN ACRONYM ACRONYM VARCHAR(20) NULL DEFAULT NULL ;

SET FOREIGN_KEY_CHECKS=1;
