\. ./FIBI-COI-5.7.1/FC-1407/Procedures/EVALUATE_FORM_VALIDATION.sql
\. ./FIBI-COI-5.7.1/FC-1407/Procedures/GET_OPA_DISCL_PERSON_ENTITY_REL.sql
\. ./FIBI-COI-5.7.1/FC-1407/Procedures/SYNC_OPA_DISCL_PERSON_ENTITY_REL.sql
\. ./FIBI-COI-5.7.1/FC-1407/Procedures/PROC_SYNC_OPA_PER_ENTITY.sql
\. ./FIBI-COI-5.7.1/FC-1407/Procedures/RULE_EVALUATE_FUNCTION.sql
\. ./FIBI-COI-5.7.1/FC-1407/Functions/FN_IS_OPA_DISCL_ENG_COMPLETE.sql
\. ./FIBI-COI-5.7.1/FC-1407/Functions/FN_IS_SABB_FILLED_IN_DISCL_ENG.sql
