SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `form_section_component_rules` (
  `FORM_SECT_COMP_RULE_ID` int NOT NULL AUTO_INCREMENT,
  `FORM_BUILDER_SECT_COMP_ID` int NOT NULL,
  `RULE_ID` int NOT NULL,
  `IS_ACTIVE` varchar(1) NOT NULL DEFAULT 'Y',
  `UPDATE_USER` varchar(60) NOT NULL,
  `UPDATE_TIMESTAMP` datetime NOT NULL,
  PRIMARY KEY (`FORM_SECT_COMP_RULE_ID`),
  KEY `FORM_SECT_COMP_RULES_FK1_idx` (`FORM_BUILDER_SECT_COMP_ID`),
  KEY `FORM_SECT_COMP_RULES_FK2_idx` (`RULE_ID`),
  CONSTRAINT `FORM_SECT_COMP_RULES_FK1` FOREIGN KEY (`FORM_BUILDER_SECT_COMP_ID`) REFERENCES `form_builder_section_component` (`FORM_BUILDER_SECT_COMP_ID`),
  CONSTRAINT `FORM_SECT_COMP_RULES_FK2` FOREIGN KEY (`RULE_ID`) REFERENCES `business_rules` (`RULE_ID`)
);

SET FOREIGN_KEY_CHECKS=1;
