ALTER TABLE `entity_stage_batch`
DROP FOREIGN KEY `ENTITY_STAGE_BATCH_FK1`;
ALTER TABLE `entity_stage_batch`
DROP INDEX `ENTITY_STAGE_BATCH_FK1` ;


ALTER TABLE `entity_stage_batch`
CHANGE COLUMN `SRC_TYPE_CODE` `SRC_TYPE_CODE` VARCHAR(3) NULL DEFAULT NULL ;

ALTER TABLE `entity_stage_batch`
ADD CONSTRAINT `ENTITY_STAGE_BATCH_FK1`
  FOREIGN KEY (`SRC_TYPE_CODE`)
  REFERENCES `entity_source_type` (`ENTITY_SOURCE_TYPE_CODE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

