\. ./FIBI-COI-5.5/FC-1313/Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./FIBI-COI-5.5/FC-1313/Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT.sql
\. ./FIBI-COI-5.5/FC-1313/Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
