DELIMITER //
CREATE FUNCTION `FN_OPA_DISCLOSURE_REQUIRED`(
AV_LOGGED_IN_PERSON_ID   VARCHAR(40)
) RETURNS boolean
    DETERMINISTIC
BEGIN

DECLARE LI_OPA_PERSON_COUNT INT DEFAULT 0;

    SELECT COUNT(*) INTO LI_OPA_PERSON_COUNT FROM OPA_PERSON WHERE PERSON_ID = AV_LOGGED_IN_PERSON_ID AND ( IS_DISCLOSURE_REQUIRED = 'Y' OR (EXEMPT_FROM_DATE IS NOT NULL
        AND EXEMPT_TO_DATE IS NOT NULL AND UTC_TIMESTAMP() NOT BETWEEN EXEMPT_FROM_DATE AND EXEMPT_TO_DATE));

    IF LI_OPA_PERSON_COUNT > 0 THEN
        RETURN true;
    END IF;
    RETURN false;

END
//
