UPDATE `business_rule_function` SET `SUB_MODULE_CODE` = '2' WHERE (`FUNCTION_NAME` = 'To check Active SFI is not Synced - Proposal');
UPDATE `business_rule_function` SET `SUB_MODULE_CODE` = '2' WHERE (`FUNCTION_NAME` = 'To check Engagement has inactive Entity - Proposal');
UPDATE `business_rule_function` SET `SUB_MODULE_CODE` = '2' WHERE (`FUNCTION_NAME` = 'To check Engagement is incomplete - Proposal');
UPDATE `business_rule_function` SET `SUB_MODULE_CODE` = '2' WHERE (`FUNCTION_NAME` = 'To check Engagement is Modified - Proposal');
UPDATE `business_rule_function` SET `SUB_MODULE_CODE` = '2' WHERE (`FUNCTION_NAME` = 'To check Entity is Modified - Proposal');
UPDATE `business_rule_function` SET `SUB_MODULE_CODE` = '2' WHERE (`FUNCTION_NAME` = 'To check Person has Engagement - Proposal');
UPDATE `business_rule_function` SET `SUB_MODULE_CODE` = '2' WHERE (`FUNCTION_NAME` = 'To check SFI is Defined - Proposal');


INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Engagement has inactive Entity - Award', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:29', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Active SFI is not Synced - Award', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:30', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Active SFI is not Synced - Award', '2', 'PERSON_ID', '2025-04-03 09:37:30', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Engagement is incomplete - Award', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:31', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Engagement is incomplete - Award', '2', 'PERSON_ID', '2025-04-03 09:37:32', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Engagement is Modified - Award', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:32', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Entity is Modified - Award', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:33', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Person has Engagement - Award', '1', 'PERSON_ID', '2025-04-03 09:37:33', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check SFI is Defined - Award', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:34', 'quickstart');



INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Engagement has inactive Entity - Proposal', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:29', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Active SFI is not Synced - Proposal', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:30', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Active SFI is not Synced - Proposal', '2', 'PERSON_ID', '2025-04-03 09:37:30', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Engagement is incomplete - Proposal', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:31', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Engagement is incomplete - Proposal', '2', 'PERSON_ID', '2025-04-03 09:37:32', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Engagement is Modified - Proposal', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:32', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Entity is Modified - Proposal', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:33', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check Person has Engagement - Proposal', '1', 'PERSON_ID', '2025-04-03 09:37:33', 'quickstart');
INSERT INTO `BUSINESS_RULE_FUNCTION_ARG` (`FUNCTION_NAME`, `ARGUMENT_SEQUENCE_NUMBER`, `ARGUMENT_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('To check SFI is Defined - Proposal', '1', 'MODULE_ITEM_KEY', '2025-04-03 09:37:34', 'quickstart');