CREATE TABLE COI_ENTITY_TYPE (
  ENTITY_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(2000) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ENTITY_TYPE_CODE)
);

INSERT INTO COI_ENTITY_TYPE (ENTITY_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATE_USER) VALUES
('001', 'US Governmental Organization (Federal, State, Local, Tribal)', 'Y', NOW(), '10000000001'),
('002', 'Foreign Governmental Organization', 'Y', NOW(), '10000000001'),
('003', 'For Profit Organization (Foreign or US)', 'Y', NOW(), '10000000001'),
('004', 'Non-profit Organization (Foreign or US)', 'Y', NOW(), '10000000001'),
('005', 'US Institution of Higher Education, Research, Medical Center, Academic Teaching Hospital', 'Y', NOW(), '10000000001'),
('006', 'Foreign Institution of Higher Education, Research, Medical Center, Academic Teaching Hospital', 'Y', NOW(), '10000000001'),
('007', 'Individual', 'Y', NOW(), '10000000001');

INSERT INTO ENTITY_SECTION (ENTITY_SECTION_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('32', 'Compliance: Compliance Details - Comment', 'Y', now(), '10000000001');

INSERT INTO ENTITY_COMMENT_TYPE (COMMENT_TYPE_CODE, SECTION_CODE, DESCRIPTION, IS_SYSTEM_COMMENT_TYPE, IS_PRIVATE, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('24', '32', 'Compliance: Compliance Details', 'N', 'N', 'Y', now(), '10000000001');

INSERT INTO ENTITY_SECTION_ACCESS_RIGHT (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('63', '32', 'MANAGE_ENTITY_COMPLIANCE_COMMENTS', now(), '10000000001');

INSERT INTO ENTITY_SECTION_ACCESS_RIGHT (SEC_ACCESS_RIGHT_ID, SECTION_CODE, RIGHT_NAME, UPDATE_TIMESTAMP, UPDATED_BY) VALUES ('64', '32', 'VIEW_ENTITY_COMPLIANCE_COMMENTS', now(), '10000000001');

ALTER TABLE ENTITY_COMPLIANCE_INFO 
ADD COLUMN ENTITY_TYPE_CODE VARCHAR(3) NULL DEFAULT NULL AFTER ENTITY_ID,
ADD INDEX ENTITY_COMPLIANCE_INFO_FK2_idx (ENTITY_TYPE_CODE ASC) VISIBLE;
;

ALTER TABLE ENTITY_COMPLIANCE_INFO 
ADD CONSTRAINT ENTITY_COMPLIANCE_INFO_FK2
  FOREIGN KEY (ENTITY_TYPE_CODE)
  REFERENCES COI_ENTITY_TYPE (ENTITY_TYPE_CODE);
