DELIMITER //
CREATE PROCEDURE ENRICH_ENTITY_REGISTRATION (
    IN AV_ENTITY_ID INT,
    IN AV_REGISTRATION_NUMBER VARCHAR(50),
    IN AV_TYPE_DESCRIPTION VARCHAR(500),
    IN AV_TYPE_CODE VARCHAR(10),
    IN AV_PERSON_ID VARCHAR(40)
) DETERMINISTIC
BEGIN
   
    IF NOT EXISTS (
        SELECT 1 
        FROM ENTITY_REGISTRATION_TYPE 
        WHERE REG_TYPE_CODE = AV_TYPE_CODE
    ) THEN
        
        INSERT INTO ENTITY_REGISTRATION_TYPE (REG_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
        VALUES (AV_TYPE_CODE, AV_TYPE_DESCRIPTION, 'Y', NOW(), AV_PERSON_ID);
    END IF;

  
    IF NOT EXISTS (
        SELECT 1 
        FROM ENTITY_REGISTRATION 
        WHERE ENTITY_ID = AV_ENTITY_ID 
        AND REG_TYPE_CODE = AV_TYPE_CODE
		
    ) THEN
	
        INSERT INTO ENTITY_REGISTRATION (ENTITY_ID, REG_TYPE_CODE, REG_NUMBER, IS_ACTIVE, UPDATE_TIMESTAMP, UPDATED_BY)
        VALUES (AV_ENTITY_ID, AV_TYPE_CODE, AV_REGISTRATION_NUMBER, 'Y', NOW(), AV_PERSON_ID);
	ELSE

		UPDATE ENTITY_REGISTRATION SET REG_NUMBER = AV_REGISTRATION_NUMBER 
		WHERE ENTITY_ID = AV_ENTITY_ID 
        AND REG_TYPE_CODE = AV_TYPE_CODE;		 
		
    END IF;
END
//
