DELIMITER //
CREATE PROCEDURE `GET_HEIR_PROJECT_TREE`(
    IN AV_MODULE_CODE INT,
    IN AV_PROJECT_NUMBER VARCHAR(20)
)
BEGIN
    DECLARE LS_PROJECT_NUMBER VARCHAR(20);
    DECLARE LS_MODULE_CODE VARCHAR(1);

/*
   Determine the project number and module code based on the input `moduleCode` and `projectNumber`. 
   The procedure checks if there is an award associated with an IP or a proposal, and based on that, 
   retrieves the hierarchy data related to the project.
*/

    IF AV_MODULE_CODE = 2 THEN
	
	-- Check if the project (IP) is linked to an award. If yes, hierarchy data is fetched based on the award number.
        SELECT LINKED_AWARD_PROJECT_NUMBER 
        INTO LS_PROJECT_NUMBER 
        FROM COI_INT_STAGE_PROPOSAL T1
		INNER JOIN COI_INT_STAGE_AWARD T2 ON T2.PROJECT_NUMBER= T1.LINKED_AWARD_PROJECT_NUMBER
        WHERE T1.PROJECT_NUMBER = AV_PROJECT_NUMBER;

        IF LS_PROJECT_NUMBER IS NULL THEN 
            SET LS_MODULE_CODE = AV_MODULE_CODE;
            SET LS_PROJECT_NUMBER = AV_PROJECT_NUMBER;
        ELSE
            SET LS_MODULE_CODE = 1;
        END IF;

    ELSEIF AV_MODULE_CODE = 3 THEN
	
		-- Check if proposal has award through linked IP If exists then hierarchy data is fetched based award number
        SELECT T1.LINKED_AWARD_PROJECT_NUMBER
		INTO LS_PROJECT_NUMBER
		FROM COI_INT_STAGE_PROPOSAL T1
		INNER JOIN COI_INT_STAGE_DEV_PROPOSAL T2 ON T1.PROJECT_NUMBER = T2.IP_NUMBER
		INNER JOIN COI_INT_STAGE_AWARD T3 ON T3.PROJECT_NUMBER = T1.LINKED_AWARD_PROJECT_NUMBER
		WHERE T2.PROPOSAL_NUMBER = AV_PROJECT_NUMBER;

        IF LS_PROJECT_NUMBER IS NULL THEN 
		
			-- Check if proposal has linked IP , If exists then hierarchy data is fetched based ip number
			SELECT T1.IP_NUMBER
			INTO LS_PROJECT_NUMBER
			FROM COI_INT_STAGE_DEV_PROPOSAL T1
			INNER JOIN COI_INT_STAGE_PROPOSAL T2 ON T2.PROJECT_NUMBER = T1.IP_NUMBER
			WHERE T1.PROPOSAL_NUMBER = AV_PROJECT_NUMBER;
					
				IF LS_PROJECT_NUMBER IS NULL THEN 
					SET LS_PROJECT_NUMBER = AV_PROJECT_NUMBER;
					SET LS_MODULE_CODE = AV_MODULE_CODE;
				ELSE
				-- Otherwise hierarchy data is fetched based on proposal
                    SET LS_MODULE_CODE = 2;
				END IF;
                
        ELSE
            SET LS_MODULE_CODE = 1;
        END IF;

    ELSE
        SET LS_MODULE_CODE = AV_MODULE_CODE;
        SET LS_PROJECT_NUMBER = AV_PROJECT_NUMBER;
    END IF;

    -- Main query to get the hierarchy structure
    IF LS_MODULE_CODE = 1 THEN
        
		SELECT IFNULL(T1.PROJECT_NUMBER,NULL) AS AWARD_NUMBER, IFNULL(T2.PROJECT_NUMBER,NULL) IP_NUMBER, IFNULL(T3.PROPOSAL_NUMBER, NULL) AS PROPOSAL_NUMBER
        FROM COI_INT_STAGE_AWARD T1
        LEFT JOIN COI_INT_STAGE_PROPOSAL T2 ON T2.LINKED_AWARD_PROJECT_NUMBER= T1.PROJECT_NUMBER
        LEFT JOIN COI_INT_STAGE_DEV_PROPOSAL T3 ON T3.IP_NUMBER=T2.PROJECT_NUMBER
		WHERE T1.PROJECT_NUMBER = LS_PROJECT_NUMBER
        UNION 
        SELECT AWARD_NUMBER, NULL AS IP_NUMBER, NULL AS PROPOSAL_NUMBER 
        FROM AWARD 
        WHERE AWARD_SEQUENCE_STATUS <> 'ARCHIVE' AND AWARD_NUMBER = LS_PROJECT_NUMBER;

    ELSEIF LS_MODULE_CODE = 2 THEN
        
		SELECT IFNULL(T3.PROJECT_NUMBER,NULL) AS AWARD_NUMBER, IFNULL(T1.PROJECT_NUMBER,NULL) IP_NUMBER, IFNULL(T2.PROPOSAL_NUMBER, NULL) AS PROPOSAL_NUMBER
        FROM COI_INT_STAGE_PROPOSAL T1 
        LEFT JOIN COI_INT_STAGE_DEV_PROPOSAL T2 ON T2.IP_NUMBER = T1.PROJECT_NUMBER
        LEFT JOIN COI_INT_STAGE_AWARD T3 ON T3.PROJECT_NUMBER = T1.LINKED_AWARD_PROJECT_NUMBER
		WHERE T1.PROJECT_NUMBER = LS_PROJECT_NUMBER
        UNION 
        SELECT NULL AS AWARD_NUMBER, PROPOSAL_NUMBER AS IP_NUMBER, NULL AS PROPOSAL_NUMBER 
        FROM PROPOSAL 
        WHERE PROPOSAL_SEQUENCE_STATUS <> 'ARCHIVE' AND PROPOSAL_NUMBER = LS_PROJECT_NUMBER;

    ELSEIF LS_MODULE_CODE = 3 THEN
        		
		SELECT IFNULL(T3.PROJECT_NUMBER,NULL) AS AWARD_NUMBER, IFNULL(T2.PROJECT_NUMBER,NULL) IP_NUMBER, IFNULL(T1.PROPOSAL_NUMBER, NULL) AS PROPOSAL_NUMBER
        FROM COI_INT_STAGE_DEV_PROPOSAL T1
        LEFT JOIN COI_INT_STAGE_PROPOSAL T2 ON T1.IP_NUMBER=T2.PROJECT_NUMBER
        LEFT JOIN COI_INT_STAGE_AWARD T3 ON T3.PROJECT_NUMBER =T2.LINKED_AWARD_PROJECT_NUMBER
		WHERE T1.PROPOSAL_NUMBER = LS_PROJECT_NUMBER
        UNION 
        SELECT NULL AS AWARD_NUMBER, NULL AS IP_NUMBER, PROPOSAL_ID AS PROPOSAL_NUMBER 
        FROM EPS_PROPOSAL 
        WHERE DOCUMENT_STATUS_CODE <> '3' AND PROPOSAL_ID = LS_PROJECT_NUMBER;
    END IF;
END //

DELIMITER ;
