DELIMITER //

CREATE PROCEDURE `GET_HEIR_PERSON_DISCLOSURES`(
    IN AV_MODULE_CODE INT,
    IN AV_PROJECT_NUMBER VARCHAR(20),
    IN AV_PERSON_ID VARCHAR(20)
)
BEGIN
    SELECT DISTINCT 
        T1.DISCLOSURE_ID,
        T3.DESCRIPTION AS CONFLICT_STATUS,
        T4.DESCRIPTION AS REVIEW_STATUS,
        CASE 
           WHEN T1.FCOI_TYPE_CODE = 1 AND T1.VERSION_NUMBER = 1 THEN 'Initial'
           WHEN T1.FCOI_TYPE_CODE = 2 THEN T7.DESCRIPTION
           WHEN T1.FCOI_TYPE_CODE = 3 THEN 'Revision'
           ELSE NULL
        END AS DISCLOSURE_TYPE,
        T1.CERTIFIED_AT,
        T5.DESCRIPTION AS DISPOSITION_STATUS
    FROM COI_DISCLOSURE T1
    INNER JOIN COI_DISCL_PROJECTS T2 
        ON T2.DISCLOSURE_ID = T1.DISCLOSURE_ID  
    LEFT JOIN COI_CONFLICT_STATUS_TYPE T3 
        ON T3.CONFLICT_STATUS_CODE = T1.CONFLICT_STATUS_CODE 
    INNER JOIN COI_REVIEW_STATUS_TYPE T4 
        ON T4.REVIEW_STATUS_CODE = T1.REVIEW_STATUS_CODE 
    INNER JOIN COI_DISPOSITION_STATUS_TYPE T5 
        ON T5.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE 
    INNER JOIN COI_DISCLOSURE_FCOI_TYPE T6 
        ON T6.FCOI_TYPE_CODE = T1.FCOI_TYPE_CODE
    LEFT JOIN COI_PROJECT_TYPE T7 
        ON T7.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
    WHERE T2.MODULE_CODE = AV_MODULE_CODE
      AND T2.MODULE_ITEM_KEY = AV_PROJECT_NUMBER
      AND T1.PERSON_ID = AV_PERSON_ID
      AND T1.REVIEW_STATUS_CODE NOT IN (1, 5, 6)
      AND T1.DISPOSITION_STATUS_CODE != 2
    ORDER BY T1.CERTIFIED_AT DESC;
    
END//

DELIMITER ;
