DELIMITER //

CREATE PROCEDURE `GET_HEIR_PROJECT_DETAIL`(
    IN AV_MODULE_CODE INT,
    IN AV_PROJECT_NUMBER VARCHAR(20)
)
BEGIN
    DECLARE LS_COUNT INT;
	
	-- Check whether the input project is in any of the staging tables then avoid the execution of fibi tables
	SELECT 
    (SELECT COUNT(*) FROM COI_INT_STAGE_AWARD WHERE PROJECT_NUMBER = AV_PROJECT_NUMBER) +
    (SELECT COUNT(*) FROM COI_INT_STAGE_PROPOSAL WHERE PROJECT_NUMBER = AV_PROJECT_NUMBER) +
    (SELECT COUNT(*) FROM COI_INT_STAGE_DEV_PROPOSAL WHERE PROPOSAL_NUMBER = AV_PROJECT_NUMBER) INTO LS_COUNT FROM DUAL;


	IF LS_COUNT > 0 THEN 
		IF AV_MODULE_CODE = 1 THEN 
			
			SELECT DISTINCT 
                T6.PROJECT_ID,T5.DESCRIPTION AS PROJECT_TYPE, T5.COI_PROJECT_TYPE_CODE, T5.BADGE_COLOR, T5.PROJECT_ICON,
                T7.KEY_PERSON_ID, T7.PROJECT_NUMBER, T7.KEY_PERSON_NAME,
                T7.KEY_PERSON_ROLE_NAME, T8.KEY_PERSON_NAME AS PI_NAME, T6.TITLE,
                T6.PROJECT_STATUS, T6.PROJECT_STATUS_CODE, T6.SPONSOR_NAME, 
                T6.SPONSOR_CODE, T6.PRIME_SPONSOR_NAME, T6.PRIME_SPONSOR_CODE,
                T6.PROJECT_START_DATE, T6.PROJECT_END_DATE, T6.LEAD_UNIT_NUMBER, T6.LEAD_UNIT_NAME,T15.SORT_ID
            FROM COI_INT_STAGE_AWARD T6 
            INNER JOIN COI_PROJECT_TYPE T5 ON T5.COI_PROJECT_TYPE_CODE = AV_MODULE_CODE
            LEFT JOIN COI_INT_STAGE_AWARD_PERSON T7 ON T7.PROJECT_NUMBER = T6.PROJECT_NUMBER
            LEFT JOIN COI_INT_STAGE_AWARD_PERSON T8 ON T8.PROJECT_NUMBER = T6.PROJECT_NUMBER AND T8.KEY_PERSON_ROLE_CODE = 3
			LEFT JOIN EPS_PROP_PERSON_ROLE T15 ON T15.PROP_PERSON_ROLE_ID = T7.KEY_PERSON_ROLE_CODE
            WHERE T6.PROJECT_NUMBER = AV_PROJECT_NUMBER AND T7.STATUS <> 'I'  ORDER BY SORT_ID;
		ELSE IF AV_MODULE_CODE = 2 THEN 
			
			SELECT DISTINCT 
                T6.PROJECT_ID,T5.DESCRIPTION AS PROJECT_TYPE, T5.COI_PROJECT_TYPE_CODE, T5.BADGE_COLOR, T5.PROJECT_ICON,
                T7.KEY_PERSON_ID, T7.PROJECT_NUMBER, T7.KEY_PERSON_NAME,
                T7.KEY_PERSON_ROLE_NAME, T8.KEY_PERSON_NAME AS PI_NAME, T6.TITLE,
                T6.PROJECT_STATUS, T6.PROJECT_STATUS_CODE, T6.SPONSOR_NAME, 
                T6.SPONSOR_CODE, T6.PRIME_SPONSOR_NAME, T6.PRIME_SPONSOR_CODE,
                T6.PROJECT_START_DATE, T6.PROJECT_END_DATE, 
                T6.LEAD_UNIT_NUMBER, T6.LEAD_UNIT_NAME,T15.SORT_ID
            FROM COI_INT_STAGE_PROPOSAL T6
            INNER JOIN COI_PROJECT_TYPE T5 ON T5.COI_PROJECT_TYPE_CODE = AV_MODULE_CODE
            LEFT JOIN COI_INT_STAGE_PROPOSAL_PERSON T7 ON T7.PROJECT_NUMBER = T6.PROJECT_NUMBER
            LEFT JOIN COI_INT_STAGE_PROPOSAL_PERSON T8 ON T8.PROJECT_NUMBER = T6.PROJECT_NUMBER AND T8.KEY_PERSON_ROLE_CODE = 3
			LEFT JOIN EPS_PROP_PERSON_ROLE T15 ON T15.PROP_PERSON_ROLE_ID = T7.KEY_PERSON_ROLE_CODE
            WHERE T6.PROJECT_NUMBER = AV_PROJECT_NUMBER  AND T7.STATUS <> 'I' ORDER BY SORT_ID;
		ELSE IF AV_MODULE_CODE = 3 THEN 
			
			SELECT DISTINCT 
                T6.PROPOSAL_NUMBER AS PROJECT_ID,T5.DESCRIPTION AS PROJECT_TYPE, T5.COI_PROJECT_TYPE_CODE, T5.BADGE_COLOR, T5.PROJECT_ICON,
                T7.KEY_PERSON_ID, T7.PROPOSAL_NUMBER AS PROJECT_NUMBER, T7.KEY_PERSON_NAME,
                T7.KEY_PERSON_ROLE AS KEY_PERSON_ROLE_NAME, T8.KEY_PERSON_NAME AS PI_NAME, T6.TITLE,
                T6.PROPOSAL_STATUS AS PROJECT_STATUS, T6.PROPOSAL_STATUS_CODE, T6.SPONSOR AS SPONSOR_NAME, 
                T6.SPONSOR_CODE, T6.PRIME_SPONSOR AS PRIME_SPONSOR_NAME, T6.PRIME_SPONSOR_CODE,
                T6.PROPOSAL_START_DATE AS PROJECT_START_DATE, T6.PROPOSAL_END_DATE AS PROJECT_END_DATE,
                T6.LEAD_UNIT AS LEAD_UNIT_NUMBER, T6.LEAD_UNIT_NAME,T15.SORT_ID
            FROM COI_INT_STAGE_DEV_PROPOSAL T6
            INNER JOIN COI_PROJECT_TYPE T5 ON T5.COI_PROJECT_TYPE_CODE = AV_MODULE_CODE
            LEFT JOIN COI_INT_STAGE_DEV_PROPOSAL_PERSON T7 ON T7.PROPOSAL_NUMBER = T6.PROPOSAL_NUMBER
            LEFT JOIN COI_INT_STAGE_DEV_PROPOSAL_PERSON T8 ON T8.PROPOSAL_NUMBER = T6.PROPOSAL_NUMBER AND T8.KEY_PERSON_ROLE_CODE = 3
			LEFT JOIN EPS_PROP_PERSON_ROLE T15 ON T15.PROP_PERSON_ROLE_ID = T7.KEY_PERSON_ROLE_CODE
            WHERE T6.PROPOSAL_NUMBER = AV_PROJECT_NUMBER AND T7.STATUS <> 'I' ORDER BY SORT_ID;
		END IF;
		END IF;
		END IF;
	ELSE
		IF AV_MODULE_CODE = 1 THEN 
			
			SELECT DISTINCT 
                T12.AWARD_ID AS PROJECT_ID,T5.DESCRIPTION AS PROJECT_TYPE, T5.COI_PROJECT_TYPE_CODE, T5.BADGE_COLOR, T5.PROJECT_ICON,
                T13.PERSON_ID AS KEY_PERSON_ID, T13.AWARD_NUMBER AS PROJECT_NUMBER, T13.FULL_NAME AS KEY_PERSON_NAME,
                T15.DESCRIPTION AS KEY_PERSON_ROLE_NAME, T14.FULL_NAME AS PI_NAME, T12.TITLE,
                T16.DESCRIPTION AS PROJECT_STATUS, T12.STATUS_CODE AS PROJECT_STATUS_CODE, 
                T17.SPONSOR_NAME, T12.SPONSOR_CODE, T18.SPONSOR_NAME AS PRIME_SPONSOR_NAME, 
                T12.PRIME_SPONSOR_CODE, T12.BEGIN_DATE AS PROJECT_START_DATE, 
                T12.FINAL_EXPIRATION_DATE AS PROJECT_END_DATE, T12.LEAD_UNIT_NUMBER, 
                T19.UNIT_NAME AS LEAD_UNIT_NAME,T15.SORT_ID
            FROM AWARD T12
			INNER JOIN COI_PROJECT_TYPE T5 ON T5.COI_PROJECT_TYPE_CODE = AV_MODULE_CODE
            LEFT JOIN AWARD_PERSONS T13 ON T13.AWARD_NUMBER = T12.AWARD_NUMBER
            LEFT JOIN AWARD_PERSONS T14 ON T14.AWARD_NUMBER = T12.AWARD_NUMBER AND T14.PERSON_ROLE_ID = 3
            LEFT JOIN EPS_PROP_PERSON_ROLE T15 ON T15.PROP_PERSON_ROLE_ID = T13.PERSON_ROLE_ID
            INNER JOIN AWARD_STATUS T16 ON T16.STATUS_CODE = T12.STATUS_CODE
            INNER JOIN SPONSOR T17 ON T17.SPONSOR_CODE = T12.SPONSOR_CODE
            LEFT JOIN SPONSOR T18 ON T18.SPONSOR_CODE = T12.PRIME_SPONSOR_CODE
            INNER JOIN UNIT T19 ON T19.UNIT_NUMBER = T12.LEAD_UNIT_NUMBER
            WHERE T12.AWARD_SEQUENCE_STATUS <> 'ARCHIVE' AND T12.AWARD_NUMBER = AV_PROJECT_NUMBER ORDER BY SORT_ID;
		ELSE IF AV_MODULE_CODE = 2 THEN 
			
			SELECT DISTINCT 
                T12.PROPOSAL_ID AS PROJECT_ID,T5.DESCRIPTION AS PROJECT_TYPE, T5.COI_PROJECT_TYPE_CODE, T5.BADGE_COLOR, T5.PROJECT_ICON,
                T13.PERSON_ID AS KEY_PERSON_ID, T13.PROPOSAL_NUMBER AS PROJECT_NUMBER, T13.FULL_NAME AS KEY_PERSON_NAME,
                T15.DESCRIPTION AS KEY_PERSON_ROLE_NAME, T14.FULL_NAME AS PI_NAME, T12.TITLE,
                T16.DESCRIPTION AS PROJECT_STATUS, T12.STATUS_CODE AS PROJECT_STATUS_CODE, 
                T17.SPONSOR_NAME, T12.SPONSOR_CODE, T18.SPONSOR_NAME AS PRIME_SPONSOR_NAME, 
                T12.PRIME_SPONSOR_CODE, T12.START_DATE AS PROJECT_START_DATE, 
                T12.END_DATE AS PROJECT_END_DATE, T12.HOME_UNIT_NUMBER AS LEAD_UNIT_NUMBER, 
                T19.UNIT_NAME AS LEAD_UNIT_NAME,T15.SORT_ID
            FROM PROPOSAL T12 
			INNER JOIN COI_PROJECT_TYPE T5 ON T5.COI_PROJECT_TYPE_CODE = AV_MODULE_CODE
            LEFT JOIN PROPOSAL_PERSONS T13 ON T13.PROPOSAL_NUMBER = T12.PROPOSAL_NUMBER
            LEFT JOIN PROPOSAL_PERSONS T14 ON T14.PROPOSAL_NUMBER = T12.PROPOSAL_NUMBER AND T14.PROP_PERSON_ROLE_ID = 3
            LEFT JOIN EPS_PROP_PERSON_ROLE T15 ON T15.PROP_PERSON_ROLE_ID = T13.PROP_PERSON_ROLE_ID
            INNER JOIN PROPOSAL_STATUS T16 ON T16.STATUS_CODE = T12.STATUS_CODE
            INNER JOIN SPONSOR T17 ON T17.SPONSOR_CODE = T12.SPONSOR_CODE
            LEFT JOIN SPONSOR T18 ON T18.SPONSOR_CODE = T12.PRIME_SPONSOR_CODE
            INNER JOIN UNIT T19 ON T19.UNIT_NUMBER = T12.HOME_UNIT_NUMBER
            WHERE T12.PROPOSAL_SEQUENCE_STATUS <> 'ARCHIVE' AND T12.PROPOSAL_NUMBER = AV_PROJECT_NUMBER ORDER BY SORT_ID;
		ELSE IF AV_MODULE_CODE = 3 THEN 
			
			SELECT DISTINCT 
                T13.PROPOSAL_ID AS PROJECT_ID,T5.DESCRIPTION AS PROJECT_TYPE, T5.COI_PROJECT_TYPE_CODE, T5.BADGE_COLOR, T5.PROJECT_ICON,
                T13.PERSON_ID AS KEY_PERSON_ID, T13.PROPOSAL_ID AS PROJECT_NUMBER, T13.FULL_NAME AS KEY_PERSON_NAME,
                T15.DESCRIPTION AS KEY_PERSON_ROLE_NAME, T14.FULL_NAME AS PI_NAME, T12.TITLE,
                T16.DESCRIPTION AS PROJECT_STATUS, T12.STATUS_CODE AS PROJECT_STATUS_CODE, 
                T17.SPONSOR_NAME, T12.SPONSOR_CODE, T18.SPONSOR_NAME AS PRIME_SPONSOR_NAME, 
                T12.PRIME_SPONSOR_CODE, T12.START_DATE AS PROJECT_START_DATE, 
                T12.END_DATE AS PROJECT_END_DATE, T12.HOME_UNIT_NUMBER AS LEAD_UNIT_NUMBER, 
                T19.UNIT_NAME AS LEAD_UNIT_NAME,T15.SORT_ID
            FROM EPS_PROPOSAL T12 
			INNER JOIN COI_PROJECT_TYPE T5 ON T5.COI_PROJECT_TYPE_CODE = AV_MODULE_CODE
            LEFT JOIN EPS_PROPOSAL_PERSONS T13 ON T13.PROPOSAL_ID = T12.PROPOSAL_ID
            LEFT JOIN EPS_PROPOSAL_PERSONS T14 ON T14.PROPOSAL_ID = T12.PROPOSAL_ID AND T14.PROP_PERSON_ROLE_ID = 3
            LEFT JOIN EPS_PROP_PERSON_ROLE T15 ON T15.PROP_PERSON_ROLE_ID = T13.PROP_PERSON_ROLE_ID
            INNER JOIN EPS_PROPOSAL_STATUS T16 ON T16.STATUS_CODE = T12.STATUS_CODE
            INNER JOIN SPONSOR T17 ON T17.SPONSOR_CODE = T12.SPONSOR_CODE
            LEFT JOIN SPONSOR T18 ON T18.SPONSOR_CODE = T12.PRIME_SPONSOR_CODE
            INNER JOIN UNIT T19 ON T19.UNIT_NUMBER = T12.HOME_UNIT_NUMBER
            WHERE T12.DOCUMENT_STATUS_CODE <> '3' AND T12.PROPOSAL_ID = AV_PROJECT_NUMBER ORDER BY SORT_ID;
		END IF;
		END IF;
		END IF;
	END IF;

   
END //

DELIMITER ;
