DROP PROCEDURE IF EXISTS COI_COPY_GLOBAL_ENTITY;
DROP PROCEDURE IF EXISTS COI_INT_GET_ORGANIZATION_DETAILS;
DROP PROCEDURE IF EXISTS COI_INT_GET_SPONSOR_DETAILS;
DROP PROCEDURE IF EXISTS COI_INT_KC_SPON_ORG_RESPONSE;
