ALTER TABLE ENTITY_STAGE_DETAILS ADD SRC_ROLODEX_ID INT NULL;

ALTER TABLE ENTITY_STAGE_BATCH ADD BATCH_TYPE varchar(200) NULL;

ALTER TABLE `ENTITY_SUB_ORG_INFO`
ADD COLUMN `IS_CREATED_FROM_IMPORT_ENTITY` VARCHAR(1) NULL DEFAULT 'N',
ADD COLUMN `ROLODEX_ID` INT NULL;

ALTER TABLE `ENTITY_SPONSOR_INFO`
ADD COLUMN `IS_CREATED_FROM_IMPORT_ENTITY` VARCHAR(1) NULL DEFAULT 'N',
ADD COLUMN `ROLODEX_ID` INT NULL;
