CREATE TABLE IF NOT EXISTS `LEGACY_COI_MATRIX_GROUP` (
  `GROUP_ID` INT NOT NULL AUTO_INCREMENT,
  `GROUP_NAME` VARCHAR(500) NOT NULL,
  `SORT_ID` INT DEFAULT NULL,
  `UPDATE_TIMESTAMP` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`GROUP_ID`)
);

CREATE TABLE IF NOT EXISTS LEGACY_COI_MATRIX_QUESTION (
MATRIX_QUESTION_ID INT NOT NULL AUTO_INCREMENT,
COLUMN_LABEL VARCHAR(4000) NOT NULL,
ANSWER_TYPE_CODE INT NOT NULL,
LOOKUP_TYPE VARCHAR(50) DEFAULT NULL,
LOOKUP_VALUE VARCHAR(50) DEFAULT NULL,
GROUP_ID INT DEFAULT NULL,
SORT_ID INT DEFAULT NULL,
IS_ACTIVE CHAR(1) NOT NULL,
UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
UPDATED_BY VARCHAR(60) NOT NULL,
PRIMARY KEY (MATRIX_QUESTION_ID),
CONSTRAINT LEGACY_COI_MATRIX_QUESTION_FK1 FOREIGN KEY (GROUP_ID) REFERENCES LEGACY_COI_MATRIX_GROUP (GROUP_ID),
CONSTRAINT LEGACY_COI_MATRIX_QUESTION_FK2 FOREIGN KEY (ANSWER_TYPE_CODE) REFERENCES PER_ENT_MATRIX_ANSWER_TYPE (ANSWER_TYPE_CODE));
