ANALYZE TABLE LEGACY_COI_ENTITY_MATRIX;

SET @sql := IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LEGACY_COI_ENTITY_MATRIX' AND COLUMN_NAME = 'COMMENTS') = 0,

    'ALTER TABLE LEGACY_COI_ENTITY_MATRIX ADD COLUMN COMMENTS VARCHAR(2000) DEFAULT NULL;',

    'DO 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
