DROP TABLE IF EXISTS ENTITY_STAGE_INTEGRATION_STATUS_TYPE;
CREATE TABLE `ENTITY_STAGE_INTEGRATION_STATUS_TYPE` (
  `INTEGRATION_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(40) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`INTEGRATION_STATUS_CODE`)
);

DROP TABLE IF EXISTS ENTITY_STAGE_BATCH_SOURCE_TYPE;
CREATE TABLE ENTITY_STAGE_BATCH_SOURCE_TYPE (
    SRC_TYPE_CODE INT NOT NULL,
    DESCRIPTION VARCHAR(255),
    UPDATE_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(40),
	IS_ACTIVE VARCHAR(1) DEFAULT NULL,
    PRIMARY KEY (SRC_TYPE_CODE)
);

DROP TABLE IF EXISTS ENTITY_STAGE_BATCH_STATUS_TYPE;
CREATE TABLE ENTITY_STAGE_BATCH_STATUS_TYPE (
    BATCH_STATUS_CODE INT NOT NULL,
    DESCRIPTION VARCHAR(255),
    UPDATE_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(40),
	IS_ACTIVE VARCHAR(1) DEFAULT NULL,
    PRIMARY KEY (BATCH_STATUS_CODE)
);

DROP TABLE IF EXISTS ENTITY_STAGE_REVIEW_STATUS_TYPE;
CREATE TABLE ENTITY_STAGE_REVIEW_STATUS_TYPE (
    REVIEW_STATUS_CODE INT NOT NULL,
    DESCRIPTION VARCHAR(255),
    UPDATE_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(40),
	IS_ACTIVE VARCHAR(1) DEFAULT NULL,
    PRIMARY KEY (REVIEW_STATUS_CODE)
);

DROP TABLE IF EXISTS ENTITY_STAGE_MATCH_STATUS_TYPE;
CREATE TABLE ENTITY_STAGE_MATCH_STATUS_TYPE (
    MATCH_STATUS_CODE INT NOT NULL,
    DESCRIPTION VARCHAR(255),
    UPDATE_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(40),
	IS_ACTIVE VARCHAR(1) DEFAULT NULL,
    PRIMARY KEY (MATCH_STATUS_CODE)
);

DROP TABLE IF EXISTS ENTITY_STAGE_ADMIN_REVIEW_TYPE;
CREATE TABLE ENTITY_STAGE_ADMIN_REVIEW_TYPE (
    ADMIN_REVIEW_STATUS_CODE INT NOT NULL,
    DESCRIPTION VARCHAR(255),
    UPDATE_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(40),
	IS_ACTIVE VARCHAR(1) DEFAULT NULL,
    PRIMARY KEY (ADMIN_REVIEW_STATUS_CODE)
);

DROP TABLE IF EXISTS ENTITY_STAGE_ADMIN_ACTION_TYPE;
CREATE TABLE ENTITY_STAGE_ADMIN_ACTION_TYPE (
    ADMIN_ACTION_CODE INT NOT NULL,
    DESCRIPTION VARCHAR(255),
    UPDATE_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(40),
	IS_ACTIVE VARCHAR(1) DEFAULT NULL,
    PRIMARY KEY (ADMIN_ACTION_CODE)
);


DROP TABLE IF EXISTS ENTITY_STAGE_BATCH;
CREATE TABLE `ENTITY_STAGE_BATCH` (
  `BATCH_ID` int NOT NULL AUTO_INCREMENT,
  `SRC_TYPE_CODE` int DEFAULT NULL,
  `BATCH_STATUS_CODE` int DEFAULT NULL,
  `REVIEW_STATUS_CODE` int DEFAULT NULL,
  `COMPLETION_DATE` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(40) DEFAULT NULL,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`BATCH_ID`),
  KEY `ENTITY_STAGE_BATCH_FK1` (`SRC_TYPE_CODE`),
  KEY `ENTITY_STAGE_BATCH_FK2` (`BATCH_STATUS_CODE`),
  KEY `ENTITY_STAGE_BATCH_FK3` (`REVIEW_STATUS_CODE`),
  CONSTRAINT `ENTITY_STAGE_BATCH_FK1` FOREIGN KEY (`SRC_TYPE_CODE`) REFERENCES `ENTITY_STAGE_BATCH_SOURCE_TYPE` (`SRC_TYPE_CODE`),
  CONSTRAINT `ENTITY_STAGE_BATCH_FK2` FOREIGN KEY (`BATCH_STATUS_CODE`) REFERENCES `ENTITY_STAGE_BATCH_STATUS_TYPE` (`BATCH_STATUS_CODE`),
  CONSTRAINT `ENTITY_STAGE_BATCH_FK3` FOREIGN KEY (`REVIEW_STATUS_CODE`) REFERENCES `ENTITY_STAGE_REVIEW_STATUS_TYPE` (`REVIEW_STATUS_CODE`)
);

DROP TABLE IF EXISTS ENTITY_STAGE_DETAILS;
CREATE TABLE `ENTITY_STAGE_DETAILS` (
  `ENTITY_STAGE_DETAIL_ID` int NOT NULL AUTO_INCREMENT,
  `GROUP_NUMBER` int DEFAULT NULL,
  `BATCH_ID` int DEFAULT NULL,
  `SRC_DATA_TYPE_CODE` varchar(10) DEFAULT NULL,
  `SRC_DATA_CODE` varchar(10) NOT NULL,
  `SRC_DATA_NAME` varchar(500) DEFAULT NULL,
  `SRC_DUNS_NUMBER` varchar(20) DEFAULT NULL,
  `SRC_CAGE_NUMBER` varchar(20) DEFAULT NULL,
  `SRC_UEI` varchar(20) DEFAULT NULL,
  `SRC_EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `SRC_ADDRESS_LINE_1` varchar(255) DEFAULT NULL,
  `SRC_ADDRESS_LINE_2` varchar(255) DEFAULT NULL,
  `SRC_POSTAL_CODE` varchar(15) DEFAULT NULL,
  `SRC_STATE` varchar(30) DEFAULT NULL,
  `SRC_COUNTRY_CODE` varchar(3) DEFAULT NULL,
  `SRC_API_NAME` varchar(1000) DEFAULT NULL,
  `SRC_PHONE_NUMBER` varchar(30) DEFAULT NULL,
  `SRC_CITY` varchar(30) DEFAULT NULL,
  `SRC_WEBSITE` varchar(100) DEFAULT NULL,
  `SRC_ACRONYM` varchar(10) DEFAULT NULL,
  `SRC_RISK_ASSMT_DATE` date DEFAULT NULL,
  `SRC_SAM_EXPIRATION_DATE` date DEFAULT NULL,
  `SRC_HUMAN_SUB_ASSURANCE` varchar(50) DEFAULT NULL,
  `SRC_ANIMAL_WELFARE_ASSURANCE` varchar(50) DEFAULT NULL,
  `SRC_ANIMAL_ACCREDITATION` varchar(50) DEFAULT NULL,
  `INTEGRATION_STATUS_CODE` varchar(3) DEFAULT NULL,
  `API_REQUEST` text,
  `API_RESPONSE` text,
  `SELECTED_DUNS_NUMBERS` varchar(20) DEFAULT NULL,
  `CANDIDATE_MATCHED_QUANTITY` mediumint DEFAULT NULL,
  `DUNS_MATCHED_RESULTS` json DEFAULT NULL,
  `HIGHEST_CONFIDENCE_CODE` tinyint DEFAULT NULL,
  `HTTP_STATUS_CODE` varchar(255) DEFAULT NULL,
  `EXTERNAL_SYS_TRANSACTION_ID` varchar(50) DEFAULT NULL,
  `ERROR_CODE` varchar(10) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(100) DEFAULT NULL,
  `ERROR_DETAILS` text,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `CREATED_BY` varchar(40) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(40) DEFAULT NULL,
  `IS_DUPLICATE_IN_SRC` varchar(1) DEFAULT NULL,
  `ENTITY_ID` int DEFAULT NULL,
  `ADMIN_ACTION_CODE` int DEFAULT NULL,
  `ADMIN_REVIEW_STATUS_CODE` int DEFAULT NULL,
  `MATCH_STATUS_CODE` int DEFAULT NULL,
  PRIMARY KEY (`ENTITY_STAGE_DETAIL_ID`),
  KEY `idx1_ENTITY_STAGE_DETAILS` (`ERROR_CODE`),
  KEY `idx12_ENTITY_STAGE_DETAILS` (`INTEGRATION_STATUS_CODE`),
  KEY `ENTITY_STAGE_DETAILS_FK1` (`BATCH_ID`),
  KEY `ENTITY_STAGE_DETAILS_FK3_idx` (`MATCH_STATUS_CODE`),
  KEY `ENTITY_STAGE_DETAILS_FK4_idx` (`ADMIN_REVIEW_STATUS_CODE`),
  KEY `ENTITY_STAGE_DETAILS_FK5_idx` (`ADMIN_ACTION_CODE`),
  CONSTRAINT `ENTITY_STAGE_DETAILS_FK1` FOREIGN KEY (`BATCH_ID`) REFERENCES `entity_stage_batch` (`BATCH_ID`),
  CONSTRAINT `ENTITY_STAGE_DETAILS_FK2` FOREIGN KEY (`INTEGRATION_STATUS_CODE`) REFERENCES `ENTITY_STAGE_INTEGRATION_STATUS_TYPE` (`INTEGRATION_STATUS_CODE`),
  CONSTRAINT `ENTITY_STAGE_DETAILS_FK3` FOREIGN KEY (`MATCH_STATUS_CODE`) REFERENCES `ENTITY_STAGE_MATCH_STATUS_TYPE` (`MATCH_STATUS_CODE`),
  CONSTRAINT `ENTITY_STAGE_DETAILS_FK4` FOREIGN KEY (`ADMIN_REVIEW_STATUS_CODE`) REFERENCES `ENTITY_STAGE_ADMIN_REVIEW_TYPE` (`ADMIN_REVIEW_STATUS_CODE`),
  CONSTRAINT `ENTITY_STAGE_DETAILS_FK5` FOREIGN KEY (`ADMIN_ACTION_CODE`) REFERENCES `ENTITY_STAGE_ADMIN_ACTION_TYPE` (`ADMIN_ACTION_CODE`)
);
