DELIMITER //
CREATE PROCEDURE GET_AWD_FOR_NOTIFY_DISCL_CREATION (
    IN AV_PERSON_ID VARCHAR(60),
    IN AV_MODULE_ITEM_KEY VARCHAR(200)
)
BEGIN
    DECLARE LS_VALIDATION_FLAG VARCHAR(20);
    DECLARE LS_REQUIRED_FLAG VARCHAR(20);

    -- Fetch DISCLOSURE_VALIDATION_FLAG and DISCLOSURE_REQUIRED_FLAG
    SELECT T1.DISCLOSURE_VALIDATION_FLAG, T2.DISCLOSURE_REQUIRED_FLAG
    INTO LS_VALIDATION_FLAG, LS_REQUIRED_FLAG
    FROM COI_INT_STAGE_AWARD T1
    INNER JOIN COI_INT_STAGE_AWARD_PERSON T2 ON T2.PROJECT_NUMBER = T1.PROJECT_NUMBER
    WHERE T2.KEY_PERSON_ID = AV_PERSON_ID
      AND T1.PROJECT_NUMBER = AV_MODULE_ITEM_KEY
      AND T1.PROJECT_STATUS_CODE IN (1, 6, 3);


    IF LS_VALIDATION_FLAG = 'SELF' THEN

        SELECT AW1.PROJECT_ID, AW1.PROJECT_NUMBER, AW1.TITLE 
        FROM COI_INT_STAGE_AWARD AW1
        INNER JOIN COI_INT_STAGE_AWARD_PERSON AW2 ON AW2.PROJECT_NUMBER = AW1.PROJECT_NUMBER
        WHERE AW1.PROJECT_STATUS_CODE IN (1, 6, 3) 
          AND AW2.KEY_PERSON_ID = AV_PERSON_ID 
          AND AW1.PROJECT_NUMBER = AV_MODULE_ITEM_KEY;

    ELSEIF LS_REQUIRED_FLAG = 'REQUIRED' AND (LS_VALIDATION_FLAG IS NULL OR LS_VALIDATION_FLAG = 'HIERARCHY') THEN

        SELECT AW2.PROJECT_ID, AW2.PROJECT_NUMBER, AW2.TITLE 
        FROM COI_INT_STAGE_AWARD AW1
        INNER JOIN COI_INT_STAGE_AWARD AW2 ON AW2.ROOT_PROJECT_NUMBER = AW1.ROOT_PROJECT_NUMBER
        INNER JOIN COI_INT_STAGE_AWARD_PERSON AW3 ON AW3.PROJECT_NUMBER = AW2.PROJECT_NUMBER
        WHERE AW2.PROJECT_STATUS_CODE IN (1, 6, 3) 
          AND AW3.KEY_PERSON_ID = AV_PERSON_ID 
          AND AW1.PROJECT_NUMBER = AV_MODULE_ITEM_KEY
        ORDER BY AW2.PROJECT_NUMBER LIMIT 1;
		
    END IF;
END //
