DROP PROCEDURE IF EXISTS VALIDATE_PROJECT_DISCLOSURE;
DROP PROCEDURE IF EXISTS GET_COI_PROJECTS;
DROP PROCEDURE IF EXISTS COI_SYNC_INSERT_DISCL_PROJECTS;
DROP PROCEDURE IF EXISTS COI_SYNC_FCOI_DISCLOSURE;
-- DROP VIEW IF EXISTS coi_project_award_v;
DROP FUNCTION FN_CHK_DISCL_SYNC_FLAG_REQ_IN_AWD;