CREATE TABLE FORM_BUILDER_ANS_HEADER (
ANS_HEADER_ID INT NOT NULL AUTO_INCREMENT,
FORM_BUILDER_ID INT DEFAULT NULL,
MODULE_ITEM_CODE INT DEFAULT NULL,
MODULE_SUB_ITEM_CODE INT DEFAULT NULL,
MODULE_ITEM_KEY VARCHAR(20) DEFAULT NULL,
MODULE_SUB_ITEM_KEY VARCHAR(20) DEFAULT NULL,
CREATE_TIMESTAMP DATETIME DEFAULT NULL,
CREATE_USER VARCHAR(60) DEFAULT NULL,
UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
UPDATE_USER VARCHAR(60) DEFAULT NULL,
PRIMARY KEY (ANS_HEADER_ID),
KEY FORM_BUILDER_ANS_HEADER_FK1 (FORM_BUILDER_ID),
CONSTRAINT FORM_BUILDER_ANS_HEADER_FK1 FOREIGN KEY (FORM_BUILDER_ID) REFERENCES FORM_BUILDER_HEADER (FORM_BUILDER_ID));
