DELIMITER //
CREATE PROCEDURE `VALIDATE_PROJECT_DISCLOSURE`(
AV_PERSON_ID varchar(40),
AV_MODULE_CODE int(3),
AV_MODULE_ITEM_ID varchar(40) 
)
BEGIN

    select (select (CASE WHEN count(d.DISCLOSURE_ID) > 0 THEN true ELSE false END) from COI_DISCLOSURE d 
    WHERE d.MODULE_CODE = AV_MODULE_CODE AND d.MODULE_ITEM_KEY = AV_MODULE_ITEM_ID AND d.PERSON_ID = AV_PERSON_ID AND d.EXPIRATION_DATE < CURDATE()) as isExpired,
	(select d.DISCLOSURE_ID from  COI_DISCLOSURE d WHERE d.MODULE_CODE = AV_MODULE_CODE AND d.MODULE_ITEM_KEY = AV_MODULE_ITEM_ID 
    AND d.PERSON_ID = AV_PERSON_ID AND d.VERSION_STATUS = 'PENDING'AND d.FCOI_TYPE_CODE !=1 AND (d.EXPIRATION_DATE IS NULL OR d.EXPIRATION_DATE > CURDATE())) as pendingProject,
	(select DISTINCT d.DISCLOSURE_ID from COI_DISCLOSURE d LEFT JOIN COI_DISCL_ENT_PROJ_DETAILS dd ON dd.DISCLOSURE_ID = d.DISCLOSURE_ID 
	  WHERE dd.MODULE_CODE = AV_MODULE_CODE AND dd.MODULE_ITEM_KEY = AV_MODULE_ITEM_ID AND d.PERSON_ID = AV_PERSON_ID AND d.VERSION_STATUS IN ('PENDING','ACTIVE') 
    AND d.FCOI_TYPE_CODE =1 AND (d.EXPIRATION_DATE IS NULL OR d.EXPIRATION_DATE > CURDATE()) ORDER BY d.DISCLOSURE_ID DESC LIMIT 1) as fcoiProject;
    
END
//