INSERT INTO MQ_ROUTER_TRIGGER_CONFIGURATION (TRIGGER_TYPE, IS_ACTIVE, QUEUE_NAME, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('NOTIFY_PERSON_TRAINING_SYNC_REPORT', 'Y', 'Q_NOTIFICATION', 'Person Training Feed Sync Report Notification', now(), 'quickstart');

INSERT INTO NOTIFICATION_TYPE (NOTIFICATION_TYPE_ID, MODULE_CODE, SUB_MODULE_CODE, DESCRIPTION, SUBJECT, MESSAGE, PROMPT_USER, IS_ACTIVE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, IS_SYSTEM_SPECIFIC) VALUES ('8045', '8', '0', 'Person Training Feed Synchronization Report Notification', 'Person Training Feed Synchronization Report at {PERSON_TRAINING#SYNC_START_DATE_AND_TIME}', '<h2>Person Training Feed Synchronization Report</h2> <p>Dear Team,</p> <p>The person training feed synchronization process has been completed successfully. Below are the process details:</p> <table border="1px" cellspacing="0" cellpadding="5"><tr> <th>Parameter</th><th>Details</th></tr><tr><td><b>Synchronization Start Time</b></td> <td>{PERSON_TRAINING#SYNC_START_DATE_AND_TIME}</td></tr><tr><td><b>Synchronization End Time</b></td><td>{PERSON_TRAINING#SYNC_END_DATE_AND_TIME}</td></tr><tr><td><b>Total Duration</b></td><td>{PERSON_TRAINING#TOTAL_DURATION}</td></tr><tr><td><b>Total Training Records Processed</b></td><td>{PERSON_TRAINING#TOTAL_NO_OF_TRAININGS}</td></tr><tr><td><b>Failed Training Records Count</b></td><td>{PERSON_TRAINING#FAILED_COUNT}</td></tr><tr><td><b>Synchronization Status</b></td><td>{PERSON_TRAINING#PERSON_FEED_SYNC_STATUS}</td></tr> </table> <br> <p><b>Training Records That Were Not Synchronized:</b></p> <br> <p>{PERSON_TRAINING#EXCEPTION_DETAILS}</p> <br> <p><i>Note: This is a system-generated email. Thank you!</i></p> <br>', 'N', 'Y', 'quickstart', now(), 'quickstart', now(), 'Y');

UPDATE NOTIFICATION_TYPE SET MESSAGE = '<h2>Person Feed Synchronization Report</h2> <p>Dear Team,</p> <p>The person feed synchronization process has been completed successfully. Below are the process details:</p> <table border="1px" cellspacing="0" cellpadding="5">    <tr>         <th>Parameter</th>         <th>Details</th>     </tr>     <tr>         <td><b>Synchronization Start Time</b></td>         <td>{PERSON_FEED#SYNC_START_DATE_AND_TIME}</td>     </tr>     <tr>         <td><b>Synchronization End Time</b></td>         <td>{PERSON_FEED#SYNC_END_DATE_AND_TIME}</td>     </tr>     <tr>         <td><b>Total Duration</b></td>         <td>{PERSON_FEED#TOTAL_DURATION}</td>     </tr>     <tr>         <td><b>Total Number of Users Processed</b></td>         <td>{PERSON_FEED#TOTAL_NO_OF_PERSONS}</td>     </tr>    <tr>         <td><b>New Users Added</b></td>         <td>{PERSON_FEED#TOTAL_NO_OF_NEW_PERSONS}</td>     </tr>     <tr>         <td><b>Existing Users Updated</b></td>         <td>{PERSON_FEED#TOTAL_NO_OF_UPDATED_PERSONS}</td>     </tr>    <tr>         <td><b>Synchronization Status</b></td>         <td>{PERSON_FEED#PERSON_FEED_SYNC_STATUS}</td>     </tr> </table> <p><b>Exception Details:</b></p> <p>{PERSON_FEED#EXCEPTION_DETAILS}</p> <br> <p><i>Note: This is a system-generated email. Thank you!</i></p> <br>', SUBJECT = 'Person Feed Synchronization Report at {PERSON_FEED#SYNC_START_DATE_AND_TIME}', UPDATE_TIMESTAMP = now() WHERE (NOTIFICATION_TYPE_ID = '8042');

INSERT INTO NOTIFICATION_RECIPIENT (NOTIFICATION_TYPE_ID, RECIPIENT_PERSON_ID, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, RECIPIENT_TYPE, RECIPIENT_NAME) VALUES ('8042', '921778351', 'quickstart', now(), 'quickstart', now(), 'TO', 'Vineeth');

INSERT INTO NOTIFICATION_RECIPIENT (NOTIFICATION_TYPE_ID, RECIPIENT_PERSON_ID, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP, RECIPIENT_TYPE, RECIPIENT_NAME) VALUES ('8045', '921778351', 'quickstart', now(), 'quickstart', now(), 'TO', 'Vineeth');

INSERT INTO NOTIFY_PLACEHOLDER_HEADER (NOTIFY_PLACEHOLDER_HEADER_ID, MODULE_CODE, SUB_MODULE_CODE, QUERY_TYPE, ELEMENT_TYPE, IS_ACTIVE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, UNIQUE_DISPLAY_NAME) VALUES ('15', '8', '0', 'S', 'S', 'Y', 'Person Training Feed Synchronization Details', now(), 'quickstart', 'PERSON_TRAINING');

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('15', 'SYNC_START_DATE_AND_TIME', 'Start Date and Time', now(), 'quickstart');

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('15', 'SYNC_END_DATE_AND_TIME', 'End Date and Time', now(), 'quickstart');

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('15', 'TOTAL_DURATION', 'Duration', now(), 'quickstart');

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('15', 'TOTAL_NO_OF_TRAININGS', 'Total Count of  Person''s Training', now(), 'quickstart');

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('15', 'FAILED_COUNT', 'Failed Person''s Training Count', now(), 'quickstart');

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('15', 'EXCEPTION_DETAILS', 'Exception Details', now(), 'quickstart');

INSERT INTO NOTIFY_PLACEHOLDER_COLUMNS (NOTIFY_PLACEHOLDER_HEADER_ID, QUERY_COLUMN_NAME, LABEL_NAME, UPDATE_TIMESTAMP, UPDATE_USER) VALUES ('15', 'PERSON_FEED_SYNC_STATUS', 'Status', now(), 'quickstart');
