INSERT INTO `COI_DISPOSITION_STATUS_TYPE` (`DISPOSITION_STATUS_CODE`,`DESCRIPTION`,`IS_ACTIVE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`SORT_ORDER`) VALUES ('4','Expired','Y',now(),'admin',4);

INSERT INTO `OPA_DISPOSITION_STATUS_TYPE` (`DISPOSITION_STATUS_CODE`,`DESCRIPTION`,`IS_ACTIVE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`SORT_ORDER`) VALUES ('4','Expired','Y',now(),'admin',4);

INSERT INTO `OPA_ACTION_LOG_TYPE` (`ACTION_TYPE_CODE`,`MESSAGE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('22','OPA disclosure <b>expired</b>','Expired',now(),'admin');

INSERT INTO `MQ_ROUTER_TRIGGER_CONFIGURATION` (`TRIGGER_TYPE`,`IS_ACTIVE`,`QUEUE_NAME`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('NOTIFY_OPA_DISCLOSURE_EXPIRED','Y','Q_NOTIFICATION','OPA Disclosure Expired',now(),'admin');
INSERT INTO `MQ_ROUTER_TRIGGER_CONFIGURATION` (`TRIGGER_TYPE`,`IS_ACTIVE`,`QUEUE_NAME`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('NOTIFY_FCOI_DISCLOSURE_EXPIRED','Y','Q_NOTIFICATION','FCOI Disclosure Expired',now(),'admin');
INSERT INTO `MQ_ROUTER_TRIGGER_CONFIGURATION` (`TRIGGER_TYPE`,`IS_ACTIVE`,`QUEUE_NAME`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('NOTIFY_PROJECT_DISCLOSURE_EXPIRED','Y','Q_NOTIFICATION','Project Disclosure Expired',now(),'admin');

INSERT INTO `NOTIFICATION_TYPE` (`NOTIFICATION_TYPE_ID`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`SUBJECT`,`MESSAGE`,`PROMPT_USER`,`IS_ACTIVE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`IS_SYSTEM_SPECIFIC`,`SHOW_TEMPLATE_IN_MODULE`,`SENT_TO_INITIATOR`) VALUES (8078,23,0,'OPA Disclosure Expired Notification','Your OPA Disclosure Has Expired','<p style=\"margin-left:0px;\"><strong>Dear </strong>{OPA_DETAILS#REPORTER_NAME},</p><p style=\"margin-left:0px;\"><span style=\"background-color:rgb(255,255,255);color:rgb(64,64,64);\">Your OPA disclosure has expired as it reached its expiration date. Below are the details:</span></p><p style=\"margin-left:0px;\"><strong>Department: </strong>{OPA_DETAILS#DEPARTMENT_NUMBER} - {OPA_DETAILS#DEPARTMENT_NAME}</p><p style=\"margin-left:0px;\"><strong>Certification Date:</strong> <span style=\"background-color:rgb(255,255,255);color:rgb(0,0,0);\">{OPA_DETAILS#CERTIFICATION_DATE}</span></p><p style=\"margin-left:0px;\"><strong>Expiration Date:</strong> <span style=\"background-color:rgb(255,255,255);color:rgb(0,0,0);\">{OPA_DETAILS#EXPIRATION_DATE}</span></p><p style=\"margin-left:0px;\"><strong>Disposition Status</strong>: {OPA_DETAILS#DISPOSITION_STATUS}</p><p style=\"margin-left:0px;\">Please follow <a href=\"{OPA_URL#OPA_URL}\">this link</a> to review the application.</p><p>Note: This is a system-generated email. Please do not reply to this email.</p>','N','Y','admin',now(),'admin',now(),'Y',NULL,NULL);
INSERT INTO `NOTIFICATION_TYPE` (`NOTIFICATION_TYPE_ID`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`SUBJECT`,`MESSAGE`,`PROMPT_USER`,`IS_ACTIVE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`IS_SYSTEM_SPECIFIC`,`SHOW_TEMPLATE_IN_MODULE`,`SENT_TO_INITIATOR`) VALUES (8079,8,0,'Financial COI Disclosure Expired Notification',' Your FCOI Disclosure Has Expired','<p style=\"margin-left:0px;\"><strong>Dear </strong>{COI_DISCLOSURE#REPORTER_NAME},</p><p style=\"margin-left:0px;\"><span style=\"background-color:rgb(255,255,255);color:rgb(64,64,64);\">Your FCOI disclosure has expired as it reached its expiration date. Below are the details:</span></p><p style=\"margin-left:0px;\"><strong>Department: </strong>{COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p style=\"margin-left:0px;\"><strong>Certification Date:</strong> <span style=\"background-color:rgb(255,255,255);color:rgb(0,0,0);\">{COI_DISCLOSURE#CERTIFICATION_DATE}</span></p><p style=\"margin-left:0px;\"><strong>Expiration Date:</strong> <span style=\"background-color:rgb(255,255,255);color:rgb(0,0,0);\">{COI_DISCLOSURE#EXPIRATION_DATE}</span></p><p style=\"margin-left:0px;\"><strong>Disposition Status</strong>: {COI_DISCLOSURE#DISPOSITION_STATUS}</p><p style=\"margin-left:0px;\"><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>','N','Y','admin',now(),'admin',now(),'Y',NULL,NULL);
INSERT INTO `NOTIFICATION_TYPE` (`NOTIFICATION_TYPE_ID`,`MODULE_CODE`,`SUB_MODULE_CODE`,`DESCRIPTION`,`SUBJECT`,`MESSAGE`,`PROMPT_USER`,`IS_ACTIVE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`IS_SYSTEM_SPECIFIC`,`SHOW_TEMPLATE_IN_MODULE`,`SENT_TO_INITIATOR`) VALUES (8080,8,0,'Project Disclosure Expired Notification','Your Project Disclosure Has Expired','<p style=\"margin-left:0px;\"><strong>Dear </strong>{COI_DISCLOSURE#REPORTER_NAME},</p><p style=\"margin-left:0px;\"><span style=\"background-color:rgb(255,255,255);color:rgb(64,64,64);\">Your Project disclosure has expired as it reached its expiration date. Below are the details:</span></p><p style=\"margin-left:0px;\"><strong>Department: </strong>{COI_DISCLOSURE#DEPARTMENT_NUMBER} - {COI_DISCLOSURE#DEPARTMENT_NAME}</p><p style=\"margin-left:0px;\"><strong>Certification Date:</strong> <span style=\"background-color:rgb(255,255,255);color:rgb(0,0,0);\">{COI_DISCLOSURE#CERTIFICATION_DATE}</span></p><p style=\"margin-left:0px;\"><strong>Expiration Date:</strong> <span style=\"background-color:rgb(255,255,255);color:rgb(0,0,0);\">{COI_DISCLOSURE#EXPIRATION_DATE}</span></p><p style=\"margin-left:0px;\"><strong>Disposition Status</strong>: {COI_DISCLOSURE#DISPOSITION_STATUS}</p><p style=\"margin-left:0px;\"><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">Please follow</span><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><a href=\"{COI_DISCL_URL#DISCLOSURE_URL}\"><span style=\"font-family:Arial, Helvetica, sans-serif;\">this link</span></a><span style=\"color:rgb(23,43,77);font-family:Arial, Helvetica, sans-serif;\"> </span><span style=\"color:hsl(0,0%,0%);font-family:Arial, Helvetica, sans-serif;\">to review the application.</span></p><p>Note: This is a system-generated email. Please do not reply to this email.</p>','N','Y','admin',now(),'admin',now(),'Y',NULL,NULL);

INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8078,NULL,68,NULL,now(),NULL,NULL,'TO','OPA Reporter');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8078,NULL,69,NULL,now(),NULL,NULL,'CC','OPA Admin Group');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8079,NULL,53,NULL,now(),NULL,NULL,'TO','COI Reporter');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8079,NULL,54,NULL,now(),NULL,NULL,'CC','COI Admin Group');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8080,NULL,53,NULL,now(),NULL,NULL,'TO','COI Reporter');
INSERT INTO `NOTIFICATION_RECIPIENT` (`NOTIFICATION_TYPE_ID`,`RECIPIENT_PERSON_ID`,`ROLE_TYPE_CODE`,`CREATE_USER`,`CREATE_TIMESTAMP`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`RECIPIENT_TYPE`,`RECIPIENT_NAME`) VALUES (8080,NULL,54,NULL,now(),NULL,NULL,'CC','COI Admin Group');
