DELIMITER //
CREATE FUNCTION `FN_PERSON_HAS_SFI_IN_DISCLOSURE`(AV_PERSON_ID VARCHAR(45)) RETURNS VARCHAR(6)
	NOT DETERMINISTIC
    READS SQL DATA
BEGIN
DECLARE LI_COUNT INT;

-- Check if the person has review submitted and pending disclosure
SELECT COUNT(*)
INTO LI_COUNT
FROM COI_DISCLOSURE 
WHERE PERSON_ID = AV_PERSON_ID
	AND VERSION_STATUS = 'PENDING'
	AND REVIEW_STATUS_CODE IN ('2', '3', '4', '7', '8');

-- Checks whether a person has at least one pending disclosure that contains a linked entity flagged with Significant Financial Interest (SFI).
IF LI_COUNT > 0 THEN
	SET LI_COUNT = 0;

	SELECT COUNT(*)
    INTO LI_COUNT
	FROM PERSON_ENTITY PE
	JOIN COI_DISCL_PERSON_ENTITY_REL CDPEL 
		ON CDPEL.PERSON_ENTITY_ID = PE.PERSON_ENTITY_ID
	JOIN COI_DISCLOSURE CD 
		ON CD.DISCLOSURE_ID = CDPEL.DISCLOSURE_ID
	WHERE CD.PERSON_ID = AV_PERSON_ID
		AND CD.VERSION_STATUS = 'PENDING'
		AND CD.REVIEW_STATUS_CODE IN ('2', '3', '4', '7', '8')
		AND PE.IS_SIGNIFICANT_FIN_INTEREST = 'Y';
        
ELSE
-- Checks whether a person has at least one active disclosure that contains a linked entity flagged with Significant Financial Interest (SFI).
	SELECT COUNT(*)
    INTO LI_COUNT
	FROM PERSON_ENTITY PE
	JOIN COI_DISCL_PERSON_ENTITY_REL CDPEL 
		ON CDPEL.PERSON_ENTITY_ID = PE.PERSON_ENTITY_ID
	JOIN COI_DISCLOSURE CD 
		ON CD.DISCLOSURE_ID = CDPEL.DISCLOSURE_ID
	WHERE CD.PERSON_ID = AV_PERSON_ID
		AND CD.VERSION_STATUS = 'ACTIVE'
		AND PE.IS_SIGNIFICANT_FIN_INTEREST = 'Y';
END IF;

IF LI_COUNT > 0 THEN
	RETURN 'TRUE';
END IF;

RETURN 'FALSE';
END
//
