SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS discl_valid_compnent_comnt_ty;

DROP TABLE IF EXISTS ENTITY_TYPE;
CREATE TABLE ENTITY_TYPE (
  ENTITY_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ENTITY_TYPE_CODE)
);

DROP TABLE IF EXISTS ENTITY_STATUS;
CREATE TABLE ENTITY_STATUS (
  ENTITY_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ENTITY_STATUS_CODE)
);

DROP TABLE IF EXISTS ENTITY_RISK_CATEGORY;
CREATE TABLE ENTITY_RISK_CATEGORY (
  RISK_CATEGORY_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(45) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (RISK_CATEGORY_CODE)
);

DROP TABLE IF EXISTS ENTITY;
CREATE TABLE ENTITY (
  ENTITY_ID int NOT NULL AUTO_INCREMENT,
  ENTITY_NUMBER int DEFAULT NULL,
  ENTITY_NAME varchar(90) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  VERSION_NUMBER int DEFAULT NULL,
  VERSION_STATUS varchar(45) DEFAULT NULL,
  ENTITY_STATUS_CODE varchar(3) DEFAULT NULL,
  ENTITY_TYPE_CODE varchar(3) DEFAULT NULL,
  RISK_CATEGORY_CODE varchar(3) DEFAULT NULL,
  PHONE varchar(45) DEFAULT NULL,
  COUNTRY_CODE varchar(3) DEFAULT NULL,
  CITY varchar(90) DEFAULT NULL,
  ADDRESS varchar(2000) DEFAULT NULL,
  ZIP_CODE varchar(15) DEFAULT NULL,
  EMAIL_ADDRESS varchar(60) DEFAULT NULL,
  WEB_URL varchar(2000) DEFAULT NULL,
  CREATE_USER varchar(60) DEFAULT NULL,
  CREATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  APPROVED_USER varchar(60) DEFAULT NULL,
  APPROVED_TIMESTAMP datetime DEFAULT NULL,
  REVISION_REASON varchar(500) DEFAULT NULL,
  PRIMARY KEY (ENTITY_ID),
  KEY ENTITY_FK1_idx (ENTITY_STATUS_CODE),
  KEY ENTITY_FK2_idx (ENTITY_TYPE_CODE),
  KEY ENTITY_FK3_idx (COUNTRY_CODE),
  KEY ENTITY_FK5_idx (RISK_CATEGORY_CODE),
  CONSTRAINT ENTITY1_FK1 FOREIGN KEY (ENTITY_STATUS_CODE) REFERENCES entity_status (ENTITY_STATUS_CODE),
  CONSTRAINT ENTITY1_FK2 FOREIGN KEY (ENTITY_TYPE_CODE) REFERENCES entity_type (ENTITY_TYPE_CODE),
  CONSTRAINT ENTITY1_FK3 FOREIGN KEY (COUNTRY_CODE) REFERENCES country (COUNTRY_CODE),
  CONSTRAINT ENTITY1_FK5 FOREIGN KEY (RISK_CATEGORY_CODE) REFERENCES entity_risk_category (RISK_CATEGORY_CODE)
);

DROP TABLE IF EXISTS ENTITY_RELATIONSHIP_TYPE;
CREATE TABLE ENTITY_RELATIONSHIP_TYPE (
  ENTITY_REL_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ENTITY_REL_TYPE_CODE)
);

DROP TABLE IF EXISTS ENTITY_REL_NODE_TYPE;
CREATE TABLE ENTITY_REL_NODE_TYPE (
  REL_NODE_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (REL_NODE_TYPE_CODE)
);

DROP TABLE IF EXISTS ENTITY_RELATIONSHIP;
CREATE TABLE ENTITY_RELATIONSHIP (
  ID int NOT NULL AUTO_INCREMENT,
  ENTITY_NUMBER int NOT NULL,
  NODE_TYPE_CODE varchar(3) DEFAULT NULL,
  NODE_ID int DEFAULT NULL,
  ENTITY_REL_TYPE_CODE varchar(3) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY ENITY_RELATIONSHIP_FK1_idx (ENTITY_REL_TYPE_CODE),
  KEY ENITY_RELATIONSHIP_FK2_idx (NODE_TYPE_CODE),
  CONSTRAINT ENITY_RELATIONSHIP_FK1 FOREIGN KEY (ENTITY_REL_TYPE_CODE) REFERENCES entity_relationship_type (ENTITY_REL_TYPE_CODE),
  CONSTRAINT ENITY_RELATIONSHIP_FK2 FOREIGN KEY (NODE_TYPE_CODE) REFERENCES entity_rel_node_type (REL_NODE_TYPE_CODE)
);

DROP TABLE IF EXISTS PERSON_ENTITY;
CREATE TABLE PERSON_ENTITY (
  PERSON_ENTITY_ID int NOT NULL AUTO_INCREMENT,
  PERSON_ID varchar(45) DEFAULT NULL,
  ENTITY_ID int DEFAULT NULL,
  ENTITY_NUMBER int DEFAULT NULL,
  IS_FORM_COMPLETED varchar(1) DEFAULT NULL,
  VERSION_NUMBER int DEFAULT NULL,
  VERSION_STATUS varchar(45) DEFAULT NULL,
  SPONSORS_RESEARCH varchar(1) DEFAULT NULL,
  INVOLVEMENT_START_DATE date DEFAULT NULL,
  INVOLVEMENT_END_DATE date DEFAULT NULL,
  STUDENT_INVOLVEMENT varchar(4000) DEFAULT NULL,
  STAFF_INVOLVEMENT varchar(4000) DEFAULT NULL,
  INSTITUTE_RESOURCE_INVOLVEMENT varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  CREATE_TIMESTAMP datetime DEFAULT NULL,
  CREATE_USER varchar(60) DEFAULT NULL,
  PERSON_ENTITY_NUMBER int DEFAULT NULL,
  REVISION_REASON varchar(100) DEFAULT NULL,
  PRIMARY KEY (PERSON_ENTITY_ID),
  KEY PERSON_ENTITY_FK1_idx (PERSON_ID),
  KEY PERSON_ENTITY_FK2_idx (ENTITY_ID),
  CONSTRAINT PERSON_ENTITY_FK1 FOREIGN KEY (PERSON_ID) REFERENCES person (PERSON_ID),
  CONSTRAINT PERSON_ENTITY_FK2 FOREIGN KEY (ENTITY_ID) REFERENCES entity (ENTITY_ID)
);

DROP TABLE IF EXISTS COI_DISCLOSURE_TYPE;
CREATE TABLE COI_DISCLOSURE_TYPE (
  DISCLOSURE_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (DISCLOSURE_TYPE_CODE)
);

DROP TABLE IF EXISTS PERSON_ENTITY_REL_TYPE;
CREATE TABLE PERSON_ENTITY_REL_TYPE (
  RELATIONSHIP_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (RELATIONSHIP_TYPE_CODE)
);

DROP TABLE IF EXISTS VALID_PERSON_ENTITY_REL_TYPE;
CREATE TABLE VALID_PERSON_ENTITY_REL_TYPE (
  VALID_PERS_ENTITY_REL_TYP_CODE int NOT NULL AUTO_INCREMENT,
  DISCLOSURE_TYPE_CODE varchar(3) DEFAULT NULL,
  RELATIONSHIP_TYPE_CODE varchar(3) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  QUESTIONNAIRE_NUMBER int DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (VALID_PERS_ENTITY_REL_TYP_CODE),
  KEY VALID_PERSON_ENTITY_REL_TYPE_FK1_idx (DISCLOSURE_TYPE_CODE),
  KEY VALID_PERSON_ENTITY_REL_TYPE_FK2_idx (RELATIONSHIP_TYPE_CODE),
  CONSTRAINT VALID_PERSON_ENTITY_REL_TYPE_FK1 FOREIGN KEY (DISCLOSURE_TYPE_CODE) REFERENCES coi_disclosure_type (DISCLOSURE_TYPE_CODE),
  CONSTRAINT VALID_PERSON_ENTITY_REL_TYPE_FK2 FOREIGN KEY (RELATIONSHIP_TYPE_CODE) REFERENCES person_entity_rel_type (RELATIONSHIP_TYPE_CODE)
);

DROP TABLE IF EXISTS PERSON_ENTITY_RELATIONSHIP;
CREATE TABLE PERSON_ENTITY_RELATIONSHIP (
  PERSON_ENTITY_REL_ID int NOT NULL AUTO_INCREMENT,
  PERSON_ENTITY_ID int DEFAULT NULL,
  VALID_PERS_ENTITY_REL_TYP_CODE int DEFAULT NULL,
  QUESTIONNAIRE_ANS_HEADER_ID int DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  START_DATE date DEFAULT NULL,
  END_DATE date DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (PERSON_ENTITY_REL_ID),
  KEY PERSON_ENTITY_RELATIONSHIP_FK1_idx (PERSON_ENTITY_ID),
  KEY PERSON_ENTITY_RELATIONSHIP_FK2_idx (VALID_PERS_ENTITY_REL_TYP_CODE),
  CONSTRAINT PERSON_ENTITY_RELATIONSHIP_FK1 FOREIGN KEY (PERSON_ENTITY_ID) REFERENCES person_entity (PERSON_ENTITY_ID),
  CONSTRAINT PERSON_ENTITY_RELATIONSHIP_FK2 FOREIGN KEY (VALID_PERS_ENTITY_REL_TYP_CODE) REFERENCES valid_person_entity_rel_type (VALID_PERS_ENTITY_REL_TYP_CODE)
);


DROP TABLE IF EXISTS COI_PROJECT_TYPE;
CREATE TABLE COI_PROJECT_TYPE (
  COI_PROJECT_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (COI_PROJECT_TYPE_CODE)
);

DROP TABLE IF EXISTS COI_PROJECT_PROPOSAL;
CREATE TABLE COI_PROJECT_PROPOSAL (
  ID int NOT NULL AUTO_INCREMENT,
  EXTERNAL_SYSTEM_REF_ID int DEFAULT NULL,
  COI_PROJECT_TYPE_CODE varchar(3) DEFAULT NULL,
  PROPOSAL_NUMBER varchar(45) DEFAULT NULL,
  TITLE varchar(2000) DEFAULT NULL,
  PI_PERSON_ID varchar(45) DEFAULT NULL,
  PI_NAME varchar(60) DEFAULT NULL,
  SPONSOR_NAME varchar(200) DEFAULT NULL,
  PRIME_SPONSOR_NAME varchar(200) DEFAULT NULL,
  PROPOSAL_START_DATE date DEFAULT NULL,
  PROPOSAL_END_DATE date DEFAULT NULL,
  LEAD_UNIT_NAME varchar(45) DEFAULT NULL,
  FED_AT datetime DEFAULT NULL,
  coi_project_proposalcol varchar(45) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  KEY_PERSON_ID varchar(45) DEFAULT NULL,
  KEY_PERSON_NAME varchar(60) DEFAULT NULL,
  KEY_PERSON_ROLE_CODE int DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY COI_PROJECT_PROPOSAL_FK1_idx (COI_PROJECT_TYPE_CODE),
  CONSTRAINT COI_PROJECT_PROPOSAL_FK1 FOREIGN KEY (COI_PROJECT_TYPE_CODE) REFERENCES coi_project_type (COI_PROJECT_TYPE_CODE)
);

DROP TABLE IF EXISTS COI_PROJECT_AWARD;
CREATE TABLE COI_PROJECT_AWARD (
  ID int NOT NULL AUTO_INCREMENT,
  EXTERNAL_SYSTEM_REF_ID int DEFAULT NULL,
  COI_PROJECT_TYPE_CODE varchar(3) DEFAULT NULL,
  AWARD_NUMBER varchar(45) DEFAULT NULL,
  TITLE varchar(2000) DEFAULT NULL,
  PI_PERSON_ID varchar(45) DEFAULT NULL,
  PI_NAME varchar(60) DEFAULT NULL,
  SPONSOR_NAME varchar(200) DEFAULT NULL,
  PRIME_SPONSOR_NAME varchar(200) DEFAULT NULL,
  AWARD_START_DATE date DEFAULT NULL,
  AWARD_END_DATE date DEFAULT NULL,
  LEAD_UNIT_NAME varchar(45) DEFAULT NULL,
  FED_AT datetime DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  KEY_PERSON_ID varchar(45) DEFAULT NULL,
  KEY_PERSON_NAME varchar(60) DEFAULT NULL,
  KEY_PERSON_ROLE_CODE int DEFAULT NULL,
  ACCOUNT_NUMBER varchar(100) DEFAULT NULL,
  SPONSOR_AWARD_NUMBER varchar(70) DEFAULT NULL,
  PROJECT_ROLE varchar(60) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY COI_PROJECT_AWARD_FK1_idx (COI_PROJECT_TYPE_CODE),
  CONSTRAINT COI_PROJECT_AWARD_FK1 FOREIGN KEY (COI_PROJECT_TYPE_CODE) REFERENCES coi_project_type (COI_PROJECT_TYPE_CODE)
);

DROP TABLE IF EXISTS COI_DISCLOSURE_FCOI_TYPE;
CREATE TABLE COI_DISCLOSURE_FCOI_TYPE (
  FCOI_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (FCOI_TYPE_CODE)
);

DROP TABLE IF EXISTS COI_CONFLICT_STATUS_TYPE;
CREATE TABLE COI_CONFLICT_STATUS_TYPE (
  CONFLICT_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (CONFLICT_STATUS_CODE)
);

DROP TABLE IF EXISTS COI_DISPOSITION_STATUS_TYPE;
CREATE TABLE COI_DISPOSITION_STATUS_TYPE (
  DISPOSITION_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (DISPOSITION_STATUS_CODE)
);

DROP TABLE IF EXISTS COI_REVIEW_STATUS_TYPE;
CREATE TABLE COI_REVIEW_STATUS_TYPE (
  REVIEW_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (REVIEW_STATUS_CODE)
);

DROP TABLE IF EXISTS COI_RISK_CATEGORY;
CREATE TABLE COI_RISK_CATEGORY (
  RISK_CATEGORY_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (RISK_CATEGORY_CODE)
);

DROP TABLE IF EXISTS COI_DISCLOSURE;
CREATE TABLE COI_DISCLOSURE (
  DISCLOSURE_ID int NOT NULL AUTO_INCREMENT,
  PERSON_ID varchar(45) DEFAULT NULL,
  DISCLOSURE_NUMBER int DEFAULT NULL,
  VERSION_NUMBER int DEFAULT NULL,
  VERSION_STATUS varchar(45) DEFAULT NULL,
  FCOI_TYPE_CODE varchar(3) DEFAULT NULL,
  CONFLICT_STATUS_CODE varchar(3) DEFAULT NULL,
  DISPOSITION_STATUS_CODE varchar(3) DEFAULT NULL,
  REVIEW_STATUS_CODE varchar(3) DEFAULT NULL,
  RISK_CATEGORY_CODE varchar(3) DEFAULT NULL,
  MODULE_CODE int DEFAULT NULL,
  MODULE_ITEM_KEY varchar(20) DEFAULT NULL,
  EXPIRATION_DATE date DEFAULT NULL,
  CERTIFICATION_TEXT varchar(1000) DEFAULT NULL,
  CERTIFIED_BY varchar(60) DEFAULT NULL,
  CERTIFIED_AT datetime DEFAULT NULL,
  REVISION_COMMENT varchar(1000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  CREATE_USER varchar(60) DEFAULT NULL,
  CREATE_TIMESTAMP datetime DEFAULT NULL,
  HOME_UNIT varchar(8) DEFAULT NULL,
  ADMIN_GROUP_ID int DEFAULT NULL,
  ADMIN_PERSON_ID varchar(45) DEFAULT NULL,
  PRIMARY KEY (DISCLOSURE_ID),
  KEY COI_DISCLOSURE1_FK1_idx (PERSON_ID),
  KEY COI_DISCLOSURE1_FK2_idx (FCOI_TYPE_CODE),
  KEY COI_DISCLOSURE1_FK3_idx (CONFLICT_STATUS_CODE),
  KEY COI_DISCLOSURE1_FK4_idx (DISPOSITION_STATUS_CODE),
  KEY COI_DISCLOSURE1_FK5_idx (REVIEW_STATUS_CODE),
  KEY COI_DISCLOSURE1_FK6_idx (RISK_CATEGORY_CODE),
  KEY COI_DIS_HOME_UNIT_FK7 (HOME_UNIT),
  CONSTRAINT COI_DIS_HOME_UNIT_FK7 FOREIGN KEY (HOME_UNIT) REFERENCES unit (UNIT_NUMBER),
  CONSTRAINT COI_DISCLOSURE1_FK1 FOREIGN KEY (PERSON_ID) REFERENCES person (PERSON_ID),
  CONSTRAINT COI_DISCLOSURE1_FK2 FOREIGN KEY (FCOI_TYPE_CODE) REFERENCES coi_disclosure_fcoi_type (FCOI_TYPE_CODE),
  CONSTRAINT COI_DISCLOSURE1_FK3 FOREIGN KEY (CONFLICT_STATUS_CODE) REFERENCES coi_conflict_status_type (CONFLICT_STATUS_CODE),
  CONSTRAINT COI_DISCLOSURE1_FK4 FOREIGN KEY (DISPOSITION_STATUS_CODE) REFERENCES coi_disposition_status_type (DISPOSITION_STATUS_CODE),
  CONSTRAINT COI_DISCLOSURE1_FK5 FOREIGN KEY (REVIEW_STATUS_CODE) REFERENCES coi_review_status_type (REVIEW_STATUS_CODE),
  CONSTRAINT COI_DISCLOSURE1_FK6 FOREIGN KEY (RISK_CATEGORY_CODE) REFERENCES coi_risk_category (RISK_CATEGORY_CODE)
);

DROP TABLE IF EXISTS COI_PROJ_CONFLICT_STATUS_TYPE;
CREATE TABLE COI_PROJ_CONFLICT_STATUS_TYPE (
  PROJECT_CONFLICT_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (PROJECT_CONFLICT_STATUS_CODE)
);

DROP TABLE IF EXISTS COI_DISCL_ENT_PROJ_DETAILS;
CREATE TABLE COI_DISCL_ENT_PROJ_DETAILS (
  DISCLOSURE_DETAILS_ID int NOT NULL AUTO_INCREMENT,
  DISCLOSURE_ID int DEFAULT NULL,
  DISCLOSURE_NUMBER varchar(45) DEFAULT NULL,
  PERSON_ENTITY_ID int DEFAULT NULL,
  ENTITY_ID int DEFAULT NULL,
  ENTITY_NUMBER int DEFAULT NULL,
  MODULE_CODE int DEFAULT NULL,
  MODULE_ITEM_KEY varchar(20) DEFAULT NULL,
  PROJECT_CONFLICT_STATUS_CODE varchar(3) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PERSON_ENTITY_NUMBER int DEFAULT NULL,
  PREVIOUS_PERSON_ENTITY_ID int DEFAULT NULL,
  PRIMARY KEY (DISCLOSURE_DETAILS_ID),
  KEY COI_DISCL_ENT_PROJ_DETAILS_FK1_idx (DISCLOSURE_ID),
  KEY COI_DISCL_ENT_PROJ_DETAILS_FK2_idx (PERSON_ENTITY_ID),
  KEY COI_DISCL_ENT_PROJ_DETAILS_FK3_idx (ENTITY_ID),
  KEY COI_DISCL_ENT_PROJ_DETAILS_FK4_idx (PROJECT_CONFLICT_STATUS_CODE),
  KEY COI_DISCL_ENT_PROJ_DETAILS_FK5_idx (PREVIOUS_PERSON_ENTITY_ID),
  CONSTRAINT COI_DISCL_ENT_PROJ_DETAILS_FK1 FOREIGN KEY (DISCLOSURE_ID) REFERENCES coi_disclosure (DISCLOSURE_ID),
  CONSTRAINT COI_DISCL_ENT_PROJ_DETAILS_FK2 FOREIGN KEY (PERSON_ENTITY_ID) REFERENCES person_entity (PERSON_ENTITY_ID),
  CONSTRAINT COI_DISCL_ENT_PROJ_DETAILS_FK3 FOREIGN KEY (ENTITY_ID) REFERENCES entity (ENTITY_ID),
  CONSTRAINT COI_DISCL_ENT_PROJ_DETAILS_FK4 FOREIGN KEY (PROJECT_CONFLICT_STATUS_CODE) REFERENCES coi_proj_conflict_status_type (PROJECT_CONFLICT_STATUS_CODE),
  CONSTRAINT COI_DISCL_ENT_PROJ_DETAILS_FK5 FOREIGN KEY (PREVIOUS_PERSON_ENTITY_ID) REFERENCES person_entity (PERSON_ENTITY_ID)
);

DROP TABLE IF EXISTS DISCL_ATTA_STATUS;
CREATE TABLE DISCL_ATTA_STATUS (
  ATTA_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ATTA_STATUS_CODE)
);

DROP TABLE IF EXISTS DISCL_FILE_DATA;
CREATE TABLE DISCL_FILE_DATA (
  FILE_DATA_ID varchar(100) NOT NULL,
  MODULE_CODE varchar(3) DEFAULT NULL,
  FILE_PATH varchar(255) DEFAULT NULL,
  ORIGINAL_FILE_NAME varchar(500) DEFAULT NULL,
  FILE_NAME varchar(100) DEFAULT NULL,
  IS_ARCHIVED char(1) DEFAULT NULL,
  DATA longblob,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (FILE_DATA_ID)
);

DROP TABLE IF EXISTS DISCL_ATTA_TYPE;
CREATE TABLE DISCL_ATTA_TYPE (
  ATTA_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ATTA_TYPE_CODE)
);

DROP TABLE IF EXISTS DISCL_COMPONENT_TYPE;
CREATE TABLE DISCL_COMPONENT_TYPE (
  COMPONENT_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (COMPONENT_TYPE_CODE)
);

DROP TABLE IF EXISTS DISCL_VALID_COMPNENT_ATTA_TY;
CREATE TABLE DISCL_VALID_COMPNENT_ATTA_TY (
  ID int NOT NULL AUTO_INCREMENT,
  COMPONENT_TYPE_CODE varchar(3) DEFAULT NULL,
  ATTA_TYPE_CODE varchar(3) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY DISCL_VALID_COMPONENT_ATTA_TYPE_FK1_idx (COMPONENT_TYPE_CODE),
  KEY DISCL_VALID_COMPONENT_ATTA_TYPE_FK2_idx (ATTA_TYPE_CODE),
  CONSTRAINT DISCL_VALID_COMPONENT_ATTA_TYPE_FK1 FOREIGN KEY (COMPONENT_TYPE_CODE) REFERENCES discl_component_type (COMPONENT_TYPE_CODE) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT DISCL_VALID_COMPONENT_ATTA_TYPE_FK2 FOREIGN KEY (ATTA_TYPE_CODE) REFERENCES discl_atta_type (ATTA_TYPE_CODE) ON DELETE RESTRICT ON UPDATE RESTRICT
);

DROP TABLE IF EXISTS DISCL_COMMENT_TYPE;
CREATE TABLE DISCL_COMMENT_TYPE (
  COMMENT_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (COMMENT_TYPE_CODE)
);

DROP TABLE IF EXISTS DISCL_COMMENT;
CREATE TABLE DISCL_COMMENT (
  COMMENT_ID int NOT NULL AUTO_INCREMENT,
  DOCUMENT_OWNER_PERSON_ID varchar(45) DEFAULT NULL,
  COMMENT_BY_PERSON_ID varchar(45) DEFAULT NULL,
  COMMENT_TYPE_CODE varchar(3) DEFAULT NULL,
  COMPONENT_TYPE_CODE varchar(3) DEFAULT NULL,
  PARENT_COMMENT_ID int DEFAULT NULL,
  IS_PRIVATE varchar(1) DEFAULT NULL,
  COMMENT text,
  MODULE_ITEM_KEY int DEFAULT NULL,
  MODULE_ITEM_NUMBER varchar(11) DEFAULT NULL,
  SUB_MODULE_ITEM_KEY int DEFAULT NULL,
  SUB_MODULE_ITEM_NUMBER varchar(11) DEFAULT NULL,
  MODULE_CODE int NOT NULL,
  SUB_MODULE_CODE int DEFAULT NULL,
  FORM_BUILDER_ID int DEFAULT NULL,
  FORM_BUILDER_SECTION_ID int DEFAULT NULL,
  FORM_BUILDER_COMPONENT_ID int DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  PRIMARY KEY (COMMENT_ID),
  KEY DISCL_COMMENT_FK1_idx (COMPONENT_TYPE_CODE),
  KEY DISCL_COMMENT_FK2_idx (COMMENT_TYPE_CODE),
  CONSTRAINT DISCL_COMMENT_FK1 FOREIGN KEY (COMPONENT_TYPE_CODE) REFERENCES discl_component_type (COMPONENT_TYPE_CODE),
  CONSTRAINT DISCL_COMMENT_FK2 FOREIGN KEY (COMMENT_TYPE_CODE) REFERENCES discl_comment_type (COMMENT_TYPE_CODE)
);

DROP TABLE IF EXISTS COI_TRAVELER;
CREATE TABLE COI_TRAVELER (
  TRAVELER_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (TRAVELER_TYPE_CODE)
);

DROP TABLE IF EXISTS COI_TRAVEL_STATUS;
CREATE TABLE COI_TRAVEL_STATUS (
  TRAVEL_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (TRAVEL_STATUS_CODE)
);

DROP TABLE IF EXISTS COI_TRAVEL_DISCLOSURE;
CREATE TABLE COI_TRAVEL_DISCLOSURE (
  TRAVEL_DISCLOSURE_ID int NOT NULL AUTO_INCREMENT,
  TRAVEL_NUMBER int DEFAULT NULL,
  VERSION_NUMBER int DEFAULT NULL,
  VERSION_STATUS varchar(45) DEFAULT NULL,
  PERSON_ENTITY_ID int DEFAULT NULL,
  ENTITY_ID int DEFAULT NULL,
  ENTITY_NUMBER int DEFAULT NULL,
  PERSON_ID varchar(45) DEFAULT NULL,
  TRAVEL_STATUS_CODE varchar(3) DEFAULT NULL,
  IS_SPONSORED_TRAVEL varchar(1) DEFAULT NULL,
  TRAVEL_TITLE varchar(200) DEFAULT NULL,
  PURPOSE_OF_THE_TRIP varchar(500) DEFAULT NULL,
  TRAVEL_AMOUNT decimal(12,2) DEFAULT NULL,
  TRAVEL_START_DATE date DEFAULT NULL,
  NO_OF_DAYS int DEFAULT NULL,
  DESTINATION_CITY varchar(90) DEFAULT NULL,
  DESTINATION_COUNTRY varchar(45) DEFAULT NULL,
  RELATIONSHIP_TO_YOUR_RESEARCH varchar(500) DEFAULT NULL,
  ACKNOWLEDGE_BY varchar(60) DEFAULT NULL,
  ACKNOWLEDGE_AT timestamp NULL DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  CREATE_USER varchar(60) DEFAULT NULL,
  CREATE_TIMESTAMP datetime DEFAULT NULL,
  TRAVEL_END_DATE date DEFAULT NULL,
  STATE varchar(60) DEFAULT NULL,
  IS_INTERNATIONAL_TRAVEL varchar(1) DEFAULT NULL,
  SUBMISSION_DATE date DEFAULT NULL,
  DESCRIPTION varchar(2000) DEFAULT NULL,
  HOME_UNIT varchar(2000) DEFAULT NULL,
  REVIEW_STATUS_CODE varchar(3) DEFAULT NULL,
  EXPIRATION_DATE date DEFAULT NULL,
  TRAVEL_DISCLOSURE_STATUS_CODE varchar(3) DEFAULT NULL,
  DISPOSITION_STATUS_CODE varchar(2000) DEFAULT NULL,
  TRAVELER_TYPE_CODE varchar(45) DEFAULT NULL,
  ADMIN_GROUP_ID int DEFAULT NULL,
  ADMIN_PERSON_ID varchar(45) DEFAULT NULL,
  CERTIFIED_BY varchar(45) DEFAULT NULL,
  CERTIFIED_AT datetime DEFAULT NULL,
  DOCUMENT_STATUS_CODE varchar(3) DEFAULT NULL,
  RISK_CATEGORY_CODE varchar(3) DEFAULT NULL,
  PRIMARY KEY (TRAVEL_DISCLOSURE_ID),
  KEY COI_TRAVEL_DISCLOSURE_FK1_idx (PERSON_ENTITY_ID),
  KEY COI_TRAVEL_DISCLOSURE_FK2_idx (ENTITY_ID),
  KEY COI_TRAVEL_DISCLOSURE_FK3_idx (PERSON_ID),
  KEY COI_TRAVEL_DISCLOSURE_FK4_idx (TRAVEL_STATUS_CODE),
  KEY COI_TRAVEL_DISCLOSURE_FK5_idx (RISK_CATEGORY_CODE),
  KEY COI_TRAVEL_DISCLOSURE_FK6_idx (TRAVEL_DISCLOSURE_STATUS_CODE),
  CONSTRAINT COI_TRAVEL_DISCLOSURE_FK1 FOREIGN KEY (PERSON_ENTITY_ID) REFERENCES person_entity (PERSON_ENTITY_ID),
  CONSTRAINT COI_TRAVEL_DISCLOSURE_FK2 FOREIGN KEY (ENTITY_ID) REFERENCES entity (ENTITY_ID),
  CONSTRAINT COI_TRAVEL_DISCLOSURE_FK3 FOREIGN KEY (PERSON_ID) REFERENCES person (PERSON_ID),
  CONSTRAINT COI_TRAVEL_DISCLOSURE_FK4 FOREIGN KEY (TRAVEL_STATUS_CODE) REFERENCES coi_travel_status (TRAVEL_STATUS_CODE),
  CONSTRAINT COI_TRAVEL_DISCLOSURE_FK5 FOREIGN KEY (RISK_CATEGORY_CODE) REFERENCES coi_risk_category (RISK_CATEGORY_CODE),
  CONSTRAINT COI_TRAVEL_DISCLOSURE_FK6 FOREIGN KEY (TRAVEL_DISCLOSURE_STATUS_CODE) REFERENCES coi_travel_disclosure_status (TRAVEL_DISCLOSURE_STATUS_CODE)
);

DROP TABLE IF EXISTS COI_TRAVEL_DISCLOSURE_TRAVELER;
CREATE TABLE COI_TRAVEL_DISCLOSURE_TRAVELER (
  TRAVEL_TRAVELER_ID int NOT NULL AUTO_INCREMENT,
  TRAVEL_DISCLOSURE_ID int DEFAULT NULL,
  TRAVELER_TYPE_CODE varchar(3) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (TRAVEL_TRAVELER_ID),
  KEY COI_TRAVEL_DISCLOSURE_TRAVELER_FK1_idx (TRAVEL_DISCLOSURE_ID),
  KEY COI_TRAVEL_DISCLOSURE_TRAVELER_FK2_idx (TRAVELER_TYPE_CODE),
  CONSTRAINT COI_TRAVEL_DISCLOSURE_TRAVELER_FK1 FOREIGN KEY (TRAVEL_DISCLOSURE_ID) REFERENCES coi_travel_disclosure (TRAVEL_DISCLOSURE_ID),
  CONSTRAINT COI_TRAVEL_DISCLOSURE_TRAVELER_FK2 FOREIGN KEY (TRAVELER_TYPE_CODE) REFERENCES coi_traveler_type (TRAVELER_TYPE_CODE)
);

DROP TABLE IF EXISTS DISCL_ATTACHMENT;
CREATE TABLE DISCL_ATTACHMENT (
  ATTACHMENT_ID int NOT NULL AUTO_INCREMENT,
  COMMENT_ID int DEFAULT NULL,
  COMPONENT_TYPE_CODE varchar(1) DEFAULT NULL,
  COMPONENT_REFERENCE_ID int DEFAULT NULL,
  COMPONENT_REFERENCE_NUMBER varchar(45) DEFAULT NULL,
  ATTACHMENT_NUMBER int DEFAULT NULL,
  VERSION_NUMBER int DEFAULT NULL,
  VERSION_STATUS varchar(45) DEFAULT NULL,
  ATTA_TYPE_CODE varchar(1) DEFAULT NULL,
  ATTA_STATUS_CODE varchar(1) DEFAULT NULL,
  DOCUMENT_OWNER_PERSON_ID varchar(45) DEFAULT NULL,
  FILE_NAME varchar(45) DEFAULT NULL,
  MIME_TYPE varchar(255) DEFAULT NULL,
  DESCRIPTION varchar(500) DEFAULT NULL,
  FILE_DATA_ID int DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ATTACHMENT_ID),
  KEY DISCL_ATTACHMENT_FK1_idx (COMMENT_ID),
  KEY DISCL_ATTACHMENT_FK2_idx (COMPONENT_TYPE_CODE),
  KEY DISCL_ATTACHMENT_FK3_idx (ATTA_TYPE_CODE),
  KEY DISCL_ATTACHMENT_FK4_idx (ATTA_STATUS_CODE),
  CONSTRAINT DISCL_ATTACHMENT_FK1 FOREIGN KEY (COMMENT_ID) REFERENCES discl_comment (COMMENT_ID),
  CONSTRAINT DISCL_ATTACHMENT_FK2 FOREIGN KEY (COMPONENT_TYPE_CODE) REFERENCES discl_component_type (COMPONENT_TYPE_CODE),
  CONSTRAINT DISCL_ATTACHMENT_FK3 FOREIGN KEY (ATTA_TYPE_CODE) REFERENCES discl_atta_type (ATTA_TYPE_CODE),
  CONSTRAINT DISCL_ATTACHMENT_FK4 FOREIGN KEY (ATTA_STATUS_CODE) REFERENCES discl_atta_status (ATTA_STATUS_CODE)
);

DROP TABLE IF EXISTS COI_TRAVEL_DISCLOSURE_STATUS;
CREATE TABLE COI_TRAVEL_DISCLOSURE_STATUS (
  TRAVEL_DISCLOSURE_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(50) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (TRAVEL_DISCLOSURE_STATUS_CODE)
);

DROP TABLE IF EXISTS COI_TRAVEL_REVIEW_STATUS;
CREATE TABLE COI_TRAVEL_REVIEW_STATUS (
  REVIEW_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL
);

DROP TABLE IF EXISTS COI_TRAVEL_DOCUMENT_STATUS;
CREATE TABLE COI_TRAVEL_DOCUMENT_STATUS (
  DOCUMENT_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL
);

DROP TABLE IF EXISTS COI_CONFLICT_HISTORY;
CREATE TABLE COI_CONFLICT_HISTORY (
  COI_CONFLICT_HISTORY_ID int NOT NULL AUTO_INCREMENT,
  DISCLOSURE_DETAILS_ID int NOT NULL,
  DISCLOSURE_ID int NOT NULL,
  COMMENT varchar(4000) DEFAULT NULL,
  CONFLICT_STATUS_CODE varchar(3) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (COI_CONFLICT_HISTORY_ID)
);

DROP TABLE IF EXISTS ATTACHMENT_NUMBER_COUNTER;
CREATE TABLE ATTACHMENT_NUMBER_COUNTER (
  counter_name varchar(255) NOT NULL,
  counter_value int DEFAULT NULL,
  PRIMARY KEY (counter_name)
);

DROP TABLE IF EXISTS COI_REVIEWER_STATUS_TYPE;
CREATE TABLE COI_REVIEWER_STATUS_TYPE (
  REVIEW_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (REVIEW_STATUS_CODE)
);

DROP TABLE IF EXISTS COI_REVIEW_LOCATION_TYPE;
CREATE TABLE COI_REVIEW_LOCATION_TYPE (
  LOCATION_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (LOCATION_TYPE_CODE)
);

DROP TABLE IF EXISTS COI_QUEST_ANSWER;
CREATE TABLE COI_QUEST_ANSWER (
  QUESTIONNAIRE_ANSWER_ID int NOT NULL AUTO_INCREMENT,
  QUESTIONNAIRE_ANS_HEADER_ID int DEFAULT NULL,
  QUESTION_ID int DEFAULT NULL,
  OPTION_NUMBER int DEFAULT NULL,
  ANSWER_NUMBER int DEFAULT NULL,
  ANSWER varchar(4000) DEFAULT NULL,
  ANSWER_LOOKUP_CODE varchar(100) DEFAULT NULL,
  EXPLANATION varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (QUESTIONNAIRE_ANSWER_ID),
  KEY COI_QUEST_ANSWER_FK1 (QUESTIONNAIRE_ANS_HEADER_ID),
  KEY COI_QUEST_ANSWER_FK2 (QUESTION_ID),
  CONSTRAINT COI_QUEST_ANSWER_FK1 FOREIGN KEY (QUESTIONNAIRE_ANS_HEADER_ID) REFERENCES quest_answer_header (QUESTIONNAIRE_ANS_HEADER_ID),
  CONSTRAINT COI_QUEST_ANSWER_FK2 FOREIGN KEY (QUESTION_ID) REFERENCES quest_question (QUESTION_ID)
);

DROP TABLE IF EXISTS COI_QUEST_ANSWER_ATTACHMENT;
CREATE TABLE COI_QUEST_ANSWER_ATTACHMENT (
  QUESTIONNAIRE_ANSWER_ATT_ID int NOT NULL AUTO_INCREMENT,
  QUESTIONNAIRE_ANSWER_ID int DEFAULT NULL,
  ATTACHMENT longblob,
  FILE_NAME varchar(300) DEFAULT NULL,
  CONTENT_TYPE varchar(100) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (QUESTIONNAIRE_ANSWER_ATT_ID),
  KEY COI_QUEST_ANSWER_ATTACHMENT_FK1 (QUESTIONNAIRE_ANSWER_ID),
  CONSTRAINT COI_QUEST_ANSWER_ATTACHMENT_FK1 FOREIGN KEY (QUESTIONNAIRE_ANSWER_ID) REFERENCES coi_quest_answer (QUESTIONNAIRE_ANSWER_ID)
);

DROP TABLE IF EXISTS COI_QUEST_TABLE_ANSWER;
CREATE TABLE COI_QUEST_TABLE_ANSWER (
  QUEST_TABLE_ANSWER_ID int NOT NULL AUTO_INCREMENT,
  QUESTIONNAIRE_ANS_HEADER_ID int DEFAULT NULL,
  QUESTION_ID int DEFAULT NULL,
  ORDER_NUMBER int DEFAULT NULL,
  COLUMN_1 varchar(250) DEFAULT NULL,
  COLUMN_2 varchar(250) DEFAULT NULL,
  COLUMN_3 varchar(250) DEFAULT NULL,
  COLUMN_4 varchar(250) DEFAULT NULL,
  COLUMN_5 varchar(250) DEFAULT NULL,
  COLUMN_6 varchar(250) DEFAULT NULL,
  COLUMN_7 varchar(250) DEFAULT NULL,
  COLUMN_8 varchar(250) DEFAULT NULL,
  COLUMN_9 varchar(250) DEFAULT NULL,
  COLUMN_10 varchar(250) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (QUEST_TABLE_ANSWER_ID),
  KEY COI_QUESTIONNAIRE_ANS_HEADER_ID_FK1 (QUESTIONNAIRE_ANS_HEADER_ID),
  CONSTRAINT COI_QUESTIONNAIRE_ANS_HEADER_ID_FK1 FOREIGN KEY (QUESTIONNAIRE_ANS_HEADER_ID) REFERENCES quest_answer_header (QUESTIONNAIRE_ANS_HEADER_ID)
);

DROP TABLE IF EXISTS DISCLOSURE_ACTION_TYPE;
CREATE TABLE DISCLOSURE_ACTION_TYPE (
  ACTION_TYPE_CODE varchar(3) NOT NULL,
  MESSAGE varchar(200) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_TYPE_CODE)
);

DROP TABLE IF EXISTS ENTITY_ACTION_TYPE;
CREATE TABLE ENTITY_ACTION_TYPE (
  ACTION_TYPE_CODE varchar(3) NOT NULL,
  MESSAGE varchar(200) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_TYPE_CODE)
);

DROP TABLE IF EXISTS DISCLOSURE_ACTION_LOG;
CREATE TABLE DISCLOSURE_ACTION_LOG (
  ACTION_LOG_ID int NOT NULL AUTO_INCREMENT,
  DISCLOSURE_ID int DEFAULT NULL,
  DISCLOSURE_NUMBER int DEFAULT NULL,
  ACTION_TYPE_CODE varchar(3) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  COMMENT varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_LOG_ID),
  KEY DISCLOSURE_ACTION_LOG_FK1 (ACTION_TYPE_CODE),
  KEY DISCLOSURE_ACTION_LOG_FK2 (DISCLOSURE_ID),
  CONSTRAINT DISCLOSURE_ACTION_LOG_FK1 FOREIGN KEY (ACTION_TYPE_CODE) REFERENCES disclosure_action_type (ACTION_TYPE_CODE),
  CONSTRAINT DISCLOSURE_ACTION_LOG_FK2 FOREIGN KEY (DISCLOSURE_ID) REFERENCES coi_disclosure (DISCLOSURE_ID)
);

DROP TABLE IF EXISTS ENTITY_ACTION_LOG;
CREATE TABLE ENTITY_ACTION_LOG (
  ACTION_LOG_ID int NOT NULL AUTO_INCREMENT,
  ENTITY_ID int DEFAULT NULL,
  ENTITY_NUMBER int DEFAULT NULL,
  ACTION_TYPE_CODE varchar(3) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  COMMENT varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_LOG_ID),
  KEY ENTITY_ACTION_LOG_FK1 (ACTION_TYPE_CODE),
  KEY ENTITY_ACTION_LOG_FK2 (ENTITY_ID),
  CONSTRAINT ENTITY_ACTION_LOG_FK1 FOREIGN KEY (ACTION_TYPE_CODE) REFERENCES entity_action_type (ACTION_TYPE_CODE),
  CONSTRAINT ENTITY_ACTION_LOG_FK2 FOREIGN KEY (ENTITY_ID) REFERENCES entity (ENTITY_ID)
);

DROP TABLE IF EXISTS TRAVEL_DISCLOSURE_ACTION_LOG;
CREATE TABLE TRAVEL_DISCLOSURE_ACTION_LOG (
  ACTION_LOG_ID int NOT NULL AUTO_INCREMENT,
  TRAVEL_DISCLOSURE_ID int DEFAULT NULL,
  TRAVEL_NUMBER int DEFAULT NULL,
  ACTION_TYPE_CODE varchar(3) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  COMMENT varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_LOG_ID),
  KEY TRAVEL_DISCLOSURE_ACTION_LOG_FK1 (ACTION_TYPE_CODE),
  KEY TRAVEL_DISCLOSURE_ACTION_LOG_FK2 (TRAVEL_DISCLOSURE_ID),
  CONSTRAINT TRAVEL_DISCLOSURE_ACTION_LOG_FK1 FOREIGN KEY (ACTION_TYPE_CODE) REFERENCES disclosure_action_type (ACTION_TYPE_CODE),
  CONSTRAINT TRAVEL_DISCLOSURE_ACTION_LOG_FK2 FOREIGN KEY (TRAVEL_DISCLOSURE_ID) REFERENCES coi_travel_disclosure (TRAVEL_DISCLOSURE_ID)
);

DROP TABLE IF EXISTS COI_TRAVEL_CONFLICT_HISTORY;
CREATE TABLE COI_TRAVEL_CONFLICT_HISTORY (
  COI_TRAVEL_CONFLICT_HISTORY_ID int NOT NULL AUTO_INCREMENT,
  TRAVEL_DISCLOSURE_ID int NOT NULL,
  COMMENT varchar(4000) DEFAULT NULL,
  CONFLICT_STATUS_CODE varchar(3) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (COI_TRAVEL_CONFLICT_HISTORY_ID),
  KEY COI_TRAVEL_CONFLICT_HISTORY_FK1_idx (CONFLICT_STATUS_CODE)
);

DROP TABLE IF EXISTS OPA_DISPOSITION_STATUS_TYPE;
CREATE TABLE OPA_DISPOSITION_STATUS_TYPE (
  DISPOSITION_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (DISPOSITION_STATUS_CODE)
);

DROP TABLE IF EXISTS OPA_ACTION_LOG_TYPE;
CREATE TABLE OPA_ACTION_LOG_TYPE (
  ACTION_TYPE_CODE varchar(3) NOT NULL,
  MESSAGE varchar(200) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_TYPE_CODE)
);

DROP TABLE IF EXISTS OPA_ACTION_LOG;
CREATE TABLE OPA_ACTION_LOG (
  ACTION_LOG_ID int NOT NULL AUTO_INCREMENT,
  OPA_DISCLOSURE_ID int DEFAULT NULL,
  OPA_DISCLOSURE_NUMBER varchar(20) DEFAULT NULL,
  ACTION_TYPE_CODE varchar(3) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  COMMENT varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_LOG_ID),
  KEY OPA_ACTION_LOG_FK2 (ACTION_TYPE_CODE),
  KEY OPA_ACTION_LOG_FK1 (OPA_DISCLOSURE_ID),
  CONSTRAINT OPA_ACTION_LOG_FK1 FOREIGN KEY (OPA_DISCLOSURE_ID) REFERENCES opa_disclosure (OPA_DISCLOSURE_ID),
  CONSTRAINT OPA_ACTION_LOG_FK2 FOREIGN KEY (ACTION_TYPE_CODE) REFERENCES opa_action_log_type (ACTION_TYPE_CODE)
);

DROP TABLE IF EXISTS PERSON_ENTITY_ACTION_TYPE;
CREATE TABLE PERSON_ENTITY_ACTION_TYPE (
  ACTION_TYPE_CODE varchar(3) NOT NULL,
  MESSAGE varchar(200) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_TYPE_CODE)
);

DROP TABLE IF EXISTS PERSON_ENTITY_ACTION_LOG;
CREATE TABLE PERSON_ENTITY_ACTION_LOG (
  ACTION_LOG_ID int NOT NULL AUTO_INCREMENT,
  PERSON_ENTITY_ID int DEFAULT NULL,
  PERSON_ENTITY_NUMBER int DEFAULT NULL,
  ACTION_TYPE_CODE varchar(3) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  COMMENT varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (ACTION_LOG_ID),
  KEY PERSON_ENTITY_AL_FK1 (ACTION_TYPE_CODE),
  KEY PERSON_ENTITY_AL_FK2 (PERSON_ENTITY_ID),
  CONSTRAINT PERSON_ENTITY_AL_FK1 FOREIGN KEY (ACTION_TYPE_CODE) REFERENCES person_entity_action_type (ACTION_TYPE_CODE),
  CONSTRAINT PERSON_ENTITY_AL_FK2 FOREIGN KEY (PERSON_ENTITY_ID) REFERENCES person_entity (PERSON_ENTITY_ID)
);

DROP TABLE IF EXISTS OPA_PERSON;
CREATE TABLE OPA_PERSON (
  PERSON_ID varchar(40) NOT NULL,
  PERSON_NAME varchar(90) DEFAULT NULL,
  FORM_OF_ADDRESS_SHORT varchar(40) DEFAULT NULL,
  FIRST_NAME varchar(30) DEFAULT NULL,
  MIDDLE_NAME varchar(30) DEFAULT NULL,
  LAST_NAME varchar(30) DEFAULT NULL,
  KRB_NAME_UPPERCASE varchar(60) DEFAULT NULL,
  EMAIL_ADDRESS varchar(60) DEFAULT NULL,
  JOB_ID varchar(20) DEFAULT NULL,
  JOB_TITLE varchar(50) DEFAULT NULL,
  ADMIN_EMPLOYEE_TYPE varchar(40) DEFAULT NULL,
  HR_DEPARTMENT_CODE_OLD varchar(10) DEFAULT NULL,
  HR_DEPARTMENT_NAME varchar(50) DEFAULT NULL,
  ADMIN_ORG_UNIT_ID varchar(10) DEFAULT NULL,
  ADMIN_ORG_UNIT_TITLE varchar(50) DEFAULT NULL,
  ADMIN_POSITION_TITLE varchar(50) DEFAULT NULL,
  PAYROLL_RANK varchar(40) DEFAULT NULL,
  IS_FACULTY varchar(1) DEFAULT NULL,
  EMPLOYMENT_PERCENT decimal(5,2) DEFAULT NULL,
  IS_CONSULT_PRIV varchar(1) DEFAULT NULL,
  IS_PAID_APPT varchar(1) DEFAULT NULL,
  IS_SUMMER_SESSION_APPT varchar(1) DEFAULT NULL,
  SUMMER_SESSION_MONTHS int DEFAULT NULL,
  IS_SABBATICAL varchar(1) DEFAULT NULL,
  SABBATICAL_BEGIN_DATE date DEFAULT NULL,
  SABBATICAL_END_DATE date DEFAULT NULL,
  WAREHOUSE_LOAD_DATE date DEFAULT NULL,
  PRIMARY KEY (PERSON_ID)
);

DROP TABLE IF EXISTS OPA_CYCLES;
CREATE TABLE OPA_CYCLES (
  OPA_CYCLE_NUMBER int NOT NULL AUTO_INCREMENT,
  PERIOD_START_DATE date NOT NULL,
  PERIOD_END_DATE date NOT NULL,
  OPA_CYCLE_STATUS varchar(1) NOT NULL,
  OPEN_DATE date DEFAULT NULL,
  CLOSE_DATE date DEFAULT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATE_USER varchar(60) NOT NULL,
  PRIMARY KEY (OPA_CYCLE_NUMBER)
);

DROP TABLE IF EXISTS OPA_DISCLOSURE;
CREATE TABLE OPA_DISCLOSURE (
  OPA_DISCLOSURE_ID int NOT NULL AUTO_INCREMENT,
  OPA_DISCLOSURE_NUMBER varchar(20) DEFAULT NULL,
  OPA_CYCLE_NUMBER int NOT NULL,
  PERSON_ID varchar(40) NOT NULL,
  PERSON_NAME varchar(90) NOT NULL,
  HOME_UNIT varchar(8) NOT NULL,
  STATUS_CODE varchar(1) DEFAULT NULL,
  IS_FACULTY varchar(1) NOT NULL,
  IS_FALL_SABATICAL varchar(1) DEFAULT NULL,
  IS_SPRING_SABATICAL varchar(1) DEFAULT NULL,
  RECEIVED_SUMMER_COMP varchar(1) DEFAULT NULL,
  SUMMER_COMP_MONTHS decimal(5,2) DEFAULT NULL,
  IS_FULL_TIME varchar(1) DEFAULT NULL,
  IS_PART_TIME varchar(1) DEFAULT NULL,
  APPOINTMENT_PERCENT decimal(5,2) DEFAULT NULL,
  IS_COMPENSATED varchar(1) DEFAULT NULL,
  HAS_POTENTIAL_CONFLICT varchar(1) DEFAULT NULL,
  CONFLICT_DESCRIPTION varchar(4000) DEFAULT NULL,
  CREATE_TIMESTAMP datetime NOT NULL,
  CREATE_USER varchar(60) NOT NULL,
  SUBMISSION_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATE_USER varchar(60) NOT NULL,
  REVIEW_STATUS_CODE varchar(3) DEFAULT NULL,
  DISPOSITION_STATUS_CODE varchar(3) DEFAULT NULL,
  ADMIN_PERSON_ID varchar(45) DEFAULT NULL,
  ADMIN_GROUP_ID int DEFAULT NULL,
  CERTIFICATION_TEXT varchar(1000) DEFAULT NULL,
  CERTIFIED_BY varchar(60) DEFAULT NULL,
  PRIMARY KEY (OPA_DISCLOSURE_ID),
  KEY OPA_DISCLOSURE_FK1_idx (OPA_CYCLE_NUMBER),
  KEY OPA_DISCLOSURE_FK2_idx (REVIEW_STATUS_CODE),
  KEY OPA_DISCLOSURE_FK3_idx (DISPOSITION_STATUS_CODE),
  KEY OPA_DISCLOSURE_FK4_idx (PERSON_ID),
  CONSTRAINT OPA_DISCLOSURE_FK1 FOREIGN KEY (OPA_CYCLE_NUMBER) REFERENCES opa_cycles (OPA_CYCLE_NUMBER),
  CONSTRAINT OPA_DISCLOSURE_FK2 FOREIGN KEY (REVIEW_STATUS_CODE) REFERENCES opa_review_status_type (REVIEW_STATUS_CODE),
  CONSTRAINT OPA_DISCLOSURE_FK3 FOREIGN KEY (DISPOSITION_STATUS_CODE) REFERENCES opa_disposition_status_type (DISPOSITION_STATUS_CODE),
  CONSTRAINT OPA_DISCLOSURE_FK4 FOREIGN KEY (PERSON_ID) REFERENCES opa_person (PERSON_ID)
);

DROP TABLE IF EXISTS OPA_DISCLOSURE_NUMBER_COUNTER;
CREATE TABLE OPA_DISCLOSURE_NUMBER_COUNTER (
  counter_name varchar(255) NOT NULL,
  counter_value int DEFAULT NULL,
  PRIMARY KEY (counter_name)
);

DROP TABLE IF EXISTS OPA_STATUS_TYPE;
CREATE TABLE OPA_STATUS_TYPE (
  STATUS_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (STATUS_TYPE_CODE)
);

DROP TABLE IF EXISTS OPA_REVIEW_STATUS_TYPE;
CREATE TABLE OPA_REVIEW_STATUS_TYPE (
  REVIEW_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (REVIEW_STATUS_CODE)
);

DROP TABLE IF EXISTS OPA_REVIEW_LOCATION_TYPE;
CREATE TABLE OPA_REVIEW_LOCATION_TYPE (
  LOCATION_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (LOCATION_TYPE_CODE)
);

DROP TABLE IF EXISTS OPA_REVIEW;
CREATE TABLE OPA_REVIEW (
  OPA_REVIEW_ID int NOT NULL AUTO_INCREMENT,
  ASSIGNEE_PERSON_ID varchar(40) DEFAULT NULL,
  OPA_DISCLOSURE_ID int DEFAULT NULL,
  ADMIN_GROUP_ID int DEFAULT NULL,
  REVIEW_STATUS_TYPE_CODE varchar(3) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  CREATE_TIMESTAMP datetime DEFAULT NULL,
  CREATE_USER varchar(60) DEFAULT NULL,
  DESCRIPTION varchar(2000) DEFAULT NULL,
  LOCATION_TYPE_CODE varchar(3) DEFAULT NULL,
  START_DATE date DEFAULT NULL,
  END_DATE date DEFAULT NULL,
  PRIMARY KEY (OPA_REVIEW_ID),
  KEY OPA_REVIEW_FK5 (ASSIGNEE_PERSON_ID),
  KEY OPA_REVIEW_FK1 (OPA_DISCLOSURE_ID),
  KEY OPA_REVIEW_FK2 (ADMIN_GROUP_ID),
  KEY OPA_REVIEW_FK3_idx (REVIEW_STATUS_TYPE_CODE),
  KEY OPA_REVIEW_FK4_idx (LOCATION_TYPE_CODE),
  CONSTRAINT OPA_REVIEW_FK1 FOREIGN KEY (OPA_DISCLOSURE_ID) REFERENCES opa_disclosure (OPA_DISCLOSURE_ID),
  CONSTRAINT OPA_REVIEW_FK2 FOREIGN KEY (ADMIN_GROUP_ID) REFERENCES admin_group (ADMIN_GROUP_ID),
  CONSTRAINT OPA_REVIEW_FK3 FOREIGN KEY (REVIEW_STATUS_TYPE_CODE) REFERENCES opa_review_reviewer_status_type (REVIEW_STATUS_CODE),
  CONSTRAINT OPA_REVIEW_FK4 FOREIGN KEY (LOCATION_TYPE_CODE) REFERENCES opa_review_location_type (LOCATION_TYPE_CODE),
  CONSTRAINT OPA_REVIEW_FK5 FOREIGN KEY (ASSIGNEE_PERSON_ID) REFERENCES person (PERSON_ID)
);

DROP TABLE IF EXISTS NOTES;
CREATE TABLE NOTES (
  NOTE_ID int NOT NULL AUTO_INCREMENT,
  PERSON_ID varchar(45) DEFAULT NULL,
  CONTENT text,
  UPDATE_USER varchar(50) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  PRIMARY KEY (NOTE_ID)
);

DROP TABLE IF EXISTS ATTACHMENTS;
CREATE TABLE ATTACHMENTS (
  ATTACHMENT_ID int NOT NULL AUTO_INCREMENT,
  PERSON_ID varchar(45) DEFAULT NULL,
  DESCRIPTION varchar(2000) DEFAULT NULL,
  ATTA_TYPE_CODE varchar(3) DEFAULT NULL,
  FILE_NAME varchar(100) DEFAULT NULL,
  MIME_TYPE varchar(255) DEFAULT NULL,
  FILE_DATA_ID varchar(100) DEFAULT NULL,
  CREATE_USER varchar(50) DEFAULT NULL,
  CREATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(50) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  PRIMARY KEY (ATTACHMENT_ID)
);

DROP TABLE IF EXISTS OPA_FORM_BUILDER_DETAILS;
CREATE TABLE OPA_FORM_BUILDER_DETAILS (
  OPA_FORM_BUILDER_DETAILS_ID int NOT NULL AUTO_INCREMENT,
  OPA_DISCLOSURE_ID int NOT NULL,
  OPA_DISCLOSURE_NUMBER varchar(20) NOT NULL,
  PERSON_ID varchar(40) NOT NULL,
  FORM_BUILDER_ID int NOT NULL,
  IS_PRIMARY_FORM varchar(1) NOT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATE_USER varchar(90) NOT NULL,
  PRIMARY KEY (OPA_FORM_BUILDER_DETAILS_ID)
);

DROP TABLE IF EXISTS OPA_REVIEW_REVIEWER_STATUS_TYPE;
CREATE TABLE OPA_REVIEW_REVIEWER_STATUS_TYPE (
  REVIEW_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (REVIEW_STATUS_CODE)
);

DROP TABLE IF EXISTS OPA_REVIEW_STATUS_TYPE;
CREATE TABLE OPA_REVIEW_STATUS_TYPE (
  REVIEW_STATUS_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  SORT_ORDER int DEFAULT NULL,
  PRIMARY KEY (REVIEW_STATUS_CODE)
);

DROP TABLE IF EXISTS OPA_INSTITUTE_RESOURCE_USE;
CREATE TABLE OPA_INSTITUTE_RESOURCE_USE (
  OPA_INST_RES_ID int NOT NULL AUTO_INCREMENT,
  OPA_DISCLOSURE_ID int DEFAULT NULL,
  OPA_DISCL_PERSON_ENTITY_ID int DEFAULT NULL,
  DESCRIPTION varchar(4000) DEFAULT NULL,
  DESCRIPTION_1 varchar(4000) DEFAULT NULL,
  DESCRIPTION_2 varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (OPA_INST_RES_ID)
);

DROP TABLE IF EXISTS COI_REVIEW_COMMENT_TAGS;
CREATE TABLE COI_REVIEW_COMMENT_TAGS (
  COI_REVIEW_COMMENT_TAGS_ID int NOT NULL AUTO_INCREMENT,
  COI_REVIEW_COMMENT_ID int DEFAULT NULL,
  TAG_REF varchar(20) DEFAULT NULL,
  TAGGED_PERSON_ID varchar(40) DEFAULT NULL,
  TAGGED_GROUP_ID int DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  COI_REVIEW_ID int DEFAULT NULL,
  PRIMARY KEY (COI_REVIEW_COMMENT_TAGS_ID),
  KEY COI_REVIEW_CMT_TAGS_FK2_idx (COI_REVIEW_COMMENT_ID),
  KEY COI_REVIEW_CMT_TAGS_FK1 (COI_REVIEW_ID),
  CONSTRAINT COI_REVIEW_CMT_TAGS_FK1 FOREIGN KEY (COI_REVIEW_ID) REFERENCES coi_review (COI_REVIEW_ID),
  CONSTRAINT COI_REVIEW_CMT_TAGS_FK2 FOREIGN KEY (COI_REVIEW_COMMENT_ID) REFERENCES discl_comment (COMMENT_ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS COI_REVIEW;
CREATE TABLE COI_REVIEW (
  COI_REVIEW_ID int NOT NULL AUTO_INCREMENT,
  ASSIGNEE_PERSON_ID varchar(40) DEFAULT NULL,
  DISCLOSURE_ID int DEFAULT NULL,
  ADMIN_GROUP_ID int DEFAULT NULL,
  REVIEW_STATUS_TYPE_CODE varchar(3) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  CREATE_TIMESTAMP datetime DEFAULT NULL,
  CREATE_USER varchar(60) DEFAULT NULL,
  DESCRIPTION varchar(2000) DEFAULT NULL,
  LOCATION_TYPE_CODE varchar(3) DEFAULT NULL,
  START_DATE date DEFAULT NULL,
  END_DATE date DEFAULT NULL,
  PRIMARY KEY (COI_REVIEW_ID),
  KEY COI_REVIEW_FK1 (ASSIGNEE_PERSON_ID),
  KEY COI_REVIEW_FK2 (DISCLOSURE_ID),
  KEY COI_REVIEW_FK3 (ADMIN_GROUP_ID),
  KEY COI_REVIEW_FK4_idx (REVIEW_STATUS_TYPE_CODE),
  KEY COI_REVIEW_FK5_idx (LOCATION_TYPE_CODE),
  CONSTRAINT COI_REVIEW_FK1 FOREIGN KEY (ASSIGNEE_PERSON_ID) REFERENCES person (PERSON_ID),
  CONSTRAINT COI_REVIEW_FK2 FOREIGN KEY (DISCLOSURE_ID) REFERENCES coi_disclosure (DISCLOSURE_ID),
  CONSTRAINT COI_REVIEW_FK3 FOREIGN KEY (ADMIN_GROUP_ID) REFERENCES admin_group (ADMIN_GROUP_ID),
  CONSTRAINT COI_REVIEW_FK4 FOREIGN KEY (REVIEW_STATUS_TYPE_CODE) REFERENCES coi_reviewer_status_type (REVIEW_STATUS_CODE),
  CONSTRAINT COI_REVIEW_FK5 FOREIGN KEY (LOCATION_TYPE_CODE) REFERENCES coi_review_location_type (LOCATION_TYPE_CODE)
);

DROP TABLE IF EXISTS OPA_DISCL_PERSON_ENTITY;
CREATE TABLE OPA_DISCL_PERSON_ENTITY (
  OPA_DISCL_PERSON_ENTITY_ID int NOT NULL AUTO_INCREMENT,
  OPA_DISCLOSURE_ID int NOT NULL,
  PERSON_ENTITY_ID int DEFAULT NULL,
  ENTITY_ID int DEFAULT NULL,
  ENTITY_NUMBER int DEFAULT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATE_USER varchar(60) NOT NULL,
  PERSON_ENTITY_NUMBER int DEFAULT NULL,
  PRIMARY KEY (OPA_DISCL_PERSON_ENTITY_ID),
  KEY OPA_DISCL_PERSON_ENTITY_FK1 (OPA_DISCLOSURE_ID),
  KEY OPA_DISCL_PERSON_ENTITY_FK2 (ENTITY_ID),
  KEY OPA_DISCL_PERSON_ENTITY_FK3 (PERSON_ENTITY_ID),
  CONSTRAINT OPA_DISCL_PERSON_ENTITY_FK1 FOREIGN KEY (OPA_DISCLOSURE_ID) REFERENCES opa_disclosure (OPA_DISCLOSURE_ID),
  CONSTRAINT OPA_DISCL_PERSON_ENTITY_FK2 FOREIGN KEY (ENTITY_ID) REFERENCES entity (ENTITY_ID),
  CONSTRAINT OPA_DISCL_PERSON_ENTITY_FK3 FOREIGN KEY (PERSON_ENTITY_ID) REFERENCES person_entity (PERSON_ENTITY_ID)
);

DROP TABLE IF EXISTS OPA_DISCL_ACTIVITIES;
CREATE TABLE OPA_DISCL_ACTIVITIES (
  OPA_DISCL_ACTIVITY_ID int NOT NULL AUTO_INCREMENT,
  OPA_DISCLOSURE_ID int NOT NULL,
  OPA_DISCL_PERSON_ENTITY_ID int DEFAULT NULL,
  IS_COMPENSATED varchar(1) NOT NULL,
  NUM_OF_DAYS_SUMMER decimal(5,2) DEFAULT NULL,
  NUM_OF_DAYS_ACADEMIC decimal(5,2) DEFAULT NULL,
  NUM_OF_DAYS_IN_YEAR decimal(5,2) DEFAULT NULL,
  NATURE_OF_WORK varchar(4000) DEFAULT NULL,
  DESCRIPTION_1 varchar(4000) DEFAULT NULL,
  DESCRIPTION_2 varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATE_USER varchar(60) NOT NULL,
  PRIMARY KEY (OPA_DISCL_ACTIVITY_ID),
  KEY OPA_DISCL_ACTIVITIES_FK1 (OPA_DISCLOSURE_ID),
  KEY OPA_DISCL_ACTIVITIES_FK2 (OPA_DISCL_PERSON_ENTITY_ID),
  CONSTRAINT OPA_DISCL_ACTIVITIES_FK1 FOREIGN KEY (OPA_DISCLOSURE_ID) REFERENCES opa_disclosure (OPA_DISCLOSURE_ID),
  CONSTRAINT OPA_DISCL_ACTIVITIES_FK2 FOREIGN KEY (OPA_DISCL_PERSON_ENTITY_ID) REFERENCES opa_discl_person_entity (OPA_DISCL_PERSON_ENTITY_ID)
);

DROP TABLE IF EXISTS OPA_OUTSIDE_FIN_INTERESTS;
CREATE TABLE OPA_OUTSIDE_FIN_INTERESTS (
  OPA_OUTSIDE_FIN_INTEREST_ID int NOT NULL AUTO_INCREMENT,
  OPA_DISCLOSURE_ID int NOT NULL,
  OPA_DISCL_PERSON_ENTITY_ID int DEFAULT NULL,
  PERSON_REL_WITH_ENTITY varchar(4000) DEFAULT NULL,
  ENTITY_REL_WITH_INSTITUTE varchar(4000) DEFAULT NULL,
  DESCRIPTION_1 varchar(4000) DEFAULT NULL,
  DESCRIPTION_2 varchar(4000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATE_USER varchar(60) NOT NULL,
  PRIMARY KEY (OPA_OUTSIDE_FIN_INTEREST_ID),
  KEY OPA_OUTSIDE_FIN_INTERESTS_FK1 (OPA_DISCLOSURE_ID),
  KEY OPA_OUTSIDE_FIN_INTERESTS_FK2 (OPA_DISCL_PERSON_ENTITY_ID),
  CONSTRAINT OPA_OUTSIDE_FIN_INTERESTS_FK1 FOREIGN KEY (OPA_DISCLOSURE_ID) REFERENCES opa_disclosure (OPA_DISCLOSURE_ID),
  CONSTRAINT OPA_OUTSIDE_FIN_INTERESTS_FK2 FOREIGN KEY (OPA_DISCL_PERSON_ENTITY_ID) REFERENCES opa_discl_person_entity (OPA_DISCL_PERSON_ENTITY_ID)
);

DROP TABLE IF EXISTS OPA_STUDENT_SUBORDINATE_INVOLVEMENT;
CREATE TABLE OPA_STUDENT_SUBORDINATE_INVOLVEMENT (
  OPA_STUD_SUB_INV_ID int NOT NULL AUTO_INCREMENT,
  OPA_DISCLOSURE_ID int DEFAULT NULL,
  OPA_PERSON_TYPE_CODE varchar(3) DEFAULT NULL,
  PERSON_ID varchar(40) DEFAULT NULL,
  NATURE_OF_WORK varchar(4000) DEFAULT NULL,
  DESCRIPTION_1 varchar(4000) DEFAULT NULL,
  DESCRIPTION_2 varchar(4000) DEFAULT NULL,
  OPA_DISCL_PERSON_ENTITY_ID int DEFAULT NULL,
  RELATIONSHIP varchar(4000) DEFAULT NULL,
  NUM_OF_DAYS decimal(5,2) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (OPA_STUD_SUB_INV_ID)
);


DROP TABLE IF EXISTS FORM_BUILDER_HEADER;
CREATE TABLE FORM_BUILDER_HEADER (
  FORM_BUILDER_ID int NOT NULL AUTO_INCREMENT,
  FORM_BUILDER_NUMBER varchar(20),
  VERSION_NUMBER int,
  VERSION_STATUS varchar(10),
  MODULE_CODE varchar(3),
  SUB_MODULE_CODE varchar(3),
  BUSINESS_RULE_ID int DEFAULT NULL,
  DESCRIPTION varchar(300),
  CREATE_TIMESTAMP datetime,
  CREATE_USER varchar(60),
  UPDATE_TIMESTAMP datetime,
  UPDATE_USER varchar(60),
  IS_ACTIVE varchar(1),
  TITLE varchar(300) DEFAULT NULL,
  PRIMARY KEY (FORM_BUILDER_ID)
);

DROP TABLE IF EXISTS FORM_BUILDER_PROG_ELEMENT;
CREATE TABLE FORM_BUILDER_PROG_ELEMENT (
  PROG_ELEMENT_ID int NOT NULL AUTO_INCREMENT,
  PROG_ELEMENT_NUMBER varchar(20) NOT NULL,
  VERSION_NUMBER int NOT NULL,
  VERSION_STATUS varchar(10) NOT NULL,
  PROG_ELEMENT_NAME varchar(100) NOT NULL,
  DESCRIPTION varchar(300) NOT NULL,
  IS_ACTIVE varchar(1) NOT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATE_USER varchar(60) NOT NULL,
  PRIMARY KEY (PROG_ELEMENT_ID)
);

DROP TABLE IF EXISTS FORM_BUILDER_SECTION;
CREATE TABLE FORM_BUILDER_SECTION (
  FORM_BUILDER_SECTION_ID int NOT NULL AUTO_INCREMENT,
  FORM_BUILDER_ID int,
  FORM_BUILDER_NUMBER varchar(20),
  SECTION_NAME varchar(200),
  SECTION_ORDER_NUMBER int,
  MODULE_CODE varchar(3),
  SUB_MODULE_CODE varchar(3),
  BUSINESS_RULE_ID int DEFAULT NULL,
  DESCRIPTION varchar(300),
  HELP_TEXT varchar(1000) DEFAULT NULL,
  HEADER_INSTRUCTION varchar(4000) DEFAULT NULL,
  FOOTER_INSTRUCTION varchar(4000) DEFAULT NULL,
  IS_ACTIVE varchar(1),
  UPDATE_TIMESTAMP datetime,
  UPDATE_USER varchar(60),
  PRIMARY KEY (FORM_BUILDER_SECTION_ID),
  KEY FORM_BUILDER_SECTION_FK1 (FORM_BUILDER_ID),
  CONSTRAINT FORM_BUILDER_SECTION_FK1 FOREIGN KEY (FORM_BUILDER_ID) REFERENCES form_builder_header (FORM_BUILDER_ID)
);

DROP TABLE IF EXISTS FORM_SECTION_COMPONENT_TYPE;
CREATE TABLE FORM_SECTION_COMPONENT_TYPE (
  COMPONENT_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) NOT NULL,
  IS_ACTIVE varchar(1) NOT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATE_USER varchar(60) NOT NULL,
  PRIMARY KEY (COMPONENT_TYPE_CODE)
);

DROP TABLE IF EXISTS FORM_BUILDER_SECTION_COMPONENT;
CREATE TABLE FORM_BUILDER_SECTION_COMPONENT (
  FORM_BUILDER_SECT_COMP_ID int NOT NULL AUTO_INCREMENT,
  FORM_BUILDER_SECTION_ID int,
  COMPONENT_TYPE_CODE varchar(3),
  COMPONENT_ORDER_NUMBER int,
  COMPONENT_DATA varchar(1000) DEFAULT NULL,
  COMPONENT_REF_ID varchar(10) DEFAULT NULL,
  DESCRIPTION varchar(300),
  HEADER_INSTRUCTION varchar(4000) DEFAULT NULL,
  FOOTER_INSTRUCTION varchar(4000) DEFAULT NULL,
  IS_ACTIVE varchar(1),
  UPDATE_TIMESTAMP datetime,
  UPDATE_USER varchar(60),
  PRIMARY KEY (FORM_BUILDER_SECT_COMP_ID),
  KEY FORM_BUILDER_SECT_COMP_FK1 (FORM_BUILDER_SECTION_ID),
  KEY FORM_BUILDER_SECT_COMP_FK2 (COMPONENT_TYPE_CODE),
  CONSTRAINT FORM_BUILDER_SECT_COMP_FK1 FOREIGN KEY (FORM_BUILDER_SECTION_ID) REFERENCES form_builder_section (FORM_BUILDER_SECTION_ID),
  CONSTRAINT FORM_BUILDER_SECT_COMP_FK2 FOREIGN KEY (COMPONENT_TYPE_CODE) REFERENCES form_section_component_type (COMPONENT_TYPE_CODE)
);

DROP TABLE IF EXISTS FORM_BUILDER_USAGE;
CREATE TABLE FORM_BUILDER_USAGE (
  FORM_USAGE_ID int NOT NULL AUTO_INCREMENT,
  FORM_BUILDER_ID int NOT NULL,
  FORM_BUILDER_NUMBER varchar(20) NOT NULL,
  FORM_ORDER_NUMBER int NOT NULL,
  MODULE_CODE varchar(3) NOT NULL,
  SUB_MODULE_CODE varchar(3) NOT NULL,
  BUSINESS_RULE_ID int DEFAULT NULL,
  DESCRIPTION varchar(300) NOT NULL,
  IS_ACTIVE varchar(1) NOT NULL,
  CREATE_TIMESTAMP datetime NOT NULL,
  CREATE_USER varchar(60) NOT NULL,
  UPDATE_TIMESTAMP datetime NOT NULL,
  UPDATE_USER varchar(60) NOT NULL,
  PRIMARY KEY (FORM_USAGE_ID),
  KEY FORM_BUILDER_USAGE_FK1 (FORM_BUILDER_ID),
  CONSTRAINT FORM_BUILDER_USAGE_FK1 FOREIGN KEY (FORM_BUILDER_ID) REFERENCES form_builder_header (FORM_BUILDER_ID)
);

DROP TABLE IF EXISTS COI_REVIEW_ACTIVITY;
CREATE TABLE COI_REVIEW_ACTIVITY (
  COI_REVIEW_ACTIVITY_ID varchar(3) NOT NULL,
  DESCRIPTION varchar(2000) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  PRIMARY KEY (COI_REVIEW_ACTIVITY_ID)
);

DROP TABLE IF EXISTS COI_REVIEW_ASSIGNEE_HISTORY;
CREATE TABLE COI_REVIEW_ASSIGNEE_HISTORY (
  COI_REVIEW_ASSIGNEE_HISTORY_ID int NOT NULL AUTO_INCREMENT,
  COI_REVIEW_ID int NOT NULL,
  ASSIGNEE_TYPE varchar(1) NOT NULL,
  ASSIGNEE_PERSON_ID varchar(40) DEFAULT NULL,
  ADMIN_GROUP_ID int DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  COI_REVIEW_ACTIVITY_ID varchar(3) DEFAULT NULL,
  PRIMARY KEY (COI_REVIEW_ASSIGNEE_HISTORY_ID),
  KEY COI_REVIEW_ASSIGNEE_HST_FK1 (COI_REVIEW_ID),
  CONSTRAINT COI_REVIEW_ASSIGNEE_HST_FK1 FOREIGN KEY (COI_REVIEW_ID) REFERENCES coi_review (COI_REVIEW_ID)
);

DROP TABLE IF EXISTS COI_REVIEW_COMMENT_ATTACHMENT;
CREATE TABLE COI_REVIEW_COMMENT_ATTACHMENT (
  COI_REVIEW_COMMENT_ATT_ID int NOT NULL AUTO_INCREMENT,
  COI_REVIEW_COMMENT_ID int NOT NULL,
  COI_REVIEW_ID int DEFAULT NULL,
  FILE_NAME varchar(255) DEFAULT NULL,
  MIME_TYPE varchar(255) DEFAULT NULL,
  FILE_DATA_ID varchar(40) NOT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  PRIMARY KEY (COI_REVIEW_COMMENT_ATT_ID),
  KEY COI_REVIEW_COMMENT_ATTACHMENT_FK1 (COI_REVIEW_ID),
  KEY COI_REVIEW_COMMENT_ATTACHMENT_FK2 (COI_REVIEW_COMMENT_ID),
  KEY COI_REVIEW_COMMENT_ATTACHMENT_FK3 (FILE_DATA_ID),
  CONSTRAINT COI_REVIEW_COMMENT_ATTACHMENT_FK1 FOREIGN KEY (COI_REVIEW_ID) REFERENCES coi_review (COI_REVIEW_ID),
  CONSTRAINT COI_REVIEW_COMMENT_ATTACHMENT_FK2 FOREIGN KEY (COI_REVIEW_COMMENT_ID) REFERENCES coi_review_comment (COI_REVIEW_COMMENT_ID),
  CONSTRAINT COI_REVIEW_COMMENT_ATTACHMENT_FK3 FOREIGN KEY (FILE_DATA_ID) REFERENCES coi_file_data (FILE_DATA_ID)
);

DROP TABLE IF EXISTS COI_SECTIONS_TYPE;
CREATE TABLE COI_SECTIONS_TYPE (
  COI_SECTIONS_TYPE_CODE varchar(3) NOT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL,
  UPDATE_TIMESTAMP datetime DEFAULT NULL,
  UPDATE_USER varchar(60) DEFAULT NULL,
  IS_ACTIVE varchar(1) DEFAULT 'Y',
  PRIMARY KEY (COI_SECTIONS_TYPE_CODE)
);

DROP TABLE IF EXISTS COI_FILE_DATA;
CREATE TABLE COI_FILE_DATA (
  FILE_DATA_ID varchar(40) NOT NULL,
  DATA longblob,
  PRIMARY KEY (FILE_DATA_ID)
);

SET FOREIGN_KEY_CHECKS=1;

