 -- ALTER TABLE `quest_question` ADD COLUMN `FOOTER_DESCRIPTION` TEXT NULL;

-- ALTER TABLE `INBOX` ADD COLUMN `ALERT_TYPE` VARCHAR(45) NULL;
-- ALTER TABLE `INBOX` ADD COLUMN `EXPIRATION_DATE` DATETIME NULL;

-- ALTER TABLE `REMINDER_NOTIFICATION` ADD COLUMN `REMINDER_TYPE_FLAG` VARCHAR(3) NULL AFTER `PLACEHOLDER_VALUES`;

-- cross check with base script and execute the above queries

UPDATE coi_project_proposal
SET EXTERNAL_SYSTEM_REF_ID = PROPOSAL_NUMBER WHERE EXTERNAL_SYSTEM_REF_ID is null;

UPDATE coi_project_award
SET EXTERNAL_SYSTEM_REF_ID = AWARD_NUMBER WHERE EXTERNAL_SYSTEM_REF_ID is null;

ALTER TABLE `coi_project_proposal` 
CHANGE COLUMN `LEAD_UNIT_NAME` `LEAD_UNIT_NAME` VARCHAR(200) NULL DEFAULT NULL ;

ALTER TABLE `coi_project_award` 
CHANGE COLUMN `LEAD_UNIT_NAME` `LEAD_UNIT_NAME` VARCHAR(200) NULL DEFAULT NULL ;