DROP FUNCTION IF EXISTS COI_INT_PRSN_DISCL_EXP_DATE;
DROP PROCEDURE IF EXISTS COI_INT_PROJECT_PRSN_DISCL_STATUS;
DROP PROCEDURE IF EXISTS ENRICH_ENTITY_INDUSTRY_CATE;
DROP PROCEDURE IF EXISTS ENRICH_ENTITY_REGISTRATION;
DROP PROCEDURE IF EXISTS ENRICH_ENTITY_TELEPHONE;
DROP PROCEDURE IF EXISTS ENRICH_TRADE_STYLE_NAME;