DELIMITER //
CREATE PROCEDURE `GET_COI_DISCL_GENERAL_DETAILS` (
	AV_COLUMN_NAMES           	VARCHAR(4000),
    AV_MODULE_ITEM_KEY         	INT,
	AV_SUB_MODULE_ITEM_KEY      INT
)
BEGIN

DECLARE LS_DYN_SQL 					LONGTEXT;

SET LS_DYN_SQL = CONCAT('SELECT ', AV_COLUMN_NAMES, ' FROM
	(SELECT t1.DISCLOSURE_NUMBER, t1.EXPIRATION_DATE, t1.CERTIFIED_AT AS CERTIFICATION_DATE, t4.DESCRIPTION AS REVIEW_STATUS,
	t3.UNIT_NAME AS DEPARTMENT_NAME, t1.HOME_UNIT AS DEPARTMENT_NUMBER, t2.FULL_NAME AS REPORTER_NAME, t5.DESCRIPTION AS DISCLOSURE_STATUS,
	CASE
        WHEN t5.PROPOSAL_TITLES IS NOT NULL THEN t5.PROPOSAL_TITLES
        ELSE t6.AWARD_TITLES
    END AS PROJECT_TITLE,
	CASE
        WHEN t5.PROPOSAL_ID IS NOT NULL THEN t5.PROPOSAL_ID
        ELSE t6.AWARD_NUMBER
    END AS PROJECT_NUMBER,
	t7.DESCRIPTION AS PROJECT_TYPE, t8.FULL_NAME AS ADMINISTRATOR_NAME
	FROM COI_DISCLOSURE t1
	INNER JOIN PERSON t2 ON t2.PERSON_ID=t1.PERSON_ID
	INNER JOIN UNIT t3 ON t3.UNIT_NUMBER = t1.HOME_UNIT
	INNER JOIN COI_REVIEW_STATUS_TYPE t4 ON t4.REVIEW_STATUS_CODE = t1.REVIEW_STATUS_CODE
	LEFT JOIN COI_CONFLICT_STATUS_TYPE t5 ON t5.CONFLICT_STATUS_CODE=t1.CONFLICT_STATUS_CODE
	LEFT JOIN (SELECT EXTERNAL_SYSTEM_REF_ID AS PROPOSAL_ID,
	TITLE  AS PROPOSAL_TITLES, EXTERNAL_SYSTEM_REF_ID FROM COI_PROJECT_PROPOSAL_V ) t5 ON t5.EXTERNAL_SYSTEM_REF_ID = t1.MODULE_ITEM_KEY
	LEFT  JOIN (SELECT AWARD_NUMBER, EXTERNAL_SYSTEM_REF_ID,
	TITLE AS AWARD_TITLES FROM COI_PROJECT_AWARD_V )t6  ON t6.EXTERNAL_SYSTEM_REF_ID = t1.MODULE_ITEM_KEY
	INNER JOIN COI_DISCLOSURE_FCOI_TYPE t7 ON t7.FCOI_TYPE_CODE = t1.FCOI_TYPE_CODE
	LEFT JOIN PERSON t8 ON t8.PERSON_ID = t1.ADMIN_PERSON_ID
	WHERE t1.DISCLOSURE_ID = ', AV_MODULE_ITEM_KEY, ') T');

SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
END
//
