
set foreign_key_checks = 0;

DROP TABLE IF EXISTS QUEST_ANSWER_DELETE_LOG;
CREATE TABLE `QUEST_ANSWER_DELETE_LOG` (
  `LOG_ID` int NOT NULL AUTO_INCREMENT,
  `QUESTIONNAIRE_ID` int DEFAULT NULL,
  `QUESTIONNAIRE_NUMBER` int DEFAULT NULL,
  `MODULE_CODE` int DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(20) DEFAULT NULL,
  `SUB_MODULE_CODE` int DEFAULT NULL,
  `SUB_MODULE_ITEM_KEY` varchar(20) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`)
);

set foreign_key_checks = 1;
