DROP PROCEDURE IF EXISTS COI_COPY_GLOBAL_ENTITY;
DROP PROCEDURE IF EXISTS COI_INT_GET_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS COI_INT_GET_ORGANIZATION_DETAILS;
DROP PROCEDURE IF EXISTS COI_INT_GET_SPONSOR_DETAILS;
DROP PROCEDURE IF EXISTS GET_ENTITY_TAB_STATUS;
DROP PROCEDURE IF EXISTS VALIDATE_ENTITY_MANDATORY_FIELDS;
