
CREATE TABLE COI_INT_STAGE_AWARD (
  STAGE_AWARD_ID int NOT NULL AUTO_INCREMENT,
  PROJECT_ID varchar(12) NOT NULL,
  PROJECT_NUMBER varchar(12) NOT NULL,
  PARENT_PROJECT_NUMBER varchar(12) DEFAULT NULL,
  ROOT_PROJECT_NUMBER varchar(12) DEFAULT NULL,
  VERSION_NUMBER int NOT NULL,
  ACCOUNT_NUMBER varchar(100) DEFAULT NULL,
  SPONSOR_GRANT_NUMBER varchar(70) DEFAULT NULL,
  LEAD_UNIT_NUMBER varchar(8) DEFAULT NULL,
  LEAD_UNIT_NAME varchar(200) DEFAULT NULL,
  PROJECT_START_DATE date DEFAULT NULL,
  PROJECT_END_DATE date DEFAULT NULL,
  PROJECT_TYPE_CODE varchar(8) DEFAULT NULL,
  PROJECT_TYPE varchar(100) DEFAULT NULL,
  TITLE varchar(1000) DEFAULT NULL,
  PROJECT_STATUS_CODE VARCHAR(12) DEFAULT NULL,
  PROJECT_STATUS varchar(100) DEFAULT NULL,
  SPONSOR_CODE varchar(10) DEFAULT NULL,
  SPONSOR_NAME varchar(200) DEFAULT NULL,
  PRIME_SPONSOR_CODE varchar(10) DEFAULT NULL,
  PRIME_SPONSOR_NAME varchar(200) DEFAULT NULL,
  ANTICIPATED_TOTAL decimal(12,2) DEFAULT NULL,
  OBLIGATED_TOTAL decimal(12,2) DEFAULT NULL,
  DOCUMENT_URL text,
  FIRST_FED_TIMESTAMP datetime DEFAULT NULL,
  LAST_FED_TIMESTAMP datetime DEFAULT NULL,
  SRC_SYS_UPDATE_TIMESTAMP datetime DEFAULT NULL,
  SRC_SYS_UPDATED_BY varchar(40) DEFAULT NULL,
  ATTRIBUTE_1_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_1_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_4_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_4_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_5_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_5_VALUE varchar(255) DEFAULT NULL,
  PRIMARY KEY (STAGE_AWARD_ID),
  INDEX idx_project_number (PROJECT_NUMBER)  
);

CREATE TABLE COI_INT_STAGE_AWARD_PERSON (
  PROJECT_NUMBER varchar(12) NOT NULL,
  KEY_PERSON_ROLE_CODE int NOT NULL,
  KEY_PERSON_ROLE_NAME varchar(25) NOT NULL,
  KEY_PERSON_ID varchar(40) NOT NULL,
  KEY_PERSON_NAME varchar(90) DEFAULT NULL,
  STATUS varchar(1) DEFAULT NULL,
  PERCENT_OF_EFFORT decimal(5,2) DEFAULT NULL,
  ATTRIBUTE_1_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_1_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_VALUE varchar(255) DEFAULT NULL,
  INDEX idx_key_person_id (KEY_PERSON_ID),
  INDEX idx_project_number (PROJECT_NUMBER),
  PRIMARY KEY (`PROJECT_NUMBER`,`KEY_PERSON_ID`)
);

CREATE TABLE COI_INT_STAGE_PROPOSAL (
  STAGE_PROPOSAL_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PROJECT_ID varchar(12) NOT NULL,
  PROJECT_NUMBER varchar(12) NOT NULL,
  VERSION_NUMBER int NOT NULL,
  LINKED_AWARD_PROJECT_NUMBER varchar(12) DEFAULT NULL,
  SPONSOR_GRANT_NUMBER varchar(70) DEFAULT NULL,
  LEAD_UNIT_NUMBER varchar(8) DEFAULT NULL,
  LEAD_UNIT_NAME varchar(200) DEFAULT NULL,
  PROJECT_START_DATE date DEFAULT NULL,
  PROJECT_END_DATE date DEFAULT NULL,
  PROJECT_TYPE_CODE varchar(12) DEFAULT NULL, 
  PROJECT_TYPE varchar(100) DEFAULT NULL,
  TITLE varchar(1000) DEFAULT NULL,
  PROJECT_STATUS_CODE VARCHAR(12) DEFAULT NULL,
  PROJECT_STATUS varchar(100) DEFAULT NULL,
  SPONSOR_CODE varchar(10) DEFAULT NULL,
  SPONSOR_NAME varchar(200) DEFAULT NULL,
  PRIME_SPONSOR_CODE varchar(10) DEFAULT NULL,
  PRIME_SPONSOR_NAME varchar(200) DEFAULT NULL,
  DOCUMENT_URL text,
  FIRST_FED_TIMESTAMP datetime DEFAULT NULL,
  LAST_FED_TIMESTAMP datetime DEFAULT NULL,
  SRC_SYS_UPDATE_TIMESTAMP datetime DEFAULT NULL,
  SRC_SYS_UPDATED_BY varchar(40) DEFAULT NULL,
  ATTRIBUTE_1_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_1_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_4_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_4_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_5_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_5_VALUE varchar(255) DEFAULT NULL,
  INDEX idx_project_number (PROJECT_NUMBER)
);

CREATE TABLE coi_int_stage_proposal_person (
  PROJECT_NUMBER varchar(12) NOT NULL,
  KEY_PERSON_ROLE_CODE int NOT NULL,
  KEY_PERSON_ROLE_NAME varchar(25) NOT NULL,
  KEY_PERSON_ID varchar(40) NOT NULL,
  KEY_PERSON_NAME varchar(90) DEFAULT NULL,
  STATUS varchar(1) DEFAULT NULL,
  PERCENT_OF_EFFORT decimal(5,2) DEFAULT NULL,
  ATTRIBUTE_1_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_1_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_VALUE varchar(255) DEFAULT NULL,
  INDEX idx_key_person_id (KEY_PERSON_ID),
  INDEX idx_project_number (PROJECT_NUMBER),
  PRIMARY KEY (`PROJECT_NUMBER`,`KEY_PERSON_ID`)
);

CREATE TABLE USER_TOKENS (
  ID bigint NOT NULL AUTO_INCREMENT,
  USER_NAME varchar(255) DEFAULT NULL,
  PASSWORD varchar(255) DEFAULT NULL,
  ACCESS_TOKEN text,
  SALT varchar(255) DEFAULT NULL,
  UPDATE_TIMESTAMP timestamp NULL DEFAULT NULL,
  PERSON_ID varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
);

/*-- Oracle scripts

DROP TABLE USER_TOKENS CASCADE CONSTRAINTS;

DROP SEQUENCE user_tokens_seq;

CREATE SEQUENCE user_tokens_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE TABLE USER_TOKENS (
    ID NUMBER(19, 0) PRIMARY KEY,
    USER_NAME VARCHAR2(500 CHAR) NOT NULL,
    PASSWORD VARCHAR2(500 CHAR) NOT NULL,
    ACCESS_TOKEN CLOB,
    SALT VARCHAR2(500 CHAR) NOT NULL,
    PERSON_ID VARCHAR2(50 CHAR),
    UPDATE_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TRIGGER user_tokens_bi
BEFORE INSERT ON USER_TOKENS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT user_tokens_seq.NEXTVAL INTO :NEW.ID FROM dual;
    END IF;
END;

ALTER TABLE SPONSOR 
ADD (ENTITY_ID NUMBER(6,0));

ALTER TABLE ORGANIZATION 
ADD (ENTITY_ID NUMBER(6,0));

*/
