ALTER TABLE NOTES 
CHANGE COLUMN UPDATE_USER UPDATED_BY VARCHAR(60) NULL DEFAULT NULL ;

SET SQL_SAFE_UPDATES = 0;
UPDATE NOTES N
JOIN PERSON P ON N.UPDATED_BY = P.USER_NAME
SET N.UPDATED_BY = P.PERSON_ID;
SET SQL_SAFE_UPDATES = 1;
