\. ./FIBI-COI-5.1.4/FC-1165-CITI-TRAINING/Procedures/MIGRATE_PERSON_TRAINING.sql
\. ./FIBI-COI-5.1.4/FC-1165-CITI-TRAINING/Procedures/GET_TRAINING_DASHBOARD.sql

\. ./FIBI-COI-5.1.4/FC-1165-CITI-TRAINING/Functions/FN_GET_TRAINING_MODULE.sql
\. ./FIBI-COI-5.1.4/FC-1165-CITI-TRAINING/Functions/FN_MAP_TRAINING_TYPE.sql
