CREATE OR REPLACE PROCEDURE FIBI_COI_FEED_ENTITY_SPONSOR(
AV_SPONCOR_CODE            IN VARCHAR2,
AV_ENTITY_ID 			   IN NUMBER,
AV_ROLODEX_ID 			   IN NUMBER,
IS_SPONSOR_SYNC_FLAG       IN VARCHAR2,
AV_PRIMARY_NAME       	   IN VARCHAR2,
AV_SPON_ADDRESS_LINE_1     IN VARCHAR2, 
AV_SPON_ADDRESS_LINE_2     IN VARCHAR2,
AV_SPON_CITY               IN VARCHAR2,
AV_SPON_STATE              IN VARCHAR2,
AV_SPON_POSTAL_CODE   	   IN VARCHAR2,
AV_SPON_COUNTRY_CODE   	   IN VARCHAR2,
AV_EMAIL_ADDRESS           IN VARCHAR2,
AV_TELEPHONE_NUMBER        IN VARCHAR2,
AV_UPDATE_BY    		   IN VARCHAR2,
AV_SPONSOR_TYPE_CODE       IN VARCHAR2,
AV_CUSTOMER_NUMBER		   IN VARCHAR2,
AV_AUDIT_REPORT_SENT 	   IN VARCHAR2,
AV_UEI					   IN VARCHAR2,
AV_DODAC_NUMBER 		   IN VARCHAR2,
AV_DUNS_NUMBER 			   IN VARCHAR2,
AV_ACRONYM 				   IN VARCHAR2,
AV_CAGE_NUMBER 			   IN VARCHAR2,
AV_DUNNING_CAMPAIGN_ID 	   IN VARCHAR2,
AV_COMMENTS          	   IN VARCHAR2,
cur_generic  			   OUT SYS_REFCURSOR
) IS
LI_ROL_CNT 					INT;
LI_SPONSOR_CNT				INT;
LI_ORG_CNT 					INT;
LI_SEQ_ROLODEX_ID 			ROLODEX.ROLODEX_ID%TYPE           		 := '';
LI_SPON_SEQ_ROLODEX_ID      ROLODEX.ROLODEX_ID%TYPE           		 := NULL;
LI_SEQ_SPONSOR_CODE 		SPONSOR.SPONSOR_CODE%TYPE         		 := NULL;
LS_UPDATE_USER 				PERSON.USER_NAME%TYPE;
LS_LAST_NAME  				ROLODEX.LAST_NAME%TYPE            		 := NULL;
LS_FIRST_NAME  				ROLODEX.FIRST_NAME%TYPE           		 := NULL;
LS_MIDDLE_NAME  			ROLODEX.MIDDLE_NAME%TYPE          		 := NULL;
LS_ADDRESS_LINE_3 			ROLODEX.ADDRESS_LINE_3%TYPE       		 := NULL;
LS_COUNTY 					ROLODEX.COUNTY%TYPE               		 := NULL;
LS_OWNED_BY_UNIT 			ROLODEX.OWNED_BY_UNIT%TYPE        		 := '000001';
LS_COMMENTS 				ROLODEX.COMMENTS%TYPE             		 := 'Sponsor Base Address';
LS_SPONSOR_ADDRESS_FLAG 	ROLODEX.SPONSOR_ADDRESS_FLAG%TYPE        := 'Y';
LI_VER_NBR 					CHAR(1)                          		 := '1';
LS_ACTV_IND 				CHAR(1)            				  		 := 'Y';
LS_ORG_ERROR_MESGE 			VARCHAR2(4000)						     := NULL;
LS_SPONSOR_ERROR_MESGE 		VARCHAR2(4000)						     := NULL;
LS_PERSON_ERROR             VARCHAR2(4000);
LS_ADDRESS                  VARCHAR2(4000)   := AV_SPON_ADDRESS_LINE_1||AV_SPON_CITY||','||AV_SPON_STATE||','||AV_SPON_POSTAL_CODE||','||AV_SPON_COUNTRY_CODE;

BEGIN
	BEGIN

		SELECT USER_NAME INTO LS_UPDATE_USER
			FROM PERSON 
			WHERE PERSON_ID = AV_UPDATE_BY; 
            
        IF LS_UPDATE_USER IS NULL THEN 
            LS_UPDATE_USER := 'KCSO';
        END IF;

        EXCEPTION
		WHEN OTHERS THEN
			LS_UPDATE_USER := AV_UPDATE_BY;
			LS_PERSON_ERROR := 'Error fetching update user: ' || SQLERRM;
		END;	

	    BEGIN
	           LS_ADDRESS := SUBSTR(LS_ADDRESS,1,60);

            IF (UPPER(IS_SPONSOR_SYNC_FLAG) = 'TRUE' OR IS_SPONSOR_SYNC_FLAG = 1) THEN

                BEGIN

                    IF AV_SPONCOR_CODE IS NULL THEN

                       SELECT SEQ_ROLODEX_ID.NEXTVAL INTO LI_SPON_SEQ_ROLODEX_ID FROM dual;

                        INSERT INTO ROLODEX(ROLODEX_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, ORGANIZATION, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, EMAIL_ADDRESS, CITY, COUNTY, STATE, POSTAL_CODE, COMMENTS, PHONE_NUMBER, COUNTRY_CODE, SPONSOR_CODE, OWNED_BY_UNIT, SPONSOR_ADDRESS_FLAG, CREATE_USER, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID, ACTV_IND)
                        VALUES (LI_SPON_SEQ_ROLODEX_ID, LS_LAST_NAME, LS_FIRST_NAME, LS_MIDDLE_NAME, AV_PRIMARY_NAME, AV_SPON_ADDRESS_LINE_1, AV_SPON_ADDRESS_LINE_2, LS_ADDRESS_LINE_3, AV_EMAIL_ADDRESS, AV_SPON_CITY, LS_COUNTY, AV_SPON_STATE, AV_SPON_POSTAL_CODE, AV_COMMENTS, AV_TELEPHONE_NUMBER, AV_SPON_COUNTRY_CODE, LI_SEQ_SPONSOR_CODE, LS_OWNED_BY_UNIT, LS_SPONSOR_ADDRESS_FLAG,
                        LS_UPDATE_USER, SYSDATE, LS_UPDATE_USER, LI_VER_NBR, SYS_GUID(), LS_ACTV_IND);

                     SELECT SEQ_SPONSOR_CODE.NEXTVAL INTO LI_SEQ_SPONSOR_CODE FROM dual;
                        INSERT INTO SPONSOR (SPONSOR_CODE, SPONSOR_NAME, ACRONYM, SPONSOR_TYPE_CODE, DUN_AND_BRADSTREET_NUMBER, DODAC_NUMBER, CAGE_NUMBER, POSTAL_CODE, STATE, COUNTRY_CODE, ROLODEX_ID, AUDIT_REPORT_SENT_FOR_FY, OWNED_BY_UNIT, CREATE_USER, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID, ACTV_IND, DUNNING_CAMPAIGN_ID, CUSTOMER_NUMBER, UEI, ENTITY_ID)
                        VALUES (LI_SEQ_SPONSOR_CODE, AV_PRIMARY_NAME, AV_ACRONYM, AV_SPONSOR_TYPE_CODE, AV_DUNS_NUMBER, AV_DODAC_NUMBER, AV_CAGE_NUMBER, AV_SPON_POSTAL_CODE, AV_SPON_STATE, AV_SPON_COUNTRY_CODE, LI_SPON_SEQ_ROLODEX_ID, AV_AUDIT_REPORT_SENT, LS_OWNED_BY_UNIT, LS_UPDATE_USER, SYSDATE, LS_UPDATE_USER, LI_VER_NBR, SYS_GUID(), LS_ACTV_IND, AV_DUNNING_CAMPAIGN_ID, AV_CUSTOMER_NUMBER, AV_UEI, AV_ENTITY_ID);


                        UPDATE ROLODEX SET SPONSOR_CODE = LI_SEQ_SPONSOR_CODE WHERE ROLODEX_ID = LI_SPON_SEQ_ROLODEX_ID;


                    ELSE

                        SELECT ROLODEX_ID INTO LI_SPON_SEQ_ROLODEX_ID
                        FROM SPONSOR
                        WHERE SPONSOR_CODE = AV_SPONCOR_CODE
                        AND ROLODEX_ID IS NOT NULL;

                        UPDATE ROLODEX SET LAST_NAME = LS_LAST_NAME, FIRST_NAME = LS_FIRST_NAME, MIDDLE_NAME = LS_MIDDLE_NAME, ORGANIZATION = AV_PRIMARY_NAME,
                        ADDRESS_LINE_1 = AV_SPON_ADDRESS_LINE_1, ADDRESS_LINE_2 = AV_SPON_ADDRESS_LINE_2, ADDRESS_LINE_3 = LS_ADDRESS_LINE_3, EMAIL_ADDRESS = AV_EMAIL_ADDRESS, CITY = AV_SPON_CITY,
                        COUNTY = LS_COUNTY, STATE = AV_SPON_STATE, POSTAL_CODE = AV_SPON_POSTAL_CODE, COMMENTS = AV_COMMENTS, PHONE_NUMBER = AV_TELEPHONE_NUMBER,
                        COUNTRY_CODE = AV_SPON_COUNTRY_CODE, SPONSOR_CODE = AV_SPONCOR_CODE, OWNED_BY_UNIT = LS_OWNED_BY_UNIT, SPONSOR_ADDRESS_FLAG = LS_SPONSOR_ADDRESS_FLAG,
                        CREATE_USER = LS_UPDATE_USER, UPDATE_TIMESTAMP = SYSDATE, UPDATE_USER = LS_UPDATE_USER, VER_NBR = LI_VER_NBR, OBJ_ID = SYS_GUID(), ACTV_IND = LS_ACTV_IND
                        WHERE ROLODEX_ID IN (LI_SPON_SEQ_ROLODEX_ID);

                        UPDATE SPONSOR SET SPONSOR_NAME = AV_PRIMARY_NAME, ACRONYM = AV_ACRONYM, SPONSOR_TYPE_CODE = AV_SPONSOR_TYPE_CODE, DUN_AND_BRADSTREET_NUMBER = AV_DUNS_NUMBER, DODAC_NUMBER = AV_DODAC_NUMBER, CAGE_NUMBER = AV_CAGE_NUMBER, POSTAL_CODE = AV_SPON_POSTAL_CODE, STATE = AV_SPON_STATE, COUNTRY_CODE = AV_SPON_COUNTRY_CODE, ROLODEX_ID = LI_SPON_SEQ_ROLODEX_ID, AUDIT_REPORT_SENT_FOR_FY = AV_AUDIT_REPORT_SENT, OWNED_BY_UNIT = LS_OWNED_BY_UNIT, CREATE_USER = LS_UPDATE_USER, UPDATE_TIMESTAMP = SYSDATE, UPDATE_USER = LS_UPDATE_USER, VER_NBR = LI_VER_NBR, OBJ_ID = SYS_GUID(), ACTV_IND = LS_ACTV_IND, DUNNING_CAMPAIGN_ID = AV_DUNNING_CAMPAIGN_ID, CUSTOMER_NUMBER = AV_CUSTOMER_NUMBER,UEI = AV_UEI, ENTITY_ID = AV_ENTITY_ID
                        WHERE SPONSOR_CODE = AV_SPONCOR_CODE;
                    END IF;

                    EXCEPTION
                    WHEN OTHERS THEN
                    LS_SPONSOR_ERROR_MESGE := 'Error during sponsor sync: ' || SQLERRM;
                END;
           END IF;
        END;

		IF LI_SEQ_SPONSOR_CODE IS NULL THEN 		
		    LI_SEQ_SPONSOR_CODE := AV_SPONCOR_CODE;
		END IF;


        IF (UPPER(IS_SPONSOR_SYNC_FLAG) = 'TRUE' OR IS_SPONSOR_SYNC_FLAG = 1) AND LS_SPONSOR_ERROR_MESGE IS NULL THEN 
		    LS_SPONSOR_ERROR_MESGE := 'SYNC_SUCCESS';
        ELSE 
            LI_SEQ_SPONSOR_CODE := NULL;
		END IF;

		OPEN CUR_GENERIC FOR SELECT LI_SEQ_SPONSOR_CODE AS SPONSOR_CODE,LS_SPONSOR_ERROR_MESGE AS SPONSOR_ERROR FROM DUAL;


END;

